# Zip files adjusts

In [1]:
# Download EMBRACE_TEC_maps_intersection_raw_files_2022_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [2]:
%pwd

'/content'

In [3]:
!ls

EMBRACE_TEC_maps_intersection_raw_files_2022_2024.zip  sample_data

In [4]:
!unzip 'EMBRACE_TEC_maps_intersection_raw_files_2022_2024.zip'

Archive:  EMBRACE_TEC_maps_intersection_raw_files_2022_2024.zip
  inflating: INPE0600.22I
  inflating: INPE0610.22I
  inflating: INPE0610.24I
  inflating: INPE0620.22I
  inflating: INPE0620.24I
  inflating: INPE0630.22I
  inflating: INPE0630.24I
  inflating: INPE0640.22I
  inflating: INPE0640.24I
  inflating: INPE0650.22I
  inflating: INPE0650.24I
  inflating: INPE0660.22I
  inflating: INPE0660.24I
  inflating: INPE0670.22I
  inflating: INPE0670.24I
  inflating: INPE0680.24I
  inflating: INPE0690.22I
  inflating: INPE0690.24I
  inflating: INPE0700.22I
  inflating: INPE0700.24I
  inflating: INPE0710.22I
  inflating: INPE0710.24I
  inflating: INPE0720.24I
  inflating: INPE0730.22I
  inflating: INPE0730.24I
  inflating: INPE0740.22I
  inflating: INPE0740.24I
  inflating: INPE0750.22I
  inflating: INPE0750.24I
  inflating: INPE0760.22I
  inflating: INPE0760.24I
  inflating: INPE0770.22I
  inflating: INPE0770.24I
  inflating: INPE0780.22I
  inflating: INPE0780.24I
  inflating: INPE0790.22I
  inflating: INPE0790.24I
  inflating: INPE0800.22I
  inflating: INPE0800.24I
  inflating: INPE0810.22I
  inflating: INPE0810.24I
  inflating: INPE0820.22I
  inflating: INPE0830.22I
  inflating: INPE0840.22I
  inflating: INPE0850.22I
  inflating: INPE0860.22I
  inflating: INPE0860.24I
  inflating: INPE0870.24I
  inflating: INPE0880.24I
  inflating: INPE0890.24I
  inflating: INPE0900.22I
  inflating: INPE0910.24I
  inflating: INPE1520.22I
  inflating: INPE1530.22I
  inflating: INPE1530.24I
  inflating: INPE1540.22I
  inflating: INPE1540.24I
  inflating: INPE1550.24I
  inflating: INPE1560.22I
  inflating: INPE1560.24I
  inflating: INPE1570.22I
  inflating: INPE1570.24I
  inflating: INPE1580.22I
  inflating: INPE1580.24I
  inflating: INPE1590.22I
  inflating: INPE1590.24I
  inflating: INPE1600.22I
  inflating: INPE1600.24I
  inflating: INPE1610.22I
  inflating: INPE1610.24I
  inflating: INPE1620.22I
  inflating: INPE1620.24I
  inflating: INPE1630.22I
  inflating: INPE1630.24I
  inflating: INPE1640.22I
  inflating: INPE1640.24I
  inflating: INPE1650.22I
  inflating: INPE1650.24I
  inflating: INPE1660.22I
  inflating: INPE1660.24I
  inflating: INPE1670.22I
  inflating: INPE1670.24I
  inflating: INPE1680.22I
  inflating: INPE1680.24I
  inflating: INPE1690.22I
  inflating: INPE1690.24I
  inflating: INPE1700.22I
  inflating: INPE1700.24I
  inflating: INPE1710.22I
  inflating: INPE1710.24I
  inflating: INPE1720.22I
  inflating: INPE1730.22I
  inflating: INPE1730.24I
  inflating: INPE1740.22I
  inflating: INPE1740.24I
  inflating: INPE1750.24I
  inflating: INPE1760.22I
  inflating: INPE1760.24I
  inflating: INPE1770.24I
  inflating: INPE1780.22I
  inflating: INPE1800.24I
  inflating: INPE1810.22I
  inflating: INPE1810.24I
  inflating: INPE2450.22I
  inflating: INPE2460.22I
  inflating: INPE2470.22I
  inflating: INPE2470.24I
  inflating: INPE2480.22I
  inflating: INPE2480.24I
  inflating: INPE2490.22I
  inflating: INPE2490.24I
  inflating: INPE2500.22I
  inflating: INPE2500.24I
  inflating: INPE2510.22I
  inflating: INPE2510.24I
  inflating: INPE2520.22I
  inflating: INPE2520.24I
  inflating: INPE2530.22I
  inflating: INPE2530.24I
  inflating: INPE2540.22I
  inflating: INPE2540.24I
  inflating: INPE2550.22I
  inflating: INPE2550.24I
  inflating: INPE2560.22I
  inflating: INPE2560.24I
  inflating: INPE2570.24I
  inflating: INPE2580.22I
  inflating: INPE2580.24I
  inflating: INPE2600.22I
  inflating: INPE2610.22I
  inflating: INPE2610.24I
  inflating: INPE2620.22I
  inflating: INPE2620.24I
  inflating: INPE2630.24I
  inflating: INPE2640.22I
  inflating: INPE2640.24I
  inflating: INPE2650.22I
  inflating: INPE2650.24I
  inflating: INPE2660.22I
  inflating: INPE2660.24I
  inflating: INPE2670.22I
  inflating: INPE2670.24I
  inflating: INPE2680.22I
  inflating: INPE2680.24I
  inflating: INPE2690.22I
  inflating: INPE2690.24I
  inflating: INPE2700.22I
  inflating: INPE2700.24I
  inflating: INPE2710.22I
  inflating: INPE2710.24I
  inflating: INPE2720.22I
  inflating: INPE2720.24I
  inflating: INPE2730.22I
  inflating: INPE2740.24I
  inflating: INPE3360.24I
  inflating: INPE3370.24I
  inflating: INPE3380.24I
  inflating: INPE3390.24I
  inflating: INPE3400.24I
  inflating: INPE3410.24I
  inflating: INPE3420.24I
  inflating: INPE3430.24I
  inflating: INPE3440.24I
  inflating: INPE3450.24I
  inflating: INPE3460.24I
  inflating: INPE3470.24I
  inflating: INPE3490.24I
  inflating: INPE3500.24I
  inflating: INPE3510.24I
  inflating: INPE3520.24I
  inflating: INPE3530.24I
  inflating: INPE3540.24I
  inflating: INPE3550.24I
  inflating: INPE3560.24I
  inflating: INPE3570.24I
  inflating: INPE3580.24I
  inflating: INPE3590.24I
  inflating: INPE3600.24I
  inflating: INPE3610.24I
  inflating: INPE3620.24I
  inflating: INPE3630.24I
  inflating: INPE3640.24I
  inflating: INPE3650.24I

# Data files adjusts

In [5]:
%pwd

'/content'

In [6]:
!ls

EMBRACE_TEC_maps_intersection_raw_files_2022_2024.zip  INPE1730.24I
INPE0600.22I					       INPE1740.22I
INPE0610.22I					       INPE1740.24I
INPE0610.24I					       INPE1750.24I
INPE0620.22I					       INPE1760.22I
INPE0620.24I					       INPE1760.24I
INPE0630.22I					       INPE1770.24I
INPE0630.24I					       INPE1780.22I
INPE0640.22I					       INPE1800.24I
INPE0640.24I					       INPE1810.22I
INPE0650.22I					       INPE1810.24I
INPE0650.24I					       INPE2450.22I
INPE0660.22I					       INPE2460.22I
INPE0660.24I					       INPE2470.22I
INPE0670.22I					       INPE2470.24I
INPE0670.24I					       INPE2480.22I
INPE0680.24I					       INPE2480.24I
INPE0690.22I					       INPE2490.22I
INPE0690.24I					       INPE2490.24I
INPE0700.22I					       INPE2500.22I
INPE0700.24I					       INPE2500.24I
INPE0710.22I					       INPE2510.22I
INPE0710.24I					       INPE2510.24I
INPE0720.24I					       INPE2520.22I
INPE0730.22I					       INPE2520.24I
INPE0730.24I					       INPE2530.22I
INPE0740.22I					       INPE2530.24I
INPE0740.24I					       INPE2540.22I
INPE0750.22I					       INPE2540.24I
INPE0750.24I					       INPE2550.22I
INPE0760.22I					       INPE2550.24I
INPE0760.24I					       INPE2560.22I
INPE0770.22I					       INPE2560.24I
INPE0770.24I					       INPE2570.24I
INPE0780.22I					       INPE2580.22I
INPE0780.24I					       INPE2580.24I
INPE0790.22I					       INPE2600.22I
INPE0790.24I					       INPE2610.22I
INPE0800.22I					       INPE2610.24I
INPE0800.24I					       INPE2620.22I
INPE0810.22I					       INPE2620.24I
INPE0810.24I					       INPE2630.24I
INPE0820.22I					       INPE2640.22I
INPE0830.22I					       INPE2640.24I
INPE0840.22I					       INPE2650.22I
INPE0850.22I					       INPE2650.24I
INPE0860.22I					       INPE2660.22I
INPE0860.24I					       INPE2660.24I
INPE0870.24I					       INPE2670.22I
INPE0880.24I					       INPE2670.24I
INPE0890.24I					       INPE2680.22I
INPE0900.22I					       INPE2680.24I
INPE0910.24I					       INPE2690.22I
INPE1520.22I					       INPE2690.24I
INPE1530.22I					       INPE2700.22I
INPE1530.24I					       INPE2700.24I
INPE1540.22I					       INPE2710.22I
INPE1540.24I					       INPE2710.24I
INPE1550.24I					       INPE2720.22I
INPE1560.22I					       INPE2720.24I
INPE1560.24I					       INPE2730.22I
INPE1570.22I					       INPE2740.24I
INPE1570.24I					       INPE3360.24I
INPE1580.22I					       INPE3370.24I
INPE1580.24I					       INPE3380.24I
INPE1590.22I					       INPE3390.24I
INPE1590.24I					       INPE3400.24I
INPE1600.22I					       INPE3410.24I
INPE1600.24I					       INPE3420.24I
INPE1610.22I					       INPE3430.24I
INPE1610.24I					       INPE3440.24I
INPE1620.22I					       INPE3450.24I
INPE1620.24I					       INPE3460.24I
INPE1630.22I					       INPE3470.24I
INPE1630.24I					       INPE3490.24I
INPE1640.22I					       INPE3500.24I
INPE1640.24I					       INPE3510.24I
INPE1650.22I					       INPE3520.24I
INPE1650.24I					       INPE3530.24I
INPE1660.22I					       INPE3540.24I
INPE1660.24I					       INPE3550.24I
INPE1670.22I					       INPE3560.24I
INPE1670.24I					       INPE3570.24I
INPE1680.22I					       INPE3580.24I
INPE1680.24I					       INPE3590.24I
INPE1690.22I					       INPE3600.24I
INPE1690.24I					       INPE3610.24I
INPE1700.22I					       INPE3620.24I
INPE1700.24I					       INPE3630.24I
INPE1710.22I					       INPE3640.24I
INPE1710.24I					       INPE3650.24I
INPE1720.22I					       sample_data
INPE1730.22I

## 2022

In [11]:
import os
import numpy as np

current_directory = './'

files_22i = []

for root, dirs, files in os.walk(current_directory):
    for file in files:
        if file.endswith(".22I") and file.startswith("INPE"):
            files_22i.append(os.path.join(root, file))

files_22i = sorted(files_22i)

print(files_22i)

print("Files .22i found (sorted):")
for file in files_22i:
    print(file)

for file_path_i in files_22i:

    data_list = []

    with open(file_path_i, 'r') as file:
        for line in file:

            if "LAT/LON1/LON2/DLON/H" in line:

                line1_values = list(map(float, file.readline().split()))
                line2_values = list(map(float, file.readline().split()))

                combined_values = line1_values + line2_values

                data_list.append(combined_values)

        data_array = np.array(data_list)

        file_name_without_extension = os.path.splitext(os.path.basename(file_path_i))[0]

        output_path_npy = os.path.join(os.path.dirname(file_path_i), f"{file_name_without_extension}_22.npy")

        elements_per_line = 41

        total_lines = data_array.shape[0] // elements_per_line

        new_shape = (total_lines, elements_per_line, data_array.shape[1])
        data_array = data_array[:total_lines * elements_per_line, :].reshape(new_shape)
        print(np.shape(data_array))
        data_array = data_array[:, :, :]
        print(np.shape(data_array))
        np.save(output_path_npy, data_array)

        print(f"Array saved in: {output_path_npy}")

['./INPE0600.22I', './INPE0610.22I', './INPE0620.22I', './INPE0630.22I', './INPE0640.22I', './INPE0650.22I', './INPE0660.22I', './INPE0670.22I', './INPE0690.22I', './INPE0700.22I', './INPE0710.22I', './INPE0730.22I', './INPE0740.22I', './INPE0750.22I', './INPE0760.22I', './INPE0770.22I', './INPE0780.22I', './INPE0790.22I', './INPE0800.22I', './INPE0810.22I', './INPE0820.22I', './INPE0830.22I', './INPE0840.22I', './INPE0850.22I', './INPE0860.22I', './INPE0900.22I', './INPE1520.22I', './INPE1530.22I', './INPE1540.22I', './INPE1560.22I', './INPE1570.22I', './INPE1580.22I', './INPE1590.22I', './INPE1600.22I', './INPE1610.22I', './INPE1620.22I', './INPE1630.22I', './INPE1640.22I', './INPE1650.22I', './INPE1660.22I', './INPE1670.22I', './INPE1680.22I', './INPE1690.22I', './INPE1700.22I', './INPE1710.22I', './INPE1720.22I', './INPE1730.22I', './INPE1740.22I', './INPE1760.22I', './INPE1780.22I', './INPE1810.22I', './INPE2450.22I', './INPE2460.22I', './INPE2470.22I', './INPE2480.22I', './INPE2490.22I', './INPE2500.22I', './INPE2510.22I', './INPE2520.22I', './INPE2530.22I', './INPE2540.22I', './INPE2550.22I', './INPE2560.22I', './INPE2580.22I', './INPE2600.22I', './INPE2610.22I', './INPE2620.22I', './INPE2640.22I', './INPE2650.22I', './INPE2660.22I', './INPE2670.22I', './INPE2680.22I', './INPE2690.22I', './INPE2700.22I', './INPE2710.22I', './INPE2720.22I', './INPE2730.22I']
Files .22i found (sorted):
./INPE0600.22I
./INPE0610.22I
./INPE0620.22I
./INPE0630.22I
./INPE0640.22I
./INPE0650.22I
./INPE0660.22I
./INPE0670.22I
./INPE0690.22I
./INPE0700.22I
./INPE0710.22I
./INPE0730.22I
./INPE0740.22I
./INPE0750.22I
./INPE0760.22I
./INPE0770.22I
./INPE0780.22I
./INPE0790.22I
./INPE0800.22I
./INPE0810.22I
./INPE0820.22I
./INPE0830.22I
./INPE0840.22I
./INPE0850.22I
./INPE0860.22I
./INPE0900.22I
./INPE1520.22I
./INPE1530.22I
./INPE1540.22I
./INPE1560.22I
./INPE1570.22I
./INPE1580.22I
./INPE1590.22I
./INPE1600.22I
./INPE1610.22I
./INPE1620.22I
./INPE1630.22I
./INPE1640.22I
./INPE1650.22I
./INPE1660.22I
./INPE1670.22I
./INPE1680.22I
./INPE1690.22I
./INPE1700.22I
./INPE1710.22I
./INPE1720.22I
./INPE1730.22I
./INPE1740.22I
./INPE1760.22I
./INPE1780.22I
./INPE1810.22I
./INPE2450.22I
./INPE2460.22I
./INPE2470.22I
./INPE2480.22I
./INPE2490.22I
./INPE2500.22I
./INPE2510.22I
./INPE2520.22I
./INPE2530.22I
./INPE2540.22I
./INPE2550.22I
./INPE2560.22I
./INPE2580.22I
./INPE2600.22I
./INPE2610.22I
./INPE2620.22I
./INPE2640.22I
./INPE2650.22I
./INPE2660.22I
./INPE2670.22I
./INPE2680.22I
./INPE2690.22I
./INPE2700.22I
./INPE2710.22I
./INPE2720.22I
./INPE2730.22I
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0600_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0610_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0620_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0630_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0640_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0650_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0660_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0670_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0690_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0700_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0710_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0730_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0740_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0750_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0760_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0770_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0780_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0790_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0800_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0810_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0820_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0830_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0840_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0850_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0860_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0900_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1520_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1530_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1540_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1560_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1570_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1580_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1590_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1600_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1610_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1620_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1630_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1640_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1650_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1660_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1670_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1680_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1690_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1700_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1710_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1720_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1730_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1740_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1760_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1780_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1810_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2450_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2460_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2470_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2480_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2490_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2500_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2510_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2520_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2530_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2540_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2550_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2560_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2580_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2600_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2610_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2620_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2640_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2650_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2660_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2670_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2680_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2690_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2700_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2710_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2720_22.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2730_22.npy

In [8]:
current_directory = './'

npy_files = [file for file in os.listdir(current_directory) if file.endswith('_22.npy')]
npy_files = sorted(npy_files)
print(npy_files)

if not npy_files:
    print("No .npy files found in the current directory.")
else:
    array_4d = np.empty((len(npy_files), 144, 41, 25))

    for i, file in enumerate(npy_files):
        file_path = os.path.join(current_directory, file)
        array_npy = np.load(file_path)
        array_4d[i, :, :, :] = array_npy

    array_4d = array_4d / 10

    print("\n\n")
    has_9999 = np.any(array_4d == 999.9)
    print(has_9999)
    count_9999 = np.sum(array_4d == 999.9)
    print(count_9999)
    print("\n\n")

    array_4d = np.where(array_4d == 999.9, np.nan, array_4d)
    has_nan = np.any(np.isnan(array_4d))
    print(has_nan)
    count_nan = np.sum(np.isnan(array_4d))
    print(count_nan)
    print("\n\n")

    has_9999 = np.any(array_4d == 999.9)
    print(has_9999)
    count_9999 = np.sum(array_4d == 999.9)
    print(count_9999)
    print("\n\n")

    np.save(os.path.join(current_directory, 'EMBRACE_TEC_maps_intersection_2022.npy'), array_4d)

    print(f"Processed {len(npy_files)} .npy files")
    print(f"Shape of the resulting array: {array_4d.shape}")

['INPE0600_22.npy', 'INPE0610_22.npy', 'INPE0620_22.npy', 'INPE0630_22.npy', 'INPE0640_22.npy', 'INPE0650_22.npy', 'INPE0660_22.npy', 'INPE0670_22.npy', 'INPE0690_22.npy', 'INPE0700_22.npy', 'INPE0710_22.npy', 'INPE0730_22.npy', 'INPE0740_22.npy', 'INPE0750_22.npy', 'INPE0760_22.npy', 'INPE0770_22.npy', 'INPE0780_22.npy', 'INPE0790_22.npy', 'INPE0800_22.npy', 'INPE0810_22.npy', 'INPE0820_22.npy', 'INPE0830_22.npy', 'INPE0840_22.npy', 'INPE0850_22.npy', 'INPE0860_22.npy', 'INPE0900_22.npy', 'INPE1520_22.npy', 'INPE1530_22.npy', 'INPE1540_22.npy', 'INPE1560_22.npy', 'INPE1570_22.npy', 'INPE1580_22.npy', 'INPE1590_22.npy', 'INPE1600_22.npy', 'INPE1610_22.npy', 'INPE1620_22.npy', 'INPE1630_22.npy', 'INPE1640_22.npy', 'INPE1650_22.npy', 'INPE1660_22.npy', 'INPE1670_22.npy', 'INPE1680_22.npy', 'INPE1690_22.npy', 'INPE1700_22.npy', 'INPE1710_22.npy', 'INPE1720_22.npy', 'INPE1730_22.npy', 'INPE1740_22.npy', 'INPE1760_22.npy', 'INPE1780_22.npy', 'INPE1810_22.npy', 'INPE2450_22.npy', 'INPE2460_22.npy', 'INPE2470_22.npy', 'INPE2480_22.npy', 'INPE2490_22.npy', 'INPE2500_22.npy', 'INPE2510_22.npy', 'INPE2520_22.npy', 'INPE2530_22.npy', 'INPE2540_22.npy', 'INPE2550_22.npy', 'INPE2560_22.npy', 'INPE2580_22.npy', 'INPE2600_22.npy', 'INPE2610_22.npy', 'INPE2620_22.npy', 'INPE2640_22.npy', 'INPE2650_22.npy', 'INPE2660_22.npy', 'INPE2670_22.npy', 'INPE2680_22.npy', 'INPE2690_22.npy', 'INPE2700_22.npy', 'INPE2710_22.npy', 'INPE2720_22.npy', 'INPE2730_22.npy']



True
6060919



True
6060919



False
0



Processed 77 .npy files
Shape of the resulting array: (77, 144, 41, 25)

## 2024

In [9]:
import os
import numpy as np

current_directory = './'

files_24i = []

for root, dirs, files in os.walk(current_directory):
    for file in files:
        if file.endswith(".24I") and file.startswith("INPE"):
            files_24i.append(os.path.join(root, file))

files_24i = sorted(files_24i)
print(files_24i)

print("Files .24i found (sorted):")
for file in files_24i:
    print(file)

for file_path_i in files_24i:

    data_list = []

    with open(file_path_i, 'r') as file:
        for line in file:

            if "LAT/LON1/LON2/DLON/H" in line:

                line1_values = list(map(float, file.readline().split()))
                line2_values = list(map(float, file.readline().split()))

                combined_values = line1_values + line2_values

                data_list.append(combined_values)

        data_array = np.array(data_list)

        file_name_without_extension = os.path.splitext(os.path.basename(file_path_i))[0]

        output_path_npy = os.path.join(os.path.dirname(file_path_i), f"{file_name_without_extension}_24.npy")

        elements_per_line = 41

        total_lines = data_array.shape[0] // elements_per_line

        new_shape = (total_lines, elements_per_line, data_array.shape[1])
        data_array = data_array[:total_lines * elements_per_line, :].reshape(new_shape)
        print(np.shape(data_array))
        data_array = data_array[:, :, :]
        print(np.shape(data_array))
        np.save(output_path_npy, data_array)

        print(f"Array saved in: {output_path_npy}")

['./INPE0610.24I', './INPE0620.24I', './INPE0630.24I', './INPE0640.24I', './INPE0650.24I', './INPE0660.24I', './INPE0670.24I', './INPE0680.24I', './INPE0690.24I', './INPE0700.24I', './INPE0710.24I', './INPE0720.24I', './INPE0730.24I', './INPE0740.24I', './INPE0750.24I', './INPE0760.24I', './INPE0770.24I', './INPE0780.24I', './INPE0790.24I', './INPE0800.24I', './INPE0810.24I', './INPE0860.24I', './INPE0870.24I', './INPE0880.24I', './INPE0890.24I', './INPE0910.24I', './INPE1530.24I', './INPE1540.24I', './INPE1550.24I', './INPE1560.24I', './INPE1570.24I', './INPE1580.24I', './INPE1590.24I', './INPE1600.24I', './INPE1610.24I', './INPE1620.24I', './INPE1630.24I', './INPE1640.24I', './INPE1650.24I', './INPE1660.24I', './INPE1670.24I', './INPE1680.24I', './INPE1690.24I', './INPE1700.24I', './INPE1710.24I', './INPE1730.24I', './INPE1740.24I', './INPE1750.24I', './INPE1760.24I', './INPE1770.24I', './INPE1800.24I', './INPE1810.24I', './INPE2470.24I', './INPE2480.24I', './INPE2490.24I', './INPE2500.24I', './INPE2510.24I', './INPE2520.24I', './INPE2530.24I', './INPE2540.24I', './INPE2550.24I', './INPE2560.24I', './INPE2570.24I', './INPE2580.24I', './INPE2610.24I', './INPE2620.24I', './INPE2630.24I', './INPE2640.24I', './INPE2650.24I', './INPE2660.24I', './INPE2670.24I', './INPE2680.24I', './INPE2690.24I', './INPE2700.24I', './INPE2710.24I', './INPE2720.24I', './INPE2740.24I', './INPE3360.24I', './INPE3370.24I', './INPE3380.24I', './INPE3390.24I', './INPE3400.24I', './INPE3410.24I', './INPE3420.24I', './INPE3430.24I', './INPE3440.24I', './INPE3450.24I', './INPE3460.24I', './INPE3470.24I', './INPE3490.24I', './INPE3500.24I', './INPE3510.24I', './INPE3520.24I', './INPE3530.24I', './INPE3540.24I', './INPE3550.24I', './INPE3560.24I', './INPE3570.24I', './INPE3580.24I', './INPE3590.24I', './INPE3600.24I', './INPE3610.24I', './INPE3620.24I', './INPE3630.24I', './INPE3640.24I', './INPE3650.24I']
Files .24i found (sorted):
./INPE0610.24I
./INPE0620.24I
./INPE0630.24I
./INPE0640.24I
./INPE0650.24I
./INPE0660.24I
./INPE0670.24I
./INPE0680.24I
./INPE0690.24I
./INPE0700.24I
./INPE0710.24I
./INPE0720.24I
./INPE0730.24I
./INPE0740.24I
./INPE0750.24I
./INPE0760.24I
./INPE0770.24I
./INPE0780.24I
./INPE0790.24I
./INPE0800.24I
./INPE0810.24I
./INPE0860.24I
./INPE0870.24I
./INPE0880.24I
./INPE0890.24I
./INPE0910.24I
./INPE1530.24I
./INPE1540.24I
./INPE1550.24I
./INPE1560.24I
./INPE1570.24I
./INPE1580.24I
./INPE1590.24I
./INPE1600.24I
./INPE1610.24I
./INPE1620.24I
./INPE1630.24I
./INPE1640.24I
./INPE1650.24I
./INPE1660.24I
./INPE1670.24I
./INPE1680.24I
./INPE1690.24I
./INPE1700.24I
./INPE1710.24I
./INPE1730.24I
./INPE1740.24I
./INPE1750.24I
./INPE1760.24I
./INPE1770.24I
./INPE1800.24I
./INPE1810.24I
./INPE2470.24I
./INPE2480.24I
./INPE2490.24I
./INPE2500.24I
./INPE2510.24I
./INPE2520.24I
./INPE2530.24I
./INPE2540.24I
./INPE2550.24I
./INPE2560.24I
./INPE2570.24I
./INPE2580.24I
./INPE2610.24I
./INPE2620.24I
./INPE2630.24I
./INPE2640.24I
./INPE2650.24I
./INPE2660.24I
./INPE2670.24I
./INPE2680.24I
./INPE2690.24I
./INPE2700.24I
./INPE2710.24I
./INPE2720.24I
./INPE2740.24I
./INPE3360.24I
./INPE3370.24I
./INPE3380.24I
./INPE3390.24I
./INPE3400.24I
./INPE3410.24I
./INPE3420.24I
./INPE3430.24I
./INPE3440.24I
./INPE3450.24I
./INPE3460.24I
./INPE3470.24I
./INPE3490.24I
./INPE3500.24I
./INPE3510.24I
./INPE3520.24I
./INPE3530.24I
./INPE3540.24I
./INPE3550.24I
./INPE3560.24I
./INPE3570.24I
./INPE3580.24I
./INPE3590.24I
./INPE3600.24I
./INPE3610.24I
./INPE3620.24I
./INPE3630.24I
./INPE3640.24I
./INPE3650.24I
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0610_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0620_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0630_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0640_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0650_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0660_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0670_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0680_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0690_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0700_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0710_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0720_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0730_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0740_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0750_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0760_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0770_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0780_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0790_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0800_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0810_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0860_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0870_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0880_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0890_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE0910_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1530_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1540_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1550_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1560_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1570_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1580_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1590_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1600_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1610_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1620_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1630_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1640_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1650_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1660_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1670_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1680_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1690_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1700_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1710_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1730_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1740_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1750_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1760_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1770_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1800_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE1810_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2470_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2480_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2490_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2500_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2510_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2520_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2530_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2540_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2550_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2560_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2570_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2580_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2610_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2620_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2630_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2640_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2650_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2660_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2670_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2680_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2690_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2700_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2710_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2720_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE2740_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3360_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3370_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3380_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3390_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3400_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3410_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3420_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3430_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3440_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3450_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3460_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3470_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3490_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3500_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3510_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3520_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3530_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3540_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3550_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3560_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3570_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3580_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3590_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3600_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3610_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3620_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3630_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3640_24.npy
(144, 41, 25)
(144, 41, 25)
Array saved in: ./INPE3650_24.npy

In [10]:
current_directory = './'

npy_files = [file for file in os.listdir(current_directory) if file.endswith('_24.npy')]
npy_files = sorted(npy_files)
print(npy_files)

if not npy_files:
    print("No .npy files found in the current directory.")
else:
    array_4d = np.empty((len(npy_files), 144, 41, 25))

    for i, file in enumerate(npy_files):
        file_path = os.path.join(current_directory, file)
        print(file_path)
        array_npy = np.load(file_path)
        print(i)
        array_4d[i, :, :, :] = array_npy

    array_4d = array_4d / 10

    print("\n\n")
    has_9999 = np.any(array_4d == 999.9)
    print(has_9999)
    count_9999 = np.sum(array_4d == 999.9)
    print(count_9999)
    print("\n\n")

    array_4d = np.where(array_4d == 999.9, np.nan, array_4d)
    has_nan = np.any(np.isnan(array_4d))
    print(has_nan)
    count_nan = np.sum(np.isnan(array_4d))
    print(count_nan)
    print("\n\n")

    has_9999 = np.any(array_4d == 999.9)
    print(has_9999)
    count_9999 = np.sum(array_4d == 999.9)
    print(count_9999)
    print("\n\n")

    np.save(os.path.join(current_directory, 'EMBRACE_TEC_maps_intersection_2024.npy'), array_4d)

    print(f"Processed {len(npy_files)} .npy files")
    print(f"Shape of the resulting array: {array_4d.shape}")

['INPE0610_24.npy', 'INPE0620_24.npy', 'INPE0630_24.npy', 'INPE0640_24.npy', 'INPE0650_24.npy', 'INPE0660_24.npy', 'INPE0670_24.npy', 'INPE0680_24.npy', 'INPE0690_24.npy', 'INPE0700_24.npy', 'INPE0710_24.npy', 'INPE0720_24.npy', 'INPE0730_24.npy', 'INPE0740_24.npy', 'INPE0750_24.npy', 'INPE0760_24.npy', 'INPE0770_24.npy', 'INPE0780_24.npy', 'INPE0790_24.npy', 'INPE0800_24.npy', 'INPE0810_24.npy', 'INPE0860_24.npy', 'INPE0870_24.npy', 'INPE0880_24.npy', 'INPE0890_24.npy', 'INPE0910_24.npy', 'INPE1530_24.npy', 'INPE1540_24.npy', 'INPE1550_24.npy', 'INPE1560_24.npy', 'INPE1570_24.npy', 'INPE1580_24.npy', 'INPE1590_24.npy', 'INPE1600_24.npy', 'INPE1610_24.npy', 'INPE1620_24.npy', 'INPE1630_24.npy', 'INPE1640_24.npy', 'INPE1650_24.npy', 'INPE1660_24.npy', 'INPE1670_24.npy', 'INPE1680_24.npy', 'INPE1690_24.npy', 'INPE1700_24.npy', 'INPE1710_24.npy', 'INPE1730_24.npy', 'INPE1740_24.npy', 'INPE1750_24.npy', 'INPE1760_24.npy', 'INPE1770_24.npy', 'INPE1800_24.npy', 'INPE1810_24.npy', 'INPE2470_24.npy', 'INPE2480_24.npy', 'INPE2490_24.npy', 'INPE2500_24.npy', 'INPE2510_24.npy', 'INPE2520_24.npy', 'INPE2530_24.npy', 'INPE2540_24.npy', 'INPE2550_24.npy', 'INPE2560_24.npy', 'INPE2570_24.npy', 'INPE2580_24.npy', 'INPE2610_24.npy', 'INPE2620_24.npy', 'INPE2630_24.npy', 'INPE2640_24.npy', 'INPE2650_24.npy', 'INPE2660_24.npy', 'INPE2670_24.npy', 'INPE2680_24.npy', 'INPE2690_24.npy', 'INPE2700_24.npy', 'INPE2710_24.npy', 'INPE2720_24.npy', 'INPE2740_24.npy', 'INPE3360_24.npy', 'INPE3370_24.npy', 'INPE3380_24.npy', 'INPE3390_24.npy', 'INPE3400_24.npy', 'INPE3410_24.npy', 'INPE3420_24.npy', 'INPE3430_24.npy', 'INPE3440_24.npy', 'INPE3450_24.npy', 'INPE3460_24.npy', 'INPE3470_24.npy', 'INPE3490_24.npy', 'INPE3500_24.npy', 'INPE3510_24.npy', 'INPE3520_24.npy', 'INPE3530_24.npy', 'INPE3540_24.npy', 'INPE3550_24.npy', 'INPE3560_24.npy', 'INPE3570_24.npy', 'INPE3580_24.npy', 'INPE3590_24.npy', 'INPE3600_24.npy', 'INPE3610_24.npy', 'INPE3620_24.npy', 'INPE3630_24.npy', 'INPE3640_24.npy', 'INPE3650_24.npy']
./INPE0610_24.npy
0
./INPE0620_24.npy
1
./INPE0630_24.npy
2
./INPE0640_24.npy
3
./INPE0650_24.npy
4
./INPE0660_24.npy
5
./INPE0670_24.npy
6
./INPE0680_24.npy
7
./INPE0690_24.npy
8
./INPE0700_24.npy
9
./INPE0710_24.npy
10
./INPE0720_24.npy
11
./INPE0730_24.npy
12
./INPE0740_24.npy
13
./INPE0750_24.npy
14
./INPE0760_24.npy
15
./INPE0770_24.npy
16
./INPE0780_24.npy
17
./INPE0790_24.npy
18
./INPE0800_24.npy
19
./INPE0810_24.npy
20
./INPE0860_24.npy
21
./INPE0870_24.npy
22
./INPE0880_24.npy
23
./INPE0890_24.npy
24
./INPE0910_24.npy
25
./INPE1530_24.npy
26
./INPE1540_24.npy
27
./INPE1550_24.npy
28
./INPE1560_24.npy
29
./INPE1570_24.npy
30
./INPE1580_24.npy
31
./INPE1590_24.npy
32
./INPE1600_24.npy
33
./INPE1610_24.npy
34
./INPE1620_24.npy
35
./INPE1630_24.npy
36
./INPE1640_24.npy
37
./INPE1650_24.npy
38
./INPE1660_24.npy
39
./INPE1670_24.npy
40
./INPE1680_24.npy
41
./INPE1690_24.npy
42
./INPE1700_24.npy
43
./INPE1710_24.npy
44
./INPE1730_24.npy
45
./INPE1740_24.npy
46
./INPE1750_24.npy
47
./INPE1760_24.npy
48
./INPE1770_24.npy
49
./INPE1800_24.npy
50
./INPE1810_24.npy
51
./INPE2470_24.npy
52
./INPE2480_24.npy
53
./INPE2490_24.npy
54
./INPE2500_24.npy
55
./INPE2510_24.npy
56
./INPE2520_24.npy
57
./INPE2530_24.npy
58
./INPE2540_24.npy
59
./INPE2550_24.npy
60
./INPE2560_24.npy
61
./INPE2570_24.npy
62
./INPE2580_24.npy
63
./INPE2610_24.npy
64
./INPE2620_24.npy
65
./INPE2630_24.npy
66
./INPE2640_24.npy
67
./INPE2650_24.npy
68
./INPE2660_24.npy
69
./INPE2670_24.npy
70
./INPE2680_24.npy
71
./INPE2690_24.npy
72
./INPE2700_24.npy
73
./INPE2710_24.npy
74
./INPE2720_24.npy
75
./INPE2740_24.npy
76
./INPE3360_24.npy
77
./INPE3370_24.npy
78
./INPE3380_24.npy
79
./INPE3390_24.npy
80
./INPE3400_24.npy
81
./INPE3410_24.npy
82
./INPE3420_24.npy
83
./INPE3430_24.npy
84
./INPE3440_24.npy
85
./INPE3450_24.npy
86
./INPE3460_24.npy
87
./INPE3470_24.npy
88
./INPE3490_24.npy
89
./INPE3500_24.npy
90
./INPE3510_24.npy
91
./INPE3520_24.npy
92
./INPE3530_24.npy
93
./INPE3540_24.npy
94
./INPE3550_24.npy
95
./INPE3560_24.npy
96
./INPE3570_24.npy
97
./INPE3580_24.npy
98
./INPE3590_24.npy
99
./INPE3600_24.npy
100
./INPE3610_24.npy
101
./INPE3620_24.npy
102
./INPE3630_24.npy
103
./INPE3640_24.npy
104
./INPE3650_24.npy
105



True
9910604



True
9910604



False
0



Processed 106 .npy files
Shape of the resulting array: (106, 144, 41, 25)

# 5D array - merge 2022-2024 data

In [12]:
%cd './'

/content

In [13]:
embrace_2022 = np.load('EMBRACE_TEC_maps_intersection_2022.npy').astype(np.float64)
print(np.shape(embrace_2022))
print(type(embrace_2022))
print(type(embrace_2022[0]))
print(type(embrace_2022[0][0]))
print(type(embrace_2022[0][0][0]))
print(type(embrace_2022[0][0][0][0]))

(77, 144, 41, 25)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>

In [14]:
embrace_2022

array([[[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       ...,


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]]])

In [15]:
embrace_2024 = np.load('EMBRACE_TEC_maps_intersection_2024.npy').astype(np.float64)
print(np.shape(embrace_2024))
print(type(embrace_2024))
print(type(embrace_2024[0]))
print(type(embrace_2024[0][0]))
print(type(embrace_2024[0][0][0]))
print(type(embrace_2024[0][0][0][0]))

(106, 144, 41, 25)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>

In [16]:
embrace_2022_2024 = np.concatenate([embrace_2022, embrace_2024], axis=0)
print(embrace_2022_2024.shape)

(183, 144, 41, 25)

In [17]:
print(type(embrace_2022_2024))
print(type(embrace_2022_2024[0]))
print(type(embrace_2022_2024[0][0]))
print(type(embrace_2022_2024[0][0][0]))
print(type(embrace_2022_2024[0][0][0][0]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>

In [18]:
for i in range(len(embrace_2022_2024)):
    print(np.shape(embrace_2022_2024[i]))

(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)
(144, 41, 25)

In [19]:
np.shape(embrace_2022_2024)

(183, 144, 41, 25)

In [20]:
has_9999 = np.any(embrace_2022_2024 == 999.9)
print(has_9999)

count_9999 = np.sum(embrace_2022_2024 == 999.9)
print(count_9999)

False
0

In [21]:
embrace_2022_2024 = np.where(embrace_2022_2024 == 999.9, np.nan, embrace_2022_2024)

has_nan = np.any(np.isnan(embrace_2022_2024))
print(has_nan)

count_nan = np.sum(np.isnan(embrace_2022_2024))
print(count_nan)

True
15971523

In [22]:
has_9999 = np.any(embrace_2022_2024 == 999.9)
print(has_9999)

count_9999 = np.sum(embrace_2022_2024 == 999.9)
print(count_9999)

False
0

In [23]:
%ls

EMBRACE_TEC_maps_intersection_2022.npy                 INPE1730.22I
EMBRACE_TEC_maps_intersection_2024.npy                 INPE1730_22.npy
EMBRACE_TEC_maps_intersection_raw_files_2022_2024.zip  INPE1730.24I
INPE0600.22I                                           INPE1730_24.npy
INPE0600_22.npy                                        INPE1740.22I
INPE0610.22I                                           INPE1740_22.npy
INPE0610_22.npy                                        INPE1740.24I
INPE0610.24I                                           INPE1740_24.npy
INPE0610_24.npy                                        INPE1750.24I
INPE0620.22I                                           INPE1750_24.npy
INPE0620_22.npy                                        INPE1760.22I
INPE0620.24I                                           INPE1760_22.npy
INPE0620_24.npy                                        INPE1760.24I
INPE0630.22I                                           INPE1760_24.npy
INPE0630_22.npy                                        INPE1770.24I
INPE0630.24I                                           INPE1770_24.npy
INPE0630_24.npy                                        INPE1780.22I
INPE0640.22I                                           INPE1780_22.npy
INPE0640_22.npy                                        INPE1800.24I
INPE0640.24I                                           INPE1800_24.npy
INPE0640_24.npy                                        INPE1810.22I
INPE0650.22I                                           INPE1810_22.npy
INPE0650_22.npy                                        INPE1810.24I
INPE0650.24I                                           INPE1810_24.npy
INPE0650_24.npy                                        INPE2450.22I
INPE0660.22I                                           INPE2450_22.npy
INPE0660_22.npy                                        INPE2460.22I
INPE0660.24I                                           INPE2460_22.npy
INPE0660_24.npy                                        INPE2470.22I
INPE0670.22I                                           INPE2470_22.npy
INPE0670_22.npy                                        INPE2470.24I
INPE0670.24I                                           INPE2470_24.npy
INPE0670_24.npy                                        INPE2480.22I
INPE0680.24I                                           INPE2480_22.npy
INPE0680_24.npy                                        INPE2480.24I
INPE0690.22I                                           INPE2480_24.npy
INPE0690_22.npy                                        INPE2490.22I
INPE0690.24I                                           INPE2490_22.npy
INPE0690_24.npy                                        INPE2490.24I
INPE0700.22I                                           INPE2490_24.npy
INPE0700_22.npy                                        INPE2500.22I
INPE0700.24I                                           INPE2500_22.npy
INPE0700_24.npy                                        INPE2500.24I
INPE0710.22I                                           INPE2500_24.npy
INPE0710_22.npy                                        INPE2510.22I
INPE0710.24I                                           INPE2510_22.npy
INPE0710_24.npy                                        INPE2510.24I
INPE0720.24I                                           INPE2510_24.npy
INPE0720_24.npy                                        INPE2520.22I
INPE0730.22I                                           INPE2520_22.npy
INPE0730_22.npy                                        INPE2520.24I
INPE0730.24I                                           INPE2520_24.npy
INPE0730_24.npy                                        INPE2530.22I
INPE0740.22I                                           INPE2530_22.npy
INPE0740_22.npy                                        INPE2530.24I
INPE0740.24I                                           INPE2530_24.npy
INPE0740_24.npy                                        INPE2540.22I
INPE0750.22I                                           INPE2540_22.npy
INPE0750_22.npy                                        INPE2540.24I
INPE0750.24I                                           INPE2540_24.npy
INPE0750_24.npy                                        INPE2550.22I
INPE0760.22I                                           INPE2550_22.npy
INPE0760_22.npy                                        INPE2550.24I
INPE0760.24I                                           INPE2550_24.npy
INPE0760_24.npy                                        INPE2560.22I
INPE0770.22I                                           INPE2560_22.npy
INPE0770_22.npy                                        INPE2560.24I
INPE0770.24I                                           INPE2560_24.npy
INPE0770_24.npy                                        INPE2570.24I
INPE0780.22I                                           INPE2570_24.npy
INPE0780_22.npy                                        INPE2580.22I
INPE0780.24I                                           INPE2580_22.npy
INPE0780_24.npy                                        INPE2580.24I
INPE0790.22I                                           INPE2580_24.npy
INPE0790_22.npy                                        INPE2600.22I
INPE0790.24I                                           INPE2600_22.npy
INPE0790_24.npy                                        INPE2610.22I
INPE0800.22I                                           INPE2610_22.npy
INPE0800_22.npy                                        INPE2610.24I
INPE0800.24I                                           INPE2610_24.npy
INPE0800_24.npy                                        INPE2620.22I
INPE0810.22I                                           INPE2620_22.npy
INPE0810_22.npy                                        INPE2620.24I
INPE0810.24I                                           INPE2620_24.npy
INPE0810_24.npy                                        INPE2630.24I
INPE0820.22I                                           INPE2630_24.npy
INPE0820_22.npy                                        INPE2640.22I
INPE0830.22I                                           INPE2640_22.npy
INPE0830_22.npy                                        INPE2640.24I
INPE0840.22I                                           INPE2640_24.npy
INPE0840_22.npy                                        INPE2650.22I
INPE0850.22I                                           INPE2650_22.npy
INPE0850_22.npy                                        INPE2650.24I
INPE0860.22I                                           INPE2650_24.npy
INPE0860_22.npy                                        INPE2660.22I
INPE0860.24I                                           INPE2660_22.npy
INPE0860_24.npy                                        INPE2660.24I
INPE0870.24I                                           INPE2660_24.npy
INPE0870_24.npy                                        INPE2670.22I
INPE0880.24I                                           INPE2670_22.npy
INPE0880_24.npy                                        INPE2670.24I
INPE0890.24I                                           INPE2670_24.npy
INPE0890_24.npy                                        INPE2680.22I
INPE0900.22I                                           INPE2680_22.npy
INPE0900_22.npy                                        INPE2680.24I
INPE0910.24I                                           INPE2680_24.npy
INPE0910_24.npy                                        INPE2690.22I
INPE1520.22I                                           INPE2690_22.npy
INPE1520_22.npy                                        INPE2690.24I
INPE1530.22I                                           INPE2690_24.npy
INPE1530_22.npy                                        INPE2700.22I
INPE1530.24I                                           INPE2700_22.npy
INPE1530_24.npy                                        INPE2700.24I
INPE1540.22I                                           INPE2700_24.npy
INPE1540_22.npy                                        INPE2710.22I
INPE1540.24I                                           INPE2710_22.npy
INPE1540_24.npy                                        INPE2710.24I
INPE1550.24I                                           INPE2710_24.npy
INPE1550_24.npy                                        INPE2720.22I
INPE1560.22I                                           INPE2720_22.npy
INPE1560_22.npy                                        INPE2720.24I
INPE1560.24I                                           INPE2720_24.npy
INPE1560_24.npy                                        INPE2730.22I
INPE1570.22I                                           INPE2730_22.npy
INPE1570_22.npy                                        INPE2740.24I
INPE1570.24I                                           INPE2740_24.npy
INPE1570_24.npy                                        INPE3360.24I
INPE1580.22I                                           INPE3360_24.npy
INPE1580_22.npy                                        INPE3370.24I
INPE1580.24I                                           INPE3370_24.npy
INPE1580_24.npy                                        INPE3380.24I
INPE1590.22I                                           INPE3380_24.npy
INPE1590_22.npy                                        INPE3390.24I
INPE1590.24I                                           INPE3390_24.npy
INPE1590_24.npy                                        INPE3400.24I
INPE1600.22I                                           INPE3400_24.npy
INPE1600_22.npy                                        INPE3410.24I
INPE1600.24I                                           INPE3410_24.npy
INPE1600_24.npy                                        INPE3420.24I
INPE1610.22I                                           INPE3420_24.npy
INPE1610_22.npy                                        INPE3430.24I
INPE1610.24I                                           INPE3430_24.npy
INPE1610_24.npy                                        INPE3440.24I
INPE1620.22I                                           INPE3440_24.npy
INPE1620_22.npy                                        INPE3450.24I
INPE1620.24I                                           INPE3450_24.npy
INPE1620_24.npy                                        INPE3460.24I
INPE1630.22I                                           INPE3460_24.npy
INPE1630_22.npy                                        INPE3470.24I
INPE1630.24I                                           INPE3470_24.npy
INPE1630_24.npy                                        INPE3490.24I
INPE1640.22I                                           INPE3490_24.npy
INPE1640_22.npy                                        INPE3500.24I
INPE1640.24I                                           INPE3500_24.npy
INPE1640_24.npy                                        INPE3510.24I
INPE1650.22I                                           INPE3510_24.npy
INPE1650_22.npy                                        INPE3520.24I
INPE1650.24I                                           INPE3520_24.npy
INPE1650_24.npy                                        INPE3530.24I
INPE1660.22I                                           INPE3530_24.npy
INPE1660_22.npy                                        INPE3540.24I
INPE1660.24I                                           INPE3540_24.npy
INPE1660_24.npy                                        INPE3550.24I
INPE1670.22I                                           INPE3550_24.npy
INPE1670_22.npy                                        INPE3560.24I
INPE1670.24I                                           INPE3560_24.npy
INPE1670_24.npy                                        INPE3570.24I
INPE1680.22I                                           INPE3570_24.npy
INPE1680_22.npy                                        INPE3580.24I
INPE1680.24I                                           INPE3580_24.npy
INPE1680_24.npy                                        INPE3590.24I
INPE1690.22I                                           INPE3590_24.npy
INPE1690_22.npy                                        INPE3600.24I
INPE1690.24I                                           INPE3600_24.npy
INPE1690_24.npy                                        INPE3610.24I
INPE1700.22I                                           INPE3610_24.npy
INPE1700_22.npy                                        INPE3620.24I
INPE1700.24I                                           INPE3620_24.npy
INPE1700_24.npy                                        INPE3630.24I
INPE1710.22I                                           INPE3630_24.npy
INPE1710_22.npy                                        INPE3640.24I
INPE1710.24I                                           INPE3640_24.npy
INPE1710_24.npy                                        INPE3650.24I
INPE1720.22I                                           INPE3650_24.npy
INPE1720_22.npy                                        sample_data/

In [24]:
embrace_2022_2024.shape

(183, 144, 41, 25)

In [25]:
np.set_printoptions(threshold=np.inf)

In [26]:
print(embrace_2022_2024[0][0])

[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan 17. 17. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 17. 17. 17. 18. 18. 14. 14. 14. 13. 13. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 17. 17. 17. 20. 18. 17. 14. 14. 14. 13. 12. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 17. 17. 17. 16. 17. 14. 14. 14. 15. 14. 12. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 17. 17. 18. 20. 18. 17. 16. 18. 16. 15. 13. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 18. 18. 19. 19. 19. 19. 17. 16. 16. 16. 14. 14. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 19. 19. 19. 16. 18. 17. 14. 15. 16. 15. nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 19. 19. 19. 18. 18. 19. 14. 15. 14. 14. 14. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 19. 20. 20. 20. 19. 19. 16. 15. 13. 12. 13. 14. nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 20. 20. 21. 20. 22. 19. 16. 14. 12. 11. 14. 14. nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 21. 20. 21. 20. 18. 18. 16. 15. 12. 14. 16. 15. 14.
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 22. 22. 20. 20. 20. 20. 20. 18. 17. 18. 16. 14. 14.
  14. nan nan nan nan nan nan]
 [nan nan nan nan nan 23. 22. 22. 23. 21. 22. 23. 22. 20. 19. 16. 14. 14.
  14. 14. nan nan nan nan nan]
 [nan nan nan nan nan 24. 25. 26. 28. 25. 25. 14. 23. 22. 20. 17. 13. 14.
  13. 14. nan nan nan nan nan]
 [nan nan nan nan nan 25. 27. 30. 13. 29. 32. 27. 27. 20. 22. 19. 16. 12.
  14. 14. 13. 13. nan nan nan]
 [nan nan nan nan nan 27. 27. 28. 20. 33. 31. 29. 27. 44. 20. 23. 19. 16.
  15. 13. 13. 12. nan nan nan]
 [nan nan nan nan nan nan 27. 24. 22. 33. 36. 33. 25. 22. 27. 26. 20. 19.
  16. 13. 12. 13. nan nan nan]
 [nan nan nan nan nan nan 29. 25. 18. 28. 36. 22. 13. 31. 31. 29. 26. 21.
  18. 14. 11. 13. 14. nan nan]
 [nan nan nan nan nan nan 31. 34. 15. 24. 26. 13. 11. 32. 34. 32. 31. 25.
  21. 18. 14. 14. 15. nan nan]
 [nan nan nan nan nan nan 32. 34. 28. 25. 25. 20. 12. 37. 43. 31. 32. 31.
  23. 20. 17. 16. 17. nan nan]
 [nan nan nan nan nan nan 32. 31. 28. 27. 27. 31. 40. 32. 40. 27. 33. 32.
  38. 21. 24. 19. 19. nan nan]
 [nan nan nan nan nan 27. 26. 26. 25. 23. 24. 35. 34. 45. 36. 23. 42. 47.
  27. 27. 21. 19. 24. nan nan]
 [nan nan nan nan nan 25. 23. 22. 21. 21. 19. 12. 25. 43. 30. 28. 23. 40.
  19. 34. 24. 31. 29. nan nan]
 [nan nan nan nan nan 22. 23. 24. 19. 20. 22. 13. 24. 29. 25. 24. 17. 35.
  28. 38. 33. 33. 33. nan nan]
 [nan nan nan nan nan 22. 22. 23. 21. 22. 17. 12. 23. 25. 24. 22. 28. 20.
  29. 28. 37. 38. 34. 36. nan]
 [nan nan 27. 27. 25. 23. 21. 26. 22. 21. 13. 16. 18. 19. 18. 19. 21.  9.
  31. 29. 34. 51. 34. 39. nan]
 [nan nan 26. 28. 28. 25. 22. 14. 19. 18. 13.  9. 17. 13. 14. 15. 16. 24.
  26. 25. 36. 38. 35. 38. nan]
 [nan nan 25. 27. 28. 27. 22. 17. 20. 18. 15. 16. 26. 15. 13.  8.  7. 18.
  21. 23. 28. 28. 33. 35. nan]
 [nan nan 23. 24. 27. 26. 23. 19. 20. 16. 16. 19. 23. 16. 12.  8. 11. 17.
  19. 21. 25. 25. 25. nan nan]
 [nan nan 20. 19. 18. 22. 23. 20. 18. 16. 16. 25. 27. 21. 11. 16. 17. 18.
  19. 21. 24. 25. 26. nan nan]
 [nan nan 18. 15. 14. 18. 20. 20. 18. 16. 21. 31. 31. 29. 16. 10. 17. 18.
  18. 20. 23. 25. nan nan nan]
 [nan nan 16. 14. 15. 15. 19. nan 18. 24. 32. 41. 47. 49. 22. 13. 17. 18.
  18. nan nan nan nan nan nan]
 [nan nan 15. 15. 16. 16. 18. nan nan nan 40. 53. 62. 57. 32. 15. 16. 17.
  18. nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan 45. 60. 62. 61. 37. 26. 18. 17.
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan 54. 59. 57. 54. 41. nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]]

In [27]:
print(embrace_2022_2024[0][-1])

[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan 16. 16. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 15. 16. 16. 17. 17. 16. 13. 12. 12. 12. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 14. 14. 14. 18. 17. 17. 15. 11. 12. 13. 12. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 15. 14. 13. 14. 16. 15. 13. 12. 12. 13. 12. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 15. 14. 14. 16. 16. 15. 14. 13. 13. 13. 12. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 15. 15. 15. 16. 18. 18. 16. 15. 14. 13. 13. 12. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan 15. 15. 16. 22. 22. 17. 17. 15. 13. nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 15. 16. 15. 15. 13. 21. 17. 16. 15. 13. 12. 11. nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 16. 16. 16. 16. 16. 14. 16. 14. 13. 12. 10. 11. 11. nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 16. 16. 16. 16. 16. 15. 18. 14. 13. 11. 10. 11. 11. nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan 16. 16. 16. 17. 15. 13. 15. 12. 13. 12. 12. 13. 11. 11.
  nan nan nan nan nan nan nan]
 [nan nan nan nan 17. 17. 18. 18. 13. 16. 17. 17. 14. 13. 13. 12. 10. 10.
  11. nan nan nan nan nan nan]
 [nan nan nan nan 17. 17. 17. 16. 19. 17. 18. 17. 15. 11. 15. 10.  9. 10.
  11. 12. nan nan nan nan nan]
 [nan nan nan nan nan 18. 18. 17. 25. 23. 21. 18. 18. 18. 14. 10.  9. 11.
  11. 12. nan nan nan nan nan]
 [nan nan nan nan nan 20. 19. 19. 24. 25. 27. 22. 21. 22. 15. 12. 11. 11.
  12. 13. 13. 13. nan nan nan]
 [nan nan nan nan nan nan 25. 28. 41. 32. 29. 26. 22.  3. 18. 17. 14. 13.
  14. 14. 13. 13. nan nan nan]
 [nan nan nan nan nan nan 30. 33. 39. 40. 42. 36. 35. 46. 25. 20. 15. 17.
  15. 14. 13. 13. nan nan nan]
 [nan nan nan nan nan nan 35. 35. 33. 39. 42. 41. 48. 35. 32. 28. 22. 18.
  18. 15. 12. 13. 14. nan nan]
 [nan nan nan nan nan nan 34. 35. 33. 35. 40. 41. 41. 35. 36. 34. 31. 24.
  21. 18. 15. 14. 16. nan nan]
 [nan nan nan nan nan nan 34. 34. 27. 30. 40. 42. 41. 36. 37. 38. 35. 35.
  26. 19. 15. 18. 18. nan nan]
 [nan nan nan nan nan nan 33. 31. 28. 29. 42. 46. 37. 26. 33. 33. 38. 29.
  39. 22. 23. 21. 21. nan nan]
 [nan nan nan nan nan 29. 29. 28. 26. 27. 36. 49. 33. 28. 31. 30. 49. 41.
  28. 23. 23. 20. 24. nan nan]
 [nan nan nan nan nan 27. 26. 26. 25. 23. 29. 31. 22. 10. 22. 30. 41. 27.
  38. 30. 30. 29. 27. nan nan]
 [nan nan nan nan nan 26. 26. 26. 27. 24. 29. 24. 23. 16. 21. 29. 23. 34.
  38. 30. 29. 31. 28. nan nan]
 [nan nan nan nan nan 26. 25. 27. 26. 26. 21. 19. 19. 18. 21. 23. 20. 26.
  26. 40. 36. 27. 26. 31. nan]
 [nan nan 30. 30. 28. 27. 26. 28. 25. 25. 21. 16. 18. 18. 18. 19. 20. 23.
  16. 29. 35. 24. 22. 30. nan]
 [nan nan 30. 30. 30. 29. 25. 18. 22. 22. 17. 18. 18. 18. 16. 16. 17. 23.
  15. 21. 36. 29. 27. 24. nan]
 [nan nan 30. 30. 30. 30. 26. 21. 21. 22. 22. 18. 16. 22. 16. 13. 16. 18.
  17. 18. 27. 24. 22. 22. nan]
 [nan nan 29. 30. 30. 29. 27. 23. 23. 23. 22. 18. 17. 18. 16. 13. 17. 14.
  14. 18. 22. 23. 25. nan nan]
 [nan nan 29. 29. 29. 29. 28. 24. 23. 25. 23. 17. 16. 16. 15. 15. 18. 16.
  14. 18. 22. 24. 24. nan nan]
 [nan nan 29. 28. 28. 29. 27. 25. 24. 23. 20. 15. 15. 17. 15. 15. 17. 16.
  16. 18. 21. 23. nan nan nan]
 [nan nan 29. 28. 28. 28. 27. nan 24. 22. 20. 16. 18. 19. 17. 16. 16. 16.
  17. nan nan nan nan nan nan]
 [nan nan 28. 28. 28. 28. 27. nan nan nan 20. 20. 22. 21. 18. nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan 21. 22. 22. 22. 20. nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan 21. 22. 22. 22. 21. nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]]

# Dates adjusts

In [28]:
import numpy as np
from datetime import datetime, timedelta

def doy_to_date(year, doy):
    return datetime(year, 1, 1) + timedelta(days=doy - 1)

doys = {
    2022: {
        3: [60, 61, 62, 63, 64, 65, 66, 67, 69, 70,
            71, 73, 74, 75, 76, 77, 78, 79, 80, 81,
            82, 83, 84, 85, 86, 90],
        6: [152, 153, 154, 156, 157, 158, 159, 160,
            161, 162, 163, 164, 165, 166, 167, 168,
            169, 170, 171, 172, 173, 174, 176, 178,
            181],
        9: [245, 246, 247, 248, 249, 250, 251, 252,
            253, 254, 255, 256, 258, 260, 261, 262,
            264, 265, 266, 267, 268, 269, 270, 271,
            272, 273]
    },

    2024: {
        3: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
            71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
            81, 86, 87, 88, 89, 91],
        6: [153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
            163, 164, 165, 166, 167, 168, 169, 170, 171, 173,
            174, 175, 176, 177, 180, 181],
        9: [247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
            257, 258, 261, 262, 263, 264, 265, 266, 267, 268,
            269, 270, 271, 272, 274],
        12: [336, 337, 338, 339, 340, 341, 342, 343, 344, 345,
             346, 347, 349, 350, 351, 352, 353, 354, 355,
             356, 357, 358, 359, 360, 361, 362, 363, 364, 365]
    }
}

datetime_list = []

for year in doys.keys():
    for month in doys[year].keys():
        for doy in doys[year][month]:
            base_date = doy_to_date(year, doy)
            for minute in range(0, 24 * 60, 10):
                dt = base_date + timedelta(minutes=minute)
                datetime_list.append(dt)

embrace_datetimes_2022_2024 = np.array(datetime_list, dtype='datetime64[s]')

print(f"Total number of datetime points: {len(embrace_datetimes_2022_2024)}")
print(f"First datetime: {embrace_datetimes_2022_2024[0]}")
print(f"Last datetime: {embrace_datetimes_2022_2024[-1]}")

print("\nSample of first 10 datetime entries:")
for dt in embrace_datetimes_2022_2024[:10]:
    print(dt)

print("\nSample of last 10 datetime entries:")
for dt in embrace_datetimes_2022_2024[-10:]:
    print(dt)

Total number of datetime points: 26352
First datetime: 2022-03-01T00:00:00
Last datetime: 2024-12-30T23:50:00

Sample of first 10 datetime entries:
2022-03-01T00:00:00
2022-03-01T00:10:00
2022-03-01T00:20:00
2022-03-01T00:30:00
2022-03-01T00:40:00
2022-03-01T00:50:00
2022-03-01T01:00:00
2022-03-01T01:10:00
2022-03-01T01:20:00
2022-03-01T01:30:00

Sample of last 10 datetime entries:
2024-12-30T22:20:00
2024-12-30T22:30:00
2024-12-30T22:40:00
2024-12-30T22:50:00
2024-12-30T23:00:00
2024-12-30T23:10:00
2024-12-30T23:20:00
2024-12-30T23:30:00
2024-12-30T23:40:00
2024-12-30T23:50:00

In [29]:
embrace_2022_2024.shape

(183, 144, 41, 25)

In [30]:
print(len(embrace_2022_2024.tolist()))
print(len(embrace_2022_2024[0].tolist()))
print(len(embrace_2022_2024[0][0].tolist()))
print(len(embrace_2022_2024[0][0][0].tolist()))

183
144
41
25

In [31]:
embrace_2022.shape

(77, 144, 41, 25)

In [32]:
embrace_2024.shape

(106, 144, 41, 25)

In [33]:
embrace_datetimes_2022 = np.array([d for d in embrace_datetimes_2022_2024 if d.astype(object).year == 2022])

In [34]:
len(embrace_datetimes_2022)

11088

In [35]:
embrace_datetimes_2024 = np.array([d for d in embrace_datetimes_2022_2024 if d.astype(object).year == 2024])

In [36]:
len(embrace_datetimes_2024)

15264

In [37]:
embrace_datetimes_2022_2024[0:12]

array(['2022-03-01T00:00:00', '2022-03-01T00:10:00',
       '2022-03-01T00:20:00', '2022-03-01T00:30:00',
       '2022-03-01T00:40:00', '2022-03-01T00:50:00',
       '2022-03-01T01:00:00', '2022-03-01T01:10:00',
       '2022-03-01T01:20:00', '2022-03-01T01:30:00',
       '2022-03-01T01:40:00', '2022-03-01T01:50:00'],
      dtype='datetime64[s]')

In [38]:
len(embrace_datetimes_2022_2024[0:12])

12

In [39]:
len(embrace_2022_2024[0:12])

12

In [40]:
embrace_2022_2024_shaped = np.reshape(embrace_2022_2024, (-1, 41, 25))

In [41]:
np.shape(embrace_2022_2024_shaped)

(26352, 41, 25)

In [42]:
np.shape(embrace_2022_2024_shaped.tolist())

(26352, 41, 25)

In [43]:
embrace_datetimes_2022_2024.shape

(26352,)

## Create dataframe

In [44]:
import pandas as pd

data = {
    'DATETIME': embrace_datetimes_2022_2024,
    'TECMAP': embrace_2022_2024_shaped.tolist()
}

df_embrace_maps_2022_2024 = pd.DataFrame(data)

print(df_embrace_maps_2022_2024)

                 DATETIME                                             TECMAP
0     2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2022-03-01 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2022-03-01 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2022-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2022-03-01 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
26347 2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
26348 2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
26349 2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
26350 2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
26351 2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[26352 rows x 2 columns]

In [45]:
np.array(df_embrace_maps_2022_2024.iloc[0]['TECMAP'])

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, 17., 17., nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 17., 17., 17., 18., 18., 14., 14., 14.,
        13., 13., 12., nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, 17., 17., 17., 20., 18., 17., 14., 14., 14.,
        13., 12., 12., nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, 17., 17., 17., 16., 17., 14., 14., 14., 15.,
        14., 12., 12., nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, 17., 17., 18., 20., 18., 17., 16., 18., 16.,
        15., 13., 12., nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, 18., 18., 19., 19., 19., 19., 17., 16., 16.,
        16., 14., 14., nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 19., 19., 19., 16., 18., 17., 14., 15.,
        16., 15., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 19., 19., 19., 18., 18., 19., 14., 15.,
        14., 14., 14., nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 19., 20., 20., 20., 19., 19., 16., 15.,
        13., 12., 13., 14., nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 20., 20., 21., 20., 22., 19., 16., 14.,
        12., 11., 14., 14., nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 21., 20., 21., 20., 18., 18., 16., 15.,
        12., 14., 16., 15., 14., nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 22., 22., 20., 20., 20., 20., 20., 18.,
        17., 18., 16., 14., 14., 14., nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 23., 22., 22., 23., 21., 22., 23., 22.,
        20., 19., 16., 14., 14., 14., 14., nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 24., 25., 26., 28., 25., 25., 14., 23.,
        22., 20., 17., 13., 14., 13., 14., nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, 25., 27., 30., 13., 29., 32., 27., 27.,
        20., 22., 19., 16., 12., 14., 14., 13., 13., nan, nan, nan],
       [nan, nan, nan, nan, nan, 27., 27., 28., 20., 33., 31., 29., 27.,
        44., 20., 23., 19., 16., 15., 13., 13., 12., nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, 27., 24., 22., 33., 36., 33., 25.,
        22., 27., 26., 20., 19., 16., 13., 12., 13., nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, 29., 25., 18., 28., 36., 22., 13.,
        31., 31., 29., 26., 21., 18., 14., 11., 13., 14., nan, nan],
       [nan, nan, nan, nan, nan, nan, 31., 34., 15., 24., 26., 13., 11.,
        32., 34., 32., 31., 25., 21., 18., 14., 14., 15., nan, nan],
       [nan, nan, nan, nan, nan, nan, 32., 34., 28., 25., 25., 20., 12.,
        37., 43., 31., 32., 31., 23., 20., 17., 16., 17., nan, nan],
       [nan, nan, nan, nan, nan, nan, 32., 31., 28., 27., 27., 31., 40.,
        32., 40., 27., 33., 32., 38., 21., 24., 19., 19., nan, nan],
       [nan, nan, nan, nan, nan, 27., 26., 26., 25., 23., 24., 35., 34.,
        45., 36., 23., 42., 47., 27., 27., 21., 19., 24., nan, nan],
       [nan, nan, nan, nan, nan, 25., 23., 22., 21., 21., 19., 12., 25.,
        43., 30., 28., 23., 40., 19., 34., 24., 31., 29., nan, nan],
       [nan, nan, nan, nan, nan, 22., 23., 24., 19., 20., 22., 13., 24.,
        29., 25., 24., 17., 35., 28., 38., 33., 33., 33., nan, nan],
       [nan, nan, nan, nan, nan, 22., 22., 23., 21., 22., 17., 12., 23.,
        25., 24., 22., 28., 20., 29., 28., 37., 38., 34., 36., nan],
       [nan, nan, 27., 27., 25., 23., 21., 26., 22., 21., 13., 16., 18.,
        19., 18., 19., 21.,  9., 31., 29., 34., 51., 34., 39., nan],
       [nan, nan, 26., 28., 28., 25., 22., 14., 19., 18., 13.,  9., 17.,
        13., 14., 15., 16., 24., 26., 25., 36., 38., 35., 38., nan],
       [nan, nan, 25., 27., 28., 27., 22., 17., 20., 18., 15., 16., 26.,
        15., 13.,  8.,  7., 18., 21., 23., 28., 28., 33., 35., nan],
       [nan, nan, 23., 24., 27., 26., 23., 19., 20., 16., 16., 19., 23.,
        16., 12.,  8., 11., 17., 19., 21., 25., 25., 25., nan, nan],
       [nan, nan, 20., 19., 18., 22., 23., 20., 18., 16., 16., 25., 27.,
        21., 11., 16., 17., 18., 19., 21., 24., 25., 26., nan, nan],
       [nan, nan, 18., 15., 14., 18., 20., 20., 18., 16., 21., 31., 31.,
        29., 16., 10., 17., 18., 18., 20., 23., 25., nan, nan, nan],
       [nan, nan, 16., 14., 15., 15., 19., nan, 18., 24., 32., 41., 47.,
        49., 22., 13., 17., 18., 18., nan, nan, nan, nan, nan, nan],
       [nan, nan, 15., 15., 16., 16., 18., nan, nan, nan, 40., 53., 62.,
        57., 32., 15., 16., 17., 18., nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 45., 60., 62.,
        61., 37., 26., 18., 17., nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 54., 59., 57.,
        54., 41., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [46]:
np.array(df_embrace_maps_2022_2024.iloc[0]['TECMAP']).shape

(41, 25)

In [47]:
type(df_embrace_maps_2022_2024.index)

pandas.core.indexes.range.RangeIndex

In [48]:
df_embrace_maps_2022_2024.set_index('DATETIME', inplace=True)

In [49]:
type(df_embrace_maps_2022_2024.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [50]:
df_embrace_maps_2022_2024

                                                                TECMAP
DATETIME
2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[26352 rows x 1 columns]

In [51]:
df_embrace_maps_2022_2024 = df_embrace_maps_2022_2024[(df_embrace_maps_2022_2024.index.minute == 0) & (df_embrace_maps_2022_2024.index.hour % 2 == 0)]

In [52]:
df_embrace_maps_2022_2024

                                                                TECMAP
DATETIME
2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 06:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 14:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[2196 rows x 1 columns]

In [53]:
np.shape(np.array(df_embrace_maps_2022_2024.iloc[:]['TECMAP']))

(2196,)

In [54]:
embrace_maps_2022_2024 = np.array(df_embrace_maps_2022_2024.iloc[:]['TECMAP'])

In [55]:
np.shape(embrace_maps_2022_2024)

(2196,)

In [56]:
np_embrace_maps_2022_2024 = []
for i in range(len(embrace_maps_2022_2024)):
    np_embrace_maps_2022_2024.append(embrace_maps_2022_2024[i])
np_embrace_maps_2022_2024 = np.array(np_embrace_maps_2022_2024)

In [57]:
np.shape(np_embrace_maps_2022_2024)

(2196, 41, 25)

In [58]:
type(np_embrace_maps_2022_2024)

numpy.ndarray

In [59]:
df_embrace_maps_2022_2024 = pd.DataFrame(data)

df_embrace_maps_2022_2024['DATETIME'] = pd.to_datetime(df_embrace_maps_2022_2024['DATETIME'])

df_embrace_maps_2022_2024.set_index('DATETIME', inplace=True)

In [60]:
df_embrace_maps_2022_2024.to_pickle("./df_embrace_maps_2022_2024.pkl")

In [62]:
!ls -lh

total 884M
-rw-r--r-- 1 root root 237M Aug  2 00:34 df_embrace_maps_2022_2024.pkl
-rw-r--r-- 1 root root  87M Aug  2 00:17 EMBRACE_TEC_maps_intersection_2022.npy
-rw-r--r-- 1 root root 120M Aug  2 00:17 EMBRACE_TEC_maps_intersection_2024.npy
-rw-r--r-- 1 root root  14M Aug  1 23:13 EMBRACE_TEC_maps_intersection_raw_files_2022_2024.zip
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0600.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0600_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0610.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0610_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0610.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0610_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0620.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0620_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0620.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0620_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0630.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0630_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0630.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0630_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0640.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0640_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0640.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0640_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0650.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0650_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0650.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0650_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0660.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0660_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0660.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0660_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0670.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0670_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0670.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0670_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0680.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0680_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0690.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0690_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0690.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0690_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0700.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0700_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0700.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0700_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0710.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0710_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0710.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0710_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0720.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0720_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0730.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0730_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0730.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0730_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0740.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0740_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0740.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0740_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0750.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0750_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0750.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0750_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0760.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0760_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0760.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0760_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0770.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0770_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0770.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0770_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0780.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0780_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0780.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0780_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0790.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0790_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0790.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0790_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0800.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0800_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0800.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0800_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0810.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0810_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0810.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0810_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0820.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0820_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0830.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0830_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0840.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0840_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0850.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0850_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0860.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0860_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0860.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0860_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0870.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0870_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0880.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0880_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0890.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0890_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE0900.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0900_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE0910.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE0910_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1520.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1520_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1530.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1530_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1530.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1530_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1540.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1540_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1540.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1540_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1550.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1550_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1560.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1560_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1560.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1560_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1570.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1570_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1570.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1570_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1580.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1580_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1580.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1580_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1590.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1590_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1590.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1590_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1600.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1600_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1600.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1600_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1610.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1610_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1610.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1610_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1620.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1620_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1620.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1620_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1630.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1630_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1630.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1630_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1640.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1640_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1640.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1640_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1650.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1650_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1650.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1650_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1660.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1660_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1660.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1660_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1670.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1670_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1670.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1670_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1680.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1680_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1680.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1680_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1690.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1690_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1690.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1690_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1700.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1700_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1700.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1700_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1710.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1710_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1710.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1710_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1720.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1720_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1730.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1730_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1730.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1730_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1740.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1740_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1740.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1740_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1750.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1750_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1760.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1760_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1760.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1760_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1770.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1770_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1780.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1780_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1800.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1800_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE1810.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1810_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE1810.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE1810_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2450.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2450_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2460.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2460_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2470.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2470_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2470.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2470_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2480.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2480_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2480.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2480_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2490.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2490_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2490.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2490_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2500.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2500_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2500.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2500_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2510.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2510_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2510.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2510_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2520.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2520_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2520.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2520_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2530.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2530_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2530.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2530_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2540.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2540_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2540.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2540_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2550.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2550_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2550.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2550_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2560.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2560_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2560.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2560_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2570.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2570_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2580.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2580_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2580.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2580_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2600.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2600_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2610.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2610_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2610.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2610_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2620.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2620_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2620.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2620_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2630.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2630_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2640.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2640_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2640.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2640_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2650.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2650_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2650.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2650_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2660.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2660_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2660.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2660_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2670.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2670_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2670.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2670_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2680.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2680_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2680.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2680_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2690.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2690_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2690.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2690_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2700.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2700_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2700.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2700_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2710.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2710_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2710.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2710_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2720.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2720_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2720.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2720_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:01 INPE2730.22I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2730_22.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE2740.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE2740_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3360.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3360_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3370.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3370_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3380.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3380_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3390.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3390_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3400.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3400_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3410.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3410_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3420.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3420_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3430.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3430_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3440.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3440_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3450.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3450_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3460.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3460_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3470.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3470_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3490.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3490_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3500.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3500_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3510.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3510_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3520.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3520_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3530.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3530_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3540.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3540_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3550.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3550_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3560.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3560_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3570.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3570_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3580.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3580_24.npy
-rw-rw-r-- 1 root root 1.3M Mar  3 02:02 INPE3590.24I
-rw-r--r-- 1 root root 1.2M Aug  2 00:17 INPE3590_24.npy

In [64]:
%cp df_embrace_maps_2022_2024.pkl /content/drive/MyDrive/df_embrace_maps_2022_2024.pkl

# TF1 adjusts

## Continuous

In [ ]:
df_embrace_maps_2022_2024_0800 = df_embrace_maps_2022_2024.between_time('08:00', '08:00')

df_embrace_maps_2022_2024_1600 = df_embrace_maps_2022_2024.between_time('16:00', '16:00')

df_embrace_maps_2022_2024_2000_2200_0000_0200_0400 = pd.concat([
    df_embrace_maps_2022_2024.between_time('20:00', '20:00'),
    df_embrace_maps_2022_2024.between_time('22:00', '22:00'),
    df_embrace_maps_2022_2024.between_time('00:00', '00:00'),
    df_embrace_maps_2022_2024.between_time('02:00', '02:00'),
    df_embrace_maps_2022_2024.between_time('04:00', '04:00')
])

df_embrace_maps_2022_2024_2000_2200_0000_0200_0400.sort_index(inplace=True)

print("08:00 data:")
print(df_embrace_maps_2022_2024_0800)

print("\n16:00 data:")
print(df_embrace_maps_2022_2024_1600)

print("\n20:00 to 04:00 data:")
print(df_embrace_maps_2022_2024_2000_2200_0000_0200_0400)

## 08:00 UT

In [ ]:
df_embrace_maps_2022_2024_0800.to_pickle("./TF1_EMBRACE_TEC_maps_2022_2024_0800.pkl")

In [ ]:
np.shape(np.array(df_embrace_maps_2022_2024_0800.iloc[:]['TECMAP']))

In [ ]:
embrace_maps_2022_2024_0800 = np.array(df_embrace_maps_2022_2024_0800.iloc[:]['TECMAP'])

In [ ]:
np.shape(embrace_maps_2022_2024_0800)

In [ ]:
np_embrace_maps_2022_2024_0800 = []
for i in range(len(embrace_maps_2022_2024_0800)):
    np_embrace_maps_2022_2024_0800.append(embrace_maps_2022_2024_0800[i])
np_embrace_maps_2022_2024_0800 = np.array(np_embrace_maps_2022_2024_0800)

In [ ]:
np.shape(np_embrace_maps_2022_2024_0800)

In [ ]:
type(np_embrace_maps_2022_2024_0800)

In [ ]:
np.save('TF1_EMBRACE_TEC_maps_2022_2024_0800.npy', np_embrace_maps_2022_2024_0800)

## 16:00 UT

In [ ]:
df_embrace_maps_2022_2024_1600.to_pickle("./TF1_EMBRACE_TEC_maps_2022_2024_1600.pkl")

In [ ]:
embrace_maps_2022_2024_1600 = np.array(df_embrace_maps_2022_2024_1600.iloc[:]['TECMAP'])

In [ ]:
np.shape(embrace_maps_2022_2024_1600)

In [ ]:
np_embrace_maps_2022_2024_1600 = []
for i in range(len(embrace_maps_2022_2024_1600)):
    np_embrace_maps_2022_2024_1600.append(embrace_maps_2022_2024_1600[i])
np_embrace_maps_2022_2024_1600 = np.array(np_embrace_maps_2022_2024_1600)

In [ ]:
np.shape(np_embrace_maps_2022_2024_1600)

In [ ]:
type(np_embrace_maps_2022_2024_1600)

In [ ]:
np.save('TF1_EMBRACE_TEC_maps_2022_2024_1600.npy', np_embrace_maps_2022_2024_1600)

## 20:00 to 04:00 UT

In [ ]:
df_embrace_maps_2022_2024_2000_2200_0000_0200_0400.to_pickle("./TF1_EMBRACE_TEC_maps_2022_2024_2000_2200_0000_0200_0400.pkl")

In [ ]:
embrace_maps_2022_2024_2000_2200_0000_0200_0400 = np.array(df_embrace_maps_2022_2024_2000_2200_0000_0200_0400.iloc[:]['TECMAP'])

In [ ]:
np.shape(embrace_maps_2022_2024_2000_2200_0000_0200_0400)

In [ ]:
np.shape(embrace_maps_2022_2024_2000_2200_0000_0200_0400[0])

In [ ]:
np_embrace_maps_2022_2024_2000_2200_0000_0200_0400 = []
for i in range(len(embrace_maps_2022_2024_2000_2200_0000_0200_0400)):
    np_embrace_maps_2022_2024_2000_2200_0000_0200_0400.append(embrace_maps_2022_2024_2000_2200_0000_0200_0400[i])
np_embrace_maps_2022_2024_2000_2200_0000_0200_0400 = np.array(np_embrace_maps_2022_2024_2000_2200_0000_0200_0400)

In [ ]:
np.shape(np_embrace_maps_2022_2024_2000_2200_0000_0200_0400)

In [ ]:
type(np_embrace_maps_2022_2024_2000_2200_0000_0200_0400)

In [ ]:
np.save('TF1_EMBRACE_TEC_maps_2022_2024_2000_2200_0000_0200_0400.npy', np_embrace_maps_2022_2024_2000_2200_0000_0200_0400)

# TF3 adjusts

## Continuous

In [ ]:
np.array(df3.iloc[0]['TECMAP'])

In [ ]:
np.array(df3.iloc[0]['TECMAP']).shape

In [ ]:
df3_0800 = df3.between_time('08:00', '08:00')

df3_1600 = df3.between_time('16:00', '16:00')

df3_2000_0400 = pd.concat([
    df3.between_time('20:00', '20:00'),
    df3.between_time('20:30', '20:30'),
    df3.between_time('21:00', '21:00'),
    df3.between_time('21:30', '21:30'),
    df3.between_time('22:00', '22:00'),
    df3.between_time('22:30', '22:30'),
    df3.between_time('23:00', '23:00'),
    df3.between_time('23:30', '23:30'),
    df3.between_time('00:00', '00:00'),
    df3.between_time('00:30', '00:30'),
    df3.between_time('01:00', '01:00'),
    df3.between_time('01:30', '01:30'),
    df3.between_time('02:00', '02:00'),
    df3.between_time('02:30', '02:30'),
    df3.between_time('03:00', '03:00'),
    df3.between_time('03:30', '03:30'),
    df3.between_time('04:00', '04:00')
])

df3_2000_0400.sort_index(inplace=True)

print("08:00 data:")
print(df3_0800)

print("\n16:00 data:")
print(df3_1600)

print("\n20:00 to 04:00 data:")
print(df3_2000_0400)

In [ ]:
np.shape(np.array(df3.iloc[:]['TECMAP']))

In [ ]:
maps3 = np.array(df3.iloc[:]['TECMAP'])

In [ ]:
np.shape(df3)

In [ ]:
np_maps3 = []
for i in range(len(maps3)):
    np_maps3.append(maps3[i])
np_maps3 = np.array(np_maps3)

In [ ]:
np.shape(np_maps3)

In [ ]:
type(np_maps3)

## 08:00 UT

In [ ]:
df3_0800.to_pickle("./TF3_EMBRACE_TEC_maps_2024_0800.pkl")

In [ ]:
np.shape(np.array(df3_0800.iloc[:]['TECMAP']))

In [ ]:
maps3_0800 = np.array(df3_0800.iloc[:]['TECMAP'])

In [ ]:
np.shape(df3_0800)

In [ ]:
np_maps3_0800 = []
for i in range(len(maps3_0800)):
    np_maps3_0800.append(maps3_0800[i])
np_maps3_0800 = np.array(np_maps3_0800)

In [ ]:
np.shape(np_maps3_0800)

In [ ]:
type(np_maps3_0800)

In [ ]:
np.save('TF3_EMBRACE_TEC_maps_2024_0800.npy', np_maps3_0800)

## 16:00 UT

In [ ]:
df3_1600.to_pickle("./TF3_EMBRACE_TEC_maps_2024_1600.pkl")

In [ ]:
maps3_1600 = np.array(df3_1600.iloc[:]['TECMAP'])

In [ ]:
np.shape(maps3_1600)

In [ ]:
np_maps3_1600 = []
for i in range(len(maps3_1600)):
    np_maps3_1600.append(maps3_1600[i])
np_maps3_1600 = np.array(np_maps3_1600)

In [ ]:
np.shape(np_maps3_1600)

In [ ]:
type(np_maps3_1600)

In [ ]:
np.save('TF3_EMBRACE_TEC_maps_2024_1600.npy', np_maps3_1600)

## 20:00 to 04:00 UT

In [ ]:
df3_2000_0400.to_pickle("./TF3_EMBRACE_TEC_maps_2024_2000_0400.pkl")

In [ ]:
df3_2000_0400

In [ ]:
maps3_2000_0400 = np.array(df3_2000_0400.iloc[:]['TECMAP'])

In [ ]:
np.shape(maps3_2000_0400)

In [ ]:
np_maps3_2000_0400 = []
for i in range(len(maps3_2000_0400)):
    np_maps3_2000_0400.append(maps3_2000_0400[i])
np_maps3_2000_0400 = np.array(np_maps3_2000_0400)

In [ ]:
np.shape(np_maps3_2000_0400)

In [ ]:
type(np_maps3_2000_0400)

In [ ]:
np.save('TF3_EMBRACE_TEC_maps_2024_2000_0400.npy', np_maps3_2000_0400)

# Download outputs

In [ ]:
from google.colab import files

In [ ]:
%pwd

In [ ]:
files.download('./EMBRACE_TEC_maps_intersection_2022.npy')

In [ ]:
files.download('./EMBRACE_TEC_maps_intersection_2024.npy')

In [ ]:
files.download('./TF1_EMBRACE_TEC_maps_2022_2024_0800.pkl')

In [ ]:
files.download('./TF1_EMBRACE_TEC_maps_2022_2024_1600.pkl')

In [ ]:
files.download('./TF1_EMBRACE_TEC_maps_2022_2024_2000_2200_0000_0200_0400.pkl')

In [63]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls -lh df3*

In [ ]:
%cp TF3_EMBRACE_TEC_maps_2024_0800.pkl /content/drive/MyDrive/TF3_EMBRACE_TEC_maps_2024_0800.pkl

In [ ]:
%cp TF3_EMBRACE_TEC_maps_2024_1600.pkl /content/drive/MyDrive/TF3_EMBRACE_TEC_maps_2024_1600.pkl

In [ ]:
%cp TF3_EMBRACE_TEC_maps_2024_2000_0400.pkl /content/drive/MyDrive/TF3_EMBRACE_TEC_maps_2024_2000_0400.pkl

In [ ]:
!ls -lh maps3*

In [ ]:
%cp TF3_EMBRACE_TEC_maps_2024_0800.npy /content/drive/MyDrive/TF3_EMBRACE_TEC_maps_2024_0800.npy

In [ ]:
%cp TF3_EMBRACE_TEC_maps_2024_1600.npy /content/drive/MyDrive/TF3_EMBRACE_TEC_maps_2024_1600.npy

In [ ]:
%cp TF3_EMBRACE_TEC_maps_2024_2000_0400.npy /content/drive/MyDrive/TF3_EMBRACE_TEC_maps_2024_2000_0400.npy