# Filter 2024 Dataframes

## EMBRACE

In [ ]:
import pandas as pd

%cd '/content/drive/MyDrive'

df_embrace = pd.read_pickle('TF_EMBRACE_TEC_maps_2022_2024.pkl')

/content/drive/MyDrive

In [ ]:
df_embrace

                                                                TECMAP
DATETIME
2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[26352 rows x 1 columns]

In [ ]:
print("Available columns in DataFrame:")
print(df_embrace.columns.tolist())
print(f"\nDataFrame shape: {df_embrace.shape}")

Available columns in DataFrame:
['TECMAP']

DataFrame shape: (26352, 1)

In [ ]:
df_embrace = df_embrace.reset_index()

print("Columns after reset_index:")
print(df_embrace.columns.tolist())

Columns after reset_index:
['DATETIME', 'TECMAP']

In [ ]:
df_embrace['DATETIME'] = pd.to_datetime(df_embrace['DATETIME'])

from datetime import datetime

dates_obj = [
    datetime(2024, 3, 20, 4, 0, 0),
    datetime(2024, 6, 21, 0, 0, 0),
    datetime(2024, 9, 22, 14, 0, 0),
    datetime(2024, 12, 21, 10, 0, 0)
]

df_embrace = df_embrace[df_embrace['DATETIME'].isin(dates_obj)]

In [ ]:
df_embrace

                 DATETIME                                             TECMAP
13848 2024-03-20 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
17568 2024-06-21 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
21108 2024-09-22 14:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
24972 2024-12-21 10:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
import numpy as np

In [ ]:
mapas_embrace = np.array(df_embrace.iloc[:]['TECMAP'])

In [ ]:
np.shape(df_embrace)

(4, 2)

In [ ]:
np_mapas_embrace = []
for i in range(len(mapas_embrace)):
    np_mapas_embrace.append(mapas_embrace[i])
np_mapas_embrace = np.array(np_mapas_embrace)

In [ ]:
np.shape(np_mapas_embrace)

(4, 41, 25)

In [ ]:
type(np_mapas_embrace)

numpy.ndarray

In [ ]:
np.save('EMBRACE_TEC_maps.npy', np_mapas_embrace)

In [ ]:
!ls -lh EMBRACE_maps*

-rw------- 1 root root 33K Aug  2 22:00 embrace_maps.npy

In [ ]:
df_embrace['DATETIME'].values

array(['2024-03-20T04:00:00', '2024-06-21T00:00:00',
       '2024-09-22T14:00:00', '2024-12-21T10:00:00'],
      dtype='datetime64[s]')

In [ ]:
np.shape(df_embrace['DATETIME'].values)

(4,)

In [ ]:
np.save('EMBRACE_TEC_maps_datetimes.npy', df_embrace['DATETIME'].values)

/usr/local/lib/python3.11/dist-packages/numpy/lib/format.py:382: UserWarning: metadata on a dtype is not saved to an npy/npz. Use another format (such as pickle) to store it.
  d['descr'] = dtype_to_descr(array.dtype)

## IGS

In [ ]:
import pandas as pd

%cd '/content/drive/MyDrive'

df_igs = pd.read_pickle('TF_IGS_TEC_maps_2022_2024.pkl')

/content/drive/MyDrive

In [ ]:
df_igs

                DATETIME                                             TECMAP
0    2022-03-01 00:00:00  [[18.4, 18.0, 17.4, 17.0, 16.9, 17.0, 17.0, 17...
1    2022-03-01 02:00:00  [[10.9, 10.6, 10.5, 10.4, 10.7, 11.1, 11.6, 11...
2    2022-03-01 04:00:00  [[7.5, 7.3, 7.3, 7.5, 7.7, 8.0, 8.4, 8.9, 9.4,...
3    2022-03-01 06:00:00  [[7.4, 7.1, 6.9, 7.0, 7.3, 7.6, 8.1, 8.6, 9.2,...
4    2022-03-01 08:00:00  [[7.2, 6.9, 6.8, 7.0, 7.4, 8.0, 8.5, 9.0, 9.4,...
...                  ...                                                ...
3607 2024-12-30 14:00:00  [[8.9, 11.1, 14.4, 18.8, 23.7, 28.3, 32.7, 36....
3608 2024-12-30 16:00:00  [[26.3, 29.8, 33.4, 37.1, 40.5, 43.7, 47.0, 49...
3609 2024-12-30 18:00:00  [[43.5, 44.5, 45.3, 46.2, 47.1, 48.6, 50.0, 51...
3610 2024-12-30 20:00:00  [[48.8, 49.1, 49.0, 48.7, 48.5, 48.1, 48.0, 47...
3611 2024-12-30 22:00:00  [[47.0, 46.6, 45.6, 44.4, 43.2, 42.0, 40.4, 38...

[3612 rows x 2 columns]

In [ ]:
reference_date = pd.Timestamp('2024-06-20 22:00:00')

subsequent_records = df_igs[df_igs['DATETIME'] > reference_date]

if len(subsequent_records) > 0:

    closest_record = subsequent_records.loc[subsequent_records['DATETIME'].idxmin()]

    print(f"Reference date: {reference_date}")
    print(f"Next record found: {closest_record['DATETIME']}")
    print(f"Difference: {closest_record['DATETIME'] - reference_date}")
    print("\nComplete record:")
    print(closest_record)
else:
    print("No records found after the specified date")

Reference date: 2024-06-20 22:00:00
Next record found: 2024-06-21 00:00:00
Difference: 0 days 02:00:00

Complete record:
DATETIME                                  2024-06-21 00:00:00
TECMAP      [[35.7, 35.8, 35.8, 35.7, 35.2, 34.8, 34.6, 34...
Name: 2880, dtype: object

In [ ]:
df_igs['DATETIME'] = pd.to_datetime(df_igs['DATETIME'])

from datetime import datetime

dates_obj = [
    datetime(2024, 3, 20, 4, 0, 0),
    datetime(2024, 6, 21, 0, 0, 0),
    datetime(2024, 9, 22, 14, 0, 0),
    datetime(2024, 12, 21, 10, 0, 0)
]

df_igs = df_igs[df_igs['DATETIME'].isin(dates_obj)]

In [ ]:
df_igs

                DATETIME                                             TECMAP
2570 2024-03-20 04:00:00  [[19.2, 18.3, 17.6, 17.2, 17.3, 18.0, 18.9, 19...
2880 2024-06-21 00:00:00  [[35.7, 35.8, 35.8, 35.7, 35.2, 34.8, 34.6, 34...
3175 2024-09-22 14:00:00  [[24.2, 26.0, 27.4, 28.5, 29.6, 30.9, 32.5, 35...
3497 2024-12-21 10:00:00  [[8.7, 8.8, 9.3, 10.0, 10.5, 10.7, 10.4, 9.8, ...

In [ ]:
import numpy as np

In [ ]:
igs_maps = np.array(df_igs.iloc[:]['TECMAP'])

In [ ]:
np.shape(df_igs)

(4, 2)

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np.shape(np_igs_maps)

(4, 49, 23)

In [ ]:
type(np_igs_maps)

numpy.ndarray

In [ ]:
np.save('IGS_TEC_maps.npy', np_igs_maps)

In [ ]:
!ls -lh IGS_maps*

-rw------- 1 root root 36K Aug  2 22:01 igs_maps.npy

In [ ]:
df_igs['DATETIME'].values

array(['2024-03-20T04:00:00', '2024-06-21T00:00:00',
       '2024-09-22T14:00:00', '2024-12-21T10:00:00'],
      dtype='datetime64[s]')

In [ ]:
np.shape(df_igs['DATETIME'].values)

(4,)

In [ ]:
np.save('IGS_TEC_maps_datetimes.npy', df_igs['DATETIME'].values)

/usr/local/lib/python3.11/dist-packages/numpy/lib/format.py:382: UserWarning: metadata on a dtype is not saved to an npy/npz. Use another format (such as pickle) to store it.
  d['descr'] = dtype_to_descr(array.dtype)

## MAGGIA

In [ ]:
import pandas as pd

%cd '/content/drive/MyDrive'

df_maggia = pd.read_pickle('TF_MAGGIA_TEC_maps_2022_2024.pkl')

/content/drive/MyDrive

In [ ]:
df_maggia

                                                                TECMAP
DATETIME
2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 00:45:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[31464 rows x 1 columns]

In [ ]:
df_maggia = df_maggia.reset_index()

print("Columns after reset_index:")
print(df_maggia.columns.tolist())

Columns after reset_index:
['DATETIME', 'TECMAP']

In [ ]:
df_maggia['DATETIME'] = pd.to_datetime(df_maggia['DATETIME'])

from datetime import datetime

dates_obj = [
    datetime(2024, 3, 20, 4, 0, 0),
    datetime(2024, 6, 21, 0, 0, 0),
    datetime(2024, 9, 22, 14, 0, 0),
    datetime(2024, 12, 21, 10, 0, 0)
]

df_maggia = df_maggia[df_maggia['DATETIME'].isin(dates_obj)]

In [ ]:
df_maggia

                 DATETIME                                             TECMAP
20560 2024-03-20 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
23040 2024-06-21 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
26220 2024-09-22 14:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
30084 2024-12-21 10:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
import numpy as np

In [ ]:
maggia_maps = np.array(df_maggia.iloc[:]['TECMAP'])

In [ ]:
np.shape(df_maggia)

(4, 2)

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np.shape(np_maggia_maps)

(4, 241, 221)

In [ ]:
type(np_maggia_maps)

numpy.ndarray

In [ ]:
np.save('MAGGIA_TEC_maps.npy', np_maggia_maps)

In [ ]:
!ls -lh MAGGIA_maps*

-rw------- 1 root root 1.7M Aug  2 21:31 maggia_maps.npy

In [ ]:
df_maggia['DATETIME'].values

array(['2024-03-20T04:00:00', '2024-06-21T00:00:00',
       '2024-09-22T14:00:00', '2024-12-21T10:00:00'],
      dtype='datetime64[s]')

In [ ]:
np.shape(df_maggia['DATETIME'].values)

(4,)

In [ ]:
np.save('MAGGIA_TEC_maps_datetimes.npy', df_maggia['DATETIME'].values)

/usr/local/lib/python3.11/dist-packages/numpy/lib/format.py:382: UserWarning: metadata on a dtype is not saved to an npy/npz. Use another format (such as pickle) to store it.
  d['descr'] = dtype_to_descr(array.dtype)

## Nagoya

In [ ]:
import pandas as pd

%cd '/content/drive/MyDrive'

df_nagoya = pd.read_pickle('TF_Nagoya_TEC_maps_2024.pkl')

/content/drive/MyDrive

In [ ]:
df_nagoya

                                                                TECMAP
DATETIME
2024-03-01 00:00:00  [[25.810989379882812, 25.531232833862305, 25.5...
2024-03-01 00:05:00  [[25.312646865844727, 24.717082977294922, 24.7...
2024-03-01 00:10:00  [[25.669565200805664, 25.669565200805664, 25.6...
2024-03-01 00:15:00  [[24.44557762145996, 24.59754180908203, 23.801...
2024-03-01 00:20:00  [[22.925626754760742, 22.925626754760742, 24.1...
...                                                                ...
2024-12-30 23:35:00  [[26.173906326293945, 27.259140014648438, 27.2...
2024-12-30 23:40:00  [[27.0389347076416, 27.0389347076416, 27.03893...
2024-12-30 23:45:00  [[26.902502059936523, 26.72080421447754, 25.94...
2024-12-30 23:50:00  [[27.88735580444336, 27.88735580444336, 27.887...
2024-12-30 23:55:00  [[24.682987213134766, 25.294950485229492, 25.2...

[30528 rows x 1 columns]

In [ ]:
df_nagoya = df_nagoya.reset_index()

print("Colunas após reset_index:")
print(df_nagoya.columns.tolist())

Colunas após reset_index:
['DATETIME', 'TECMAP']

In [ ]:
df_nagoya['DATETIME'] = pd.to_datetime(df_nagoya['DATETIME'])

from datetime import datetime

dates_obj = [
    datetime(2024, 3, 20, 4, 0, 0),
    datetime(2024, 6, 21, 0, 0, 0),
    datetime(2024, 9, 22, 14, 0, 0),
    datetime(2024, 12, 21, 10, 0, 0)
]

df_nagoya = df_nagoya[df_nagoya['DATETIME'].isin(dates_obj)]

In [ ]:
df_nagoya

                 DATETIME                                             TECMAP
5520  2024-03-20 04:00:00  [[23.575471878051758, 23.575471878051758, 23.5...
12960 2024-06-21 00:00:00  [[5.295955181121826, 5.295955181121826, 5.2959...
20040 2024-09-22 14:00:00  [[10.517388343811035, 10.517388343811035, 10.5...
27768 2024-12-21 10:00:00  [[12.604318618774414, 12.604318618774414, 12.6...

In [ ]:
import numpy as np

In [ ]:
nagoya_maps = np.array(df_nagoya.iloc[:]['TECMAP'])

In [ ]:
np.shape(df_nagoya)

(4, 2)

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np.shape(np_nagoya_maps)

(4, 242, 221)

In [ ]:
type(np_nagoya_maps)

numpy.ndarray

In [ ]:
np.save('Nagoya_TEC_maps.npy', np_nagoya_maps)

In [ ]:
!ls -lh nagoya_maps*

ls: cannot access 'mapas_nagoya*': No such file or directory

In [ ]:
df_nagoya['DATETIME'].values

array(['2024-03-20T04:00:00', '2024-06-21T00:00:00',
       '2024-09-22T14:00:00', '2024-12-21T10:00:00'],
      dtype='datetime64[s]')

In [ ]:
np.shape(df_nagoya['DATETIME'].values)

(4,)

In [ ]:
np.save('Nagoya_TEC_maps_datetimes.npy', df_nagoya['DATETIME'].values)

/usr/local/lib/python3.11/dist-packages/numpy/lib/format.py:382: UserWarning: metadata on a dtype is not saved to an npy/npz. Use another format (such as pickle) to store it.
  d['descr'] = dtype_to_descr(array.dtype)