# Gopi TEC Manaus analysis - 09/27/2024

In [ ]:
#Download Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [ ]:
%pwd

'/content'

In [ ]:
!ls

Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip  sample_data

In [ ]:
!unzip 'Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: naus271-2024-09-27.Bias
  inflating: naus271-2024-09-27.Cmn
  inflating: naus271-2024-09-27.Std
  inflating: naus271-2024-09-27_page0.png
  inflating: naus271-2024-09-27-wbias.png
  inflating: naus336-2024-12-01.Bias
  inflating: naus336-2024-12-01.Cmn
  inflating: naus336-2024-12-01.Std
  inflating: naus336-2024-12-01_page0.png
  inflating: naus336-2024-12-01-wbias.png
  inflating: naus337-2024-12-02.Bias
  inflating: naus337-2024-12-02.Cmn
  inflating: naus337-2024-12-02.Std
  inflating: naus337-2024-12-02_page0.png
  inflating: naus337-2024-12-02-wbias.png
  inflating: naus338-2024-12-03.Bias
  inflating: naus338-2024-12-03.Cmn
  inflating: naus338-2024-12-03.Std
  inflating: naus338-2024-12-03_page0.png
  inflating: naus338-2024-12-03-wbias.png
  inflating: naus339-2024-12-04.Bias
  inflating: naus339-2024-12-04.Cmn
  inflating: naus339-2024-12-04.Std
  inflating: naus339-2024-12-04_page0.png
  inflating: naus339-2024-12-04-wbias.png
  inflating: naus340-2024-12-05.Bias
  inflating: naus340-2024-12-05.Cmn
  inflating: naus340-2024-12-05.Std
  inflating: naus340-2024-12-05_page0.png
  inflating: naus340-2024-12-05-wbias.png
  inflating: naus341-2024-12-06.Bias
  inflating: naus341-2024-12-06.Cmn
  inflating: naus341-2024-12-06.Std
  inflating: naus341-2024-12-06_page0.png
  inflating: naus341-2024-12-06-wbias.png
  inflating: naus342-2024-12-07.Bias
  inflating: naus342-2024-12-07.Cmn
  inflating: naus342-2024-12-07.Std
  inflating: naus342-2024-12-07_page0.png
  inflating: naus342-2024-12-07-wbias.png
  inflating: naus343-2024-12-08.Bias
  inflating: naus343-2024-12-08.Cmn
  inflating: naus343-2024-12-08.Std
  inflating: naus343-2024-12-08_page0.png
  inflating: naus343-2024-12-08-wbias.png
  inflating: naus344-2024-12-09.Bias
  inflating: naus344-2024-12-09.Cmn
  inflating: naus344-2024-12-09.Std
  inflating: naus344-2024-12-09_page0.png
  inflating: naus344-2024-12-09-wbias.png
  inflating: naus345-2024-12-10.Bias
  inflating: naus345-2024-12-10.Cmn
  inflating: naus345-2024-12-10.Std
  inflating: naus345-2024-12-10_page0.png
  inflating: naus345-2024-12-10-wbias.png
  inflating: naus346-2024-12-11.Bias
  inflating: naus346-2024-12-11.Cmn
  inflating: naus346-2024-12-11.Std
  inflating: naus346-2024-12-11_page0.png
  inflating: naus346-2024-12-11-wbias.png
  inflating: naus347-2024-12-12.Bias
  inflating: naus347-2024-12-12.Cmn
  inflating: naus347-2024-12-12.Std
  inflating: naus347-2024-12-12_page0.png
  inflating: naus347-2024-12-12-wbias.png
  inflating: naus348-2024-12-13.Bias
  inflating: naus348-2024-12-13.Cmn
  inflating: naus348-2024-12-13.Std
  inflating: naus348-2024-12-13_page0.png
  inflating: naus348-2024-12-13-wbias.png
  inflating: naus349-2024-12-14.Bias
  inflating: naus349-2024-12-14.Cmn
  inflating: naus349-2024-12-14.Std
  inflating: naus349-2024-12-14_page0.png
  inflating: naus349-2024-12-14-wbias.png
  inflating: naus350-2024-12-15.Bias
  inflating: naus350-2024-12-15.Cmn
  inflating: naus350-2024-12-15.Std
  inflating: naus350-2024-12-15_page0.png
  inflating: naus350-2024-12-15-wbias.png
  inflating: naus351-2024-12-16.Bias
  inflating: naus351-2024-12-16.Cmn
  inflating: naus351-2024-12-16.Std
  inflating: naus351-2024-12-16_page0.png
  inflating: naus351-2024-12-16-wbias.png
  inflating: naus352-2024-12-17.Bias
  inflating: naus352-2024-12-17.Cmn
  inflating: naus352-2024-12-17.Std
  inflating: naus352-2024-12-17_page0.png
  inflating: naus352-2024-12-17-wbias.png
  inflating: naus353-2024-12-18.Bias
  inflating: naus353-2024-12-18.Cmn
  inflating: naus353-2024-12-18.Std
  inflating: naus353-2024-12-18_page0.png
  inflating: naus353-2024-12-18-wbias.png
  inflating: naus354-2024-12-19.Bias
  inflating: naus354-2024-12-19.Cmn
  inflating: naus354-2024-12-19.Std
  inflating: naus354-2024-12-19_page0.png
  inflating: naus354-2024-12-19-wbias.png
  inflating: naus355-2024-12-20.Bias
  inflating: naus355-2024-12-20.Cmn
  inflating: naus355-2024-12-20.Std
  inflating: naus355-2024-12-20_page0.png
  inflating: naus355-2024-12-20-wbias.png
  inflating: naus356-2024-12-21.Bias
  inflating: naus356-2024-12-21.Cmn
  inflating: naus356-2024-12-21.Std
  inflating: naus356-2024-12-21_page0.png
  inflating: naus356-2024-12-21-wbias.png
  inflating: naus357-2024-12-22.Bias
  inflating: naus357-2024-12-22.Cmn
  inflating: naus357-2024-12-22.Std
  inflating: naus357-2024-12-22_page0.png
  inflating: naus357-2024-12-22-wbias.png
  inflating: naus358-2024-12-23.Bias
  inflating: naus358-2024-12-23.Cmn
  inflating: naus358-2024-12-23.Std
  inflating: naus358-2024-12-23_page0.png
  inflating: naus358-2024-12-23-wbias.png
  inflating: naus359-2024-12-24.Bias
  inflating: naus359-2024-12-24.Cmn
  inflating: naus359-2024-12-24.Std
  inflating: naus359-2024-12-24_page0.png
  inflating: naus359-2024-12-24-wbias.png
  inflating: naus360-2024-12-25.Bias
  inflating: naus360-2024-12-25.Cmn
  inflating: naus360-2024-12-25.Std
  inflating: naus360-2024-12-25_page0.png
  inflating: naus360-2024-12-25-wbias.png
  inflating: naus361-2024-12-26.Bias
  inflating: naus361-2024-12-26.Cmn
  inflating: naus361-2024-12-26.Std
  inflating: naus361-2024-12-26_page0.png
  inflating: naus361-2024-12-26-wbias.png
  inflating: naus362-2024-12-27.Bias
  inflating: naus362-2024-12-27.Cmn
  inflating: naus362-2024-12-27.Std
  inflating: naus362-2024-12-27_page0.png
  inflating: naus362-2024-12-27-wbias.png
  inflating: naus363-2024-12-28.Bias
  inflating: naus363-2024-12-28.Cmn
  inflating: naus363-2024-12-28.Std
  inflating: naus363-2024-12-28_page0.png
  inflating: naus363-2024-12-28-wbias.png
  inflating: naus364-2024-12-29.Bias
  inflating: naus364-2024-12-29.Cmn
  inflating: naus364-2024-12-29.Std
  inflating: naus364-2024-12-29_page0.png
  inflating: naus364-2024-12-29-wbias.png
  inflating: naus365-2024-12-30.Bias
  inflating: naus365-2024-12-30.Cmn
  inflating: naus365-2024-12-30.Std
  inflating: naus365-2024-12-30_page0.png
  inflating: naus365-2024-12-30-wbias.png
  inflating: naus366-2024-12-31.Bias
  inflating: naus366-2024-12-31.Cmn
  inflating: naus366-2024-12-31.Std
  inflating: naus366-2024-12-31_page0.png
  inflating: naus366-2024-12-31-wbias.png

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

df = pd.read_csv('naus271-2024-09-27.Std', sep='\s+', header=None)

df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

base_date = datetime(2024, 9, 27)

def decimal_to_time(decimal_hours):
    hours = int(decimal_hours)
    minutes = int((decimal_hours - hours) * 60)
    seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
    return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

print(df)

df.to_pickle('naus271-2024-09-27.pkl')

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-3076271457.py:5: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('naus271-2024-09-27.Std', sep='\s+', header=None)

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  18.97     6.67     -3.02
1    2024-09-27 00:01:01  19.00     8.07     -3.02
2    2024-09-27 00:01:58  19.04     7.83     -3.02
3    2024-09-27 00:03:00  19.07     8.87     -3.02
4    2024-09-27 00:04:01  19.11     8.45     -3.02
...                  ...    ...      ...       ...
1435 2024-09-27 23:55:01  11.82     7.64     -3.02
1436 2024-09-27 23:55:58  11.67     7.71     -3.02
1437 2024-09-27 23:56:59  11.53     7.79     -3.02
1438 2024-09-27 23:58:01  11.40     8.11     -3.02
1439 2024-09-27 23:58:58  11.27     8.31     -3.02

[1440 rows x 4 columns]

In [ ]:
df

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  18.97     6.67     -3.02
1    2024-09-27 00:01:01  19.00     8.07     -3.02
2    2024-09-27 00:01:58  19.04     7.83     -3.02
3    2024-09-27 00:03:00  19.07     8.87     -3.02
4    2024-09-27 00:04:01  19.11     8.45     -3.02
...                  ...    ...      ...       ...
1435 2024-09-27 23:55:01  11.82     7.64     -3.02
1436 2024-09-27 23:55:58  11.67     7.71     -3.02
1437 2024-09-27 23:56:59  11.53     7.79     -3.02
1438 2024-09-27 23:58:01  11.40     8.11     -3.02
1439 2024-09-27 23:58:58  11.27     8.31     -3.02

[1440 rows x 4 columns]

In [ ]:
import pandas as pd
from datetime import time
import numpy as np

df['DATETIME'] = pd.to_datetime(df['DATETIME'])

target_times = [
    time(0, 50),
    time(1, 0),
    time(1, 10)
]

def find_closest_time(df, target_time):

    df_times = df['DATETIME'].dt.time


    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second


    df_seconds = (df['DATETIME'].dt.hour * 3600 +
                  df['DATETIME'].dt.minute * 60 +
                  df['DATETIME'].dt.second)


    time_diff = np.abs(df_seconds - target_seconds)


    closest_idx = time_diff.idxmin()

    return df.loc[[closest_idx]]

df_filtered_list = []
for target_time in target_times:
    closest_row = find_closest_time(df, target_time)
    df_filtered_list.append(closest_row)

df_filtered = pd.concat(df_filtered_list, ignore_index=True)

df_filtered = df_filtered.sort_values('DATETIME').reset_index(drop=True)

print("DataFrame filtered for closest times to 00:50, 01:00 and 01:10:")
print(df_filtered)

print("\nDifference from target times:")
for i, target_time in enumerate(target_times):
    actual_time = df_filtered.iloc[i]['DATETIME'].time()
    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second
    actual_seconds = actual_time.hour * 3600 + actual_time.minute * 60 + actual_time.second
    diff_seconds = abs(actual_seconds - target_seconds)
    print(f"Target: {target_time} | Actual: {actual_time} | Difference: {diff_seconds} seconds")

DataFrame filtered for closest times to 00:50, 01:00 and 01:10:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-09-27 00:49:58  19.83     2.12     -3.02
1 2024-09-27 01:00:00  19.68     1.55     -3.02
2 2024-09-27 01:10:01  19.47     2.55     -3.02

Difference from target times:
Target: 00:50:00 | Actual: 00:49:58 | Difference: 2 seconds
Target: 01:00:00 | Actual: 01:00:00 | Difference: 0 seconds
Target: 01:10:00 | Actual: 01:10:01 | Difference: 1 seconds

In [ ]:
reference_time = pd.Timestamp('2024-09-27 00:50:00')
wide_window = timedelta(minutes=5)
df_proximos = df[(df['DATETIME'] >= reference_time - wide_window) &
                 (df['DATETIME'] <= reference_time + wide_window)]
print("Records close to 00:50:")
print(df_proximos[['DATETIME', 'TEC']])

Records close to 00:50:
              DATETIME    TEC
45 2024-09-27 00:45:00  19.88
46 2024-09-27 00:46:01  19.87
47 2024-09-27 00:46:58  19.86
48 2024-09-27 00:48:00  19.85
49 2024-09-27 00:49:01  19.84
50 2024-09-27 00:49:58  19.83
51 2024-09-27 00:51:00  19.81
52 2024-09-27 00:52:01  19.80
53 2024-09-27 00:52:58  19.79
54 2024-09-27 00:54:00  19.77

In [ ]:
print(df.iloc[[50, 60, 70]][['DATETIME', 'TEC']])

              DATETIME    TEC
50 2024-09-27 00:49:58  19.83
60 2024-09-27 01:00:00  19.68
70 2024-09-27 01:10:01  19.47

In [ ]:
df.to_pickle('naus271-2024-09-27_selected_0050_to_0110.pkl')

# EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_embrace_maps_2024

                                                                TECMAP
DATETIME
2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[16704 rows x 1 columns]

In [ ]:
data = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{data} {time}' for time in times]

result = df_embrace_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(3, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = Embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec = Embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

## 00:50

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  38.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  31.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  45.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  26.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  38.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  31.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  45.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  26.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.06 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x =   2.44 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -3.02 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y =   0.98 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 38.0 + 0.500204* 31.0 + 0.010752* 45.0 + 0.477788* 26.0
   Value =   0.4277 +  15.5063 +   0.4838 +  12.4225
   Value = 28.840377

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 28.8404
============================================================

## 01:00

In [ ]:
embrace_tec.tec_map = np_embrace_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  35.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  32.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  39.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  32.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  35.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  32.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  39.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  32.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.06 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x =   2.44 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -3.02 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y =   0.98 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 35.0 + 0.500204* 32.0 + 0.010752* 39.0 + 0.477788* 32.0
   Value =   0.3940 +  16.0065 +   0.4193 +  15.2892
   Value = 32.109031

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 32.1090
============================================================

## 01:10

In [ ]:
embrace_tec.tec_map = np_embrace_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  37.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  34.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  37.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  34.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  37.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  34.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  37.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  34.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.06 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x =   2.44 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -3.02 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y =   0.98 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 37.0 + 0.500204* 34.0 + 0.010752* 37.0 + 0.477788* 34.0
   Value =   0.4165 +  17.0069 +   0.3978 +  16.2448
   Value = 34.066024

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 34.0660
============================================================

# MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024

                 DATETIME                                             TECMAP
0     2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2024-09-05 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
15619 2024-12-31 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15620 2024-12-31 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15621 2024-12-31 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15622 2024-12-31 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15623 2024-12-31 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[15624 rows x 2 columns]

In [ ]:
df_maggia_maps_2024.set_index('DATETIME', inplace=True)

In [ ]:
df_maggia_maps_2024

                                                                TECMAP
DATETIME
2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-31 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-31 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-31 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-31 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-31 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[15624 rows x 1 columns]

In [ ]:
data = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{data} {hourrio}' for hourrio in times]

result = df_maggia_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
maggia_maps

array([list([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.62400055, 48.20500183, 47.78499985, ..., 19.22900009,
         18.24799919, 16.43799973],
        [48.70800018, 48.36100006, 48.0019989 , ..., 18.61000061,
         17.57699966, 16.23500061],
        [48.7120018 , 48.42399979, 48.11700058, ..., 17.99799919,
         16.95499992, 16.04000092]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [43.38299942, 43.10300064, 43.09799957, ..., 19.18000031,
         18.25300026, 17.1609993 ],
        [43.85400009, 43.58499908, 43.34700012, ..., 18.40399933,
         17.62000084, 16.44000053],
        [44.19599915, 43.94599915, 43.70500183, ..., 17.70899963,
         16.94099998, 15.69099998]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.6230011 , 41.29999924, 41.13800049, ..., 18.74399948,
         18.67399979, 18.62999916],
        [42.11100006, 41.79499817, 41.5340004 , ..., 18.92099953,
         18.80699921, 17.86199951],
        [42.46699905, 42.18199921, 41.9280014 , ..., 18.2670002 ,
         17.5340004 , 16.79299927]]])

In [ ]:
np_maggia_maps.shape

(3, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:

    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(tec_obj, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = tec_obj.extent
        lat_step, lon_step = tec_obj.lat_step, tec_obj.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, tec_obj.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, tec_obj.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, tec_obj.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, tec_obj.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

class Maggia(TecMap):

    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
maggia_tec = Maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

## 00:50

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  41.2
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  40.5
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  41.2
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  40.9

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  41.2
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  40.5
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  41.2
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  40.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.06 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x =   0.44 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -3.02 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y =   0.48 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 41.2 + 0.040796* 40.5 + 0.104996* 41.2 + 0.849164* 40.9
   Value =   0.2077 +   1.6537 +   4.3243 +  34.7436
   Value = 40.929291

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 40.9293
============================================================

## 01:00

In [ ]:
maggia_tec.tec_map = np_maggia_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  39.6
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  39.9
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  39.0
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  39.3

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  39.6
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  39.9
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  39.0
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  39.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.06 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x =   0.44 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -3.02 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y =   0.48 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 39.6 + 0.040796* 39.9 + 0.104996* 39.0 + 0.849164* 39.3
   Value =   0.1997 +   1.6291 +   4.0937 +  33.3314
   Value = 39.253821

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 39.2538
============================================================

## 01:10

In [ ]:
maggia_tec.tec_map = np_maggia_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  44.9
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  44.9
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  44.9
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  44.9

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  44.9
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  44.9
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  44.9
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  44.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.06 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x =   0.44 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -3.02 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y =   0.48 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 44.9 + 0.040796* 44.9 + 0.104996* 44.9 + 0.849164* 44.9
   Value =   0.2266 +   1.8324 +   4.7160 +  38.1411
   Value = 44.916000

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 44.9160
============================================================