# Gopi TEC Manaus analysis - December/2024

In [1]:
#Download Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [2]:
!gdown '16wKjT_0gSP07GKQH7fsgHlH2kVOGGlZs'

Downloading...
From (original): https://drive.google.com/uc?id=16wKjT_0gSP07GKQH7fsgHlH2kVOGGlZs
From (redirected): https://drive.google.com/uc?id=16wKjT_0gSP07GKQH7fsgHlH2kVOGGlZs&confirm=t&uuid=d3b33f3a-2e04-4821-a0d0-46edc4c46c28
To: /content/Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip
100% 55.0M/55.0M [00:00<00:00, 85.9MB/s]

In [3]:
%pwd

'/content'

In [4]:
!ls

Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip  sample_data

In [5]:
!unzip 'Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_NAUS_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: naus271-2024-09-27.Bias
  inflating: naus271-2024-09-27.Cmn
  inflating: naus271-2024-09-27.Std
  inflating: naus271-2024-09-27_page0.png
  inflating: naus271-2024-09-27-wbias.png
  inflating: naus336-2024-12-01.Bias
  inflating: naus336-2024-12-01.Cmn
  inflating: naus336-2024-12-01.Std
  inflating: naus336-2024-12-01_page0.png
  inflating: naus336-2024-12-01-wbias.png
  inflating: naus337-2024-12-02.Bias
  inflating: naus337-2024-12-02.Cmn
  inflating: naus337-2024-12-02.Std
  inflating: naus337-2024-12-02_page0.png
  inflating: naus337-2024-12-02-wbias.png
  inflating: naus338-2024-12-03.Bias
  inflating: naus338-2024-12-03.Cmn
  inflating: naus338-2024-12-03.Std
  inflating: naus338-2024-12-03_page0.png
  inflating: naus338-2024-12-03-wbias.png
  inflating: naus339-2024-12-04.Bias
  inflating: naus339-2024-12-04.Cmn
  inflating: naus339-2024-12-04.Std
  inflating: naus339-2024-12-04_page0.png
  inflating: naus339-2024-12-04-wbias.png
  inflating: naus340-2024-12-05.Bias
  inflating: naus340-2024-12-05.Cmn
  inflating: naus340-2024-12-05.Std
  inflating: naus340-2024-12-05_page0.png
  inflating: naus340-2024-12-05-wbias.png
  inflating: naus341-2024-12-06.Bias
  inflating: naus341-2024-12-06.Cmn
  inflating: naus341-2024-12-06.Std
  inflating: naus341-2024-12-06_page0.png
  inflating: naus341-2024-12-06-wbias.png
  inflating: naus342-2024-12-07.Bias
  inflating: naus342-2024-12-07.Cmn
  inflating: naus342-2024-12-07.Std
  inflating: naus342-2024-12-07_page0.png
  inflating: naus342-2024-12-07-wbias.png
  inflating: naus343-2024-12-08.Bias
  inflating: naus343-2024-12-08.Cmn
  inflating: naus343-2024-12-08.Std
  inflating: naus343-2024-12-08_page0.png
  inflating: naus343-2024-12-08-wbias.png
  inflating: naus344-2024-12-09.Bias
  inflating: naus344-2024-12-09.Cmn
  inflating: naus344-2024-12-09.Std
  inflating: naus344-2024-12-09_page0.png
  inflating: naus344-2024-12-09-wbias.png
  inflating: naus345-2024-12-10.Bias
  inflating: naus345-2024-12-10.Cmn
  inflating: naus345-2024-12-10.Std
  inflating: naus345-2024-12-10_page0.png
  inflating: naus345-2024-12-10-wbias.png
  inflating: naus346-2024-12-11.Bias
  inflating: naus346-2024-12-11.Cmn
  inflating: naus346-2024-12-11.Std
  inflating: naus346-2024-12-11_page0.png
  inflating: naus346-2024-12-11-wbias.png
  inflating: naus347-2024-12-12.Bias
  inflating: naus347-2024-12-12.Cmn
  inflating: naus347-2024-12-12.Std
  inflating: naus347-2024-12-12_page0.png
  inflating: naus347-2024-12-12-wbias.png
  inflating: naus348-2024-12-13.Bias
  inflating: naus348-2024-12-13.Cmn
  inflating: naus348-2024-12-13.Std
  inflating: naus348-2024-12-13_page0.png
  inflating: naus348-2024-12-13-wbias.png
  inflating: naus349-2024-12-14.Bias
  inflating: naus349-2024-12-14.Cmn
  inflating: naus349-2024-12-14.Std
  inflating: naus349-2024-12-14_page0.png
  inflating: naus349-2024-12-14-wbias.png
  inflating: naus350-2024-12-15.Bias
  inflating: naus350-2024-12-15.Cmn
  inflating: naus350-2024-12-15.Std
  inflating: naus350-2024-12-15_page0.png
  inflating: naus350-2024-12-15-wbias.png
  inflating: naus351-2024-12-16.Bias
  inflating: naus351-2024-12-16.Cmn
  inflating: naus351-2024-12-16.Std
  inflating: naus351-2024-12-16_page0.png
  inflating: naus351-2024-12-16-wbias.png
  inflating: naus352-2024-12-17.Bias
  inflating: naus352-2024-12-17.Cmn
  inflating: naus352-2024-12-17.Std
  inflating: naus352-2024-12-17_page0.png
  inflating: naus352-2024-12-17-wbias.png
  inflating: naus353-2024-12-18.Bias
  inflating: naus353-2024-12-18.Cmn
  inflating: naus353-2024-12-18.Std
  inflating: naus353-2024-12-18_page0.png
  inflating: naus353-2024-12-18-wbias.png
  inflating: naus354-2024-12-19.Bias
  inflating: naus354-2024-12-19.Cmn
  inflating: naus354-2024-12-19.Std
  inflating: naus354-2024-12-19_page0.png
  inflating: naus354-2024-12-19-wbias.png
  inflating: naus355-2024-12-20.Bias
  inflating: naus355-2024-12-20.Cmn
  inflating: naus355-2024-12-20.Std
  inflating: naus355-2024-12-20_page0.png
  inflating: naus355-2024-12-20-wbias.png
  inflating: naus356-2024-12-21.Bias
  inflating: naus356-2024-12-21.Cmn
  inflating: naus356-2024-12-21.Std
  inflating: naus356-2024-12-21_page0.png
  inflating: naus356-2024-12-21-wbias.png
  inflating: naus357-2024-12-22.Bias
  inflating: naus357-2024-12-22.Cmn
  inflating: naus357-2024-12-22.Std
  inflating: naus357-2024-12-22_page0.png
  inflating: naus357-2024-12-22-wbias.png
  inflating: naus358-2024-12-23.Bias
  inflating: naus358-2024-12-23.Cmn
  inflating: naus358-2024-12-23.Std
  inflating: naus358-2024-12-23_page0.png
  inflating: naus358-2024-12-23-wbias.png
  inflating: naus359-2024-12-24.Bias
  inflating: naus359-2024-12-24.Cmn
  inflating: naus359-2024-12-24.Std
  inflating: naus359-2024-12-24_page0.png
  inflating: naus359-2024-12-24-wbias.png
  inflating: naus360-2024-12-25.Bias
  inflating: naus360-2024-12-25.Cmn
  inflating: naus360-2024-12-25.Std
  inflating: naus360-2024-12-25_page0.png
  inflating: naus360-2024-12-25-wbias.png
  inflating: naus361-2024-12-26.Bias
  inflating: naus361-2024-12-26.Cmn
  inflating: naus361-2024-12-26.Std
  inflating: naus361-2024-12-26_page0.png
  inflating: naus361-2024-12-26-wbias.png
  inflating: naus362-2024-12-27.Bias
  inflating: naus362-2024-12-27.Cmn
  inflating: naus362-2024-12-27.Std
  inflating: naus362-2024-12-27_page0.png
  inflating: naus362-2024-12-27-wbias.png
  inflating: naus363-2024-12-28.Bias
  inflating: naus363-2024-12-28.Cmn
  inflating: naus363-2024-12-28.Std
  inflating: naus363-2024-12-28_page0.png
  inflating: naus363-2024-12-28-wbias.png
  inflating: naus364-2024-12-29.Bias
  inflating: naus364-2024-12-29.Cmn
  inflating: naus364-2024-12-29.Std
  inflating: naus364-2024-12-29_page0.png
  inflating: naus364-2024-12-29-wbias.png
  inflating: naus365-2024-12-30.Bias
  inflating: naus365-2024-12-30.Cmn
  inflating: naus365-2024-12-30.Std
  inflating: naus365-2024-12-30_page0.png
  inflating: naus365-2024-12-30-wbias.png
  inflating: naus366-2024-12-31.Bias
  inflating: naus366-2024-12-31.Cmn
  inflating: naus366-2024-12-31.Std
  inflating: naus366-2024-12-31_page0.png
  inflating: naus366-2024-12-31-wbias.png

In [6]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta
import glob

data_dir = '.'

std_files = glob.glob(os.path.join(data_dir, 'naus3*-2024-12-*.Std'))

std_files.sort()

dfs = []

for file_path in std_files:
    try:

        filename = os.path.basename(file_path)
        print(f"Processing {filename}")

        date_parts = filename.replace('.Std', '').split('-')
        year = int(date_parts[1])
        month = int(date_parts[2])
        day = int(date_parts[3])
        base_date = datetime(year, month, day)

        df = pd.read_csv(file_path, sep='\s+', header=None)

        df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

        def decimal_to_time(decimal_hours):
            hours = int(decimal_hours)
            minutes = int((decimal_hours - hours) * 60)
            seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
            return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

        df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

        df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
        df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

        df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
        df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

        dfs.append(df)

    except Exception as e:
        print(f"Erro ao processar o arquivo {file_path}: {e}")

if dfs:
    combined_df = pd.concat(dfs, ignore_index=True)

    combined_df = combined_df.sort_values('DATETIME')

    combined_df.to_pickle('naus_dec_2024_complete.pkl')

    print(f"DataFrame combinado criado com {len(combined_df)} linhas")
    print("Primeiras 5 linhas:")
    print(combined_df.head())

    print("\nPeríodo coberto pelos dados:")
    print(f"Início: {combined_df['DATETIME'].min()}")
    print(f"Fim: {combined_df['DATETIME'].max()}")
    print(f"Total de dias: {(combined_df['DATETIME'].max() - combined_df['DATETIME'].min()).days + 1}")

    dias_presentes = combined_df['DATETIME'].dt.date.unique()
    print(f"\nTotal de dias com dados: {len(dias_presentes)}")
    print("Dias presentes:", sorted(dias_presentes))
else:
    print("Nenhum arquivo foi processado com sucesso.")

Processing naus336-2024-12-01.Std
Processing naus337-2024-12-02.Std
Processing naus338-2024-12-03.Std
Processing naus339-2024-12-04.Std
Processing naus340-2024-12-05.Std
Processing naus341-2024-12-06.Std
Processing naus342-2024-12-07.Std
Processing naus343-2024-12-08.Std
Processing naus344-2024-12-09.Std
Processing naus345-2024-12-10.Std
Processing naus346-2024-12-11.Std
Processing naus347-2024-12-12.Std
Processing naus348-2024-12-13.Std
Processing naus349-2024-12-14.Std
Processing naus350-2024-12-15.Std
Processing naus351-2024-12-16.Std
Processing naus352-2024-12-17.Std
Processing naus353-2024-12-18.Std
Processing naus354-2024-12-19.Std
Processing naus355-2024-12-20.Std
Processing naus356-2024-12-21.Std
Processing naus357-2024-12-22.Std
Processing naus358-2024-12-23.Std
Processing naus359-2024-12-24.Std
Processing naus360-2024-12-25.Std
Processing naus361-2024-12-26.Std
Processing naus362-2024-12-27.Std
Processing naus363-2024-12-28.Std
Processing naus364-2024-12-29.Std
Processing naus365-2024-12-30.Std
Processing naus366-2024-12-31.Std
DataFrame combinado criado com 44640 linhas
Primeiras 5 linhas:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-12-01 00:00:00  23.79     6.53     -3.02
1 2024-12-01 00:01:01  23.78     6.92     -3.02
2 2024-12-01 00:01:58  23.75     5.67     -3.02
3 2024-12-01 00:03:00  23.72     5.02     -3.02
4 2024-12-01 00:04:01  23.69     4.37     -3.02

Período coberto pelos dados:
Início: 2024-12-01 00:00:00
Fim: 2024-12-31 23:58:58
Total de dias: 31

Total de dias com dados: 31
Dias presentes: [datetime.date(2024, 12, 1), datetime.date(2024, 12, 2), datetime.date(2024, 12, 3), datetime.date(2024, 12, 4), datetime.date(2024, 12, 5), datetime.date(2024, 12, 6), datetime.date(2024, 12, 7), datetime.date(2024, 12, 8), datetime.date(2024, 12, 9), datetime.date(2024, 12, 10), datetime.date(2024, 12, 11), datetime.date(2024, 12, 12), datetime.date(2024, 12, 13), datetime.date(2024, 12, 14), datetime.date(2024, 12, 15), datetime.date(2024, 12, 16), datetime.date(2024, 12, 17), datetime.date(2024, 12, 18), datetime.date(2024, 12, 19), datetime.date(2024, 12, 20), datetime.date(2024, 12, 21), datetime.date(2024, 12, 22), datetime.date(2024, 12, 23), datetime.date(2024, 12, 24), datetime.date(2024, 12, 25), datetime.date(2024, 12, 26), datetime.date(2024, 12, 27), datetime.date(2024, 12, 28), datetime.date(2024, 12, 29), datetime.date(2024, 12, 30), datetime.date(2024, 12, 31)]

In [7]:
combined_df

                 DATETIME    TEC  TEC_STD  LATITUDE
0     2024-12-01 00:00:00  23.79     6.53     -3.02
1     2024-12-01 00:01:01  23.78     6.92     -3.02
2     2024-12-01 00:01:58  23.75     5.67     -3.02
3     2024-12-01 00:03:00  23.72     5.02     -3.02
4     2024-12-01 00:04:01  23.69     4.37     -3.02
...                   ...    ...      ...       ...
44635 2024-12-31 23:55:01  38.49     5.38     -3.02
44636 2024-12-31 23:55:58  38.29     5.31     -3.02
44637 2024-12-31 23:56:59  38.10     5.22     -3.02
44638 2024-12-31 23:58:01  37.93     5.44     -3.02
44639 2024-12-31 23:58:58  37.76     5.49     -3.02

[44640 rows x 4 columns]

## 18:00

In [8]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('naus_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_PEAKS_at_precise_interval(hour_start, minute_start, second_start, hour_end, minute_end, second_end):

    interval_label = f"{hour_start:02d}:{minute_start:02d}:{second_start:02d}-{hour_end:02d}:{minute_end:02d}:{second_end:02d}"

    print(f"\n{'='*80}")
    print(f"ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE {interval_label} UTC")
    print(f"{'='*80}")

    start_timestamps = []
    end_timestamps = []

    for day in df_clean['DATETIME'].dt.date.unique():
        start_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_start, minute_start, second_start))
        end_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_end, minute_end, second_end))

    df_interval = pd.DataFrame()
    for start, end in zip(start_timestamps, end_timestamps):
        day_interval = df_clean[(df_clean['DATETIME'] >= start) & (df_clean['DATETIME'] <= end)]
        df_interval = pd.concat([df_interval, day_interval])

    print(f"Filtering for times between {interval_label} UTC: {len(df_interval)} remaining points")

    if len(df_interval) == 0:
        print(f"ATTENTION: No data found in the range {interval_label} UTC!")
        return pd.DataFrame(), []

    df_interval['DATE'] = df_interval['DATETIME'].dt.date

    daily_max = df_interval.loc[df_interval.groupby('DATE')['TEC'].idxmax()]
    print(f"Unique days with data in range {interval_label}: {len(daily_max)}")

    if len(daily_max) >= 5:
        top_5_days = daily_max.nlargest(5, 'TEC').reset_index(drop=True)
    else:
        top_5_days = daily_max.sort_values('TEC', ascending=False).reset_index(drop=True)
        print(f"ATTENTION: Only {len(top_5_days)} days have data in this time range!")

    print(f"\n{len(top_5_days)} HIGHEST TEC VALUES IN THE INTERVAL {interval_label} (ONE PER DAY):")
    for idx, row in top_5_days.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_5_days.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_5_days) > 0:
        print(f"\nSUMMARY TABLE OF TEC PEAKS IN THE INTERVAL {interval_label} UTC:")
        print("-" * 100)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<12}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration'}")
        print("-" * 100)

        for idx, row in top_5_days.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M:%S'):<12}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration}")
        print("-" * 100)

    return top_5_days, sequences

def analyze_PEAKS_at_interval(hour_start, minute_start, hour_end, minute_end):

    return analyze_PEAKS_at_precise_interval(hour_start, minute_start, 0, hour_end, minute_end, 0)

print("\n\n" + "*"*40 + " ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC " + "*"*40)
top_5_exact_18h, sequences_exact_18h = analyze_PEAKS_at_precise_interval(17, 59, 55, 18, 0, 5)

print("\nAnálise concluída!")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Analysing 44640 points after removing missing values


**************************************** ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC ****************************************

================================================================================
ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE 17:59:55-18:00:05 UTC
================================================================================
Filtering for times between 17:59:55-18:00:05 UTC: 31 remaining points
Unique days with data in range 17:59:55-18:00:05: 31

5 HIGHEST TEC VALUES IN THE INTERVAL 17:59:55-18:00:05 (ONE PER DAY):
1. TEC: 79.52 ± 3.82 TECU, Date/Time: 2024-12-01 18:00:00, Latitude: -3.02
2. TEC: 78.79 ± 1.91 TECU, Date/Time: 2024-12-02 18:00:00, Latitude: -3.02
3. TEC: 77.72 ± 1.76 TECU, Date/Time: 2024-12-03 18:00:00, Latitude: -3.02
4. TEC: 75.81 ± 3.27 TECU, Date/Time: 2024-12-04 18:00:00, Latitude: -3.02
5. TEC: 74.64 ± 2.25 TECU, Date/Time: 2024-12-27 18:00:00, Latitude: -3.02

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 79.52 ± 3.82) has a sequence of 3 high values:
  1. 2024-12-01 17:58:58: 79.44 ± 3.82 TECU (99.9% do Peak)
  2. 2024-12-01 18:00:00: 79.52 ± 3.82 TECU (100.0% do Peak)
  3. 2024-12-01 18:01:01: 79.60 ± 3.82 TECU (100.1% do Peak)

Peak #2 (TEC = 78.79 ± 1.91) has a sequence of 3 high values:
  1. 2024-12-02 17:58:58: 78.82 ± 1.90 TECU (100.0% do Peak)
  2. 2024-12-02 18:00:00: 78.79 ± 1.91 TECU (100.0% do Peak)
  3. 2024-12-02 18:01:01: 78.76 ± 1.92 TECU (100.0% do Peak)

Peak #3 (TEC = 77.72 ± 1.76) has a sequence of 3 high values:
  1. 2024-12-03 17:58:58: 77.74 ± 1.83 TECU (100.0% do Peak)
  2. 2024-12-03 18:00:00: 77.72 ± 1.76 TECU (100.0% do Peak)
  3. 2024-12-03 18:01:01: 77.69 ± 1.69 TECU (100.0% do Peak)

Peak #4 (TEC = 75.81 ± 3.27) has a sequence of 3 high values:
  1. 2024-12-04 17:58:58: 75.79 ± 3.26 TECU (100.0% do Peak)
  2. 2024-12-04 18:00:00: 75.81 ± 3.27 TECU (100.0% do Peak)
  3. 2024-12-04 18:01:01: 75.83 ± 3.29 TECU (100.0% do Peak)

Peak #5 (TEC = 74.64 ± 2.25) has a sequence of 3 high values:
  1. 2024-12-27 17:58:58: 74.65 ± 2.35 TECU (100.0% do Peak)
  2. 2024-12-27 18:00:00: 74.64 ± 2.25 TECU (100.0% do Peak)
  3. 2024-12-27 18:01:01: 74.62 ± 2.14 TECU (100.0% do Peak)

SUMMARY TABLE OF TEC PEAKS IN THE INTERVAL 17:59:55-18:00:05 UTC:
----------------------------------------------------------------------------------------------------
Rank Data        UTC time    TEC       TEC_STD   Sequence       Sequence Duration
----------------------------------------------------------------------------------------------------
1    01/12/2024  18:00:00    79.52    3.82    Sim            2.0 min
2    02/12/2024  18:00:00    78.79    1.91    Sim            2.0 min
3    03/12/2024  18:00:00    77.72    1.76    Sim            2.0 min
4    04/12/2024  18:00:00    75.81    3.27    Sim            2.0 min
5    27/12/2024  18:00:00    74.64    2.25    Sim            2.0 min
----------------------------------------------------------------------------------------------------

Análise concluída!

## DECEMBER

In [9]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('naus_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_top_PEAKS(top_n=200):

    print(f"\n{'='*80}")
    print(f"TOP {top_n} PEAK ANALYSIS OF TEC (ALL TIMES)")
    print(f"{'='*80}")

    df_clean['DATE'] = df_clean['DATETIME'].dt.date

    top_n_PEAKS = df_clean.nlargest(top_n, 'TEC').reset_index(drop=True)

    print(f"\nTOP {top_n} HIGHEST VALUES OF TEC (ALL TIMES):")
    for idx, row in top_n_PEAKS.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_n_PEAKS.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_n_PEAKS) > 0:
        print(f"\nSUMMARY TABLE OF TOP {top_n} TEC PEAKS:")
        print("-" * 110)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration':<20}{'Horário do dia'}")
        print("-" * 110)

        for idx, row in top_n_PEAKS.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            hour = row['DATETIME'].hour
            minute = row['DATETIME'].minute
            time_category = f"{hour:02d}:{minute:02d} UTC"

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M'):<10}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration:<20}{time_category}")
        print("-" * 110)

    return top_n_PEAKS, sequences

print("\n\n" + "*"*40 + "TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) " + "*"*40)
top_n_PEAKS, sequences = analyze_top_PEAKS(top_n=200)

print("\nAnálise concluída!")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Analysing 44640 points after removing missing values


****************************************TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) ****************************************

================================================================================
TOP 200 PEAK ANALYSIS OF TEC (ALL TIMES)
================================================================================

TOP 200 HIGHEST VALUES OF TEC (ALL TIMES):
1. TEC: 81.24 ± 4.22 TECU, Date/Time: 2024-12-01 18:34:58, Latitude: -3.02
2. TEC: 81.24 ± 3.54 TECU, Date/Time: 2024-12-01 18:36:00, Latitude: -3.02
3. TEC: 81.23 ± 4.06 TECU, Date/Time: 2024-12-01 18:33:00, Latitude: -3.02
4. TEC: 81.23 ± 4.01 TECU, Date/Time: 2024-12-01 18:34:01, Latitude: -3.02
5. TEC: 81.23 ± 3.87 TECU, Date/Time: 2024-12-01 18:37:01, Latitude: -3.02
6. TEC: 81.23 ± 3.82 TECU, Date/Time: 2024-12-01 18:37:58, Latitude: -3.02
7. TEC: 81.23 ± 3.77 TECU, Date/Time: 2024-12-01 18:38:59, Latitude: -3.02
8. TEC: 81.22 ± 4.10 TECU, Date/Time: 2024-12-01 18:31:58, Latitude: -3.02
9. TEC: 81.22 ± 3.71 TECU, Date/Time: 2024-12-01 18:40:01, Latitude: -3.02
10. TEC: 81.21 ± 4.15 TECU, Date/Time: 2024-12-01 18:31:01, Latitude: -3.02
11. TEC: 81.21 ± 3.90 TECU, Date/Time: 2024-12-01 18:40:58, Latitude: -3.02
12. TEC: 81.20 ± 4.18 TECU, Date/Time: 2024-12-01 18:30:00, Latitude: -3.02
13. TEC: 81.20 ± 3.22 TECU, Date/Time: 2024-12-01 18:41:59, Latitude: -3.02
14. TEC: 81.19 ± 3.51 TECU, Date/Time: 2024-12-01 18:43:01, Latitude: -3.02
15. TEC: 81.18 ± 4.20 TECU, Date/Time: 2024-12-01 18:28:58, Latitude: -3.02
16. TEC: 81.18 ± 3.45 TECU, Date/Time: 2024-12-01 18:43:58, Latitude: -3.02
17. TEC: 81.16 ± 4.22 TECU, Date/Time: 2024-12-01 18:28:01, Latitude: -3.02
18. TEC: 81.16 ± 3.40 TECU, Date/Time: 2024-12-01 18:45:00, Latitude: -3.02
19. TEC: 81.15 ± 3.16 TECU, Date/Time: 2024-12-01 18:46:01, Latitude: -3.02
20. TEC: 81.14 ± 4.23 TECU, Date/Time: 2024-12-01 18:26:59, Latitude: -3.02
21. TEC: 81.14 ± 3.24 TECU, Date/Time: 2024-12-01 18:46:58, Latitude: -3.02
22. TEC: 81.12 ± 0.56 TECU, Date/Time: 2024-12-01 18:48:00, Latitude: -3.02
23. TEC: 81.11 ± 4.22 TECU, Date/Time: 2024-12-01 18:25:58, Latitude: -3.02
24. TEC: 81.11 ± 0.60 TECU, Date/Time: 2024-12-01 18:49:01, Latitude: -3.02
25. TEC: 81.10 ± 0.66 TECU, Date/Time: 2024-12-01 18:49:58, Latitude: -3.02
26. TEC: 81.09 ± 4.20 TECU, Date/Time: 2024-12-01 18:25:01, Latitude: -3.02
27. TEC: 81.08 ± 0.72 TECU, Date/Time: 2024-12-01 18:51:00, Latitude: -3.02
28. TEC: 81.07 ± 0.78 TECU, Date/Time: 2024-12-01 18:52:01, Latitude: -3.02
29. TEC: 81.06 ± 0.83 TECU, Date/Time: 2024-12-01 18:52:58, Latitude: -3.02
30. TEC: 81.05 ± 4.19 TECU, Date/Time: 2024-12-01 18:23:59, Latitude: -3.02
31. TEC: 81.04 ± 0.89 TECU, Date/Time: 2024-12-01 18:53:59, Latitude: -3.02
32. TEC: 81.03 ± 0.95 TECU, Date/Time: 2024-12-01 18:55:01, Latitude: -3.02
33. TEC: 81.02 ± 4.17 TECU, Date/Time: 2024-12-01 18:22:58, Latitude: -3.02
34. TEC: 81.02 ± 1.00 TECU, Date/Time: 2024-12-01 18:55:58, Latitude: -3.02
35. TEC: 81.01 ± 1.06 TECU, Date/Time: 2024-12-01 18:56:59, Latitude: -3.02
36. TEC: 80.99 ± 1.12 TECU, Date/Time: 2024-12-01 18:58:01, Latitude: -3.02
37. TEC: 80.98 ± 4.13 TECU, Date/Time: 2024-12-01 18:22:01, Latitude: -3.02
38. TEC: 80.98 ± 1.19 TECU, Date/Time: 2024-12-01 18:58:58, Latitude: -3.02
39. TEC: 80.97 ± 0.87 TECU, Date/Time: 2024-12-01 19:00:00, Latitude: -3.02
40. TEC: 80.96 ± 0.60 TECU, Date/Time: 2024-12-01 19:01:01, Latitude: -3.02
41. TEC: 80.95 ± 0.61 TECU, Date/Time: 2024-12-01 19:01:58, Latitude: -3.02
42. TEC: 80.94 ± 4.10 TECU, Date/Time: 2024-12-01 18:21:00, Latitude: -3.02
43. TEC: 80.94 ± 0.64 TECU, Date/Time: 2024-12-01 19:03:00, Latitude: -3.02
44. TEC: 80.93 ± 0.63 TECU, Date/Time: 2024-12-01 19:04:01, Latitude: -3.02
45. TEC: 80.92 ± 0.65 TECU, Date/Time: 2024-12-01 19:04:58, Latitude: -3.02
46. TEC: 80.91 ± 0.69 TECU, Date/Time: 2024-12-01 19:06:00, Latitude: -3.02
47. TEC: 80.90 ± 0.67 TECU, Date/Time: 2024-12-01 19:07:01, Latitude: -3.02
48. TEC: 80.89 ± 4.08 TECU, Date/Time: 2024-12-01 18:19:58, Latitude: -3.02
49. TEC: 80.89 ± 0.73 TECU, Date/Time: 2024-12-01 19:07:58, Latitude: -3.02
50. TEC: 80.88 ± 0.81 TECU, Date/Time: 2024-12-01 19:08:59, Latitude: -3.02
51. TEC: 80.87 ± 0.84 TECU, Date/Time: 2024-12-01 19:10:01, Latitude: -3.02
52. TEC: 80.85 ± 4.04 TECU, Date/Time: 2024-12-01 18:19:01, Latitude: -3.02
53. TEC: 80.85 ± 0.92 TECU, Date/Time: 2024-12-01 19:10:58, Latitude: -3.02
54. TEC: 80.84 ± 0.99 TECU, Date/Time: 2024-12-01 19:11:59, Latitude: -3.02
55. TEC: 80.83 ± 1.02 TECU, Date/Time: 2024-12-01 19:13:01, Latitude: -3.02
56. TEC: 80.81 ± 1.06 TECU, Date/Time: 2024-12-01 19:13:58, Latitude: -3.02
57. TEC: 80.80 ± 1.08 TECU, Date/Time: 2024-12-01 19:15:00, Latitude: -3.02
58. TEC: 80.79 ± 4.01 TECU, Date/Time: 2024-12-01 18:18:00, Latitude: -3.02
59. TEC: 80.78 ± 1.07 TECU, Date/Time: 2024-12-01 19:16:01, Latitude: -3.02
60. TEC: 80.76 ± 1.10 TECU, Date/Time: 2024-12-01 19:16:58, Latitude: -3.02
61. TEC: 80.74 ± 3.98 TECU, Date/Time: 2024-12-01 18:16:58, Latitude: -3.02
62. TEC: 80.74 ± 1.12 TECU, Date/Time: 2024-12-01 19:18:00, Latitude: -3.02
63. TEC: 80.72 ± 1.12 TECU, Date/Time: 2024-12-01 19:19:01, Latitude: -3.02
64. TEC: 80.70 ± 1.13 TECU, Date/Time: 2024-12-01 19:19:58, Latitude: -3.02
65. TEC: 80.68 ± 3.96 TECU, Date/Time: 2024-12-01 18:16:01, Latitude: -3.02
66. TEC: 80.67 ± 1.13 TECU, Date/Time: 2024-12-01 19:21:00, Latitude: -3.02
67. TEC: 80.64 ± 1.14 TECU, Date/Time: 2024-12-01 19:22:01, Latitude: -3.02
68. TEC: 80.62 ± 3.94 TECU, Date/Time: 2024-12-01 18:15:00, Latitude: -3.02
69. TEC: 80.62 ± 1.12 TECU, Date/Time: 2024-12-01 19:22:58, Latitude: -3.02
70. TEC: 80.58 ± 1.09 TECU, Date/Time: 2024-12-01 19:23:59, Latitude: -3.02
71. TEC: 80.56 ± 3.93 TECU, Date/Time: 2024-12-01 18:13:58, Latitude: -3.02
72. TEC: 80.55 ± 1.07 TECU, Date/Time: 2024-12-01 19:25:01, Latitude: -3.02
73. TEC: 80.52 ± 1.04 TECU, Date/Time: 2024-12-01 19:25:58, Latitude: -3.02
74. TEC: 80.50 ± 3.91 TECU, Date/Time: 2024-12-01 18:13:01, Latitude: -3.02
75. TEC: 80.48 ± 1.79 TECU, Date/Time: 2024-12-01 19:26:59, Latitude: -3.02
76. TEC: 80.44 ± 2.44 TECU, Date/Time: 2024-12-01 19:28:01, Latitude: -3.02
77. TEC: 80.43 ± 3.90 TECU, Date/Time: 2024-12-01 18:11:59, Latitude: -3.02
78. TEC: 80.40 ± 2.33 TECU, Date/Time: 2024-12-01 19:28:58, Latitude: -3.02
79. TEC: 80.36 ± 3.88 TECU, Date/Time: 2024-12-01 18:10:58, Latitude: -3.02
80. TEC: 80.36 ± 2.22 TECU, Date/Time: 2024-12-01 19:30:00, Latitude: -3.02
81. TEC: 80.31 ± 2.10 TECU, Date/Time: 2024-12-01 19:31:01, Latitude: -3.02
82. TEC: 80.29 ± 3.87 TECU, Date/Time: 2024-12-01 18:10:01, Latitude: -3.02
83. TEC: 80.26 ± 2.00 TECU, Date/Time: 2024-12-01 19:31:58, Latitude: -3.02
84. TEC: 80.22 ± 3.85 TECU, Date/Time: 2024-12-01 18:08:59, Latitude: -3.02
85. TEC: 80.21 ± 3.43 TECU, Date/Time: 2024-12-01 19:33:00, Latitude: -3.02
86. TEC: 80.16 ± 3.34 TECU, Date/Time: 2024-12-01 19:34:01, Latitude: -3.02
87. TEC: 80.14 ± 3.83 TECU, Date/Time: 2024-12-01 18:07:58, Latitude: -3.02
88. TEC: 80.11 ± 3.33 TECU, Date/Time: 2024-12-01 19:34:58, Latitude: -3.02
89. TEC: 80.07 ± 3.82 TECU, Date/Time: 2024-12-01 18:07:01, Latitude: -3.02
90. TEC: 80.05 ± 3.33 TECU, Date/Time: 2024-12-01 19:36:00, Latitude: -3.02
91. TEC: 79.99 ± 3.81 TECU, Date/Time: 2024-12-01 18:06:00, Latitude: -3.02
92. TEC: 79.99 ± 3.35 TECU, Date/Time: 2024-12-01 19:37:01, Latitude: -3.02
93. TEC: 79.93 ± 3.35 TECU, Date/Time: 2024-12-01 19:37:58, Latitude: -3.02
94. TEC: 79.91 ± 3.82 TECU, Date/Time: 2024-12-01 18:04:58, Latitude: -3.02
95. TEC: 79.87 ± 3.35 TECU, Date/Time: 2024-12-01 19:38:59, Latitude: -3.02
96. TEC: 79.84 ± 3.82 TECU, Date/Time: 2024-12-01 18:04:01, Latitude: -3.02
97. TEC: 79.81 ± 3.34 TECU, Date/Time: 2024-12-01 19:40:01, Latitude: -3.02
98. TEC: 79.76 ± 3.81 TECU, Date/Time: 2024-12-01 18:03:00, Latitude: -3.02
99. TEC: 79.74 ± 3.30 TECU, Date/Time: 2024-12-01 19:40:58, Latitude: -3.02
100. TEC: 79.68 ± 3.81 TECU, Date/Time: 2024-12-01 18:01:58, Latitude: -3.02
101. TEC: 79.67 ± 3.26 TECU, Date/Time: 2024-12-01 19:41:59, Latitude: -3.02
102. TEC: 79.61 ± 3.21 TECU, Date/Time: 2024-12-01 19:43:01, Latitude: -3.02
103. TEC: 79.60 ± 3.82 TECU, Date/Time: 2024-12-01 18:01:01, Latitude: -3.02
104. TEC: 79.54 ± 3.16 TECU, Date/Time: 2024-12-01 19:43:58, Latitude: -3.02
105. TEC: 79.52 ± 3.82 TECU, Date/Time: 2024-12-01 18:00:00, Latitude: -3.02
106. TEC: 79.46 ± 3.10 TECU, Date/Time: 2024-12-01 19:45:00, Latitude: -3.02
107. TEC: 79.44 ± 3.82 TECU, Date/Time: 2024-12-01 17:58:58, Latitude: -3.02
108. TEC: 79.39 ± 3.04 TECU, Date/Time: 2024-12-01 19:46:01, Latitude: -3.02
109. TEC: 79.37 ± 3.83 TECU, Date/Time: 2024-12-01 17:58:01, Latitude: -3.02
110. TEC: 79.32 ± 3.00 TECU, Date/Time: 2024-12-01 19:46:58, Latitude: -3.02
111. TEC: 79.29 ± 3.84 TECU, Date/Time: 2024-12-01 17:56:59, Latitude: -3.02
112. TEC: 79.24 ± 2.95 TECU, Date/Time: 2024-12-01 19:48:00, Latitude: -3.02
113. TEC: 79.22 ± 3.84 TECU, Date/Time: 2024-12-01 17:55:58, Latitude: -3.02
114. TEC: 79.16 ± 2.90 TECU, Date/Time: 2024-12-01 19:49:01, Latitude: -3.02
115. TEC: 79.14 ± 3.95 TECU, Date/Time: 2024-12-01 17:55:01, Latitude: -3.02
116. TEC: 79.08 ± 2.84 TECU, Date/Time: 2024-12-01 19:49:58, Latitude: -3.02
117. TEC: 79.07 ± 4.33 TECU, Date/Time: 2024-12-01 17:53:59, Latitude: -3.02
118. TEC: 79.00 ± 5.44 TECU, Date/Time: 2024-12-01 17:52:58, Latitude: -3.02
119. TEC: 79.00 ± 2.79 TECU, Date/Time: 2024-12-01 19:51:00, Latitude: -3.02
120. TEC: 78.99 ± 1.46 TECU, Date/Time: 2024-12-02 17:41:59, Latitude: -3.02
121. TEC: 78.99 ± 1.51 TECU, Date/Time: 2024-12-02 17:43:01, Latitude: -3.02
122. TEC: 78.99 ± 1.55 TECU, Date/Time: 2024-12-02 17:43:58, Latitude: -3.02
123. TEC: 78.99 ± 1.59 TECU, Date/Time: 2024-12-02 17:45:00, Latitude: -3.02
124. TEC: 78.99 ± 1.63 TECU, Date/Time: 2024-12-02 17:46:01, Latitude: -3.02
125. TEC: 78.99 ± 1.68 TECU, Date/Time: 2024-12-02 17:46:58, Latitude: -3.02
126. TEC: 78.98 ± 1.35 TECU, Date/Time: 2024-12-02 17:40:01, Latitude: -3.02
127. TEC: 78.98 ± 1.41 TECU, Date/Time: 2024-12-02 17:40:58, Latitude: -3.02
128. TEC: 78.98 ± 1.73 TECU, Date/Time: 2024-12-02 17:48:00, Latitude: -3.02
129. TEC: 78.97 ± 1.32 TECU, Date/Time: 2024-12-02 17:38:59, Latitude: -3.02
130. TEC: 78.97 ± 1.78 TECU, Date/Time: 2024-12-02 17:49:01, Latitude: -3.02
131. TEC: 78.97 ± 1.76 TECU, Date/Time: 2024-12-02 17:49:58, Latitude: -3.02
132. TEC: 78.96 ± 1.27 TECU, Date/Time: 2024-12-02 17:37:58, Latitude: -3.02
133. TEC: 78.96 ± 1.75 TECU, Date/Time: 2024-12-02 17:51:00, Latitude: -3.02
134. TEC: 78.95 ± 1.20 TECU, Date/Time: 2024-12-02 17:37:01, Latitude: -3.02
135. TEC: 78.95 ± 1.74 TECU, Date/Time: 2024-12-02 17:52:01, Latitude: -3.02
136. TEC: 78.94 ± 1.14 TECU, Date/Time: 2024-12-02 17:36:00, Latitude: -3.02
137. TEC: 78.93 ± 5.43 TECU, Date/Time: 2024-12-01 17:52:01, Latitude: -3.02
138. TEC: 78.93 ± 1.10 TECU, Date/Time: 2024-12-02 17:34:58, Latitude: -3.02
139. TEC: 78.93 ± 1.76 TECU, Date/Time: 2024-12-02 17:52:58, Latitude: -3.02
140. TEC: 78.92 ± 2.72 TECU, Date/Time: 2024-12-01 19:52:01, Latitude: -3.02
141. TEC: 78.92 ± 1.05 TECU, Date/Time: 2024-12-02 17:34:01, Latitude: -3.02
142. TEC: 78.92 ± 1.79 TECU, Date/Time: 2024-12-02 17:53:59, Latitude: -3.02
143. TEC: 78.90 ± 1.00 TECU, Date/Time: 2024-12-02 17:33:00, Latitude: -3.02
144. TEC: 78.90 ± 1.82 TECU, Date/Time: 2024-12-02 17:55:01, Latitude: -3.02
145. TEC: 78.89 ± 0.98 TECU, Date/Time: 2024-12-02 17:31:58, Latitude: -3.02
146. TEC: 78.88 ± 1.84 TECU, Date/Time: 2024-12-02 17:55:58, Latitude: -3.02
147. TEC: 78.87 ± 5.40 TECU, Date/Time: 2024-12-01 17:51:00, Latitude: -3.02
148. TEC: 78.87 ± 0.96 TECU, Date/Time: 2024-12-02 17:31:01, Latitude: -3.02
149. TEC: 78.86 ± 1.86 TECU, Date/Time: 2024-12-02 17:56:59, Latitude: -3.02
150. TEC: 78.85 ± 0.94 TECU, Date/Time: 2024-12-02 17:30:00, Latitude: -3.02
151. TEC: 78.84 ± 2.64 TECU, Date/Time: 2024-12-01 19:52:58, Latitude: -3.02
152. TEC: 78.84 ± 1.89 TECU, Date/Time: 2024-12-02 17:58:01, Latitude: -3.02
153. TEC: 78.83 ± 0.92 TECU, Date/Time: 2024-12-02 17:28:58, Latitude: -3.02
154. TEC: 78.82 ± 1.90 TECU, Date/Time: 2024-12-02 17:58:58, Latitude: -3.02
155. TEC: 78.81 ± 0.89 TECU, Date/Time: 2024-12-02 17:28:01, Latitude: -3.02
156. TEC: 78.80 ± 5.33 TECU, Date/Time: 2024-12-01 17:49:58, Latitude: -3.02
157. TEC: 78.79 ± 1.91 TECU, Date/Time: 2024-12-02 18:00:00, Latitude: -3.02
158. TEC: 78.78 ± 0.88 TECU, Date/Time: 2024-12-02 17:26:59, Latitude: -3.02
159. TEC: 78.76 ± 2.57 TECU, Date/Time: 2024-12-01 19:53:59, Latitude: -3.02
160. TEC: 78.76 ± 0.88 TECU, Date/Time: 2024-12-02 17:25:58, Latitude: -3.02
161. TEC: 78.76 ± 1.92 TECU, Date/Time: 2024-12-02 18:01:01, Latitude: -3.02
162. TEC: 78.74 ± 5.25 TECU, Date/Time: 2024-12-01 17:49:01, Latitude: -3.02
163. TEC: 78.73 ± 0.88 TECU, Date/Time: 2024-12-02 17:25:01, Latitude: -3.02
164. TEC: 78.73 ± 1.93 TECU, Date/Time: 2024-12-02 18:01:58, Latitude: -3.02
165. TEC: 78.70 ± 0.89 TECU, Date/Time: 2024-12-02 17:23:59, Latitude: -3.02
166. TEC: 78.69 ± 1.94 TECU, Date/Time: 2024-12-02 18:03:00, Latitude: -3.02
167. TEC: 78.68 ± 5.32 TECU, Date/Time: 2024-12-01 17:48:00, Latitude: -3.02
168. TEC: 78.68 ± 2.49 TECU, Date/Time: 2024-12-01 19:55:01, Latitude: -3.02
169. TEC: 78.67 ± 0.90 TECU, Date/Time: 2024-12-02 17:22:58, Latitude: -3.02
170. TEC: 78.66 ± 1.95 TECU, Date/Time: 2024-12-02 18:04:01, Latitude: -3.02
171. TEC: 78.64 ± 1.39 TECU, Date/Time: 2024-12-02 17:22:01, Latitude: -3.02
172. TEC: 78.62 ± 5.29 TECU, Date/Time: 2024-12-01 17:46:58, Latitude: -3.02
173. TEC: 78.62 ± 1.95 TECU, Date/Time: 2024-12-02 18:04:58, Latitude: -3.02
174. TEC: 78.60 ± 1.60 TECU, Date/Time: 2024-12-02 17:21:00, Latitude: -3.02
175. TEC: 78.59 ± 2.41 TECU, Date/Time: 2024-12-01 19:55:58, Latitude: -3.02
176. TEC: 78.58 ± 1.95 TECU, Date/Time: 2024-12-02 18:06:00, Latitude: -3.02
177. TEC: 78.57 ± 5.26 TECU, Date/Time: 2024-12-01 17:46:01, Latitude: -3.02
178. TEC: 78.57 ± 1.59 TECU, Date/Time: 2024-12-02 17:19:58, Latitude: -3.02
179. TEC: 78.53 ± 1.58 TECU, Date/Time: 2024-12-02 17:19:01, Latitude: -3.02
180. TEC: 78.53 ± 1.95 TECU, Date/Time: 2024-12-02 18:07:01, Latitude: -3.02
181. TEC: 78.52 ± 5.21 TECU, Date/Time: 2024-12-01 17:45:00, Latitude: -3.02
182. TEC: 78.51 ± 2.33 TECU, Date/Time: 2024-12-01 19:56:59, Latitude: -3.02
183. TEC: 78.49 ± 1.56 TECU, Date/Time: 2024-12-02 17:18:00, Latitude: -3.02
184. TEC: 78.49 ± 1.94 TECU, Date/Time: 2024-12-02 18:07:58, Latitude: -3.02
185. TEC: 78.47 ± 5.20 TECU, Date/Time: 2024-12-01 17:43:58, Latitude: -3.02
186. TEC: 78.45 ± 1.55 TECU, Date/Time: 2024-12-02 17:16:58, Latitude: -3.02
187. TEC: 78.44 ± 1.92 TECU, Date/Time: 2024-12-02 18:08:59, Latitude: -3.02
188. TEC: 78.42 ± 5.05 TECU, Date/Time: 2024-12-01 17:43:01, Latitude: -3.02
189. TEC: 78.42 ± 2.24 TECU, Date/Time: 2024-12-01 19:58:01, Latitude: -3.02
190. TEC: 78.40 ± 1.53 TECU, Date/Time: 2024-12-02 17:16:01, Latitude: -3.02
191. TEC: 78.39 ± 1.90 TECU, Date/Time: 2024-12-02 18:10:01, Latitude: -3.02
192. TEC: 78.38 ± 5.15 TECU, Date/Time: 2024-12-01 17:41:59, Latitude: -3.02
193. TEC: 78.36 ± 1.52 TECU, Date/Time: 2024-12-02 17:15:00, Latitude: -3.02
194. TEC: 78.34 ± 5.11 TECU, Date/Time: 2024-12-01 17:40:58, Latitude: -3.02
195. TEC: 78.34 ± 2.15 TECU, Date/Time: 2024-12-01 19:58:58, Latitude: -3.02
196. TEC: 78.34 ± 1.88 TECU, Date/Time: 2024-12-02 18:10:58, Latitude: -3.02
197. TEC: 78.32 ± 1.51 TECU, Date/Time: 2024-12-02 17:13:58, Latitude: -3.02
198. TEC: 78.30 ± 4.97 TECU, Date/Time: 2024-12-01 17:40:01, Latitude: -3.02
199. TEC: 78.29 ± 1.95 TECU, Date/Time: 2024-12-03 17:34:01, Latitude: -3.02
200. TEC: 78.29 ± 1.91 TECU, Date/Time: 2024-12-03 17:34:58, Latitude: -3.02

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 81.24 ± 4.22) has a sequence of 3 high values:
  1. 2024-12-01 18:34:01: 81.23 ± 4.01 TECU (100.0% do Peak)
  2. 2024-12-01 18:34:58: 81.24 ± 4.22 TECU (100.0% do Peak)
  3. 2024-12-01 18:36:00: 81.24 ± 3.54 TECU (100.0% do Peak)

Peak #2 (TEC = 81.24 ± 3.54) has a sequence of 3 high values:
  1. 2024-12-01 18:34:58: 81.24 ± 4.22 TECU (100.0% do Peak)
  2. 2024-12-01 18:36:00: 81.24 ± 3.54 TECU (100.0% do Peak)
  3. 2024-12-01 18:37:01: 81.23 ± 3.87 TECU (100.0% do Peak)

Peak #3 (TEC = 81.23 ± 4.06) has a sequence of 3 high values:
  1. 2024-12-01 18:31:58: 81.22 ± 4.10 TECU (100.0% do Peak)
  2. 2024-12-01 18:33:00: 81.23 ± 4.06 TECU (100.0% do Peak)
  3. 2024-12-01 18:34:01: 81.23 ± 4.01 TECU (100.0% do Peak)

Peak #4 (TEC = 81.23 ± 4.01) has a sequence of 3 high values:
  1. 2024-12-01 18:33:00: 81.23 ± 4.06 TECU (100.0% do Peak)
  2. 2024-12-01 18:34:01: 81.23 ± 4.01 TECU (100.0% do Peak)
  3. 2024-12-01 18:34:58: 81.24 ± 4.22 TECU (100.0% do Peak)

Peak #5 (TEC = 81.23 ± 3.87) has a sequence of 3 high values:
  1. 2024-12-01 18:36:00: 81.24 ± 3.54 TECU (100.0% do Peak)
  2. 2024-12-01 18:37:01: 81.23 ± 3.87 TECU (100.0% do Peak)
  3. 2024-12-01 18:37:58: 81.23 ± 3.82 TECU (100.0% do Peak)

Peak #6 (TEC = 81.23 ± 3.82) has a sequence of 3 high values:
  1. 2024-12-01 18:37:01: 81.23 ± 3.87 TECU (100.0% do Peak)
  2. 2024-12-01 18:37:58: 81.23 ± 3.82 TECU (100.0% do Peak)
  3. 2024-12-01 18:38:59: 81.23 ± 3.77 TECU (100.0% do Peak)

Peak #7 (TEC = 81.23 ± 3.77) has a sequence of 3 high values:
  1. 2024-12-01 18:37:58: 81.23 ± 3.82 TECU (100.0% do Peak)
  2. 2024-12-01 18:38:59: 81.23 ± 3.77 TECU (100.0% do Peak)
  3. 2024-12-01 18:40:01: 81.22 ± 3.71 TECU (100.0% do Peak)

Peak #8 (TEC = 81.22 ± 4.10) has a sequence of 3 high values:
  1. 2024-12-01 18:31:01: 81.21 ± 4.15 TECU (100.0% do Peak)
  2. 2024-12-01 18:31:58: 81.22 ± 4.10 TECU (100.0% do Peak)
  3. 2024-12-01 18:33:00: 81.23 ± 4.06 TECU (100.0% do Peak)

Peak #9 (TEC = 81.22 ± 3.71) has a sequence of 3 high values:
  1. 2024-12-01 18:38:59: 81.23 ± 3.77 TECU (100.0% do Peak)
  2. 2024-12-01 18:40:01: 81.22 ± 3.71 TECU (100.0% do Peak)
  3. 2024-12-01 18:40:58: 81.21 ± 3.90 TECU (100.0% do Peak)

Peak #10 (TEC = 81.21 ± 4.15) has a sequence of 3 high values:
  1. 2024-12-01 18:30:00: 81.20 ± 4.18 TECU (100.0% do Peak)
  2. 2024-12-01 18:31:01: 81.21 ± 4.15 TECU (100.0% do Peak)
  3. 2024-12-01 18:31:58: 81.22 ± 4.10 TECU (100.0% do Peak)

Peak #11 (TEC = 81.21 ± 3.90) has a sequence of 3 high values:
  1. 2024-12-01 18:40:01: 81.22 ± 3.71 TECU (100.0% do Peak)
  2. 2024-12-01 18:40:58: 81.21 ± 3.90 TECU (100.0% do Peak)
  3. 2024-12-01 18:41:59: 81.20 ± 3.22 TECU (100.0% do Peak)

Peak #12 (TEC = 81.20 ± 4.18) has a sequence of 3 high values:
  1. 2024-12-01 18:28:58: 81.18 ± 4.20 TECU (100.0% do Peak)
  2. 2024-12-01 18:30:00: 81.20 ± 4.18 TECU (100.0% do Peak)
  3. 2024-12-01 18:31:01: 81.21 ± 4.15 TECU (100.0% do Peak)

Peak #13 (TEC = 81.20 ± 3.22) has a sequence of 3 high values:
  1. 2024-12-01 18:40:58: 81.21 ± 3.90 TECU (100.0% do Peak)
  2. 2024-12-01 18:41:59: 81.20 ± 3.22 TECU (100.0% do Peak)
  3. 2024-12-01 18:43:01: 81.19 ± 3.51 TECU (100.0% do Peak)

Peak #14 (TEC = 81.19 ± 3.51) has a sequence of 3 high values:
  1. 2024-12-01 18:41:59: 81.20 ± 3.22 TECU (100.0% do Peak)
  2. 2024-12-01 18:43:01: 81.19 ± 3.51 TECU (100.0% do Peak)
  3. 2024-12-01 18:43:58: 81.18 ± 3.45 TECU (100.0% do Peak)

Peak #15 (TEC = 81.18 ± 4.20) has a sequence of 3 high values:
  1. 2024-12-01 18:28:01: 81.16 ± 4.22 TECU (100.0% do Peak)
  2. 2024-12-01 18:28:58: 81.18 ± 4.20 TECU (100.0% do Peak)
  3. 2024-12-01 18:30:00: 81.20 ± 4.18 TECU (100.0% do Peak)

Peak #16 (TEC = 81.18 ± 3.45) has a sequence of 3 high values:
  1. 2024-12-01 18:43:01: 81.19 ± 3.51 TECU (100.0% do Peak)
  2. 2024-12-01 18:43:58: 81.18 ± 3.45 TECU (100.0% do Peak)
  3. 2024-12-01 18:45:00: 81.16 ± 3.40 TECU (100.0% do Peak)

Peak #17 (TEC = 81.16 ± 4.22) has a sequence of 3 high values:
  1. 2024-12-01 18:26:59: 81.14 ± 4.23 TECU (100.0% do Peak)
  2. 2024-12-01 18:28:01: 81.16 ± 4.22 TECU (100.0% do Peak)

## SPECIFIC TIMES FOR 12/18

In [10]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('naus_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

# Verificar as colunas disponíveis
print(f"Colunas disponíveis no DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):
    """
    Encontra o valor TEC mais próximo de um datetime específico,
    dentro de uma diferença máxima de minutos especificada.
    """
    # Converte target_datetime para pandas Timestamp se necessário
    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    # Calcula a diferença em minutos absoluta entre cada timestamp e o target
    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    # Filtra apenas valores dentro da diferença máxima permitida
    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    # Encontra o índice do valor mais próximo dentro do range
    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):
    """
    Retorna informações de localização disponíveis no DataFrame
    """
    location_info = {}

    # Verifica quais colunas de localização estão disponíveis
    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):
    """
    Analisa valores TEC próximos a datetimes específicos.

    Parameters:
    target_datetimes: lista de strings ou datetime objects com os horários target
    max_minutes_diff: diferença máxima em minutos para considerar um valor como "próximo"
    """

    print(f"\n{'='*100}")
    print(f"ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS")
    print(f"(Diferença máxima permitida: {max_minutes_diff} minutos)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"BUSCANDO VALORES PRÓXIMOS A: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f"✓ VALOR ENCONTRADO:")
            print(f"  Data/Hora real: {closest_row['DATETIME']}")
            print(f"  Data/Hora alvo: {target_dt}")
            print(f"  Diferença: {time_diff:.2f} minutos")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            # Obter informações de localização disponíveis
            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            # Verifica se há sequência de valores altos
            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f"    {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% do valor)")
            else:
                print(f"  ✗ NÃO possui sequência de 3 valores altos consecutivos")

            # Preparar resultado para a tabela
            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f"✗ NENHUM VALOR ENCONTRADO dentro de {max_minutes_diff} minutos do horário alvo")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    # Tabela resumo
    print(f"\n{'='*120}")
    print(f"TABELA RESUMO DOS RESULTADOS")
    print(f"{'='*120}")

    # Cabeçalho adaptativo baseado nas colunas disponíveis
    header = f"{'#':<3}{'Horário Alvo':<20}{'Horário Encontrado':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequência':<12}"

    # Adicionar colunas de localização disponíveis
    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            # Adicionar informações de localização
            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            # Preencher com N/A para colunas de localização
            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

# Definindo os horários específicos solicitados
target_datetimes = [
    "2024-12-18 18:20:00",
    "2024-12-18 18:10:00",
    "2024-12-18 18:30:00",
    "2024-12-18 18:00:00"
]

print("\n\n" + "*"*50 + " ANÁLISE DOS HORÁRIOS ESPECÍFICOS " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnálise concluída!")

# Informações adicionais sobre os dados encontrados
found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"Valores TEC encontrados:")
    print(f"  Mínimo: {min(tec_values):.2f} TECU")
    print(f"  Máximo: {max(tec_values):.2f} TECU")
    print(f"  Média: {np.mean(tec_values):.2f} TECU")
    print(f"  Desvio padrão: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nSequências de valores altos encontradas: {sequences_found} de {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Colunas disponíveis no DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANÁLISE DOS HORÁRIOS ESPECÍFICOS **************************************************

====================================================================================================
ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS
(Diferença máxima permitida: 2 minutos)
====================================================================================================

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:20:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:19:58
  Data/Hora alvo: 2024-12-18 18:20:00
  Diferença: 0.03 minutos
  TEC: 67.05 ± 2.17 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:19:01: 67.05 ± 2.14 TECU (100.0% do valor)
    2. 2024-12-18 18:19:58: 67.05 ± 2.17 TECU (100.0% do valor)
    3. 2024-12-18 18:21:00: 67.05 ± 2.20 TECU (100.0% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:10:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:10:01
  Data/Hora alvo: 2024-12-18 18:10:00
  Diferença: 0.02 minutos
  TEC: 67.10 ± 1.29 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:08:59: 67.12 ± 1.27 TECU (100.0% do valor)
    2. 2024-12-18 18:10:01: 67.10 ± 1.29 TECU (100.0% do valor)
    3. 2024-12-18 18:10:58: 67.09 ± 1.27 TECU (100.0% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:30:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:30:00
  Data/Hora alvo: 2024-12-18 18:30:00
  Diferença: 0.00 minutos
  TEC: 67.06 ± 2.05 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:28:58: 67.06 ± 2.05 TECU (100.0% do valor)
    2. 2024-12-18 18:30:00: 67.06 ± 2.05 TECU (100.0% do valor)
    3. 2024-12-18 18:31:01: 67.05 ± 2.05 TECU (100.0% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:00:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:00:00
  Data/Hora alvo: 2024-12-18 18:00:00
  Diferença: 0.00 minutos
  TEC: 67.33 ± 1.10 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 17:58:58: 67.36 ± 1.07 TECU (100.0% do valor)
    2. 2024-12-18 18:00:00: 67.33 ± 1.10 TECU (100.0% do valor)
    3. 2024-12-18 18:01:01: 67.30 ± 1.13 TECU (100.0% do valor)

========================================================================================================================
TABELA RESUMO DOS RESULTADOS
========================================================================================================================
#  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    67.05    2.17    Sim         -3.02
2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    67.10    1.29    Sim         -3.02
3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    67.06    2.05    Sim         -3.02
4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    67.33    1.10    Sim         -3.02
-------------------------------------------------------------------------------------------------

Análise concluída!

================================================================================
ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS
================================================================================
Valores TEC encontrados:
  Mínimo: 67.05 TECU
  Máximo: 67.33 TECU
  Média: 67.13 TECU
  Desvio padrão: 0.11 TECU

Sequências de valores altos encontradas: 4 de 4 (100.0%)

## 12/18 AT 18:00

In [11]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('naus_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

# Verificar as colunas disponíveis
print(f"Colunas disponíveis no DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):
    """
    Encontra o valor TEC mais próximo de um datetime específico,
    dentro de uma diferença máxima de minutos especificada.
    """
    # Converte target_datetime para pandas Timestamp se necessário
    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    # Calcula a diferença em minutos absoluta entre cada timestamp e o target
    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    # Filtra apenas valores dentro da diferença máxima permitida
    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    # Encontra o índice do valor mais próximo dentro do range
    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):
    """
    Retorna informações de localização disponíveis no DataFrame
    """
    location_info = {}

    # Verifica quais colunas de localização estão disponíveis
    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):
    """
    Analisa valores TEC próximos a datetimes específicos.

    Parameters:
    target_datetimes: lista de strings ou datetime objects com os horários target
    max_minutes_diff: diferença máxima em minutos para considerar um valor como "próximo"
    """

    print(f"\n{'='*100}")
    print(f"ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS")
    print(f"(Diferença máxima permitida: {max_minutes_diff} minutos)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"BUSCANDO VALORES PRÓXIMOS A: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f"✓ VALOR ENCONTRADO:")
            print(f"  Data/Hora real: {closest_row['DATETIME']}")
            print(f"  Data/Hora alvo: {target_dt}")
            print(f"  Diferença: {time_diff:.2f} minutos")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            # Obter informações de localização disponíveis
            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            # Verifica se há sequência de valores altos
            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f"    {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% do valor)")
            else:
                print(f"  ✗ NÃO possui sequência de 3 valores altos consecutivos")

            # Preparar resultado para a tabela
            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f"✗ NENHUM VALOR ENCONTRADO dentro de {max_minutes_diff} minutos do horário alvo")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    # Tabela resumo
    print(f"\n{'='*120}")
    print(f"TABELA RESUMO DOS RESULTADOS")
    print(f"{'='*120}")

    # Cabeçalho adaptativo baseado nas colunas disponíveis
    header = f"{'#':<3}{'Horário Alvo':<20}{'Horário Encontrado':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequência':<12}"

    # Adicionar colunas de localização disponíveis
    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            # Adicionar informações de localização
            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            # Preencher com N/A para colunas de localização
            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

# Definindo os horários específicos solicitados
target_datetimes = [
    "2024-12-18 18:00:00"
]

print("\n\n" + "*"*50 + " ANÁLISE DOS HORÁRIOS ESPECÍFICOS " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnálise concluída!")

# Informações adicionais sobre os dados encontrados
found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"Valores TEC encontrados:")
    print(f"  Mínimo: {min(tec_values):.2f} TECU")
    print(f"  Máximo: {max(tec_values):.2f} TECU")
    print(f"  Média: {np.mean(tec_values):.2f} TECU")
    print(f"  Desvio padrão: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nSequências de valores altos encontradas: {sequences_found} de {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Colunas disponíveis no DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANÁLISE DOS HORÁRIOS ESPECÍFICOS **************************************************

====================================================================================================
ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS
(Diferença máxima permitida: 2 minutos)
====================================================================================================

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:00:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:00:00
  Data/Hora alvo: 2024-12-18 18:00:00
  Diferença: 0.00 minutos
  TEC: 67.33 ± 1.10 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 17:58:58: 67.36 ± 1.07 TECU (100.0% do valor)
    2. 2024-12-18 18:00:00: 67.33 ± 1.10 TECU (100.0% do valor)
    3. 2024-12-18 18:01:01: 67.30 ± 1.13 TECU (100.0% do valor)

========================================================================================================================
TABELA RESUMO DOS RESULTADOS
========================================================================================================================
#  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    67.33    1.10    Sim         -3.02
-------------------------------------------------------------------------------------------------

Análise concluída!

================================================================================
ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS
================================================================================
Valores TEC encontrados:
  Mínimo: 67.33 TECU
  Máximo: 67.33 TECU
  Média: 67.33 TECU
  Desvio padrão: 0.00 TECU

Sequências de valores altos encontradas: 1 de 1 (100.0%)

## 12/22 AT 18:00

In [12]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('naus_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

# Verificar as colunas disponíveis
print(f"Colunas disponíveis no DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):
    """
    Encontra o valor TEC mais próximo de um datetime específico,
    dentro de uma diferença máxima de minutos especificada.
    """
    # Converte target_datetime para pandas Timestamp se necessário
    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    # Calcula a diferença em minutos absoluta entre cada timestamp e o target
    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    # Filtra apenas valores dentro da diferença máxima permitida
    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    # Encontra o índice do valor mais próximo dentro do range
    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):
    """
    Retorna informações de localização disponíveis no DataFrame
    """
    location_info = {}

    # Verifica quais colunas de localização estão disponíveis
    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):
    """
    Analisa valores TEC próximos a datetimes específicos.

    Parameters:
    target_datetimes: lista de strings ou datetime objects com os horários target
    max_minutes_diff: diferença máxima em minutos para considerar um valor como "próximo"
    """

    print(f"\n{'='*100}")
    print(f"ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS")
    print(f"(Diferença máxima permitida: {max_minutes_diff} minutos)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"BUSCANDO VALORES PRÓXIMOS A: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f"✓ VALOR ENCONTRADO:")
            print(f"  Data/Hora real: {closest_row['DATETIME']}")
            print(f"  Data/Hora alvo: {target_dt}")
            print(f"  Diferença: {time_diff:.2f} minutos")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            # Obter informações de localização disponíveis
            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            # Verifica se há sequência de valores altos
            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f"    {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% do valor)")
            else:
                print(f"  ✗ NÃO possui sequência de 3 valores altos consecutivos")

            # Preparar resultado para a tabela
            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f"✗ NENHUM VALOR ENCONTRADO dentro de {max_minutes_diff} minutos do horário alvo")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    # Tabela resumo
    print(f"\n{'='*120}")
    print(f"TABELA RESUMO DOS RESULTADOS")
    print(f"{'='*120}")

    # Cabeçalho adaptativo baseado nas colunas disponíveis
    header = f"{'#':<3}{'Horário Alvo':<20}{'Horário Encontrado':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequência':<12}"

    # Adicionar colunas de localização disponíveis
    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            # Adicionar informações de localização
            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            # Preencher com N/A para colunas de localização
            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

# Definindo os horários específicos solicitados
target_datetimes = [
    "2024-12-22 18:00:00"
]

print("\n\n" + "*"*50 + " ANÁLISE DOS HORÁRIOS ESPECÍFICOS " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnálise concluída!")

# Informações adicionais sobre os dados encontrados
found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"Valores TEC encontrados:")
    print(f"  Mínimo: {min(tec_values):.2f} TECU")
    print(f"  Máximo: {max(tec_values):.2f} TECU")
    print(f"  Média: {np.mean(tec_values):.2f} TECU")
    print(f"  Desvio padrão: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nSequências de valores altos encontradas: {sequences_found} de {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Colunas disponíveis no DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANÁLISE DOS HORÁRIOS ESPECÍFICOS **************************************************

====================================================================================================
ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS
(Diferença máxima permitida: 2 minutos)
====================================================================================================

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-22 18:00:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-22 18:00:00
  Data/Hora alvo: 2024-12-22 18:00:00
  Diferença: 0.00 minutos
  TEC: 66.96 ± 0.84 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-22 17:58:58: 66.98 ± 0.85 TECU (100.0% do valor)
    2. 2024-12-22 18:00:00: 66.96 ± 0.84 TECU (100.0% do valor)
    3. 2024-12-22 18:01:01: 66.94 ± 0.78 TECU (100.0% do valor)

========================================================================================================================
TABELA RESUMO DOS RESULTADOS
========================================================================================================================
#  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-22 18:00:00 2024-12-22 18:00:00 0.00    66.96    0.84    Sim         -3.02
-------------------------------------------------------------------------------------------------

Análise concluída!

================================================================================
ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS
================================================================================
Valores TEC encontrados:
  Mínimo: 66.96 TECU
  Máximo: 66.96 TECU
  Média: 66.96 TECU
  Desvio padrão: 0.00 TECU

Sequências de valores altos encontradas: 1 de 1 (100.0%)

## 12/19 AT 18:00

In [13]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('naus_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

# Verificar as colunas disponíveis
print(f"Colunas disponíveis no DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):
    """
    Encontra o valor TEC mais próximo de um datetime específico,
    dentro de uma diferença máxima de minutos especificada.
    """
    # Converte target_datetime para pandas Timestamp se necessário
    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    # Calcula a diferença em minutos absoluta entre cada timestamp e o target
    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    # Filtra apenas valores dentro da diferença máxima permitida
    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    # Encontra o índice do valor mais próximo dentro do range
    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):
    """
    Retorna informações de localização disponíveis no DataFrame
    """
    location_info = {}

    # Verifica quais colunas de localização estão disponíveis
    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):
    """
    Analisa valores TEC próximos a datetimes específicos.

    Parameters:
    target_datetimes: lista de strings ou datetime objects com os horários target
    max_minutes_diff: diferença máxima em minutos para considerar um valor como "próximo"
    """

    print(f"\n{'='*100}")
    print(f"ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS")
    print(f"(Diferença máxima permitida: {max_minutes_diff} minutos)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"BUSCANDO VALORES PRÓXIMOS A: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f"✓ VALOR ENCONTRADO:")
            print(f"  Data/Hora real: {closest_row['DATETIME']}")
            print(f"  Data/Hora alvo: {target_dt}")
            print(f"  Diferença: {time_diff:.2f} minutos")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            # Obter informações de localização disponíveis
            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            # Verifica se há sequência de valores altos
            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f"    {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% do valor)")
            else:
                print(f"  ✗ NÃO possui sequência de 3 valores altos consecutivos")

            # Preparar resultado para a tabela
            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f"✗ NENHUM VALOR ENCONTRADO dentro de {max_minutes_diff} minutos do horário alvo")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    # Tabela resumo
    print(f"\n{'='*120}")
    print(f"TABELA RESUMO DOS RESULTADOS")
    print(f"{'='*120}")

    # Cabeçalho adaptativo baseado nas colunas disponíveis
    header = f"{'#':<3}{'Horário Alvo':<20}{'Horário Encontrado':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequência':<12}"

    # Adicionar colunas de localização disponíveis
    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            # Adicionar informações de localização
            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            # Preencher com N/A para colunas de localização
            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

# Definindo os horários específicos solicitados
target_datetimes = [
    "2024-12-19 18:00:00"
]

print("\n\n" + "*"*50 + " ANÁLISE DOS HORÁRIOS ESPECÍFICOS " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnálise concluída!")

# Informações adicionais sobre os dados encontrados
found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"Valores TEC encontrados:")
    print(f"  Mínimo: {min(tec_values):.2f} TECU")
    print(f"  Máximo: {max(tec_values):.2f} TECU")
    print(f"  Média: {np.mean(tec_values):.2f} TECU")
    print(f"  Desvio padrão: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nSequências de valores altos encontradas: {sequences_found} de {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Colunas disponíveis no DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANÁLISE DOS HORÁRIOS ESPECÍFICOS **************************************************

====================================================================================================
ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS
(Diferença máxima permitida: 2 minutos)
====================================================================================================

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-19 18:00:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-19 18:00:00
  Data/Hora alvo: 2024-12-19 18:00:00
  Diferença: 0.00 minutos
  TEC: 62.93 ± 0.16 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-19 17:58:58: 62.94 ± 0.15 TECU (100.0% do valor)
    2. 2024-12-19 18:00:00: 62.93 ± 0.16 TECU (100.0% do valor)
    3. 2024-12-19 18:01:01: 62.91 ± 0.18 TECU (100.0% do valor)

========================================================================================================================
TABELA RESUMO DOS RESULTADOS
========================================================================================================================
#  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-19 18:00:00 2024-12-19 18:00:00 0.00    62.93    0.16    Sim         -3.02
-------------------------------------------------------------------------------------------------

Análise concluída!

================================================================================
ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS
================================================================================
Valores TEC encontrados:
  Mínimo: 62.93 TECU
  Máximo: 62.93 TECU
  Média: 62.93 TECU
  Desvio padrão: 0.00 TECU

Sequências de valores altos encontradas: 1 de 1 (100.0%)

## 12/01 AT 18:00

In [14]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('naus_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

# Verificar as colunas disponíveis
print(f"Colunas disponíveis no DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):
    """
    Encontra o valor TEC mais próximo de um datetime específico,
    dentro de uma diferença máxima de minutos especificada.
    """
    # Converte target_datetime para pandas Timestamp se necessário
    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    # Calcula a diferença em minutos absoluta entre cada timestamp e o target
    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    # Filtra apenas valores dentro da diferença máxima permitida
    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    # Encontra o índice do valor mais próximo dentro do range
    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):
    """
    Retorna informações de localização disponíveis no DataFrame
    """
    location_info = {}

    # Verifica quais colunas de localização estão disponíveis
    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):
    """
    Analisa valores TEC próximos a datetimes específicos.

    Parameters:
    target_datetimes: lista de strings ou datetime objects com os horários target
    max_minutes_diff: diferença máxima em minutos para considerar um valor como "próximo"
    """

    print(f"\n{'='*100}")
    print(f"ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS")
    print(f"(Diferença máxima permitida: {max_minutes_diff} minutos)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"BUSCANDO VALORES PRÓXIMOS A: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f"✓ VALOR ENCONTRADO:")
            print(f"  Data/Hora real: {closest_row['DATETIME']}")
            print(f"  Data/Hora alvo: {target_dt}")
            print(f"  Diferença: {time_diff:.2f} minutos")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            # Obter informações de localização disponíveis
            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            # Verifica se há sequência de valores altos
            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f"    {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% do valor)")
            else:
                print(f"  ✗ NÃO possui sequência de 3 valores altos consecutivos")

            # Preparar resultado para a tabela
            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f"✗ NENHUM VALOR ENCONTRADO dentro de {max_minutes_diff} minutos do horário alvo")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    # Tabela resumo
    print(f"\n{'='*120}")
    print(f"TABELA RESUMO DOS RESULTADOS")
    print(f"{'='*120}")

    # Cabeçalho adaptativo baseado nas colunas disponíveis
    header = f"{'#':<3}{'Horário Alvo':<20}{'Horário Encontrado':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequência':<12}"

    # Adicionar colunas de localização disponíveis
    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            # Adicionar informações de localização
            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            # Preencher com N/A para colunas de localização
            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

# Definindo os horários específicos solicitados
target_datetimes = [
    "2024-12-01 18:00:00"
]

print("\n\n" + "*"*50 + " ANÁLISE DOS HORÁRIOS ESPECÍFICOS " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnálise concluída!")

# Informações adicionais sobre os dados encontrados
found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"Valores TEC encontrados:")
    print(f"  Mínimo: {min(tec_values):.2f} TECU")
    print(f"  Máximo: {max(tec_values):.2f} TECU")
    print(f"  Média: {np.mean(tec_values):.2f} TECU")
    print(f"  Desvio padrão: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nSequências de valores altos encontradas: {sequences_found} de {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Colunas disponíveis no DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANÁLISE DOS HORÁRIOS ESPECÍFICOS **************************************************

====================================================================================================
ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS
(Diferença máxima permitida: 2 minutos)
====================================================================================================

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-01 18:00:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-01 18:00:00
  Data/Hora alvo: 2024-12-01 18:00:00
  Diferença: 0.00 minutos
  TEC: 79.52 ± 3.82 TECU
  LATITUDE: -3.02
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-01 17:58:58: 79.44 ± 3.82 TECU (99.9% do valor)
    2. 2024-12-01 18:00:00: 79.52 ± 3.82 TECU (100.0% do valor)
    3. 2024-12-01 18:01:01: 79.60 ± 3.82 TECU (100.1% do valor)

========================================================================================================================
TABELA RESUMO DOS RESULTADOS
========================================================================================================================
#  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-01 18:00:00 2024-12-01 18:00:00 0.00    79.52    3.82    Sim         -3.02
-------------------------------------------------------------------------------------------------

Análise concluída!

================================================================================
ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS
================================================================================
Valores TEC encontrados:
  Mínimo: 79.52 TECU
  Máximo: 79.52 TECU
  Média: 79.52 TECU
  Desvio padrão: 0.00 TECU

Sequências de valores altos encontradas: 1 de 1 (100.0%)

# IGS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_igs_maps_2024 = pd.read_pickle('/content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [ ]:
df_igs_maps_2024

               DATETIME                                             TECMAP
0   2024-12-01 00:00:00  [[37.7, 34.6, 31.9, 30.0, 28.6, 27.2, 25.8, 24...
1   2024-12-01 02:00:00  [[20.3, 18.7, 18.1, 18.2, 18.2, 18.1, 17.7, 17...
2   2024-12-01 04:00:00  [[11.6, 11.8, 12.0, 12.4, 13.0, 13.5, 14.0, 14...
3   2024-12-01 06:00:00  [[10.4, 10.8, 11.1, 11.7, 12.1, 12.7, 13.3, 13...
4   2024-12-01 08:00:00  [[9.9, 10.1, 10.3, 10.6, 11.0, 11.6, 12.3, 13....
..                  ...                                                ...
343 2024-12-30 14:00:00  [[8.9, 11.1, 14.4, 18.8, 23.7, 28.3, 32.7, 36....
344 2024-12-30 16:00:00  [[26.3, 29.8, 33.4, 37.1, 40.5, 43.7, 47.0, 49...
345 2024-12-30 18:00:00  [[43.5, 44.5, 45.3, 46.2, 47.1, 48.6, 50.0, 51...
346 2024-12-30 20:00:00  [[48.8, 49.1, 49.0, 48.7, 48.5, 48.1, 48.0, 47...
347 2024-12-30 22:00:00  [[47.0, 46.6, 45.6, 44.4, 43.2, 42.0, 40.4, 38...

[348 rows x 2 columns]

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:

    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(igs_points)

[(-5.0, -65, 30, 9), (-5.0, -60, 30, 10), (-2.5, -65, 31, 9), (-2.5, -60, 31, 10)]

In [ ]:
igs_points

[(-5.0, -65, 30, 9),
 (-5.0, -60, 30, 10),
 (-2.5, -65, 31, 9),
 (-2.5, -60, 31, 10)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -5.0°,  -65.0°) - Indexes: [30,  9] - TEC:  72.7
   P2: (  -5.0°,  -60.0°) - Indexes: [30, 10] - TEC:  71.5
   P3: (  -2.5°,  -65.0°) - Indexes: [31,  9] - TEC:  68.9
   P4: (  -2.5°,  -60.0°) - Indexes: [31, 10] - TEC:  67.7

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -5.0° to   -2.5° (range:  2.5°)
   Longitude:  -65.0° to  -60.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -5.0°,  -65.0°) =  72.7
   f_01 (lat_min, lon_max) = (  -5.0°,  -60.0°) =  71.5
   f_10 (lat_max, lon_min) = (  -2.5°,  -65.0°) =  68.9
   f_11 (lat_max, lon_max) = (  -2.5°,  -60.0°) =  67.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -65.0)) / ( -60.0 - ( -65.0))
   t_x = 4.94498 /  5.0 = 0.988996

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -5.0)) / (  -2.5 - (  -5.0))
   t_y = 1.97708 /  2.5 = 0.790832

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.988996) * (1 - 0.790832) = 0.002302
   w_01 = t_x * (1 - t_y)       = 0.988996 * (1 - 0.790832)       = 0.206866
   w_10 = (1 - t_x) * t_y       = (1 - 0.988996) * 0.790832       = 0.008702
   w_11 = t_x * t_y             = 0.988996 * 0.790832             = 0.782130
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.002302* 72.7 + 0.206866* 71.5 + 0.008702* 68.9 + 0.782130* 67.7
   Value =   0.1673 +  14.7909 +   0.5996 +  52.9502
   Value = 68.508043

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 98.90% of the way from -65° to -60°
   In Y direction (latitude):  79.08% of the way from -5.0° to -2.5°

============================================================
FINAL RESULT: TEC = 68.5080
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
249 2024-12-22 18:00:00  [[48.9, 51.6, 53.7, 54.6, 54.9, 54.7, 54.6, 54...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[48.9, 51.6, 53.7, ..., 23. , 21.7, 20.7],
        [49.6, 52. , 53.9, ..., 25.5, 24.4, 23. ],
        [50.2, 52.1, 53.8, ..., 30.7, 29.2, 27.9],
        ...,
        [24.7, 24.7, 24.4, ..., 20.9, 20.5, 20.2],
        [25. , 24.9, 24.8, ..., 21.5, 21. , 20.8],
        [24.7, 24.8, 24.5, ..., 21.6, 21.2, 20.9]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(igs_points)

[(-5.0, -65, 30, 9), (-5.0, -60, 30, 10), (-2.5, -65, 31, 9), (-2.5, -60, 31, 10)]

In [ ]:
igs_points

[(-5.0, -65, 30, 9),
 (-5.0, -60, 30, 10),
 (-2.5, -65, 31, 9),
 (-2.5, -60, 31, 10)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -5.0°,  -65.0°) - Indexes: [30,  9] - TEC:  76.1
   P2: (  -5.0°,  -60.0°) - Indexes: [30, 10] - TEC:  75.4
   P3: (  -2.5°,  -65.0°) - Indexes: [31,  9] - TEC:  72.5
   P4: (  -2.5°,  -60.0°) - Indexes: [31, 10] - TEC:  71.7

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -5.0° to   -2.5° (range:  2.5°)
   Longitude:  -65.0° to  -60.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -5.0°,  -65.0°) =  76.1
   f_01 (lat_min, lon_max) = (  -5.0°,  -60.0°) =  75.4
   f_10 (lat_max, lon_min) = (  -2.5°,  -65.0°) =  72.5
   f_11 (lat_max, lon_max) = (  -2.5°,  -60.0°) =  71.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -65.0)) / ( -60.0 - ( -65.0))
   t_x = 4.94498 /  5.0 = 0.988996

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -5.0)) / (  -2.5 - (  -5.0))
   t_y = 1.97708 /  2.5 = 0.790832

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.988996) * (1 - 0.790832) = 0.002302
   w_01 = t_x * (1 - t_y)       = 0.988996 * (1 - 0.790832)       = 0.206866
   w_10 = (1 - t_x) * t_y       = (1 - 0.988996) * 0.790832       = 0.008702
   w_11 = t_x * t_y             = 0.988996 * 0.790832             = 0.782130
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.002302* 76.1 + 0.206866* 75.4 + 0.008702* 72.5 + 0.782130* 71.7
   Value =   0.1752 +  15.5977 +   0.6309 +  56.0787
   Value = 72.482495

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 98.90% of the way from -65° to -60°
   In Y direction (latitude):  79.08% of the way from -5.0° to -2.5°

============================================================
FINAL RESULT: TEC = 72.4825
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
213 2024-12-19 18:00:00  [[36.1, 39.3, 41.5, 42.6, 42.4, 41.2, 39.2, 37...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[36.1, 39.3, 41.5, ..., 15. , 14.4, 14.1],
        [37.3, 40. , 42.4, ..., 17. , 16.5, 16.2],
        [38.2, 40.5, 42.6, ..., 20.6, 20.1, 19.7],
        ...,
        [23.4, 23.3, 23.2, ..., 23.6, 23.2, 22.9],
        [23.3, 23.2, 23.1, ..., 23.7, 23.5, 23.2],
        [23. , 23.1, 22.9, ..., 23.5, 23.6, 23.5]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):
        """
        Função para encontrar os 4 pontos da grade mais próximos
        a uma coordenada específica
        """
        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(igs_points)

[(-5.0, -65, 30, 9), (-5.0, -60, 30, 10), (-2.5, -65, 31, 9), (-2.5, -60, 31, 10)]

In [ ]:
igs_points

[(-5.0, -65, 30, 9),
 (-5.0, -60, 30, 10),
 (-2.5, -65, 31, 9),
 (-2.5, -60, 31, 10)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -5.0°,  -65.0°) - Indexes: [30,  9] - TEC:  78.5
   P2: (  -5.0°,  -60.0°) - Indexes: [30, 10] - TEC:  77.0
   P3: (  -2.5°,  -65.0°) - Indexes: [31,  9] - TEC:  75.5
   P4: (  -2.5°,  -60.0°) - Indexes: [31, 10] - TEC:  73.8

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -5.0° to   -2.5° (range:  2.5°)
   Longitude:  -65.0° to  -60.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -5.0°,  -65.0°) =  78.5
   f_01 (lat_min, lon_max) = (  -5.0°,  -60.0°) =  77.0
   f_10 (lat_max, lon_min) = (  -2.5°,  -65.0°) =  75.5
   f_11 (lat_max, lon_max) = (  -2.5°,  -60.0°) =  73.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -65.0)) / ( -60.0 - ( -65.0))
   t_x = 4.94498 /  5.0 = 0.988996

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -5.0)) / (  -2.5 - (  -5.0))
   t_y = 1.97708 /  2.5 = 0.790832

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.988996) * (1 - 0.790832) = 0.002302
   w_01 = t_x * (1 - t_y)       = 0.988996 * (1 - 0.790832)       = 0.206866
   w_10 = (1 - t_x) * t_y       = (1 - 0.988996) * 0.790832       = 0.008702
   w_11 = t_x * t_y             = 0.988996 * 0.790832             = 0.782130
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.002302* 78.5 + 0.206866* 77.0 + 0.008702* 75.5 + 0.782130* 73.8
   Value =   0.1807 +  15.9287 +   0.6570 +  57.7212
   Value = 74.487584

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 98.90% of the way from -65° to -60°
   In Y direction (latitude):  79.08% of the way from -5.0° to -2.5°

============================================================
FINAL RESULT: TEC = 74.4876
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

             DATETIME                                             TECMAP
9 2024-12-01 18:00:00  [[50.5, 53.3, 54.8, 55.0, 54.6, 54.1, 54.0, 54...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[50.5, 53.3, 54.8, ..., 26.7, 24.5, 22.9],
        [50.2, 52.6, 54.1, ..., 30.3, 28.1, 26.2],
        [50.4, 52.2, 53.4, ..., 36.6, 34. , 31.8],
        ...,
        [30.4, 30.4, 30.2, ..., 23.1, 22.6, 22. ],
        [30.3, 30.3, 30.1, ..., 23.2, 22.9, 22.5],
        [29.4, 29.3, 29.2, ..., 23.3, 23.1, 22.8]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):
        """
        Função para encontrar os 4 pontos da grade mais próximos
        a uma coordenada específica
        """
        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(igs_points)

[(-5.0, -65, 30, 9), (-5.0, -60, 30, 10), (-2.5, -65, 31, 9), (-2.5, -60, 31, 10)]

In [ ]:
igs_points

[(-5.0, -65, 30, 9),
 (-5.0, -60, 30, 10),
 (-2.5, -65, 31, 9),
 (-2.5, -60, 31, 10)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -5.0°,  -65.0°) - Indexes: [30,  9] - TEC:  72.3
   P2: (  -5.0°,  -60.0°) - Indexes: [30, 10] - TEC:  73.2
   P3: (  -2.5°,  -65.0°) - Indexes: [31,  9] - TEC:  67.5
   P4: (  -2.5°,  -60.0°) - Indexes: [31, 10] - TEC:  68.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -5.0° to   -2.5° (range:  2.5°)
   Longitude:  -65.0° to  -60.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -5.0°,  -65.0°) =  72.3
   f_01 (lat_min, lon_max) = (  -5.0°,  -60.0°) =  73.2
   f_10 (lat_max, lon_min) = (  -2.5°,  -65.0°) =  67.5
   f_11 (lat_max, lon_max) = (  -2.5°,  -60.0°) =  68.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -65.0)) / ( -60.0 - ( -65.0))
   t_x = 4.94498 /  5.0 = 0.988996

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -5.0)) / (  -2.5 - (  -5.0))
   t_y = 1.97708 /  2.5 = 0.790832

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.988996) * (1 - 0.790832) = 0.002302
   w_01 = t_x * (1 - t_y)       = 0.988996 * (1 - 0.790832)       = 0.206866
   w_10 = (1 - t_x) * t_y       = (1 - 0.988996) * 0.790832       = 0.008702
   w_11 = t_x * t_y             = 0.988996 * 0.790832             = 0.782130
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.002302* 72.3 + 0.206866* 73.2 + 0.008702* 67.5 + 0.782130* 68.0
   Value =   0.1664 +  15.1426 +   0.5874 +  53.1848
   Value = 69.081251

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 98.90% of the way from -65° to -60°
   In Y direction (latitude):  79.08% of the way from -5.0° to -2.5°

============================================================
FINAL RESULT: TEC = 69.0813
============================================================

# Nagoya

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_nagoya_maps_2024 = pd.read_pickle('TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [ ]:
df_nagoya_maps_2024

                DATETIME                                             TECMAP
0    2024-12-01 00:00:00  [[18.593109130859375, 19.42150115966797, 19.42...
1    2024-12-01 00:05:00  [[18.222612380981445, 18.222612380981445, 18.2...
2    2024-12-01 00:10:00  [[18.21422576904297, 18.21422576904297, 18.214...
3    2024-12-01 00:15:00  [[18.284513473510742, 18.284513473510742, 18.0...
4    2024-12-01 00:20:00  [[18.328298568725586, 18.328298568725586, 18.0...
...                  ...                                                ...
8347 2024-12-30 23:35:00  [[26.173906326293945, 27.259140014648438, 27.2...
8348 2024-12-30 23:40:00  [[27.0389347076416, 27.0389347076416, 27.03893...
8349 2024-12-30 23:45:00  [[26.902502059936523, 26.72080421447754, 25.94...
8350 2024-12-30 23:50:00  [[27.88735580444336, 27.88735580444336, 27.887...
8351 2024-12-30 23:55:00  [[24.682987213134766, 25.294950485229492, 25.2...

[8352 rows x 2 columns]

## 12/18/2024 - 18:20

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4828 2024-12-18 18:20:00  [[18.751976013183594, 18.751976013183594, 18.8...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.25943375, 18.13648224, 18.13648224, ...,         nan,
                 nan,         nan],
        ...,
        [38.79235458, 39.10980225, 39.51619339, ..., 13.45065308,
         13.1072731 , 12.96411705],
        [38.38473892, 38.68589783, 39.00465393, ..., 13.27555275,
         12.90675449, 12.72219276],
        [38.23902512, 38.27802277, 38.43577194, ..., 12.968153  ,
         12.60940075, 12.51128292]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(nagoya_points)

[(-3.4000000000000057, -60.5, 154, 99), (-3.4000000000000057, -60.0, 154, 100), (-2.9000000000000057, -60.5, 155, 99), (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_points

[(-3.4000000000000057, -60.5, 154, 99),
 (-3.4000000000000057, -60.0, 154, 100),
 (-2.9000000000000057, -60.5, 155, 99),
 (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.4°,  -60.5°) - Indexes: [154, 99] - TEC:  61.5
   P2: (  -3.4°,  -60.0°) - Indexes: [154, 100] - TEC:  60.7
   P3: (  -2.9°,  -60.5°) - Indexes: [155, 99] - TEC:  62.7
   P4: (  -2.9°,  -60.0°) - Indexes: [155, 100] - TEC:  60.7

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.4° to   -2.9° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.4°,  -60.5°) =  61.5
   f_01 (lat_min, lon_max) = (  -3.4°,  -60.0°) =  60.7
   f_10 (lat_max, lon_min) = (  -2.9°,  -60.5°) =  62.7
   f_11 (lat_max, lon_max) = (  -2.9°,  -60.0°) =  60.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.4)) / (  -2.9 - (  -3.4))
   t_y = 0.37708 /  0.5 = 0.754160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.754160) = 0.027052
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.754160)       = 0.218788
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.754160       = 0.082988
   w_11 = t_x * t_y             = 0.889960 * 0.754160             = 0.671172
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.027052* 61.5 + 0.218788* 60.7 + 0.082988* 62.7 + 0.671172* 60.7
   Value =   1.6650 +  13.2780 +   5.2043 +  40.7326
   Value = 60.879866

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  75.42% of the way from -3.4000000000000057° to -2.9000000000000057°

============================================================
FINAL RESULT: TEC = 60.8799
============================================================

## 12/18/2024 - 18:10

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4826 2024-12-18 18:10:00  [[18.412939071655273, 17.651090621948242, 17.6...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[18.41293907, 17.65109062, 17.65109062, ...,         nan,
                 nan,         nan],
        [18.53962135, 17.62540054, 17.62540054, ...,         nan,
                 nan,         nan],
        [17.62013054, 17.62013054, 17.62540054, ...,         nan,
                 nan,         nan],
        ...,
        [36.95772552, 37.32144928, 37.6816864 , ..., 14.07102394,
         13.53792286, 13.37452602],
        [37.09318542, 37.28800964, 37.65478134, ..., 13.818923  ,
         13.44021893, 13.28282356],
        [36.133461  , 36.14941025, 36.71422577, ..., 13.40729332,
         13.00967979, 13.02010918]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(nagoya_points)

[(-3.4000000000000057, -60.5, 154, 99), (-3.4000000000000057, -60.0, 154, 100), (-2.9000000000000057, -60.5, 155, 99), (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_points

[(-3.4000000000000057, -60.5, 154, 99),
 (-3.4000000000000057, -60.0, 154, 100),
 (-2.9000000000000057, -60.5, 155, 99),
 (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.4°,  -60.5°) - Indexes: [154, 99] - TEC:  61.8
   P2: (  -3.4°,  -60.0°) - Indexes: [154, 100] - TEC:  61.0
   P3: (  -2.9°,  -60.5°) - Indexes: [155, 99] - TEC:  61.0
   P4: (  -2.9°,  -60.0°) - Indexes: [155, 100] - TEC:  61.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.4° to   -2.9° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.4°,  -60.5°) =  61.8
   f_01 (lat_min, lon_max) = (  -3.4°,  -60.0°) =  61.0
   f_10 (lat_max, lon_min) = (  -2.9°,  -60.5°) =  61.0
   f_11 (lat_max, lon_max) = (  -2.9°,  -60.0°) =  61.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.4)) / (  -2.9 - (  -3.4))
   t_y = 0.37708 /  0.5 = 0.754160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.754160) = 0.027052
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.754160)       = 0.218788
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.754160       = 0.082988
   w_11 = t_x * t_y             = 0.889960 * 0.754160             = 0.671172
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.027052* 61.8 + 0.218788* 61.0 + 0.082988* 61.0 + 0.671172* 61.0
   Value =   1.6722 +  13.3465 +   5.0624 +  40.9428
   Value = 61.023841

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  75.42% of the way from -3.4000000000000057° to -2.9000000000000057°

============================================================
FINAL RESULT: TEC = 61.0238
============================================================

## 12/18/2024 - 18:30

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4830 2024-12-18 18:30:00  [[21.299997329711914, 21.299997329711914, 21.2...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.28308678, 21.28308678, 21.28308678, ...,         nan,
                 nan,         nan],
        ...,
        [39.65393066, 40.11976624, 40.50592804, ..., 13.14062977,
         12.80635357, 12.63247967],
        [39.26050949, 39.7519455 , 40.19271851, ..., 12.65815067,
         12.54124069, 12.46903992],
        [39.23273468, 39.40169144, 39.72786331, ..., 12.41631317,
         12.32884121, 12.25786972]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(nagoya_points)

[(-3.4000000000000057, -60.5, 154, 99), (-3.4000000000000057, -60.0, 154, 100), (-2.9000000000000057, -60.5, 155, 99), (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_points

[(-3.4000000000000057, -60.5, 154, 99),
 (-3.4000000000000057, -60.0, 154, 100),
 (-2.9000000000000057, -60.5, 155, 99),
 (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.4°,  -60.5°) - Indexes: [154, 99] - TEC:  62.9
   P2: (  -3.4°,  -60.0°) - Indexes: [154, 100] - TEC:  60.5
   P3: (  -2.9°,  -60.5°) - Indexes: [155, 99] - TEC:  64.1
   P4: (  -2.9°,  -60.0°) - Indexes: [155, 100] - TEC:  61.7

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.4° to   -2.9° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.4°,  -60.5°) =  62.9
   f_01 (lat_min, lon_max) = (  -3.4°,  -60.0°) =  60.5
   f_10 (lat_max, lon_min) = (  -2.9°,  -60.5°) =  64.1
   f_11 (lat_max, lon_max) = (  -2.9°,  -60.0°) =  61.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.4)) / (  -2.9 - (  -3.4))
   t_y = 0.37708 /  0.5 = 0.754160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.754160) = 0.027052
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.754160)       = 0.218788
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.754160       = 0.082988
   w_11 = t_x * t_y             = 0.889960 * 0.754160             = 0.671172
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.027052* 62.9 + 0.218788* 60.5 + 0.082988* 64.1 + 0.671172* 61.7
   Value =   1.7016 +  13.2374 +   5.3182 +  41.3826
   Value = 61.639767

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  75.42% of the way from -3.4000000000000057° to -2.9000000000000057°

============================================================
FINAL RESULT: TEC = 61.6398
============================================================

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(nagoya_points)

[(-3.4000000000000057, -60.5, 154, 99), (-3.4000000000000057, -60.0, 154, 100), (-2.9000000000000057, -60.5, 155, 99), (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_points

[(-3.4000000000000057, -60.5, 154, 99),
 (-3.4000000000000057, -60.0, 154, 100),
 (-2.9000000000000057, -60.5, 155, 99),
 (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.4°,  -60.5°) - Indexes: [154, 99] - TEC:  62.3
   P2: (  -3.4°,  -60.0°) - Indexes: [154, 100] - TEC:  61.6
   P3: (  -2.9°,  -60.5°) - Indexes: [155, 99] - TEC:  61.6
   P4: (  -2.9°,  -60.0°) - Indexes: [155, 100] - TEC:  61.6

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.4° to   -2.9° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.4°,  -60.5°) =  62.3
   f_01 (lat_min, lon_max) = (  -3.4°,  -60.0°) =  61.6
   f_10 (lat_max, lon_min) = (  -2.9°,  -60.5°) =  61.6
   f_11 (lat_max, lon_max) = (  -2.9°,  -60.0°) =  61.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.4)) / (  -2.9 - (  -3.4))
   t_y = 0.37708 /  0.5 = 0.754160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.754160) = 0.027052
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.754160)       = 0.218788
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.754160       = 0.082988
   w_11 = t_x * t_y             = 0.889960 * 0.754160             = 0.671172
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.027052* 62.3 + 0.218788* 61.6 + 0.082988* 61.6 + 0.671172* 61.6
   Value =   1.6846 +  13.4675 +   5.1083 +  41.3142
   Value = 61.574691

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  75.42% of the way from -3.4000000000000057° to -2.9000000000000057°

============================================================
FINAL RESULT: TEC = 61.5747
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
5976 2024-12-22 18:00:00  [[14.305987358093262, 14.235016822814941, 15.1...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[14.30598736, 14.23501682, 15.19717693, ...,         nan,
                 nan,         nan],
        [13.24124527, 13.24124527, 13.24124527, ...,         nan,
                 nan,         nan],
        [13.24124527, 13.24124527, 13.24124527, ...,         nan,
                 nan,         nan],
        ...,
        [43.63508224, 43.97467422, 44.23501205, ..., 20.72278595,
         20.15914345, 19.78045845],
        [43.53390503, 43.86975861, 44.0747261 , ..., 20.29078865,
         19.64533615, 19.32730103],
        [43.54644394, 43.77022934, 43.95893478, ..., 19.72059822,
         19.0694046 , 18.65716362]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(nagoya_points)

[(-3.4000000000000057, -60.5, 154, 99), (-3.4000000000000057, -60.0, 154, 100), (-2.9000000000000057, -60.5, 155, 99), (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_points

[(-3.4000000000000057, -60.5, 154, 99),
 (-3.4000000000000057, -60.0, 154, 100),
 (-2.9000000000000057, -60.5, 155, 99),
 (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.4°,  -60.5°) - Indexes: [154, 99] - TEC:  66.8
   P2: (  -3.4°,  -60.0°) - Indexes: [154, 100] - TEC:  66.3
   P3: (  -2.9°,  -60.5°) - Indexes: [155, 99] - TEC:  68.2
   P4: (  -2.9°,  -60.0°) - Indexes: [155, 100] - TEC:  66.3

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.4° to   -2.9° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.4°,  -60.5°) =  66.8
   f_01 (lat_min, lon_max) = (  -3.4°,  -60.0°) =  66.3
   f_10 (lat_max, lon_min) = (  -2.9°,  -60.5°) =  68.2
   f_11 (lat_max, lon_max) = (  -2.9°,  -60.0°) =  66.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.4)) / (  -2.9 - (  -3.4))
   t_y = 0.37708 /  0.5 = 0.754160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.754160) = 0.027052
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.754160)       = 0.218788
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.754160       = 0.082988
   w_11 = t_x * t_y             = 0.889960 * 0.754160             = 0.671172
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.027052* 66.8 + 0.218788* 66.3 + 0.082988* 68.2 + 0.671172* 66.3
   Value =   1.8074 +  14.5059 +   5.6612 +  44.4995
   Value = 66.473998

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  75.42% of the way from -3.4000000000000057° to -2.9000000000000057°

============================================================
FINAL RESULT: TEC = 66.4740
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
5112 2024-12-19 18:00:00  [[12.639724731445312, 11.565997123718262, 11.5...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[12.63972473, 11.56599712, 11.56599712, ...,         nan,
                 nan,         nan],
        [11.71732426, 10.61837482, 10.61837482, ...,         nan,
                 nan,         nan],
        [14.18716908, 11.54071808, 10.25730038, ...,         nan,
                 nan,         nan],
        ...,
        [34.01515198, 34.48353958, 34.89712906, ..., 11.77007103,
         11.27845764, 11.27845764],
        [33.72997284, 33.06239319, 33.53577042, ..., 11.66871548,
         11.30887318, 11.18506527],
        [33.0634613 , 32.32966614, 32.78850937, ..., 11.32422161,
         11.1510849 , 11.04978752]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(nagoya_points)

[(-3.4000000000000057, -60.5, 154, 99), (-3.4000000000000057, -60.0, 154, 100), (-2.9000000000000057, -60.5, 155, 99), (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_points

[(-3.4000000000000057, -60.5, 154, 99),
 (-3.4000000000000057, -60.0, 154, 100),
 (-2.9000000000000057, -60.5, 155, 99),
 (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.4°,  -60.5°) - Indexes: [154, 99] - TEC:  64.2
   P2: (  -3.4°,  -60.0°) - Indexes: [154, 100] - TEC:  64.9
   P3: (  -2.9°,  -60.5°) - Indexes: [155, 99] - TEC:  64.9
   P4: (  -2.9°,  -60.0°) - Indexes: [155, 100] - TEC:  64.9

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.4° to   -2.9° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.4°,  -60.5°) =  64.2
   f_01 (lat_min, lon_max) = (  -3.4°,  -60.0°) =  64.9
   f_10 (lat_max, lon_min) = (  -2.9°,  -60.5°) =  64.9
   f_11 (lat_max, lon_max) = (  -2.9°,  -60.0°) =  64.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.4)) / (  -2.9 - (  -3.4))
   t_y = 0.37708 /  0.5 = 0.754160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.754160) = 0.027052
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.754160)       = 0.218788
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.754160       = 0.082988
   w_11 = t_x * t_y             = 0.889960 * 0.754160             = 0.671172
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.027052* 64.2 + 0.218788* 64.9 + 0.082988* 64.9 + 0.671172* 64.9
   Value =   1.7355 +  14.2019 +   5.3869 +  43.5669
   Value = 64.891174

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  75.42% of the way from -3.4000000000000057° to -2.9000000000000057°

============================================================
FINAL RESULT: TEC = 64.8912
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
216 2024-12-01 18:00:00  [[5.463457107543945, 5.463457107543945, 5.4634...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[ 5.46345711,  5.46345711,  5.46345711, ...,         nan,
                 nan,         nan],
        [ 9.9241066 , 10.95889568, 10.95889568, ...,         nan,
                 nan,         nan],
        [14.80212975, 14.80212975, 14.12398911, ...,         nan,
                 nan,         nan],
        ...,
        [43.88991547, 44.48843002, 44.89578247, ..., 21.9361248 ,
         21.8728199 , 21.43001556],
        [44.12051773, 44.59725952, 44.77046967, ..., 21.9361248 ,
         21.76833344, 21.42024994],
        [44.22133255, 44.64913177, 44.84080887, ..., 21.9361248 ,
         21.67697716, 21.29607773]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(nagoya_points)

[(-3.4000000000000057, -60.5, 154, 99), (-3.4000000000000057, -60.0, 154, 100), (-2.9000000000000057, -60.5, 155, 99), (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_points

[(-3.4000000000000057, -60.5, 154, 99),
 (-3.4000000000000057, -60.0, 154, 100),
 (-2.9000000000000057, -60.5, 155, 99),
 (-2.9000000000000057, -60.0, 155, 100)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.4°,  -60.5°) - Indexes: [154, 99] - TEC:   nan
   P2: (  -3.4°,  -60.0°) - Indexes: [154, 100] - TEC:  81.0
   P3: (  -2.9°,  -60.5°) - Indexes: [155, 99] - TEC:   nan
   P4: (  -2.9°,  -60.0°) - Indexes: [155, 100] - TEC:  81.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.4° to   -2.9° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.4°,  -60.5°) =   nan
   f_01 (lat_min, lon_max) = (  -3.4°,  -60.0°) =  81.0
   f_10 (lat_max, lon_min) = (  -2.9°,  -60.5°) =   nan
   f_11 (lat_max, lon_max) = (  -2.9°,  -60.0°) =  81.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.4)) / (  -2.9 - (  -3.4))
   t_y = 0.37708 /  0.5 = 0.754160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.754160) = 0.027052
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.754160)       = 0.218788
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.754160       = 0.082988
   w_11 = t_x * t_y             = 0.889960 * 0.754160             = 0.671172
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.027052*  nan + 0.218788* 81.0 + 0.082988*  nan + 0.671172* 81.0
   Value =      nan +  17.7133 +      nan +  54.3388
   Value = nan

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  75.42% of the way from -3.4000000000000057° to -2.9000000000000057°

============================================================
FINAL RESULT: TEC = nan
============================================================

# EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_embrace_maps_2024

                                                                TECMAP
DATETIME
2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[16704 rows x 1 columns]

## 12/18/2024 - 18:20

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  65.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  65.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  63.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  60.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  65.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  65.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  63.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  60.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x = 2.44498 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y = 0.97708 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 65.0 + 0.500204* 65.0 + 0.010752* 63.0 + 0.477788* 60.0
   Value =   0.7317 +  32.5132 +   0.6774 +  28.6673
   Value = 62.589555

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 62.5896
============================================================

## 12/18/2024 - 18:10

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 37., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  63.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  65.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  63.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  60.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  63.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  65.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  63.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  60.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x = 2.44498 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y = 0.97708 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 63.0 + 0.500204* 65.0 + 0.010752* 63.0 + 0.477788* 60.0
   Value =   0.7091 +  32.5132 +   0.6774 +  28.6673
   Value = 62.567043

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 62.5670
============================================================

## 12/18/2024 - 18:30

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  65.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  65.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  64.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  60.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  65.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  65.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  64.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  60.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x = 2.44498 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y = 0.97708 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 65.0 + 0.500204* 65.0 + 0.010752* 64.0 + 0.477788* 60.0
   Value =   0.7317 +  32.5132 +   0.6881 +  28.6673
   Value = 62.600307

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 62.6003
============================================================

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  64.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  65.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  64.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  61.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  64.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  65.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  64.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  61.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x = 2.44498 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y = 0.97708 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 64.0 + 0.500204* 65.0 + 0.010752* 64.0 + 0.477788* 61.0
   Value =   0.7204 +  32.5132 +   0.6881 +  29.1451
   Value = 63.066839

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 63.0668
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-22 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 52., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  69.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  68.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  68.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  67.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  69.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  68.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  68.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  67.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x = 2.44498 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y = 0.97708 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 69.0 + 0.500204* 68.0 + 0.010752* 68.0 + 0.477788* 67.0
   Value =   0.7767 +  34.0139 +   0.7311 +  32.0118
   Value = 67.533468

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 67.5335
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-19 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 41., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  64.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  63.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  69.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  61.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  64.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  63.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  69.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  61.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x = 2.44498 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y = 0.97708 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 64.0 + 0.500204* 63.0 + 0.010752* 69.0 + 0.477788* 61.0
   Value =   0.7204 +  31.5128 +   0.7419 +  29.1451
   Value = 62.120191

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 62.1202
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-01 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 46., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(embrace_points)

[(-4, -62.5, 28, 11), (-4, -60.0, 28, 12), (-2, -62.5, 29, 11), (-2, -60.0, 29, 12)]

In [ ]:
embrace_points

[(-4, -62.5, 28, 11),
 (-4, -60.0, 28, 12),
 (-2, -62.5, 29, 11),
 (-2, -60.0, 29, 12)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -62.5°) - Indexes: [28, 11] - TEC:  81.0
   P2: (  -4.0°,  -60.0°) - Indexes: [28, 12] - TEC:  80.0
   P3: (  -2.0°,  -62.5°) - Indexes: [29, 11] - TEC:  77.0
   P4: (  -2.0°,  -60.0°) - Indexes: [29, 12] - TEC:  78.0

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -62.5° to  -60.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -62.5°) =  81.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -60.0°) =  80.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -62.5°) =  77.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -60.0°) =  78.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -62.5)) / ( -60.0 - ( -62.5))
   t_x = 2.44498 /  2.5 = 0.977992

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y = 0.97708 /  2.0 = 0.488540

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.977992) * (1 - 0.488540) = 0.011256
   w_01 = t_x * (1 - t_y)       = 0.977992 * (1 - 0.488540)       = 0.500204
   w_10 = (1 - t_x) * t_y       = (1 - 0.977992) * 0.488540       = 0.010752
   w_11 = t_x * t_y             = 0.977992 * 0.488540             = 0.477788
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.011256* 81.0 + 0.500204* 80.0 + 0.010752* 77.0 + 0.477788* 78.0
   Value =   0.9118 +  40.0163 +   0.8279 +  37.2675
   Value = 79.023424

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 97.80% of the way from -62.5° to -60.0°
   In Y direction (latitude):  48.85% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 79.0234
============================================================

# MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024

                 DATETIME                                             TECMAP
0     2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2024-09-05 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
15619 2024-12-31 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15620 2024-12-31 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15621 2024-12-31 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15622 2024-12-31 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15623 2024-12-31 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[15624 rows x 2 columns]

## 12/18/2024 - 18:20

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13718 2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [40.14899826, 40.15000153, 40.18000031, ..., 13.84500027,
         13.67500019, 13.12800026],
        [39.97399902, 40.02799988, 40.15399933, ..., 13.75800037,
         13.67599964, 12.39599991],
        [39.73500061, 39.83499908, 40.02500153, ..., 13.10700035,
         12.6239996 , 12.06000042]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(maggia_points)

[(-3.5, -60.5, 153, 99), (-3.5, -60.0, 153, 100), (-3.0, -60.5, 154, 99), (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  89.9
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  89.2
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  89.7
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  89.5

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  89.9
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  89.2
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  89.7
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  89.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y = 0.47708 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 89.9 + 0.040796* 89.2 + 0.104996* 89.7 + 0.849164* 89.5
   Value =   0.4537 +   3.6385 +   9.4223 +  75.9977
   Value = 89.512098

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 89.5121
============================================================

## 12/18/2024 - 18:10

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13717 2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [36.83499908, 37.06399918, 37.23899841, ..., 12.40799999,
         12.40799999, 12.40799999],
        [36.57699966, 36.82799911, 37.03300095, ..., 12.85900021,
         12.6619997 , 12.54399967],
        [36.34600067, 36.5909996 , 36.81399918, ..., 13.00500011,
         12.82999992, 12.32600021]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(maggia_points)

[(-3.5, -60.5, 153, 99), (-3.5, -60.0, 153, 100), (-3.0, -60.5, 154, 99), (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  97.4
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  91.8
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  99.2
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  94.6

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  97.4
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  91.8
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  99.2
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  94.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y = 0.47708 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 97.4 + 0.040796* 91.8 + 0.104996* 99.2 + 0.849164* 94.6
   Value =   0.4913 +   3.7434 +  10.4207 +  80.3377
   Value = 94.993169

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 94.9932
============================================================

## 12/18/2024 - 18:30

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13719 2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.94900131, 41.94900131, 41.94900131, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.94400024, 41.94400024, 41.94499969, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.89500046, 41.89799881, 41.90100098, ..., 11.36600018,
         11.25800037, 11.1960001 ]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(maggia_points)

[(-3.5, -60.5, 153, 99), (-3.5, -60.0, 153, 100), (-3.0, -60.5, 154, 99), (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  88.1
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  87.0
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  88.6
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  87.4

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  88.1
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  87.0
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  88.6
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  87.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y = 0.47708 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 88.1 + 0.040796* 87.0 + 0.104996* 88.6 + 0.849164* 87.4
   Value =   0.4442 +   3.5500 +   9.3025 +  74.2178
   Value = 87.514572

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 87.5146
============================================================

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(maggia_points)

[(-3.5, -60.5, 153, 99), (-3.5, -60.0, 153, 100), (-3.0, -60.5, 154, 99), (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  87.0
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  87.4
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  87.2
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  87.4

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  87.0
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  87.4
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  87.2
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  87.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y = 0.47708 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 87.0 + 0.040796* 87.4 + 0.104996* 87.2 + 0.849164* 87.4
   Value =   0.4387 +   3.5667 +   9.1516 +  74.2416
   Value = 87.398702

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 87.3987
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
14292 2024-12-22 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.41400146, 48.5379982 , 48.59199905, ..., 19.10899925,
         17.45599937, 17.45599937],
        [48.26200104, 48.41799927, 48.52799988, ..., 18.8560009 ,
         18.24600029, 17.79299927],
        [48.11100006, 48.27999878, 48.42100143, ..., 19.0890007 ,
         18.74200058, 18.39999962]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(maggia_points)

[(-3.5, -60.5, 153, 99), (-3.5, -60.0, 153, 100), (-3.0, -60.5, 154, 99), (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  91.9
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  95.0
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  91.4
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  93.1

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  91.9
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  95.0
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  91.4
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  93.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y = 0.47708 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 91.9 + 0.040796* 95.0 + 0.104996* 91.4 + 0.849164* 93.1
   Value =   0.4635 +   3.8739 +   9.5978 +  79.0988
   Value = 93.034039

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 93.0340
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13860 2024-12-19 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [37.94499969, 38.06100082, 38.13499832, ..., 11.56599998,
         11.17399979, 10.60200024],
        [37.7840004 , 37.92599869, 38.02999878, ..., 11.47599983,
         10.99199963, 10.38300037],
        [37.63499832, 37.77899933, 37.90499878, ..., 11.36100006,
         10.8739996 , 10.52200031]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(maggia_points)

[(-3.5, -60.5, 153, 99), (-3.5, -60.0, 153, 100), (-3.0, -60.5, 154, 99), (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC:  83.6
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC:  81.4
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC:  84.1
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC:  82.9

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) =  83.6
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) =  81.4
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) =  84.1
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) =  82.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y = 0.47708 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044* 83.6 + 0.040796* 81.4 + 0.104996* 84.1 + 0.849164* 82.9
   Value =   0.4215 +   3.3219 +   8.8305 +  70.3668
   Value = 82.940759

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 82.9408
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
11268 2024-12-01 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [45.95299911, 45.88100052, 45.71300125, ..., 23.45899963,
         23.20400047, 22.93400002],
        [45.90299988, 45.8370018 , 45.67300034, ..., 23.38800049,
         23.23900032, 23.04000092],
        [45.86399841, 45.79700089, 45.63999939, ..., 23.29700089,
         23.1590004 , 23.00300026]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-3.02292, lon=-60.05502)
print(maggia_points)

[(-3.5, -60.5, 153, 99), (-3.5, -60.0, 153, 100), (-3.0, -60.5, 154, 99), (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_points

[(-3.5, -60.5, 153, 99),
 (-3.5, -60.0, 153, 100),
 (-3.0, -60.5, 154, 99),
 (-3.0, -60.0, 154, 100)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -3.02292
target_lon = -60.05502

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.5°,  -60.5°) - Indexes: [153, 99] - TEC: 101.5
   P2: (  -3.5°,  -60.0°) - Indexes: [153, 100] - TEC: 100.7
   P3: (  -3.0°,  -60.5°) - Indexes: [154, 99] - TEC: 101.5
   P4: (  -3.0°,  -60.0°) - Indexes: [154, 100] - TEC: 100.3

2. TARGET POINT: (-3.02292°, -60.05502°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.5° to   -3.0° (range:  0.5°)
   Longitude:  -60.5° to  -60.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.5°,  -60.5°) = 101.5
   f_01 (lat_min, lon_max) = (  -3.5°,  -60.0°) = 100.7
   f_10 (lat_max, lon_min) = (  -3.0°,  -60.5°) = 101.5
   f_11 (lat_max, lon_max) = (  -3.0°,  -60.0°) = 100.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-60.05502 - ( -60.5)) / ( -60.0 - ( -60.5))
   t_x = 0.44498 /  0.5 = 0.889960

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-3.02292 - (  -3.5)) / (  -3.0 - (  -3.5))
   t_y = 0.47708 /  0.5 = 0.954160

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.889960) * (1 - 0.954160) = 0.005044
   w_01 = t_x * (1 - t_y)       = 0.889960 * (1 - 0.954160)       = 0.040796
   w_10 = (1 - t_x) * t_y       = (1 - 0.889960) * 0.954160       = 0.104996
   w_11 = t_x * t_y             = 0.889960 * 0.954160             = 0.849164
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.005044*101.5 + 0.040796*100.7 + 0.104996*101.5 + 0.849164*100.3
   Value =   0.5120 +   4.1094 +  10.6578 +  85.2119
   Value = 100.491161

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 89.00% of the way from -60.5° to -60.0°
   In Y direction (latitude):  95.42% of the way from -3.5° to -3.0°

============================================================
FINAL RESULT: TEC = 100.4912
============================================================