# Gopi TEC São Luís analysis - 09/27/2024

In [ ]:
#Download Gopi_TEC_SALU_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [ ]:
%pwd

'/content'

In [ ]:
!ls

Gopi_TEC_SALU_09_27_2024_and_Dec_2024.zip  sample_data

In [ ]:
!unzip 'Gopi_TEC_SALU_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_SALU_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: salu271-2024-09-27.Bias
  inflating: salu271-2024-09-27.Cmn
  inflating: salu271-2024-09-27.Std
  inflating: salu271-2024-09-27_page0.png
  inflating: salu271-2024-09-27-wbias.png
  inflating: salu336-2024-12-01.Bias
  inflating: salu336-2024-12-01.Cmn
  inflating: salu336-2024-12-01.Std
  inflating: salu336-2024-12-01_page0.png
  inflating: salu336-2024-12-01-wbias.png
  inflating: salu337-2024-12-02.Bias
  inflating: salu337-2024-12-02.Cmn
  inflating: salu337-2024-12-02.Std
  inflating: salu337-2024-12-02_page0.png
  inflating: salu337-2024-12-02-wbias.png
  inflating: salu338-2024-12-03.Bias
  inflating: salu338-2024-12-03.Cmn
  inflating: salu338-2024-12-03.Std
  inflating: salu338-2024-12-03_page0.png
  inflating: salu338-2024-12-03-wbias.png
  inflating: salu339-2024-12-04.Bias
  inflating: salu339-2024-12-04.Cmn
  inflating: salu339-2024-12-04.Std
  inflating: salu339-2024-12-04_page0.png
  inflating: salu339-2024-12-04-wbias.png
  inflating: salu340-2024-12-05.Bias
  inflating: salu340-2024-12-05.Cmn
  inflating: salu340-2024-12-05.Std
  inflating: salu340-2024-12-05_page0.png
  inflating: salu340-2024-12-05-wbias.png
  inflating: salu341-2024-12-06.Bias
  inflating: salu341-2024-12-06.Cmn
  inflating: salu341-2024-12-06.Std
  inflating: salu341-2024-12-06_page0.png
  inflating: salu341-2024-12-06-wbias.png
  inflating: salu342-2024-12-07.Bias
  inflating: salu342-2024-12-07.Cmn
  inflating: salu342-2024-12-07.Std
  inflating: salu342-2024-12-07_page0.png
  inflating: salu342-2024-12-07-wbias.png
  inflating: salu343-2024-12-08.Bias
  inflating: salu343-2024-12-08.Cmn
  inflating: salu343-2024-12-08.Std
  inflating: salu343-2024-12-08_page0.png
  inflating: salu343-2024-12-08-wbias.png
  inflating: salu344-2024-12-09.Bias
  inflating: salu344-2024-12-09.Cmn
  inflating: salu344-2024-12-09.Std
  inflating: salu344-2024-12-09_page0.png
  inflating: salu344-2024-12-09-wbias.png
  inflating: salu345-2024-12-10.Bias
  inflating: salu345-2024-12-10.Cmn
  inflating: salu345-2024-12-10.Std
  inflating: salu345-2024-12-10_page0.png
  inflating: salu345-2024-12-10-wbias.png
  inflating: salu346-2024-12-11.Bias
  inflating: salu346-2024-12-11.Cmn
  inflating: salu346-2024-12-11.Std
  inflating: salu346-2024-12-11_page0.png
  inflating: salu346-2024-12-11-wbias.png
  inflating: salu347-2024-12-12.Bias
  inflating: salu347-2024-12-12.Cmn
  inflating: salu347-2024-12-12.Std
  inflating: salu347-2024-12-12_page0.png
  inflating: salu347-2024-12-12-wbias.png
  inflating: salu348-2024-12-13.Bias
  inflating: salu348-2024-12-13.Cmn
  inflating: salu348-2024-12-13.Std
  inflating: salu348-2024-12-13_page0.png
  inflating: salu348-2024-12-13-wbias.png
  inflating: salu349-2024-12-14.Bias
  inflating: salu349-2024-12-14.Cmn
  inflating: salu349-2024-12-14.Std
  inflating: salu349-2024-12-14_page0.png
  inflating: salu349-2024-12-14-wbias.png
  inflating: salu350-2024-12-15.Bias
  inflating: salu350-2024-12-15.Cmn
  inflating: salu350-2024-12-15.Std
  inflating: salu350-2024-12-15_page0.png
  inflating: salu350-2024-12-15-wbias.png
  inflating: salu351-2024-12-16.Bias
  inflating: salu351-2024-12-16.Cmn
  inflating: salu351-2024-12-16.Std
  inflating: salu351-2024-12-16_page0.png
  inflating: salu351-2024-12-16-wbias.png
  inflating: salu352-2024-12-17.Bias
  inflating: salu352-2024-12-17.Cmn
  inflating: salu352-2024-12-17.Std
  inflating: salu352-2024-12-17_page0.png
  inflating: salu352-2024-12-17-wbias.png
  inflating: salu353-2024-12-18.Bias
  inflating: salu353-2024-12-18.Cmn
  inflating: salu353-2024-12-18.Std
  inflating: salu353-2024-12-18_page0.png
  inflating: salu353-2024-12-18-wbias.png
  inflating: salu354-2024-12-19.Bias
  inflating: salu354-2024-12-19.Cmn
  inflating: salu354-2024-12-19.Std
  inflating: salu354-2024-12-19_page0.png
  inflating: salu354-2024-12-19-wbias.png
  inflating: salu355-2024-12-20.Bias
  inflating: salu355-2024-12-20.Cmn
  inflating: salu355-2024-12-20.Std
  inflating: salu355-2024-12-20_page0.png
  inflating: salu355-2024-12-20-wbias.png
  inflating: salu356-2024-12-21.Bias
  inflating: salu356-2024-12-21.Cmn
  inflating: salu356-2024-12-21.Std
  inflating: salu356-2024-12-21_page0.png
  inflating: salu356-2024-12-21-wbias.png
  inflating: salu357-2024-12-22.Bias
  inflating: salu357-2024-12-22.Cmn
  inflating: salu357-2024-12-22.Std
  inflating: salu357-2024-12-22_page0.png
  inflating: salu357-2024-12-22-wbias.png
  inflating: salu358-2024-12-23.Bias
  inflating: salu358-2024-12-23.Cmn
  inflating: salu358-2024-12-23.Std
  inflating: salu358-2024-12-23_page0.png
  inflating: salu358-2024-12-23-wbias.png
  inflating: salu359-2024-12-24.Bias
  inflating: salu359-2024-12-24.Cmn
  inflating: salu359-2024-12-24.Std
  inflating: salu359-2024-12-24_page0.png
  inflating: salu359-2024-12-24-wbias.png
  inflating: salu360-2024-12-25.Bias
  inflating: salu360-2024-12-25.Cmn
  inflating: salu360-2024-12-25.Std
  inflating: salu360-2024-12-25_page0.png
  inflating: salu360-2024-12-25-wbias.png
  inflating: salu361-2024-12-26.Bias
  inflating: salu361-2024-12-26.Cmn
  inflating: salu361-2024-12-26.Std
  inflating: salu361-2024-12-26_page0.png
  inflating: salu361-2024-12-26-wbias.png
  inflating: salu362-2024-12-27.Bias
  inflating: salu362-2024-12-27.Cmn
  inflating: salu362-2024-12-27.Std
  inflating: salu362-2024-12-27_page0.png
  inflating: salu362-2024-12-27-wbias.png
  inflating: salu363-2024-12-28.Bias
  inflating: salu363-2024-12-28.Cmn
  inflating: salu363-2024-12-28.Std
  inflating: salu363-2024-12-28_page0.png
  inflating: salu363-2024-12-28-wbias.png
  inflating: salu364-2024-12-29.Bias
  inflating: salu364-2024-12-29.Cmn
  inflating: salu364-2024-12-29.Std
  inflating: salu364-2024-12-29_page0.png
  inflating: salu364-2024-12-29-wbias.png
  inflating: salu365-2024-12-30.Bias
  inflating: salu365-2024-12-30.Cmn
  inflating: salu365-2024-12-30.Std
  inflating: salu365-2024-12-30_page0.png
  inflating: salu365-2024-12-30-wbias.png
  inflating: salu366-2024-12-31.Bias
  inflating: salu366-2024-12-31.Cmn
  inflating: salu366-2024-12-31.Std
  inflating: salu366-2024-12-31_page0.png
  inflating: salu366-2024-12-31-wbias.png

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

df = pd.read_csv('salu271-2024-09-27.Std', sep='\s+', header=None)

df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

base_date = datetime(2024, 9, 27)

def decimal_to_time(decimal_hours):
    hours = int(decimal_hours)
    minutes = int((decimal_hours - hours) * 60)
    seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
    return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

print(df)

df.to_pickle('salu271-2024-09-27.pkl')

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-716261192.py:5: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('salu271-2024-09-27.Std', sep='\s+', header=None)

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  23.47     8.24     -2.59
1    2024-09-27 00:01:01  23.47     8.01     -2.59
2    2024-09-27 00:01:58  23.48     8.31     -2.59
3    2024-09-27 00:03:00  23.49     8.24     -2.59
4    2024-09-27 00:04:01  23.49     8.38     -2.59
...                  ...    ...      ...       ...
1435 2024-09-27 23:55:01  13.95     7.76     -2.59
1436 2024-09-27 23:55:58  13.94     8.06     -2.59
1437 2024-09-27 23:56:59  13.94     8.35     -2.59
1438 2024-09-27 23:58:01  13.95     8.49     -2.59
1439 2024-09-27 23:58:58  13.96     9.44     -2.59

[1440 rows x 4 columns]

In [ ]:
df

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  23.47     8.24     -2.59
1    2024-09-27 00:01:01  23.47     8.01     -2.59
2    2024-09-27 00:01:58  23.48     8.31     -2.59
3    2024-09-27 00:03:00  23.49     8.24     -2.59
4    2024-09-27 00:04:01  23.49     8.38     -2.59
...                  ...    ...      ...       ...
1435 2024-09-27 23:55:01  13.95     7.76     -2.59
1436 2024-09-27 23:55:58  13.94     8.06     -2.59
1437 2024-09-27 23:56:59  13.94     8.35     -2.59
1438 2024-09-27 23:58:01  13.95     8.49     -2.59
1439 2024-09-27 23:58:58  13.96     9.44     -2.59

[1440 rows x 4 columns]

In [ ]:
import pandas as pd
from datetime import time
import numpy as np

df['DATETIME'] = pd.to_datetime(df['DATETIME'])

target_times = [
    time(0, 50),
    time(1, 0),
    time(1, 10)
]

def find_closest_time(df, target_time):

    df_times = df['DATETIME'].dt.time


    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second


    df_seconds = (df['DATETIME'].dt.hour * 3600 +
                  df['DATETIME'].dt.minute * 60 +
                  df['DATETIME'].dt.second)


    time_diff = np.abs(df_seconds - target_seconds)


    closest_idx = time_diff.idxmin()

    return df.loc[[closest_idx]]

df_filtered_list = []
for target_time in target_times:
    closest_row = find_closest_time(df, target_time)
    df_filtered_list.append(closest_row)

df_filtered = pd.concat(df_filtered_list, ignore_index=True)

df_filtered = df_filtered.sort_values('DATETIME').reset_index(drop=True)

print("DataFrame filtered for closest times to 00:50, 01:00 and 01:10:")
print(df_filtered)

print("\nDifference from target times:")
for i, target_time in enumerate(target_times):
    actual_time = df_filtered.iloc[i]['DATETIME'].time()
    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second
    actual_seconds = actual_time.hour * 3600 + actual_time.minute * 60 + actual_time.second
    diff_seconds = abs(actual_seconds - target_seconds)
    print(f"Target: {target_time} | Actual: {actual_time} | Difference: {diff_seconds} seconds")

DataFrame filtered for closest times to 00:50, 01:00 and 01:10:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-09-27 00:49:58  21.98     6.73     -2.59
1 2024-09-27 01:00:00  20.75     6.62     -2.59
2 2024-09-27 01:10:01  19.45     7.05     -2.59

Difference from target times:
Target: 00:50:00 | Actual: 00:49:58 | Difference: 2 seconds
Target: 01:00:00 | Actual: 01:00:00 | Difference: 0 seconds
Target: 01:10:00 | Actual: 01:10:01 | Difference: 1 seconds

In [ ]:
reference_time = pd.Timestamp('2024-09-27 00:50:00')
wide_window = timedelta(minutes=5)
df_proximos = df[(df['DATETIME'] >= reference_time - wide_window) &
                 (df['DATETIME'] <= reference_time + wide_window)]
print("Records close to 00:50:")
print(df_proximos[['DATETIME', 'TEC']])

Records close to 00:50:
              DATETIME    TEC
45 2024-09-27 00:45:00  22.48
46 2024-09-27 00:46:01  22.39
47 2024-09-27 00:46:58  22.29
48 2024-09-27 00:48:00  22.19
49 2024-09-27 00:49:01  22.09
50 2024-09-27 00:49:58  21.98
51 2024-09-27 00:51:00  21.87
52 2024-09-27 00:52:01  21.75
53 2024-09-27 00:52:58  21.64
54 2024-09-27 00:54:00  21.52

In [ ]:
print(df.iloc[[50, 60, 70]][['DATETIME', 'TEC']])

              DATETIME    TEC
50 2024-09-27 00:49:58  21.98
60 2024-09-27 01:00:00  20.75
70 2024-09-27 01:10:01  19.45

In [ ]:
df.to_pickle('naus271-2024-09-27_selected_0050_to_0110.pkl')

# TEC maps analysis

In [ ]:
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

## EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
embrace_tec = Embrace()
embrace_points = embrace_tec.find_nearest_points(lat=-2.59346, lon=-44.21248)

In [ ]:
embrace_points

[(-4, -45.0, 28, 18),
 (-4, -42.5, 28, 19),
 (-2, -45.0, 29, 18),
 (-2, -42.5, 29, 19)]

In [ ]:
data = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{data} {time}' for time in times]

result = df_embrace_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(3, 41, 25)

### 00:50

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -2.59346
target_lon = -44.21248

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -45.0°) - Indexes: [28, 18] - TEC:  57.0
   P2: (  -4.0°,  -42.5°) - Indexes: [28, 19] - TEC:  48.0
   P3: (  -2.0°,  -45.0°) - Indexes: [29, 18] - TEC:  28.0
   P4: (  -2.0°,  -42.5°) - Indexes: [29, 19] - TEC:  44.0

2. TARGET POINT: (-2.59346°, -44.21248°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -45.0° to  -42.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -45.0°) =  57.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -42.5°) =  48.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -45.0°) =  28.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -42.5°) =  44.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-44.21 - ( -45.0)) / ( -42.5 - ( -45.0))
   t_x =   0.79 /  2.5 = 0.315008

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -2.59 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y =   1.41 /  2.0 = 0.703270

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.315008) * (1 - 0.703270) = 0.203258
   w_01 = t_x * (1 - t_y)       = 0.315008 * (1 - 0.703270)       = 0.093472
   w_10 = (1 - t_x) * t_y       = (1 - 0.315008) * 0.703270       = 0.481734
   w_11 = t_x * t_y             = 0.315008 * 0.703270             = 0.221536
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.203258* 57.0 + 0.093472* 48.0 + 0.481734* 28.0 + 0.221536* 44.0
   Value =  11.5857 +   4.4867 +  13.4886 +   9.7476
   Value = 39.308490

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 31.50% of the way from -45.0° to -42.5°
   In Y direction (latitude):  70.33% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 39.3085
============================================================

### 01:00

In [ ]:
embrace_tec.tec_map = np_embrace_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -2.59346
target_lon = -44.21248

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -45.0°) - Indexes: [28, 18] - TEC:  42.0
   P2: (  -4.0°,  -42.5°) - Indexes: [28, 19] - TEC:  52.0
   P3: (  -2.0°,  -45.0°) - Indexes: [29, 18] - TEC:  38.0
   P4: (  -2.0°,  -42.5°) - Indexes: [29, 19] - TEC:  43.0

2. TARGET POINT: (-2.59346°, -44.21248°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -45.0° to  -42.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -45.0°) =  42.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -42.5°) =  52.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -45.0°) =  38.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -42.5°) =  43.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-44.21 - ( -45.0)) / ( -42.5 - ( -45.0))
   t_x =   0.79 /  2.5 = 0.315008

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -2.59 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y =   1.41 /  2.0 = 0.703270

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.315008) * (1 - 0.703270) = 0.203258
   w_01 = t_x * (1 - t_y)       = 0.315008 * (1 - 0.703270)       = 0.093472
   w_10 = (1 - t_x) * t_y       = (1 - 0.315008) * 0.703270       = 0.481734
   w_11 = t_x * t_y             = 0.315008 * 0.703270             = 0.221536
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.203258* 42.0 + 0.093472* 52.0 + 0.481734* 38.0 + 0.221536* 43.0
   Value =   8.5368 +   4.8606 +  18.3059 +   9.5260
   Value = 41.229322

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 31.50% of the way from -45.0° to -42.5°
   In Y direction (latitude):  70.33% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 41.2293
============================================================

### 01:10

In [ ]:
embrace_tec.tec_map = np_embrace_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -2.59346
target_lon = -44.21248

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -4.0°,  -45.0°) - Indexes: [28, 18] - TEC:  20.0
   P2: (  -4.0°,  -42.5°) - Indexes: [28, 19] - TEC:  57.0
   P3: (  -2.0°,  -45.0°) - Indexes: [29, 18] - TEC:  33.0
   P4: (  -2.0°,  -42.5°) - Indexes: [29, 19] - TEC:  42.0

2. TARGET POINT: (-2.59346°, -44.21248°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -4.0° to   -2.0° (range:  2.0°)
   Longitude:  -45.0° to  -42.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -4.0°,  -45.0°) =  20.0
   f_01 (lat_min, lon_max) = (  -4.0°,  -42.5°) =  57.0
   f_10 (lat_max, lon_min) = (  -2.0°,  -45.0°) =  33.0
   f_11 (lat_max, lon_max) = (  -2.0°,  -42.5°) =  42.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-44.21 - ( -45.0)) / ( -42.5 - ( -45.0))
   t_x =   0.79 /  2.5 = 0.315008

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -2.59 - (  -4.0)) / (  -2.0 - (  -4.0))
   t_y =   1.41 /  2.0 = 0.703270

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.315008) * (1 - 0.703270) = 0.203258
   w_01 = t_x * (1 - t_y)       = 0.315008 * (1 - 0.703270)       = 0.093472
   w_10 = (1 - t_x) * t_y       = (1 - 0.315008) * 0.703270       = 0.481734
   w_11 = t_x * t_y             = 0.315008 * 0.703270             = 0.221536
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.203258* 20.0 + 0.093472* 57.0 + 0.481734* 33.0 + 0.221536* 42.0
   Value =   4.0652 +   5.3279 +  15.8972 +   9.3045
   Value = 34.594807

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 31.50% of the way from -45.0° to -42.5°
   In Y direction (latitude):  70.33% of the way from -4° to -2°

============================================================
FINAL RESULT: TEC = 34.5948
============================================================

## MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024['DATETIME'] = pd.to_datetime(df_maggia_maps_2024['DATETIME'])
df_maggia_maps_2024 = df_maggia_maps_2024.set_index('DATETIME')

In [ ]:
df_maggia_maps_2024.columns

Index(['TECMAP'], dtype='object')

In [ ]:
class Maggia(TecMap):

    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
maggia_tec = Maggia()
maggia_points = maggia_tec.find_nearest_points(lat=-2.59346, lon=-44.21248)

In [ ]:
maggia_points

[(-3.0, -44.5, 154, 131),
 (-3.0, -44.0, 154, 132),
 (-2.5, -44.5, 155, 131),
 (-2.5, -44.0, 155, 132)]

In [ ]:
data = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{data} {hourrio}' for hourrio in times]

result = df_maggia_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.62400055, 48.20500183, 47.78499985, ..., 19.22900009,
         18.24799919, 16.43799973],
        [48.70800018, 48.36100006, 48.0019989 , ..., 18.61000061,
         17.57699966, 16.23500061],
        [48.7120018 , 48.42399979, 48.11700058, ..., 17.99799919,
         16.95499992, 16.04000092]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [43.38299942, 43.10300064, 43.09799957, ..., 19.18000031,
         18.25300026, 17.1609993 ],
        [43.85400009, 43.58499908, 43.34700012, ..., 18.40399933,
         17.62000084, 16.44000053],
        [44.19599915, 43.94599915, 43.70500183, ..., 17.70899963,
         16.94099998, 15.69099998]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.6230011 , 41.29999924, 41.13800049, ..., 18.74399948,
         18.67399979, 18.62999916],
        [42.11100006, 41.79499817, 41.5340004 , ..., 18.92099953,
         18.80699921, 17.86199951],
        [42.46699905, 42.18199921, 41.9280014 , ..., 18.2670002 ,
         17.5340004 , 16.79299927]]])

In [ ]:
np_maggia_maps.shape

(3, 241, 221)

### 00:50

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -2.59346
target_lon = -44.21248

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.0°,  -44.5°) - Indexes: [154, 131] - TEC:  40.5
   P2: (  -3.0°,  -44.0°) - Indexes: [154, 132] - TEC:  39.6
   P3: (  -2.5°,  -44.5°) - Indexes: [155, 131] - TEC:  38.9
   P4: (  -2.5°,  -44.0°) - Indexes: [155, 132] - TEC:  38.0

2. TARGET POINT: (-2.59346°, -44.21248°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.0° to   -2.5° (range:  0.5°)
   Longitude:  -44.5° to  -44.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.0°,  -44.5°) =  40.5
   f_01 (lat_min, lon_max) = (  -3.0°,  -44.0°) =  39.6
   f_10 (lat_max, lon_min) = (  -2.5°,  -44.5°) =  38.9
   f_11 (lat_max, lon_max) = (  -2.5°,  -44.0°) =  38.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-44.21 - ( -44.5)) / ( -44.0 - ( -44.5))
   t_x =   0.29 /  0.5 = 0.575040

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -2.59 - (  -3.0)) / (  -2.5 - (  -3.0))
   t_y =   0.41 /  0.5 = 0.813080

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.575040) * (1 - 0.813080) = 0.079434
   w_01 = t_x * (1 - t_y)       = 0.575040 * (1 - 0.813080)       = 0.107486
   w_10 = (1 - t_x) * t_y       = (1 - 0.575040) * 0.813080       = 0.345526
   w_11 = t_x * t_y             = 0.575040 * 0.813080             = 0.467554
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.079434* 40.5 + 0.107486* 39.6 + 0.345526* 38.9 + 0.467554* 38.0
   Value =   3.2139 +   4.2615 +  13.4361 +  17.7764
   Value = 38.687925

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.50% of the way from -44.5° to -44.0°
   In Y direction (latitude):  81.31% of the way from -3.0° to -2.5°

============================================================
FINAL RESULT: TEC = 38.6879
============================================================

### 01:00

In [ ]:
maggia_tec.tec_map = np_maggia_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -2.59346
target_lon = -44.21248

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.0°,  -44.5°) - Indexes: [154, 131] - TEC:  44.5
   P2: (  -3.0°,  -44.0°) - Indexes: [154, 132] - TEC:  47.4
   P3: (  -2.5°,  -44.5°) - Indexes: [155, 131] - TEC:  40.0
   P4: (  -2.5°,  -44.0°) - Indexes: [155, 132] - TEC:  42.4

2. TARGET POINT: (-2.59346°, -44.21248°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.0° to   -2.5° (range:  0.5°)
   Longitude:  -44.5° to  -44.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.0°,  -44.5°) =  44.5
   f_01 (lat_min, lon_max) = (  -3.0°,  -44.0°) =  47.4
   f_10 (lat_max, lon_min) = (  -2.5°,  -44.5°) =  40.0
   f_11 (lat_max, lon_max) = (  -2.5°,  -44.0°) =  42.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-44.21 - ( -44.5)) / ( -44.0 - ( -44.5))
   t_x =   0.29 /  0.5 = 0.575040

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -2.59 - (  -3.0)) / (  -2.5 - (  -3.0))
   t_y =   0.41 /  0.5 = 0.813080

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.575040) * (1 - 0.813080) = 0.079434
   w_01 = t_x * (1 - t_y)       = 0.575040 * (1 - 0.813080)       = 0.107486
   w_10 = (1 - t_x) * t_y       = (1 - 0.575040) * 0.813080       = 0.345526
   w_11 = t_x * t_y             = 0.575040 * 0.813080             = 0.467554
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.079434* 44.5 + 0.107486* 47.4 + 0.345526* 40.0 + 0.467554* 42.4
   Value =   3.5333 +   5.0901 +  13.8297 +  19.8014
   Value = 42.254470

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.50% of the way from -44.5° to -44.0°
   In Y direction (latitude):  81.31% of the way from -3.0° to -2.5°

============================================================
FINAL RESULT: TEC = 42.2545
============================================================

### 01:10

In [ ]:
maggia_tec.tec_map = np_maggia_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -2.59346
target_lon = -44.21248

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: (  -3.0°,  -44.5°) - Indexes: [154, 131] - TEC:  45.7
   P2: (  -3.0°,  -44.0°) - Indexes: [154, 132] - TEC:  49.9
   P3: (  -2.5°,  -44.5°) - Indexes: [155, 131] - TEC:  38.9
   P4: (  -2.5°,  -44.0°) - Indexes: [155, 132] - TEC:  45.1

2. TARGET POINT: (-2.59346°, -44.21248°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:    -3.0° to   -2.5° (range:  0.5°)
   Longitude:  -44.5° to  -44.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = (  -3.0°,  -44.5°) =  45.7
   f_01 (lat_min, lon_max) = (  -3.0°,  -44.0°) =  49.9
   f_10 (lat_max, lon_min) = (  -2.5°,  -44.5°) =  38.9
   f_11 (lat_max, lon_max) = (  -2.5°,  -44.0°) =  45.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-44.21 - ( -44.5)) / ( -44.0 - ( -44.5))
   t_x =   0.29 /  0.5 = 0.575040

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = ( -2.59 - (  -3.0)) / (  -2.5 - (  -3.0))
   t_y =   0.41 /  0.5 = 0.813080

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.575040) * (1 - 0.813080) = 0.079434
   w_01 = t_x * (1 - t_y)       = 0.575040 * (1 - 0.813080)       = 0.107486
   w_10 = (1 - t_x) * t_y       = (1 - 0.575040) * 0.813080       = 0.345526
   w_11 = t_x * t_y             = 0.575040 * 0.813080             = 0.467554
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.079434* 45.7 + 0.107486* 49.9 + 0.345526* 38.9 + 0.467554* 45.1
   Value =   3.6300 +   5.3586 +  13.4265 +  21.0890
   Value = 43.504054

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.50% of the way from -44.5° to -44.0°
   In Y direction (latitude):  81.31% of the way from -3.0° to -2.5°

============================================================
FINAL RESULT: TEC = 43.5041
============================================================