# Gopi TEC Porto Alegre analysis - 09/27/2024

In [ ]:
#Download Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [ ]:
%pwd

'/content'

In [ ]:
!ls

Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip  sample_data

In [ ]:
!unzip 'Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: poal271-2024-09-27.Bias
  inflating: poal271-2024-09-27.Cmn
  inflating: poal271-2024-09-27.Std
  inflating: poal271-2024-09-27_page0.png
  inflating: poal271-2024-09-27-wbias.png
  inflating: poal336-2024-12-01.Bias
  inflating: poal336-2024-12-01.Cmn
  inflating: poal336-2024-12-01.Std
  inflating: poal336-2024-12-01_page0.png
  inflating: poal336-2024-12-01-wbias.png
  inflating: poal337-2024-12-02.Bias
  inflating: poal337-2024-12-02.Cmn
  inflating: poal337-2024-12-02.Std
  inflating: poal337-2024-12-02_page0.png
  inflating: poal337-2024-12-02-wbias.png
  inflating: poal338-2024-12-03.Bias
  inflating: poal338-2024-12-03.Cmn
  inflating: poal338-2024-12-03.Std
  inflating: poal338-2024-12-03_page0.png
  inflating: poal338-2024-12-03-wbias.png
  inflating: poal339-2024-12-04.Bias
  inflating: poal339-2024-12-04.Cmn
  inflating: poal339-2024-12-04.Std
  inflating: poal339-2024-12-04_page0.png
  inflating: poal339-2024-12-04-wbias.png
  inflating: poal340-2024-12-05.Bias
  inflating: poal340-2024-12-05.Cmn
  inflating: poal340-2024-12-05.Std
  inflating: poal340-2024-12-05_page0.png
  inflating: poal340-2024-12-05-wbias.png
  inflating: poal341-2024-12-06.Bias
  inflating: poal341-2024-12-06.Cmn
  inflating: poal341-2024-12-06.Std
  inflating: poal341-2024-12-06_page0.png
  inflating: poal341-2024-12-06-wbias.png
  inflating: poal342-2024-12-07.Bias
  inflating: poal342-2024-12-07.Cmn
  inflating: poal342-2024-12-07.Std
  inflating: poal342-2024-12-07_page0.png
  inflating: poal342-2024-12-07-wbias.png
  inflating: poal343-2024-12-08.Bias
  inflating: poal343-2024-12-08.Cmn
  inflating: poal343-2024-12-08.Std
  inflating: poal343-2024-12-08_page0.png
  inflating: poal343-2024-12-08-wbias.png
  inflating: poal344-2024-12-09.Bias
  inflating: poal344-2024-12-09.Cmn
  inflating: poal344-2024-12-09.Std
  inflating: poal344-2024-12-09_page0.png
  inflating: poal344-2024-12-09-wbias.png
  inflating: poal345-2024-12-10.Bias
  inflating: poal345-2024-12-10.Cmn
  inflating: poal345-2024-12-10.Std
  inflating: poal345-2024-12-10_page0.png
  inflating: poal345-2024-12-10-wbias.png
  inflating: poal346-2024-12-11.Bias
  inflating: poal346-2024-12-11.Cmn
  inflating: poal346-2024-12-11.Std
  inflating: poal346-2024-12-11_page0.png
  inflating: poal346-2024-12-11-wbias.png
  inflating: poal347-2024-12-12.Bias
  inflating: poal347-2024-12-12.Cmn
  inflating: poal347-2024-12-12.Std
  inflating: poal347-2024-12-12_page0.png
  inflating: poal347-2024-12-12-wbias.png
  inflating: poal348-2024-12-13.Bias
  inflating: poal348-2024-12-13.Cmn
  inflating: poal348-2024-12-13.Std
  inflating: poal348-2024-12-13_page0.png
  inflating: poal348-2024-12-13-wbias.png
  inflating: poal349-2024-12-14.Bias
  inflating: poal349-2024-12-14.Cmn
  inflating: poal349-2024-12-14.Std
  inflating: poal349-2024-12-14_page0.png
  inflating: poal349-2024-12-14-wbias.png
  inflating: poal350-2024-12-15.Bias
  inflating: poal350-2024-12-15.Cmn
  inflating: poal350-2024-12-15.Std
  inflating: poal350-2024-12-15_page0.png
  inflating: poal350-2024-12-15-wbias.png
  inflating: poal351-2024-12-16.Bias
  inflating: poal351-2024-12-16.Cmn
  inflating: poal351-2024-12-16.Std
  inflating: poal351-2024-12-16_page0.png
  inflating: poal351-2024-12-16-wbias.png
  inflating: poal352-2024-12-17.Bias
  inflating: poal352-2024-12-17.Cmn
  inflating: poal352-2024-12-17.Std
  inflating: poal352-2024-12-17_page0.png
  inflating: poal352-2024-12-17-wbias.png
  inflating: poal353-2024-12-18.Bias
  inflating: poal353-2024-12-18.Cmn
  inflating: poal353-2024-12-18.Std
  inflating: poal353-2024-12-18_page0.png
  inflating: poal353-2024-12-18-wbias.png
  inflating: poal354-2024-12-19.Bias
  inflating: poal354-2024-12-19.Cmn
  inflating: poal354-2024-12-19.Std
  inflating: poal354-2024-12-19_page0.png
  inflating: poal354-2024-12-19-wbias.png
  inflating: poal355-2024-12-20.Bias
  inflating: poal355-2024-12-20.Cmn
  inflating: poal355-2024-12-20.Std
  inflating: poal355-2024-12-20_page0.png
  inflating: poal355-2024-12-20-wbias.png
  inflating: poal356-2024-12-21.Bias
  inflating: poal356-2024-12-21.Cmn
  inflating: poal356-2024-12-21.Std
  inflating: poal356-2024-12-21_page0.png
  inflating: poal356-2024-12-21-wbias.png
  inflating: poal357-2024-12-22.Bias
  inflating: poal357-2024-12-22.Cmn
  inflating: poal357-2024-12-22.Std
  inflating: poal357-2024-12-22_page0.png
  inflating: poal357-2024-12-22-wbias.png
  inflating: poal358-2024-12-23.Bias
  inflating: poal358-2024-12-23.Cmn
  inflating: poal358-2024-12-23.Std
  inflating: poal358-2024-12-23_page0.png
  inflating: poal358-2024-12-23-wbias.png
  inflating: poal359-2024-12-24.Bias
  inflating: poal359-2024-12-24.Cmn
  inflating: poal359-2024-12-24.Std
  inflating: poal359-2024-12-24_page0.png
  inflating: poal359-2024-12-24-wbias.png
  inflating: poal360-2024-12-25.Bias
  inflating: poal360-2024-12-25.Cmn
  inflating: poal360-2024-12-25.Std
  inflating: poal360-2024-12-25_page0.png
  inflating: poal360-2024-12-25-wbias.png
  inflating: poal361-2024-12-26.Bias
  inflating: poal361-2024-12-26.Cmn
  inflating: poal361-2024-12-26.Std
  inflating: poal361-2024-12-26_page0.png
  inflating: poal361-2024-12-26-wbias.png
  inflating: poal362-2024-12-27.Bias
  inflating: poal362-2024-12-27.Cmn
  inflating: poal362-2024-12-27.Std
  inflating: poal362-2024-12-27_page0.png
  inflating: poal362-2024-12-27-wbias.png
  inflating: poal363-2024-12-28.Bias
  inflating: poal363-2024-12-28.Cmn
  inflating: poal363-2024-12-28.Std
  inflating: poal363-2024-12-28_page0.png
  inflating: poal363-2024-12-28-wbias.png
  inflating: poal364-2024-12-29.Bias
  inflating: poal364-2024-12-29.Cmn
  inflating: poal364-2024-12-29.Std
  inflating: poal364-2024-12-29_page0.png
  inflating: poal364-2024-12-29-wbias.png
  inflating: poal365-2024-12-30.Bias
  inflating: poal365-2024-12-30.Cmn
  inflating: poal365-2024-12-30.Std
  inflating: poal365-2024-12-30_page0.png
  inflating: poal365-2024-12-30-wbias.png
  inflating: poal366-2024-12-31.Bias
  inflating: poal366-2024-12-31.Cmn
  inflating: poal366-2024-12-31.Std
  inflating: poal366-2024-12-31_page0.png
  inflating: poal366-2024-12-31-wbias.png

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

df = pd.read_csv('poal271-2024-09-27.Std', sep='\s+', header=None)

df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

base_date = datetime(2024, 9, 27)

def decimal_to_time(decimal_hours):
    hours = int(decimal_hours)
    minutes = int((decimal_hours - hours) * 60)
    seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
    return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

print(df)

df.to_pickle('poal271-2024-09-27.pkl')

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2581092949.py:5: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('poal271-2024-09-27.Std', sep='\s+', header=None)

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  12.15     8.27    -30.07
1    2024-09-27 00:01:01  12.17     8.59    -30.07
2    2024-09-27 00:01:58  12.18     3.27    -30.07
3    2024-09-27 00:03:00  12.20     3.10    -30.07
4    2024-09-27 00:04:01  12.22     3.02    -30.07
...                  ...    ...      ...       ...
1435 2024-09-27 23:55:01  23.31    20.48    -30.07
1436 2024-09-27 23:55:58  23.24    20.71    -30.07
1437 2024-09-27 23:56:59  23.17    20.76    -30.07
1438 2024-09-27 23:58:01  23.11    21.45    -30.07
1439 2024-09-27 23:58:58  23.06    22.45    -30.07

[1440 rows x 4 columns]

In [ ]:
df

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  12.15     8.27    -30.07
1    2024-09-27 00:01:01  12.17     8.59    -30.07
2    2024-09-27 00:01:58  12.18     3.27    -30.07
3    2024-09-27 00:03:00  12.20     3.10    -30.07
4    2024-09-27 00:04:01  12.22     3.02    -30.07
...                  ...    ...      ...       ...
1435 2024-09-27 23:55:01  23.31    20.48    -30.07
1436 2024-09-27 23:55:58  23.24    20.71    -30.07
1437 2024-09-27 23:56:59  23.17    20.76    -30.07
1438 2024-09-27 23:58:01  23.11    21.45    -30.07
1439 2024-09-27 23:58:58  23.06    22.45    -30.07

[1440 rows x 4 columns]

In [ ]:
import pandas as pd
from datetime import time
import numpy as np

df['DATETIME'] = pd.to_datetime(df['DATETIME'])

target_times = [
    time(0, 50),
    time(1, 0),
    time(1, 10)
]

def find_closest_time(df, target_time):

    df_times = df['DATETIME'].dt.time


    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second


    df_seconds = (df['DATETIME'].dt.hour * 3600 +
                  df['DATETIME'].dt.minute * 60 +
                  df['DATETIME'].dt.second)


    time_diff = np.abs(df_seconds - target_seconds)


    closest_idx = time_diff.idxmin()

    return df.loc[[closest_idx]]

df_filtered_list = []
for target_time in target_times:
    closest_row = find_closest_time(df, target_time)
    df_filtered_list.append(closest_row)

df_filtered = pd.concat(df_filtered_list, ignore_index=True)

df_filtered = df_filtered.sort_values('DATETIME').reset_index(drop=True)

print("DataFrame filtered for closest times to 00:50, 01:00 and 01:10:")
print(df_filtered)

print("\nDifference from target times:")
for i, target_time in enumerate(target_times):
    actual_time = df_filtered.iloc[i]['DATETIME'].time()
    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second
    actual_seconds = actual_time.hour * 3600 + actual_time.minute * 60 + actual_time.second
    diff_seconds = abs(actual_seconds - target_seconds)
    print(f"Target: {target_time} | Actual: {actual_time} | Difference: {diff_seconds} seconds")

DataFrame filtered for closest times to 00:50, 01:00 and 01:10:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-09-27 00:49:58  14.77     4.29    -30.07
1 2024-09-27 01:00:00  15.80     3.82    -30.07
2 2024-09-27 01:10:01  16.92     3.35    -30.07

Difference from target times:
Target: 00:50:00 | Actual: 00:49:58 | Difference: 2 seconds
Target: 01:00:00 | Actual: 01:00:00 | Difference: 0 seconds
Target: 01:10:00 | Actual: 01:10:01 | Difference: 1 seconds

In [ ]:
reference_time = pd.Timestamp('2024-09-27 00:50:00')
wide_window = timedelta(minutes=5)
df_proximos = df[(df['DATETIME'] >= reference_time - wide_window) &
                 (df['DATETIME'] <= reference_time + wide_window)]
print("Records close to 00:50:")
print(df_proximos[['DATETIME', 'TEC']])

Records close to 00:50:
              DATETIME    TEC
45 2024-09-27 00:45:00  14.32
46 2024-09-27 00:46:01  14.41
47 2024-09-27 00:46:58  14.50
48 2024-09-27 00:48:00  14.59
49 2024-09-27 00:49:01  14.68
50 2024-09-27 00:49:58  14.77
51 2024-09-27 00:51:00  14.87
52 2024-09-27 00:52:01  14.97
53 2024-09-27 00:52:58  15.06
54 2024-09-27 00:54:00  15.17

In [ ]:
print(df.iloc[[50, 60, 70]][['DATETIME', 'TEC']])

              DATETIME    TEC
50 2024-09-27 00:49:58  14.77
60 2024-09-27 01:00:00  15.80
70 2024-09-27 01:10:01  16.92

In [ ]:
df.to_pickle('naus271-2024-09-27_selected_0050_to_0110.pkl')

# TEC maps analysis

In [ ]:
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

## EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
embrace_tec = Embrace()
embrace_points = embrace_tec.find_nearest_points(lat=-30.07404, lon=-51.11976)

In [ ]:
embrace_points

[(-32, -52.5, 14, 15),
 (-32, -50.0, 14, 16),
 (-30, -52.5, 15, 15),
 (-30, -50.0, 15, 16)]

In [ ]:
data = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{data} {time}' for time in times]

result = df_embrace_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(3, 41, 25)

### 00:50

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  34.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  34.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  35.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  33.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  34.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  34.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  35.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  33.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.12 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x =   1.38 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y =   1.93 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 34.0 + 0.020439* 34.0 + 0.431323* 35.0 + 0.531657* 33.0
   Value =   0.5638 +   0.6949 +  15.0963 +  17.5447
   Value = 33.899665

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 33.8997
============================================================

### 01:00

In [ ]:
embrace_tec.tec_map = np_embrace_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  37.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  35.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  34.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  32.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  37.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  35.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  34.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  32.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.12 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x =   1.38 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y =   1.93 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 37.0 + 0.020439* 35.0 + 0.431323* 34.0 + 0.531657* 32.0
   Value =   0.6135 +   0.7154 +  14.6650 +  17.0130
   Value = 33.006868

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 33.0069
============================================================

### 01:10

In [ ]:
embrace_tec.tec_map = np_embrace_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  36.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  34.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  33.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  35.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  36.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  34.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  33.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  35.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.12 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x =   1.38 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y =   1.93 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 36.0 + 0.020439* 34.0 + 0.431323* 33.0 + 0.531657* 35.0
   Value =   0.5969 +   0.6949 +  14.2336 +  18.6080
   Value = 34.133498

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 34.1335
============================================================

## MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024['DATETIME'] = pd.to_datetime(df_maggia_maps_2024['DATETIME'])
df_maggia_maps_2024 = df_maggia_maps_2024.set_index('DATETIME')

In [ ]:
df_maggia_maps_2024.columns

Index(['TECMAP'], dtype='object')

In [ ]:
class Maggia(TecMap):

    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
maggia_tec = Maggia()
maggia_points = maggia_tec.find_nearest_points(lat=-30.07404, lon=-51.11976)

In [ ]:
maggia_points

[(-30.5, -51.5, 99, 117),
 (-30.5, -51.0, 99, 118),
 (-30.0, -51.5, 100, 117),
 (-30.0, -51.0, 100, 118)]

In [ ]:
data = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{data} {hourrio}' for hourrio in times]

result = df_maggia_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.62400055, 48.20500183, 47.78499985, ..., 19.22900009,
         18.24799919, 16.43799973],
        [48.70800018, 48.36100006, 48.0019989 , ..., 18.61000061,
         17.57699966, 16.23500061],
        [48.7120018 , 48.42399979, 48.11700058, ..., 17.99799919,
         16.95499992, 16.04000092]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [43.38299942, 43.10300064, 43.09799957, ..., 19.18000031,
         18.25300026, 17.1609993 ],
        [43.85400009, 43.58499908, 43.34700012, ..., 18.40399933,
         17.62000084, 16.44000053],
        [44.19599915, 43.94599915, 43.70500183, ..., 17.70899963,
         16.94099998, 15.69099998]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.6230011 , 41.29999924, 41.13800049, ..., 18.74399948,
         18.67399979, 18.62999916],
        [42.11100006, 41.79499817, 41.5340004 , ..., 18.92099953,
         18.80699921, 17.86199951],
        [42.46699905, 42.18199921, 41.9280014 , ..., 18.2670002 ,
         17.5340004 , 16.79299927]]])

In [ ]:
np_maggia_maps.shape

(3, 241, 221)

### 00:50

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  26.5
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  25.2
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  29.5
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  30.9

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  26.5
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  25.2
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  29.5
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  30.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.12 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x =   0.38 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y =   0.43 /  0.5 = 0.851920
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 26.5 + 0.112612* 25.2 + 0.204052* 29.5 + 0.647868* 30.9
   Value =   0.9407 +   2.8388 +   6.0179 +  20.0023
   Value = 29.799662

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 29.7997
============================================================

### 01:00

In [ ]:
maggia_tec.tec_map = np_maggia_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  30.3
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  24.5
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  29.3
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  27.8

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  30.3
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  24.5
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  29.3
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  27.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.12 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x =   0.38 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y =   0.43 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 30.3 + 0.112612* 24.5 + 0.204052* 29.3 + 0.647868* 27.8
   Value =   1.0732 +   2.7579 +   5.9836 +  18.0412
   Value = 27.855896

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 27.8559
============================================================

### 01:10

In [ ]:
maggia_tec.tec_map = np_maggia_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  22.8
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  27.5
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  28.1
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  26.6

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  22.8
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  27.5
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  28.1
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  26.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.12 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x =   0.38 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y =   0.43 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 22.8 + 0.112612* 27.5 + 0.204052* 28.1 + 0.647868* 26.6
   Value =   0.8090 +   3.0949 +   5.7239 +  17.2275
   Value = 26.855260

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 26.8553
============================================================