# Gopi TEC Cuiabá analysis - 09/27/2024

In [ ]:
#Download Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [ ]:
%pwd

'/content'

In [ ]:
!ls

Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip  sample_data

In [ ]:
!unzip 'Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: cuib271-2024-09-27.Std
  inflating: cuib336-2024-12-01.Std
  inflating: cuib337-2024-12-02.Std
  inflating: cuib338-2024-12-03.Std
  inflating: cuib339-2024-12-04.Std
  inflating: cuib340-2024-12-05.Std
  inflating: cuib341-2024-12-06.Std
  inflating: cuib342-2024-12-07.Std
  inflating: cuib343-2024-12-08.Std
  inflating: cuib344-2024-12-09.Std
  inflating: cuib345-2024-12-10.Std
  inflating: cuib346-2024-12-11.Std
  inflating: cuib347-2024-12-12.Std
  inflating: cuib348-2024-12-13.Std
  inflating: cuib349-2024-12-14.Std
  inflating: cuib350-2024-12-15.Std
  inflating: cuib351-2024-12-16.Std
  inflating: cuib352-2024-12-17.Std
  inflating: cuib353-2024-12-18.Std
  inflating: cuib354-2024-12-19.Std
  inflating: cuib355-2024-12-20.Std
  inflating: cuib356-2024-12-21.Std
  inflating: cuib357-2024-12-22.Std
  inflating: cuib358-2024-12-23.Std
  inflating: cuib359-2024-12-24.Std
  inflating: cuib360-2024-12-25.Std
  inflating: cuib361-2024-12-26.Std
  inflating: cuib362-2024-12-27.Std
  inflating: cuib363-2024-12-28.Std
  inflating: cuib364-2024-12-29.Std
  inflating: cuib365-2024-12-30.Std
  inflating: cuib366-2024-12-31.Std
  inflating: cuib271-2024-09-27_page0.png
  inflating: cuib271-2024-09-27-wbias.png
  inflating: cuib336-2024-12-01_page0.png
  inflating: cuib336-2024-12-01-wbias.png
  inflating: cuib337-2024-12-02_page0.png
  inflating: cuib337-2024-12-02-wbias.png
  inflating: cuib338-2024-12-03_page0.png
  inflating: cuib338-2024-12-03-wbias.png
  inflating: cuib339-2024-12-04_page0.png
  inflating: cuib339-2024-12-04-wbias.png
  inflating: cuib340-2024-12-05_page0.png
  inflating: cuib340-2024-12-05-wbias.png
  inflating: cuib341-2024-12-06_page0.png
  inflating: cuib341-2024-12-06-wbias.png
  inflating: cuib342-2024-12-07_page0.png
  inflating: cuib342-2024-12-07-wbias.png
  inflating: cuib343-2024-12-08_page0.png
  inflating: cuib343-2024-12-08-wbias.png
  inflating: cuib344-2024-12-09_page0.png
  inflating: cuib344-2024-12-09-wbias.png
  inflating: cuib345-2024-12-10_page0.png
  inflating: cuib345-2024-12-10-wbias.png
  inflating: cuib346-2024-12-11_page0.png
  inflating: cuib346-2024-12-11-wbias.png
  inflating: cuib347-2024-12-12_page0.png
  inflating: cuib347-2024-12-12-wbias.png
  inflating: cuib348-2024-12-13_page0.png
  inflating: cuib348-2024-12-13-wbias.png
  inflating: cuib349-2024-12-14_page0.png
  inflating: cuib349-2024-12-14-wbias.png
  inflating: cuib350-2024-12-15_page0.png
  inflating: cuib350-2024-12-15-wbias.png
  inflating: cuib351-2024-12-16_page0.png
  inflating: cuib351-2024-12-16-wbias.png
  inflating: cuib352-2024-12-17_page0.png
  inflating: cuib352-2024-12-17-wbias.png
  inflating: cuib353-2024-12-18_page0.png
  inflating: cuib353-2024-12-18-wbias.png
  inflating: cuib354-2024-12-19_page0.png
  inflating: cuib354-2024-12-19-wbias.png
  inflating: cuib355-2024-12-20_page0.png
  inflating: cuib355-2024-12-20-wbias.png
  inflating: cuib356-2024-12-21_page0.png
  inflating: cuib356-2024-12-21-wbias.png
  inflating: cuib357-2024-12-22_page0.png
  inflating: cuib357-2024-12-22-wbias.png
  inflating: cuib358-2024-12-23_page0.png
  inflating: cuib358-2024-12-23-wbias.png
  inflating: cuib359-2024-12-24_page0.png
  inflating: cuib359-2024-12-24-wbias.png
  inflating: cuib360-2024-12-25_page0.png
  inflating: cuib360-2024-12-25-wbias.png
  inflating: cuib361-2024-12-26_page0.png
  inflating: cuib361-2024-12-26-wbias.png
  inflating: cuib362-2024-12-27_page0.png
  inflating: cuib362-2024-12-27-wbias.png
  inflating: cuib363-2024-12-28_page0.png
  inflating: cuib363-2024-12-28-wbias.png
  inflating: cuib364-2024-12-29_page0.png
  inflating: cuib364-2024-12-29-wbias.png
  inflating: cuib365-2024-12-30_page0.png
  inflating: cuib365-2024-12-30-wbias.png
  inflating: cuib366-2024-12-31_page0.png
  inflating: cuib366-2024-12-31-wbias.png
  inflating: cuib271-2024-09-27.Bias
  inflating: cuib271-2024-09-27.Cmn
  inflating: cuib336-2024-12-01.Bias
  inflating: cuib336-2024-12-01.Cmn
  inflating: cuib337-2024-12-02.Bias
  inflating: cuib337-2024-12-02.Cmn
  inflating: cuib338-2024-12-03.Bias
  inflating: cuib338-2024-12-03.Cmn
  inflating: cuib339-2024-12-04.Bias
  inflating: cuib339-2024-12-04.Cmn
  inflating: cuib340-2024-12-05.Bias
  inflating: cuib340-2024-12-05.Cmn
  inflating: cuib341-2024-12-06.Bias
  inflating: cuib341-2024-12-06.Cmn
  inflating: cuib342-2024-12-07.Bias
  inflating: cuib342-2024-12-07.Cmn
  inflating: cuib343-2024-12-08.Bias
  inflating: cuib343-2024-12-08.Cmn
  inflating: cuib344-2024-12-09.Bias
  inflating: cuib344-2024-12-09.Cmn
  inflating: cuib345-2024-12-10.Bias
  inflating: cuib345-2024-12-10.Cmn
  inflating: cuib346-2024-12-11.Bias
  inflating: cuib346-2024-12-11.Cmn
  inflating: cuib347-2024-12-12.Bias
  inflating: cuib347-2024-12-12.Cmn
  inflating: cuib348-2024-12-13.Bias
  inflating: cuib348-2024-12-13.Cmn
  inflating: cuib349-2024-12-14.Bias
  inflating: cuib349-2024-12-14.Cmn
  inflating: cuib350-2024-12-15.Bias
  inflating: cuib350-2024-12-15.Cmn
  inflating: cuib351-2024-12-16.Bias
  inflating: cuib351-2024-12-16.Cmn
  inflating: cuib352-2024-12-17.Bias
  inflating: cuib352-2024-12-17.Cmn
  inflating: cuib353-2024-12-18.Bias
  inflating: cuib353-2024-12-18.Cmn
  inflating: cuib354-2024-12-19.Bias
  inflating: cuib354-2024-12-19.Cmn
  inflating: cuib355-2024-12-20.Bias
  inflating: cuib355-2024-12-20.Cmn
  inflating: cuib356-2024-12-21.Bias
  inflating: cuib356-2024-12-21.Cmn
  inflating: cuib357-2024-12-22.Bias
  inflating: cuib357-2024-12-22.Cmn
  inflating: cuib358-2024-12-23.Bias
  inflating: cuib358-2024-12-23.Cmn
  inflating: cuib359-2024-12-24.Bias
  inflating: cuib359-2024-12-24.Cmn
  inflating: cuib360-2024-12-25.Bias
  inflating: cuib360-2024-12-25.Cmn
  inflating: cuib361-2024-12-26.Bias
  inflating: cuib361-2024-12-26.Cmn
  inflating: cuib362-2024-12-27.Bias
  inflating: cuib362-2024-12-27.Cmn
  inflating: cuib363-2024-12-28.Bias
  inflating: cuib363-2024-12-28.Cmn
  inflating: cuib364-2024-12-29.Bias
  inflating: cuib364-2024-12-29.Cmn
  inflating: cuib365-2024-12-30.Bias
  inflating: cuib365-2024-12-30.Cmn
  inflating: cuib366-2024-12-31.Bias
  inflating: cuib366-2024-12-31.Cmn

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

pd.set_option('display.max_rows', None)

df = pd.read_csv('cuib271-2024-09-27.Std', sep='\s+', header=None)

df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

base_date = datetime(2024, 9, 27)

def decimal_to_time(decimal_hours):
    hours = int(decimal_hours)
    minutes = int((decimal_hours - hours) * 60)
    seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
    return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

print(df)

df.to_pickle('cuib271-2024-09-27.pkl')

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2802720263.py:7: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('cuib271-2024-09-27.Std', sep='\s+', header=None)

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  73.94    14.37    -15.56
1    2024-09-27 00:01:01  73.96    13.21    -15.56
2    2024-09-27 00:01:58  73.99    10.49    -15.56
3    2024-09-27 00:03:00  74.01     9.33    -15.56
4    2024-09-27 00:04:01  74.04     9.36    -15.56
5    2024-09-27 00:04:58  74.07    11.00    -15.56
6    2024-09-27 00:06:00  74.09    10.33    -15.56
7    2024-09-27 00:07:01  74.12    10.05    -15.56
8    2024-09-27 00:07:58  74.15    10.09    -15.56
9    2024-09-27 00:09:00  74.17     9.95    -15.56
10   2024-09-27 00:10:01  74.20     9.47    -15.56
11   2024-09-27 00:10:58  74.22     9.59    -15.56
12   2024-09-27 00:12:00  74.25     9.32    -15.56
13   2024-09-27 00:13:01  74.27     9.24    -15.56
14   2024-09-27 00:13:58  74.29     9.08    -15.56
15   2024-09-27 00:15:00  74.31     9.24    -15.56
16   2024-09-27 00:16:01  74.33     8.91    -15.56
17   2024-09-27 00:16:58  74.35     8.71    -15.56
18   2024-09-27 00:18:00  74.36     8.72    -15.56
19   2024-09-27 00:19:01  74.38     8.42    -15.56
20   2024-09-27 00:19:58  74.39     8.49    -15.56
21   2024-09-27 00:21:00  74.40     8.10    -15.56
22   2024-09-27 00:22:01  74.40     8.00    -15.56
23   2024-09-27 00:22:58  74.41     7.83    -15.56
24   2024-09-27 00:24:00  74.41     7.76    -15.56
25   2024-09-27 00:25:01  74.41     7.66    -15.56
26   2024-09-27 00:25:58  74.41     7.96    -15.56
27   2024-09-27 00:27:00  74.40     8.26    -15.56
28   2024-09-27 00:28:01  74.40     8.30    -15.56
29   2024-09-27 00:28:58  74.39     8.61    -15.56
30   2024-09-27 00:30:00  74.38     8.63    -15.56
31   2024-09-27 00:31:01  74.36     8.95    -15.56
32   2024-09-27 00:31:58  74.35    11.32    -15.56
33   2024-09-27 00:33:00  74.33    12.94    -15.56
34   2024-09-27 00:34:01  74.31    12.92    -15.56
35   2024-09-27 00:34:58  74.29    12.39    -15.56
36   2024-09-27 00:36:00  74.26    12.59    -15.56
37   2024-09-27 00:37:01  74.24    13.07    -15.56
38   2024-09-27 00:37:58  74.21    12.96    -15.56
39   2024-09-27 00:39:00  74.19    12.10    -15.56
40   2024-09-27 00:40:01  74.16    13.04    -15.56
41   2024-09-27 00:40:58  74.13    12.12    -15.56
42   2024-09-27 00:42:00  74.10    12.28    -15.56
43   2024-09-27 00:43:01  74.08    12.44    -15.56
44   2024-09-27 00:43:58  74.05    11.44    -15.56
45   2024-09-27 00:45:00  74.02    12.00    -15.56
46   2024-09-27 00:46:01  73.99    11.64    -15.56
47   2024-09-27 00:46:58  73.97    10.26    -15.56
48   2024-09-27 00:48:00  73.94    11.63    -15.56
49   2024-09-27 00:49:01  73.92    10.06    -15.56
50   2024-09-27 00:49:58  73.90    11.18    -15.56
51   2024-09-27 00:51:00  73.88    11.72    -15.56
52   2024-09-27 00:52:01  73.86    12.47    -15.56
53   2024-09-27 00:52:58  73.85    11.95    -15.56
54   2024-09-27 00:54:00  73.84    10.91    -15.56
55   2024-09-27 00:55:01  73.84    11.56    -15.56
56   2024-09-27 00:55:58  73.84    11.76    -15.56
57   2024-09-27 00:57:00  73.84    11.90    -15.56
58   2024-09-27 00:58:01  73.84    10.18    -15.56
59   2024-09-27 00:58:58  73.85    10.46    -15.56
60   2024-09-27 01:00:00  73.87    10.38    -15.56
61   2024-09-27 01:01:01  73.88    10.03    -15.56
62   2024-09-27 01:01:58  73.91    10.68    -15.56
63   2024-09-27 01:03:00  73.93     9.94    -15.56
64   2024-09-27 01:04:01  73.96     9.59    -15.56
65   2024-09-27 01:04:58  74.00    10.05    -15.56
66   2024-09-27 01:06:00  74.04    10.06    -15.56
67   2024-09-27 01:07:01  74.08    10.10    -15.56
68   2024-09-27 01:07:58  74.12    10.16    -15.56
69   2024-09-27 01:08:59  74.17     9.95    -15.56
70   2024-09-27 01:10:01  74.22    10.51    -15.56
71   2024-09-27 01:10:58  74.27    10.40    -15.56
72   2024-09-27 01:11:59  74.32    10.90    -15.56
73   2024-09-27 01:13:01  74.38    10.90    -15.56
74   2024-09-27 01:13:58  74.43    10.88    -15.56
75   2024-09-27 01:15:00  74.48    10.96    -15.56
76   2024-09-27 01:16:01  74.53    11.25    -15.56
77   2024-09-27 01:16:58  74.58    10.81    -15.56
78   2024-09-27 01:18:00  74.63    11.47    -15.56
79   2024-09-27 01:19:01  74.67    11.48    -15.56
80   2024-09-27 01:19:58  74.71    10.91    -15.56
81   2024-09-27 01:21:00  74.75    10.85    -15.56
82   2024-09-27 01:22:01  74.77    11.35    -15.56
83   2024-09-27 01:22:58  74.79    11.70    -15.56
84   2024-09-27 01:23:59  74.81    11.09    -15.56
85   2024-09-27 01:25:01  74.81    11.33    -15.56
86   2024-09-27 01:25:58  74.81    10.53    -15.56
87   2024-09-27 01:26:59  74.80    10.55    -15.56
88   2024-09-27 01:28:01  74.78    10.63    -15.56
89   2024-09-27 01:28:58  74.74     9.51    -15.56
90   2024-09-27 01:30:00  74.70     9.05    -15.56
91   2024-09-27 01:31:01  74.65     8.68    -15.56
92   2024-09-27 01:31:58  74.58     9.44    -15.56
93   2024-09-27 01:33:00  74.51     8.10    -15.56
94   2024-09-27 01:34:01  74.42     8.80    -15.56
95   2024-09-27 01:34:58  74.32     9.80    -15.56
96   2024-09-27 01:36:00  74.21     9.09    -15.56
97   2024-09-27 01:37:01  74.09     8.42    -15.56
98   2024-09-27 01:37:58  73.96     9.60    -15.56
99   2024-09-27 01:38:59  73.81     9.15    -15.56
100  2024-09-27 01:40:01  73.66     8.93    -15.56
101  2024-09-27 01:40:58  73.50     9.07    -15.56
102  2024-09-27 01:42:00  73.32     9.34    -15.56
103  2024-09-27 01:43:01  73.14     8.32    -15.56
104  2024-09-27 01:43:58  72.96     9.39    -15.56
105  2024-09-27 01:45:00  72.76     8.92    -15.56
106  2024-09-27 01:46:01  72.56     8.94    -15.56
107  2024-09-27 01:46:58  72.35     9.42    -15.56
108  2024-09-27 01:48:00  72.14     9.88    -15.56
109  2024-09-27 01:49:01  71.92     9.41    -15.56
110  2024-09-27 01:49:58  71.70     9.35    -15.56
111  2024-09-27 01:51:00  71.48     9.08    -15.56
112  2024-09-27 01:52:01  71.26     8.28    -15.56
113  2024-09-27 01:52:58  71.03     9.50    -15.56
114  2024-09-27 01:53:59  70.81     8.07    -15.56
115  2024-09-27 01:55:01  70.59     8.68    -15.56
116  2024-09-27 01:55:58  70.37     8.57    -15.56
117  2024-09-27 01:57:00  70.15     8.60    -15.56
118  2024-09-27 01:58:01  69.93     8.90    -15.56
119  2024-09-27 01:58:58  69.72     8.88    -15.56
120  2024-09-27 02:00:00  69.51     8.56    -15.56
121  2024-09-27 02:01:01  69.30     8.35    -15.56
122  2024-09-27 02:01:58  69.10     7.84    -15.56
123  2024-09-27 02:02:59  68.90     7.93    -15.56
124  2024-09-27 02:04:01  68.71     7.82    -15.56
125  2024-09-27 02:04:58  68.52     7.76    -15.56
126  2024-09-27 02:06:00  68.34     7.67    -15.56
127  2024-09-27 02:07:01  68.16     7.71    -15.56
128  2024-09-27 02:07:58  67.98     7.86    -15.56
129  2024-09-27 02:08:59  67.80     7.06    -15.56
130  2024-09-27 02:10:01  67.63     7.50    -15.56
131  2024-09-27 02:10:58  67.46     7.40    -15.56
132  2024-09-27 02:12:00  67.29     7.16    -15.56
133  2024-09-27 02:13:01  67.12     7.62    -15.56
134  2024-09-27 02:13:58  66.95     7.80    -15.56
135  2024-09-27 02:15:00  66.78     7.86    -15.56
136  2024-09-27 02:16:01  66.61     7.52    -15.56
137  2024-09-27 02:16:58  66.44     8.00    -15.56
138  2024-09-27 02:17:59  66.26     6.85    -15.56
139  2024-09-27 02:19:01  66.08     6.95    -15.56
140  2024-09-27 02:19:58  65.90     7.70    -15.56
141  2024-09-27 02:21:00  65.71     7.62    -15.56
142  2024-09-27 02:22:01  65.52     7.86    -15.56
143  2024-09-27 02:22:58  65.32     8.32    -15.56
144  2024-09-27 02:23:59  65.11     8.07    -15.56
145  2024-09-27 02:25:01  64.90     7.55    -15.56
146  2024-09-27 02:25:58  64.68     8.18    -15.56
147  2024-09-27 02:27:00  64.46     8.59    -15.56
148  2024-09-27 02:28:01  64.23     9.32    -15.56
149  2024-09-27 02:28:58  63.99     9.57    -15.56
150  2024-09-27 02:30:00  63.75     9.66    -15.56
151  2024-09-27 02:31:01  63.50     9.86    -15.56
152  2024-09-27 02:31:58  63.25    10.06    -15.56
153  2024-09-27 02:32:59  62.99     9.82    -15.56
154  2024-09-27 02:34:01  62.73    10.01    -15.56
155  2024-09-27 02:34:58  62.46     9.61    -15.56
156  2024-09-27 02:36:00  62.19    10.32    -15.56
157  2024-09-27 02:37:01  61.91     9.86    -15.56
158  2024-09-27 02:37:58  61.64     9.35    -15.56
159  2024-09-27 02:38:59  61.36     9.94    -15.56
160  2024-09-27 02:40:01  61.09     9.82    -15.56
161  2024-09-27 02:40:58  60.81    10.31    -15.56
162  2024-09-27 02:42:00  60.54     9.41    -15.56
163  2024-09-27 02:43:01  60.28     9.56    -15.56
164  2024-09-27 02:43:58  60.02     9.69    -15.56
165  2024-09-27 02:45:00  59.76     9.75    -15.56
166  2024-09-27 02:46:01  59.52     9.09    -15.56
167  2024-09-27 02:46:58  59.28     9.37    -15.56
168  2024-09-27 02:47:59  59.05     9.14    -15.56
169  2024-09-27 02:49:01  58.84     9.59    -15.56
170  2024-09-27 02:49:58  58.63     9.31    -15.56
171  2024-09-27 02:51:00  58.44     9.34    -15.56
172  2024-09-27 02:52:01  58.27     9.88    -15.56
173  2024-09-27 02:52:58  58.10    10.22    -15.56
174  2024-09-27 02:53:59  57.96    10.54    -15.56
175  2024-09-27 02:55:01  57.83    10.84    -15.56
176  2024-09-27 02:55:58  57.72    10.69    -15.56
177  2024-09-27 02:57:00  57.63    10.68    -15.56
178  2024-09-27 02:58:01  57.55    10.70    -15.56
179  2024-09-27 02:58:58  57.50    10.47    -15.56
180  2024-09-27 03:00:00  57.46    10.54    -15.56
181  2024-09-27 03:01:01  57.44    10.25    -15.56
182  2024-09-27 03:01:58  57.44    10.17    -15.56
183  2024-09-27 03:02:59  57.45    10.54    -15.56
184  2024-09-27 03:04:01  57.49    10.21    -15.56
185  2024-09-27 03:04:58  57.54    10.64    -15.56
186  2024-09-27 03:06:00  57.61    10.69    -15.56
187  2024-09-27 03:07:01  57.70    10.04    -15.56
188  2024-09-27 03:07:58  57.80    10.36    -15.56
189  2024-09-27 03:08:59  57.92    10.49    -15.56
190  2024-09-27 03:10:01  58.05    10.62    -15.56
191  2024-09-27 03:10:58  58.19    11.02    -15.56
192  2024-09-27 03:12:00  58.34    10.42    -15.56
193  2024-09-27 03:13:01  58.50    11.41    -15.56
194  2024-09-27 03:13:58  58.67    10.91    -15.56
195  2024-09-27 03:15:00  58.85    11.24    -15.56
196  2024-09-27 03:16:01  59.03    10.79    -15.56
197  2024-09-27 03:16:58  59.21    11.40    -15.56
198  2024-09-27 03:17:59  59.40    11.56    -15.56
199  2024-09-27 03:19:01  59.59    12.20    -15.56
200  2024-09-27 03:19:58  59.78    13.43    -15.56
201  2024-09-27 03:21:00  59.97    14.04    -15.56
202  2024-09-27 03:22:01  60.15    13.80    -15.56
203  2024-09-27 03:22:58  60.33    13.89    -15.56
204  2024-09-27 03:23:59  60.51    13.99    -15.56
205  2024-09-27 03:25:01  60.67    14.33    -15.56
206  2024-09-27 03:25:58  60.83    13.50    -15.56
207  2024-09-27 03:27:00  60.98    13.60    -15.56
208  2024-09-27 03:28:01  61.12    13.84    -15.56
209  2024-09-27 03:28:58  61.25    13.17    -15.56
210  2024-09-27 03:30:00  61.37    13.13    -15.56
211  2024-09-27 03:31:01  61.47    12.04    -15.56
212  2024-09-27 03:31:58  61.57    12.06    -15.56
213  2024-09-27 03:32:59  61.65    11.96    -15.56
214  2024-09-27 03:34:01  61.71    11.58    -15.56
215  2024-09-27 03:34:58  61.76    11.30    -15.56
216  2024-09-27 03:36:00  61.80    11.00    -15.56
217  2024-09-27 03:37:01  61.82    11.16    -15.56
218  2024-09-27 03:37:58  61.83    10.91    -15.56
219  2024-09-27 03:38:59  61.83    10.65    -15.56
220  2024-09-27 03:40:01  61.81    10.45    -15.56
221  2024-09-27 03:40:58  61.78    10.56    -15.56
222  2024-09-27 03:42:00  61.74    10.52    -15.56
223  2024-09-27 03:43:01  61.69    10.60    -15.56
224  2024-09-27 03:43:58  61.63    10.52    -15.56
225  2024-09-27 03:45:00  61.55    10.84    -15.56
226  2024-09-27 03:46:01  61.47    10.82    -15.56
227  2024-09-27 03:46:58  61.38    11.08    -15.56
228  2024-09-27 03:47:59  61.28    11.05    -15.56
229  2024-09-27 03:49:01  61.17    11.09    -15.56
230  2024-09-27 03:49:58  61.06    11.16    -15.56
231  2024-09-27 03:51:00  60.94    11.90    -15.56
232  2024-09-27 03:52:01  60.82    10.85    -15.56
233  2024-09-27 03:52:58  60.70    11.50    -15.56
234  2024-09-27 03:53:59  60.57    11.63    -15.56
235  2024-09-27 03:55:01  60.44    12.29    -15.56
236  2024-09-27 03:55:58  60.31    10.91    -15.56
237  2024-09-27 03:57:00  60.18    12.10    -15.56
238  2024-09-27 03:58:01  60.05    12.03    -15.56
239  2024-09-27 03:58:58  59.92    12.78    -15.56
240  2024-09-27 04:00:00  59.79    12.65    -15.56
241  2024-09-27 04:01:01  59.67    12.80    -15.56
242  2024-09-27 04:01:58  59.54    12.96    -15.56
243  2024-09-27 04:02:59  59.41    12.02    -15.56
244  2024-09-27 04:04:01  59.29    12.37    -15.56
245  2024-09-27 04:04:58  59.17     7.50    -15.56
246  2024-09-27 04:05:59  59.05     7.43    -15.56
247  2024-09-27 04:07:01  58.93     7.25    -15.56
248  2024-09-27 04:07:58  58.81     7.17    -15.56
249  2024-09-27 04:09:00  58.70     7.34    -15.56
250  2024-09-27 04:10:01  58.58     7.34    -15.56
251  2024-09-27 04:10:58  58.46     7.00    -15.56
252  2024-09-27 04:12:00  58.35     6.84    -15.56
253  2024-09-27 04:13:01  58.23     6.86    -15.56
254  2024-09-27 04:13:58  58.11     6.57    -15.56
255  2024-09-27 04:15:00  57.99     6.72    -15.56
256  2024-09-27 04:16:01  57.86     6.72    -15.56
257  2024-09-27 04:16:58  57.74     6.69    -15.56
258  2024-09-27 04:17:59  57.61     6.51    -15.56
259  2024-09-27 04:19:01  57.47     6.47    -15.56
260  2024-09-27 04:19:58  57.34     6.49    -15.56
261  2024-09-27 04:20:59  57.19     6.21    -15.56
262  2024-09-27 04:22:01  57.05     6.28    -15.56
263  2024-09-27 04:22:58  56.89     6.39    -15.56
264  2024-09-27 04:24:00  56.73     6.56    -15.56
265  2024-09-27 04:25:01  56.56     6.71    -15.56
266  2024-09-27 04:25:58  56.39     6.86    -15.56
267  2024-09-27 04:27:00  56.20     6.98    -15.56
268  2024-09-27 04:28:01  56.01     7.06    -15.56
269  2024-09-27 04:28:58  55.81     7.14    -15.56
270  2024-09-27 04:30:00  55.60     7.01    -15.56
271  2024-09-27 04:31:01  55.38     7.00    -15.56
272  2024-09-27 04:31:58  55.15     6.92    -15.56
273  2024-09-27 04:32:59  54.92     6.92    -15.56
274  2024-09-27 04:34:01  54.67     7.00    -15.56
275  2024-09-27 04:34:58  54.41     6.67    -15.56
276  2024-09-27 04:35:59  54.15     9.09    -15.56
277  2024-09-27 04:37:01  53.87     9.14    -15.56
278  2024-09-27 04:37:58  53.58     8.87    -15.56
279  2024-09-27 04:39:00  53.28     9.16    -15.56
280  2024-09-27 04:40:01  52.98     8.89    -15.56
281  2024-09-27 04:40:58  52.66     8.56    -15.56
282  2024-09-27 04:42:00  52.33     8.47    -15.56
283  2024-09-27 04:43:01  51.99     8.43    -15.56
284  2024-09-27 04:43:58  51.64     8.43    -15.56
285  2024-09-27 04:45:00  51.28     8.43    -15.56
286  2024-09-27 04:46:01  50.91     8.45    -15.56
287  2024-09-27 04:46:58  50.53     8.45    -15.56
288  2024-09-27 04:47:59  50.14     8.44    -15.56
289  2024-09-27 04:49:01  49.74     8.40    -15.56
290  2024-09-27 04:49:58  49.33     8.35    -15.56
291  2024-09-27 04:50:59  48.91     8.32    -15.56
292  2024-09-27 04:52:01  48.48     8.47    -15.56
293  2024-09-27 04:52:58  48.04     7.91    -15.56
294  2024-09-27 04:54:00  47.58     8.32    -15.56
295  2024-09-27 04:55:01  47.12     8.20    -15.56
296  2024-09-27 04:55:58  46.65     8.19    -15.56
297  2024-09-27 04:57:00  46.17     8.08    -15.56
298  2024-09-27 04:58:01  45.68     8.50    -15.56
299  2024-09-27 04:58:58  45.18     8.11    -15.56
300  2024-09-27 05:00:00  44.67     8.01    -15.56
301  2024-09-27 05:01:01  44.16     8.05    -15.56
302  2024-09-27 05:01:58  43.63     8.22    -15.56
303  2024-09-27 05:02:59  43.09     8.20    -15.56
304  2024-09-27 05:04:01  42.55     8.17    -15.56
305  2024-09-27 05:04:58  42.00     8.42    -15.56
306  2024-09-27 05:05:59  41.44     8.11    -15.56
307  2024-09-27 05:07:01  40.88     7.97    -15.56
308  2024-09-27 05:07:58  40.31     7.67    -15.56
309  2024-09-27 05:09:00  39.73     7.98    -15.56
310  2024-09-27 05:10:01  39.15     7.74    -15.56
311  2024-09-27 05:10:58  38.56     7.39    -15.56
312  2024-09-27 05:12:00  37.97     7.30    -15.56
313  2024-09-27 05:13:01  37.37     7.35    -15.56
314  2024-09-27 05:13:58  36.77     6.97    -15.56
315  2024-09-27 05:15:00  36.17     6.98    -15.56
316  2024-09-27 05:16:01  35.57     6.66    -15.56
317  2024-09-27 05:16:58  34.96     6.32    -15.56
318  2024-09-27 05:17:59  34.36     6.39    -15.56
319  2024-09-27 05:19:01  33.76     6.38    -15.56
320  2024-09-27 05:19:58  33.15     5.99    -15.56
321  2024-09-27 05:20:59  32.55     5.70    -15.56
322  2024-09-27 05:22:01  31.95     5.68    -15.56
323  2024-09-27 05:22:58  31.36     5.77    -15.56
324  2024-09-27 05:24:00  30.77     5.32    -15.56
325  2024-09-27 05:25:01  30.18     5.41    -15.56
326  2024-09-27 05:25:58  29.60     5.13    -15.56
327  2024-09-27 05:27:00  29.02     4.85    -15.56
328  2024-09-27 05:28:01  28.45     4.95    -15.56
329  2024-09-27 05:28:58  27.89     4.54    -15.56
330  2024-09-27 05:30:00  27.34     4.63    -15.56
331  2024-09-27 05:31:01  26.79     4.68    -15.56
332  2024-09-27 05:31:58  26.26     4.54    -15.56
333  2024-09-27 05:32:59  25.73     4.23    -15.56
334  2024-09-27 05:34:01  25.22     4.41    -15.56
335  2024-09-27 05:34:58  24.71     4.12    -15.56
336  2024-09-27 05:35:59  24.22     3.98    -15.56
337  2024-09-27 05:37:01  23.74     3.84    -15.56
338  2024-09-27 05:37:58  23.27     3.72    -15.56
339  2024-09-27 05:39:00  22.81     3.59    -15.56
340  2024-09-27 05:40:01  22.36     3.58    -15.56
341  2024-09-27 05:40:58  21.93     3.42    -15.56
342  2024-09-27 05:42:00  21.50     3.32    -15.56
343  2024-09-27 05:43:01  21.10     3.26    -15.56
344  2024-09-27 05:43:58  20.70     3.24    -15.56
345  2024-09-27 05:45:00  20.31     2.98    -15.56
346  2024-09-27 05:46:01  19.94     3.08    -15.56
347  2024-09-27 05:46:58  19.58     3.07    -15.56
348  2024-09-27 05:47:59  19.24     3.00    -15.56
349  2024-09-27 05:49:01  18.90     2.96    -15.56
350  2024-09-27 05:49:58  18.58     2.94    -15.56
351  2024-09-27 05:50:59  18.27     2.91    -15.56
352  2024-09-27 05:52:01  17.97     2.85    -15.56
353  2024-09-27 05:52:58  17.68     2.86    -15.56
354  2024-09-27 05:54:00  17.41     2.68    -15.56
355  2024-09-27 05:55:01  17.14     2.73    -15.56
356  2024-09-27 05:55:58  16.88     2.69    -15.56
357  2024-09-27 05:57:00  16.64     2.67    -15.56
358  2024-09-27 05:58:01  16.40     2.68    -15.56
359  2024-09-27 05:58:58  16.18     2.69    -15.56
360  2024-09-27 06:00:00  15.96     2.71    -15.56
361  2024-09-27 06:01:01  15.75     2.72    -15.56
362  2024-09-27 06:01:58  15.55     2.74    -15.56
363  2024-09-27 06:02:59  15.35     2.76    -15.56
364  2024-09-27 06:04:01  15.17     2.68    -15.56
365  2024-09-27 06:04:58  14.99     2.47    -15.56
366  2024-09-27 06:05:59  14.82     2.47    -15.56
367  2024-09-27 06:07:01  14.65     2.52    -15.56
368  2024-09-27 06:07:58  14.49     2.62    -15.56
369  2024-09-27 06:09:00  14.34     2.61    -15.56
370  2024-09-27 06:10:01  14.19     2.77    -15.56
371  2024-09-27 06:10:58  14.05     2.45    -15.56
372  2024-09-27 06:12:00  13.91     2.57    -15.56
373  2024-09-27 06:13:01  13.78     2.66    -15.56
374  2024-09-27 06:13:58  13.65     2.78    -15.56
375  2024-09-27 06:15:00  13.52     2.65    -15.56
376  2024-09-27 06:16:01  13.40     2.44    -15.56
377  2024-09-27 06:16:58  13.29     2.79    -15.56
378  2024-09-27 06:17:59  13.17     2.40    -15.56
379  2024-09-27 06:19:01  13.06     2.72    -15.56
380  2024-09-27 06:19:58  12.95     2.74    -15.56
381  2024-09-27 06:20:59  12.85     2.46    -15.56
382  2024-09-27 06:22:01  12.75     2.57    -15.56
383  2024-09-27 06:22:58  12.65     2.65    -15.56
384  2024-09-27 06:24:00  12.55     2.67    -15.56
385  2024-09-27 06:25:01  12.45     2.69    -15.56
386  2024-09-27 06:25:58  12.36     2.69    -15.56
387  2024-09-27 06:27:00  12.27     2.78    -15.56
388  2024-09-27 06:28:01  12.18     2.62    -15.56
389  2024-09-27 06:28:58  12.09     2.74    -15.56
390  2024-09-27 06:30:00  12.00     2.95    -15.56

In [ ]:
df

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  73.94    14.37    -15.56
1    2024-09-27 00:01:01  73.96    13.21    -15.56
2    2024-09-27 00:01:58  73.99    10.49    -15.56
3    2024-09-27 00:03:00  74.01     9.33    -15.56
4    2024-09-27 00:04:01  74.04     9.36    -15.56
5    2024-09-27 00:04:58  74.07    11.00    -15.56
6    2024-09-27 00:06:00  74.09    10.33    -15.56
7    2024-09-27 00:07:01  74.12    10.05    -15.56
8    2024-09-27 00:07:58  74.15    10.09    -15.56
9    2024-09-27 00:09:00  74.17     9.95    -15.56
10   2024-09-27 00:10:01  74.20     9.47    -15.56
11   2024-09-27 00:10:58  74.22     9.59    -15.56
12   2024-09-27 00:12:00  74.25     9.32    -15.56
13   2024-09-27 00:13:01  74.27     9.24    -15.56
14   2024-09-27 00:13:58  74.29     9.08    -15.56
15   2024-09-27 00:15:00  74.31     9.24    -15.56
16   2024-09-27 00:16:01  74.33     8.91    -15.56
17   2024-09-27 00:16:58  74.35     8.71    -15.56
18   2024-09-27 00:18:00  74.36     8.72    -15.56
19   2024-09-27 00:19:01  74.38     8.42    -15.56
20   2024-09-27 00:19:58  74.39     8.49    -15.56
21   2024-09-27 00:21:00  74.40     8.10    -15.56
22   2024-09-27 00:22:01  74.40     8.00    -15.56
23   2024-09-27 00:22:58  74.41     7.83    -15.56
24   2024-09-27 00:24:00  74.41     7.76    -15.56
25   2024-09-27 00:25:01  74.41     7.66    -15.56
26   2024-09-27 00:25:58  74.41     7.96    -15.56
27   2024-09-27 00:27:00  74.40     8.26    -15.56
28   2024-09-27 00:28:01  74.40     8.30    -15.56
29   2024-09-27 00:28:58  74.39     8.61    -15.56
30   2024-09-27 00:30:00  74.38     8.63    -15.56
31   2024-09-27 00:31:01  74.36     8.95    -15.56
32   2024-09-27 00:31:58  74.35    11.32    -15.56
33   2024-09-27 00:33:00  74.33    12.94    -15.56
34   2024-09-27 00:34:01  74.31    12.92    -15.56
35   2024-09-27 00:34:58  74.29    12.39    -15.56
36   2024-09-27 00:36:00  74.26    12.59    -15.56
37   2024-09-27 00:37:01  74.24    13.07    -15.56
38   2024-09-27 00:37:58  74.21    12.96    -15.56
39   2024-09-27 00:39:00  74.19    12.10    -15.56
40   2024-09-27 00:40:01  74.16    13.04    -15.56
41   2024-09-27 00:40:58  74.13    12.12    -15.56
42   2024-09-27 00:42:00  74.10    12.28    -15.56
43   2024-09-27 00:43:01  74.08    12.44    -15.56
44   2024-09-27 00:43:58  74.05    11.44    -15.56
45   2024-09-27 00:45:00  74.02    12.00    -15.56
46   2024-09-27 00:46:01  73.99    11.64    -15.56
47   2024-09-27 00:46:58  73.97    10.26    -15.56
48   2024-09-27 00:48:00  73.94    11.63    -15.56
49   2024-09-27 00:49:01  73.92    10.06    -15.56
50   2024-09-27 00:49:58  73.90    11.18    -15.56
51   2024-09-27 00:51:00  73.88    11.72    -15.56
52   2024-09-27 00:52:01  73.86    12.47    -15.56
53   2024-09-27 00:52:58  73.85    11.95    -15.56
54   2024-09-27 00:54:00  73.84    10.91    -15.56
55   2024-09-27 00:55:01  73.84    11.56    -15.56
56   2024-09-27 00:55:58  73.84    11.76    -15.56
57   2024-09-27 00:57:00  73.84    11.90    -15.56
58   2024-09-27 00:58:01  73.84    10.18    -15.56
59   2024-09-27 00:58:58  73.85    10.46    -15.56
60   2024-09-27 01:00:00  73.87    10.38    -15.56
61   2024-09-27 01:01:01  73.88    10.03    -15.56
62   2024-09-27 01:01:58  73.91    10.68    -15.56
63   2024-09-27 01:03:00  73.93     9.94    -15.56
64   2024-09-27 01:04:01  73.96     9.59    -15.56
65   2024-09-27 01:04:58  74.00    10.05    -15.56
66   2024-09-27 01:06:00  74.04    10.06    -15.56
67   2024-09-27 01:07:01  74.08    10.10    -15.56
68   2024-09-27 01:07:58  74.12    10.16    -15.56
69   2024-09-27 01:08:59  74.17     9.95    -15.56
70   2024-09-27 01:10:01  74.22    10.51    -15.56
71   2024-09-27 01:10:58  74.27    10.40    -15.56
72   2024-09-27 01:11:59  74.32    10.90    -15.56
73   2024-09-27 01:13:01  74.38    10.90    -15.56
74   2024-09-27 01:13:58  74.43    10.88    -15.56
75   2024-09-27 01:15:00  74.48    10.96    -15.56
76   2024-09-27 01:16:01  74.53    11.25    -15.56
77   2024-09-27 01:16:58  74.58    10.81    -15.56
78   2024-09-27 01:18:00  74.63    11.47    -15.56
79   2024-09-27 01:19:01  74.67    11.48    -15.56
80   2024-09-27 01:19:58  74.71    10.91    -15.56
81   2024-09-27 01:21:00  74.75    10.85    -15.56
82   2024-09-27 01:22:01  74.77    11.35    -15.56
83   2024-09-27 01:22:58  74.79    11.70    -15.56
84   2024-09-27 01:23:59  74.81    11.09    -15.56
85   2024-09-27 01:25:01  74.81    11.33    -15.56
86   2024-09-27 01:25:58  74.81    10.53    -15.56
87   2024-09-27 01:26:59  74.80    10.55    -15.56
88   2024-09-27 01:28:01  74.78    10.63    -15.56
89   2024-09-27 01:28:58  74.74     9.51    -15.56
90   2024-09-27 01:30:00  74.70     9.05    -15.56
91   2024-09-27 01:31:01  74.65     8.68    -15.56
92   2024-09-27 01:31:58  74.58     9.44    -15.56
93   2024-09-27 01:33:00  74.51     8.10    -15.56
94   2024-09-27 01:34:01  74.42     8.80    -15.56
95   2024-09-27 01:34:58  74.32     9.80    -15.56
96   2024-09-27 01:36:00  74.21     9.09    -15.56
97   2024-09-27 01:37:01  74.09     8.42    -15.56
98   2024-09-27 01:37:58  73.96     9.60    -15.56
99   2024-09-27 01:38:59  73.81     9.15    -15.56
100  2024-09-27 01:40:01  73.66     8.93    -15.56
101  2024-09-27 01:40:58  73.50     9.07    -15.56
102  2024-09-27 01:42:00  73.32     9.34    -15.56
103  2024-09-27 01:43:01  73.14     8.32    -15.56
104  2024-09-27 01:43:58  72.96     9.39    -15.56
105  2024-09-27 01:45:00  72.76     8.92    -15.56
106  2024-09-27 01:46:01  72.56     8.94    -15.56
107  2024-09-27 01:46:58  72.35     9.42    -15.56
108  2024-09-27 01:48:00  72.14     9.88    -15.56
109  2024-09-27 01:49:01  71.92     9.41    -15.56
110  2024-09-27 01:49:58  71.70     9.35    -15.56
111  2024-09-27 01:51:00  71.48     9.08    -15.56
112  2024-09-27 01:52:01  71.26     8.28    -15.56
113  2024-09-27 01:52:58  71.03     9.50    -15.56
114  2024-09-27 01:53:59  70.81     8.07    -15.56
115  2024-09-27 01:55:01  70.59     8.68    -15.56
116  2024-09-27 01:55:58  70.37     8.57    -15.56
117  2024-09-27 01:57:00  70.15     8.60    -15.56
118  2024-09-27 01:58:01  69.93     8.90    -15.56
119  2024-09-27 01:58:58  69.72     8.88    -15.56
120  2024-09-27 02:00:00  69.51     8.56    -15.56
121  2024-09-27 02:01:01  69.30     8.35    -15.56
122  2024-09-27 02:01:58  69.10     7.84    -15.56
123  2024-09-27 02:02:59  68.90     7.93    -15.56
124  2024-09-27 02:04:01  68.71     7.82    -15.56
125  2024-09-27 02:04:58  68.52     7.76    -15.56
126  2024-09-27 02:06:00  68.34     7.67    -15.56
127  2024-09-27 02:07:01  68.16     7.71    -15.56
128  2024-09-27 02:07:58  67.98     7.86    -15.56
129  2024-09-27 02:08:59  67.80     7.06    -15.56
130  2024-09-27 02:10:01  67.63     7.50    -15.56
131  2024-09-27 02:10:58  67.46     7.40    -15.56
132  2024-09-27 02:12:00  67.29     7.16    -15.56
133  2024-09-27 02:13:01  67.12     7.62    -15.56
134  2024-09-27 02:13:58  66.95     7.80    -15.56
135  2024-09-27 02:15:00  66.78     7.86    -15.56
136  2024-09-27 02:16:01  66.61     7.52    -15.56
137  2024-09-27 02:16:58  66.44     8.00    -15.56
138  2024-09-27 02:17:59  66.26     6.85    -15.56
139  2024-09-27 02:19:01  66.08     6.95    -15.56
140  2024-09-27 02:19:58  65.90     7.70    -15.56
141  2024-09-27 02:21:00  65.71     7.62    -15.56
142  2024-09-27 02:22:01  65.52     7.86    -15.56
143  2024-09-27 02:22:58  65.32     8.32    -15.56
144  2024-09-27 02:23:59  65.11     8.07    -15.56
145  2024-09-27 02:25:01  64.90     7.55    -15.56
146  2024-09-27 02:25:58  64.68     8.18    -15.56
147  2024-09-27 02:27:00  64.46     8.59    -15.56
148  2024-09-27 02:28:01  64.23     9.32    -15.56
149  2024-09-27 02:28:58  63.99     9.57    -15.56
150  2024-09-27 02:30:00  63.75     9.66    -15.56
151  2024-09-27 02:31:01  63.50     9.86    -15.56
152  2024-09-27 02:31:58  63.25    10.06    -15.56
153  2024-09-27 02:32:59  62.99     9.82    -15.56
154  2024-09-27 02:34:01  62.73    10.01    -15.56
155  2024-09-27 02:34:58  62.46     9.61    -15.56
156  2024-09-27 02:36:00  62.19    10.32    -15.56
157  2024-09-27 02:37:01  61.91     9.86    -15.56
158  2024-09-27 02:37:58  61.64     9.35    -15.56
159  2024-09-27 02:38:59  61.36     9.94    -15.56
160  2024-09-27 02:40:01  61.09     9.82    -15.56
161  2024-09-27 02:40:58  60.81    10.31    -15.56
162  2024-09-27 02:42:00  60.54     9.41    -15.56
163  2024-09-27 02:43:01  60.28     9.56    -15.56
164  2024-09-27 02:43:58  60.02     9.69    -15.56
165  2024-09-27 02:45:00  59.76     9.75    -15.56
166  2024-09-27 02:46:01  59.52     9.09    -15.56
167  2024-09-27 02:46:58  59.28     9.37    -15.56
168  2024-09-27 02:47:59  59.05     9.14    -15.56
169  2024-09-27 02:49:01  58.84     9.59    -15.56
170  2024-09-27 02:49:58  58.63     9.31    -15.56
171  2024-09-27 02:51:00  58.44     9.34    -15.56
172  2024-09-27 02:52:01  58.27     9.88    -15.56
173  2024-09-27 02:52:58  58.10    10.22    -15.56
174  2024-09-27 02:53:59  57.96    10.54    -15.56
175  2024-09-27 02:55:01  57.83    10.84    -15.56
176  2024-09-27 02:55:58  57.72    10.69    -15.56
177  2024-09-27 02:57:00  57.63    10.68    -15.56
178  2024-09-27 02:58:01  57.55    10.70    -15.56
179  2024-09-27 02:58:58  57.50    10.47    -15.56
180  2024-09-27 03:00:00  57.46    10.54    -15.56
181  2024-09-27 03:01:01  57.44    10.25    -15.56
182  2024-09-27 03:01:58  57.44    10.17    -15.56
183  2024-09-27 03:02:59  57.45    10.54    -15.56
184  2024-09-27 03:04:01  57.49    10.21    -15.56
185  2024-09-27 03:04:58  57.54    10.64    -15.56
186  2024-09-27 03:06:00  57.61    10.69    -15.56
187  2024-09-27 03:07:01  57.70    10.04    -15.56
188  2024-09-27 03:07:58  57.80    10.36    -15.56
189  2024-09-27 03:08:59  57.92    10.49    -15.56
190  2024-09-27 03:10:01  58.05    10.62    -15.56
191  2024-09-27 03:10:58  58.19    11.02    -15.56
192  2024-09-27 03:12:00  58.34    10.42    -15.56
193  2024-09-27 03:13:01  58.50    11.41    -15.56
194  2024-09-27 03:13:58  58.67    10.91    -15.56
195  2024-09-27 03:15:00  58.85    11.24    -15.56
196  2024-09-27 03:16:01  59.03    10.79    -15.56
197  2024-09-27 03:16:58  59.21    11.40    -15.56
198  2024-09-27 03:17:59  59.40    11.56    -15.56
199  2024-09-27 03:19:01  59.59    12.20    -15.56
200  2024-09-27 03:19:58  59.78    13.43    -15.56
201  2024-09-27 03:21:00  59.97    14.04    -15.56
202  2024-09-27 03:22:01  60.15    13.80    -15.56
203  2024-09-27 03:22:58  60.33    13.89    -15.56
204  2024-09-27 03:23:59  60.51    13.99    -15.56
205  2024-09-27 03:25:01  60.67    14.33    -15.56
206  2024-09-27 03:25:58  60.83    13.50    -15.56
207  2024-09-27 03:27:00  60.98    13.60    -15.56
208  2024-09-27 03:28:01  61.12    13.84    -15.56
209  2024-09-27 03:28:58  61.25    13.17    -15.56
210  2024-09-27 03:30:00  61.37    13.13    -15.56
211  2024-09-27 03:31:01  61.47    12.04    -15.56
212  2024-09-27 03:31:58  61.57    12.06    -15.56
213  2024-09-27 03:32:59  61.65    11.96    -15.56
214  2024-09-27 03:34:01  61.71    11.58    -15.56
215  2024-09-27 03:34:58  61.76    11.30    -15.56
216  2024-09-27 03:36:00  61.80    11.00    -15.56
217  2024-09-27 03:37:01  61.82    11.16    -15.56
218  2024-09-27 03:37:58  61.83    10.91    -15.56
219  2024-09-27 03:38:59  61.83    10.65    -15.56
220  2024-09-27 03:40:01  61.81    10.45    -15.56
221  2024-09-27 03:40:58  61.78    10.56    -15.56
222  2024-09-27 03:42:00  61.74    10.52    -15.56
223  2024-09-27 03:43:01  61.69    10.60    -15.56
224  2024-09-27 03:43:58  61.63    10.52    -15.56
225  2024-09-27 03:45:00  61.55    10.84    -15.56
226  2024-09-27 03:46:01  61.47    10.82    -15.56
227  2024-09-27 03:46:58  61.38    11.08    -15.56
228  2024-09-27 03:47:59  61.28    11.05    -15.56
229  2024-09-27 03:49:01  61.17    11.09    -15.56
230  2024-09-27 03:49:58  61.06    11.16    -15.56
231  2024-09-27 03:51:00  60.94    11.90    -15.56
232  2024-09-27 03:52:01  60.82    10.85    -15.56
233  2024-09-27 03:52:58  60.70    11.50    -15.56
234  2024-09-27 03:53:59  60.57    11.63    -15.56
235  2024-09-27 03:55:01  60.44    12.29    -15.56
236  2024-09-27 03:55:58  60.31    10.91    -15.56
237  2024-09-27 03:57:00  60.18    12.10    -15.56
238  2024-09-27 03:58:01  60.05    12.03    -15.56
239  2024-09-27 03:58:58  59.92    12.78    -15.56
240  2024-09-27 04:00:00  59.79    12.65    -15.56
241  2024-09-27 04:01:01  59.67    12.80    -15.56
242  2024-09-27 04:01:58  59.54    12.96    -15.56
243  2024-09-27 04:02:59  59.41    12.02    -15.56
244  2024-09-27 04:04:01  59.29    12.37    -15.56
245  2024-09-27 04:04:58  59.17     7.50    -15.56
246  2024-09-27 04:05:59  59.05     7.43    -15.56
247  2024-09-27 04:07:01  58.93     7.25    -15.56
248  2024-09-27 04:07:58  58.81     7.17    -15.56
249  2024-09-27 04:09:00  58.70     7.34    -15.56
250  2024-09-27 04:10:01  58.58     7.34    -15.56
251  2024-09-27 04:10:58  58.46     7.00    -15.56
252  2024-09-27 04:12:00  58.35     6.84    -15.56
253  2024-09-27 04:13:01  58.23     6.86    -15.56
254  2024-09-27 04:13:58  58.11     6.57    -15.56
255  2024-09-27 04:15:00  57.99     6.72    -15.56
256  2024-09-27 04:16:01  57.86     6.72    -15.56
257  2024-09-27 04:16:58  57.74     6.69    -15.56
258  2024-09-27 04:17:59  57.61     6.51    -15.56
259  2024-09-27 04:19:01  57.47     6.47    -15.56
260  2024-09-27 04:19:58  57.34     6.49    -15.56
261  2024-09-27 04:20:59  57.19     6.21    -15.56
262  2024-09-27 04:22:01  57.05     6.28    -15.56
263  2024-09-27 04:22:58  56.89     6.39    -15.56
264  2024-09-27 04:24:00  56.73     6.56    -15.56
265  2024-09-27 04:25:01  56.56     6.71    -15.56
266  2024-09-27 04:25:58  56.39     6.86    -15.56
267  2024-09-27 04:27:00  56.20     6.98    -15.56
268  2024-09-27 04:28:01  56.01     7.06    -15.56
269  2024-09-27 04:28:58  55.81     7.14    -15.56
270  2024-09-27 04:30:00  55.60     7.01    -15.56
271  2024-09-27 04:31:01  55.38     7.00    -15.56
272  2024-09-27 04:31:58  55.15     6.92    -15.56
273  2024-09-27 04:32:59  54.92     6.92    -15.56
274  2024-09-27 04:34:01  54.67     7.00    -15.56
275  2024-09-27 04:34:58  54.41     6.67    -15.56
276  2024-09-27 04:35:59  54.15     9.09    -15.56
277  2024-09-27 04:37:01  53.87     9.14    -15.56
278  2024-09-27 04:37:58  53.58     8.87    -15.56
279  2024-09-27 04:39:00  53.28     9.16    -15.56
280  2024-09-27 04:40:01  52.98     8.89    -15.56
281  2024-09-27 04:40:58  52.66     8.56    -15.56
282  2024-09-27 04:42:00  52.33     8.47    -15.56
283  2024-09-27 04:43:01  51.99     8.43    -15.56
284  2024-09-27 04:43:58  51.64     8.43    -15.56
285  2024-09-27 04:45:00  51.28     8.43    -15.56
286  2024-09-27 04:46:01  50.91     8.45    -15.56
287  2024-09-27 04:46:58  50.53     8.45    -15.56
288  2024-09-27 04:47:59  50.14     8.44    -15.56
289  2024-09-27 04:49:01  49.74     8.40    -15.56
290  2024-09-27 04:49:58  49.33     8.35    -15.56
291  2024-09-27 04:50:59  48.91     8.32    -15.56
292  2024-09-27 04:52:01  48.48     8.47    -15.56
293  2024-09-27 04:52:58  48.04     7.91    -15.56
294  2024-09-27 04:54:00  47.58     8.32    -15.56
295  2024-09-27 04:55:01  47.12     8.20    -15.56
296  2024-09-27 04:55:58  46.65     8.19    -15.56
297  2024-09-27 04:57:00  46.17     8.08    -15.56
298  2024-09-27 04:58:01  45.68     8.50    -15.56
299  2024-09-27 04:58:58  45.18     8.11    -15.56
300  2024-09-27 05:00:00  44.67     8.01    -15.56
301  2024-09-27 05:01:01  44.16     8.05    -15.56
302  2024-09-27 05:01:58  43.63     8.22    -15.56
303  2024-09-27 05:02:59  43.09     8.20    -15.56
304  2024-09-27 05:04:01  42.55     8.17    -15.56
305  2024-09-27 05:04:58  42.00     8.42    -15.56
306  2024-09-27 05:05:59  41.44     8.11    -15.56
307  2024-09-27 05:07:01  40.88     7.97    -15.56
308  2024-09-27 05:07:58  40.31     7.67    -15.56
309  2024-09-27 05:09:00  39.73     7.98    -15.56
310  2024-09-27 05:10:01  39.15     7.74    -15.56
311  2024-09-27 05:10:58  38.56     7.39    -15.56
312  2024-09-27 05:12:00  37.97     7.30    -15.56
313  2024-09-27 05:13:01  37.37     7.35    -15.56
314  2024-09-27 05:13:58  36.77     6.97    -15.56
315  2024-09-27 05:15:00  36.17     6.98    -15.56
316  2024-09-27 05:16:01  35.57     6.66    -15.56
317  2024-09-27 05:16:58  34.96     6.32    -15.56
318  2024-09-27 05:17:59  34.36     6.39    -15.56
319  2024-09-27 05:19:01  33.76     6.38    -15.56
320  2024-09-27 05:19:58  33.15     5.99    -15.56
321  2024-09-27 05:20:59  32.55     5.70    -15.56
322  2024-09-27 05:22:01  31.95     5.68    -15.56
323  2024-09-27 05:22:58  31.36     5.77    -15.56
324  2024-09-27 05:24:00  30.77     5.32    -15.56
325  2024-09-27 05:25:01  30.18     5.41    -15.56
326  2024-09-27 05:25:58  29.60     5.13    -15.56
327  2024-09-27 05:27:00  29.02     4.85    -15.56
328  2024-09-27 05:28:01  28.45     4.95    -15.56
329  2024-09-27 05:28:58  27.89     4.54    -15.56
330  2024-09-27 05:30:00  27.34     4.63    -15.56
331  2024-09-27 05:31:01  26.79     4.68    -15.56
332  2024-09-27 05:31:58  26.26     4.54    -15.56
333  2024-09-27 05:32:59  25.73     4.23    -15.56
334  2024-09-27 05:34:01  25.22     4.41    -15.56
335  2024-09-27 05:34:58  24.71     4.12    -15.56
336  2024-09-27 05:35:59  24.22     3.98    -15.56
337  2024-09-27 05:37:01  23.74     3.84    -15.56
338  2024-09-27 05:37:58  23.27     3.72    -15.56
339  2024-09-27 05:39:00  22.81     3.59    -15.56
340  2024-09-27 05:40:01  22.36     3.58    -15.56
341  2024-09-27 05:40:58  21.93     3.42    -15.56
342  2024-09-27 05:42:00  21.50     3.32    -15.56
343  2024-09-27 05:43:01  21.10     3.26    -15.56
344  2024-09-27 05:43:58  20.70     3.24    -15.56
345  2024-09-27 05:45:00  20.31     2.98    -15.56
346  2024-09-27 05:46:01  19.94     3.08    -15.56
347  2024-09-27 05:46:58  19.58     3.07    -15.56
348  2024-09-27 05:47:59  19.24     3.00    -15.56
349  2024-09-27 05:49:01  18.90     2.96    -15.56
350  2024-09-27 05:49:58  18.58     2.94    -15.56
351  2024-09-27 05:50:59  18.27     2.91    -15.56
352  2024-09-27 05:52:01  17.97     2.85    -15.56
353  2024-09-27 05:52:58  17.68     2.86    -15.56
354  2024-09-27 05:54:00  17.41     2.68    -15.56
355  2024-09-27 05:55:01  17.14     2.73    -15.56
356  2024-09-27 05:55:58  16.88     2.69    -15.56
357  2024-09-27 05:57:00  16.64     2.67    -15.56
358  2024-09-27 05:58:01  16.40     2.68    -15.56
359  2024-09-27 05:58:58  16.18     2.69    -15.56
360  2024-09-27 06:00:00  15.96     2.71    -15.56
361  2024-09-27 06:01:01  15.75     2.72    -15.56
362  2024-09-27 06:01:58  15.55     2.74    -15.56
363  2024-09-27 06:02:59  15.35     2.76    -15.56
364  2024-09-27 06:04:01  15.17     2.68    -15.56
365  2024-09-27 06:04:58  14.99     2.47    -15.56
366  2024-09-27 06:05:59  14.82     2.47    -15.56
367  2024-09-27 06:07:01  14.65     2.52    -15.56
368  2024-09-27 06:07:58  14.49     2.62    -15.56
369  2024-09-27 06:09:00  14.34     2.61    -15.56
370  2024-09-27 06:10:01  14.19     2.77    -15.56
371  2024-09-27 06:10:58  14.05     2.45    -15.56
372  2024-09-27 06:12:00  13.91     2.57    -15.56
373  2024-09-27 06:13:01  13.78     2.66    -15.56
374  2024-09-27 06:13:58  13.65     2.78    -15.56
375  2024-09-27 06:15:00  13.52     2.65    -15.56
376  2024-09-27 06:16:01  13.40     2.44    -15.56
377  2024-09-27 06:16:58  13.29     2.79    -15.56
378  2024-09-27 06:17:59  13.17     2.40    -15.56
379  2024-09-27 06:19:01  13.06     2.72    -15.56
380  2024-09-27 06:19:58  12.95     2.74    -15.56
381  2024-09-27 06:20:59  12.85     2.46    -15.56
382  2024-09-27 06:22:01  12.75     2.57    -15.56
383  2024-09-27 06:22:58  12.65     2.65    -15.56
384  2024-09-27 06:24:00  12.55     2.67    -15.56
385  2024-09-27 06:25:01  12.45     2.69    -15.56
386  2024-09-27 06:25:58  12.36     2.69    -15.56
387  2024-09-27 06:27:00  12.27     2.78    -15.56
388  2024-09-27 06:28:01  12.18     2.62    -15.56
389  2024-09-27 06:28:58  12.09     2.74    -15.56
390  2024-09-27 06:30:00  12.00     2.95    -15.56

In [ ]:
import pandas as pd
from datetime import time
import numpy as np

df['DATETIME'] = pd.to_datetime(df['DATETIME'])

target_times = [
    time(0, 50),
    time(1, 0),
    time(1, 10)
]

def find_closest_time(df, target_time):

    df_times = df['DATETIME'].dt.time


    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second


    df_seconds = (df['DATETIME'].dt.hour * 3600 +
                  df['DATETIME'].dt.minute * 60 +
                  df['DATETIME'].dt.second)


    time_diff = np.abs(df_seconds - target_seconds)


    closest_idx = time_diff.idxmin()

    return df.loc[[closest_idx]]

df_filtered_list = []
for target_time in target_times:
    closest_row = find_closest_time(df, target_time)
    df_filtered_list.append(closest_row)

df_filtered = pd.concat(df_filtered_list, ignore_index=True)

df_filtered = df_filtered.sort_values('DATETIME').reset_index(drop=True)

print("DataFrame filtered for closest times to 00:50, 01:00 and 01:10:")
print(df_filtered)

print("\nDifference from target times:")
for i, target_time in enumerate(target_times):
    actual_time = df_filtered.iloc[i]['DATETIME'].time()
    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second
    actual_seconds = actual_time.hour * 3600 + actual_time.minute * 60 + actual_time.second
    diff_seconds = abs(actual_seconds - target_seconds)
    print(f"Target: {target_time} | Actual: {actual_time} | Difference: {diff_seconds} seconds")

DataFrame filtered for closest times to 00:50, 01:00 and 01:10:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-09-27 00:49:58  73.90    11.18    -15.56
1 2024-09-27 01:00:00  73.87    10.38    -15.56
2 2024-09-27 01:10:01  74.22    10.51    -15.56

Difference from target times:
Target: 00:50:00 | Actual: 00:49:58 | Difference: 2 seconds
Target: 01:00:00 | Actual: 01:00:00 | Difference: 0 seconds
Target: 01:10:00 | Actual: 01:10:01 | Difference: 1 seconds

In [ ]:
reference_time = pd.Timestamp('2024-09-27 00:50:00')
wide_window = timedelta(minutes=5)
df_proximos = df[(df['DATETIME'] >= reference_time - wide_window) &
                 (df['DATETIME'] <= reference_time + wide_window)]
print("Records close to 00:50:")
print(df_proximos[['DATETIME', 'TEC']])

Records close to 00:50:
              DATETIME    TEC
45 2024-09-27 00:45:00  74.02
46 2024-09-27 00:46:01  73.99
47 2024-09-27 00:46:58  73.97
48 2024-09-27 00:48:00  73.94
49 2024-09-27 00:49:01  73.92
50 2024-09-27 00:49:58  73.90
51 2024-09-27 00:51:00  73.88
52 2024-09-27 00:52:01  73.86
53 2024-09-27 00:52:58  73.85
54 2024-09-27 00:54:00  73.84

In [ ]:
print(df.iloc[[50, 60, 70]][['DATETIME', 'TEC']])

              DATETIME    TEC
50 2024-09-27 00:49:58  73.90
60 2024-09-27 01:00:00  73.87
70 2024-09-27 01:10:01  74.22

In [ ]:
df.to_pickle('cuib271-2024-09-27_selected_0050_to_0110.pkl')

# TEC maps analysis

In [ ]:
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

## EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_embrace_maps_2024.columns

Index(['TECMAP'], dtype='object')

In [ ]:
class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
embrace_tec = Embrace()
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
date = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{date} {time}' for time in times]

result = df_embrace_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(3, 41, 25)

### 00:50

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  47.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  37.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  37.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  10.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  47.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  37.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  37.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  10.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.07 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x =   1.43 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.56 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y =   0.44 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 47.0 + 0.444845* 37.0 + 0.095163* 37.0 + 0.127207* 10.0
   Value =  15.6409 +  16.4593 +   3.5210 +   1.2721
   Value = 36.893258

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 36.8933
============================================================

### 01:00

In [ ]:
embrace_tec.tec_map = np_embrace_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  47.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  51.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  30.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  17.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  47.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  51.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  30.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  17.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.07 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x =   1.43 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.56 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y =   0.44 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 47.0 + 0.444845* 51.0 + 0.095163* 30.0 + 0.127207* 17.0
   Value =  15.6409 +  22.6871 +   2.8549 +   2.1625
   Value = 43.345396

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 43.3454
============================================================

### 01:10

In [ ]:
embrace_tec.tec_map = np_embrace_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  49.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  43.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  28.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  38.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  49.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  43.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  28.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  38.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.07 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x =   1.43 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.56 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y =   0.44 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 49.0 + 0.444845* 43.0 + 0.095163* 28.0 + 0.127207* 38.0
   Value =  16.3065 +  19.1283 +   2.6646 +   4.8339
   Value = 42.933233

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 42.9332
============================================================

## MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024['DATETIME'] = pd.to_datetime(df_maggia_maps_2024['DATETIME'])
df_maggia_maps_2024 = df_maggia_maps_2024.set_index('DATETIME')

In [ ]:
df_maggia_maps_2024.columns

Index(['TECMAP'], dtype='object')

In [ ]:
class Maggia(TecMap):

    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
maggia_tec = Maggia()
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526 , lon=-56.06987)

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
date = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{date} {time}' for time in times]

result = df_maggia_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.62400055, 48.20500183, 47.78499985, ..., 19.22900009,
         18.24799919, 16.43799973],
        [48.70800018, 48.36100006, 48.0019989 , ..., 18.61000061,
         17.57699966, 16.23500061],
        [48.7120018 , 48.42399979, 48.11700058, ..., 17.99799919,
         16.95499992, 16.04000092]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [43.38299942, 43.10300064, 43.09799957, ..., 19.18000031,
         18.25300026, 17.1609993 ],
        [43.85400009, 43.58499908, 43.34700012, ..., 18.40399933,
         17.62000084, 16.44000053],
        [44.19599915, 43.94599915, 43.70500183, ..., 17.70899963,
         16.94099998, 15.69099998]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.6230011 , 41.29999924, 41.13800049, ..., 18.74399948,
         18.67399979, 18.62999916],
        [42.11100006, 41.79499817, 41.5340004 , ..., 18.92099953,
         18.80699921, 17.86199951],
        [42.46699905, 42.18199921, 41.9280014 , ..., 18.2670002 ,
         17.5340004 , 16.79299927]]])

In [ ]:
np_maggia_maps.shape

(3, 241, 221)

### 00:50

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  75.9
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  75.9
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  75.9
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  75.9

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  75.9
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  75.9
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  75.9
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  75.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.07 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x =   0.43 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.56 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y =   0.44 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 75.9 + 0.095076* 75.9 + 0.124296* 75.9 + 0.765184* 75.9
   Value =   1.1728 +   7.2197 +   9.4385 +  58.1050
   Value = 75.935997

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 75.9360
============================================================

### 01:00

In [ ]:
maggia_tec.tec_map = np_maggia_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC: 118.5
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC: 116.6
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC: 107.4
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC: 111.9

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) = 118.5
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) = 116.6
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) = 107.4
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) = 111.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.07 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x =   0.43 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.56 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y =   0.44 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444*118.5 + 0.095076*116.6 + 0.124296*107.4 + 0.765184*111.9
   Value =   1.8308 +  11.0838 +  13.3435 +  85.6417
   Value = 111.899783

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 111.8998
============================================================

### 01:10

In [ ]:
maggia_tec.tec_map = np_maggia_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  93.1
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  90.8
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  84.5
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  84.5

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  93.1
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  90.8
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  84.5
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  84.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.07 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x =   0.43 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.56 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y =   0.44 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 93.1 + 0.095076* 90.8 + 0.124296* 84.5 + 0.765184* 84.5
   Value =   1.4383 +   8.6297 +  10.5026 +  64.6558
   Value = 85.226315

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 85.2263
============================================================