# Gopi TEC Porto Alegre analysis - December/2024

In [1]:
#Download Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [2]:
!gdown '1dh3D-pEWKLsTx2gnk_NMhLW2jl2Kc9b-'

Downloading...
From (original): https://drive.google.com/uc?id=1dh3D-pEWKLsTx2gnk_NMhLW2jl2Kc9b-
From (redirected): https://drive.google.com/uc?id=1dh3D-pEWKLsTx2gnk_NMhLW2jl2Kc9b-&confirm=t&uuid=d6d76129-e77c-4c89-b4cc-ff0575655c65
To: /content/Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip
100% 46.5M/46.5M [00:01<00:00, 38.4MB/s]

In [3]:
%pwd

'/content'

In [4]:
!ls

Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip  sample_data

In [5]:
!unzip 'Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_POAL_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: poal271-2024-09-27.Bias
  inflating: poal271-2024-09-27.Cmn
  inflating: poal271-2024-09-27.Std
  inflating: poal271-2024-09-27_page0.png
  inflating: poal271-2024-09-27-wbias.png
  inflating: poal336-2024-12-01.Bias
  inflating: poal336-2024-12-01.Cmn
  inflating: poal336-2024-12-01.Std
  inflating: poal336-2024-12-01_page0.png
  inflating: poal336-2024-12-01-wbias.png
  inflating: poal337-2024-12-02.Bias
  inflating: poal337-2024-12-02.Cmn
  inflating: poal337-2024-12-02.Std
  inflating: poal337-2024-12-02_page0.png
  inflating: poal337-2024-12-02-wbias.png
  inflating: poal338-2024-12-03.Bias
  inflating: poal338-2024-12-03.Cmn
  inflating: poal338-2024-12-03.Std
  inflating: poal338-2024-12-03_page0.png
  inflating: poal338-2024-12-03-wbias.png
  inflating: poal339-2024-12-04.Bias
  inflating: poal339-2024-12-04.Cmn
  inflating: poal339-2024-12-04.Std
  inflating: poal339-2024-12-04_page0.png
  inflating: poal339-2024-12-04-wbias.png
  inflating: poal340-2024-12-05.Bias
  inflating: poal340-2024-12-05.Cmn
  inflating: poal340-2024-12-05.Std
  inflating: poal340-2024-12-05_page0.png
  inflating: poal340-2024-12-05-wbias.png
  inflating: poal341-2024-12-06.Bias
  inflating: poal341-2024-12-06.Cmn
  inflating: poal341-2024-12-06.Std
  inflating: poal341-2024-12-06_page0.png
  inflating: poal341-2024-12-06-wbias.png
  inflating: poal342-2024-12-07.Bias
  inflating: poal342-2024-12-07.Cmn
  inflating: poal342-2024-12-07.Std
  inflating: poal342-2024-12-07_page0.png
  inflating: poal342-2024-12-07-wbias.png
  inflating: poal343-2024-12-08.Bias
  inflating: poal343-2024-12-08.Cmn
  inflating: poal343-2024-12-08.Std
  inflating: poal343-2024-12-08_page0.png
  inflating: poal343-2024-12-08-wbias.png
  inflating: poal344-2024-12-09.Bias
  inflating: poal344-2024-12-09.Cmn
  inflating: poal344-2024-12-09.Std
  inflating: poal344-2024-12-09_page0.png
  inflating: poal344-2024-12-09-wbias.png
  inflating: poal345-2024-12-10.Bias
  inflating: poal345-2024-12-10.Cmn
  inflating: poal345-2024-12-10.Std
  inflating: poal345-2024-12-10_page0.png
  inflating: poal345-2024-12-10-wbias.png
  inflating: poal346-2024-12-11.Bias
  inflating: poal346-2024-12-11.Cmn
  inflating: poal346-2024-12-11.Std
  inflating: poal346-2024-12-11_page0.png
  inflating: poal346-2024-12-11-wbias.png
  inflating: poal347-2024-12-12.Bias
  inflating: poal347-2024-12-12.Cmn
  inflating: poal347-2024-12-12.Std
  inflating: poal347-2024-12-12_page0.png
  inflating: poal347-2024-12-12-wbias.png
  inflating: poal348-2024-12-13.Bias
  inflating: poal348-2024-12-13.Cmn
  inflating: poal348-2024-12-13.Std
  inflating: poal348-2024-12-13_page0.png
  inflating: poal348-2024-12-13-wbias.png
  inflating: poal349-2024-12-14.Bias
  inflating: poal349-2024-12-14.Cmn
  inflating: poal349-2024-12-14.Std
  inflating: poal349-2024-12-14_page0.png
  inflating: poal349-2024-12-14-wbias.png
  inflating: poal350-2024-12-15.Bias
  inflating: poal350-2024-12-15.Cmn
  inflating: poal350-2024-12-15.Std
  inflating: poal350-2024-12-15_page0.png
  inflating: poal350-2024-12-15-wbias.png
  inflating: poal351-2024-12-16.Bias
  inflating: poal351-2024-12-16.Cmn
  inflating: poal351-2024-12-16.Std
  inflating: poal351-2024-12-16_page0.png
  inflating: poal351-2024-12-16-wbias.png
  inflating: poal352-2024-12-17.Bias
  inflating: poal352-2024-12-17.Cmn
  inflating: poal352-2024-12-17.Std
  inflating: poal352-2024-12-17_page0.png
  inflating: poal352-2024-12-17-wbias.png
  inflating: poal353-2024-12-18.Bias
  inflating: poal353-2024-12-18.Cmn
  inflating: poal353-2024-12-18.Std
  inflating: poal353-2024-12-18_page0.png
  inflating: poal353-2024-12-18-wbias.png
  inflating: poal354-2024-12-19.Bias
  inflating: poal354-2024-12-19.Cmn
  inflating: poal354-2024-12-19.Std
  inflating: poal354-2024-12-19_page0.png
  inflating: poal354-2024-12-19-wbias.png
  inflating: poal355-2024-12-20.Bias
  inflating: poal355-2024-12-20.Cmn
  inflating: poal355-2024-12-20.Std
  inflating: poal355-2024-12-20_page0.png
  inflating: poal355-2024-12-20-wbias.png
  inflating: poal356-2024-12-21.Bias
  inflating: poal356-2024-12-21.Cmn
  inflating: poal356-2024-12-21.Std
  inflating: poal356-2024-12-21_page0.png
  inflating: poal356-2024-12-21-wbias.png
  inflating: poal357-2024-12-22.Bias
  inflating: poal357-2024-12-22.Cmn
  inflating: poal357-2024-12-22.Std
  inflating: poal357-2024-12-22_page0.png
  inflating: poal357-2024-12-22-wbias.png
  inflating: poal358-2024-12-23.Bias
  inflating: poal358-2024-12-23.Cmn
  inflating: poal358-2024-12-23.Std
  inflating: poal358-2024-12-23_page0.png
  inflating: poal358-2024-12-23-wbias.png
  inflating: poal359-2024-12-24.Bias
  inflating: poal359-2024-12-24.Cmn
  inflating: poal359-2024-12-24.Std
  inflating: poal359-2024-12-24_page0.png
  inflating: poal359-2024-12-24-wbias.png
  inflating: poal360-2024-12-25.Bias
  inflating: poal360-2024-12-25.Cmn
  inflating: poal360-2024-12-25.Std
  inflating: poal360-2024-12-25_page0.png
  inflating: poal360-2024-12-25-wbias.png
  inflating: poal361-2024-12-26.Bias
  inflating: poal361-2024-12-26.Cmn
  inflating: poal361-2024-12-26.Std
  inflating: poal361-2024-12-26_page0.png
  inflating: poal361-2024-12-26-wbias.png
  inflating: poal362-2024-12-27.Bias
  inflating: poal362-2024-12-27.Cmn
  inflating: poal362-2024-12-27.Std
  inflating: poal362-2024-12-27_page0.png
  inflating: poal362-2024-12-27-wbias.png
  inflating: poal363-2024-12-28.Bias
  inflating: poal363-2024-12-28.Cmn
  inflating: poal363-2024-12-28.Std
  inflating: poal363-2024-12-28_page0.png
  inflating: poal363-2024-12-28-wbias.png
  inflating: poal364-2024-12-29.Bias
  inflating: poal364-2024-12-29.Cmn
  inflating: poal364-2024-12-29.Std
  inflating: poal364-2024-12-29_page0.png
  inflating: poal364-2024-12-29-wbias.png
  inflating: poal365-2024-12-30.Bias
  inflating: poal365-2024-12-30.Cmn
  inflating: poal365-2024-12-30.Std
  inflating: poal365-2024-12-30_page0.png
  inflating: poal365-2024-12-30-wbias.png
  inflating: poal366-2024-12-31.Bias
  inflating: poal366-2024-12-31.Cmn
  inflating: poal366-2024-12-31.Std
  inflating: poal366-2024-12-31_page0.png
  inflating: poal366-2024-12-31-wbias.png

In [6]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta
import glob

data_dir = '.'

std_files = glob.glob(os.path.join(data_dir, 'poal3*-2024-12-*.Std'))

std_files.sort()

dfs = []

for file_path in std_files:
    try:

        filename = os.path.basename(file_path)
        print(f"Processing {filename}")

        date_parts = filename.replace('.Std', '').split('-')
        year = int(date_parts[1])
        month = int(date_parts[2])
        day = int(date_parts[3])
        base_date = datetime(year, month, day)

        df = pd.read_csv(file_path, sep='\s+', header=None)

        df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

        def decimal_to_time(decimal_hours):
            hours = int(decimal_hours)
            minutes = int((decimal_hours - hours) * 60)
            seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
            return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

        df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

        df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
        df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

        df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
        df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

        dfs.append(df)

    except Exception as e:
        print(f"Error processing file {file_path}: {e}")

if dfs:
    combined_df = pd.concat(dfs, ignore_index=True)

    combined_df = combined_df.sort_values('DATETIME')

    combined_df.to_pickle('poal_dec_2024_complete.pkl')

    print(f"Combined DataFrame created with {len(combined_df)} rows")
    print("First 5 lines:")
    print(combined_df.head())

    print("\nPeriod covered by data:")
    print(f"Start: {combined_df['DATETIME'].min()}")
    print(f"End: {combined_df['DATETIME'].max()}")
    print(f"Total days: {(combined_df['DATETIME'].max() - combined_df['DATETIME'].min()).days + 1}")

    present_days = combined_df['DATETIME'].dt.date.unique()
    print(f"\nTotal days with data: {len(present_days)}")
    print("Present days:", sorted(present_days))
else:
    print("No files were successfully processed.")

<>:27: SyntaxWarning: invalid escape sequence '\s'
<>:27: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2398406323.py:27: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(file_path, sep='\s+', header=None)

Processing poal336-2024-12-01.Std
Processing poal337-2024-12-02.Std
Processing poal338-2024-12-03.Std
Processing poal339-2024-12-04.Std
Processing poal340-2024-12-05.Std
Processing poal341-2024-12-06.Std
Processing poal342-2024-12-07.Std
Processing poal343-2024-12-08.Std
Processing poal344-2024-12-09.Std
Processing poal345-2024-12-10.Std
Processing poal346-2024-12-11.Std
Processing poal347-2024-12-12.Std
Processing poal348-2024-12-13.Std
Processing poal349-2024-12-14.Std
Processing poal350-2024-12-15.Std
Processing poal351-2024-12-16.Std
Processing poal352-2024-12-17.Std
Processing poal353-2024-12-18.Std
Processing poal354-2024-12-19.Std
Processing poal355-2024-12-20.Std
Processing poal356-2024-12-21.Std
Processing poal357-2024-12-22.Std
Processing poal358-2024-12-23.Std
Processing poal359-2024-12-24.Std
Processing poal360-2024-12-25.Std
Processing poal361-2024-12-26.Std
Processing poal362-2024-12-27.Std
Processing poal363-2024-12-28.Std
Processing poal364-2024-12-29.Std
Processing poal365-2024-12-30.Std
Processing poal366-2024-12-31.Std
Combined DataFrame created with 44640 rows
First 5 lines:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-12-01 00:00:00  36.54     9.03    -30.07
1 2024-12-01 00:01:01  36.66     7.96    -30.07
2 2024-12-01 00:01:58  36.79     6.47    -30.07
3 2024-12-01 00:03:00  36.93     6.96    -30.07
4 2024-12-01 00:04:01  37.07     6.56    -30.07

Period covered by data:
Start: 2024-12-01 00:00:00
End: 2024-12-31 23:58:58
Total days: 31

Total days with data: 31
Present days: [datetime.date(2024, 12, 1), datetime.date(2024, 12, 2), datetime.date(2024, 12, 3), datetime.date(2024, 12, 4), datetime.date(2024, 12, 5), datetime.date(2024, 12, 6), datetime.date(2024, 12, 7), datetime.date(2024, 12, 8), datetime.date(2024, 12, 9), datetime.date(2024, 12, 10), datetime.date(2024, 12, 11), datetime.date(2024, 12, 12), datetime.date(2024, 12, 13), datetime.date(2024, 12, 14), datetime.date(2024, 12, 15), datetime.date(2024, 12, 16), datetime.date(2024, 12, 17), datetime.date(2024, 12, 18), datetime.date(2024, 12, 19), datetime.date(2024, 12, 20), datetime.date(2024, 12, 21), datetime.date(2024, 12, 22), datetime.date(2024, 12, 23), datetime.date(2024, 12, 24), datetime.date(2024, 12, 25), datetime.date(2024, 12, 26), datetime.date(2024, 12, 27), datetime.date(2024, 12, 28), datetime.date(2024, 12, 29), datetime.date(2024, 12, 30), datetime.date(2024, 12, 31)]

In [7]:
combined_df

                 DATETIME    TEC  TEC_STD  LATITUDE
0     2024-12-01 00:00:00  36.54     9.03    -30.07
1     2024-12-01 00:01:01  36.66     7.96    -30.07
2     2024-12-01 00:01:58  36.79     6.47    -30.07
3     2024-12-01 00:03:00  36.93     6.96    -30.07
4     2024-12-01 00:04:01  37.07     6.56    -30.07
...                   ...    ...      ...       ...
44635 2024-12-31 23:55:01  20.87     2.35    -30.07
44636 2024-12-31 23:55:58  20.85     2.36    -30.07
44637 2024-12-31 23:56:59  20.82     2.38    -30.07
44638 2024-12-31 23:58:01  20.80     2.41    -30.07
44639 2024-12-31 23:58:58  20.78     2.65    -30.07

[44640 rows x 4 columns]

## SPECIFIC TIMES FOR 12/18

In [8]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('poal_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

print(f"Available columns in the DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):

    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):

    location_info = {}

    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):

    print(f"\n{'='*100}")
    print(f"ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES")
    print(f"(Maximum allowed difference: {max_minutes_diff} minutes)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"LOOKING FOR VALUES NEAR: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f" VALUE FOUND:")
            print(f" Actual Date/Time: {closest_row['DATETIME']}")
            print(f" Target Date/Time: {target_dt}")
            print(f" Difference: {time_diff:.2f} minutes")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  HAS a sequence of 3 high values ​​(≥90% of the peak):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f" {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% of value)")
            else:
                print(f"  does NOT have a sequence of 3 consecutive high values")

            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f" NO VALUE FOUND within {max_minutes_diff} minutes of target time")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    print(f"\n{'='*120}")
    print(f"RESULTS SUMMARY TABLE")
    print(f"{'='*120}")

    header = f"{'#':<3}{'Target Time':<20}{'Found Time':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<12}"

    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Yes" if result['has_sequence'] else "No"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NOT FOUND':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

target_datetimes = [
    "2024-12-18 18:20:00",
    "2024-12-18 18:10:00",
    "2024-12-18 18:30:00",
    "2024-12-18 18:00:00"
]

print("\n\n" + "*"*50 + " ANALYSIS OF SPECIFIC TIMES " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnalysis complete!")

found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"STATISTICS OF THE RESULTS FOUND")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"TEC values ​​found:")
    print(f" Minimum: {min(tec_values):.2f} TECU")
    print(f" Maximum: {max(tec_values):.2f} TECU")
    print(f" Mean: {np.mean(tec_values):.2f} TECU")
    print(f" Standard deviation: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nHigh value sequences found: {sequences_found} out of {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Available columns in the DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANALYSIS OF SPECIFIC TIMES **************************************************

====================================================================================================
ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES
(Maximum allowed difference: 2 minutes)
====================================================================================================

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:20:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:19:58
 Target Date/Time: 2024-12-18 18:20:00
 Difference: 0.03 minutes
  TEC: 56.66 ± 6.22 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 18:19:01: 56.75 ± 6.08 TECU (100.2% of value)
 2. 2024-12-18 18:19:58: 56.66 ± 6.22 TECU (100.0% of value)
 3. 2024-12-18 18:21:00: 56.58 ± 6.30 TECU (99.9% of value)

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:10:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:10:01
 Target Date/Time: 2024-12-18 18:10:00
 Difference: 0.02 minutes
  TEC: 57.57 ± 5.61 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 18:08:59: 57.66 ± 5.72 TECU (100.2% of value)
 2. 2024-12-18 18:10:01: 57.57 ± 5.61 TECU (100.0% of value)
 3. 2024-12-18 18:10:58: 57.48 ± 5.79 TECU (99.8% of value)

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:30:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:30:00
 Target Date/Time: 2024-12-18 18:30:00
 Difference: 0.00 minutes
  TEC: 55.93 ± 4.65 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 18:28:58: 55.99 ± 4.63 TECU (100.1% of value)
 2. 2024-12-18 18:30:00: 55.93 ± 4.65 TECU (100.0% of value)
 3. 2024-12-18 18:31:01: 55.87 ± 4.73 TECU (99.9% of value)

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:00:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:00:00
 Target Date/Time: 2024-12-18 18:00:00
 Difference: 0.00 minutes
  TEC: 58.40 ± 4.98 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 17:58:58: 58.46 ± 4.93 TECU (100.1% of value)
 2. 2024-12-18 18:00:00: 58.40 ± 4.98 TECU (100.0% of value)
 3. 2024-12-18 18:01:01: 58.32 ± 5.06 TECU (99.9% of value)

========================================================================================================================
RESULTS SUMMARY TABLE
========================================================================================================================
#  Target Time         Found Time          Diff(min) TEC       TEC_STD   Sequence    LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    56.66    6.22    Yes         -30.07
2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    57.57    5.61    Yes         -30.07
3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    55.93    4.65    Yes         -30.07
4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    58.40    4.98    Yes         -30.07
-------------------------------------------------------------------------------------------------

Analysis complete!

================================================================================
STATISTICS OF THE RESULTS FOUND
================================================================================
TEC values ​​found:
 Minimum: 55.93 TECU
 Maximum: 58.40 TECU
 Mean: 57.14 TECU
 Standard deviation: 0.93 TECU

High value sequences found: 4 out of 4 (100.0%)

## 12/01 - 18:00

In [9]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('poal_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

print(f"Available columns in the DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):

    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):

    location_info = {}

    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):

    print(f"\n{'='*100}")
    print(f"ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES")
    print(f"(Maximum allowed difference: {max_minutes_diff} minutes)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"LOOKING FOR VALUES NEAR: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f" VALUE FOUND:")
            print(f" Actual Date/Time: {closest_row['DATETIME']}")
            print(f" Target Date/Time: {target_dt}")
            print(f" Difference: {time_diff:.2f} minutes")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  HAS a sequence of 3 high values ​​(≥90% of the peak):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f" {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% of value)")
            else:
                print(f"  does NOT have a sequence of 3 consecutive high values")

            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f" NO VALUE FOUND within {max_minutes_diff} minutes of target time")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    print(f"\n{'='*120}")
    print(f"RESULTS SUMMARY TABLE")
    print(f"{'='*120}")

    header = f"{'#':<3}{'Target Time':<20}{'Found Time':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<12}"

    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Yes" if result['has_sequence'] else "No"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NOT FOUND':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

target_datetimes = [
    "2024-12-01 18:00:00"
]

print("\n\n" + "*"*50 + " ANALYSIS OF SPECIFIC TIMES " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnalysis complete!")

found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"STATISTICS OF THE RESULTS FOUND")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"TEC values ​​found:")
    print(f" Minimum: {min(tec_values):.2f} TECU")
    print(f" Maximum: {max(tec_values):.2f} TECU")
    print(f" Mean: {np.mean(tec_values):.2f} TECU")
    print(f" Standard deviation: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nHigh value sequences found: {sequences_found} out of {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Available columns in the DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANALYSIS OF SPECIFIC TIMES **************************************************

====================================================================================================
ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES
(Maximum allowed difference: 2 minutes)
====================================================================================================

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-01 18:00:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-01 18:00:00
 Target Date/Time: 2024-12-01 18:00:00
 Difference: 0.00 minutes
  TEC: 59.27 ± 4.33 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-01 17:58:58: 59.40 ± 4.34 TECU (100.2% of value)
 2. 2024-12-01 18:00:00: 59.27 ± 4.33 TECU (100.0% of value)
 3. 2024-12-01 18:01:01: 59.15 ± 4.31 TECU (99.8% of value)

========================================================================================================================
RESULTS SUMMARY TABLE
========================================================================================================================
#  Target Time         Found Time          Diff(min) TEC       TEC_STD   Sequence    LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-01 18:00:00 2024-12-01 18:00:00 0.00    59.27    4.33    Yes         -30.07
-------------------------------------------------------------------------------------------------

Analysis complete!

================================================================================
STATISTICS OF THE RESULTS FOUND
================================================================================
TEC values ​​found:
 Minimum: 59.27 TECU
 Maximum: 59.27 TECU
 Mean: 59.27 TECU
 Standard deviation: 0.00 TECU

High value sequences found: 1 out of 1 (100.0%)

## 12/18 - 18:00

In [10]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('poal_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

print(f"Available columns in the DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):

    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):

    location_info = {}

    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):

    print(f"\n{'='*100}")
    print(f"ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES")
    print(f"(Maximum allowed difference: {max_minutes_diff} minutes)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"LOOKING FOR VALUES NEAR: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f" VALUE FOUND:")
            print(f" Actual Date/Time: {closest_row['DATETIME']}")
            print(f" Target Date/Time: {target_dt}")
            print(f" Difference: {time_diff:.2f} minutes")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  HAS a sequence of 3 high values ​​(≥90% of the peak):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f" {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% of value)")
            else:
                print(f"  does NOT have a sequence of 3 consecutive high values")

            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f" NO VALUE FOUND within {max_minutes_diff} minutes of target time")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    print(f"\n{'='*120}")
    print(f"RESULTS SUMMARY TABLE")
    print(f"{'='*120}")

    header = f"{'#':<3}{'Target Time':<20}{'Found Time':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<12}"

    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Yes" if result['has_sequence'] else "No"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NOT FOUND':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

target_datetimes = [
    "2024-12-18 18:00:00"
]

print("\n\n" + "*"*50 + " ANALYSIS OF SPECIFIC TIMES " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnalysis complete!")

found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"STATISTICS OF THE RESULTS FOUND")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"TEC values ​​found:")
    print(f" Minimum: {min(tec_values):.2f} TECU")
    print(f" Maximum: {max(tec_values):.2f} TECU")
    print(f" Mean: {np.mean(tec_values):.2f} TECU")
    print(f" Standard deviation: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nHigh value sequences found: {sequences_found} out of {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Available columns in the DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANALYSIS OF SPECIFIC TIMES **************************************************

====================================================================================================
ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES
(Maximum allowed difference: 2 minutes)
====================================================================================================

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:00:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:00:00
 Target Date/Time: 2024-12-18 18:00:00
 Difference: 0.00 minutes
  TEC: 58.40 ± 4.98 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 17:58:58: 58.46 ± 4.93 TECU (100.1% of value)
 2. 2024-12-18 18:00:00: 58.40 ± 4.98 TECU (100.0% of value)
 3. 2024-12-18 18:01:01: 58.32 ± 5.06 TECU (99.9% of value)

========================================================================================================================
RESULTS SUMMARY TABLE
========================================================================================================================
#  Target Time         Found Time          Diff(min) TEC       TEC_STD   Sequence    LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    58.40    4.98    Yes         -30.07
-------------------------------------------------------------------------------------------------

Analysis complete!

================================================================================
STATISTICS OF THE RESULTS FOUND
================================================================================
TEC values ​​found:
 Minimum: 58.40 TECU
 Maximum: 58.40 TECU
 Mean: 58.40 TECU
 Standard deviation: 0.00 TECU

High value sequences found: 1 out of 1 (100.0%)

## 12/19 - 18:00

In [11]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('poal_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

print(f"Available columns in the DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):

    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):

    location_info = {}

    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):

    print(f"\n{'='*100}")
    print(f"ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES")
    print(f"(Maximum allowed difference: {max_minutes_diff} minutes)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"LOOKING FOR VALUES NEAR: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f" VALUE FOUND:")
            print(f" Actual Date/Time: {closest_row['DATETIME']}")
            print(f" Target Date/Time: {target_dt}")
            print(f" Difference: {time_diff:.2f} minutes")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  HAS a sequence of 3 high values ​​(≥90% of the peak):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f" {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% of value)")
            else:
                print(f"  does NOT have a sequence of 3 consecutive high values")

            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f" NO VALUE FOUND within {max_minutes_diff} minutes of target time")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    print(f"\n{'='*120}")
    print(f"RESULTS SUMMARY TABLE")
    print(f"{'='*120}")

    header = f"{'#':<3}{'Target Time':<20}{'Found Time':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<12}"

    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Yes" if result['has_sequence'] else "No"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NOT FOUND':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

target_datetimes = [
    "2024-12-19 18:00:00"
]

print("\n\n" + "*"*50 + " ANALYSIS OF SPECIFIC TIMES " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnalysis complete!")

found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"STATISTICS OF THE RESULTS FOUND")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"TEC values ​​found:")
    print(f" Minimum: {min(tec_values):.2f} TECU")
    print(f" Maximum: {max(tec_values):.2f} TECU")
    print(f" Mean: {np.mean(tec_values):.2f} TECU")
    print(f" Standard deviation: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nHigh value sequences found: {sequences_found} out of {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Available columns in the DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANALYSIS OF SPECIFIC TIMES **************************************************

====================================================================================================
ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES
(Maximum allowed difference: 2 minutes)
====================================================================================================

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-19 18:00:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-19 18:00:00
 Target Date/Time: 2024-12-19 18:00:00
 Difference: 0.00 minutes
  TEC: 61.57 ± 3.62 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-19 17:58:58: 61.68 ± 3.60 TECU (100.2% of value)
 2. 2024-12-19 18:00:00: 61.57 ± 3.62 TECU (100.0% of value)
 3. 2024-12-19 18:01:01: 61.46 ± 3.70 TECU (99.8% of value)

========================================================================================================================
RESULTS SUMMARY TABLE
========================================================================================================================
#  Target Time         Found Time          Diff(min) TEC       TEC_STD   Sequence    LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-19 18:00:00 2024-12-19 18:00:00 0.00    61.57    3.62    Yes         -30.07
-------------------------------------------------------------------------------------------------

Analysis complete!

================================================================================
STATISTICS OF THE RESULTS FOUND
================================================================================
TEC values ​​found:
 Minimum: 61.57 TECU
 Maximum: 61.57 TECU
 Mean: 61.57 TECU
 Standard deviation: 0.00 TECU

High value sequences found: 1 out of 1 (100.0%)

## 12/22 - 18:00

In [12]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('poal_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

print(f"Available columns in the DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):

    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):

    location_info = {}

    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):

    print(f"\n{'='*100}")
    print(f"ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES")
    print(f"(Maximum allowed difference: {max_minutes_diff} minutes)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"LOOKING FOR VALUES NEAR: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f" VALUE FOUND:")
            print(f" Actual Date/Time: {closest_row['DATETIME']}")
            print(f" Target Date/Time: {target_dt}")
            print(f" Difference: {time_diff:.2f} minutes")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  HAS a sequence of 3 high values ​​(≥90% of the peak):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f" {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% of value)")
            else:
                print(f"  does NOT have a sequence of 3 consecutive high values")

            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f" NO VALUE FOUND within {max_minutes_diff} minutes of target time")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    print(f"\n{'='*120}")
    print(f"RESULTS SUMMARY TABLE")
    print(f"{'='*120}")

    header = f"{'#':<3}{'Target Time':<20}{'Found Time':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<12}"

    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Yes" if result['has_sequence'] else "No"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NOT FOUND':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

target_datetimes = [
    "2024-12-22 18:00:00"
]

print("\n\n" + "*"*50 + " ANALYSIS OF SPECIFIC TIMES " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnalysis complete!")

found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"STATISTICS OF THE RESULTS FOUND")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"TEC values ​​found:")
    print(f" Minimum: {min(tec_values):.2f} TECU")
    print(f" Maximum: {max(tec_values):.2f} TECU")
    print(f" Mean: {np.mean(tec_values):.2f} TECU")
    print(f" Standard deviation: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nHigh value sequences found: {sequences_found} out of {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Available columns in the DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44640 points after removing missing values


************************************************** ANALYSIS OF SPECIFIC TIMES **************************************************

====================================================================================================
ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES
(Maximum allowed difference: 2 minutes)
====================================================================================================

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-22 18:00:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-22 18:00:00
 Target Date/Time: 2024-12-22 18:00:00
 Difference: 0.00 minutes
  TEC: 60.67 ± 5.03 TECU
  LATITUDE: -30.07
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-22 17:58:58: 60.88 ± 4.78 TECU (100.3% of value)
 2. 2024-12-22 18:00:00: 60.67 ± 5.03 TECU (100.0% of value)
 3. 2024-12-22 18:01:01: 60.47 ± 4.98 TECU (99.7% of value)

========================================================================================================================
RESULTS SUMMARY TABLE
========================================================================================================================
#  Target Time         Found Time          Diff(min) TEC       TEC_STD   Sequence    LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-22 18:00:00 2024-12-22 18:00:00 0.00    60.67    5.03    Yes         -30.07
-------------------------------------------------------------------------------------------------

Analysis complete!

================================================================================
STATISTICS OF THE RESULTS FOUND
================================================================================
TEC values ​​found:
 Minimum: 60.67 TECU
 Maximum: 60.67 TECU
 Mean: 60.67 TECU
 Standard deviation: 0.00 TECU

High value sequences found: 1 out of 1 (100.0%)

# TEC maps analysis

In [13]:
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

## EMBRACE

In [14]:
import pandas as pd
import numpy as np

In [15]:
#Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [16]:
!gdown '1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH'

Downloading...
From (original): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH
From (redirected): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH&confirm=t&uuid=215e0216-ef88-4241-913f-56a2efe44f3b
To: /content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl
100% 157M/157M [00:04<00:00, 37.2MB/s]

In [17]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [18]:
df_embrace_maps_2024

                                                                TECMAP
DATETIME
2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[16704 rows x 1 columns]

In [19]:
class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)

In [20]:
embrace_tec = Embrace()
embrace_points = embrace_tec.find_nearest_points(lat=-30.07404, lon=-51.11976)

In [21]:
embrace_points

[(-32, -52.5, 14, 15),
 (-32, -50.0, 14, 16),
 (-30, -52.5, 15, 15),
 (-30, -50.0, 15, 16)]

### 12/01 - 18:00

In [22]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [23]:
result

                                                                TECMAP
DATETIME
2024-12-01 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [24]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [25]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [26]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 46., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [27]:
np_embrace_maps.shape

(1, 41, 25)

In [28]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  72.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  71.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  76.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  74.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  72.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  71.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  76.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  74.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x = 1.38024 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y = 1.92596 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 72.0 + 0.020439* 71.0 + 0.431323* 76.0 + 0.531657* 74.0
   Value =   1.1939 +   1.4511 +  32.7805 +  39.3426
   Value = 74.768167

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 74.7682
============================================================

### 12/18 - 18:00

In [29]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [30]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [31]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [32]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [33]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [34]:
np_embrace_maps.shape

(1, 41, 25)

In [35]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  72.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  71.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  76.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  76.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  72.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  71.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  76.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x = 1.38024 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y = 1.92596 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 72.0 + 0.020439* 71.0 + 0.431323* 76.0 + 0.531657* 76.0
   Value =   1.1939 +   1.4511 +  32.7805 +  40.4060
   Value = 75.831481

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 75.8315
============================================================

### 12/18 - 18:10

In [36]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [37]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [38]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [39]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [40]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 37., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [41]:
np_embrace_maps.shape

(1, 41, 25)

In [42]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  73.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  69.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  76.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  77.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  73.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  69.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  76.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  77.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x = 1.38024 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y = 1.92596 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 73.0 + 0.020439* 69.0 + 0.431323* 76.0 + 0.531657* 77.0
   Value =   1.2104 +   1.4103 +  32.7805 +  40.9376
   Value = 76.338843

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 76.3388
============================================================

### 12/18 - 18:20

In [43]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [44]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [45]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [46]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [47]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [48]:
np_embrace_maps.shape

(1, 41, 25)

In [49]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  72.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  68.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  79.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  77.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  72.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  68.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  79.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  77.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x = 1.38024 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y = 1.92596 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 72.0 + 0.020439* 68.0 + 0.431323* 79.0 + 0.531657* 77.0
   Value =   1.1939 +   1.3898 +  34.0745 +  40.9376
   Value = 77.595791

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 77.5958
============================================================

### 12/18 - 18:30

In [50]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [51]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [52]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [53]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [54]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [55]:
np_embrace_maps.shape

(1, 41, 25)

In [56]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  72.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  66.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  74.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  75.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  72.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  66.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  74.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  75.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x = 1.38024 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y = 1.92596 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 72.0 + 0.020439* 66.0 + 0.431323* 74.0 + 0.531657* 75.0
   Value =   1.1939 +   1.3489 +  31.9179 +  39.8743
   Value = 74.334986

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 74.3350
============================================================

### 12/19 - 18:00

In [57]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [58]:
result

                                                                TECMAP
DATETIME
2024-12-19 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [59]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [60]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [61]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 41., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [62]:
np_embrace_maps.shape

(1, 41, 25)

In [63]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  73.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  72.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  75.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  72.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  73.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  72.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  75.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  72.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x = 1.38024 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y = 1.92596 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 73.0 + 0.020439* 72.0 + 0.431323* 75.0 + 0.531657* 72.0
   Value =   1.2104 +   1.4716 +  32.3492 +  38.2793
   Value = 73.310549

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 73.3105
============================================================

### 12/22 - 18:00

In [64]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [65]:
result

                                                                TECMAP
DATETIME
2024-12-22 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [66]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [67]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [68]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 52., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [69]:
np_embrace_maps.shape

(1, 41, 25)

In [70]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -32.0°,  -52.5°) - Indexes: [14, 15] - TEC:  71.0
   P2: ( -32.0°,  -50.0°) - Indexes: [14, 16] - TEC:  67.0
   P3: ( -30.0°,  -52.5°) - Indexes: [15, 15] - TEC:  76.0
   P4: ( -30.0°,  -50.0°) - Indexes: [15, 16] - TEC:  76.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.0° to  -30.0° (range:  2.0°)
   Longitude:  -52.5° to  -50.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.0°,  -52.5°) =  71.0
   f_01 (lat_min, lon_max) = ( -32.0°,  -50.0°) =  67.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -52.5°) =  76.0
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -52.5)) / ( -50.0 - ( -52.5))
   t_x = 1.38024 /  2.5 = 0.552096

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.0)) / ( -30.0 - ( -32.0))
   t_y = 1.92596 /  2.0 = 0.962980

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.552096) * (1 - 0.962980) = 0.016581
   w_01 = t_x * (1 - t_y)       = 0.552096 * (1 - 0.962980)       = 0.020439
   w_10 = (1 - t_x) * t_y       = (1 - 0.552096) * 0.962980       = 0.431323
   w_11 = t_x * t_y             = 0.552096 * 0.962980             = 0.531657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.016581* 71.0 + 0.020439* 67.0 + 0.431323* 76.0 + 0.531657* 76.0
   Value =   1.1773 +   1.3694 +  32.7805 +  40.4060
   Value = 75.733146

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 55.21% of the way from -52.5° to -50.0°
   In Y direction (latitude):  96.30% of the way from -32° to -30°

============================================================
FINAL RESULT: TEC = 75.7331
============================================================

## IGS

In [71]:
import pandas as pd
import numpy as np

In [72]:
#Download TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [73]:
!gdown '1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp'

Downloading...
From: https://drive.google.com/uc?id=1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp
To: /content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl
100% 3.60M/3.60M [00:00<00:00, 246MB/s]

In [74]:
df_igs_maps_2024 = pd.read_pickle('/content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [75]:
df_igs_maps_2024

               DATETIME                                             TECMAP
0   2024-12-01 00:00:00  [[37.7, 34.6, 31.9, 30.0, 28.6, 27.2, 25.8, 24...
1   2024-12-01 02:00:00  [[20.3, 18.7, 18.1, 18.2, 18.2, 18.1, 17.7, 17...
2   2024-12-01 04:00:00  [[11.6, 11.8, 12.0, 12.4, 13.0, 13.5, 14.0, 14...
3   2024-12-01 06:00:00  [[10.4, 10.8, 11.1, 11.7, 12.1, 12.7, 13.3, 13...
4   2024-12-01 08:00:00  [[9.9, 10.1, 10.3, 10.6, 11.0, 11.6, 12.3, 13....
..                  ...                                                ...
343 2024-12-30 14:00:00  [[8.9, 11.1, 14.4, 18.8, 23.7, 28.3, 32.7, 36....
344 2024-12-30 16:00:00  [[26.3, 29.8, 33.4, 37.1, 40.5, 43.7, 47.0, 49...
345 2024-12-30 18:00:00  [[43.5, 44.5, 45.3, 46.2, 47.1, 48.6, 50.0, 51...
346 2024-12-30 20:00:00  [[48.8, 49.1, 49.0, 48.7, 48.5, 48.1, 48.0, 47...
347 2024-12-30 22:00:00  [[47.0, 46.6, 45.6, 44.4, 43.2, 42.0, 40.4, 38...

[348 rows x 2 columns]

In [76]:
class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),  # (lon_min, lon_max, lat_min_geo, lat_max_geo)
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        """
        IGS TEC Map - Specific implementation for IGS data structure.

        IMPORTANT: IGS arrays are organized North to South:
        - Array[0, :] contains the NORTHERNMOST latitudes (+40°)
        - Array[-1, :] contains the SOUTHERNMOST latitudes (-80°)

        The extent parameter follows GEOGRAPHIC convention:
        - extent = (lon_min, lon_max, lat_min_geographic, lat_max_geographic)
        - lat_min_geographic = -80° (southernmost point)
        - lat_max_geographic = +40° (northernmost point)

        This differs from array indexing where Array[0] = +40° (North).
        The find_nearest_points method handles this coordinate conversion.
        """
        super().__init__(extent, lat_step, lon_step)

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat_max - lat) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_max - lat_idx_lower * lat_step
        lat_upper = lat_max - lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

In [77]:
igs_tec = Igs()
igs_points = igs_tec.find_nearest_points(lat=-30.07404, lon=-51.11976)

In [78]:
igs_points

[(-30.0, -55, 28, 11),
 (-30.0, -50, 28, 12),
 (-32.5, -55, 29, 11),
 (-32.5, -50, 29, 12)]

### 12/01 - 18:00

In [79]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [80]:
result

             DATETIME                                             TECMAP
9 2024-12-01 18:00:00  [[50.5, 53.3, 54.8, 55.0, 54.6, 54.1, 54.0, 54...

In [81]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [82]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [83]:
np_igs_maps

array([[[50.5, 53.3, 54.8, ..., 26.7, 24.5, 22.9],
        [50.2, 52.6, 54.1, ..., 30.3, 28.1, 26.2],
        [50.4, 52.2, 53.4, ..., 36.6, 34. , 31.8],
        ...,
        [30.4, 30.4, 30.2, ..., 23.1, 22.6, 22. ],
        [30.3, 30.3, 30.1, ..., 23.2, 22.9, 22.5],
        [29.4, 29.3, 29.2, ..., 23.3, 23.1, 22.8]]])

In [84]:
np_igs_maps.shape

(1, 49, 23)

In [85]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.0°,  -55.0°) - Indexes: [28, 11] - TEC:  82.6
   P2: ( -30.0°,  -50.0°) - Indexes: [28, 12] - TEC:  81.8
   P3: ( -32.5°,  -55.0°) - Indexes: [29, 11] - TEC:  78.4
   P4: ( -32.5°,  -50.0°) - Indexes: [29, 12] - TEC:  77.4

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.5° to  -30.0° (range:  2.5°)
   Longitude:  -55.0° to  -50.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.5°,  -55.0°) =  78.4
   f_01 (lat_min, lon_max) = ( -32.5°,  -50.0°) =  77.4
   f_10 (lat_max, lon_min) = ( -30.0°,  -55.0°) =  82.6
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  81.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -55.0)) / ( -50.0 - ( -55.0))
   t_x = 3.88024 /  5.0 = 0.776048

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.5)) / ( -30.0 - ( -32.5))
   t_y = 2.42596 /  2.5 = 0.970384

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.776048) * (1 - 0.970384) = 0.006633
   w_01 = t_x * (1 - t_y)       = 0.776048 * (1 - 0.970384)       = 0.022983
   w_10 = (1 - t_x) * t_y       = (1 - 0.776048) * 0.970384       = 0.217319
   w_11 = t_x * t_y             = 0.776048 * 0.970384             = 0.753065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.006633* 78.4 + 0.022983* 77.4 + 0.217319* 82.6 + 0.753065* 81.8
   Value =   0.5200 +   1.7789 +  17.9506 +  61.6007
   Value = 81.850178

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 77.60% of the way from -55° to -50°
   In Y direction (latitude):  97.04% of the way from -32.5° to -30.0°

============================================================
FINAL RESULT: TEC = 81.8502
============================================================

### 12/18 - 18:00

In [86]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:

    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [87]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [88]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [89]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [90]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [91]:
np_igs_maps.shape

(1, 49, 23)

In [92]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.0°,  -55.0°) - Indexes: [28, 11] - TEC:  76.7
   P2: ( -30.0°,  -50.0°) - Indexes: [28, 12] - TEC:  74.9
   P3: ( -32.5°,  -55.0°) - Indexes: [29, 11] - TEC:  73.2
   P4: ( -32.5°,  -50.0°) - Indexes: [29, 12] - TEC:  71.1

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.5° to  -30.0° (range:  2.5°)
   Longitude:  -55.0° to  -50.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.5°,  -55.0°) =  73.2
   f_01 (lat_min, lon_max) = ( -32.5°,  -50.0°) =  71.1
   f_10 (lat_max, lon_min) = ( -30.0°,  -55.0°) =  76.7
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  74.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -55.0)) / ( -50.0 - ( -55.0))
   t_x = 3.88024 /  5.0 = 0.776048

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.5)) / ( -30.0 - ( -32.5))
   t_y = 2.42596 /  2.5 = 0.970384

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.776048) * (1 - 0.970384) = 0.006633
   w_01 = t_x * (1 - t_y)       = 0.776048 * (1 - 0.970384)       = 0.022983
   w_10 = (1 - t_x) * t_y       = (1 - 0.776048) * 0.970384       = 0.217319
   w_11 = t_x * t_y             = 0.776048 * 0.970384             = 0.753065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.006633* 73.2 + 0.022983* 71.1 + 0.217319* 76.7 + 0.753065* 74.9
   Value =   0.4855 +   1.6341 +  16.6684 +  56.4045
   Value = 75.192563

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 77.60% of the way from -55° to -50°
   In Y direction (latitude):  97.04% of the way from -32.5° to -30.0°

============================================================
FINAL RESULT: TEC = 75.1926
============================================================

### 12/19 - 18:00

In [93]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [94]:
result

               DATETIME                                             TECMAP
213 2024-12-19 18:00:00  [[36.1, 39.3, 41.5, 42.6, 42.4, 41.2, 39.2, 37...

In [95]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [96]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [97]:
np_igs_maps

array([[[36.1, 39.3, 41.5, ..., 15. , 14.4, 14.1],
        [37.3, 40. , 42.4, ..., 17. , 16.5, 16.2],
        [38.2, 40.5, 42.6, ..., 20.6, 20.1, 19.7],
        ...,
        [23.4, 23.3, 23.2, ..., 23.6, 23.2, 22.9],
        [23.3, 23.2, 23.1, ..., 23.7, 23.5, 23.2],
        [23. , 23.1, 22.9, ..., 23.5, 23.6, 23.5]]])

In [98]:
np_igs_maps.shape

(1, 49, 23)

In [99]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.0°,  -55.0°) - Indexes: [28, 11] - TEC:  79.9
   P2: ( -30.0°,  -50.0°) - Indexes: [28, 12] - TEC:  77.8
   P3: ( -32.5°,  -55.0°) - Indexes: [29, 11] - TEC:  77.9
   P4: ( -32.5°,  -50.0°) - Indexes: [29, 12] - TEC:  75.5

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.5° to  -30.0° (range:  2.5°)
   Longitude:  -55.0° to  -50.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.5°,  -55.0°) =  77.9
   f_01 (lat_min, lon_max) = ( -32.5°,  -50.0°) =  75.5
   f_10 (lat_max, lon_min) = ( -30.0°,  -55.0°) =  79.9
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  77.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -55.0)) / ( -50.0 - ( -55.0))
   t_x = 3.88024 /  5.0 = 0.776048

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.5)) / ( -30.0 - ( -32.5))
   t_y = 2.42596 /  2.5 = 0.970384

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.776048) * (1 - 0.970384) = 0.006633
   w_01 = t_x * (1 - t_y)       = 0.776048 * (1 - 0.970384)       = 0.022983
   w_10 = (1 - t_x) * t_y       = (1 - 0.776048) * 0.970384       = 0.217319
   w_11 = t_x * t_y             = 0.776048 * 0.970384             = 0.753065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.006633* 77.9 + 0.022983* 75.5 + 0.217319* 79.9 + 0.753065* 77.8
   Value =   0.5167 +   1.7352 +  17.3638 +  58.5884
   Value = 78.204172

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 77.60% of the way from -55° to -50°
   In Y direction (latitude):  97.04% of the way from -32.5° to -30.0°

============================================================
FINAL RESULT: TEC = 78.2042
============================================================

### 12/22 - 18:00

In [100]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [101]:
result

               DATETIME                                             TECMAP
249 2024-12-22 18:00:00  [[48.9, 51.6, 53.7, 54.6, 54.9, 54.7, 54.6, 54...

In [102]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [103]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [104]:
np_igs_maps

array([[[48.9, 51.6, 53.7, ..., 23. , 21.7, 20.7],
        [49.6, 52. , 53.9, ..., 25.5, 24.4, 23. ],
        [50.2, 52.1, 53.8, ..., 30.7, 29.2, 27.9],
        ...,
        [24.7, 24.7, 24.4, ..., 20.9, 20.5, 20.2],
        [25. , 24.9, 24.8, ..., 21.5, 21. , 20.8],
        [24.7, 24.8, 24.5, ..., 21.6, 21.2, 20.9]]])

In [105]:
np_igs_maps.shape

(1, 49, 23)

In [106]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.0°,  -55.0°) - Indexes: [28, 11] - TEC:  80.1
   P2: ( -30.0°,  -50.0°) - Indexes: [28, 12] - TEC:  78.6
   P3: ( -32.5°,  -55.0°) - Indexes: [29, 11] - TEC:  77.6
   P4: ( -32.5°,  -50.0°) - Indexes: [29, 12] - TEC:  75.5

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -32.5° to  -30.0° (range:  2.5°)
   Longitude:  -55.0° to  -50.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -32.5°,  -55.0°) =  77.6
   f_01 (lat_min, lon_max) = ( -32.5°,  -50.0°) =  75.5
   f_10 (lat_max, lon_min) = ( -30.0°,  -55.0°) =  80.1
   f_11 (lat_max, lon_max) = ( -30.0°,  -50.0°) =  78.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -55.0)) / ( -50.0 - ( -55.0))
   t_x = 3.88024 /  5.0 = 0.776048

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -32.5)) / ( -30.0 - ( -32.5))
   t_y = 2.42596 /  2.5 = 0.970384

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.776048) * (1 - 0.970384) = 0.006633
   w_01 = t_x * (1 - t_y)       = 0.776048 * (1 - 0.970384)       = 0.022983
   w_10 = (1 - t_x) * t_y       = (1 - 0.776048) * 0.970384       = 0.217319
   w_11 = t_x * t_y             = 0.776048 * 0.970384             = 0.753065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.006633* 77.6 + 0.022983* 75.5 + 0.217319* 80.1 + 0.753065* 78.6
   Value =   0.5147 +   1.7352 +  17.4073 +  59.1909
   Value = 78.848098

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 77.60% of the way from -55° to -50°
   In Y direction (latitude):  97.04% of the way from -32.5° to -30.0°

============================================================
FINAL RESULT: TEC = 78.8481
============================================================

## MAGGIA

In [107]:
import pandas as pd
import numpy as np

In [108]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [109]:
!gdown '1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33'

Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33

but Gdown can't. Please check connections and permissions.

In [110]:
!curl 'https://drive.usercontent.google.com/download?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33&export=download&authuser=0&confirm=t&uuid=d9b8a6df-11db-4307-a167-ac211ac5581c&at=AN8xHoq4trwnwLFNTmxL5MWYU6R5%3A1758215477607' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'cache-control: no-cache' \
  -b 'OSID=g.a0001AgDnrQVJxXRCSwbzED_9iqn4my6nkJayE5wiYTLe9znmuJwCIMTQyXzIoLAKxHvlg5lOQACgYKATgSARMSFQHGX2MioCBriDJpWb2yRc1cnIMLExoVAUF8yKoRjxHP5I3tkQz9jUCTOMox0076; __Secure-OSID=g.a0001AgDnrQVJxXRCSwbzED_9iqn4my6nkJayE5wiYTLe9znmuJwnOJGZdpvbl-aK9RemVlKVwACgYKAZ4SARMSFQHGX2MinHk7BUUUwBPvJVCbPhj2MxoVAUF8yKrnOhwBFWPw0xsqi1DTWgxY0076; SID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE2PPdTeaOJdBeAtlpmXw0sewACgYKAbcSARMSFQHGX2MiN1EGMoYW5-zZxBT1_ezSjxoVAUF8yKp-Bxf-8e594r0CQzdCemGa0076; __Secure-1PSID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE232KZqePrzsSMgAiOjp4augACgYKAfwSARMSFQHGX2MiPmCqH2pVXTz0Lo82CmWsBhoVAUF8yKr1aTm8Qb3W38L98ZBLWPW00076; __Secure-3PSID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE2breUz8eJRfYGoHI-qm-VKQACgYKAagSARMSFQHGX2Mi-twVlgPzsTmjh9L3oX7OnRoVAUF8yKoG1gSkhWePQUxvPuKDbr8S0076; HSID=AMSoVtm4f2JOblFWQ; SSID=Ar4xkmiXaV7ZvsP_s; APISID=kylgo9NxpVDz00IS/AjUM8Yk5s56Ua4Eh8; SAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; __Secure-1PAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; __Secure-3PAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; AEC=AaJma5sHSMxOHlxGgF7UlW_iRFyPyjgEr18diEgqqKCL2BLcwan5fEPRB2s; NID=525=CNtlUvsSnUt4R6c7ftiXrWGpj-HywIsZMApOnrSLpatxi1U5dgZBC5UHUQzq7Pjps-73Xed-NUfBQ7OYju3vKKs7V4Qw_7yB7oHkcD1p2V3c3pX7-MiOZUiJHmSkgfa1pQCwfANSpSjelh8Ndyh6mEXWPm3-gbvVVJlQaowIOKd_57vTOsMYVT14LVIJKdqekPmvS7pY19rFTlH0KMR1qAKmMToSum6NmVfk_p6FgAMGTbTQPDkZadOC-GJsoITTxuMz6pq2UxqArcy3IUzb5uQCbnHwUDaPUlJueqCjwUsnmQjx5_LdWMGRMUdwmNr4fckZRsQtrmM4y4NKg-eMQ7I4GQ2Pf9k6oW0uec99qvGGf6djhOB5EymsROT6II3w6prjjqxe9zODQVxTHx8rsWUjCm9ch_x6EeuYb9I0eNVs7NszzhNHDbT_PnuiNhx2fdxkRDLx3aG3pv4QxJKpbQu8FhEAbp7BmHEn1Y9EWsM1NkPf3eMVd_XEY6ZqZuJRdLORbg-6aDI0TXn3FG2K0zbJuSCKaAN3w0mQ9eb-fSS_UOe34iFWC8jBJVSExm_bZm1DM0u5VKdRqyyzeLvaapxcoq1Yr42pmn7JRVKhV47kCQjjs6zUKBiAp8U1wUrJF0ARe060TY-sZG7qbmbqmeLP87ykzXsb2Agr1GwA6vI1E-Y_EnSsKS7soFLQAx5C2yCOwRcp9EnjUl11cweqkc99_TGeESvGKjFbxcBVNRia3zHJdZcbDffn--cII9HZmOClyv2nrlU-MuIYugpTIhoyPCU71TihKMuJvv_sduOJ0aTzYWwDkQsdnmNk-FG7ynOzC2OCJaHfuGtAt8Z8h2Fr_8Do32Gy5tPqeACm39QPKhD9Z1W-azqpwChPKAG_rWZfNa6kjYCTBKCx0VnCgx2uTgeCP2GFZM9K; __Secure-1PSIDTS=sidts-CjIBmkD5SwDEJcM4eZMPV5i5nWvF8h9MqcRi0Ri4QrwY8d0Nh16njjSPiC7lWfyUT07KJhAA; __Secure-3PSIDTS=sidts-CjIBmkD5SwDEJcM4eZMPV5i5nWvF8h9MqcRi0Ri4QrwY8d0Nh16njjSPiC7lWfyUT07KJhAA; SIDCC=AKEyXzWX4EnEWcSDVZT-cPacBP1_DR1lyM22KokLQOUrXh5X_rP8OlyoNCDL89A0H_uEZ989zL0; __Secure-1PSIDCC=AKEyXzVFPxbnMiKJpjR1u08AiYdCIiDtMa-E8L7G56hKRj9HYsxQG0l3AmhCUceVeM019Y0FsQ; __Secure-3PSIDCC=AKEyXzWrn0R73KBqEyzQh5Hd61knVuAHBdCQAI5o-yu04EGLxN9Uu-qKYItneVG_U1TddGorlQ' \
  -H 'pragma: no-cache' \
  -H 'priority: u=0, i' \
  -H 'sec-ch-ua: "Chromium";v="140", "Not=A?Brand";v="24", "Google Chrome";v="140"' \
  -H 'sec-ch-ua-arch: "x86"' \
  -H 'sec-ch-ua-bitness: "64"' \
  -H 'sec-ch-ua-form-factors: "Desktop"' \
  -H 'sec-ch-ua-full-version: "140.0.7339.127"' \
  -H 'sec-ch-ua-full-version-list: "Chromium";v="140.0.7339.127", "Not=A?Brand";v="24.0.0.0", "Google Chrome";v="140.0.7339.127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-model: ""' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-ch-ua-platform-version: "6.11.0"' \
  -H 'sec-ch-ua-wow64: ?0' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36' \
  -H 'x-browser-channel: stable' \
  -H 'x-browser-copyright: Copyright 2025 Google LLC. All rights reserved.' \
  -H 'x-browser-validation: vkog5hSrCvuYLnOVCb84JEvPqcg=' \
  -H 'x-browser-year: 2025' \
  -H 'x-client-data: CJO2yQEIo7bJAQipncoBCNCgygEIrYfLAQiTocsBCIegzQE=' > 'TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7157M  100 7157M    0     0   170M      0  0:00:42  0:00:42 --:--:--  179M

In [111]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [112]:
df_maggia_maps_2024

                 DATETIME                                             TECMAP
0     2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2024-09-05 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
15619 2024-12-31 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15620 2024-12-31 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15621 2024-12-31 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15622 2024-12-31 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15623 2024-12-31 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[15624 rows x 2 columns]

In [113]:
class Maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [114]:
maggia_tec = Maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-30.07404, lon=-51.11976)

In [115]:
maggia_points

[(-30.5, -51.5, 99, 117),
 (-30.5, -51.0, 99, 118),
 (-30.0, -51.5, 100, 117),
 (-30.0, -51.0, 100, 118)]

### 12/01 - 18:00

In [116]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [117]:
result

                 DATETIME                                             TECMAP
11268 2024-12-01 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [118]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [119]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [120]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [45.95299911, 45.88100052, 45.71300125, ..., 23.45899963,
         23.20400047, 22.93400002],
        [45.90299988, 45.8370018 , 45.67300034, ..., 23.38800049,
         23.23900032, 23.04000092],
        [45.86399841, 45.79700089, 45.63999939, ..., 23.29700089,
         23.1590004 , 23.00300026]]])

In [121]:
np_maggia_maps.shape

(1, 241, 221)

In [122]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  83.6
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  82.9
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  84.6
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  84.3

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  83.6
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  82.9
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  84.6
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  84.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y = 0.42596 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 83.6 + 0.112612* 82.9 + 0.204052* 84.6 + 0.647868* 84.3
   Value =   2.9656 +   9.3362 +  17.2548 +  54.5861
   Value = 84.142753

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 84.1428
============================================================

### 12/18 - 18:00

In [123]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [124]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [125]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [126]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [127]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [128]:
np_maggia_maps.shape

(1, 241, 221)

In [129]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  76.0
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  76.6
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  78.1
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  73.7

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  76.0
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  76.6
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  78.1
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  73.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y = 0.42596 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 76.0 + 0.112612* 76.6 + 0.204052* 78.1 + 0.647868* 73.7
   Value =   2.6955 +   8.6233 +  15.9375 +  47.7783
   Value = 75.034600

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 75.0346
============================================================

### 12/18 - 18:10

In [130]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [131]:
result

                 DATETIME                                             TECMAP
13717 2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [132]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [133]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [134]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [36.83499908, 37.06399918, 37.23899841, ..., 12.40799999,
         12.40799999, 12.40799999],
        [36.57699966, 36.82799911, 37.03300095, ..., 12.85900021,
         12.6619997 , 12.54399967],
        [36.34600067, 36.5909996 , 36.81399918, ..., 13.00500011,
         12.82999992, 12.32600021]]])

In [135]:
np_maggia_maps.shape

(1, 241, 221)

In [136]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  74.6
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  76.0
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  74.7
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  75.4

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  74.6
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  76.0
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  74.7
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  75.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y = 0.42596 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 74.6 + 0.112612* 76.0 + 0.204052* 74.7 + 0.647868* 75.4
   Value =   2.6468 +   8.5602 +  15.2508 +  48.8246
   Value = 75.282439

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 75.2824
============================================================

### 12/18 - 18:20

In [137]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [138]:
result

                 DATETIME                                             TECMAP
13718 2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [139]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [140]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [141]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [40.14899826, 40.15000153, 40.18000031, ..., 13.84500027,
         13.67500019, 13.12800026],
        [39.97399902, 40.02799988, 40.15399933, ..., 13.75800037,
         13.67599964, 12.39599991],
        [39.73500061, 39.83499908, 40.02500153, ..., 13.10700035,
         12.6239996 , 12.06000042]]])

In [142]:
np_maggia_maps.shape

(1, 241, 221)

In [143]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  74.7
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  74.4
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  74.1
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  74.8

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  74.7
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  74.4
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  74.1
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  74.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y = 0.42596 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 74.7 + 0.112612* 74.4 + 0.204052* 74.1 + 0.647868* 74.8
   Value =   2.6510 +   8.3802 +  15.1296 +  48.4716
   Value = 74.632378

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 74.6324
============================================================

### 12/18 - 18:30

In [144]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [145]:
result

                 DATETIME                                             TECMAP
13719 2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [146]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [147]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [148]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.94900131, 41.94900131, 41.94900131, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.94400024, 41.94400024, 41.94499969, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.89500046, 41.89799881, 41.90100098, ..., 11.36600018,
         11.25800037, 11.1960001 ]]])

In [149]:
np_maggia_maps.shape

(1, 241, 221)

In [150]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  72.6
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  74.1
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  74.7
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  75.5

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  72.6
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  74.1
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  74.7
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  75.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y = 0.42596 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 72.6 + 0.112612* 74.1 + 0.204052* 74.7 + 0.647868* 75.5
   Value =   2.5750 +   8.3394 +  15.2470 +  48.9335
   Value = 75.094785

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 75.0948
============================================================

### 12/19 - 18:00

In [151]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [152]:
result

                 DATETIME                                             TECMAP
13860 2024-12-19 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [153]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [154]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [155]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [37.94499969, 38.06100082, 38.13499832, ..., 11.56599998,
         11.17399979, 10.60200024],
        [37.7840004 , 37.92599869, 38.02999878, ..., 11.47599983,
         10.99199963, 10.38300037],
        [37.63499832, 37.77899933, 37.90499878, ..., 11.36100006,
         10.8739996 , 10.52200031]]])

In [156]:
np_maggia_maps.shape

(1, 241, 221)

In [157]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  77.8
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  80.3
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  79.8
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  80.4

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  77.8
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  80.3
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  79.8
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  80.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y = 0.42596 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 77.8 + 0.112612* 80.3 + 0.204052* 79.8 + 0.647868* 80.4
   Value =   2.7603 +   9.0459 +  16.2876 +  52.1061
   Value = 80.199909

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 80.1999
============================================================

### 12/22 - 18:00

In [158]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [159]:
result

                 DATETIME                                             TECMAP
14292 2024-12-22 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [160]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [161]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [162]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.41400146, 48.5379982 , 48.59199905, ..., 19.10899925,
         17.45599937, 17.45599937],
        [48.26200104, 48.41799927, 48.52799988, ..., 18.8560009 ,
         18.24600029, 17.79299927],
        [48.11100006, 48.27999878, 48.42100143, ..., 19.0890007 ,
         18.74200058, 18.39999962]]])

In [163]:
np_maggia_maps.shape

(1, 241, 221)

In [164]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.5°,  -51.5°) - Indexes: [99, 117] - TEC:  82.1
   P2: ( -30.5°,  -51.0°) - Indexes: [99, 118] - TEC:  82.2
   P3: ( -30.0°,  -51.5°) - Indexes: [100, 117] - TEC:  83.4
   P4: ( -30.0°,  -51.0°) - Indexes: [100, 118] - TEC:  82.4

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.5° to  -30.0° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.5°,  -51.5°) =  82.1
   f_01 (lat_min, lon_max) = ( -30.5°,  -51.0°) =  82.2
   f_10 (lat_max, lon_min) = ( -30.0°,  -51.5°) =  83.4
   f_11 (lat_max, lon_max) = ( -30.0°,  -51.0°) =  82.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.5)) / ( -30.0 - ( -30.5))
   t_y = 0.42596 /  0.5 = 0.851920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.851920) = 0.035468
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.851920)       = 0.112612
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.851920       = 0.204052
   w_11 = t_x * t_y             = 0.760480 * 0.851920             = 0.647868
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.035468* 82.1 + 0.112612* 82.2 + 0.204052* 83.4 + 0.647868* 82.4
   Value =   2.9106 +   9.2577 +  17.0098 +  53.3688
   Value = 82.546879

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  85.19% of the way from -30.5° to -30.0°

============================================================
FINAL RESULT: TEC = 82.5469
============================================================

## Nagoya

In [165]:
import pandas as pd
import numpy as np

In [166]:
#Download TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [167]:
!gdown '1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR'

Downloading...
From (original): https://drive.google.com/uc?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR
From (redirected): https://drive.google.com/uc?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR&confirm=t&uuid=22ed2c52-b7f2-4670-bd5e-d9b41a52882f
To: /content/TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl
100% 4.03G/4.03G [00:37<00:00, 108MB/s]

In [168]:
df_nagoya_maps_2024 = pd.read_pickle('TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [169]:
df_nagoya_maps_2024

                DATETIME                                             TECMAP
0    2024-12-01 00:00:00  [[18.593109130859375, 19.42150115966797, 19.42...
1    2024-12-01 00:05:00  [[18.222612380981445, 18.222612380981445, 18.2...
2    2024-12-01 00:10:00  [[18.21422576904297, 18.21422576904297, 18.214...
3    2024-12-01 00:15:00  [[18.284513473510742, 18.284513473510742, 18.0...
4    2024-12-01 00:20:00  [[18.328298568725586, 18.328298568725586, 18.0...
...                  ...                                                ...
8347 2024-12-30 23:35:00  [[26.173906326293945, 27.259140014648438, 27.2...
8348 2024-12-30 23:40:00  [[27.0389347076416, 27.0389347076416, 27.03893...
8349 2024-12-30 23:45:00  [[26.902502059936523, 26.72080421447754, 25.94...
8350 2024-12-30 23:50:00  [[27.88735580444336, 27.88735580444336, 27.887...
8351 2024-12-30 23:55:00  [[24.682987213134766, 25.294950485229492, 25.2...

[8352 rows x 2 columns]

In [170]:
class Nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [171]:
nagoya_tec = Nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-30.07404, lon=-51.11976)

In [172]:
nagoya_points

[(-30.400000000000006, -51.5, 100, 117),
 (-30.400000000000006, -51.0, 100, 118),
 (-29.900000000000006, -51.5, 101, 117),
 (-29.900000000000006, -51.0, 101, 118)]

### 12/01 - 18:00

In [173]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [174]:
result

               DATETIME                                             TECMAP
216 2024-12-01 18:00:00  [[5.463457107543945, 5.463457107543945, 5.4634...

In [175]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [176]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [177]:
np_nagoya_maps

array([[[ 5.46345711,  5.46345711,  5.46345711, ...,         nan,
                 nan,         nan],
        [ 9.9241066 , 10.95889568, 10.95889568, ...,         nan,
                 nan,         nan],
        [14.80212975, 14.80212975, 14.12398911, ...,         nan,
                 nan,         nan],
        ...,
        [43.88991547, 44.48843002, 44.89578247, ..., 21.9361248 ,
         21.8728199 , 21.43001556],
        [44.12051773, 44.59725952, 44.77046967, ..., 21.9361248 ,
         21.76833344, 21.42024994],
        [44.22133255, 44.64913177, 44.84080887, ..., 21.9361248 ,
         21.67697716, 21.29607773]]])

In [178]:
np_nagoya_maps.shape

(1, 242, 221)

In [179]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.4°,  -51.5°) - Indexes: [100, 117] - TEC:  75.8
   P2: ( -30.4°,  -51.0°) - Indexes: [100, 118] - TEC:  75.7
   P3: ( -29.9°,  -51.5°) - Indexes: [101, 117] - TEC:  75.9
   P4: ( -29.9°,  -51.0°) - Indexes: [101, 118] - TEC:  75.9

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.4° to  -29.9° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.4°,  -51.5°) =  75.8
   f_01 (lat_min, lon_max) = ( -30.4°,  -51.0°) =  75.7
   f_10 (lat_max, lon_min) = ( -29.9°,  -51.5°) =  75.9
   f_11 (lat_max, lon_max) = ( -29.9°,  -51.0°) =  75.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.4)) / ( -29.9 - ( -30.4))
   t_y = 0.32596 /  0.5 = 0.651920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.651920) = 0.083372
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.651920)       = 0.264708
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.651920       = 0.156148
   w_11 = t_x * t_y             = 0.760480 * 0.651920             = 0.495772
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.083372* 75.8 + 0.264708* 75.7 + 0.156148* 75.9 + 0.495772* 75.9
   Value =   6.3173 +  20.0488 +  11.8490 +  37.6201
   Value = 75.835373

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  65.19% of the way from -30.400000000000006° to -29.900000000000006°

============================================================
FINAL RESULT: TEC = 75.8354
============================================================

### 12/18 - 18:00

In [180]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [181]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [182]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [183]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [184]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [185]:
np_nagoya_maps.shape

(1, 242, 221)

In [186]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.4°,  -51.5°) - Indexes: [100, 117] - TEC:  75.0
   P2: ( -30.4°,  -51.0°) - Indexes: [100, 118] - TEC:  74.9
   P3: ( -29.9°,  -51.5°) - Indexes: [101, 117] - TEC:  74.3
   P4: ( -29.9°,  -51.0°) - Indexes: [101, 118] - TEC:  74.0

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.4° to  -29.9° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.4°,  -51.5°) =  75.0
   f_01 (lat_min, lon_max) = ( -30.4°,  -51.0°) =  74.9
   f_10 (lat_max, lon_min) = ( -29.9°,  -51.5°) =  74.3
   f_11 (lat_max, lon_max) = ( -29.9°,  -51.0°) =  74.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.4)) / ( -29.9 - ( -30.4))
   t_y = 0.32596 /  0.5 = 0.651920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.651920) = 0.083372
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.651920)       = 0.264708
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.651920       = 0.156148
   w_11 = t_x * t_y             = 0.760480 * 0.651920             = 0.495772
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.083372* 75.0 + 0.264708* 74.9 + 0.156148* 74.3 + 0.495772* 74.0
   Value =   6.2493 +  19.8163 +  11.6085 +  36.6711
   Value = 74.345210

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  65.19% of the way from -30.400000000000006° to -29.900000000000006°

============================================================
FINAL RESULT: TEC = 74.3452
============================================================

### 12/18 - 18:10

In [187]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [188]:
result

                DATETIME                                             TECMAP
4826 2024-12-18 18:10:00  [[18.412939071655273, 17.651090621948242, 17.6...

In [189]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [190]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [191]:
np_nagoya_maps

array([[[18.41293907, 17.65109062, 17.65109062, ...,         nan,
                 nan,         nan],
        [18.53962135, 17.62540054, 17.62540054, ...,         nan,
                 nan,         nan],
        [17.62013054, 17.62013054, 17.62540054, ...,         nan,
                 nan,         nan],
        ...,
        [36.95772552, 37.32144928, 37.6816864 , ..., 14.07102394,
         13.53792286, 13.37452602],
        [37.09318542, 37.28800964, 37.65478134, ..., 13.818923  ,
         13.44021893, 13.28282356],
        [36.133461  , 36.14941025, 36.71422577, ..., 13.40729332,
         13.00967979, 13.02010918]]])

In [192]:
np_nagoya_maps.shape

(1, 242, 221)

In [193]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.4°,  -51.5°) - Indexes: [100, 117] - TEC:  76.1
   P2: ( -30.4°,  -51.0°) - Indexes: [100, 118] - TEC:  75.8
   P3: ( -29.9°,  -51.5°) - Indexes: [101, 117] - TEC:  76.9
   P4: ( -29.9°,  -51.0°) - Indexes: [101, 118] - TEC:  76.6

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.4° to  -29.9° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.4°,  -51.5°) =  76.1
   f_01 (lat_min, lon_max) = ( -30.4°,  -51.0°) =  75.8
   f_10 (lat_max, lon_min) = ( -29.9°,  -51.5°) =  76.9
   f_11 (lat_max, lon_max) = ( -29.9°,  -51.0°) =  76.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.4)) / ( -29.9 - ( -30.4))
   t_y = 0.32596 /  0.5 = 0.651920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.651920) = 0.083372
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.651920)       = 0.264708
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.651920       = 0.156148
   w_11 = t_x * t_y             = 0.760480 * 0.651920             = 0.495772
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.083372* 76.1 + 0.264708* 75.8 + 0.156148* 76.9 + 0.495772* 76.6
   Value =   6.3437 +  20.0720 +  12.0153 +  37.9833
   Value = 76.414381

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  65.19% of the way from -30.400000000000006° to -29.900000000000006°

============================================================
FINAL RESULT: TEC = 76.4144
============================================================

### 12/18 - 18:20

In [194]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [195]:
result

                DATETIME                                             TECMAP
4828 2024-12-18 18:20:00  [[18.751976013183594, 18.751976013183594, 18.8...

In [196]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [197]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [198]:
np_nagoya_maps

array([[[18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.25943375, 18.13648224, 18.13648224, ...,         nan,
                 nan,         nan],
        ...,
        [38.79235458, 39.10980225, 39.51619339, ..., 13.45065308,
         13.1072731 , 12.96411705],
        [38.38473892, 38.68589783, 39.00465393, ..., 13.27555275,
         12.90675449, 12.72219276],
        [38.23902512, 38.27802277, 38.43577194, ..., 12.968153  ,
         12.60940075, 12.51128292]]])

In [199]:
np_nagoya_maps.shape

(1, 242, 221)

In [200]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.4°,  -51.5°) - Indexes: [100, 117] - TEC:  76.5
   P2: ( -30.4°,  -51.0°) - Indexes: [100, 118] - TEC:  76.9
   P3: ( -29.9°,  -51.5°) - Indexes: [101, 117] - TEC:  77.8
   P4: ( -29.9°,  -51.0°) - Indexes: [101, 118] - TEC:  77.9

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.4° to  -29.9° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.4°,  -51.5°) =  76.5
   f_01 (lat_min, lon_max) = ( -30.4°,  -51.0°) =  76.9
   f_10 (lat_max, lon_min) = ( -29.9°,  -51.5°) =  77.8
   f_11 (lat_max, lon_max) = ( -29.9°,  -51.0°) =  77.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.4)) / ( -29.9 - ( -30.4))
   t_y = 0.32596 /  0.5 = 0.651920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.651920) = 0.083372
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.651920)       = 0.264708
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.651920       = 0.156148
   w_11 = t_x * t_y             = 0.760480 * 0.651920             = 0.495772
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.083372* 76.5 + 0.264708* 76.9 + 0.156148* 77.8 + 0.495772* 77.9
   Value =   6.3754 +  20.3473 +  12.1526 +  38.6348
   Value = 77.510151

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  65.19% of the way from -30.400000000000006° to -29.900000000000006°

============================================================
FINAL RESULT: TEC = 77.5102
============================================================

### 12/18 - 18:30

In [201]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [202]:
result

                DATETIME                                             TECMAP
4830 2024-12-18 18:30:00  [[21.299997329711914, 21.299997329711914, 21.2...

In [203]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [204]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [205]:
np_nagoya_maps

array([[[21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.28308678, 21.28308678, 21.28308678, ...,         nan,
                 nan,         nan],
        ...,
        [39.65393066, 40.11976624, 40.50592804, ..., 13.14062977,
         12.80635357, 12.63247967],
        [39.26050949, 39.7519455 , 40.19271851, ..., 12.65815067,
         12.54124069, 12.46903992],
        [39.23273468, 39.40169144, 39.72786331, ..., 12.41631317,
         12.32884121, 12.25786972]]])

In [206]:
np_nagoya_maps.shape

(1, 242, 221)

In [207]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.4°,  -51.5°) - Indexes: [100, 117] - TEC:  77.3
   P2: ( -30.4°,  -51.0°) - Indexes: [100, 118] - TEC:  77.8
   P3: ( -29.9°,  -51.5°) - Indexes: [101, 117] - TEC:  78.2
   P4: ( -29.9°,  -51.0°) - Indexes: [101, 118] - TEC:  78.9

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.4° to  -29.9° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.4°,  -51.5°) =  77.3
   f_01 (lat_min, lon_max) = ( -30.4°,  -51.0°) =  77.8
   f_10 (lat_max, lon_min) = ( -29.9°,  -51.5°) =  78.2
   f_11 (lat_max, lon_max) = ( -29.9°,  -51.0°) =  78.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.4)) / ( -29.9 - ( -30.4))
   t_y = 0.32596 /  0.5 = 0.651920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.651920) = 0.083372
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.651920)       = 0.264708
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.651920       = 0.156148
   w_11 = t_x * t_y             = 0.760480 * 0.651920             = 0.495772
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.083372* 77.3 + 0.264708* 77.8 + 0.156148* 78.2 + 0.495772* 78.9
   Value =   6.4422 +  20.5882 +  12.2087 +  39.1178
   Value = 78.356940

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  65.19% of the way from -30.400000000000006° to -29.900000000000006°

============================================================
FINAL RESULT: TEC = 78.3569
============================================================

### 12/19 - 18:00

In [208]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [209]:
result

                DATETIME                                             TECMAP
5112 2024-12-19 18:00:00  [[12.639724731445312, 11.565997123718262, 11.5...

In [210]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [211]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [212]:
np_nagoya_maps

array([[[12.63972473, 11.56599712, 11.56599712, ...,         nan,
                 nan,         nan],
        [11.71732426, 10.61837482, 10.61837482, ...,         nan,
                 nan,         nan],
        [14.18716908, 11.54071808, 10.25730038, ...,         nan,
                 nan,         nan],
        ...,
        [34.01515198, 34.48353958, 34.89712906, ..., 11.77007103,
         11.27845764, 11.27845764],
        [33.72997284, 33.06239319, 33.53577042, ..., 11.66871548,
         11.30887318, 11.18506527],
        [33.0634613 , 32.32966614, 32.78850937, ..., 11.32422161,
         11.1510849 , 11.04978752]]])

In [213]:
np_nagoya_maps.shape

(1, 242, 221)

In [214]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.4°,  -51.5°) - Indexes: [100, 117] - TEC:  73.6
   P2: ( -30.4°,  -51.0°) - Indexes: [100, 118] - TEC:  73.2
   P3: ( -29.9°,  -51.5°) - Indexes: [101, 117] - TEC:  73.6
   P4: ( -29.9°,  -51.0°) - Indexes: [101, 118] - TEC:  73.5

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.4° to  -29.9° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.4°,  -51.5°) =  73.6
   f_01 (lat_min, lon_max) = ( -30.4°,  -51.0°) =  73.2
   f_10 (lat_max, lon_min) = ( -29.9°,  -51.5°) =  73.6
   f_11 (lat_max, lon_max) = ( -29.9°,  -51.0°) =  73.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.4)) / ( -29.9 - ( -30.4))
   t_y = 0.32596 /  0.5 = 0.651920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.651920) = 0.083372
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.651920)       = 0.264708
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.651920       = 0.156148
   w_11 = t_x * t_y             = 0.760480 * 0.651920             = 0.495772
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.083372* 73.6 + 0.264708* 73.2 + 0.156148* 73.6 + 0.495772* 73.5
   Value =   6.1325 +  19.3803 +  11.4927 +  36.4487
   Value = 73.454224

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  65.19% of the way from -30.400000000000006° to -29.900000000000006°

============================================================
FINAL RESULT: TEC = 73.4542
============================================================

### 12/22 - 18:00

In [215]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [216]:
result

                DATETIME                                             TECMAP
5976 2024-12-22 18:00:00  [[14.305987358093262, 14.235016822814941, 15.1...

In [217]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [218]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [219]:
np_nagoya_maps

array([[[14.30598736, 14.23501682, 15.19717693, ...,         nan,
                 nan,         nan],
        [13.24124527, 13.24124527, 13.24124527, ...,         nan,
                 nan,         nan],
        [13.24124527, 13.24124527, 13.24124527, ...,         nan,
                 nan,         nan],
        ...,
        [43.63508224, 43.97467422, 44.23501205, ..., 20.72278595,
         20.15914345, 19.78045845],
        [43.53390503, 43.86975861, 44.0747261 , ..., 20.29078865,
         19.64533615, 19.32730103],
        [43.54644394, 43.77022934, 43.95893478, ..., 19.72059822,
         19.0694046 , 18.65716362]]])

In [220]:
np_nagoya_maps.shape

(1, 242, 221)

In [221]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -30.07404
target_lon = -51.11976

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -30.4°,  -51.5°) - Indexes: [100, 117] - TEC:  76.2
   P2: ( -30.4°,  -51.0°) - Indexes: [100, 118] - TEC:  76.5
   P3: ( -29.9°,  -51.5°) - Indexes: [101, 117] - TEC:  77.1
   P4: ( -29.9°,  -51.0°) - Indexes: [101, 118] - TEC:  77.3

2. TARGET POINT: (-30.07404°, -51.11976°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -30.4° to  -29.9° (range:  0.5°)
   Longitude:  -51.5° to  -51.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -30.4°,  -51.5°) =  76.2
   f_01 (lat_min, lon_max) = ( -30.4°,  -51.0°) =  76.5
   f_10 (lat_max, lon_min) = ( -29.9°,  -51.5°) =  77.1
   f_11 (lat_max, lon_max) = ( -29.9°,  -51.0°) =  77.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-51.11976 - ( -51.5)) / ( -51.0 - ( -51.5))
   t_x = 0.38024 /  0.5 = 0.760480

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-30.07404 - ( -30.4)) / ( -29.9 - ( -30.4))
   t_y = 0.32596 /  0.5 = 0.651920

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.760480) * (1 - 0.651920) = 0.083372
   w_01 = t_x * (1 - t_y)       = 0.760480 * (1 - 0.651920)       = 0.264708
   w_10 = (1 - t_x) * t_y       = (1 - 0.760480) * 0.651920       = 0.156148
   w_11 = t_x * t_y             = 0.760480 * 0.651920             = 0.495772
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.083372* 76.2 + 0.264708* 76.5 + 0.156148* 77.1 + 0.495772* 77.3
   Value =   6.3493 +  20.2466 +  12.0433 +  38.3115
   Value = 76.950774

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 76.05% of the way from -51.5° to -51.0°
   In Y direction (latitude):  65.19% of the way from -30.400000000000006° to -29.900000000000006°

============================================================
FINAL RESULT: TEC = 76.9508
============================================================