# Gopi TEC Brasília analysis - December/2024

In [1]:
#Download Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [2]:
!gdown '1Dpt31SWcuPd9CGF6afPV1XkySQ7i0yTx'

Downloading...
From (original): https://drive.google.com/uc?id=1Dpt31SWcuPd9CGF6afPV1XkySQ7i0yTx
From (redirected): https://drive.google.com/uc?id=1Dpt31SWcuPd9CGF6afPV1XkySQ7i0yTx&confirm=t&uuid=d46aa135-cd5e-4a9f-917c-207429a92f24
To: /content/Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip
100% 46.0M/46.0M [00:00<00:00, 48.3MB/s]

In [3]:
%pwd

'/content'

In [4]:
!ls

Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip  sample_data

In [5]:
!unzip 'Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: braz271-2024-09-27.Std
  inflating: braz336-2024-12-01.Std
  inflating: braz337-2024-12-02.Std
  inflating: braz338-2024-12-03.Std
  inflating: braz339-2024-12-04.Std
  inflating: braz340-2024-12-05.Std
  inflating: braz341-2024-12-06.Std
  inflating: braz342-2024-12-07.Std
  inflating: braz343-2024-12-08.Std
  inflating: braz344-2024-12-09.Std
  inflating: braz345-2024-12-10.Std
  inflating: braz346-2024-12-11.Std
  inflating: braz347-2024-12-12.Std
  inflating: braz348-2024-12-13.Std
  inflating: braz349-2024-12-14.Std
  inflating: braz350-2024-12-15.Std
  inflating: braz351-2024-12-16.Std
  inflating: braz352-2024-12-17.Std
  inflating: braz353-2024-12-18.Std
  inflating: braz354-2024-12-19.Std
  inflating: braz355-2024-12-20.Std
  inflating: braz356-2024-12-21.Std
  inflating: braz357-2024-12-22.Std
  inflating: braz358-2024-12-23.Std
  inflating: braz359-2024-12-24.Std
  inflating: braz361-2024-12-26.Std
  inflating: braz362-2024-12-27.Std
  inflating: braz363-2024-12-28.Std
  inflating: braz364-2024-12-29.Std
  inflating: braz365-2024-12-30.Std
  inflating: braz366-2024-12-31.Std
  inflating: braz271-2024-09-27_page0.png
  inflating: braz271-2024-09-27-wbias.png
  inflating: braz336-2024-12-01_page0.png
  inflating: braz336-2024-12-01-wbias.png
  inflating: braz337-2024-12-02_page0.png
  inflating: braz337-2024-12-02-wbias.png
  inflating: braz338-2024-12-03_page0.png
  inflating: braz338-2024-12-03-wbias.png
  inflating: braz339-2024-12-04_page0.png
  inflating: braz339-2024-12-04-wbias.png
  inflating: braz340-2024-12-05_page0.png
  inflating: braz340-2024-12-05-wbias.png
  inflating: braz341-2024-12-06_page0.png
  inflating: braz341-2024-12-06-wbias.png
  inflating: braz342-2024-12-07_page0.png
  inflating: braz342-2024-12-07-wbias.png
  inflating: braz343-2024-12-08_page0.png
  inflating: braz343-2024-12-08-wbias.png
  inflating: braz344-2024-12-09_page0.png
  inflating: braz344-2024-12-09-wbias.png
  inflating: braz345-2024-12-10_page0.png
  inflating: braz345-2024-12-10-wbias.png
  inflating: braz346-2024-12-11_page0.png
  inflating: braz346-2024-12-11-wbias.png
  inflating: braz347-2024-12-12_page0.png
  inflating: braz347-2024-12-12-wbias.png
  inflating: braz348-2024-12-13_page0.png
  inflating: braz348-2024-12-13-wbias.png
  inflating: braz349-2024-12-14_page0.png
  inflating: braz349-2024-12-14-wbias.png
  inflating: braz350-2024-12-15_page0.png
  inflating: braz350-2024-12-15-wbias.png
  inflating: braz351-2024-12-16_page0.png
  inflating: braz351-2024-12-16-wbias.png
  inflating: braz352-2024-12-17_page0.png
  inflating: braz352-2024-12-17-wbias.png
  inflating: braz353-2024-12-18_page0.png
  inflating: braz353-2024-12-18-wbias.png
  inflating: braz354-2024-12-19_page0.png
  inflating: braz354-2024-12-19-wbias.png
  inflating: braz355-2024-12-20_page0.png
  inflating: braz355-2024-12-20-wbias.png
  inflating: braz356-2024-12-21_page0.png
  inflating: braz356-2024-12-21-wbias.png
  inflating: braz357-2024-12-22_page0.png
  inflating: braz357-2024-12-22-wbias.png
  inflating: braz358-2024-12-23_page0.png
  inflating: braz358-2024-12-23-wbias.png
  inflating: braz359-2024-12-24_page0.png
  inflating: braz359-2024-12-24-wbias.png
  inflating: braz361-2024-12-26_page0.png
  inflating: braz361-2024-12-26-wbias.png
  inflating: braz362-2024-12-27_page0.png
  inflating: braz362-2024-12-27-wbias.png
  inflating: braz363-2024-12-28_page0.png
  inflating: braz363-2024-12-28-wbias.png
  inflating: braz364-2024-12-29_page0.png
  inflating: braz364-2024-12-29-wbias.png
  inflating: braz365-2024-12-30_page0.png
  inflating: braz365-2024-12-30-wbias.png
  inflating: braz366-2024-12-31_page0.png
  inflating: braz366-2024-12-31-wbias.png
  inflating: braz271-2024-09-27.Bias
  inflating: braz271-2024-09-27.Cmn
  inflating: braz336-2024-12-01.Bias
  inflating: braz336-2024-12-01.Cmn
  inflating: braz337-2024-12-02.Bias
  inflating: braz337-2024-12-02.Cmn
  inflating: braz338-2024-12-03.Bias
  inflating: braz338-2024-12-03.Cmn
  inflating: braz339-2024-12-04.Bias
  inflating: braz339-2024-12-04.Cmn
  inflating: braz340-2024-12-05.Bias
  inflating: braz340-2024-12-05.Cmn
  inflating: braz341-2024-12-06.Bias
  inflating: braz341-2024-12-06.Cmn
  inflating: braz342-2024-12-07.Bias
  inflating: braz342-2024-12-07.Cmn
  inflating: braz343-2024-12-08.Bias
  inflating: braz343-2024-12-08.Cmn
  inflating: braz344-2024-12-09.Bias
  inflating: braz344-2024-12-09.Cmn
  inflating: braz345-2024-12-10.Bias
  inflating: braz345-2024-12-10.Cmn
  inflating: braz346-2024-12-11.Bias
  inflating: braz346-2024-12-11.Cmn
  inflating: braz347-2024-12-12.Bias
  inflating: braz347-2024-12-12.Cmn
  inflating: braz348-2024-12-13.Bias
  inflating: braz348-2024-12-13.Cmn
  inflating: braz349-2024-12-14.Bias
  inflating: braz349-2024-12-14.Cmn
  inflating: braz350-2024-12-15.Bias
  inflating: braz350-2024-12-15.Cmn
  inflating: braz351-2024-12-16.Bias
  inflating: braz351-2024-12-16.Cmn
  inflating: braz352-2024-12-17.Bias
  inflating: braz352-2024-12-17.Cmn
  inflating: braz353-2024-12-18.Bias
  inflating: braz353-2024-12-18.Cmn
  inflating: braz354-2024-12-19.Bias
  inflating: braz354-2024-12-19.Cmn
  inflating: braz355-2024-12-20.Bias
  inflating: braz355-2024-12-20.Cmn
  inflating: braz356-2024-12-21.Bias
  inflating: braz356-2024-12-21.Cmn
  inflating: braz357-2024-12-22.Bias
  inflating: braz357-2024-12-22.Cmn
  inflating: braz358-2024-12-23.Bias
  inflating: braz358-2024-12-23.Cmn
  inflating: braz359-2024-12-24.Bias
  inflating: braz359-2024-12-24.Cmn
  inflating: braz361-2024-12-26.Bias
  inflating: braz361-2024-12-26.Cmn
  inflating: braz362-2024-12-27.Bias
  inflating: braz362-2024-12-27.Cmn
  inflating: braz363-2024-12-28.Bias
  inflating: braz363-2024-12-28.Cmn
  inflating: braz364-2024-12-29.Bias
  inflating: braz364-2024-12-29.Cmn
  inflating: braz365-2024-12-30.Bias
  inflating: braz365-2024-12-30.Cmn
  inflating: braz366-2024-12-31.Bias
  inflating: braz366-2024-12-31.Cmn
  inflating: missing_rbmc_files_2024.txt

In [6]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta
import glob

data_dir = '.'

std_files = glob.glob(os.path.join(data_dir, 'braz3*-2024-12-*.Std'))

std_files.sort()

dfs = []

for file_path in std_files:
    try:

        filename = os.path.basename(file_path)
        print(f"Processing {filename}")

        date_parts = filename.replace('.Std', '').split('-')
        year = int(date_parts[1])
        month = int(date_parts[2])
        day = int(date_parts[3])
        base_date = datetime(year, month, day)

        df = pd.read_csv(file_path, sep='\s+', header=None)

        df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

        def decimal_to_time(decimal_hours):
            hours = int(decimal_hours)
            minutes = int((decimal_hours - hours) * 60)
            seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
            return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

        df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

        df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
        df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

        df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
        df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

        dfs.append(df)

    except Exception as e:
        print(f"Erro ao processar o arquivo {file_path}: {e}")

if dfs:
    combined_df = pd.concat(dfs, ignore_index=True)

    combined_df = combined_df.sort_values('DATETIME')

    combined_df.to_pickle('braz_dec_2024_complete.pkl')

    print(f"DataFrame combinado criado com {len(combined_df)} linhas")
    print("Primeiras 5 linhas:")
    print(combined_df.head())

    print("\nPeríodo coberto pelos dados:")
    print(f"Início: {combined_df['DATETIME'].min()}")
    print(f"Fim: {combined_df['DATETIME'].max()}")
    print(f"Total de dias: {(combined_df['DATETIME'].max() - combined_df['DATETIME'].min()).days + 1}")

    dias_presentes = combined_df['DATETIME'].dt.date.unique()
    print(f"\nTotal de dias com dados: {len(dias_presentes)}")
    print("Dias presentes:", sorted(dias_presentes))
else:
    print("Nenhum arquivo foi processado com sucesso.")

Processing braz336-2024-12-01.Std
Processing braz337-2024-12-02.Std
Processing braz338-2024-12-03.Std
Processing braz339-2024-12-04.Std
Processing braz340-2024-12-05.Std
Processing braz341-2024-12-06.Std
Processing braz342-2024-12-07.Std
Processing braz343-2024-12-08.Std
Processing braz344-2024-12-09.Std
Processing braz345-2024-12-10.Std
Processing braz346-2024-12-11.Std
Processing braz347-2024-12-12.Std
Processing braz348-2024-12-13.Std
Processing braz349-2024-12-14.Std
Processing braz350-2024-12-15.Std
Processing braz351-2024-12-16.Std
Processing braz352-2024-12-17.Std
Processing braz353-2024-12-18.Std
Processing braz354-2024-12-19.Std
Processing braz355-2024-12-20.Std
Processing braz356-2024-12-21.Std
Processing braz357-2024-12-22.Std
Processing braz358-2024-12-23.Std
Processing braz359-2024-12-24.Std
Processing braz361-2024-12-26.Std
Processing braz362-2024-12-27.Std
Processing braz363-2024-12-28.Std
Processing braz364-2024-12-29.Std
Processing braz365-2024-12-30.Std
Processing braz366-2024-12-31.Std
DataFrame combinado criado com 42320 linhas
Primeiras 5 linhas:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-12-01 00:00:00  88.02    11.61    -15.95
1 2024-12-01 00:01:01  88.05    11.11    -15.95
2 2024-12-01 00:01:58  88.07    11.13    -15.95
3 2024-12-01 00:03:00  88.10    10.34    -15.95
4 2024-12-01 00:04:01  88.12    10.02    -15.95

Período coberto pelos dados:
Início: 2024-12-01 00:00:00
Fim: 2024-12-31 23:58:58
Total de dias: 31

Total de dias com dados: 30
Dias presentes: [datetime.date(2024, 12, 1), datetime.date(2024, 12, 2), datetime.date(2024, 12, 3), datetime.date(2024, 12, 4), datetime.date(2024, 12, 5), datetime.date(2024, 12, 6), datetime.date(2024, 12, 7), datetime.date(2024, 12, 8), datetime.date(2024, 12, 9), datetime.date(2024, 12, 10), datetime.date(2024, 12, 11), datetime.date(2024, 12, 12), datetime.date(2024, 12, 13), datetime.date(2024, 12, 14), datetime.date(2024, 12, 15), datetime.date(2024, 12, 16), datetime.date(2024, 12, 17), datetime.date(2024, 12, 18), datetime.date(2024, 12, 19), datetime.date(2024, 12, 20), datetime.date(2024, 12, 21), datetime.date(2024, 12, 22), datetime.date(2024, 12, 23), datetime.date(2024, 12, 24), datetime.date(2024, 12, 26), datetime.date(2024, 12, 27), datetime.date(2024, 12, 28), datetime.date(2024, 12, 29), datetime.date(2024, 12, 30), datetime.date(2024, 12, 31)]

In [7]:
combined_df

                 DATETIME    TEC  TEC_STD  LATITUDE
0     2024-12-01 00:00:00  88.02    11.61    -15.95
1     2024-12-01 00:01:01  88.05    11.11    -15.95
2     2024-12-01 00:01:58  88.07    11.13    -15.95
3     2024-12-01 00:03:00  88.10    10.34    -15.95
4     2024-12-01 00:04:01  88.12    10.02    -15.95
...                   ...    ...      ...       ...
42315 2024-12-31 23:55:01  62.39     4.24    -15.95
42316 2024-12-31 23:55:58  62.46     4.17    -15.95
42317 2024-12-31 23:56:59  62.52     4.11    -15.95
42318 2024-12-31 23:58:01  62.58     4.39    -15.95
42319 2024-12-31 23:58:58  62.63     4.52    -15.95

[42320 rows x 4 columns]

## 18:00

In [8]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('braz_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_PEAKS_at_precise_interval(hour_start, minute_start, second_start, hour_end, minute_end, second_end):

    interval_label = f"{hour_start:02d}:{minute_start:02d}:{second_start:02d}-{hour_end:02d}:{minute_end:02d}:{second_end:02d}"

    print(f"\n{'='*80}")
    print(f"ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE {interval_label} UTC")
    print(f"{'='*80}")

    start_timestamps = []
    end_timestamps = []

    for day in df_clean['DATETIME'].dt.date.unique():
        start_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_start, minute_start, second_start))
        end_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_end, minute_end, second_end))

    df_interval = pd.DataFrame()
    for start, end in zip(start_timestamps, end_timestamps):
        day_interval = df_clean[(df_clean['DATETIME'] >= start) & (df_clean['DATETIME'] <= end)]
        df_interval = pd.concat([df_interval, day_interval])

    print(f"Filtering for times between {interval_label} UTC: {len(df_interval)} remaining points")

    if len(df_interval) == 0:
        print(f"ATTENTION: No data found in the range {interval_label} UTC!")
        return pd.DataFrame(), []

    df_interval['DATE'] = df_interval['DATETIME'].dt.date

    daily_max = df_interval.loc[df_interval.groupby('DATE')['TEC'].idxmax()]
    print(f"Unique days with data in range {interval_label}: {len(daily_max)}")

    if len(daily_max) >= 5:
        top_5_days = daily_max.nlargest(5, 'TEC').reset_index(drop=True)
    else:
        top_5_days = daily_max.sort_values('TEC', ascending=False).reset_index(drop=True)
        print(f"ATTENTION: Only {len(top_5_days)} days have data in this time range!")

    print(f"\n{len(top_5_days)} HIGHEST TEC VALUES IN THE INTERVAL {interval_label} (ONE PER DAY):")
    for idx, row in top_5_days.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_5_days.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_5_days) > 0:
        print(f"\nSUMMARY TABLE OF TEC PEAKS IN THE INTERVAL {interval_label} UTC:")
        print("-" * 100)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<12}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration'}")
        print("-" * 100)

        for idx, row in top_5_days.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M:%S'):<12}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration}")
        print("-" * 100)

    return top_5_days, sequences

def analyze_PEAKS_at_interval(hour_start, minute_start, hour_end, minute_end):

    return analyze_PEAKS_at_precise_interval(hour_start, minute_start, 0, hour_end, minute_end, 0)

print("\n\n" + "*"*40 + " ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC " + "*"*40)
top_5_exact_18h, sequences_exact_18h = analyze_PEAKS_at_precise_interval(17, 59, 55, 18, 0, 5)

print("\nAnálise concluída!")

Data loaded: 42320 records of 2024-12-01 until 2024-12-31
Analysing 41633 points after removing missing values


**************************************** ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC ****************************************

================================================================================
ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE 17:59:55-18:00:05 UTC
================================================================================
Filtering for times between 17:59:55-18:00:05 UTC: 29 remaining points
Unique days with data in range 17:59:55-18:00:05: 29

5 HIGHEST TEC VALUES IN THE INTERVAL 17:59:55-18:00:05 (ONE PER DAY):
1. TEC: 79.74 ± 5.18 TECU, Date/Time: 2024-12-18 18:00:00, Latitude: -15.95
2. TEC: 78.26 ± 5.59 TECU, Date/Time: 2024-12-22 18:00:00, Latitude: -15.95
3. TEC: 75.71 ± 4.47 TECU, Date/Time: 2024-12-02 18:00:00, Latitude: -15.95
4. TEC: 75.19 ± 4.36 TECU, Date/Time: 2024-12-03 18:00:00, Latitude: -15.95
5. TEC: 74.05 ± 1.66 TECU, Date/Time: 2024-12-16 18:00:00, Latitude: -15.95

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 79.74 ± 5.18) has a sequence of 3 high values:
  1. 2024-12-18 17:58:58: 79.59 ± 4.62 TECU (99.8% do Peak)
  2. 2024-12-18 18:00:00: 79.74 ± 5.18 TECU (100.0% do Peak)
  3. 2024-12-18 18:01:01: 79.87 ± 5.20 TECU (100.2% do Peak)

Peak #2 (TEC = 78.26 ± 5.59) has a sequence of 3 high values:
  1. 2024-12-22 17:58:58: 78.28 ± 5.54 TECU (100.0% do Peak)
  2. 2024-12-22 18:00:00: 78.26 ± 5.59 TECU (100.0% do Peak)
  3. 2024-12-22 18:01:01: 78.24 ± 5.64 TECU (100.0% do Peak)

Peak #3 (TEC = 75.71 ± 4.47) has a sequence of 3 high values:
  1. 2024-12-02 17:58:58: 75.58 ± 4.42 TECU (99.8% do Peak)
  2. 2024-12-02 18:00:00: 75.71 ± 4.47 TECU (100.0% do Peak)
  3. 2024-12-02 18:01:01: 75.84 ± 4.54 TECU (100.2% do Peak)

Peak #4 (TEC = 75.19 ± 4.36) has a sequence of 3 high values:
  1. 2024-12-03 17:58:58: 75.06 ± 4.34 TECU (99.8% do Peak)
  2. 2024-12-03 18:00:00: 75.19 ± 4.36 TECU (100.0% do Peak)
  3. 2024-12-03 18:01:01: 75.33 ± 4.39 TECU (100.2% do Peak)

Peak #5 (TEC = 74.05 ± 1.66) has a sequence of 3 high values:
  1. 2024-12-16 17:58:58: 73.95 ± 1.58 TECU (99.9% do Peak)
  2. 2024-12-16 18:00:00: 74.05 ± 1.66 TECU (100.0% do Peak)
  3. 2024-12-16 18:01:01: 74.16 ± 1.75 TECU (100.1% do Peak)

SUMMARY TABLE OF TEC PEAKS IN THE INTERVAL 17:59:55-18:00:05 UTC:
----------------------------------------------------------------------------------------------------
Rank Data        UTC time    TEC       TEC_STD   Sequence       Sequence Duration
----------------------------------------------------------------------------------------------------
1    18/12/2024  18:00:00    79.74    5.18    Sim            2.0 min
2    22/12/2024  18:00:00    78.26    5.59    Sim            2.0 min
3    02/12/2024  18:00:00    75.71    4.47    Sim            2.0 min
4    03/12/2024  18:00:00    75.19    4.36    Sim            2.0 min
5    16/12/2024  18:00:00    74.05    1.66    Sim            2.0 min
----------------------------------------------------------------------------------------------------

Análise concluída!

## DECEMBER

In [9]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('braz_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_top_PEAKS(top_n=200):

    print(f"\n{'='*80}")
    print(f"TOP {top_n} PEAK ANALYSIS OF TEC (ALL TIMES)")
    print(f"{'='*80}")

    df_clean['DATE'] = df_clean['DATETIME'].dt.date

    top_n_PEAKS = df_clean.nlargest(top_n, 'TEC').reset_index(drop=True)

    print(f"\nTOP {top_n} HIGHEST VALUES OF TEC (ALL TIMES):")
    for idx, row in top_n_PEAKS.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_n_PEAKS.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_n_PEAKS) > 0:
        print(f"\nSUMMARY TABLE OF TOP {top_n} TEC PEAKS:")
        print("-" * 110)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration':<20}{'Horário do dia'}")
        print("-" * 110)

        for idx, row in top_n_PEAKS.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            hour = row['DATETIME'].hour
            minute = row['DATETIME'].minute
            time_category = f"{hour:02d}:{minute:02d} UTC"

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M'):<10}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration:<20}{time_category}")
        print("-" * 110)

    return top_n_PEAKS, sequences

print("\n\n" + "*"*40 + "TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) " + "*"*40)
top_n_PEAKS, sequences = analyze_top_PEAKS(top_n=200)

print("\nAnálise concluída!")

Data loaded: 42320 records of 2024-12-01 until 2024-12-31
Analysing 41633 points after removing missing values


****************************************TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) ****************************************

================================================================================
TOP 200 PEAK ANALYSIS OF TEC (ALL TIMES)
================================================================================

TOP 200 HIGHEST VALUES OF TEC (ALL TIMES):
1. TEC: 98.06 ± 8.46 TECU, Date/Time: 2024-12-03 23:58:58, Latitude: -15.95
2. TEC: 97.92 ± 8.45 TECU, Date/Time: 2024-12-03 23:58:01, Latitude: -15.95
3. TEC: 97.77 ± 8.49 TECU, Date/Time: 2024-12-03 23:56:59, Latitude: -15.95
4. TEC: 97.62 ± 8.38 TECU, Date/Time: 2024-12-03 23:55:58, Latitude: -15.95
5. TEC: 97.45 ± 8.28 TECU, Date/Time: 2024-12-03 23:55:01, Latitude: -15.95
6. TEC: 97.28 ± 8.52 TECU, Date/Time: 2024-12-03 23:53:59, Latitude: -15.95
7. TEC: 97.09 ± 8.00 TECU, Date/Time: 2024-12-03 23:52:58, Latitude: -15.95
8. TEC: 96.90 ± 7.43 TECU, Date/Time: 2024-12-03 23:52:01, Latitude: -15.95
9. TEC: 96.69 ± 7.49 TECU, Date/Time: 2024-12-03 23:51:00, Latitude: -15.95
10. TEC: 96.48 ± 7.67 TECU, Date/Time: 2024-12-03 23:49:58, Latitude: -15.95
11. TEC: 96.25 ± 7.34 TECU, Date/Time: 2024-12-03 23:49:01, Latitude: -15.95
12. TEC: 96.02 ± 7.28 TECU, Date/Time: 2024-12-03 23:48:00, Latitude: -15.95
13. TEC: 95.77 ± 7.22 TECU, Date/Time: 2024-12-03 23:46:58, Latitude: -15.95
14. TEC: 95.51 ± 6.65 TECU, Date/Time: 2024-12-03 23:46:01, Latitude: -15.95
15. TEC: 95.25 ± 6.17 TECU, Date/Time: 2024-12-03 23:45:00, Latitude: -15.95
16. TEC: 94.97 ± 6.05 TECU, Date/Time: 2024-12-03 23:43:58, Latitude: -15.95
17. TEC: 94.68 ± 5.86 TECU, Date/Time: 2024-12-03 23:43:01, Latitude: -15.95
18. TEC: 94.38 ± 5.70 TECU, Date/Time: 2024-12-03 23:41:59, Latitude: -15.95
19. TEC: 94.07 ± 5.95 TECU, Date/Time: 2024-12-03 23:40:58, Latitude: -15.95
20. TEC: 93.76 ± 5.77 TECU, Date/Time: 2024-12-03 23:40:01, Latitude: -15.95
21. TEC: 93.43 ± 5.28 TECU, Date/Time: 2024-12-03 23:38:59, Latitude: -15.95
22. TEC: 93.09 ± 4.97 TECU, Date/Time: 2024-12-03 23:37:58, Latitude: -15.95
23. TEC: 92.74 ± 4.92 TECU, Date/Time: 2024-12-03 23:37:01, Latitude: -15.95
24. TEC: 92.38 ± 4.76 TECU, Date/Time: 2024-12-03 23:36:00, Latitude: -15.95
25. TEC: 92.02 ± 4.64 TECU, Date/Time: 2024-12-03 23:34:58, Latitude: -15.95
26. TEC: 91.64 ± 4.43 TECU, Date/Time: 2024-12-03 23:34:01, Latitude: -15.95
27. TEC: 91.26 ± 4.33 TECU, Date/Time: 2024-12-03 23:33:00, Latitude: -15.95
28. TEC: 90.87 ± 4.42 TECU, Date/Time: 2024-12-03 23:31:58, Latitude: -15.95
29. TEC: 90.47 ± 4.25 TECU, Date/Time: 2024-12-03 23:31:01, Latitude: -15.95
30. TEC: 90.06 ± 3.58 TECU, Date/Time: 2024-12-03 23:30:00, Latitude: -15.95
31. TEC: 89.64 ± 3.05 TECU, Date/Time: 2024-12-03 23:28:58, Latitude: -15.95
32. TEC: 89.22 ± 3.19 TECU, Date/Time: 2024-12-03 23:28:01, Latitude: -15.95
33. TEC: 88.79 ± 3.01 TECU, Date/Time: 2024-12-03 23:26:59, Latitude: -15.95
34. TEC: 88.35 ± 20.11 TECU, Date/Time: 2024-12-03 23:25:58, Latitude: -15.95
35. TEC: 88.18 ± 11.10 TECU, Date/Time: 2024-12-01 00:07:58, Latitude: -15.95
36. TEC: 88.18 ± 10.90 TECU, Date/Time: 2024-12-01 00:09:00, Latitude: -15.95
37. TEC: 88.18 ± 10.36 TECU, Date/Time: 2024-12-01 00:10:01, Latitude: -15.95
38. TEC: 88.17 ± 10.56 TECU, Date/Time: 2024-12-01 00:07:01, Latitude: -15.95
39. TEC: 88.17 ± 11.09 TECU, Date/Time: 2024-12-01 00:10:58, Latitude: -15.95
40. TEC: 88.16 ± 10.81 TECU, Date/Time: 2024-12-01 00:06:00, Latitude: -15.95
41. TEC: 88.16 ± 10.97 TECU, Date/Time: 2024-12-01 00:12:00, Latitude: -15.95
42. TEC: 88.14 ± 10.67 TECU, Date/Time: 2024-12-01 00:04:58, Latitude: -15.95
43. TEC: 88.14 ± 11.01 TECU, Date/Time: 2024-12-01 00:13:01, Latitude: -15.95
44. TEC: 88.12 ± 10.02 TECU, Date/Time: 2024-12-01 00:04:01, Latitude: -15.95
45. TEC: 88.12 ± 11.27 TECU, Date/Time: 2024-12-01 00:13:58, Latitude: -15.95
46. TEC: 88.10 ± 10.34 TECU, Date/Time: 2024-12-01 00:03:00, Latitude: -15.95
47. TEC: 88.09 ± 10.74 TECU, Date/Time: 2024-12-01 00:15:00, Latitude: -15.95
48. TEC: 88.07 ± 11.13 TECU, Date/Time: 2024-12-01 00:01:58, Latitude: -15.95
49. TEC: 88.06 ± 10.69 TECU, Date/Time: 2024-12-01 00:16:01, Latitude: -15.95
50. TEC: 88.05 ± 11.11 TECU, Date/Time: 2024-12-01 00:01:01, Latitude: -15.95
51. TEC: 88.02 ± 11.61 TECU, Date/Time: 2024-12-01 00:00:00, Latitude: -15.95
52. TEC: 88.02 ± 10.43 TECU, Date/Time: 2024-12-01 00:16:58, Latitude: -15.95
53. TEC: 87.97 ± 9.98 TECU, Date/Time: 2024-12-01 00:18:00, Latitude: -15.95
54. TEC: 87.92 ± 9.88 TECU, Date/Time: 2024-12-01 00:19:01, Latitude: -15.95
55. TEC: 87.91 ± 26.35 TECU, Date/Time: 2024-12-03 23:25:01, Latitude: -15.95
56. TEC: 87.86 ± 9.80 TECU, Date/Time: 2024-12-01 00:19:58, Latitude: -15.95
57. TEC: 87.80 ± 9.72 TECU, Date/Time: 2024-12-01 00:21:00, Latitude: -15.95
58. TEC: 87.72 ± 9.30 TECU, Date/Time: 2024-12-01 00:22:01, Latitude: -15.95
59. TEC: 87.64 ± 9.28 TECU, Date/Time: 2024-12-01 00:22:58, Latitude: -15.95
60. TEC: 87.56 ± 9.50 TECU, Date/Time: 2024-12-01 00:24:00, Latitude: -15.95
61. TEC: 87.46 ± 9.19 TECU, Date/Time: 2024-12-01 00:25:01, Latitude: -15.95
62. TEC: 87.46 ± 24.73 TECU, Date/Time: 2024-12-03 23:23:59, Latitude: -15.95
63. TEC: 87.36 ± 9.29 TECU, Date/Time: 2024-12-01 00:25:58, Latitude: -15.95
64. TEC: 87.25 ± 9.11 TECU, Date/Time: 2024-12-01 00:27:00, Latitude: -15.95
65. TEC: 87.14 ± 8.65 TECU, Date/Time: 2024-12-01 00:28:01, Latitude: -15.95
66. TEC: 87.01 ± 7.73 TECU, Date/Time: 2024-12-01 00:28:58, Latitude: -15.95
67. TEC: 87.00 ± 24.36 TECU, Date/Time: 2024-12-03 23:22:58, Latitude: -15.95
68. TEC: 86.88 ± 7.71 TECU, Date/Time: 2024-12-01 00:30:00, Latitude: -15.95
69. TEC: 86.74 ± 7.34 TECU, Date/Time: 2024-12-01 00:31:01, Latitude: -15.95
70. TEC: 86.59 ± 6.65 TECU, Date/Time: 2024-12-01 00:31:58, Latitude: -15.95
71. TEC: 86.54 ± 23.89 TECU, Date/Time: 2024-12-03 23:22:01, Latitude: -15.95
72. TEC: 86.43 ± 6.90 TECU, Date/Time: 2024-12-01 00:33:00, Latitude: -15.95
73. TEC: 86.26 ± 6.17 TECU, Date/Time: 2024-12-01 00:34:01, Latitude: -15.95
74. TEC: 86.09 ± 5.65 TECU, Date/Time: 2024-12-01 00:34:58, Latitude: -15.95
75. TEC: 86.08 ± 23.85 TECU, Date/Time: 2024-12-03 23:21:00, Latitude: -15.95
76. TEC: 85.90 ± 5.83 TECU, Date/Time: 2024-12-01 00:36:00, Latitude: -15.95
77. TEC: 85.70 ± 5.21 TECU, Date/Time: 2024-12-01 00:37:01, Latitude: -15.95
78. TEC: 85.61 ± 23.85 TECU, Date/Time: 2024-12-03 23:19:58, Latitude: -15.95
79. TEC: 85.60 ± 7.95 TECU, Date/Time: 2024-12-02 19:10:58, Latitude: -15.95
80. TEC: 85.59 ± 7.92 TECU, Date/Time: 2024-12-02 19:10:01, Latitude: -15.95
81. TEC: 85.59 ± 7.97 TECU, Date/Time: 2024-12-02 19:11:59, Latitude: -15.95
82. TEC: 85.59 ± 8.00 TECU, Date/Time: 2024-12-02 19:13:01, Latitude: -15.95
83. TEC: 85.58 ± 7.91 TECU, Date/Time: 2024-12-02 19:08:59, Latitude: -15.95
84. TEC: 85.58 ± 8.01 TECU, Date/Time: 2024-12-02 19:13:58, Latitude: -15.95
85. TEC: 85.56 ± 7.91 TECU, Date/Time: 2024-12-02 19:07:58, Latitude: -15.95
86. TEC: 85.56 ± 7.99 TECU, Date/Time: 2024-12-02 19:15:00, Latitude: -15.95
87. TEC: 85.56 ± 7.23 TECU, Date/Time: 2024-12-03 19:11:59, Latitude: -15.95
88. TEC: 85.56 ± 7.27 TECU, Date/Time: 2024-12-03 19:13:01, Latitude: -15.95
89. TEC: 85.55 ± 7.18 TECU, Date/Time: 2024-12-03 19:10:58, Latitude: -15.95
90. TEC: 85.55 ± 7.31 TECU, Date/Time: 2024-12-03 19:13:58, Latitude: -15.95
91. TEC: 85.54 ± 8.21 TECU, Date/Time: 2024-12-02 19:07:01, Latitude: -15.95
92. TEC: 85.53 ± 7.96 TECU, Date/Time: 2024-12-02 19:16:01, Latitude: -15.95
93. TEC: 85.53 ± 7.17 TECU, Date/Time: 2024-12-03 19:10:01, Latitude: -15.95
94. TEC: 85.53 ± 7.34 TECU, Date/Time: 2024-12-03 19:15:00, Latitude: -15.95
95. TEC: 85.51 ± 7.59 TECU, Date/Time: 2024-12-02 19:06:00, Latitude: -15.95
96. TEC: 85.50 ± 4.38 TECU, Date/Time: 2024-12-01 00:37:58, Latitude: -15.95
97. TEC: 85.50 ± 7.97 TECU, Date/Time: 2024-12-02 19:16:58, Latitude: -15.95
98. TEC: 85.50 ± 7.16 TECU, Date/Time: 2024-12-03 19:08:59, Latitude: -15.95
99. TEC: 85.50 ± 7.39 TECU, Date/Time: 2024-12-03 19:16:01, Latitude: -15.95
100. TEC: 85.47 ± 7.58 TECU, Date/Time: 2024-12-02 19:04:58, Latitude: -15.95
101. TEC: 85.47 ± 7.98 TECU, Date/Time: 2024-12-02 19:18:00, Latitude: -15.95
102. TEC: 85.46 ± 7.14 TECU, Date/Time: 2024-12-03 19:07:58, Latitude: -15.95
103. TEC: 85.46 ± 7.44 TECU, Date/Time: 2024-12-03 19:16:58, Latitude: -15.95
104. TEC: 85.43 ± 6.78 TECU, Date/Time: 2024-12-02 19:04:01, Latitude: -15.95
105. TEC: 85.43 ± 7.98 TECU, Date/Time: 2024-12-02 19:19:01, Latitude: -15.95
106. TEC: 85.42 ± 7.11 TECU, Date/Time: 2024-12-03 19:07:01, Latitude: -15.95
107. TEC: 85.41 ± 7.43 TECU, Date/Time: 2024-12-03 19:18:00, Latitude: -15.95
108. TEC: 85.38 ± 8.03 TECU, Date/Time: 2024-12-02 19:19:58, Latitude: -15.95
109. TEC: 85.37 ± 6.74 TECU, Date/Time: 2024-12-02 19:03:00, Latitude: -15.95
110. TEC: 85.36 ± 7.08 TECU, Date/Time: 2024-12-03 19:06:00, Latitude: -15.95
111. TEC: 85.36 ± 7.44 TECU, Date/Time: 2024-12-03 19:19:01, Latitude: -15.95
112. TEC: 85.33 ± 8.06 TECU, Date/Time: 2024-12-02 19:21:00, Latitude: -15.95
113. TEC: 85.32 ± 6.70 TECU, Date/Time: 2024-12-02 19:01:58, Latitude: -15.95
114. TEC: 85.30 ± 7.04 TECU, Date/Time: 2024-12-03 19:04:58, Latitude: -15.95
115. TEC: 85.29 ± 7.47 TECU, Date/Time: 2024-12-03 19:19:58, Latitude: -15.95
116. TEC: 85.28 ± 12.01 TECU, Date/Time: 2024-12-01 00:39:00, Latitude: -15.95
117. TEC: 85.28 ± 8.07 TECU, Date/Time: 2024-12-02 19:22:01, Latitude: -15.95
118. TEC: 85.25 ± 6.68 TECU, Date/Time: 2024-12-02 19:01:01, Latitude: -15.95
119. TEC: 85.23 ± 6.97 TECU, Date/Time: 2024-12-03 19:04:01, Latitude: -15.95
120. TEC: 85.22 ± 7.51 TECU, Date/Time: 2024-12-03 19:21:00, Latitude: -15.95
121. TEC: 85.21 ± 8.11 TECU, Date/Time: 2024-12-02 19:22:58, Latitude: -15.95
122. TEC: 85.18 ± 6.64 TECU, Date/Time: 2024-12-02 19:00:00, Latitude: -15.95
123. TEC: 85.15 ± 8.15 TECU, Date/Time: 2024-12-02 19:23:59, Latitude: -15.95
124. TEC: 85.15 ± 6.93 TECU, Date/Time: 2024-12-03 19:03:00, Latitude: -15.95
125. TEC: 85.14 ± 7.55 TECU, Date/Time: 2024-12-03 19:22:01, Latitude: -15.95
126. TEC: 85.13 ± 23.50 TECU, Date/Time: 2024-12-03 23:19:01, Latitude: -15.95
127. TEC: 85.10 ± 6.57 TECU, Date/Time: 2024-12-02 18:58:58, Latitude: -15.95
128. TEC: 85.07 ± 8.20 TECU, Date/Time: 2024-12-02 19:25:01, Latitude: -15.95
129. TEC: 85.06 ± 16.90 TECU, Date/Time: 2024-12-01 00:40:01, Latitude: -15.95
130. TEC: 85.06 ± 6.87 TECU, Date/Time: 2024-12-03 19:01:58, Latitude: -15.95
131. TEC: 85.05 ± 7.60 TECU, Date/Time: 2024-12-03 19:22:58, Latitude: -15.95
132. TEC: 85.01 ± 6.51 TECU, Date/Time: 2024-12-02 18:58:01, Latitude: -15.95
133. TEC: 84.99 ± 8.25 TECU, Date/Time: 2024-12-02 19:25:58, Latitude: -15.95
134. TEC: 84.97 ± 6.45 TECU, Date/Time: 2024-12-03 19:01:01, Latitude: -15.95
135. TEC: 84.95 ± 7.66 TECU, Date/Time: 2024-12-03 19:23:59, Latitude: -15.95
136. TEC: 84.92 ± 6.47 TECU, Date/Time: 2024-12-02 18:56:59, Latitude: -15.95
137. TEC: 84.91 ± 8.29 TECU, Date/Time: 2024-12-02 19:26:59, Latitude: -15.95
138. TEC: 84.87 ± 6.18 TECU, Date/Time: 2024-12-03 19:00:00, Latitude: -15.95
139. TEC: 84.84 ± 7.74 TECU, Date/Time: 2024-12-03 19:25:01, Latitude: -15.95
140. TEC: 84.82 ± 18.74 TECU, Date/Time: 2024-12-01 00:40:58, Latitude: -15.95
141. TEC: 84.82 ± 6.39 TECU, Date/Time: 2024-12-02 18:55:58, Latitude: -15.95
142. TEC: 84.81 ± 8.31 TECU, Date/Time: 2024-12-02 19:28:01, Latitude: -15.95
143. TEC: 84.76 ± 6.11 TECU, Date/Time: 2024-12-03 18:58:58, Latitude: -15.95
144. TEC: 84.73 ± 7.81 TECU, Date/Time: 2024-12-03 19:25:58, Latitude: -15.95
145. TEC: 84.72 ± 8.34 TECU, Date/Time: 2024-12-02 19:28:58, Latitude: -15.95
146. TEC: 84.71 ± 6.32 TECU, Date/Time: 2024-12-02 18:55:01, Latitude: -15.95
147. TEC: 84.66 ± 23.07 TECU, Date/Time: 2024-12-03 23:18:00, Latitude: -15.95
148. TEC: 84.64 ± 6.00 TECU, Date/Time: 2024-12-03 18:58:01, Latitude: -15.95
149. TEC: 84.61 ± 8.36 TECU, Date/Time: 2024-12-02 19:30:00, Latitude: -15.95
150. TEC: 84.61 ± 7.88 TECU, Date/Time: 2024-12-03 19:26:59, Latitude: -15.95
151. TEC: 84.59 ± 6.24 TECU, Date/Time: 2024-12-02 18:53:59, Latitude: -15.95
152. TEC: 84.58 ± 19.83 TECU, Date/Time: 2024-12-01 00:42:00, Latitude: -15.95
153. TEC: 84.52 ± 5.91 TECU, Date/Time: 2024-12-03 18:56:59, Latitude: -15.95
154. TEC: 84.50 ± 8.38 TECU, Date/Time: 2024-12-02 19:31:01, Latitude: -15.95
155. TEC: 84.48 ± 7.97 TECU, Date/Time: 2024-12-03 19:28:01, Latitude: -15.95
156. TEC: 84.47 ± 6.20 TECU, Date/Time: 2024-12-02 18:52:58, Latitude: -15.95
157. TEC: 84.39 ± 5.83 TECU, Date/Time: 2024-12-03 18:55:58, Latitude: -15.95
158. TEC: 84.38 ± 8.42 TECU, Date/Time: 2024-12-02 19:31:58, Latitude: -15.95
159. TEC: 84.35 ± 8.03 TECU, Date/Time: 2024-12-03 19:28:58, Latitude: -15.95
160. TEC: 84.34 ± 6.13 TECU, Date/Time: 2024-12-02 18:52:01, Latitude: -15.95
161. TEC: 84.32 ± 16.17 TECU, Date/Time: 2024-12-01 00:43:01, Latitude: -15.95
162. TEC: 84.26 ± 5.73 TECU, Date/Time: 2024-12-03 18:55:01, Latitude: -15.95
163. TEC: 84.25 ± 8.44 TECU, Date/Time: 2024-12-02 19:33:00, Latitude: -15.95
164. TEC: 84.21 ± 6.06 TECU, Date/Time: 2024-12-02 18:51:00, Latitude: -15.95
165. TEC: 84.21 ± 8.09 TECU, Date/Time: 2024-12-03 19:30:00, Latitude: -15.95
166. TEC: 84.18 ± 22.70 TECU, Date/Time: 2024-12-03 23:16:58, Latitude: -15.95
167. TEC: 84.12 ± 8.49 TECU, Date/Time: 2024-12-02 19:34:01, Latitude: -15.95
168. TEC: 84.12 ± 5.67 TECU, Date/Time: 2024-12-03 18:53:59, Latitude: -15.95
169. TEC: 84.07 ± 8.12 TECU, Date/Time: 2024-12-03 19:31:01, Latitude: -15.95
170. TEC: 84.06 ± 5.96 TECU, Date/Time: 2024-12-02 18:49:58, Latitude: -15.95
171. TEC: 84.05 ± 17.68 TECU, Date/Time: 2024-12-01 00:43:58, Latitude: -15.95
172. TEC: 83.98 ± 8.48 TECU, Date/Time: 2024-12-02 19:34:58, Latitude: -15.95
173. TEC: 83.97 ± 5.78 TECU, Date/Time: 2024-12-03 18:52:58, Latitude: -15.95
174. TEC: 83.92 ± 5.87 TECU, Date/Time: 2024-12-02 18:49:01, Latitude: -15.95
175. TEC: 83.92 ± 8.15 TECU, Date/Time: 2024-12-03 19:31:58, Latitude: -15.95
176. TEC: 83.91 ± 7.15 TECU, Date/Time: 2024-12-03 21:11:59, Latitude: -15.95
177. TEC: 83.91 ± 7.24 TECU, Date/Time: 2024-12-03 21:13:01, Latitude: -15.95
178. TEC: 83.91 ± 7.36 TECU, Date/Time: 2024-12-03 21:13:58, Latitude: -15.95
179. TEC: 83.90 ± 7.49 TECU, Date/Time: 2024-12-03 21:15:00, Latitude: -15.95
180. TEC: 83.89 ± 7.06 TECU, Date/Time: 2024-12-03 21:10:58, Latitude: -15.95
181. TEC: 83.87 ± 6.97 TECU, Date/Time: 2024-12-03 21:10:01, Latitude: -15.95
182. TEC: 83.87 ± 7.60 TECU, Date/Time: 2024-12-03 21:16:01, Latitude: -15.95
183. TEC: 83.84 ± 8.38 TECU, Date/Time: 2024-12-03 21:16:58, Latitude: -15.95
184. TEC: 83.83 ± 8.47 TECU, Date/Time: 2024-12-02 19:36:00, Latitude: -15.95
185. TEC: 83.83 ± 6.86 TECU, Date/Time: 2024-12-03 21:08:59, Latitude: -15.95
186. TEC: 83.82 ± 5.75 TECU, Date/Time: 2024-12-03 18:52:01, Latitude: -15.95
187. TEC: 83.80 ± 8.77 TECU, Date/Time: 2024-12-03 21:18:00, Latitude: -15.95
188. TEC: 83.79 ± 6.77 TECU, Date/Time: 2024-12-03 21:07:58, Latitude: -15.95
189. TEC: 83.77 ± 18.44 TECU, Date/Time: 2024-12-01 00:45:00, Latitude: -15.95
190. TEC: 83.77 ± 8.20 TECU, Date/Time: 2024-12-03 19:33:00, Latitude: -15.95
191. TEC: 83.76 ± 5.75 TECU, Date/Time: 2024-12-02 18:48:00, Latitude: -15.95
192. TEC: 83.74 ± 6.68 TECU, Date/Time: 2024-12-03 21:07:01, Latitude: -15.95
193. TEC: 83.74 ± 8.89 TECU, Date/Time: 2024-12-03 21:19:01, Latitude: -15.95
194. TEC: 83.69 ± 22.41 TECU, Date/Time: 2024-12-03 23:16:01, Latitude: -15.95
195. TEC: 83.68 ± 8.49 TECU, Date/Time: 2024-12-02 19:37:01, Latitude: -15.95
196. TEC: 83.68 ± 6.55 TECU, Date/Time: 2024-12-03 21:06:00, Latitude: -15.95
197. TEC: 83.67 ± 8.99 TECU, Date/Time: 2024-12-03 21:19:58, Latitude: -15.95
198. TEC: 83.66 ± 5.04 TECU, Date/Time: 2024-12-03 18:51:00, Latitude: -15.95
199. TEC: 83.62 ± 6.42 TECU, Date/Time: 2024-12-03 21:04:58, Latitude: -15.95
200. TEC: 83.61 ± 5.63 TECU, Date/Time: 2024-12-02 18:46:58, Latitude: -15.95

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 98.06 ± 8.46) has a sequence of 3 high values:
  1. 2024-12-03 23:56:59: 97.77 ± 8.49 TECU (99.7% do Peak)
  2. 2024-12-03 23:58:01: 97.92 ± 8.45 TECU (99.9% do Peak)
  3. 2024-12-03 23:58:58: 98.06 ± 8.46 TECU (100.0% do Peak)

Peak #2 (TEC = 97.92 ± 8.45) has a sequence of 3 high values:
  1. 2024-12-03 23:56:59: 97.77 ± 8.49 TECU (99.8% do Peak)
  2. 2024-12-03 23:58:01: 97.92 ± 8.45 TECU (100.0% do Peak)
  3. 2024-12-03 23:58:58: 98.06 ± 8.46 TECU (100.1% do Peak)

Peak #3 (TEC = 97.77 ± 8.49) has a sequence of 3 high values:
  1. 2024-12-03 23:55:58: 97.62 ± 8.38 TECU (99.8% do Peak)
  2. 2024-12-03 23:56:59: 97.77 ± 8.49 TECU (100.0% do Peak)
  3. 2024-12-03 23:58:01: 97.92 ± 8.45 TECU (100.2% do Peak)

Peak #4 (TEC = 97.62 ± 8.38) has a sequence of 3 high values:
  1. 2024-12-03 23:55:01: 97.45 ± 8.28 TECU (99.8% do Peak)
  2. 2024-12-03 23:55:58: 97.62 ± 8.38 TECU (100.0% do Peak)
  3. 2024-12-03 23:56:59: 97.77 ± 8.49 TECU (100.2% do Peak)

Peak #5 (TEC = 97.45 ± 8.28) has a sequence of 3 high values:
  1. 2024-12-03 23:53:59: 97.28 ± 8.52 TECU (99.8% do Peak)
  2. 2024-12-03 23:55:01: 97.45 ± 8.28 TECU (100.0% do Peak)
  3. 2024-12-03 23:55:58: 97.62 ± 8.38 TECU (100.2% do Peak)

Peak #6 (TEC = 97.28 ± 8.52) has a sequence of 3 high values:
  1. 2024-12-03 23:52:58: 97.09 ± 8.00 TECU (99.8% do Peak)
  2. 2024-12-03 23:53:59: 97.28 ± 8.52 TECU (100.0% do Peak)
  3. 2024-12-03 23:55:01: 97.45 ± 8.28 TECU (100.2% do Peak)

Peak #7 (TEC = 97.09 ± 8.00) has a sequence of 3 high values:
  1. 2024-12-03 23:52:01: 96.90 ± 7.43 TECU (99.8% do Peak)
  2. 2024-12-03 23:52:58: 97.09 ± 8.00 TECU (100.0% do Peak)
  3. 2024-12-03 23:53:59: 97.28 ± 8.52 TECU (100.2% do Peak)

Peak #8 (TEC = 96.90 ± 7.43) has a sequence of 3 high values:
  1. 2024-12-03 23:51:00: 96.69 ± 7.49 TECU (99.8% do Peak)
  2. 2024-12-03 23:52:01: 96.90 ± 7.43 TECU (100.0% do Peak)
  3. 2024-12-03 23:52:58: 97.09 ± 8.00 TECU (100.2% do Peak)

Peak #9 (TEC = 96.69 ± 7.49) has a sequence of 3 high values:
  1. 2024-12-03 23:49:58: 96.48 ± 7.67 TECU (99.8% do Peak)
  2. 2024-12-03 23:51:00: 96.69 ± 7.49 TECU (100.0% do Peak)
  3. 2024-12-03 23:52:01: 96.90 ± 7.43 TECU (100.2% do Peak)

Peak #10 (TEC = 96.48 ± 7.67) has a sequence of 3 high values:
  1. 2024-12-03 23:49:01: 96.25 ± 7.34 TECU (99.8% do Peak)
  2. 2024-12-03 23:49:58: 96.48 ± 7.67 TECU (100.0% do Peak)
  3. 2024-12-03 23:51:00: 96.69 ± 7.49 TECU (100.2% do Peak)

Peak #11 (TEC = 96.25 ± 7.34) has a sequence of 3 high values:
  1. 2024-12-03 23:48:00: 96.02 ± 7.28 TECU (99.8% do Peak)
  2. 2024-12-03 23:49:01: 96.25 ± 7.34 TECU (100.0% do Peak)
  3. 2024-12-03 23:49:58: 96.48 ± 7.67 TECU (100.2% do Peak)

Peak #12 (TEC = 96.02 ± 7.28) has a sequence of 3 high values:
  1. 2024-12-03 23:46:58: 95.77 ± 7.22 TECU (99.7% do Peak)
  2. 2024-12-03 23:48:00: 96.02 ± 7.28 TECU (100.0% do Peak)
  3. 2024-12-03 23:49:01: 96.25 ± 7.34 TECU (100.2% do Peak)

Peak #13 (TEC = 95.77 ± 7.22) has a sequence of 3 high values:
  1. 2024-12-03 23:46:01: 95.51 ± 6.65 TECU (99.7% do Peak)
  2. 2024-12-03 23:46:58: 95.77 ± 7.22 TECU (100.0% do Peak)
  3. 2024-12-03 23:48:00: 96.02 ± 7.28 TECU (100.3% do Peak)

Peak #14 (TEC = 95.51 ± 6.65) has a sequence of 3 high values:
  1. 2024-12-03 23:45:00: 95.25 ± 6.17 TECU (99.7% do Peak)
  2. 2024-12-03 23:46:01: 95.51 ± 6.65 TECU (100.0% do Peak)
  3. 2024-12-03 23:46:58: 95.77 ± 7.22 TECU (100.3% do Peak)

Peak #15 (TEC = 95.25 ± 6.17) has a sequence of 3 high values:
  1. 2024-12-03 23:43:58: 94.97 ± 6.05 TECU (99.7% do Peak)
  2. 2024-12-03 23:45:00: 95.25 ± 6.17 TECU (100.0% do Peak)
  3. 2024-12-03 23:46:01: 95.51 ± 6.65 TECU (100.3% do Peak)

Peak #16 (TEC = 94.97 ± 6.05) has a sequence of 3 high values:
  1. 2024-12-03 23:43:01: 94.68 ± 5.86 TECU (99.7% do Peak)
  2. 2024-12-03 23:43:58: 94.97 ± 6.05 TECU (100.0% do Peak)

## SPECIFIC TIMES FOR 12/18

In [10]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('braz_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

# Verificar as colunas disponíveis
print(f"Colunas disponíveis no DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):
    """
    Encontra o valor TEC mais próximo de um datetime específico,
    dentro de uma diferença máxima de minutos especificada.
    """
    # Converte target_datetime para pandas Timestamp se necessário
    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    # Calcula a diferença em minutos absoluta entre cada timestamp e o target
    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    # Filtra apenas valores dentro da diferença máxima permitida
    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    # Encontra o índice do valor mais próximo dentro do range
    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):
    """
    Retorna informações de localização disponíveis no DataFrame
    """
    location_info = {}

    # Verifica quais colunas de localização estão disponíveis
    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):
    """
    Analisa valores TEC próximos a datetimes específicos.

    Parameters:
    target_datetimes: lista de strings ou datetime objects com os horários target
    max_minutes_diff: diferença máxima em minutos para considerar um valor como "próximo"
    """

    print(f"\n{'='*100}")
    print(f"ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS")
    print(f"(Diferença máxima permitida: {max_minutes_diff} minutos)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"BUSCANDO VALORES PRÓXIMOS A: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f"✓ VALOR ENCONTRADO:")
            print(f"  Data/Hora real: {closest_row['DATETIME']}")
            print(f"  Data/Hora alvo: {target_dt}")
            print(f"  Diferença: {time_diff:.2f} minutos")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            # Obter informações de localização disponíveis
            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            # Verifica se há sequência de valores altos
            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f"    {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% do valor)")
            else:
                print(f"  ✗ NÃO possui sequência de 3 valores altos consecutivos")

            # Preparar resultado para a tabela
            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f"✗ NENHUM VALOR ENCONTRADO dentro de {max_minutes_diff} minutos do horário alvo")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    # Tabela resumo
    print(f"\n{'='*120}")
    print(f"TABELA RESUMO DOS RESULTADOS")
    print(f"{'='*120}")

    # Cabeçalho adaptativo baseado nas colunas disponíveis
    header = f"{'#':<3}{'Horário Alvo':<20}{'Horário Encontrado':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequência':<12}"

    # Adicionar colunas de localização disponíveis
    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            # Adicionar informações de localização
            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            # Preencher com N/A para colunas de localização
            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

# Definindo os horários específicos solicitados
target_datetimes = [
    "2024-12-18 18:20:00",
    "2024-12-18 18:10:00",
    "2024-12-18 18:30:00",
    "2024-12-18 18:00:00"
]

print("\n\n" + "*"*50 + " ANÁLISE DOS HORÁRIOS ESPECÍFICOS " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnálise concluída!")

# Informações adicionais sobre os dados encontrados
found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"Valores TEC encontrados:")
    print(f"  Mínimo: {min(tec_values):.2f} TECU")
    print(f"  Máximo: {max(tec_values):.2f} TECU")
    print(f"  Média: {np.mean(tec_values):.2f} TECU")
    print(f"  Desvio padrão: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nSequências de valores altos encontradas: {sequences_found} de {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 42320 records of 2024-12-01 until 2024-12-31
Colunas disponíveis no DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 41633 points after removing missing values


************************************************** ANÁLISE DOS HORÁRIOS ESPECÍFICOS **************************************************

====================================================================================================
ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS
(Diferença máxima permitida: 2 minutos)
====================================================================================================

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:20:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:19:58
  Data/Hora alvo: 2024-12-18 18:20:00
  Diferença: 0.03 minutos
  TEC: 81.52 ± 4.94 TECU
  LATITUDE: -15.95
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:19:01: 81.48 ± 5.04 TECU (100.0% do valor)
    2. 2024-12-18 18:19:58: 81.52 ± 4.94 TECU (100.0% do valor)
    3. 2024-12-18 18:21:00: 81.55 ± 4.92 TECU (100.0% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:10:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:10:01
  Data/Hora alvo: 2024-12-18 18:10:00
  Diferença: 0.02 minutos
  TEC: 80.90 ± 5.24 TECU
  LATITUDE: -15.95
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:08:59: 80.81 ± 5.28 TECU (99.9% do valor)
    2. 2024-12-18 18:10:01: 80.90 ± 5.24 TECU (100.0% do valor)
    3. 2024-12-18 18:10:58: 80.99 ± 5.23 TECU (100.1% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:30:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:30:00
  Data/Hora alvo: 2024-12-18 18:30:00
  Diferença: 0.00 minutos
  TEC: 81.67 ± 4.82 TECU
  LATITUDE: -15.95
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:28:58: 81.67 ± 4.93 TECU (100.0% do valor)
    2. 2024-12-18 18:30:00: 81.67 ± 4.82 TECU (100.0% do valor)
    3. 2024-12-18 18:31:01: 81.66 ± 4.84 TECU (100.0% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:00:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:00:00
  Data/Hora alvo: 2024-12-18 18:00:00
  Diferença: 0.00 minutos
  TEC: 79.74 ± 5.18 TECU
  LATITUDE: -15.95
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 17:58:58: 79.59 ± 4.62 TECU (99.8% do valor)
    2. 2024-12-18 18:00:00: 79.74 ± 5.18 TECU (100.0% do valor)
    3. 2024-12-18 18:01:01: 79.87 ± 5.20 TECU (100.2% do valor)

========================================================================================================================
TABELA RESUMO DOS RESULTADOS
========================================================================================================================
#  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
-------------------------------------------------------------------------------------------------

Análise concluída!

================================================================================
ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS
================================================================================
Valores TEC encontrados:
  Mínimo: 79.74 TECU
  Máximo: 81.67 TECU
  Média: 80.96 TECU
  Desvio padrão: 0.76 TECU

Sequências de valores altos encontradas: 4 de 4 (100.0%)

# IGS

In [11]:
import pandas as pd
import numpy as np

In [12]:
#Download TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [13]:
!gdown '1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp'

Downloading...
From: https://drive.google.com/uc?id=1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp
To: /content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl
100% 3.60M/3.60M [00:00<00:00, 174MB/s]

In [14]:
df_igs_maps_2024 = pd.read_pickle('/content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [15]:
df_igs_maps_2024

               DATETIME                                             TECMAP
0   2024-12-01 00:00:00  [[37.7, 34.6, 31.9, 30.0, 28.6, 27.2, 25.8, 24...
1   2024-12-01 02:00:00  [[20.3, 18.7, 18.1, 18.2, 18.2, 18.1, 17.7, 17...
2   2024-12-01 04:00:00  [[11.6, 11.8, 12.0, 12.4, 13.0, 13.5, 14.0, 14...
3   2024-12-01 06:00:00  [[10.4, 10.8, 11.1, 11.7, 12.1, 12.7, 13.3, 13...
4   2024-12-01 08:00:00  [[9.9, 10.1, 10.3, 10.6, 11.0, 11.6, 12.3, 13....
..                  ...                                                ...
343 2024-12-30 14:00:00  [[8.9, 11.1, 14.4, 18.8, 23.7, 28.3, 32.7, 36....
344 2024-12-30 16:00:00  [[26.3, 29.8, 33.4, 37.1, 40.5, 43.7, 47.0, 49...
345 2024-12-30 18:00:00  [[43.5, 44.5, 45.3, 46.2, 47.1, 48.6, 50.0, 51...
346 2024-12-30 20:00:00  [[48.8, 49.1, 49.0, 48.7, 48.5, 48.1, 48.0, 47...
347 2024-12-30 22:00:00  [[47.0, 46.6, 45.6, 44.4, 43.2, 42.0, 40.4, 38...

[348 rows x 2 columns]

## 12/18/2024 - 18:00

In [16]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:

    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [17]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [18]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [19]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [20]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [21]:
np_igs_maps.shape

(1, 49, 23)

In [22]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(igs_points)

[(-17.5, -50, 25, 12), (-17.5, -45, 25, 13), (-15.0, -50, 26, 12), (-15.0, -45, 26, 13)]

In [23]:
igs_points

[(-17.5, -50, 25, 12),
 (-17.5, -45, 25, 13),
 (-15.0, -50, 26, 12),
 (-15.0, -45, 26, 13)]

In [24]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -50.0°) - Indexes: [25, 12] - TEC:  88.0
   P2: ( -17.5°,  -45.0°) - Indexes: [25, 13] - TEC:  86.5
   P3: ( -15.0°,  -50.0°) - Indexes: [26, 12] - TEC:  83.6
   P4: ( -15.0°,  -45.0°) - Indexes: [26, 13] - TEC:  81.6

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -50.0°) =  88.0
   f_01 (lat_min, lon_max) = ( -17.5°,  -45.0°) =  86.5
   f_10 (lat_max, lon_min) = ( -15.0°,  -50.0°) =  83.6
   f_11 (lat_max, lon_max) = ( -15.0°,  -45.0°) =  81.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 2.12213 /  5.0 = 0.424426

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.55252 /  2.5 = 0.621008

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.424426) * (1 - 0.621008) = 0.218138
   w_01 = t_x * (1 - t_y)       = 0.424426 * (1 - 0.621008)       = 0.160854
   w_10 = (1 - t_x) * t_y       = (1 - 0.424426) * 0.621008       = 0.357436
   w_11 = t_x * t_y             = 0.424426 * 0.621008             = 0.263572
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.218138* 88.0 + 0.160854* 86.5 + 0.357436* 83.6 + 0.263572* 81.6
   Value =  19.1961 +  13.9139 +  29.8817 +  21.5075
   Value = 84.499140

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 42.44% of the way from -50° to -45°
   In Y direction (latitude):  62.10% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 84.4991
============================================================

## 12/22/2024 - 18:00

In [25]:
import pandas as pd

data = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [26]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [27]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [28]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [29]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [30]:
np_igs_maps.shape

(1, 49, 23)

In [31]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(igs_points)

[(-17.5, -50, 25, 12), (-17.5, -45, 25, 13), (-15.0, -50, 26, 12), (-15.0, -45, 26, 13)]

In [32]:
igs_points

[(-17.5, -50, 25, 12),
 (-17.5, -45, 25, 13),
 (-15.0, -50, 26, 12),
 (-15.0, -45, 26, 13)]

In [33]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -50.0°) - Indexes: [25, 12] - TEC:  88.0
   P2: ( -17.5°,  -45.0°) - Indexes: [25, 13] - TEC:  86.5
   P3: ( -15.0°,  -50.0°) - Indexes: [26, 12] - TEC:  83.6
   P4: ( -15.0°,  -45.0°) - Indexes: [26, 13] - TEC:  81.6

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -50.0°) =  88.0
   f_01 (lat_min, lon_max) = ( -17.5°,  -45.0°) =  86.5
   f_10 (lat_max, lon_min) = ( -15.0°,  -50.0°) =  83.6
   f_11 (lat_max, lon_max) = ( -15.0°,  -45.0°) =  81.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 2.12213 /  5.0 = 0.424426

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.55252 /  2.5 = 0.621008

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.424426) * (1 - 0.621008) = 0.218138
   w_01 = t_x * (1 - t_y)       = 0.424426 * (1 - 0.621008)       = 0.160854
   w_10 = (1 - t_x) * t_y       = (1 - 0.424426) * 0.621008       = 0.357436
   w_11 = t_x * t_y             = 0.424426 * 0.621008             = 0.263572
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.218138* 88.0 + 0.160854* 86.5 + 0.357436* 83.6 + 0.263572* 81.6
   Value =  19.1961 +  13.9139 +  29.8817 +  21.5075
   Value = 84.499140

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 42.44% of the way from -50° to -45°
   In Y direction (latitude):  62.10% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 84.4991
============================================================

## 12/19/2024 - 18:00

In [34]:
import pandas as pd

data = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [35]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [36]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [37]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [38]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [39]:
np_igs_maps.shape

(1, 49, 23)

In [40]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):
        """
        Função para encontrar os 4 pontos da grade mais próximos
        a uma coordenada específica
        """
        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(igs_points)

[(-17.5, -50, 25, 12), (-17.5, -45, 25, 13), (-15.0, -50, 26, 12), (-15.0, -45, 26, 13)]

In [41]:
igs_points

[(-17.5, -50, 25, 12),
 (-17.5, -45, 25, 13),
 (-15.0, -50, 26, 12),
 (-15.0, -45, 26, 13)]

In [42]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -50.0°) - Indexes: [25, 12] - TEC:  88.0
   P2: ( -17.5°,  -45.0°) - Indexes: [25, 13] - TEC:  86.5
   P3: ( -15.0°,  -50.0°) - Indexes: [26, 12] - TEC:  83.6
   P4: ( -15.0°,  -45.0°) - Indexes: [26, 13] - TEC:  81.6

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -50.0°) =  88.0
   f_01 (lat_min, lon_max) = ( -17.5°,  -45.0°) =  86.5
   f_10 (lat_max, lon_min) = ( -15.0°,  -50.0°) =  83.6
   f_11 (lat_max, lon_max) = ( -15.0°,  -45.0°) =  81.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 2.12213 /  5.0 = 0.424426

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.55252 /  2.5 = 0.621008

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.424426) * (1 - 0.621008) = 0.218138
   w_01 = t_x * (1 - t_y)       = 0.424426 * (1 - 0.621008)       = 0.160854
   w_10 = (1 - t_x) * t_y       = (1 - 0.424426) * 0.621008       = 0.357436
   w_11 = t_x * t_y             = 0.424426 * 0.621008             = 0.263572
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.218138* 88.0 + 0.160854* 86.5 + 0.357436* 83.6 + 0.263572* 81.6
   Value =  19.1961 +  13.9139 +  29.8817 +  21.5075
   Value = 84.499140

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 42.44% of the way from -50° to -45°
   In Y direction (latitude):  62.10% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 84.4991
============================================================

## 12/01/2024 - 18:00

In [43]:
import pandas as pd

data = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [44]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [45]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [46]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [47]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [48]:
np_igs_maps.shape

(1, 49, 23)

In [49]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):
        """
        Função para encontrar os 4 pontos da grade mais próximos
        a uma coordenada específica
        """
        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(igs_points)

[(-17.5, -50, 25, 12), (-17.5, -45, 25, 13), (-15.0, -50, 26, 12), (-15.0, -45, 26, 13)]

In [50]:
igs_points

[(-17.5, -50, 25, 12),
 (-17.5, -45, 25, 13),
 (-15.0, -50, 26, 12),
 (-15.0, -45, 26, 13)]

In [51]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -50.0°) - Indexes: [25, 12] - TEC:  88.0
   P2: ( -17.5°,  -45.0°) - Indexes: [25, 13] - TEC:  86.5
   P3: ( -15.0°,  -50.0°) - Indexes: [26, 12] - TEC:  83.6
   P4: ( -15.0°,  -45.0°) - Indexes: [26, 13] - TEC:  81.6

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -50.0°) =  88.0
   f_01 (lat_min, lon_max) = ( -17.5°,  -45.0°) =  86.5
   f_10 (lat_max, lon_min) = ( -15.0°,  -50.0°) =  83.6
   f_11 (lat_max, lon_max) = ( -15.0°,  -45.0°) =  81.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 2.12213 /  5.0 = 0.424426

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.55252 /  2.5 = 0.621008

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.424426) * (1 - 0.621008) = 0.218138
   w_01 = t_x * (1 - t_y)       = 0.424426 * (1 - 0.621008)       = 0.160854
   w_10 = (1 - t_x) * t_y       = (1 - 0.424426) * 0.621008       = 0.357436
   w_11 = t_x * t_y             = 0.424426 * 0.621008             = 0.263572
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.218138* 88.0 + 0.160854* 86.5 + 0.357436* 83.6 + 0.263572* 81.6
   Value =  19.1961 +  13.9139 +  29.8817 +  21.5075
   Value = 84.499140

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 42.44% of the way from -50° to -45°
   In Y direction (latitude):  62.10% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 84.4991
============================================================

# Nagoya

In [52]:
import pandas as pd
import numpy as np

In [53]:
#Download TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [54]:
!gdown '1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR'

Downloading...
From (original): https://drive.google.com/uc?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR
From (redirected): https://drive.google.com/uc?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR&confirm=t&uuid=3aea3348-7bed-4964-a508-9bffecd6cc9c
To: /content/TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl
100% 4.03G/4.03G [00:32<00:00, 123MB/s]

In [55]:
df_nagoya_maps_2024 = pd.read_pickle('TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [56]:
df_nagoya_maps_2024

                DATETIME                                             TECMAP
0    2024-12-01 00:00:00  [[18.593109130859375, 19.42150115966797, 19.42...
1    2024-12-01 00:05:00  [[18.222612380981445, 18.222612380981445, 18.2...
2    2024-12-01 00:10:00  [[18.21422576904297, 18.21422576904297, 18.214...
3    2024-12-01 00:15:00  [[18.284513473510742, 18.284513473510742, 18.0...
4    2024-12-01 00:20:00  [[18.328298568725586, 18.328298568725586, 18.0...
...                  ...                                                ...
8347 2024-12-30 23:35:00  [[26.173906326293945, 27.259140014648438, 27.2...
8348 2024-12-30 23:40:00  [[27.0389347076416, 27.0389347076416, 27.03893...
8349 2024-12-30 23:45:00  [[26.902502059936523, 26.72080421447754, 25.94...
8350 2024-12-30 23:50:00  [[27.88735580444336, 27.88735580444336, 27.887...
8351 2024-12-30 23:55:00  [[24.682987213134766, 25.294950485229492, 25.2...

[8352 rows x 2 columns]

## 12/18/2024 - 18:20

In [57]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [58]:
result

                DATETIME                                             TECMAP
4828 2024-12-18 18:20:00  [[18.751976013183594, 18.751976013183594, 18.8...

In [59]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [60]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [61]:
np_nagoya_maps

array([[[18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.25943375, 18.13648224, 18.13648224, ...,         nan,
                 nan,         nan],
        ...,
        [38.79235458, 39.10980225, 39.51619339, ..., 13.45065308,
         13.1072731 , 12.96411705],
        [38.38473892, 38.68589783, 39.00465393, ..., 13.27555275,
         12.90675449, 12.72219276],
        [38.23902512, 38.27802277, 38.43577194, ..., 12.968153  ,
         12.60940075, 12.51128292]]])

In [62]:
np_nagoya_maps.shape

(1, 242, 221)

In [63]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(nagoya_points)

[(-16.400000000000006, -48.0, 128, 124), (-16.400000000000006, -47.5, 128, 125), (-15.900000000000006, -48.0, 129, 124), (-15.900000000000006, -47.5, 129, 125)]

In [64]:
nagoya_points

[(-16.400000000000006, -48.0, 128, 124),
 (-16.400000000000006, -47.5, 128, 125),
 (-15.900000000000006, -48.0, 129, 124),
 (-15.900000000000006, -47.5, 129, 125)]

In [65]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.4°,  -48.0°) - Indexes: [128, 124] - TEC:  86.1
   P2: ( -16.4°,  -47.5°) - Indexes: [128, 125] - TEC:  85.8
   P3: ( -15.9°,  -48.0°) - Indexes: [129, 124] - TEC:  86.5
   P4: ( -15.9°,  -47.5°) - Indexes: [129, 125] - TEC:  85.8

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.4° to  -15.9° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.4°,  -48.0°) =  86.1
   f_01 (lat_min, lon_max) = ( -16.4°,  -47.5°) =  85.8
   f_10 (lat_max, lon_min) = ( -15.9°,  -48.0°) =  86.5
   f_11 (lat_max, lon_max) = ( -15.9°,  -47.5°) =  85.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.4)) / ( -15.9 - ( -16.4))
   t_y = 0.45252 /  0.5 = 0.905040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.905040) = 0.071765
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.905040)       = 0.023195
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.905040       = 0.683975
   w_11 = t_x * t_y             = 0.244260 * 0.905040             = 0.221065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.071765* 86.1 + 0.023195* 85.8 + 0.683975* 86.5 + 0.221065* 85.8
   Value =   6.1821 +   1.9895 +  59.1901 +  18.9635
   Value = 86.325173

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  90.50% of the way from -16.400000000000006° to -15.900000000000006°

============================================================
FINAL RESULT: TEC = 86.3252
============================================================

### RMSE/MAE

In [66]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [68]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(86.3252, y_pred)
# rmse = np.sqrt(mean_squared_error(86.3252, y_pred))

## 12/18/2024 - 18:10

In [69]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [70]:
result

                DATETIME                                             TECMAP
4826 2024-12-18 18:10:00  [[18.412939071655273, 17.651090621948242, 17.6...

In [71]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [72]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [73]:
np_nagoya_maps

array([[[18.41293907, 17.65109062, 17.65109062, ...,         nan,
                 nan,         nan],
        [18.53962135, 17.62540054, 17.62540054, ...,         nan,
                 nan,         nan],
        [17.62013054, 17.62013054, 17.62540054, ...,         nan,
                 nan,         nan],
        ...,
        [36.95772552, 37.32144928, 37.6816864 , ..., 14.07102394,
         13.53792286, 13.37452602],
        [37.09318542, 37.28800964, 37.65478134, ..., 13.818923  ,
         13.44021893, 13.28282356],
        [36.133461  , 36.14941025, 36.71422577, ..., 13.40729332,
         13.00967979, 13.02010918]]])

In [74]:
np_nagoya_maps.shape

(1, 242, 221)

In [75]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(nagoya_points)

[(-16.400000000000006, -48.0, 128, 124), (-16.400000000000006, -47.5, 128, 125), (-15.900000000000006, -48.0, 129, 124), (-15.900000000000006, -47.5, 129, 125)]

In [76]:
nagoya_points

[(-16.400000000000006, -48.0, 128, 124),
 (-16.400000000000006, -47.5, 128, 125),
 (-15.900000000000006, -48.0, 129, 124),
 (-15.900000000000006, -47.5, 129, 125)]

In [77]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.4°,  -48.0°) - Indexes: [128, 124] - TEC:  87.5
   P2: ( -16.4°,  -47.5°) - Indexes: [128, 125] - TEC:  91.0
   P3: ( -15.9°,  -48.0°) - Indexes: [129, 124] - TEC:  75.7
   P4: ( -15.9°,  -47.5°) - Indexes: [129, 125] - TEC:  78.8

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.4° to  -15.9° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.4°,  -48.0°) =  87.5
   f_01 (lat_min, lon_max) = ( -16.4°,  -47.5°) =  91.0
   f_10 (lat_max, lon_min) = ( -15.9°,  -48.0°) =  75.7
   f_11 (lat_max, lon_max) = ( -15.9°,  -47.5°) =  78.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.4)) / ( -15.9 - ( -16.4))
   t_y = 0.45252 /  0.5 = 0.905040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.905040) = 0.071765
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.905040)       = 0.023195
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.905040       = 0.683975
   w_11 = t_x * t_y             = 0.244260 * 0.905040             = 0.221065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.071765* 87.5 + 0.023195* 91.0 + 0.683975* 75.7 + 0.221065* 78.8
   Value =   6.2816 +   2.1111 +  51.7680 +  17.4171
   Value = 77.577780

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  90.50% of the way from -16.400000000000006° to -15.900000000000006°

============================================================
FINAL RESULT: TEC = 77.5778
============================================================

### RMSE/MAE

In [78]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [79]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(77.5778, y_pred)
# rmse = np.sqrt(mean_squared_error(77.5778, y_pred))

## 12/18/2024 - 18:30

In [80]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [81]:
result

                DATETIME                                             TECMAP
4830 2024-12-18 18:30:00  [[21.299997329711914, 21.299997329711914, 21.2...

In [82]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [83]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [84]:
np_nagoya_maps

array([[[21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.28308678, 21.28308678, 21.28308678, ...,         nan,
                 nan,         nan],
        ...,
        [39.65393066, 40.11976624, 40.50592804, ..., 13.14062977,
         12.80635357, 12.63247967],
        [39.26050949, 39.7519455 , 40.19271851, ..., 12.65815067,
         12.54124069, 12.46903992],
        [39.23273468, 39.40169144, 39.72786331, ..., 12.41631317,
         12.32884121, 12.25786972]]])

In [85]:
np_nagoya_maps.shape

(1, 242, 221)

In [86]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(nagoya_points)

[(-16.400000000000006, -48.0, 128, 124), (-16.400000000000006, -47.5, 128, 125), (-15.900000000000006, -48.0, 129, 124), (-15.900000000000006, -47.5, 129, 125)]

In [87]:
nagoya_points

[(-16.400000000000006, -48.0, 128, 124),
 (-16.400000000000006, -47.5, 128, 125),
 (-15.900000000000006, -48.0, 129, 124),
 (-15.900000000000006, -47.5, 129, 125)]

In [88]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.4°,  -48.0°) - Indexes: [128, 124] - TEC:  83.6
   P2: ( -16.4°,  -47.5°) - Indexes: [128, 125] - TEC:  83.0
   P3: ( -15.9°,  -48.0°) - Indexes: [129, 124] - TEC:  82.7
   P4: ( -15.9°,  -47.5°) - Indexes: [129, 125] - TEC:  81.3

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.4° to  -15.9° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.4°,  -48.0°) =  83.6
   f_01 (lat_min, lon_max) = ( -16.4°,  -47.5°) =  83.0
   f_10 (lat_max, lon_min) = ( -15.9°,  -48.0°) =  82.7
   f_11 (lat_max, lon_max) = ( -15.9°,  -47.5°) =  81.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.4)) / ( -15.9 - ( -16.4))
   t_y = 0.45252 /  0.5 = 0.905040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.905040) = 0.071765
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.905040)       = 0.023195
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.905040       = 0.683975
   w_11 = t_x * t_y             = 0.244260 * 0.905040             = 0.221065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.071765* 83.6 + 0.023195* 83.0 + 0.683975* 82.7 + 0.221065* 81.3
   Value =   6.0025 +   1.9257 +  56.5953 +  17.9765
   Value = 82.499926

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  90.50% of the way from -16.400000000000006° to -15.900000000000006°

============================================================
FINAL RESULT: TEC = 82.4999
============================================================

### RMSE/MAE

In [89]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [90]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(82.4999, y_pred)
# rmse = np.sqrt(mean_squared_error(82.4999, y_pred))

## 12/18/2024 - 18:00

In [91]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [92]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [93]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [94]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [95]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [96]:
np_nagoya_maps.shape

(1, 242, 221)

In [97]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(nagoya_points)

[(-16.400000000000006, -48.0, 128, 124), (-16.400000000000006, -47.5, 128, 125), (-15.900000000000006, -48.0, 129, 124), (-15.900000000000006, -47.5, 129, 125)]

In [98]:
nagoya_points

[(-16.400000000000006, -48.0, 128, 124),
 (-16.400000000000006, -47.5, 128, 125),
 (-15.900000000000006, -48.0, 129, 124),
 (-15.900000000000006, -47.5, 129, 125)]

In [99]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.4°,  -48.0°) - Indexes: [128, 124] - TEC:  84.5
   P2: ( -16.4°,  -47.5°) - Indexes: [128, 125] - TEC:  82.6
   P3: ( -15.9°,  -48.0°) - Indexes: [129, 124] - TEC:  82.1
   P4: ( -15.9°,  -47.5°) - Indexes: [129, 125] - TEC:  83.1

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.4° to  -15.9° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.4°,  -48.0°) =  84.5
   f_01 (lat_min, lon_max) = ( -16.4°,  -47.5°) =  82.6
   f_10 (lat_max, lon_min) = ( -15.9°,  -48.0°) =  82.1
   f_11 (lat_max, lon_max) = ( -15.9°,  -47.5°) =  83.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.4)) / ( -15.9 - ( -16.4))
   t_y = 0.45252 /  0.5 = 0.905040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.905040) = 0.071765
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.905040)       = 0.023195
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.905040       = 0.683975
   w_11 = t_x * t_y             = 0.244260 * 0.905040             = 0.221065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.071765* 84.5 + 0.023195* 82.6 + 0.683975* 82.1 + 0.221065* 83.1
   Value =   6.0672 +   1.9163 +  56.1447 +  18.3615
   Value = 82.489682

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  90.50% of the way from -16.400000000000006° to -15.900000000000006°

============================================================
FINAL RESULT: TEC = 82.4897
============================================================

### RMSE/MAE

In [100]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [101]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(82.4897, y_pred)
# rmse = np.sqrt(mean_squared_error(82.4897, y_pred))

## 12/22/2024 - 18:00

In [102]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [103]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [104]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [105]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [106]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [107]:
np_nagoya_maps.shape

(1, 242, 221)

In [108]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(nagoya_points)

[(-16.400000000000006, -48.0, 128, 124), (-16.400000000000006, -47.5, 128, 125), (-15.900000000000006, -48.0, 129, 124), (-15.900000000000006, -47.5, 129, 125)]

In [109]:
nagoya_points

[(-16.400000000000006, -48.0, 128, 124),
 (-16.400000000000006, -47.5, 128, 125),
 (-15.900000000000006, -48.0, 129, 124),
 (-15.900000000000006, -47.5, 129, 125)]

In [110]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.4°,  -48.0°) - Indexes: [128, 124] - TEC:  84.5
   P2: ( -16.4°,  -47.5°) - Indexes: [128, 125] - TEC:  82.6
   P3: ( -15.9°,  -48.0°) - Indexes: [129, 124] - TEC:  82.1
   P4: ( -15.9°,  -47.5°) - Indexes: [129, 125] - TEC:  83.1

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.4° to  -15.9° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.4°,  -48.0°) =  84.5
   f_01 (lat_min, lon_max) = ( -16.4°,  -47.5°) =  82.6
   f_10 (lat_max, lon_min) = ( -15.9°,  -48.0°) =  82.1
   f_11 (lat_max, lon_max) = ( -15.9°,  -47.5°) =  83.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.4)) / ( -15.9 - ( -16.4))
   t_y = 0.45252 /  0.5 = 0.905040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.905040) = 0.071765
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.905040)       = 0.023195
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.905040       = 0.683975
   w_11 = t_x * t_y             = 0.244260 * 0.905040             = 0.221065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.071765* 84.5 + 0.023195* 82.6 + 0.683975* 82.1 + 0.221065* 83.1
   Value =   6.0672 +   1.9163 +  56.1447 +  18.3615
   Value = 82.489682

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  90.50% of the way from -16.400000000000006° to -15.900000000000006°

============================================================
FINAL RESULT: TEC = 82.4897
============================================================

### RMSE/MAE

In [111]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [112]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(82.4897, y_pred)
# rmse = np.sqrt(mean_squared_error(82.4897, y_pred))

## 12/19/2024 - 18:00

In [113]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [114]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [115]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [116]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [117]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [118]:
np_nagoya_maps.shape

(1, 242, 221)

In [119]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(nagoya_points)

[(-16.400000000000006, -48.0, 128, 124), (-16.400000000000006, -47.5, 128, 125), (-15.900000000000006, -48.0, 129, 124), (-15.900000000000006, -47.5, 129, 125)]

In [120]:
nagoya_points

[(-16.400000000000006, -48.0, 128, 124),
 (-16.400000000000006, -47.5, 128, 125),
 (-15.900000000000006, -48.0, 129, 124),
 (-15.900000000000006, -47.5, 129, 125)]

In [121]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.4°,  -48.0°) - Indexes: [128, 124] - TEC:  84.5
   P2: ( -16.4°,  -47.5°) - Indexes: [128, 125] - TEC:  82.6
   P3: ( -15.9°,  -48.0°) - Indexes: [129, 124] - TEC:  82.1
   P4: ( -15.9°,  -47.5°) - Indexes: [129, 125] - TEC:  83.1

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.4° to  -15.9° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.4°,  -48.0°) =  84.5
   f_01 (lat_min, lon_max) = ( -16.4°,  -47.5°) =  82.6
   f_10 (lat_max, lon_min) = ( -15.9°,  -48.0°) =  82.1
   f_11 (lat_max, lon_max) = ( -15.9°,  -47.5°) =  83.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.4)) / ( -15.9 - ( -16.4))
   t_y = 0.45252 /  0.5 = 0.905040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.905040) = 0.071765
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.905040)       = 0.023195
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.905040       = 0.683975
   w_11 = t_x * t_y             = 0.244260 * 0.905040             = 0.221065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.071765* 84.5 + 0.023195* 82.6 + 0.683975* 82.1 + 0.221065* 83.1
   Value =   6.0672 +   1.9163 +  56.1447 +  18.3615
   Value = 82.489682

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  90.50% of the way from -16.400000000000006° to -15.900000000000006°

============================================================
FINAL RESULT: TEC = 82.4897
============================================================

### RMSE/MAE

In [122]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [123]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(82.4897, y_pred)
# rmse = np.sqrt(mean_squared_error(82.4897, y_pred))

## 12/01/2024 - 18:00

In [124]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [125]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [126]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [127]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [128]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [129]:
np_nagoya_maps.shape

(1, 242, 221)

In [130]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(nagoya_points)

[(-16.400000000000006, -48.0, 128, 124), (-16.400000000000006, -47.5, 128, 125), (-15.900000000000006, -48.0, 129, 124), (-15.900000000000006, -47.5, 129, 125)]

In [131]:
nagoya_points

[(-16.400000000000006, -48.0, 128, 124),
 (-16.400000000000006, -47.5, 128, 125),
 (-15.900000000000006, -48.0, 129, 124),
 (-15.900000000000006, -47.5, 129, 125)]

In [132]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.4°,  -48.0°) - Indexes: [128, 124] - TEC:  84.5
   P2: ( -16.4°,  -47.5°) - Indexes: [128, 125] - TEC:  82.6
   P3: ( -15.9°,  -48.0°) - Indexes: [129, 124] - TEC:  82.1
   P4: ( -15.9°,  -47.5°) - Indexes: [129, 125] - TEC:  83.1

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.4° to  -15.9° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.4°,  -48.0°) =  84.5
   f_01 (lat_min, lon_max) = ( -16.4°,  -47.5°) =  82.6
   f_10 (lat_max, lon_min) = ( -15.9°,  -48.0°) =  82.1
   f_11 (lat_max, lon_max) = ( -15.9°,  -47.5°) =  83.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.4)) / ( -15.9 - ( -16.4))
   t_y = 0.45252 /  0.5 = 0.905040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.905040) = 0.071765
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.905040)       = 0.023195
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.905040       = 0.683975
   w_11 = t_x * t_y             = 0.244260 * 0.905040             = 0.221065
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.071765* 84.5 + 0.023195* 82.6 + 0.683975* 82.1 + 0.221065* 83.1
   Value =   6.0672 +   1.9163 +  56.1447 +  18.3615
   Value = 82.489682

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  90.50% of the way from -16.400000000000006° to -15.900000000000006°

============================================================
FINAL RESULT: TEC = 82.4897
============================================================

### RMSE/MAE

In [133]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [134]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

# EMBRACE

In [135]:
import pandas as pd
import numpy as np

In [136]:
#Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [137]:
!gdown '1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH'

Downloading...
From (original): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH
From (redirected): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH&confirm=t&uuid=e4b71a84-449e-4d82-aabd-28a9a190b89e
To: /content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl
100% 157M/157M [00:01<00:00, 97.3MB/s]

In [138]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [139]:
df_embrace_maps_2024

                                                                TECMAP
DATETIME
2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[16704 rows x 1 columns]

## 12/18/2024 - 18:20

In [140]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [141]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [142]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [143]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [144]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [145]:
np_embrace_maps.shape

(1, 41, 25)

In [146]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(embrace_points)

[(-16, -50.0, 22, 16), (-16, -47.5, 22, 17), (-14, -50.0, 23, 16), (-14, -47.5, 23, 17)]

In [147]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [148]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  82.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  87.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  79.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  82.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  82.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  87.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  79.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  82.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 82.0 + 0.826561* 87.0 + 0.003969* 79.0 + 0.022291* 82.0
   Value =  12.0687 +  71.9108 +   0.3136 +   1.8278
   Value = 86.120898

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 86.1209
============================================================

### RMSE/MAE

In [149]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [150]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/18/2024 - 18:10

In [151]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [152]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [153]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [154]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [155]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 37., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [156]:
np_embrace_maps.shape

(1, 41, 25)

In [157]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(embrace_points)

[(-16, -50.0, 22, 16), (-16, -47.5, 22, 17), (-14, -50.0, 23, 16), (-14, -47.5, 23, 17)]

In [158]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [159]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  81.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  83.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  87.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  79.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  81.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  83.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  87.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  79.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 81.0 + 0.826561* 83.0 + 0.003969* 87.0 + 0.022291* 79.0
   Value =  11.9215 +  68.6046 +   0.3453 +   1.7610
   Value = 82.632355

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 82.6324
============================================================

### RMSE/MAE

In [160]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [161]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/18/2024 - 18:30

In [162]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [163]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [164]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [165]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [166]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [167]:
np_embrace_maps.shape

(1, 41, 25)

In [168]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(embrace_points)

[(-16, -50.0, 22, 16), (-16, -47.5, 22, 17), (-14, -50.0, 23, 16), (-14, -47.5, 23, 17)]

In [169]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [170]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  81.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  91.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  79.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  81.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  81.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  91.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  79.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  81.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 81.0 + 0.826561* 91.0 + 0.003969* 79.0 + 0.022291* 81.0
   Value =  11.9215 +  75.2171 +   0.3136 +   1.8056
   Value = 89.257673

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 89.2577
============================================================

### RMSE/MAE

In [171]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [172]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/18/2024 - 18:00

In [173]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [174]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [175]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [176]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [177]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [178]:
np_embrace_maps.shape

(1, 41, 25)

In [179]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(embrace_points)

[(-16, -50.0, 22, 16), (-16, -47.5, 22, 17), (-14, -50.0, 23, 16), (-14, -47.5, 23, 17)]

In [180]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [181]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  79.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  82.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  71.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  75.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  79.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  82.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  71.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  75.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 79.0 + 0.826561* 82.0 + 0.003969* 71.0 + 0.022291* 75.0
   Value =  11.6271 +  67.7780 +   0.2818 +   1.6718
   Value = 81.358767

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 81.3588
============================================================

### RMSE/MAE

In [182]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [183]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/22/2024 - 18:00

In [184]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [185]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [186]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [187]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [188]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [189]:
np_embrace_maps.shape

(1, 41, 25)

In [190]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(embrace_points)

[(-16, -50.0, 22, 16), (-16, -47.5, 22, 17), (-14, -50.0, 23, 16), (-14, -47.5, 23, 17)]

In [191]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [192]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  79.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  82.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  71.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  75.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  79.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  82.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  71.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  75.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 79.0 + 0.826561* 82.0 + 0.003969* 71.0 + 0.022291* 75.0
   Value =  11.6271 +  67.7780 +   0.2818 +   1.6718
   Value = 81.358767

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 81.3588
============================================================

### RMSE/MAE

In [193]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [194]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/19/2024 - 18:00

In [195]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [196]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [197]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [198]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [199]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [200]:
np_embrace_maps.shape

(1, 41, 25)

In [201]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(embrace_points)

[(-16, -50.0, 22, 16), (-16, -47.5, 22, 17), (-14, -50.0, 23, 16), (-14, -47.5, 23, 17)]

In [202]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [203]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  79.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  82.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  71.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  75.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  79.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  82.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  71.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  75.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 79.0 + 0.826561* 82.0 + 0.003969* 71.0 + 0.022291* 75.0
   Value =  11.6271 +  67.7780 +   0.2818 +   1.6718
   Value = 81.358767

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 81.3588
============================================================

### RMSE/MAE

In [204]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [205]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/01/2024 - 18:00

In [206]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [207]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [208]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [209]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [210]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [211]:
np_embrace_maps.shape

(1, 41, 25)

In [212]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(embrace_points)

[(-16, -50.0, 22, 16), (-16, -47.5, 22, 17), (-14, -50.0, 23, 16), (-14, -47.5, 23, 17)]

In [213]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [214]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  79.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  82.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  71.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  75.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  79.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  82.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  71.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  75.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 79.0 + 0.826561* 82.0 + 0.003969* 71.0 + 0.022291* 75.0
   Value =  11.6271 +  67.7780 +   0.2818 +   1.6718
   Value = 81.358767

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 81.3588
============================================================

### RMSE/MAE

In [221]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [222]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

# MAGGIA

In [223]:
import pandas as pd
import numpy as np

In [224]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [225]:
!gdown '1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33'

Downloading...
From (original): https://drive.google.com/uc?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33
From (redirected): https://drive.google.com/uc?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33&confirm=t&uuid=4a7001b1-d196-4d50-ab0c-1ae43d963622
To: /content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl
100% 7.51G/7.51G [00:52<00:00, 142MB/s]

In [226]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [227]:
df_maggia_maps_2024

                 DATETIME                                             TECMAP
0     2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2024-09-05 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
15619 2024-12-31 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15620 2024-12-31 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15621 2024-12-31 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15622 2024-12-31 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15623 2024-12-31 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[15624 rows x 2 columns]

## 12/18/2024 - 18:20

In [228]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [229]:
result

                 DATETIME                                             TECMAP
13718 2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [230]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [231]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [232]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [40.14899826, 40.15000153, 40.18000031, ..., 13.84500027,
         13.67500019, 13.12800026],
        [39.97399902, 40.02799988, 40.15399933, ..., 13.75800037,
         13.67599964, 12.39599991],
        [39.73500061, 39.83499908, 40.02500153, ..., 13.10700035,
         12.6239996 , 12.06000042]]])

In [233]:
np_maggia_maps.shape

(1, 241, 221)

In [234]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(maggia_points)

[(-16.0, -48.0, 128, 124), (-16.0, -47.5, 128, 125), (-15.5, -48.0, 129, 124), (-15.5, -47.5, 129, 125)]

In [235]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [236]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC: 101.5
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC: 102.8
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC: 103.5
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC: 102.8

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) = 101.5
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) = 102.8
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) = 103.5
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) = 102.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357*101.5 + 0.218603*102.8 + 0.079383*103.5 + 0.025657*102.8
   Value =  68.6543 +  22.4630 +   8.2154 +   2.6364
   Value = 101.969143

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 101.9691
============================================================

### RMSE/MAE

In [237]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [238]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/18/2024 - 18:10

In [239]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [240]:
result

                 DATETIME                                             TECMAP
13717 2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [241]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [242]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [243]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [36.83499908, 37.06399918, 37.23899841, ..., 12.40799999,
         12.40799999, 12.40799999],
        [36.57699966, 36.82799911, 37.03300095, ..., 12.85900021,
         12.6619997 , 12.54399967],
        [36.34600067, 36.5909996 , 36.81399918, ..., 13.00500011,
         12.82999992, 12.32600021]]])

In [244]:
np_maggia_maps.shape

(1, 241, 221)

In [245]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(maggia_points)

[(-16.0, -48.0, 128, 124), (-16.0, -47.5, 128, 125), (-15.5, -48.0, 129, 124), (-15.5, -47.5, 129, 125)]

In [246]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [247]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC: 100.4
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC: 101.1
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC: 100.3
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC:  99.6

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) = 100.4
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) = 101.1
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) = 100.3
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) =  99.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357*100.4 + 0.218603*101.1 + 0.079383*100.3 + 0.025657* 99.6
   Value =  67.9177 +  22.1029 +   7.9610 +   2.5553
   Value = 100.536952

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 100.5370
============================================================

### RMSE/MAE

In [248]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [249]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/18/2024 - 18:30

In [250]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [251]:
result

                 DATETIME                                             TECMAP
13719 2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [252]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [253]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [254]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.94900131, 41.94900131, 41.94900131, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.94400024, 41.94400024, 41.94499969, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.89500046, 41.89799881, 41.90100098, ..., 11.36600018,
         11.25800037, 11.1960001 ]]])

In [255]:
np_maggia_maps.shape

(1, 241, 221)

In [256]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(maggia_points)

[(-16.0, -48.0, 128, 124), (-16.0, -47.5, 128, 125), (-15.5, -48.0, 129, 124), (-15.5, -47.5, 129, 125)]

In [257]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [258]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC:  97.8
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC:  95.6
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC: 100.8
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC: 102.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) =  97.8
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  95.6
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) = 100.8
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) = 102.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357* 97.8 + 0.218603* 95.6 + 0.079383*100.8 + 0.025657*102.0
   Value =  66.1464 +  20.8958 +   8.0028 +   2.6162
   Value = 97.661240

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 97.6612
============================================================

### RMSE/MAE

In [259]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [260]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/18/2024 - 18:00

In [261]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [262]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [263]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [264]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [265]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [266]:
np_maggia_maps.shape

(1, 241, 221)

In [267]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(maggia_points)

[(-16.0, -48.0, 128, 124), (-16.0, -47.5, 128, 125), (-15.5, -48.0, 129, 124), (-15.5, -47.5, 129, 125)]

In [268]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [269]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC: 100.4
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC:  97.8
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC: 100.9
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC:  97.8

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) = 100.4
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  97.8
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) = 100.9
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) =  97.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357*100.4 + 0.218603* 97.8 + 0.079383*100.9 + 0.025657* 97.8
   Value =  67.8860 +  21.3752 +   8.0106 +   2.5088
   Value = 99.780559

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 99.7806
============================================================

### RMSE/MAE

In [270]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [271]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/22/2024 - 18:00

In [272]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [273]:
result

                 DATETIME                                             TECMAP
14292 2024-12-22 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [274]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [275]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [276]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.41400146, 48.5379982 , 48.59199905, ..., 19.10899925,
         17.45599937, 17.45599937],
        [48.26200104, 48.41799927, 48.52799988, ..., 18.8560009 ,
         18.24600029, 17.79299927],
        [48.11100006, 48.27999878, 48.42100143, ..., 19.0890007 ,
         18.74200058, 18.39999962]]])

In [277]:
np_maggia_maps.shape

(1, 241, 221)

In [278]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(maggia_points)

[(-16.0, -48.0, 128, 124), (-16.0, -47.5, 128, 125), (-15.5, -48.0, 129, 124), (-15.5, -47.5, 129, 125)]

In [279]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [280]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC:  94.4
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC:  94.9
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC:  91.5
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC:  97.8

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) =  94.4
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  94.9
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) =  91.5
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) =  97.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357* 94.4 + 0.218603* 94.9 + 0.079383* 91.5 + 0.025657* 97.8
   Value =  63.8305 +  20.7500 +   7.2623 +   2.5095
   Value = 94.352396

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 94.3524
============================================================

### RMSE/MAE

In [281]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [282]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/19/2024 - 18:00

In [283]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [284]:
result

                 DATETIME                                             TECMAP
13860 2024-12-19 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [285]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [286]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [287]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [37.94499969, 38.06100082, 38.13499832, ..., 11.56599998,
         11.17399979, 10.60200024],
        [37.7840004 , 37.92599869, 38.02999878, ..., 11.47599983,
         10.99199963, 10.38300037],
        [37.63499832, 37.77899933, 37.90499878, ..., 11.36100006,
         10.8739996 , 10.52200031]]])

In [288]:
np_maggia_maps.shape

(1, 241, 221)

In [289]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(maggia_points)

[(-16.0, -48.0, 128, 124), (-16.0, -47.5, 128, 125), (-15.5, -48.0, 129, 124), (-15.5, -47.5, 129, 125)]

In [290]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [291]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC:  85.8
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC:  83.9
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC:  87.1
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC:  83.9

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) =  85.8
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  83.9
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) =  87.1
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) =  83.9

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357* 85.8 + 0.218603* 83.9 + 0.079383* 87.1 + 0.025657* 83.9
   Value =  58.0639 +  18.3329 +   6.9145 +   2.1517
   Value = 85.463013

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 85.4630
============================================================

### RMSE/MAE

In [292]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [293]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))

## 12/01/2024 - 18:00

In [294]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [295]:
result

                 DATETIME                                             TECMAP
11268 2024-12-01 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [296]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [297]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [298]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [45.95299911, 45.88100052, 45.71300125, ..., 23.45899963,
         23.20400047, 22.93400002],
        [45.90299988, 45.8370018 , 45.67300034, ..., 23.38800049,
         23.23900032, 23.04000092],
        [45.86399841, 45.79700089, 45.63999939, ..., 23.29700089,
         23.1590004 , 23.00300026]]])

In [299]:
np_maggia_maps.shape

(1, 241, 221)

In [300]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)
print(maggia_points)

[(-16.0, -48.0, 128, 124), (-16.0, -47.5, 128, 125), (-15.5, -48.0, 129, 124), (-15.5, -47.5, 129, 125)]

In [301]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [302]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC:  92.5
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC:  94.9
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC:  93.6
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC:  93.8

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) =  92.5
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  94.9
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) =  93.6
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) =  93.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357* 92.5 + 0.218603* 94.9 + 0.079383* 93.6 + 0.025657* 93.8
   Value =  62.5806 +  20.7518 +   7.4321 +   2.4074
   Value = 93.171949

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 93.1719
============================================================

### RMSE/MAE

In [303]:
# ========================================================================================================================
# TABELA RESUMO DOS RESULTADOS
# ========================================================================================================================
# #  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
# -------------------------------------------------------------------------------------------------
# 1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    81.52    4.94    Sim         -15.95
# 2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    80.90    5.24    Sim         -15.95
# 3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    81.67    4.82    Sim         -15.95
# 4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    79.74    5.18    Sim         -15.95
# -------------------------------------------------------------------------------------------------

# Análise concluída!

In [305]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# # mae = mean_absolute_error(y_true, y_pred)
# rmse = np.sqrt(mean_squared_error(y_true, y_pred))