# Gopi TEC SJC analysis - December/2024

In [1]:
#Download Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [2]:
!gdown '1PxTO3tsOMgFFKpMf9bRqtvvvDQhC7xMm'

Downloading...
From (original): https://drive.google.com/uc?id=1PxTO3tsOMgFFKpMf9bRqtvvvDQhC7xMm
From (redirected): https://drive.google.com/uc?id=1PxTO3tsOMgFFKpMf9bRqtvvvDQhC7xMm&confirm=t&uuid=807f5415-fa4b-4baa-93c7-c791f050cab8
To: /content/Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip
100% 57.5M/57.5M [00:00<00:00, 58.8MB/s]

In [3]:
%pwd

'/content'

In [4]:
!ls

Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip  sample_data

In [5]:
!unzip 'Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: missing_sjsp_2024.txt
  inflating: sjsp271-2024-09-27.Bias
  inflating: sjsp271-2024-09-27.Cmn
  inflating: sjsp271-2024-09-27.Std
  inflating: sjsp271-2024-09-27-wbias.png
  inflating: sjsp336-2024-12-01.Bias
  inflating: sjsp336-2024-12-01.Cmn
  inflating: sjsp336-2024-12-01.Std
  inflating: sjsp336-2024-12-01-wbias.png
  inflating: sjsp337-2024-12-02.Bias
  inflating: sjsp337-2024-12-02.Cmn
  inflating: sjsp337-2024-12-02.Std
  inflating: sjsp337-2024-12-02-wbias.png
  inflating: sjsp338-2024-12-03.Bias
  inflating: sjsp338-2024-12-03.Cmn
  inflating: sjsp338-2024-12-03.Std
  inflating: sjsp338-2024-12-03-wbias.png
  inflating: sjsp339-2024-12-04.Bias
  inflating: sjsp339-2024-12-04.Cmn
  inflating: sjsp339-2024-12-04.Std
  inflating: sjsp339-2024-12-04-wbias.png
  inflating: sjsp340-2024-12-05.Bias
  inflating: sjsp340-2024-12-05.Cmn
  inflating: sjsp340-2024-12-05.Std
  inflating: sjsp340-2024-12-05-wbias.png
  inflating: sjsp341-2024-12-06.Bias
  inflating: sjsp341-2024-12-06.Cmn
  inflating: sjsp341-2024-12-06.Std
  inflating: sjsp341-2024-12-06-wbias.png
  inflating: sjsp342-2024-12-07.Bias
  inflating: sjsp342-2024-12-07.Cmn
  inflating: sjsp342-2024-12-07.Std
  inflating: sjsp342-2024-12-07-wbias.png
  inflating: sjsp348-2024-12-13.Bias
  inflating: sjsp348-2024-12-13.Cmn
  inflating: sjsp348-2024-12-13.Std
  inflating: sjsp348-2024-12-13-wbias.png
  inflating: sjsp349-2024-12-14.Bias
  inflating: sjsp349-2024-12-14.Cmn
  inflating: sjsp349-2024-12-14.Std
  inflating: sjsp349-2024-12-14-wbias.png
  inflating: sjsp350-2024-12-15.Bias
  inflating: sjsp350-2024-12-15.Cmn
  inflating: sjsp350-2024-12-15.Std
  inflating: sjsp350-2024-12-15-wbias.png
  inflating: sjsp351-2024-12-16.Bias
  inflating: sjsp351-2024-12-16.Cmn
  inflating: sjsp351-2024-12-16.Std
  inflating: sjsp351-2024-12-16-wbias.png
  inflating: sjsp352-2024-12-17.Bias
  inflating: sjsp352-2024-12-17.Cmn
  inflating: sjsp352-2024-12-17.Std
  inflating: sjsp352-2024-12-17-wbias.png
  inflating: sjsp353-2024-12-18.Bias
  inflating: sjsp353-2024-12-18.Cmn
  inflating: sjsp353-2024-12-18.Std
  inflating: sjsp353-2024-12-18-wbias.png
  inflating: sjsp354-2024-12-19.Bias
  inflating: sjsp354-2024-12-19.Cmn
  inflating: sjsp354-2024-12-19.Std
  inflating: sjsp354-2024-12-19-wbias.png
  inflating: sjsp355-2024-12-20.Bias
  inflating: sjsp355-2024-12-20.Cmn
  inflating: sjsp355-2024-12-20.Std
  inflating: sjsp355-2024-12-20-wbias.png
  inflating: sjsp356-2024-12-21.Bias
  inflating: sjsp356-2024-12-21.Cmn
  inflating: sjsp356-2024-12-21.Std
  inflating: sjsp356-2024-12-21-wbias.png
  inflating: sjsp357-2024-12-22.Bias
  inflating: sjsp357-2024-12-22.Cmn
  inflating: sjsp357-2024-12-22.Std
  inflating: sjsp357-2024-12-22-wbias.png
  inflating: sjsp358-2024-12-23.Bias
  inflating: sjsp358-2024-12-23.Cmn
  inflating: sjsp358-2024-12-23.Std
  inflating: sjsp358-2024-12-23-wbias.png
  inflating: sjsp359-2024-12-24.Bias
  inflating: sjsp359-2024-12-24.Cmn
  inflating: sjsp359-2024-12-24.Std
  inflating: sjsp359-2024-12-24-wbias.png
  inflating: sjsp360-2024-12-25.Bias
  inflating: sjsp360-2024-12-25.Cmn
  inflating: sjsp360-2024-12-25.Std
  inflating: sjsp360-2024-12-25-wbias.png
  inflating: sjsp361-2024-12-26.Bias
  inflating: sjsp361-2024-12-26.Cmn
  inflating: sjsp361-2024-12-26.Std
  inflating: sjsp361-2024-12-26-wbias.png
  inflating: sjsp362-2024-12-27.Bias
  inflating: sjsp362-2024-12-27.Cmn
  inflating: sjsp362-2024-12-27.Std
  inflating: sjsp362-2024-12-27-wbias.png
  inflating: sjsp363-2024-12-28.Bias
  inflating: sjsp363-2024-12-28.Cmn
  inflating: sjsp363-2024-12-28.Std
  inflating: sjsp363-2024-12-28-wbias.png
  inflating: sjsp364-2024-12-29.Bias
  inflating: sjsp364-2024-12-29.Cmn
  inflating: sjsp364-2024-12-29.Std
  inflating: sjsp364-2024-12-29-wbias.png
  inflating: sjsp365-2024-12-30.Bias
  inflating: sjsp365-2024-12-30.Cmn
  inflating: sjsp365-2024-12-30.Std
  inflating: sjsp365-2024-12-30-wbias.png
  inflating: sjsp366-2024-12-31.Bias
  inflating: sjsp366-2024-12-31.Cmn
  inflating: sjsp366-2024-12-31.Std
  inflating: sjsp366-2024-12-31-wbias.png
  inflating: TEC_dec_2024.zip

In [6]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta
import glob

data_dir = '.'

std_files = glob.glob(os.path.join(data_dir, 'sjsp3*-2024-12-*.Std'))

std_files.sort()

dfs = []

for file_path in std_files:
    try:

        filename = os.path.basename(file_path)
        print(f"Processing {filename}")

        date_parts = filename.replace('.Std', '').split('-')
        year = int(date_parts[1])
        month = int(date_parts[2])
        day = int(date_parts[3])
        base_date = datetime(year, month, day)

        df = pd.read_csv(file_path, sep='\s+', header=None)

        df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

        def decimal_to_time(decimal_hours):
            hours = int(decimal_hours)
            minutes = int((decimal_hours - hours) * 60)
            seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
            return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

        df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

        df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
        df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

        df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
        df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

        dfs.append(df)

    except Exception as e:
        print(f"Error processing file {file_path}: {e}")

if dfs:
    combined_df = pd.concat(dfs, ignore_index=True)

    combined_df = combined_df.sort_values('DATETIME')

    combined_df.to_pickle('sjsp_dec_2024_complete.pkl')

    print(f"Combined DataFrame created with {len(combined_df)} rows")
    print("First 5 lines:")
    print(combined_df.head())

    print("\nPeriod covered by data:")
    print(f"Start: {combined_df['DATETIME'].min()}")
    print(f"End: {combined_df['DATETIME'].max()}")
    print(f"Total days: {(combined_df['DATETIME'].max() - combined_df['DATETIME'].min()).days + 1}")

    present_days = combined_df['DATETIME'].dt.date.unique()
    print(f"\nTotal days with data: {len(present_days)}")
    print("Dias presentes:", sorted(present_days))
else:
    print(f"\nTotal days with data: {len(present_days)}")

<>:27: SyntaxWarning: invalid escape sequence '\s'
<>:27: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-3510872553.py:27: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(file_path, sep='\s+', header=None)

Processing sjsp336-2024-12-01.Std
Processing sjsp337-2024-12-02.Std
Processing sjsp338-2024-12-03.Std
Processing sjsp339-2024-12-04.Std
Processing sjsp340-2024-12-05.Std
Processing sjsp341-2024-12-06.Std
Processing sjsp342-2024-12-07.Std
Processing sjsp348-2024-12-13.Std
Processing sjsp349-2024-12-14.Std
Processing sjsp350-2024-12-15.Std
Processing sjsp351-2024-12-16.Std
Processing sjsp352-2024-12-17.Std
Processing sjsp353-2024-12-18.Std
Processing sjsp354-2024-12-19.Std
Processing sjsp355-2024-12-20.Std
Processing sjsp356-2024-12-21.Std
Processing sjsp357-2024-12-22.Std
Processing sjsp358-2024-12-23.Std
Processing sjsp359-2024-12-24.Std
Processing sjsp360-2024-12-25.Std
Processing sjsp361-2024-12-26.Std
Processing sjsp362-2024-12-27.Std
Processing sjsp363-2024-12-28.Std
Processing sjsp364-2024-12-29.Std
Processing sjsp365-2024-12-30.Std
Processing sjsp366-2024-12-31.Std
Combined DataFrame created with 36180 rows
First 5 lines:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-12-01 00:00:00  50.09    23.77    -23.21
1 2024-12-01 00:01:01  50.02    22.40    -23.21
2 2024-12-01 00:01:58  49.94    22.07    -23.21
3 2024-12-01 00:03:00  49.86    19.59    -23.21
4 2024-12-01 00:04:01  49.77    21.47    -23.21

Period covered by data:
Start: 2024-12-01 00:00:00
End: 2024-12-31 23:58:58
Total days: 31

Total days with data: 26
Dias presentes: [datetime.date(2024, 12, 1), datetime.date(2024, 12, 2), datetime.date(2024, 12, 3), datetime.date(2024, 12, 4), datetime.date(2024, 12, 5), datetime.date(2024, 12, 6), datetime.date(2024, 12, 7), datetime.date(2024, 12, 13), datetime.date(2024, 12, 14), datetime.date(2024, 12, 15), datetime.date(2024, 12, 16), datetime.date(2024, 12, 17), datetime.date(2024, 12, 18), datetime.date(2024, 12, 19), datetime.date(2024, 12, 20), datetime.date(2024, 12, 21), datetime.date(2024, 12, 22), datetime.date(2024, 12, 23), datetime.date(2024, 12, 24), datetime.date(2024, 12, 25), datetime.date(2024, 12, 26), datetime.date(2024, 12, 27), datetime.date(2024, 12, 28), datetime.date(2024, 12, 29), datetime.date(2024, 12, 30), datetime.date(2024, 12, 31)]

In [7]:
combined_df

                 DATETIME    TEC  TEC_STD  LATITUDE
0     2024-12-01 00:00:00  50.09    23.77    -23.21
1     2024-12-01 00:01:01  50.02    22.40    -23.21
2     2024-12-01 00:01:58  49.94    22.07    -23.21
3     2024-12-01 00:03:00  49.86    19.59    -23.21
4     2024-12-01 00:04:01  49.77    21.47    -23.21
...                   ...    ...      ...       ...
36175 2024-12-31 23:55:01  31.16     6.37    -23.21
36176 2024-12-31 23:55:58  31.14     6.43    -23.21
36177 2024-12-31 23:56:59  31.13     6.44    -23.21
36178 2024-12-31 23:58:01  31.11     6.50    -23.21
36179 2024-12-31 23:58:58  31.10     6.88    -23.21

[36180 rows x 4 columns]

## 18:00

In [8]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('sjsp_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_PEAKS_at_precise_interval(hour_start, minute_start, second_start, hour_end, minute_end, second_end):

    interval_label = f"{hour_start:02d}:{minute_start:02d}:{second_start:02d}-{hour_end:02d}:{minute_end:02d}:{second_end:02d}"

    print(f"\n{'='*80}")
    print(f"ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE {interval_label} UTC")
    print(f"{'='*80}")

    start_timestamps = []
    end_timestamps = []

    for day in df_clean['DATETIME'].dt.date.unique():
        start_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_start, minute_start, second_start))
        end_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_end, minute_end, second_end))

    df_interval = pd.DataFrame()
    for start, end in zip(start_timestamps, end_timestamps):
        day_interval = df_clean[(df_clean['DATETIME'] >= start) & (df_clean['DATETIME'] <= end)]
        df_interval = pd.concat([df_interval, day_interval])

    print(f"Filtering for times between {interval_label} UTC: {len(df_interval)} remaining points")

    if len(df_interval) == 0:
        print(f"ATTENTION: No data found in the range {interval_label} UTC!")
        return pd.DataFrame(), []

    df_interval['DATE'] = df_interval['DATETIME'].dt.date

    daily_max = df_interval.loc[df_interval.groupby('DATE')['TEC'].idxmax()]
    print(f"Unique days with data in range {interval_label}: {len(daily_max)}")

    if len(daily_max) >= 5:
        top_5_days = daily_max.nlargest(5, 'TEC').reset_index(drop=True)
    else:
        top_5_days = daily_max.sort_values('TEC', ascending=False).reset_index(drop=True)
        print(f"ATTENTION: Only {len(top_5_days)} days have data in this time range!")

    print(f"\n{len(top_5_days)} HIGHEST TEC VALUES IN THE INTERVAL {interval_label} (ONE PER DAY):")
    for idx, row in top_5_days.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_5_days.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_5_days) > 0:
        print(f"\nSUMMARY TABLE OF TEC PEAKS IN THE INTERVAL {interval_label} UTC:")
        print("-" * 100)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<12}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration'}")
        print("-" * 100)

        for idx, row in top_5_days.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M:%S'):<12}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration}")
        print("-" * 100)

    return top_5_days, sequences

def analyze_PEAKS_at_interval(hour_start, minute_start, hour_end, minute_end):

    return analyze_PEAKS_at_precise_interval(hour_start, minute_start, 0, hour_end, minute_end, 0)

print("\n\n" + "*"*40 + " ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC " + "*"*40)
top_5_exact_18h, sequences_exact_18h = analyze_PEAKS_at_precise_interval(17, 59, 55, 18, 0, 5)

print("\nAnalysis complete!")

Data loaded: 36180 records of 2024-12-01 until 2024-12-31
Analysing 36172 points after removing missing values


**************************************** ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC ****************************************

================================================================================
ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE 17:59:55-18:00:05 UTC
================================================================================
Filtering for times between 17:59:55-18:00:05 UTC: 24 remaining points
Unique days with data in range 17:59:55-18:00:05: 24

5 HIGHEST TEC VALUES IN THE INTERVAL 17:59:55-18:00:05 (ONE PER DAY):
1. TEC: 71.73 ± 5.98 TECU, Date/Time: 2024-12-18 18:00:00, Latitude: -23.21
2. TEC: 67.49 ± 4.86 TECU, Date/Time: 2024-12-22 18:00:00, Latitude: -23.21
3. TEC: 67.35 ± 2.73 TECU, Date/Time: 2024-12-19 18:00:00, Latitude: -23.21
4. TEC: 67.11 ± 2.09 TECU, Date/Time: 2024-12-01 18:00:00, Latitude: -23.21
5. TEC: 64.56 ± 2.65 TECU, Date/Time: 2024-12-20 18:00:00, Latitude: -23.21

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 71.73 ± 5.98) has a sequence of 3 high values:
  1. 2024-12-18 17:58:58: 71.55 ± 5.91 TECU (99.7% do Peak)
  2. 2024-12-18 18:00:00: 71.73 ± 5.98 TECU (100.0% do Peak)
  3. 2024-12-18 18:01:01: 71.90 ± 6.05 TECU (100.2% do Peak)

Peak #2 (TEC = 67.49 ± 4.86) has a sequence of 3 high values:
  1. 2024-12-22 17:58:58: 67.57 ± 4.85 TECU (100.1% do Peak)
  2. 2024-12-22 18:00:00: 67.49 ± 4.86 TECU (100.0% do Peak)
  3. 2024-12-22 18:01:01: 67.39 ± 5.86 TECU (99.9% do Peak)

Peak #3 (TEC = 67.35 ± 2.73) has a sequence of 3 high values:
  1. 2024-12-19 17:58:58: 67.36 ± 2.66 TECU (100.0% do Peak)
  2. 2024-12-19 18:00:00: 67.35 ± 2.73 TECU (100.0% do Peak)
  3. 2024-12-19 18:01:01: 67.35 ± 2.72 TECU (100.0% do Peak)

Peak #4 (TEC = 67.11 ± 2.09) has a sequence of 3 high values:
  1. 2024-12-01 17:58:58: 67.18 ± 2.06 TECU (100.1% do Peak)
  2. 2024-12-01 18:00:00: 67.11 ± 2.09 TECU (100.0% do Peak)
  3. 2024-12-01 18:01:01: 67.04 ± 2.11 TECU (99.9% do Peak)

Peak #5 (TEC = 64.56 ± 2.65) has a sequence of 3 high values:
  1. 2024-12-20 17:58:58: 64.58 ± 2.62 TECU (100.0% do Peak)
  2. 2024-12-20 18:00:00: 64.56 ± 2.65 TECU (100.0% do Peak)
  3. 2024-12-20 18:01:01: 64.54 ± 2.67 TECU (100.0% do Peak)

SUMMARY TABLE OF TEC PEAKS IN THE INTERVAL 17:59:55-18:00:05 UTC:
----------------------------------------------------------------------------------------------------
Rank Data        UTC time    TEC       TEC_STD   Sequence       Sequence Duration
----------------------------------------------------------------------------------------------------
1    18/12/2024  18:00:00    71.73    5.98    Sim            2.0 min
2    22/12/2024  18:00:00    67.49    4.86    Sim            2.0 min
3    19/12/2024  18:00:00    67.35    2.73    Sim            2.0 min
4    01/12/2024  18:00:00    67.11    2.09    Sim            2.0 min
5    20/12/2024  18:00:00    64.56    2.65    Sim            2.0 min
----------------------------------------------------------------------------------------------------

Analysis complete!

## DECEMBER

In [9]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('sjsp_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_top_PEAKS(top_n=200):

    print(f"\n{'='*80}")
    print(f"TOP {top_n} PEAK ANALYSIS OF TEC (ALL TIMES)")
    print(f"{'='*80}")

    df_clean['DATE'] = df_clean['DATETIME'].dt.date

    top_n_PEAKS = df_clean.nlargest(top_n, 'TEC').reset_index(drop=True)

    print(f"\nTOP {top_n} HIGHEST VALUES OF TEC (ALL TIMES):")
    for idx, row in top_n_PEAKS.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_n_PEAKS.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_n_PEAKS) > 0:
        print(f"\nSUMMARY TABLE OF TOP {top_n} TEC PEAKS:")
        print("-" * 110)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration':<20}{'Horário do dia'}")
        print("-" * 110)

        for idx, row in top_n_PEAKS.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            hour = row['DATETIME'].hour
            minute = row['DATETIME'].minute
            time_category = f"{hour:02d}:{minute:02d} UTC"

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M'):<10}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration:<20}{time_category}")
        print("-" * 110)

    return top_n_PEAKS, sequences

print("\n\n" + "*"*40 + "TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) " + "*"*40)
top_n_PEAKS, sequences = analyze_top_PEAKS(top_n=200)

print("\nAnalysis complete!")

Data loaded: 36180 records of 2024-12-01 until 2024-12-31
Analysing 36172 points after removing missing values


****************************************TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) ****************************************

================================================================================
TOP 200 PEAK ANALYSIS OF TEC (ALL TIMES)
================================================================================

TOP 200 HIGHEST VALUES OF TEC (ALL TIMES):
1. TEC: 73.56 ± 8.07 TECU, Date/Time: 2024-12-18 18:16:58, Latitude: -23.21
2. TEC: 73.55 ± 7.94 TECU, Date/Time: 2024-12-18 18:16:01, Latitude: -23.21
3. TEC: 73.55 ± 8.22 TECU, Date/Time: 2024-12-18 18:18:00, Latitude: -23.21
4. TEC: 73.53 ± 7.79 TECU, Date/Time: 2024-12-18 18:15:00, Latitude: -23.21
5. TEC: 73.53 ± 8.35 TECU, Date/Time: 2024-12-18 18:19:01, Latitude: -23.21
6. TEC: 73.49 ± 7.65 TECU, Date/Time: 2024-12-18 18:13:58, Latitude: -23.21
7. TEC: 73.49 ± 8.34 TECU, Date/Time: 2024-12-18 18:19:58, Latitude: -23.21
8. TEC: 73.44 ± 8.71 TECU, Date/Time: 2024-12-18 18:21:00, Latitude: -23.21
9. TEC: 73.43 ± 7.51 TECU, Date/Time: 2024-12-18 18:13:01, Latitude: -23.21
10. TEC: 73.37 ± 7.37 TECU, Date/Time: 2024-12-18 18:11:59, Latitude: -23.21
11. TEC: 73.37 ± 8.71 TECU, Date/Time: 2024-12-18 18:22:01, Latitude: -23.21
12. TEC: 73.29 ± 8.82 TECU, Date/Time: 2024-12-18 18:22:58, Latitude: -23.21
13. TEC: 73.28 ± 7.21 TECU, Date/Time: 2024-12-18 18:10:58, Latitude: -23.21
14. TEC: 73.19 ± 7.07 TECU, Date/Time: 2024-12-18 18:10:01, Latitude: -23.21
15. TEC: 73.19 ± 8.94 TECU, Date/Time: 2024-12-18 18:23:59, Latitude: -23.21
16. TEC: 73.09 ± 6.94 TECU, Date/Time: 2024-12-18 18:08:59, Latitude: -23.21
17. TEC: 73.07 ± 9.43 TECU, Date/Time: 2024-12-18 18:25:01, Latitude: -23.21
18. TEC: 72.97 ± 6.80 TECU, Date/Time: 2024-12-18 18:07:58, Latitude: -23.21
19. TEC: 72.94 ± 9.84 TECU, Date/Time: 2024-12-18 18:25:58, Latitude: -23.21
20. TEC: 72.84 ± 6.69 TECU, Date/Time: 2024-12-18 18:07:01, Latitude: -23.21
21. TEC: 72.80 ± 9.76 TECU, Date/Time: 2024-12-18 18:26:59, Latitude: -23.21
22. TEC: 72.71 ± 6.58 TECU, Date/Time: 2024-12-18 18:06:00, Latitude: -23.21
23. TEC: 72.64 ± 10.00 TECU, Date/Time: 2024-12-18 18:28:01, Latitude: -23.21
24. TEC: 72.56 ± 6.46 TECU, Date/Time: 2024-12-18 18:04:58, Latitude: -23.21
25. TEC: 72.48 ± 9.99 TECU, Date/Time: 2024-12-18 18:28:58, Latitude: -23.21
26. TEC: 72.41 ± 6.34 TECU, Date/Time: 2024-12-18 18:04:01, Latitude: -23.21
27. TEC: 72.30 ± 10.16 TECU, Date/Time: 2024-12-18 18:30:00, Latitude: -23.21
28. TEC: 72.24 ± 6.23 TECU, Date/Time: 2024-12-18 18:03:00, Latitude: -23.21
29. TEC: 72.10 ± 10.28 TECU, Date/Time: 2024-12-18 18:31:01, Latitude: -23.21
30. TEC: 72.08 ± 6.14 TECU, Date/Time: 2024-12-18 18:01:58, Latitude: -23.21
31. TEC: 71.90 ± 6.05 TECU, Date/Time: 2024-12-18 18:01:01, Latitude: -23.21
32. TEC: 71.90 ± 10.40 TECU, Date/Time: 2024-12-18 18:31:58, Latitude: -23.21
33. TEC: 71.73 ± 5.98 TECU, Date/Time: 2024-12-18 18:00:00, Latitude: -23.21
34. TEC: 71.69 ± 10.48 TECU, Date/Time: 2024-12-18 18:33:00, Latitude: -23.21
35. TEC: 71.55 ± 5.91 TECU, Date/Time: 2024-12-18 17:58:58, Latitude: -23.21
36. TEC: 71.47 ± 10.59 TECU, Date/Time: 2024-12-18 18:34:01, Latitude: -23.21
37. TEC: 71.36 ± 5.83 TECU, Date/Time: 2024-12-18 17:58:01, Latitude: -23.21
38. TEC: 71.25 ± 10.69 TECU, Date/Time: 2024-12-18 18:34:58, Latitude: -23.21
39. TEC: 71.17 ± 5.76 TECU, Date/Time: 2024-12-18 17:56:59, Latitude: -23.21
40. TEC: 71.02 ± 10.80 TECU, Date/Time: 2024-12-18 18:36:00, Latitude: -23.21
41. TEC: 70.99 ± 5.69 TECU, Date/Time: 2024-12-18 17:55:58, Latitude: -23.21
42. TEC: 70.80 ± 5.63 TECU, Date/Time: 2024-12-18 17:55:01, Latitude: -23.21
43. TEC: 70.78 ± 10.43 TECU, Date/Time: 2024-12-18 18:37:01, Latitude: -23.21
44. TEC: 70.61 ± 5.59 TECU, Date/Time: 2024-12-18 17:53:59, Latitude: -23.21
45. TEC: 70.54 ± 8.22 TECU, Date/Time: 2024-12-18 18:37:58, Latitude: -23.21
46. TEC: 70.42 ± 5.53 TECU, Date/Time: 2024-12-18 17:52:58, Latitude: -23.21
47. TEC: 70.33 ± 2.02 TECU, Date/Time: 2024-12-02 15:35:59, Latitude: -23.21
48. TEC: 70.33 ± 2.01 TECU, Date/Time: 2024-12-02 15:37:01, Latitude: -23.21
49. TEC: 70.33 ± 2.00 TECU, Date/Time: 2024-12-02 15:37:58, Latitude: -23.21
50. TEC: 70.32 ± 2.02 TECU, Date/Time: 2024-12-02 15:34:01, Latitude: -23.21
51. TEC: 70.32 ± 2.03 TECU, Date/Time: 2024-12-02 15:34:58, Latitude: -23.21
52. TEC: 70.32 ± 1.98 TECU, Date/Time: 2024-12-02 15:39:00, Latitude: -23.21
53. TEC: 70.32 ± 1.97 TECU, Date/Time: 2024-12-02 15:40:01, Latitude: -23.21
54. TEC: 70.31 ± 2.01 TECU, Date/Time: 2024-12-02 15:33:00, Latitude: -23.21
55. TEC: 70.31 ± 1.95 TECU, Date/Time: 2024-12-02 15:40:58, Latitude: -23.21
56. TEC: 70.30 ± 2.00 TECU, Date/Time: 2024-12-02 15:31:58, Latitude: -23.21
57. TEC: 70.30 ± 1.93 TECU, Date/Time: 2024-12-02 15:41:59, Latitude: -23.21
58. TEC: 70.30 ± 8.23 TECU, Date/Time: 2024-12-18 18:38:59, Latitude: -23.21
59. TEC: 70.29 ± 1.99 TECU, Date/Time: 2024-12-02 15:31:01, Latitude: -23.21
60. TEC: 70.29 ± 1.91 TECU, Date/Time: 2024-12-02 15:43:01, Latitude: -23.21
61. TEC: 70.27 ± 2.02 TECU, Date/Time: 2024-12-02 15:30:00, Latitude: -23.21
62. TEC: 70.27 ± 1.91 TECU, Date/Time: 2024-12-02 15:43:58, Latitude: -23.21
63. TEC: 70.25 ± 2.03 TECU, Date/Time: 2024-12-02 15:28:58, Latitude: -23.21
64. TEC: 70.25 ± 1.89 TECU, Date/Time: 2024-12-02 15:45:00, Latitude: -23.21
65. TEC: 70.23 ± 2.04 TECU, Date/Time: 2024-12-02 15:28:01, Latitude: -23.21
66. TEC: 70.23 ± 1.87 TECU, Date/Time: 2024-12-02 15:46:01, Latitude: -23.21
67. TEC: 70.23 ± 5.81 TECU, Date/Time: 2024-12-18 17:52:01, Latitude: -23.21
68. TEC: 70.21 ± 2.07 TECU, Date/Time: 2024-12-02 15:26:59, Latitude: -23.21
69. TEC: 70.21 ± 1.87 TECU, Date/Time: 2024-12-02 15:46:58, Latitude: -23.21
70. TEC: 70.19 ± 2.07 TECU, Date/Time: 2024-12-02 15:25:58, Latitude: -23.21
71. TEC: 70.19 ± 2.03 TECU, Date/Time: 2024-12-02 15:48:00, Latitude: -23.21
72. TEC: 70.16 ± 2.08 TECU, Date/Time: 2024-12-02 15:25:01, Latitude: -23.21
73. TEC: 70.16 ± 2.02 TECU, Date/Time: 2024-12-02 15:49:01, Latitude: -23.21
74. TEC: 70.13 ± 2.08 TECU, Date/Time: 2024-12-02 15:24:00, Latitude: -23.21
75. TEC: 70.13 ± 2.01 TECU, Date/Time: 2024-12-02 15:49:58, Latitude: -23.21
76. TEC: 70.10 ± 2.08 TECU, Date/Time: 2024-12-02 15:22:58, Latitude: -23.21
77. TEC: 70.10 ± 2.00 TECU, Date/Time: 2024-12-02 15:50:59, Latitude: -23.21
78. TEC: 70.07 ± 2.07 TECU, Date/Time: 2024-12-02 15:22:01, Latitude: -23.21
79. TEC: 70.06 ± 2.00 TECU, Date/Time: 2024-12-02 15:52:01, Latitude: -23.21
80. TEC: 70.05 ± 8.33 TECU, Date/Time: 2024-12-18 18:40:01, Latitude: -23.21
81. TEC: 70.04 ± 2.07 TECU, Date/Time: 2024-12-02 15:20:59, Latitude: -23.21
82. TEC: 70.04 ± 5.93 TECU, Date/Time: 2024-12-18 17:51:00, Latitude: -23.21
83. TEC: 70.03 ± 1.99 TECU, Date/Time: 2024-12-02 15:52:58, Latitude: -23.21
84. TEC: 70.00 ± 2.06 TECU, Date/Time: 2024-12-02 15:19:58, Latitude: -23.21
85. TEC: 69.99 ± 1.99 TECU, Date/Time: 2024-12-02 15:54:00, Latitude: -23.21
86. TEC: 69.96 ± 2.06 TECU, Date/Time: 2024-12-02 15:19:01, Latitude: -23.21
87. TEC: 69.95 ± 1.99 TECU, Date/Time: 2024-12-02 15:55:01, Latitude: -23.21
88. TEC: 69.92 ± 2.05 TECU, Date/Time: 2024-12-02 15:18:00, Latitude: -23.21
89. TEC: 69.90 ± 1.99 TECU, Date/Time: 2024-12-02 15:55:58, Latitude: -23.21
90. TEC: 69.89 ± 1.58 TECU, Date/Time: 2024-12-04 15:33:00, Latitude: -23.21
91. TEC: 69.89 ± 1.57 TECU, Date/Time: 2024-12-04 15:34:01, Latitude: -23.21
92. TEC: 69.89 ± 1.57 TECU, Date/Time: 2024-12-04 15:34:58, Latitude: -23.21
93. TEC: 69.89 ± 1.58 TECU, Date/Time: 2024-12-04 15:35:59, Latitude: -23.21
94. TEC: 69.89 ± 1.59 TECU, Date/Time: 2024-12-04 15:37:01, Latitude: -23.21
95. TEC: 69.89 ± 1.60 TECU, Date/Time: 2024-12-04 15:37:58, Latitude: -23.21
96. TEC: 69.89 ± 1.62 TECU, Date/Time: 2024-12-04 15:39:00, Latitude: -23.21
97. TEC: 69.88 ± 1.60 TECU, Date/Time: 2024-12-04 15:31:58, Latitude: -23.21
98. TEC: 69.88 ± 1.79 TECU, Date/Time: 2024-12-04 15:40:01, Latitude: -23.21
99. TEC: 69.87 ± 2.05 TECU, Date/Time: 2024-12-02 15:16:58, Latitude: -23.21
100. TEC: 69.87 ± 1.60 TECU, Date/Time: 2024-12-04 15:30:00, Latitude: -23.21
101. TEC: 69.87 ± 1.60 TECU, Date/Time: 2024-12-04 15:31:01, Latitude: -23.21
102. TEC: 69.87 ± 1.81 TECU, Date/Time: 2024-12-04 15:40:58, Latitude: -23.21
103. TEC: 69.87 ± 1.83 TECU, Date/Time: 2024-12-04 15:41:59, Latitude: -23.21
104. TEC: 69.86 ± 1.99 TECU, Date/Time: 2024-12-02 15:56:59, Latitude: -23.21
105. TEC: 69.86 ± 1.60 TECU, Date/Time: 2024-12-04 15:28:58, Latitude: -23.21
106. TEC: 69.86 ± 1.85 TECU, Date/Time: 2024-12-04 15:43:01, Latitude: -23.21
107. TEC: 69.86 ± 5.89 TECU, Date/Time: 2024-12-18 17:49:58, Latitude: -23.21
108. TEC: 69.85 ± 1.61 TECU, Date/Time: 2024-12-04 15:28:01, Latitude: -23.21
109. TEC: 69.85 ± 1.85 TECU, Date/Time: 2024-12-04 15:43:58, Latitude: -23.21
110. TEC: 69.84 ± 1.60 TECU, Date/Time: 2024-12-04 15:26:59, Latitude: -23.21
111. TEC: 69.83 ± 2.05 TECU, Date/Time: 2024-12-02 15:16:01, Latitude: -23.21
112. TEC: 69.83 ± 1.86 TECU, Date/Time: 2024-12-04 15:45:00, Latitude: -23.21
113. TEC: 69.82 ± 1.60 TECU, Date/Time: 2024-12-04 15:25:58, Latitude: -23.21
114. TEC: 69.82 ± 1.88 TECU, Date/Time: 2024-12-04 15:46:01, Latitude: -23.21
115. TEC: 69.81 ± 1.99 TECU, Date/Time: 2024-12-02 15:58:01, Latitude: -23.21
116. TEC: 69.81 ± 1.59 TECU, Date/Time: 2024-12-04 15:25:01, Latitude: -23.21
117. TEC: 69.80 ± 1.61 TECU, Date/Time: 2024-12-04 15:24:00, Latitude: -23.21
118. TEC: 69.80 ± 1.89 TECU, Date/Time: 2024-12-04 15:46:58, Latitude: -23.21
119. TEC: 69.80 ± 8.44 TECU, Date/Time: 2024-12-18 18:40:58, Latitude: -23.21
120. TEC: 69.78 ± 2.07 TECU, Date/Time: 2024-12-02 15:15:00, Latitude: -23.21
121. TEC: 69.78 ± 1.61 TECU, Date/Time: 2024-12-04 15:22:58, Latitude: -23.21
122. TEC: 69.78 ± 1.92 TECU, Date/Time: 2024-12-04 15:48:00, Latitude: -23.21
123. TEC: 69.77 ± 2.00 TECU, Date/Time: 2024-12-02 15:58:58, Latitude: -23.21
124. TEC: 69.77 ± 1.62 TECU, Date/Time: 2024-12-04 15:22:01, Latitude: -23.21
125. TEC: 69.76 ± 1.94 TECU, Date/Time: 2024-12-04 15:49:01, Latitude: -23.21
126. TEC: 69.75 ± 1.64 TECU, Date/Time: 2024-12-04 15:20:59, Latitude: -23.21
127. TEC: 69.74 ± 1.93 TECU, Date/Time: 2024-12-04 15:49:58, Latitude: -23.21
128. TEC: 69.73 ± 2.09 TECU, Date/Time: 2024-12-02 15:13:58, Latitude: -23.21
129. TEC: 69.73 ± 1.67 TECU, Date/Time: 2024-12-04 15:19:58, Latitude: -23.21
130. TEC: 69.72 ± 2.00 TECU, Date/Time: 2024-12-02 16:00:00, Latitude: -23.21
131. TEC: 69.72 ± 1.70 TECU, Date/Time: 2024-12-04 15:19:01, Latitude: -23.21
132. TEC: 69.72 ± 1.95 TECU, Date/Time: 2024-12-04 15:50:59, Latitude: -23.21
133. TEC: 69.70 ± 1.72 TECU, Date/Time: 2024-12-04 15:18:00, Latitude: -23.21
134. TEC: 69.70 ± 1.99 TECU, Date/Time: 2024-12-04 15:52:01, Latitude: -23.21
135. TEC: 69.68 ± 2.10 TECU, Date/Time: 2024-12-02 15:13:01, Latitude: -23.21
136. TEC: 69.68 ± 1.76 TECU, Date/Time: 2024-12-04 15:16:58, Latitude: -23.21
137. TEC: 69.68 ± 5.80 TECU, Date/Time: 2024-12-18 17:49:01, Latitude: -23.21
138. TEC: 69.67 ± 2.01 TECU, Date/Time: 2024-12-02 16:01:01, Latitude: -23.21
139. TEC: 69.67 ± 2.00 TECU, Date/Time: 2024-12-04 15:52:58, Latitude: -23.21
140. TEC: 69.66 ± 1.78 TECU, Date/Time: 2024-12-04 15:16:01, Latitude: -23.21
141. TEC: 69.65 ± 1.78 TECU, Date/Time: 2024-12-04 15:15:00, Latitude: -23.21
142. TEC: 69.65 ± 2.00 TECU, Date/Time: 2024-12-04 15:54:00, Latitude: -23.21
143. TEC: 69.63 ± 2.10 TECU, Date/Time: 2024-12-02 15:11:59, Latitude: -23.21
144. TEC: 69.63 ± 1.79 TECU, Date/Time: 2024-12-04 15:13:58, Latitude: -23.21
145. TEC: 69.62 ± 2.03 TECU, Date/Time: 2024-12-04 15:55:01, Latitude: -23.21
146. TEC: 69.61 ± 2.05 TECU, Date/Time: 2024-12-02 16:01:58, Latitude: -23.21
147. TEC: 69.61 ± 1.80 TECU, Date/Time: 2024-12-04 15:13:01, Latitude: -23.21
148. TEC: 69.59 ± 1.80 TECU, Date/Time: 2024-12-04 15:11:59, Latitude: -23.21
149. TEC: 69.59 ± 2.06 TECU, Date/Time: 2024-12-04 15:55:58, Latitude: -23.21
150. TEC: 69.57 ± 2.11 TECU, Date/Time: 2024-12-02 15:10:58, Latitude: -23.21
151. TEC: 69.57 ± 1.81 TECU, Date/Time: 2024-12-04 15:10:58, Latitude: -23.21
152. TEC: 69.56 ± 2.09 TECU, Date/Time: 2024-12-02 16:03:00, Latitude: -23.21
153. TEC: 69.56 ± 2.11 TECU, Date/Time: 2024-12-04 15:56:59, Latitude: -23.21
154. TEC: 69.56 ± 8.42 TECU, Date/Time: 2024-12-18 18:41:59, Latitude: -23.21
155. TEC: 69.55 ± 1.81 TECU, Date/Time: 2024-12-04 15:10:01, Latitude: -23.21
156. TEC: 69.53 ± 1.81 TECU, Date/Time: 2024-12-04 15:09:00, Latitude: -23.21
157. TEC: 69.52 ± 1.70 TECU, Date/Time: 2024-12-02 15:10:01, Latitude: -23.21
158. TEC: 69.52 ± 2.14 TECU, Date/Time: 2024-12-04 15:58:01, Latitude: -23.21
159. TEC: 69.51 ± 2.11 TECU, Date/Time: 2024-12-02 16:04:01, Latitude: -23.21
160. TEC: 69.51 ± 1.81 TECU, Date/Time: 2024-12-04 15:07:58, Latitude: -23.21
161. TEC: 69.50 ± 5.74 TECU, Date/Time: 2024-12-18 17:48:00, Latitude: -23.21
162. TEC: 69.49 ± 1.78 TECU, Date/Time: 2024-12-04 15:07:01, Latitude: -23.21
163. TEC: 69.49 ± 2.00 TECU, Date/Time: 2024-12-04 15:58:58, Latitude: -23.21
164. TEC: 69.47 ± 1.78 TECU, Date/Time: 2024-12-04 15:05:59, Latitude: -23.21
165. TEC: 69.46 ± 1.48 TECU, Date/Time: 2024-12-02 15:09:00, Latitude: -23.21
166. TEC: 69.46 ± 2.06 TECU, Date/Time: 2024-12-02 16:04:58, Latitude: -23.21
167. TEC: 69.46 ± 1.78 TECU, Date/Time: 2024-12-04 15:04:58, Latitude: -23.21
168. TEC: 69.45 ± 2.02 TECU, Date/Time: 2024-12-04 16:00:00, Latitude: -23.21
169. TEC: 69.44 ± 1.76 TECU, Date/Time: 2024-12-04 15:04:01, Latitude: -23.21
170. TEC: 69.42 ± 1.76 TECU, Date/Time: 2024-12-04 15:03:00, Latitude: -23.21
171. TEC: 69.42 ± 2.03 TECU, Date/Time: 2024-12-04 16:01:01, Latitude: -23.21
172. TEC: 69.40 ± 1.50 TECU, Date/Time: 2024-12-02 15:07:58, Latitude: -23.21
173. TEC: 69.40 ± 2.17 TECU, Date/Time: 2024-12-02 16:06:00, Latitude: -23.21
174. TEC: 69.40 ± 1.70 TECU, Date/Time: 2024-12-04 15:01:58, Latitude: -23.21
175. TEC: 69.38 ± 1.67 TECU, Date/Time: 2024-12-04 15:01:01, Latitude: -23.21
176. TEC: 69.38 ± 2.04 TECU, Date/Time: 2024-12-04 16:01:58, Latitude: -23.21
177. TEC: 69.36 ± 1.70 TECU, Date/Time: 2024-12-04 15:00:00, Latitude: -23.21
178. TEC: 69.35 ± 2.14 TECU, Date/Time: 2024-12-02 16:07:01, Latitude: -23.21
179. TEC: 69.34 ± 1.73 TECU, Date/Time: 2024-12-04 14:58:58, Latitude: -23.21
180. TEC: 69.34 ± 2.06 TECU, Date/Time: 2024-12-04 16:03:00, Latitude: -23.21
181. TEC: 69.33 ± 1.51 TECU, Date/Time: 2024-12-02 15:07:01, Latitude: -23.21
182. TEC: 69.32 ± 5.69 TECU, Date/Time: 2024-12-18 17:46:58, Latitude: -23.21
183. TEC: 69.31 ± 1.78 TECU, Date/Time: 2024-12-04 14:58:01, Latitude: -23.21
184. TEC: 69.31 ± 8.46 TECU, Date/Time: 2024-12-18 18:43:01, Latitude: -23.21
185. TEC: 69.30 ± 2.15 TECU, Date/Time: 2024-12-02 16:07:58, Latitude: -23.21
186. TEC: 69.30 ± 2.04 TECU, Date/Time: 2024-12-04 16:04:01, Latitude: -23.21
187. TEC: 69.29 ± 1.81 TECU, Date/Time: 2024-12-04 14:56:59, Latitude: -23.21
188. TEC: 69.27 ± 1.54 TECU, Date/Time: 2024-12-02 15:05:59, Latitude: -23.21
189. TEC: 69.27 ± 1.85 TECU, Date/Time: 2024-12-04 14:55:58, Latitude: -23.21
190. TEC: 69.26 ± 2.02 TECU, Date/Time: 2024-12-04 16:04:58, Latitude: -23.21
191. TEC: 69.25 ± 1.88 TECU, Date/Time: 2024-12-04 14:55:01, Latitude: -23.21
192. TEC: 69.24 ± 2.18 TECU, Date/Time: 2024-12-02 16:08:59, Latitude: -23.21
193. TEC: 69.22 ± 1.92 TECU, Date/Time: 2024-12-04 14:54:00, Latitude: -23.21
194. TEC: 69.22 ± 2.01 TECU, Date/Time: 2024-12-04 16:06:00, Latitude: -23.21
195. TEC: 69.20 ± 1.56 TECU, Date/Time: 2024-12-02 15:04:58, Latitude: -23.21
196. TEC: 69.20 ± 1.96 TECU, Date/Time: 2024-12-04 14:52:58, Latitude: -23.21
197. TEC: 69.19 ± 2.21 TECU, Date/Time: 2024-12-02 16:10:01, Latitude: -23.21
198. TEC: 69.17 ± 1.99 TECU, Date/Time: 2024-12-04 14:52:01, Latitude: -23.21
199. TEC: 69.17 ± 1.92 TECU, Date/Time: 2024-12-04 16:07:01, Latitude: -23.21
200. TEC: 69.15 ± 5.61 TECU, Date/Time: 2024-12-18 17:46:01, Latitude: -23.21

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 73.56 ± 8.07) has a sequence of 3 high values:
  1. 2024-12-18 18:16:01: 73.55 ± 7.94 TECU (100.0% do Peak)
  2. 2024-12-18 18:16:58: 73.56 ± 8.07 TECU (100.0% do Peak)
  3. 2024-12-18 18:18:00: 73.55 ± 8.22 TECU (100.0% do Peak)

Peak #2 (TEC = 73.55 ± 7.94) has a sequence of 3 high values:
  1. 2024-12-18 18:15:00: 73.53 ± 7.79 TECU (100.0% do Peak)
  2. 2024-12-18 18:16:01: 73.55 ± 7.94 TECU (100.0% do Peak)
  3. 2024-12-18 18:16:58: 73.56 ± 8.07 TECU (100.0% do Peak)

Peak #3 (TEC = 73.55 ± 8.22) has a sequence of 3 high values:
  1. 2024-12-18 18:16:58: 73.56 ± 8.07 TECU (100.0% do Peak)
  2. 2024-12-18 18:18:00: 73.55 ± 8.22 TECU (100.0% do Peak)
  3. 2024-12-18 18:19:01: 73.53 ± 8.35 TECU (100.0% do Peak)

Peak #4 (TEC = 73.53 ± 7.79) has a sequence of 3 high values:
  1. 2024-12-18 18:13:58: 73.49 ± 7.65 TECU (99.9% do Peak)
  2. 2024-12-18 18:15:00: 73.53 ± 7.79 TECU (100.0% do Peak)
  3. 2024-12-18 18:16:01: 73.55 ± 7.94 TECU (100.0% do Peak)

Peak #5 (TEC = 73.53 ± 8.35) has a sequence of 3 high values:
  1. 2024-12-18 18:18:00: 73.55 ± 8.22 TECU (100.0% do Peak)
  2. 2024-12-18 18:19:01: 73.53 ± 8.35 TECU (100.0% do Peak)
  3. 2024-12-18 18:19:58: 73.49 ± 8.34 TECU (99.9% do Peak)

Peak #6 (TEC = 73.49 ± 7.65) has a sequence of 3 high values:
  1. 2024-12-18 18:13:01: 73.43 ± 7.51 TECU (99.9% do Peak)
  2. 2024-12-18 18:13:58: 73.49 ± 7.65 TECU (100.0% do Peak)
  3. 2024-12-18 18:15:00: 73.53 ± 7.79 TECU (100.1% do Peak)

Peak #7 (TEC = 73.49 ± 8.34) has a sequence of 3 high values:
  1. 2024-12-18 18:19:01: 73.53 ± 8.35 TECU (100.1% do Peak)
  2. 2024-12-18 18:19:58: 73.49 ± 8.34 TECU (100.0% do Peak)
  3. 2024-12-18 18:21:00: 73.44 ± 8.71 TECU (99.9% do Peak)

Peak #8 (TEC = 73.44 ± 8.71) has a sequence of 3 high values:
  1. 2024-12-18 18:19:58: 73.49 ± 8.34 TECU (100.1% do Peak)
  2. 2024-12-18 18:21:00: 73.44 ± 8.71 TECU (100.0% do Peak)
  3. 2024-12-18 18:22:01: 73.37 ± 8.71 TECU (99.9% do Peak)

Peak #9 (TEC = 73.43 ± 7.51) has a sequence of 3 high values:
  1. 2024-12-18 18:11:59: 73.37 ± 7.37 TECU (99.9% do Peak)
  2. 2024-12-18 18:13:01: 73.43 ± 7.51 TECU (100.0% do Peak)
  3. 2024-12-18 18:13:58: 73.49 ± 7.65 TECU (100.1% do Peak)

Peak #10 (TEC = 73.37 ± 7.37) has a sequence of 3 high values:
  1. 2024-12-18 18:10:58: 73.28 ± 7.21 TECU (99.9% do Peak)
  2. 2024-12-18 18:11:59: 73.37 ± 7.37 TECU (100.0% do Peak)
  3. 2024-12-18 18:13:01: 73.43 ± 7.51 TECU (100.1% do Peak)

Peak #11 (TEC = 73.37 ± 8.71) has a sequence of 3 high values:
  1. 2024-12-18 18:21:00: 73.44 ± 8.71 TECU (100.1% do Peak)
  2. 2024-12-18 18:22:01: 73.37 ± 8.71 TECU (100.0% do Peak)
  3. 2024-12-18 18:22:58: 73.29 ± 8.82 TECU (99.9% do Peak)

Peak #12 (TEC = 73.29 ± 8.82) has a sequence of 3 high values:
  1. 2024-12-18 18:22:01: 73.37 ± 8.71 TECU (100.1% do Peak)
  2. 2024-12-18 18:22:58: 73.29 ± 8.82 TECU (100.0% do Peak)
  3. 2024-12-18 18:23:59: 73.19 ± 8.94 TECU (99.9% do Peak)

Peak #13 (TEC = 73.28 ± 7.21) has a sequence of 3 high values:
  1. 2024-12-18 18:10:01: 73.19 ± 7.07 TECU (99.9% do Peak)
  2. 2024-12-18 18:10:58: 73.28 ± 7.21 TECU (100.0% do Peak)
  3. 2024-12-18 18:11:59: 73.37 ± 7.37 TECU (100.1% do Peak)

Peak #14 (TEC = 73.19 ± 7.07) has a sequence of 3 high values:
  1. 2024-12-18 18:08:59: 73.09 ± 6.94 TECU (99.9% do Peak)
  2. 2024-12-18 18:10:01: 73.19 ± 7.07 TECU (100.0% do Peak)
  3. 2024-12-18 18:10:58: 73.28 ± 7.21 TECU (100.1% do Peak)

Peak #15 (TEC = 73.19 ± 8.94) has a sequence of 3 high values:
  1. 2024-12-18 18:22:58: 73.29 ± 8.82 TECU (100.1% do Peak)
  2. 2024-12-18 18:23:59: 73.19 ± 8.94 TECU (100.0% do Peak)
  3. 2024-12-18 18:25:01: 73.07 ± 9.43 TECU (99.8% do Peak)

Peak #16 (TEC = 73.09 ± 6.94) has a sequence of 3 high values:
  1. 2024-12-18 18:07:58: 72.97 ± 6.80 TECU (99.8% do Peak)
  2. 2024-12-18 18:08:59: 73.09 ± 6.94 TECU (100.0% do Peak)
  3. 2024-12-18 18:10:01: 73.19 ± 7.07 TECU (100.1% do Peak)


## SPECIFIC TIMES FOR 12/18

In [10]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('sjsp_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

print(f"Available columns in the DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):

    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):

    location_info = {}

    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):

    print(f"\n{'='*100}")
    print(f"ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES")
    print(f"(Maximum allowed difference: {max_minutes_diff} minutes)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"LOOKING FOR VALUES NEAR: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f" VALUE FOUND:")
            print(f" Actual Date/Time: {closest_row['DATETIME']}")
            print(f" Target Date/Time: {target_dt}")
            print(f" Difference: {time_diff:.2f} minutes")
            print(f" TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  HAS a sequence of 3 high values ​​(≥90% of the peak):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f" {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% of value)")
            else:
                print(f"  does NOT have a sequence of 3 consecutive high values")

            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f" NO VALUE FOUND within {max_minutes_diff} minutes of target time")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    print(f"\n{'='*120}")
    print(f"RESULTS SUMMARY TABLE")
    print(f"{'='*120}")

    header = f"{'#':<3}{'Target Time':<20}{'Found Time':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<12}"

    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

target_datetimes = [
    "2024-12-18 18:20:00",
    "2024-12-18 18:10:00",
    "2024-12-18 18:30:00",
    "2024-12-18 18:00:00"
]

print("\n\n" + "*"*50 + " ANALYSIS OF SPECIFIC TIMES " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnalysis complete!")

found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"STATISTICS OF THE RESULTS FOUND")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"TEC values ​​found:")
    print(f" Minimum: {min(tec_values):.2f} TECU")
    print(f" Maximum: {max(tec_values):.2f} TECU")
    print(f" Mean: {np.mean(tec_values):.2f} TECU")
    print(f" Standard deviation: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nHigh value sequences found: {sequences_found} out of {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 36180 records of 2024-12-01 until 2024-12-31
Available columns in the DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 36172 points after removing missing values


************************************************** ANALYSIS OF SPECIFIC TIMES **************************************************

====================================================================================================
ANALYSIS OF TEC VALUES CLOSE TO SPECIFIC TIMES
(Maximum allowed difference: 2 minutes)
====================================================================================================

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:20:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:19:58
 Target Date/Time: 2024-12-18 18:20:00
 Difference: 0.03 minutes
 TEC: 73.49 ± 8.34 TECU
  LATITUDE: -23.21
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 18:19:01: 73.53 ± 8.35 TECU (100.1% of value)
 2. 2024-12-18 18:19:58: 73.49 ± 8.34 TECU (100.0% of value)
 3. 2024-12-18 18:21:00: 73.44 ± 8.71 TECU (99.9% of value)

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:10:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:10:01
 Target Date/Time: 2024-12-18 18:10:00
 Difference: 0.02 minutes
 TEC: 73.19 ± 7.07 TECU
  LATITUDE: -23.21
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 18:08:59: 73.09 ± 6.94 TECU (99.9% of value)
 2. 2024-12-18 18:10:01: 73.19 ± 7.07 TECU (100.0% of value)
 3. 2024-12-18 18:10:58: 73.28 ± 7.21 TECU (100.1% of value)

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:30:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:30:00
 Target Date/Time: 2024-12-18 18:30:00
 Difference: 0.00 minutes
 TEC: 72.30 ± 10.16 TECU
  LATITUDE: -23.21
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 18:28:58: 72.48 ± 9.99 TECU (100.2% of value)
 2. 2024-12-18 18:30:00: 72.30 ± 10.16 TECU (100.0% of value)
 3. 2024-12-18 18:31:01: 72.10 ± 10.28 TECU (99.7% of value)

------------------------------------------------------------
LOOKING FOR VALUES NEAR: 2024-12-18 18:00:00
------------------------------------------------------------
 VALUE FOUND:
 Actual Date/Time: 2024-12-18 18:00:00
 Target Date/Time: 2024-12-18 18:00:00
 Difference: 0.00 minutes
 TEC: 71.73 ± 5.98 TECU
  LATITUDE: -23.21
  HAS a sequence of 3 high values ​​(≥90% of the peak):
 1. 2024-12-18 17:58:58: 71.55 ± 5.91 TECU (99.7% of value)
 2. 2024-12-18 18:00:00: 71.73 ± 5.98 TECU (100.0% of value)
 3. 2024-12-18 18:01:01: 71.90 ± 6.05 TECU (100.2% of value)

========================================================================================================================
RESULTS SUMMARY TABLE
========================================================================================================================
#  Target Time         Found Time          Diff(min) TEC       TEC_STD   Sequence    LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    73.49    8.34    Sim         -23.21
2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    73.19    7.07    Sim         -23.21
3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    72.30    10.16    Sim         -23.21
4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    71.73    5.98    Sim         -23.21
-------------------------------------------------------------------------------------------------

Analysis complete!

================================================================================
STATISTICS OF THE RESULTS FOUND
================================================================================
TEC values ​​found:
 Minimum: 71.73 TECU
 Maximum: 73.49 TECU
 Mean: 72.68 TECU
 Standard deviation: 0.70 TECU

High value sequences found: 4 out of 4 (100.0%)

# TEC maps analysis

In [11]:
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

## EMBRACE

In [12]:
import pandas as pd
import numpy as np

In [13]:
#Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [14]:
!gdown '1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH'

Downloading...
From (original): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH
From (redirected): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH&confirm=t&uuid=54618237-f312-4cc0-975f-6f01fb7e3b69
To: /content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl
100% 157M/157M [00:00<00:00, 234MB/s]

In [15]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [16]:
df_embrace_maps_2024

                                                                TECMAP
DATETIME
2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[16704 rows x 1 columns]

In [17]:
class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)

In [18]:
embrace_tec = Embrace()
embrace_points = embrace_tec.find_nearest_points(lat=-23.20713, lon=-45.86174)

In [19]:
embrace_points

[(-24, -47.5, 18, 17),
 (-24, -45.0, 18, 18),
 (-22, -47.5, 19, 17),
 (-22, -45.0, 19, 18)]

### 12/01 - 18:00

In [20]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [21]:
result

                                                                TECMAP
DATETIME
2024-12-01 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [22]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [23]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [24]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 46., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [25]:
np_embrace_maps.shape

(1, 41, 25)

In [26]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  76.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  78.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  79.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  80.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  76.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  78.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  79.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  80.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 76.0 + 0.395519* 78.0 + 0.136650* 79.0 + 0.259785* 80.0
   Value =  15.8115 +  30.8504 +  10.7953 +  20.7828
   Value = 78.240128

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 78.2401
============================================================

### 12/18 - 18:00

In [27]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [28]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [29]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [30]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [31]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [32]:
np_embrace_maps.shape

(1, 41, 25)

In [33]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  79.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  77.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  81.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  86.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  79.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  77.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  81.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  86.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 79.0 + 0.395519* 77.0 + 0.136650* 81.0 + 0.259785* 86.0
   Value =  16.4357 +  30.4549 +  11.0686 +  22.3415
   Value = 80.300760

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 80.3008
============================================================

### 12/18 - 18:10

In [34]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [35]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [36]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [37]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [38]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 37., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [39]:
np_embrace_maps.shape

(1, 41, 25)

In [40]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  78.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  79.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  86.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  83.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  78.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  79.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  86.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  83.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 78.0 + 0.395519* 79.0 + 0.136650* 86.0 + 0.259785* 83.0
   Value =  16.2276 +  31.2460 +  11.7519 +  21.5622
   Value = 80.787642

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 80.7876
============================================================

### 12/18 - 18:20

In [41]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [42]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [43]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [44]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [45]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [46]:
np_embrace_maps.shape

(1, 41, 25)

In [47]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  74.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  80.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  80.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  86.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  74.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  80.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  80.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  86.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 74.0 + 0.395519* 80.0 + 0.136650* 80.0 + 0.259785* 86.0
   Value =  15.3954 +  31.6415 +  10.9320 +  22.3415
   Value = 80.310434

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 80.3104
============================================================

### 12/18 - 18:30

In [48]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [49]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [50]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [51]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [52]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [53]:
np_embrace_maps.shape

(1, 41, 25)

In [54]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  77.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  79.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  92.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  88.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  77.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  79.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  92.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  88.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 77.0 + 0.395519* 79.0 + 0.136650* 92.0 + 0.259785* 88.0
   Value =  16.0196 +  31.2460 +  12.5718 +  22.8611
   Value = 82.698420

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 82.6984
============================================================

### 12/19 - 18:00

In [55]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [56]:
result

                                                                TECMAP
DATETIME
2024-12-19 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [57]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [58]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [59]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 41., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [60]:
np_embrace_maps.shape

(1, 41, 25)

In [61]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  79.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  76.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  71.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  80.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  79.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  76.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  71.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  80.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 79.0 + 0.395519* 76.0 + 0.136650* 71.0 + 0.259785* 80.0
   Value =  16.4357 +  30.0594 +   9.7021 +  20.7828
   Value = 76.980033

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 76.9800
============================================================

### 12/22 - 18:00

In [62]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [63]:
result

                                                                TECMAP
DATETIME
2024-12-22 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [64]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [65]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [66]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 52., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [67]:
np_embrace_maps.shape

(1, 41, 25)

In [68]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - EMBRACE
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  79.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  78.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  75.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  79.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  79.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  78.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  75.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  79.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 79.0 + 0.395519* 78.0 + 0.136650* 75.0 + 0.259785* 79.0
   Value =  16.4357 +  30.8504 +  10.2487 +  20.5230
   Value = 78.057883

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 78.0579
============================================================

## IGS

In [69]:
import pandas as pd
import numpy as np

In [70]:
#Download TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [71]:
!gdown '1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp'

Downloading...
From: https://drive.google.com/uc?id=1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp
To: /content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl
100% 3.60M/3.60M [00:00<00:00, 179MB/s]

In [72]:
df_igs_maps_2024 = pd.read_pickle('/content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [73]:
df_igs_maps_2024

               DATETIME                                             TECMAP
0   2024-12-01 00:00:00  [[37.7, 34.6, 31.9, 30.0, 28.6, 27.2, 25.8, 24...
1   2024-12-01 02:00:00  [[20.3, 18.7, 18.1, 18.2, 18.2, 18.1, 17.7, 17...
2   2024-12-01 04:00:00  [[11.6, 11.8, 12.0, 12.4, 13.0, 13.5, 14.0, 14...
3   2024-12-01 06:00:00  [[10.4, 10.8, 11.1, 11.7, 12.1, 12.7, 13.3, 13...
4   2024-12-01 08:00:00  [[9.9, 10.1, 10.3, 10.6, 11.0, 11.6, 12.3, 13....
..                  ...                                                ...
343 2024-12-30 14:00:00  [[8.9, 11.1, 14.4, 18.8, 23.7, 28.3, 32.7, 36....
344 2024-12-30 16:00:00  [[26.3, 29.8, 33.4, 37.1, 40.5, 43.7, 47.0, 49...
345 2024-12-30 18:00:00  [[43.5, 44.5, 45.3, 46.2, 47.1, 48.6, 50.0, 51...
346 2024-12-30 20:00:00  [[48.8, 49.1, 49.0, 48.7, 48.5, 48.1, 48.0, 47...
347 2024-12-30 22:00:00  [[47.0, 46.6, 45.6, 44.4, 43.2, 42.0, 40.4, 38...

[348 rows x 2 columns]

In [74]:
class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),  # (lon_min, lon_max, lat_min_geo, lat_max_geo)
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        """
        IGS TEC Map - Specific implementation for IGS data structure.

        IMPORTANT: IGS arrays are organized North to South:
        - Array[0, :] contains the NORTHERNMOST latitudes (+40°)
        - Array[-1, :] contains the SOUTHERNMOST latitudes (-80°)

        The extent parameter follows GEOGRAPHIC convention:
        - extent = (lon_min, lon_max, lat_min_geographic, lat_max_geographic)
        - lat_min_geographic = -80° (southernmost point)
        - lat_max_geographic = +40° (northernmost point)

        This differs from array indexing where Array[0] = +40° (North).
        The find_nearest_points method handles this coordinate conversion.
        """
        super().__init__(extent, lat_step, lon_step)

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat_max - lat) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_max - lat_idx_lower * lat_step
        lat_upper = lat_max - lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

In [75]:
igs_tec = Igs()
igs_points = igs_tec.find_nearest_points(lat=-23.20713, lon=-45.86174)

In [76]:
igs_points

[(-22.5, -50, 25, 12),
 (-22.5, -45, 25, 13),
 (-25.0, -50, 26, 12),
 (-25.0, -45, 26, 13)]

### 12/01 - 18:00

In [77]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [78]:
result

             DATETIME                                             TECMAP
9 2024-12-01 18:00:00  [[50.5, 53.3, 54.8, 55.0, 54.6, 54.1, 54.0, 54...

In [79]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [80]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [81]:
np_igs_maps

array([[[50.5, 53.3, 54.8, ..., 26.7, 24.5, 22.9],
        [50.2, 52.6, 54.1, ..., 30.3, 28.1, 26.2],
        [50.4, 52.2, 53.4, ..., 36.6, 34. , 31.8],
        ...,
        [30.4, 30.4, 30.2, ..., 23.1, 22.6, 22. ],
        [30.3, 30.3, 30.1, ..., 23.2, 22.9, 22.5],
        [29.4, 29.3, 29.2, ..., 23.3, 23.1, 22.8]]])

In [82]:
np_igs_maps.shape

(1, 49, 23)

In [83]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -22.5°,  -50.0°) - Indexes: [25, 12] - TEC:  90.1
   P2: ( -22.5°,  -45.0°) - Indexes: [25, 13] - TEC:  88.4
   P3: ( -25.0°,  -50.0°) - Indexes: [26, 12] - TEC:  87.8
   P4: ( -25.0°,  -45.0°) - Indexes: [26, 13] - TEC:  86.2

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -25.0° to  -22.5° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -25.0°,  -50.0°) =  87.8
   f_01 (lat_min, lon_max) = ( -25.0°,  -45.0°) =  86.2
   f_10 (lat_max, lon_min) = ( -22.5°,  -50.0°) =  90.1
   f_11 (lat_max, lon_max) = ( -22.5°,  -45.0°) =  88.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 4.13826 /  5.0 = 0.827652

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -25.0)) / ( -22.5 - ( -25.0))
   t_y = 1.79287 /  2.5 = 0.717148

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.827652) * (1 - 0.717148) = 0.048749
   w_01 = t_x * (1 - t_y)       = 0.827652 * (1 - 0.717148)       = 0.234103
   w_10 = (1 - t_x) * t_y       = (1 - 0.827652) * 0.717148       = 0.123599
   w_11 = t_x * t_y             = 0.827652 * 0.717148             = 0.593549
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.048749* 87.8 + 0.234103* 86.2 + 0.123599* 90.1 + 0.593549* 88.4
   Value =   4.2802 +  20.1797 +  11.1363 +  52.4697
   Value = 88.065842

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 82.77% of the way from -50° to -45°
   In Y direction (latitude):  71.71% of the way from -25.0° to -22.5°

============================================================
FINAL RESULT: TEC = 88.0658
============================================================

### 12/18 - 18:00

In [84]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:

    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [85]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [86]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [87]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [88]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [89]:
np_igs_maps.shape

(1, 49, 23)

In [90]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -22.5°,  -50.0°) - Indexes: [25, 12] - TEC:  88.0
   P2: ( -22.5°,  -45.0°) - Indexes: [25, 13] - TEC:  86.5
   P3: ( -25.0°,  -50.0°) - Indexes: [26, 12] - TEC:  83.6
   P4: ( -25.0°,  -45.0°) - Indexes: [26, 13] - TEC:  81.6

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -25.0° to  -22.5° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -25.0°,  -50.0°) =  83.6
   f_01 (lat_min, lon_max) = ( -25.0°,  -45.0°) =  81.6
   f_10 (lat_max, lon_min) = ( -22.5°,  -50.0°) =  88.0
   f_11 (lat_max, lon_max) = ( -22.5°,  -45.0°) =  86.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 4.13826 /  5.0 = 0.827652

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -25.0)) / ( -22.5 - ( -25.0))
   t_y = 1.79287 /  2.5 = 0.717148

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.827652) * (1 - 0.717148) = 0.048749
   w_01 = t_x * (1 - t_y)       = 0.827652 * (1 - 0.717148)       = 0.234103
   w_10 = (1 - t_x) * t_y       = (1 - 0.827652) * 0.717148       = 0.123599
   w_11 = t_x * t_y             = 0.827652 * 0.717148             = 0.593549
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.048749* 83.6 + 0.234103* 81.6 + 0.123599* 88.0 + 0.593549* 86.5
   Value =   4.0754 +  19.1028 +  10.8767 +  51.3420
   Value = 85.396922

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 82.77% of the way from -50° to -45°
   In Y direction (latitude):  71.71% of the way from -25.0° to -22.5°

============================================================
FINAL RESULT: TEC = 85.3969
============================================================

### 12/19 - 18:00

In [91]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [92]:
result

               DATETIME                                             TECMAP
213 2024-12-19 18:00:00  [[36.1, 39.3, 41.5, 42.6, 42.4, 41.2, 39.2, 37...

In [93]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [94]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [95]:
np_igs_maps

array([[[36.1, 39.3, 41.5, ..., 15. , 14.4, 14.1],
        [37.3, 40. , 42.4, ..., 17. , 16.5, 16.2],
        [38.2, 40.5, 42.6, ..., 20.6, 20.1, 19.7],
        ...,
        [23.4, 23.3, 23.2, ..., 23.6, 23.2, 22.9],
        [23.3, 23.2, 23.1, ..., 23.7, 23.5, 23.2],
        [23. , 23.1, 22.9, ..., 23.5, 23.6, 23.5]]])

In [96]:
np_igs_maps.shape

(1, 49, 23)

In [97]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -22.5°,  -50.0°) - Indexes: [25, 12] - TEC:  82.6
   P2: ( -22.5°,  -45.0°) - Indexes: [25, 13] - TEC:  81.0
   P3: ( -25.0°,  -50.0°) - Indexes: [26, 12] - TEC:  81.3
   P4: ( -25.0°,  -45.0°) - Indexes: [26, 13] - TEC:  79.1

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -25.0° to  -22.5° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -25.0°,  -50.0°) =  81.3
   f_01 (lat_min, lon_max) = ( -25.0°,  -45.0°) =  79.1
   f_10 (lat_max, lon_min) = ( -22.5°,  -50.0°) =  82.6
   f_11 (lat_max, lon_max) = ( -22.5°,  -45.0°) =  81.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 4.13826 /  5.0 = 0.827652

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -25.0)) / ( -22.5 - ( -25.0))
   t_y = 1.79287 /  2.5 = 0.717148

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.827652) * (1 - 0.717148) = 0.048749
   w_01 = t_x * (1 - t_y)       = 0.827652 * (1 - 0.717148)       = 0.234103
   w_10 = (1 - t_x) * t_y       = (1 - 0.827652) * 0.717148       = 0.123599
   w_11 = t_x * t_y             = 0.827652 * 0.717148             = 0.593549
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.048749* 81.3 + 0.234103* 79.1 + 0.123599* 82.6 + 0.593549* 81.0
   Value =   3.9633 +  18.5175 +  10.2093 +  48.0775
   Value = 80.767587

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 82.77% of the way from -50° to -45°
   In Y direction (latitude):  71.71% of the way from -25.0° to -22.5°

============================================================
FINAL RESULT: TEC = 80.7676
============================================================

### 12/22 - 18:00

In [98]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [99]:
result

               DATETIME                                             TECMAP
249 2024-12-22 18:00:00  [[48.9, 51.6, 53.7, 54.6, 54.9, 54.7, 54.6, 54...

In [100]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [101]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [102]:
np_igs_maps

array([[[48.9, 51.6, 53.7, ..., 23. , 21.7, 20.7],
        [49.6, 52. , 53.9, ..., 25.5, 24.4, 23. ],
        [50.2, 52.1, 53.8, ..., 30.7, 29.2, 27.9],
        ...,
        [24.7, 24.7, 24.4, ..., 20.9, 20.5, 20.2],
        [25. , 24.9, 24.8, ..., 21.5, 21. , 20.8],
        [24.7, 24.8, 24.5, ..., 21.6, 21.2, 20.9]]])

In [103]:
np_igs_maps.shape

(1, 49, 23)

In [104]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -22.5°,  -50.0°) - Indexes: [25, 12] - TEC:  87.3
   P2: ( -22.5°,  -45.0°) - Indexes: [25, 13] - TEC:  85.7
   P3: ( -25.0°,  -50.0°) - Indexes: [26, 12] - TEC:  84.1
   P4: ( -25.0°,  -45.0°) - Indexes: [26, 13] - TEC:  82.2

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -25.0° to  -22.5° (range:  2.5°)
   Longitude:  -50.0° to  -45.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -25.0°,  -50.0°) =  84.1
   f_01 (lat_min, lon_max) = ( -25.0°,  -45.0°) =  82.2
   f_10 (lat_max, lon_min) = ( -22.5°,  -50.0°) =  87.3
   f_11 (lat_max, lon_max) = ( -22.5°,  -45.0°) =  85.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -50.0)) / ( -45.0 - ( -50.0))
   t_x = 4.13826 /  5.0 = 0.827652

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -25.0)) / ( -22.5 - ( -25.0))
   t_y = 1.79287 /  2.5 = 0.717148

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.827652) * (1 - 0.717148) = 0.048749
   w_01 = t_x * (1 - t_y)       = 0.827652 * (1 - 0.717148)       = 0.234103
   w_10 = (1 - t_x) * t_y       = (1 - 0.827652) * 0.717148       = 0.123599
   w_11 = t_x * t_y             = 0.827652 * 0.717148             = 0.593549
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.048749* 84.1 + 0.234103* 82.2 + 0.123599* 87.3 + 0.593549* 85.7
   Value =   4.0998 +  19.2433 +  10.7902 +  50.8671
   Value = 85.000399

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 82.77% of the way from -50° to -45°
   In Y direction (latitude):  71.71% of the way from -25.0° to -22.5°

============================================================
FINAL RESULT: TEC = 85.0004
============================================================

## MAGGIA

In [105]:
import pandas as pd
import numpy as np

In [106]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [107]:
!gdown '1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33'

Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33

but Gdown can't. Please check connections and permissions.

In [110]:
!curl 'https://drive.usercontent.google.com/download?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33&export=download&authuser=0&confirm=t&uuid=c08ac5de-3885-4f79-94ca-8c330c18a009&at=AN8xHoquUkJpNDx3MgFLBpAklXfq%3A1758216852519' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'cache-control: no-cache' \
  -b 'SID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE2PPdTeaOJdBeAtlpmXw0sewACgYKAbcSARMSFQHGX2MiN1EGMoYW5-zZxBT1_ezSjxoVAUF8yKp-Bxf-8e594r0CQzdCemGa0076; __Secure-1PSID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE232KZqePrzsSMgAiOjp4augACgYKAfwSARMSFQHGX2MiPmCqH2pVXTz0Lo82CmWsBhoVAUF8yKr1aTm8Qb3W38L98ZBLWPW00076; __Secure-3PSID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE2breUz8eJRfYGoHI-qm-VKQACgYKAagSARMSFQHGX2Mi-twVlgPzsTmjh9L3oX7OnRoVAUF8yKoG1gSkhWePQUxvPuKDbr8S0076; HSID=AMSoVtm4f2JOblFWQ; SSID=Ar4xkmiXaV7ZvsP_s; APISID=kylgo9NxpVDz00IS/AjUM8Yk5s56Ua4Eh8; SAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; __Secure-1PAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; __Secure-3PAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; AEC=AaJma5sHSMxOHlxGgF7UlW_iRFyPyjgEr18diEgqqKCL2BLcwan5fEPRB2s; NID=525=CNtlUvsSnUt4R6c7ftiXrWGpj-HywIsZMApOnrSLpatxi1U5dgZBC5UHUQzq7Pjps-73Xed-NUfBQ7OYju3vKKs7V4Qw_7yB7oHkcD1p2V3c3pX7-MiOZUiJHmSkgfa1pQCwfANSpSjelh8Ndyh6mEXWPm3-gbvVVJlQaowIOKd_57vTOsMYVT14LVIJKdqekPmvS7pY19rFTlH0KMR1qAKmMToSum6NmVfk_p6FgAMGTbTQPDkZadOC-GJsoITTxuMz6pq2UxqArcy3IUzb5uQCbnHwUDaPUlJueqCjwUsnmQjx5_LdWMGRMUdwmNr4fckZRsQtrmM4y4NKg-eMQ7I4GQ2Pf9k6oW0uec99qvGGf6djhOB5EymsROT6II3w6prjjqxe9zODQVxTHx8rsWUjCm9ch_x6EeuYb9I0eNVs7NszzhNHDbT_PnuiNhx2fdxkRDLx3aG3pv4QxJKpbQu8FhEAbp7BmHEn1Y9EWsM1NkPf3eMVd_XEY6ZqZuJRdLORbg-6aDI0TXn3FG2K0zbJuSCKaAN3w0mQ9eb-fSS_UOe34iFWC8jBJVSExm_bZm1DM0u5VKdRqyyzeLvaapxcoq1Yr42pmn7JRVKhV47kCQjjs6zUKBiAp8U1wUrJF0ARe060TY-sZG7qbmbqmeLP87ykzXsb2Agr1GwA6vI1E-Y_EnSsKS7soFLQAx5C2yCOwRcp9EnjUl11cweqkc99_TGeESvGKjFbxcBVNRia3zHJdZcbDffn--cII9HZmOClyv2nrlU-MuIYugpTIhoyPCU71TihKMuJvv_sduOJ0aTzYWwDkQsdnmNk-FG7ynOzC2OCJaHfuGtAt8Z8h2Fr_8Do32Gy5tPqeACm39QPKhD9Z1W-azqpwChPKAG_rWZfNa6kjYCTBKCx0VnCgx2uTgeCP2GFZM9K; OSID=g.a0001ggDnh5vx7v2eXlOltr9BhXJTuJGu2rYsDhPqgRqu_bMlLhWSwgL10CN_GVXM8AAGTOfjQACgYKAc8SARMSFQHGX2Mio9qh9iwu6yV724Fq_YOEaBoVAUF8yKrkBz3OaQOngPuEPxIRQLYk0076; __Secure-OSID=g.a0001ggDnh5vx7v2eXlOltr9BhXJTuJGu2rYsDhPqgRqu_bMlLhWDP1aRXplTvdXAt02bUhtHwACgYKAccSARMSFQHGX2MiwPavYoxhd3f5_lXW-LBmNhoVAUF8yKrk8442K3HPIhUbccBs4W2a0076; __Secure-1PSIDTS=sidts-CjIBmkD5SyLITgP9_sYOQuEI9JJ2RgtchvpW1-RF2yiJLgz2b9da-ciV_5aN2Vkn1r94mBAA; __Secure-3PSIDTS=sidts-CjIBmkD5SyLITgP9_sYOQuEI9JJ2RgtchvpW1-RF2yiJLgz2b9da-ciV_5aN2Vkn1r94mBAA; SIDCC=AKEyXzXuaje9M0q4LWLp1nGjS2LA2sAonEPAj0AMsIHNMw8y0rmkJS-XdojNu-FOa9AwUNZMUtM; __Secure-1PSIDCC=AKEyXzUrezOPnzm1BJBcxjq3B1YEnB0N-6Xi82Yc95wzIiHbKnEqcTn7Em0kvhMZfFVMP8Te1w; __Secure-3PSIDCC=AKEyXzXq6KHNyRMkrqVDBLZhU5zQRcg6zMUup2Uzc_G3vLmPBx8v8jpTHdJuySnfX767xF5kBg' \
  -H 'pragma: no-cache' \
  -H 'priority: u=0, i' \
  -H 'sec-ch-ua: "Chromium";v="140", "Not=A?Brand";v="24", "Google Chrome";v="140"' \
  -H 'sec-ch-ua-arch: "x86"' \
  -H 'sec-ch-ua-bitness: "64"' \
  -H 'sec-ch-ua-form-factors: "Desktop"' \
  -H 'sec-ch-ua-full-version: "140.0.7339.127"' \
  -H 'sec-ch-ua-full-version-list: "Chromium";v="140.0.7339.127", "Not=A?Brand";v="24.0.0.0", "Google Chrome";v="140.0.7339.127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-model: ""' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-ch-ua-platform-version: "6.11.0"' \
  -H 'sec-ch-ua-wow64: ?0' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36' \
  -H 'x-browser-channel: stable' \
  -H 'x-browser-copyright: Copyright 2025 Google LLC. All rights reserved.' \
  -H 'x-browser-validation: vkog5hSrCvuYLnOVCb84JEvPqcg=' \
  -H 'x-browser-year: 2025' \
  -H 'x-client-data: CJO2yQEIo7bJAQipncoBCNCgygEIrYfLAQiTocsBCIegzQE=' > 'TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7157M  100 7157M    0     0  89.6M      0  0:01:19  0:01:19 --:--:--  109M

In [111]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [112]:
df_maggia_maps_2024

                 DATETIME                                             TECMAP
0     2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2024-09-05 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
15619 2024-12-31 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15620 2024-12-31 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15621 2024-12-31 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15622 2024-12-31 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15623 2024-12-31 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[15624 rows x 2 columns]

In [113]:
class Maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [114]:
maggia_tec = Maggia()
maggia_points = maggia_tec.find_nearest_points(lat=-23.20713, lon=-45.86174)

In [115]:
maggia_points

[(-23.5, -46.0, 113, 128),
 (-23.5, -45.5, 113, 129),
 (-23.0, -46.0, 114, 128),
 (-23.0, -45.5, 114, 129)]

### 12/01 - 18:00

In [116]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [117]:
result

                 DATETIME                                             TECMAP
11268 2024-12-01 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [118]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [119]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [120]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [45.95299911, 45.88100052, 45.71300125, ..., 23.45899963,
         23.20400047, 22.93400002],
        [45.90299988, 45.8370018 , 45.67300034, ..., 23.38800049,
         23.23900032, 23.04000092],
        [45.86399841, 45.79700089, 45.63999939, ..., 23.29700089,
         23.1590004 , 23.00300026]]])

In [121]:
np_maggia_maps.shape

(1, 241, 221)

In [122]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  86.6
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  85.8
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  89.6
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  89.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  86.6
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  85.8
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  89.6
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  89.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 86.6 + 0.114551* 85.8 + 0.423771* 89.6 + 0.161969* 89.0
   Value =  25.9671 +   9.8298 +  37.9720 +  14.4133
   Value = 88.182122

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 88.1821
============================================================

### 12/18 - 18:00

In [123]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [124]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [125]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [126]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [127]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [128]:
np_maggia_maps.shape

(1, 241, 221)

In [129]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  85.7
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  79.4
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  82.8
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  83.2

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  85.7
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  79.4
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  82.8
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  83.2

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 85.7 + 0.114551* 79.4 + 0.423771* 82.8 + 0.161969* 83.2
   Value =  25.6874 +   9.0901 +  35.0908 +  13.4779
   Value = 83.346245

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 83.3462
============================================================

### 12/18 - 18:10

In [130]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [131]:
result

                 DATETIME                                             TECMAP
13717 2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [132]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [133]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [134]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [36.83499908, 37.06399918, 37.23899841, ..., 12.40799999,
         12.40799999, 12.40799999],
        [36.57699966, 36.82799911, 37.03300095, ..., 12.85900021,
         12.6619997 , 12.54399967],
        [36.34600067, 36.5909996 , 36.81399918, ..., 13.00500011,
         12.82999992, 12.32600021]]])

In [135]:
np_maggia_maps.shape

(1, 241, 221)

In [136]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  85.7
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  80.1
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  85.8
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  83.7

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  85.7
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  80.1
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  85.8
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  83.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 85.7 + 0.114551* 80.1 + 0.423771* 85.8 + 0.161969* 83.7
   Value =  25.6725 +   9.1797 +  36.3401 +  13.5646
   Value = 84.756769

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 84.7568
============================================================

### 12/18 - 18:20

In [137]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [138]:
result

                 DATETIME                                             TECMAP
13718 2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [139]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [140]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [141]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [40.14899826, 40.15000153, 40.18000031, ..., 13.84500027,
         13.67500019, 13.12800026],
        [39.97399902, 40.02799988, 40.15399933, ..., 13.75800037,
         13.67599964, 12.39599991],
        [39.73500061, 39.83499908, 40.02500153, ..., 13.10700035,
         12.6239996 , 12.06000042]]])

In [142]:
np_maggia_maps.shape

(1, 241, 221)

In [143]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  84.3
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  81.6
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  86.6
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  84.2

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  84.3
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  81.6
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  86.6
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  84.2

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 84.3 + 0.114551* 81.6 + 0.423771* 86.6 + 0.161969* 84.2
   Value =  25.2738 +   9.3420 +  36.7041 +  13.6434
   Value = 84.963375

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 84.9634
============================================================

### 12/18 - 18:30

In [144]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [145]:
result

                 DATETIME                                             TECMAP
13719 2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [146]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [147]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [148]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.94900131, 41.94900131, 41.94900131, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.94400024, 41.94400024, 41.94499969, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.89500046, 41.89799881, 41.90100098, ..., 11.36600018,
         11.25800037, 11.1960001 ]]])

In [149]:
np_maggia_maps.shape

(1, 241, 221)

In [150]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  81.6
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  82.2
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  86.3
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  85.6

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  81.6
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  82.2
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  86.3
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  85.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 81.6 + 0.114551* 82.2 + 0.423771* 86.3 + 0.161969* 85.6
   Value =  24.4553 +   9.4126 +  36.5579 +  13.8615
   Value = 84.287241

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 84.2872
============================================================

### 12/19 - 18:00

In [151]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [152]:
result

                 DATETIME                                             TECMAP
13860 2024-12-19 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [153]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [154]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [155]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [37.94499969, 38.06100082, 38.13499832, ..., 11.56599998,
         11.17399979, 10.60200024],
        [37.7840004 , 37.92599869, 38.02999878, ..., 11.47599983,
         10.99199963, 10.38300037],
        [37.63499832, 37.77899933, 37.90499878, ..., 11.36100006,
         10.8739996 , 10.52200031]]])

In [156]:
np_maggia_maps.shape

(1, 241, 221)

In [157]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  80.6
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  80.8
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  80.1
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  80.8

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  80.6
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  80.8
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  80.1
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  80.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 80.6 + 0.114551* 80.8 + 0.423771* 80.1 + 0.161969* 80.8
   Value =  24.1610 +   9.2548 +  33.9568 +  13.0832
   Value = 80.455822

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 80.4558
============================================================

### 12/22 - 18:00

In [158]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [159]:
result

                 DATETIME                                             TECMAP
14292 2024-12-22 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [160]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [161]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [162]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.41400146, 48.5379982 , 48.59199905, ..., 19.10899925,
         17.45599937, 17.45599937],
        [48.26200104, 48.41799927, 48.52799988, ..., 18.8560009 ,
         18.24600029, 17.79299927],
        [48.11100006, 48.27999878, 48.42100143, ..., 19.0890007 ,
         18.74200058, 18.39999962]]])

In [163]:
np_maggia_maps.shape

(1, 241, 221)

In [164]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  87.6
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  86.1
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  87.9
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  86.8

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  87.6
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  86.1
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  87.9
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  86.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 87.6 + 0.114551* 86.1 + 0.423771* 87.9 + 0.161969* 86.8
   Value =  26.2605 +   9.8655 +  37.2571 +  14.0518
   Value = 87.434860

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 87.4349
============================================================

## Nagoya

In [165]:
import pandas as pd
import numpy as np

In [166]:
#Download TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [167]:
!gdown '1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR'

Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR

but Gdown can't. Please check connections and permissions.

In [169]:
!curl 'https://drive.usercontent.google.com/download?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR&export=download&authuser=0&confirm=t&uuid=e62294f3-5d3b-4201-9821-f868319ab167&at=AN8xHorzxZ0OGZmSGDgcRLrJ2nEF%3A1758217090390' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'cache-control: no-cache' \
  -b 'SID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE2PPdTeaOJdBeAtlpmXw0sewACgYKAbcSARMSFQHGX2MiN1EGMoYW5-zZxBT1_ezSjxoVAUF8yKp-Bxf-8e594r0CQzdCemGa0076; __Secure-1PSID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE232KZqePrzsSMgAiOjp4augACgYKAfwSARMSFQHGX2MiPmCqH2pVXTz0Lo82CmWsBhoVAUF8yKr1aTm8Qb3W38L98ZBLWPW00076; __Secure-3PSID=g.a0001QgDnv7PqHbM8Pn7sIxqKj3lHVD4fl3G2RgkdSiAccVawJE2breUz8eJRfYGoHI-qm-VKQACgYKAagSARMSFQHGX2Mi-twVlgPzsTmjh9L3oX7OnRoVAUF8yKoG1gSkhWePQUxvPuKDbr8S0076; HSID=AMSoVtm4f2JOblFWQ; SSID=Ar4xkmiXaV7ZvsP_s; APISID=kylgo9NxpVDz00IS/AjUM8Yk5s56Ua4Eh8; SAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; __Secure-1PAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; __Secure-3PAPISID=dfw72HSW2gMI0NIv/ActmezOe8M9c6ZNKq; AEC=AaJma5sHSMxOHlxGgF7UlW_iRFyPyjgEr18diEgqqKCL2BLcwan5fEPRB2s; NID=525=CNtlUvsSnUt4R6c7ftiXrWGpj-HywIsZMApOnrSLpatxi1U5dgZBC5UHUQzq7Pjps-73Xed-NUfBQ7OYju3vKKs7V4Qw_7yB7oHkcD1p2V3c3pX7-MiOZUiJHmSkgfa1pQCwfANSpSjelh8Ndyh6mEXWPm3-gbvVVJlQaowIOKd_57vTOsMYVT14LVIJKdqekPmvS7pY19rFTlH0KMR1qAKmMToSum6NmVfk_p6FgAMGTbTQPDkZadOC-GJsoITTxuMz6pq2UxqArcy3IUzb5uQCbnHwUDaPUlJueqCjwUsnmQjx5_LdWMGRMUdwmNr4fckZRsQtrmM4y4NKg-eMQ7I4GQ2Pf9k6oW0uec99qvGGf6djhOB5EymsROT6II3w6prjjqxe9zODQVxTHx8rsWUjCm9ch_x6EeuYb9I0eNVs7NszzhNHDbT_PnuiNhx2fdxkRDLx3aG3pv4QxJKpbQu8FhEAbp7BmHEn1Y9EWsM1NkPf3eMVd_XEY6ZqZuJRdLORbg-6aDI0TXn3FG2K0zbJuSCKaAN3w0mQ9eb-fSS_UOe34iFWC8jBJVSExm_bZm1DM0u5VKdRqyyzeLvaapxcoq1Yr42pmn7JRVKhV47kCQjjs6zUKBiAp8U1wUrJF0ARe060TY-sZG7qbmbqmeLP87ykzXsb2Agr1GwA6vI1E-Y_EnSsKS7soFLQAx5C2yCOwRcp9EnjUl11cweqkc99_TGeESvGKjFbxcBVNRia3zHJdZcbDffn--cII9HZmOClyv2nrlU-MuIYugpTIhoyPCU71TihKMuJvv_sduOJ0aTzYWwDkQsdnmNk-FG7ynOzC2OCJaHfuGtAt8Z8h2Fr_8Do32Gy5tPqeACm39QPKhD9Z1W-azqpwChPKAG_rWZfNa6kjYCTBKCx0VnCgx2uTgeCP2GFZM9K; OSID=g.a0001ggDnh5vx7v2eXlOltr9BhXJTuJGu2rYsDhPqgRqu_bMlLhWSwgL10CN_GVXM8AAGTOfjQACgYKAc8SARMSFQHGX2Mio9qh9iwu6yV724Fq_YOEaBoVAUF8yKrkBz3OaQOngPuEPxIRQLYk0076; __Secure-OSID=g.a0001ggDnh5vx7v2eXlOltr9BhXJTuJGu2rYsDhPqgRqu_bMlLhWDP1aRXplTvdXAt02bUhtHwACgYKAccSARMSFQHGX2MiwPavYoxhd3f5_lXW-LBmNhoVAUF8yKrk8442K3HPIhUbccBs4W2a0076; __Secure-1PSIDTS=sidts-CjIBmkD5SyLITgP9_sYOQuEI9JJ2RgtchvpW1-RF2yiJLgz2b9da-ciV_5aN2Vkn1r94mBAA; __Secure-3PSIDTS=sidts-CjIBmkD5SyLITgP9_sYOQuEI9JJ2RgtchvpW1-RF2yiJLgz2b9da-ciV_5aN2Vkn1r94mBAA; SIDCC=AKEyXzWFvJYTVOWwklbps7CGYj_lvH__oFCd0zQYe0WtTJmitgFN09568k_O5-gjuWvVeadmeT4; __Secure-1PSIDCC=AKEyXzXwJvBZ6vV2H9Ua9mRN_9KX71xQsaSI38-F62LFPYHzCaqbYn3pAgr776EswU0vpsBSxg; __Secure-3PSIDCC=AKEyXzW1IqN__lDZ8oR8EbYqjahtmuYEtw_SD-LwyR6-suKZ7eIYLm8N-tMCroVUrWPhquluZQ' \
  -H 'pragma: no-cache' \
  -H 'priority: u=0, i' \
  -H 'sec-ch-ua: "Chromium";v="140", "Not=A?Brand";v="24", "Google Chrome";v="140"' \
  -H 'sec-ch-ua-arch: "x86"' \
  -H 'sec-ch-ua-bitness: "64"' \
  -H 'sec-ch-ua-form-factors: "Desktop"' \
  -H 'sec-ch-ua-full-version: "140.0.7339.127"' \
  -H 'sec-ch-ua-full-version-list: "Chromium";v="140.0.7339.127", "Not=A?Brand";v="24.0.0.0", "Google Chrome";v="140.0.7339.127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-model: ""' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-ch-ua-platform-version: "6.11.0"' \
  -H 'sec-ch-ua-wow64: ?0' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36' \
  -H 'x-browser-channel: stable' \
  -H 'x-browser-copyright: Copyright 2025 Google LLC. All rights reserved.' \
  -H 'x-browser-validation: vkog5hSrCvuYLnOVCb84JEvPqcg=' \
  -H 'x-browser-year: 2025' \
  -H 'x-client-data: CJO2yQEIo7bJAQipncoBCNCgygEIrYfLAQiTocsBCIegzQE=' > 'TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3842M  100 3842M    0     0   187M      0  0:00:20  0:00:20 --:--:--  217M

In [170]:
df_nagoya_maps_2024 = pd.read_pickle('TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [171]:
df_nagoya_maps_2024

                DATETIME                                             TECMAP
0    2024-12-01 00:00:00  [[18.593109130859375, 19.42150115966797, 19.42...
1    2024-12-01 00:05:00  [[18.222612380981445, 18.222612380981445, 18.2...
2    2024-12-01 00:10:00  [[18.21422576904297, 18.21422576904297, 18.214...
3    2024-12-01 00:15:00  [[18.284513473510742, 18.284513473510742, 18.0...
4    2024-12-01 00:20:00  [[18.328298568725586, 18.328298568725586, 18.0...
...                  ...                                                ...
8347 2024-12-30 23:35:00  [[26.173906326293945, 27.259140014648438, 27.2...
8348 2024-12-30 23:40:00  [[27.0389347076416, 27.0389347076416, 27.03893...
8349 2024-12-30 23:45:00  [[26.902502059936523, 26.72080421447754, 25.94...
8350 2024-12-30 23:50:00  [[27.88735580444336, 27.88735580444336, 27.887...
8351 2024-12-30 23:55:00  [[24.682987213134766, 25.294950485229492, 25.2...

[8352 rows x 2 columns]

In [172]:
class Nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [173]:
nagoya_tec = Nagoya()
nagoya_points = nagoya_tec.find_nearest_points(lat=-23.20713, lon=-45.86174)

In [174]:
nagoya_points

[(-23.400000000000006, -46.0, 114, 128),
 (-23.400000000000006, -45.5, 114, 129),
 (-22.900000000000006, -46.0, 115, 128),
 (-22.900000000000006, -45.5, 115, 129)]

### 12/01 - 18:00

In [175]:
import pandas as pd

date = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [176]:
result

               DATETIME                                             TECMAP
216 2024-12-01 18:00:00  [[5.463457107543945, 5.463457107543945, 5.4634...

In [177]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [178]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [179]:
np_nagoya_maps

array([[[ 5.46345711,  5.46345711,  5.46345711, ...,         nan,
                 nan,         nan],
        [ 9.9241066 , 10.95889568, 10.95889568, ...,         nan,
                 nan,         nan],
        [14.80212975, 14.80212975, 14.12398911, ...,         nan,
                 nan,         nan],
        ...,
        [43.88991547, 44.48843002, 44.89578247, ..., 21.9361248 ,
         21.8728199 , 21.43001556],
        [44.12051773, 44.59725952, 44.77046967, ..., 21.9361248 ,
         21.76833344, 21.42024994],
        [44.22133255, 44.64913177, 44.84080887, ..., 21.9361248 ,
         21.67697716, 21.29607773]]])

In [180]:
np_nagoya_maps.shape

(1, 242, 221)

In [181]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.4°,  -46.0°) - Indexes: [114, 128] - TEC:  78.7
   P2: ( -23.4°,  -45.5°) - Indexes: [114, 129] - TEC:  78.5
   P3: ( -22.9°,  -46.0°) - Indexes: [115, 128] - TEC:  78.5
   P4: ( -22.9°,  -45.5°) - Indexes: [115, 129] - TEC:  78.3

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.4° to  -22.9° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.4°,  -46.0°) =  78.7
   f_01 (lat_min, lon_max) = ( -23.4°,  -45.5°) =  78.5
   f_10 (lat_max, lon_min) = ( -22.9°,  -46.0°) =  78.5
   f_11 (lat_max, lon_max) = ( -22.9°,  -45.5°) =  78.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x = 0.13826 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -23.4)) / ( -22.9 - ( -23.4))
   t_y = 0.19287 /  0.5 = 0.385740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.385740) = 0.444405
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.385740)       = 0.169855
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.385740       = 0.279075
   w_11 = t_x * t_y             = 0.276520 * 0.385740             = 0.106665
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.444405* 78.7 + 0.169855* 78.5 + 0.279075* 78.5 + 0.106665* 78.3
   Value =  34.9938 +  13.3273 +  21.9000 +   8.3483
   Value = 78.569376

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  38.57% of the way from -23.400000000000006° to -22.900000000000006°

============================================================
FINAL RESULT: TEC = 78.5694
============================================================

### 12/18 - 18:00

In [182]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [183]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [184]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [185]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [186]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [187]:
np_nagoya_maps.shape

(1, 242, 221)

In [188]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.4°,  -46.0°) - Indexes: [114, 128] - TEC:  82.9
   P2: ( -23.4°,  -45.5°) - Indexes: [114, 129] - TEC:  81.7
   P3: ( -22.9°,  -46.0°) - Indexes: [115, 128] - TEC:  84.2
   P4: ( -22.9°,  -45.5°) - Indexes: [115, 129] - TEC:  82.1

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.4° to  -22.9° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.4°,  -46.0°) =  82.9
   f_01 (lat_min, lon_max) = ( -23.4°,  -45.5°) =  81.7
   f_10 (lat_max, lon_min) = ( -22.9°,  -46.0°) =  84.2
   f_11 (lat_max, lon_max) = ( -22.9°,  -45.5°) =  82.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x = 0.13826 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -23.4)) / ( -22.9 - ( -23.4))
   t_y = 0.19287 /  0.5 = 0.385740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.385740) = 0.444405
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.385740)       = 0.169855
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.385740       = 0.279075
   w_11 = t_x * t_y             = 0.276520 * 0.385740             = 0.106665
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.444405* 82.9 + 0.169855* 81.7 + 0.279075* 84.2 + 0.106665* 82.1
   Value =  36.8527 +  13.8754 +  23.5108 +   8.7597
   Value = 82.998548

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  38.57% of the way from -23.400000000000006° to -22.900000000000006°

============================================================
FINAL RESULT: TEC = 82.9985
============================================================

### 12/18 - 18:10

In [189]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [190]:
result

                DATETIME                                             TECMAP
4826 2024-12-18 18:10:00  [[18.412939071655273, 17.651090621948242, 17.6...

In [191]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [192]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [193]:
np_nagoya_maps

array([[[18.41293907, 17.65109062, 17.65109062, ...,         nan,
                 nan,         nan],
        [18.53962135, 17.62540054, 17.62540054, ...,         nan,
                 nan,         nan],
        [17.62013054, 17.62013054, 17.62540054, ...,         nan,
                 nan,         nan],
        ...,
        [36.95772552, 37.32144928, 37.6816864 , ..., 14.07102394,
         13.53792286, 13.37452602],
        [37.09318542, 37.28800964, 37.65478134, ..., 13.818923  ,
         13.44021893, 13.28282356],
        [36.133461  , 36.14941025, 36.71422577, ..., 13.40729332,
         13.00967979, 13.02010918]]])

In [194]:
np_nagoya_maps.shape

(1, 242, 221)

In [195]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.4°,  -46.0°) - Indexes: [114, 128] - TEC:  82.9
   P2: ( -23.4°,  -45.5°) - Indexes: [114, 129] - TEC:  83.6
   P3: ( -22.9°,  -46.0°) - Indexes: [115, 128] - TEC:  84.9
   P4: ( -22.9°,  -45.5°) - Indexes: [115, 129] - TEC:  85.6

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.4° to  -22.9° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.4°,  -46.0°) =  82.9
   f_01 (lat_min, lon_max) = ( -23.4°,  -45.5°) =  83.6
   f_10 (lat_max, lon_min) = ( -22.9°,  -46.0°) =  84.9
   f_11 (lat_max, lon_max) = ( -22.9°,  -45.5°) =  85.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x = 0.13826 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -23.4)) / ( -22.9 - ( -23.4))
   t_y = 0.19287 /  0.5 = 0.385740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.385740) = 0.444405
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.385740)       = 0.169855
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.385740       = 0.279075
   w_11 = t_x * t_y             = 0.276520 * 0.385740             = 0.106665
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.444405* 82.9 + 0.169855* 83.6 + 0.279075* 84.9 + 0.106665* 85.6
   Value =  36.8349 +  14.2029 +  23.7032 +   9.1263
   Value = 83.867300

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  38.57% of the way from -23.400000000000006° to -22.900000000000006°

============================================================
FINAL RESULT: TEC = 83.8673
============================================================

### 12/18 - 18:20

In [196]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [197]:
result

                DATETIME                                             TECMAP
4828 2024-12-18 18:20:00  [[18.751976013183594, 18.751976013183594, 18.8...

In [198]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [199]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [200]:
np_nagoya_maps

array([[[18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.25943375, 18.13648224, 18.13648224, ...,         nan,
                 nan,         nan],
        ...,
        [38.79235458, 39.10980225, 39.51619339, ..., 13.45065308,
         13.1072731 , 12.96411705],
        [38.38473892, 38.68589783, 39.00465393, ..., 13.27555275,
         12.90675449, 12.72219276],
        [38.23902512, 38.27802277, 38.43577194, ..., 12.968153  ,
         12.60940075, 12.51128292]]])

In [201]:
np_nagoya_maps.shape

(1, 242, 221)

In [202]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.4°,  -46.0°) - Indexes: [114, 128] - TEC:  81.2
   P2: ( -23.4°,  -45.5°) - Indexes: [114, 129] - TEC:  81.2
   P3: ( -22.9°,  -46.0°) - Indexes: [115, 128] - TEC:  82.0
   P4: ( -22.9°,  -45.5°) - Indexes: [115, 129] - TEC:  82.7

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.4° to  -22.9° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.4°,  -46.0°) =  81.2
   f_01 (lat_min, lon_max) = ( -23.4°,  -45.5°) =  81.2
   f_10 (lat_max, lon_min) = ( -22.9°,  -46.0°) =  82.0
   f_11 (lat_max, lon_max) = ( -22.9°,  -45.5°) =  82.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x = 0.13826 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -23.4)) / ( -22.9 - ( -23.4))
   t_y = 0.19287 /  0.5 = 0.385740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.385740) = 0.444405
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.385740)       = 0.169855
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.385740       = 0.279075
   w_11 = t_x * t_y             = 0.276520 * 0.385740             = 0.106665
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.444405* 81.2 + 0.169855* 81.2 + 0.279075* 82.0 + 0.106665* 82.7
   Value =  36.0908 +  13.7942 +  22.8780 +   8.8171
   Value = 81.580177

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  38.57% of the way from -23.400000000000006° to -22.900000000000006°

============================================================
FINAL RESULT: TEC = 81.5802
============================================================

### 12/18 - 18:30

In [203]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [204]:
result

                DATETIME                                             TECMAP
4830 2024-12-18 18:30:00  [[21.299997329711914, 21.299997329711914, 21.2...

In [205]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [206]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [207]:
np_nagoya_maps

array([[[21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.28308678, 21.28308678, 21.28308678, ...,         nan,
                 nan,         nan],
        ...,
        [39.65393066, 40.11976624, 40.50592804, ..., 13.14062977,
         12.80635357, 12.63247967],
        [39.26050949, 39.7519455 , 40.19271851, ..., 12.65815067,
         12.54124069, 12.46903992],
        [39.23273468, 39.40169144, 39.72786331, ..., 12.41631317,
         12.32884121, 12.25786972]]])

In [208]:
np_nagoya_maps.shape

(1, 242, 221)

In [209]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.4°,  -46.0°) - Indexes: [114, 128] - TEC:  82.0
   P2: ( -23.4°,  -45.5°) - Indexes: [114, 129] - TEC:  81.0
   P3: ( -22.9°,  -46.0°) - Indexes: [115, 128] - TEC:  83.6
   P4: ( -22.9°,  -45.5°) - Indexes: [115, 129] - TEC:  81.8

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.4° to  -22.9° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.4°,  -46.0°) =  82.0
   f_01 (lat_min, lon_max) = ( -23.4°,  -45.5°) =  81.0
   f_10 (lat_max, lon_min) = ( -22.9°,  -46.0°) =  83.6
   f_11 (lat_max, lon_max) = ( -22.9°,  -45.5°) =  81.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x = 0.13826 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -23.4)) / ( -22.9 - ( -23.4))
   t_y = 0.19287 /  0.5 = 0.385740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.385740) = 0.444405
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.385740)       = 0.169855
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.385740       = 0.279075
   w_11 = t_x * t_y             = 0.276520 * 0.385740             = 0.106665
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.444405* 82.0 + 0.169855* 81.0 + 0.279075* 83.6 + 0.106665* 81.8
   Value =  36.4624 +  13.7532 +  23.3224 +   8.7226
   Value = 82.260679

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  38.57% of the way from -23.400000000000006° to -22.900000000000006°

============================================================
FINAL RESULT: TEC = 82.2607
============================================================

### 12/19 - 18:00

In [210]:
import pandas as pd

date = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [211]:
result

                DATETIME                                             TECMAP
5112 2024-12-19 18:00:00  [[12.639724731445312, 11.565997123718262, 11.5...

In [212]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [213]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [214]:
np_nagoya_maps

array([[[12.63972473, 11.56599712, 11.56599712, ...,         nan,
                 nan,         nan],
        [11.71732426, 10.61837482, 10.61837482, ...,         nan,
                 nan,         nan],
        [14.18716908, 11.54071808, 10.25730038, ...,         nan,
                 nan,         nan],
        ...,
        [34.01515198, 34.48353958, 34.89712906, ..., 11.77007103,
         11.27845764, 11.27845764],
        [33.72997284, 33.06239319, 33.53577042, ..., 11.66871548,
         11.30887318, 11.18506527],
        [33.0634613 , 32.32966614, 32.78850937, ..., 11.32422161,
         11.1510849 , 11.04978752]]])

In [215]:
np_nagoya_maps.shape

(1, 242, 221)

In [216]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.4°,  -46.0°) - Indexes: [114, 128] - TEC:  76.6
   P2: ( -23.4°,  -45.5°) - Indexes: [114, 129] - TEC:  76.8
   P3: ( -22.9°,  -46.0°) - Indexes: [115, 128] - TEC:  76.0
   P4: ( -22.9°,  -45.5°) - Indexes: [115, 129] - TEC:  76.0

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.4° to  -22.9° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.4°,  -46.0°) =  76.6
   f_01 (lat_min, lon_max) = ( -23.4°,  -45.5°) =  76.8
   f_10 (lat_max, lon_min) = ( -22.9°,  -46.0°) =  76.0
   f_11 (lat_max, lon_max) = ( -22.9°,  -45.5°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x = 0.13826 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -23.4)) / ( -22.9 - ( -23.4))
   t_y = 0.19287 /  0.5 = 0.385740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.385740) = 0.444405
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.385740)       = 0.169855
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.385740       = 0.279075
   w_11 = t_x * t_y             = 0.276520 * 0.385740             = 0.106665
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.444405* 76.6 + 0.169855* 76.8 + 0.279075* 76.0 + 0.106665* 76.0
   Value =  34.0508 +  13.0422 +  21.2078 +   8.1058
   Value = 76.406551

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  38.57% of the way from -23.400000000000006° to -22.900000000000006°

============================================================
FINAL RESULT: TEC = 76.4066
============================================================

### 12/22 - 18:00

In [217]:
import pandas as pd

date = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [218]:
result

                DATETIME                                             TECMAP
5976 2024-12-22 18:00:00  [[14.305987358093262, 14.235016822814941, 15.1...

In [219]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [220]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [221]:
np_nagoya_maps

array([[[14.30598736, 14.23501682, 15.19717693, ...,         nan,
                 nan,         nan],
        [13.24124527, 13.24124527, 13.24124527, ...,         nan,
                 nan,         nan],
        [13.24124527, 13.24124527, 13.24124527, ...,         nan,
                 nan,         nan],
        ...,
        [43.63508224, 43.97467422, 44.23501205, ..., 20.72278595,
         20.15914345, 19.78045845],
        [43.53390503, 43.86975861, 44.0747261 , ..., 20.29078865,
         19.64533615, 19.32730103],
        [43.54644394, 43.77022934, 43.95893478, ..., 19.72059822,
         19.0694046 , 18.65716362]]])

In [222]:
np_nagoya_maps.shape

(1, 242, 221)

In [223]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.4°,  -46.0°) - Indexes: [114, 128] - TEC:  80.9
   P2: ( -23.4°,  -45.5°) - Indexes: [114, 129] - TEC:  81.0
   P3: ( -22.9°,  -46.0°) - Indexes: [115, 128] - TEC:  81.0
   P4: ( -22.9°,  -45.5°) - Indexes: [115, 129] - TEC:  81.3

2. TARGET POINT: (-23.20713°, -45.86174°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.4° to  -22.9° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.4°,  -46.0°) =  80.9
   f_01 (lat_min, lon_max) = ( -23.4°,  -45.5°) =  81.0
   f_10 (lat_max, lon_min) = ( -22.9°,  -46.0°) =  81.0
   f_11 (lat_max, lon_max) = ( -22.9°,  -45.5°) =  81.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86174 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x = 0.13826 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.20713 - ( -23.4)) / ( -22.9 - ( -23.4))
   t_y = 0.19287 /  0.5 = 0.385740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.385740) = 0.444405
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.385740)       = 0.169855
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.385740       = 0.279075
   w_11 = t_x * t_y             = 0.276520 * 0.385740             = 0.106665
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.444405* 80.9 + 0.169855* 81.0 + 0.279075* 81.0 + 0.106665* 81.3
   Value =  35.9373 +  13.7544 +  22.5986 +   8.6727
   Value = 80.963068

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  38.57% of the way from -23.400000000000006° to -22.900000000000006°

============================================================
FINAL RESULT: TEC = 80.9631
============================================================