# Gopi TEC Brasília analysis - 09/27/2024

In [ ]:
#Download Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [ ]:
%pwd

'/content'

In [ ]:
!ls

Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip  sample_data

In [ ]:
!unzip 'Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_BRAZ_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: braz271-2024-09-27.Std
  inflating: braz336-2024-12-01.Std
  inflating: braz337-2024-12-02.Std
  inflating: braz338-2024-12-03.Std
  inflating: braz339-2024-12-04.Std
  inflating: braz340-2024-12-05.Std
  inflating: braz341-2024-12-06.Std
  inflating: braz342-2024-12-07.Std
  inflating: braz343-2024-12-08.Std
  inflating: braz344-2024-12-09.Std
  inflating: braz345-2024-12-10.Std
  inflating: braz346-2024-12-11.Std
  inflating: braz347-2024-12-12.Std
  inflating: braz348-2024-12-13.Std
  inflating: braz349-2024-12-14.Std
  inflating: braz350-2024-12-15.Std
  inflating: braz351-2024-12-16.Std
  inflating: braz352-2024-12-17.Std
  inflating: braz353-2024-12-18.Std
  inflating: braz354-2024-12-19.Std
  inflating: braz355-2024-12-20.Std
  inflating: braz356-2024-12-21.Std
  inflating: braz357-2024-12-22.Std
  inflating: braz358-2024-12-23.Std
  inflating: braz359-2024-12-24.Std
  inflating: braz361-2024-12-26.Std
  inflating: braz362-2024-12-27.Std
  inflating: braz363-2024-12-28.Std
  inflating: braz364-2024-12-29.Std
  inflating: braz365-2024-12-30.Std
  inflating: braz366-2024-12-31.Std
  inflating: braz271-2024-09-27_page0.png
  inflating: braz271-2024-09-27-wbias.png
  inflating: braz336-2024-12-01_page0.png
  inflating: braz336-2024-12-01-wbias.png
  inflating: braz337-2024-12-02_page0.png
  inflating: braz337-2024-12-02-wbias.png
  inflating: braz338-2024-12-03_page0.png
  inflating: braz338-2024-12-03-wbias.png
  inflating: braz339-2024-12-04_page0.png
  inflating: braz339-2024-12-04-wbias.png
  inflating: braz340-2024-12-05_page0.png
  inflating: braz340-2024-12-05-wbias.png
  inflating: braz341-2024-12-06_page0.png
  inflating: braz341-2024-12-06-wbias.png
  inflating: braz342-2024-12-07_page0.png
  inflating: braz342-2024-12-07-wbias.png
  inflating: braz343-2024-12-08_page0.png
  inflating: braz343-2024-12-08-wbias.png
  inflating: braz344-2024-12-09_page0.png
  inflating: braz344-2024-12-09-wbias.png
  inflating: braz345-2024-12-10_page0.png
  inflating: braz345-2024-12-10-wbias.png
  inflating: braz346-2024-12-11_page0.png
  inflating: braz346-2024-12-11-wbias.png
  inflating: braz347-2024-12-12_page0.png
  inflating: braz347-2024-12-12-wbias.png
  inflating: braz348-2024-12-13_page0.png
  inflating: braz348-2024-12-13-wbias.png
  inflating: braz349-2024-12-14_page0.png
  inflating: braz349-2024-12-14-wbias.png
  inflating: braz350-2024-12-15_page0.png
  inflating: braz350-2024-12-15-wbias.png
  inflating: braz351-2024-12-16_page0.png
  inflating: braz351-2024-12-16-wbias.png
  inflating: braz352-2024-12-17_page0.png
  inflating: braz352-2024-12-17-wbias.png
  inflating: braz353-2024-12-18_page0.png
  inflating: braz353-2024-12-18-wbias.png
  inflating: braz354-2024-12-19_page0.png
  inflating: braz354-2024-12-19-wbias.png
  inflating: braz355-2024-12-20_page0.png
  inflating: braz355-2024-12-20-wbias.png
  inflating: braz356-2024-12-21_page0.png
  inflating: braz356-2024-12-21-wbias.png
  inflating: braz357-2024-12-22_page0.png
  inflating: braz357-2024-12-22-wbias.png
  inflating: braz358-2024-12-23_page0.png
  inflating: braz358-2024-12-23-wbias.png
  inflating: braz359-2024-12-24_page0.png
  inflating: braz359-2024-12-24-wbias.png
  inflating: braz361-2024-12-26_page0.png
  inflating: braz361-2024-12-26-wbias.png
  inflating: braz362-2024-12-27_page0.png
  inflating: braz362-2024-12-27-wbias.png
  inflating: braz363-2024-12-28_page0.png
  inflating: braz363-2024-12-28-wbias.png
  inflating: braz364-2024-12-29_page0.png
  inflating: braz364-2024-12-29-wbias.png
  inflating: braz365-2024-12-30_page0.png
  inflating: braz365-2024-12-30-wbias.png
  inflating: braz366-2024-12-31_page0.png
  inflating: braz366-2024-12-31-wbias.png
  inflating: braz271-2024-09-27.Bias
  inflating: braz271-2024-09-27.Cmn
  inflating: braz336-2024-12-01.Bias
  inflating: braz336-2024-12-01.Cmn
  inflating: braz337-2024-12-02.Bias
  inflating: braz337-2024-12-02.Cmn
  inflating: braz338-2024-12-03.Bias
  inflating: braz338-2024-12-03.Cmn
  inflating: braz339-2024-12-04.Bias
  inflating: braz339-2024-12-04.Cmn
  inflating: braz340-2024-12-05.Bias
  inflating: braz340-2024-12-05.Cmn
  inflating: braz341-2024-12-06.Bias
  inflating: braz341-2024-12-06.Cmn
  inflating: braz342-2024-12-07.Bias
  inflating: braz342-2024-12-07.Cmn
  inflating: braz343-2024-12-08.Bias
  inflating: braz343-2024-12-08.Cmn
  inflating: braz344-2024-12-09.Bias
  inflating: braz344-2024-12-09.Cmn
  inflating: braz345-2024-12-10.Bias
  inflating: braz345-2024-12-10.Cmn
  inflating: braz346-2024-12-11.Bias
  inflating: braz346-2024-12-11.Cmn
  inflating: braz347-2024-12-12.Bias
  inflating: braz347-2024-12-12.Cmn
  inflating: braz348-2024-12-13.Bias
  inflating: braz348-2024-12-13.Cmn
  inflating: braz349-2024-12-14.Bias
  inflating: braz349-2024-12-14.Cmn
  inflating: braz350-2024-12-15.Bias
  inflating: braz350-2024-12-15.Cmn
  inflating: braz351-2024-12-16.Bias
  inflating: braz351-2024-12-16.Cmn
  inflating: braz352-2024-12-17.Bias
  inflating: braz352-2024-12-17.Cmn
  inflating: braz353-2024-12-18.Bias
  inflating: braz353-2024-12-18.Cmn
  inflating: braz354-2024-12-19.Bias
  inflating: braz354-2024-12-19.Cmn
  inflating: braz355-2024-12-20.Bias
  inflating: braz355-2024-12-20.Cmn
  inflating: braz356-2024-12-21.Bias
  inflating: braz356-2024-12-21.Cmn
  inflating: braz357-2024-12-22.Bias
  inflating: braz357-2024-12-22.Cmn
  inflating: braz358-2024-12-23.Bias
  inflating: braz358-2024-12-23.Cmn
  inflating: braz359-2024-12-24.Bias
  inflating: braz359-2024-12-24.Cmn
  inflating: braz361-2024-12-26.Bias
  inflating: braz361-2024-12-26.Cmn
  inflating: braz362-2024-12-27.Bias
  inflating: braz362-2024-12-27.Cmn
  inflating: braz363-2024-12-28.Bias
  inflating: braz363-2024-12-28.Cmn
  inflating: braz364-2024-12-29.Bias
  inflating: braz364-2024-12-29.Cmn
  inflating: braz365-2024-12-30.Bias
  inflating: braz365-2024-12-30.Cmn
  inflating: braz366-2024-12-31.Bias
  inflating: braz366-2024-12-31.Cmn
  inflating: missing_rbmc_files_2024.txt

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

pd.set_option('display.max_rows', None)

df = pd.read_csv('braz271-2024-09-27.Std', sep='\s+', header=None)

df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

base_date = datetime(2024, 9, 27)

def decimal_to_time(decimal_hours):
    hours = int(decimal_hours)
    minutes = int((decimal_hours - hours) * 60)
    seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
    return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

print(df)

df.to_pickle('braz271-2024-09-27.pkl')

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-859440300.py:7: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('braz271-2024-09-27.Std', sep='\s+', header=None)

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  97.46     6.43    -15.95
1    2024-09-27 00:01:01  97.42     6.23    -15.95
2    2024-09-27 00:01:58  97.38     5.64    -15.95
3    2024-09-27 00:03:00  97.33     5.48    -15.95
4    2024-09-27 00:04:01  97.28     5.24    -15.95
5    2024-09-27 00:04:58  97.22     4.80    -15.95
6    2024-09-27 00:06:00  97.15     4.21    -15.95
7    2024-09-27 00:07:01  97.08     4.12    -15.95
8    2024-09-27 00:07:58  97.00     3.41    -15.95
9    2024-09-27 00:09:00  96.92     3.86    -15.95
10   2024-09-27 00:10:01  96.83     3.76    -15.95
11   2024-09-27 00:10:58  96.73     3.49    -15.95
12   2024-09-27 00:12:00  96.63     3.49    -15.95
13   2024-09-27 00:13:01  96.51     2.92    -15.95
14   2024-09-27 00:13:58  96.40     3.76    -15.95
15   2024-09-27 00:15:00  96.27     2.81    -15.95
16   2024-09-27 00:16:01  96.14     4.68    -15.95
17   2024-09-27 00:16:58  96.00     5.15    -15.95
18   2024-09-27 00:18:00  95.86     5.21    -15.95
19   2024-09-27 00:19:01  95.71     5.13    -15.95
20   2024-09-27 00:19:58  95.56     4.67    -15.95
21   2024-09-27 00:21:00  95.41     5.17    -15.95
22   2024-09-27 00:22:01    NaN      NaN    -15.95
23   2024-09-27 00:22:58    NaN      NaN    -15.95
24   2024-09-27 00:24:00  95.24     5.20    -15.95
25   2024-09-27 00:25:01  95.08     5.59    -15.95
26   2024-09-27 00:25:58  94.91     5.45    -15.95
27   2024-09-27 00:27:00  94.74     5.50    -15.95
28   2024-09-27 00:28:01  94.57     5.18    -15.95
29   2024-09-27 00:28:58  94.40     5.44    -15.95
30   2024-09-27 00:30:00  94.23     5.00    -15.95
31   2024-09-27 00:31:01  94.06     5.52    -15.95
32   2024-09-27 00:31:58  93.89     6.18    -15.95
33   2024-09-27 00:33:00  93.72     6.03    -15.95
34   2024-09-27 00:34:01  93.56     5.90    -15.95
35   2024-09-27 00:34:58  93.40     5.08    -15.95
36   2024-09-27 00:36:00  93.24     6.96    -15.95
37   2024-09-27 00:37:01  93.09     5.91    -15.95
38   2024-09-27 00:37:58  92.95     5.74    -15.95
39   2024-09-27 00:39:00  92.81     6.54    -15.95
40   2024-09-27 00:40:01  92.68     7.05    -15.95
41   2024-09-27 00:40:58  92.56     7.21    -15.95
42   2024-09-27 00:42:00  92.45     7.87    -15.95
43   2024-09-27 00:43:01  92.35     7.76    -15.95
44   2024-09-27 00:43:58  92.26     8.23    -15.95
45   2024-09-27 00:45:00  92.18     8.38    -15.95
46   2024-09-27 00:46:01  92.10     7.89    -15.95
47   2024-09-27 00:46:58  92.04     8.15    -15.95
48   2024-09-27 00:48:00  92.00     8.51    -15.95
49   2024-09-27 00:49:01  91.96     7.83    -15.95
50   2024-09-27 00:49:58  91.93     8.91    -15.95
51   2024-09-27 00:51:00  91.92     8.60    -15.95
52   2024-09-27 00:52:01  91.92     8.39    -15.95
53   2024-09-27 00:52:58  91.92     8.64    -15.95
54   2024-09-27 00:54:00  91.94     8.57    -15.95
55   2024-09-27 00:55:01  91.98     8.57    -15.95
56   2024-09-27 00:55:58  92.02     8.17    -15.95
57   2024-09-27 00:57:00  92.07     7.74    -15.95
58   2024-09-27 00:58:01  92.13     8.16    -15.95
59   2024-09-27 00:58:58  92.20     8.15    -15.95
60   2024-09-27 01:00:00  92.28     7.67    -15.95
61   2024-09-27 01:01:01  92.37     7.94    -15.95
62   2024-09-27 01:01:58  92.46     6.82    -15.95
63   2024-09-27 01:03:00  92.56     8.15    -15.95
64   2024-09-27 01:04:01  92.67     9.11    -15.95
65   2024-09-27 01:04:58  92.78     8.19    -15.95
66   2024-09-27 01:06:00  92.90     8.57    -15.95
67   2024-09-27 01:07:01  93.01     8.81    -15.95
68   2024-09-27 01:07:58  93.13     9.73    -15.95
69   2024-09-27 01:08:59  93.26    10.57    -15.95
70   2024-09-27 01:10:01  93.38     9.55    -15.95
71   2024-09-27 01:10:58  93.49    10.81    -15.95
72   2024-09-27 01:11:59  93.61    10.93    -15.95
73   2024-09-27 01:13:01  93.73     8.49    -15.95
74   2024-09-27 01:13:58  93.84     9.83    -15.95
75   2024-09-27 01:15:00  93.94    11.78    -15.95
76   2024-09-27 01:16:01  94.04     7.01    -15.95
77   2024-09-27 01:16:58  94.13     5.70    -15.95
78   2024-09-27 01:18:00  94.22     7.07    -15.95
79   2024-09-27 01:19:01  94.29     6.71    -15.95
80   2024-09-27 01:19:58  94.36     6.29    -15.95
81   2024-09-27 01:21:00  94.42     7.98    -15.95
82   2024-09-27 01:22:01  94.46     7.00    -15.95
83   2024-09-27 01:22:58  94.50     8.29    -15.95
84   2024-09-27 01:23:59  94.52     8.31    -15.95
85   2024-09-27 01:25:01  94.53     7.46    -15.95
86   2024-09-27 01:25:58  94.53     8.50    -15.95
87   2024-09-27 01:26:59  94.51     8.89    -15.95
88   2024-09-27 01:28:01  94.49     7.66    -15.95
89   2024-09-27 01:28:58  94.45     8.20    -15.95
90   2024-09-27 01:30:00  94.39     8.67    -15.95
91   2024-09-27 01:31:01  94.32     9.79    -15.95
92   2024-09-27 01:31:58  94.24     9.33    -15.95
93   2024-09-27 01:33:00  94.15    10.39    -15.95
94   2024-09-27 01:34:01  94.04     7.23    -15.95
95   2024-09-27 01:34:58  93.93     5.96    -15.95
96   2024-09-27 01:36:00  93.79     5.34    -15.95
97   2024-09-27 01:37:01  93.65     5.86    -15.95
98   2024-09-27 01:37:58  93.50     5.36    -15.95
99   2024-09-27 01:38:59  93.33     5.68    -15.95
100  2024-09-27 01:40:01  93.16     5.15    -15.95
101  2024-09-27 01:40:58  92.97     5.46    -15.95
102  2024-09-27 01:42:00  92.78     5.11    -15.95
103  2024-09-27 01:43:01  92.58     5.00    -15.95
104  2024-09-27 01:43:58  92.37     4.59    -15.95
105  2024-09-27 01:45:00  92.15     5.19    -15.95
106  2024-09-27 01:46:01  91.93     5.22    -15.95
107  2024-09-27 01:46:58  91.70     5.59    -15.95
108  2024-09-27 01:48:00  91.47     6.42    -15.95
109  2024-09-27 01:49:01  91.24     5.77    -15.95
110  2024-09-27 01:49:58  91.00     6.91    -15.95
111  2024-09-27 01:51:00  90.76     7.03    -15.95
112  2024-09-27 01:52:01  90.52     7.32    -15.95
113  2024-09-27 01:52:58  90.28     7.45    -15.95
114  2024-09-27 01:53:59  90.04     8.13    -15.95
115  2024-09-27 01:55:01  89.80     8.11    -15.95
116  2024-09-27 01:55:58  89.57     8.54    -15.95
117  2024-09-27 01:57:00  89.33     7.48    -15.95
118  2024-09-27 01:58:01  89.10    12.41    -15.95
119  2024-09-27 01:58:58  88.87    12.78    -15.95
120  2024-09-27 02:00:00  88.64    13.41    -15.95
121  2024-09-27 02:01:01  88.42    13.56    -15.95
122  2024-09-27 02:01:58  88.19    14.23    -15.95
123  2024-09-27 02:02:59  87.98    12.58    -15.95
124  2024-09-27 02:04:01  87.77    13.72    -15.95
125  2024-09-27 02:04:58  87.56    14.92    -15.95
126  2024-09-27 02:06:00  87.35    14.77    -15.95
127  2024-09-27 02:07:01  87.15    14.67    -15.95
128  2024-09-27 02:07:58  86.95    15.62    -15.95
129  2024-09-27 02:08:59  86.76    14.84    -15.95
130  2024-09-27 02:10:01  86.56    14.56    -15.95
131  2024-09-27 02:10:58  86.38    15.46    -15.95
132  2024-09-27 02:12:00  86.19    15.80    -15.95
133  2024-09-27 02:13:01  86.00    15.00    -15.95
134  2024-09-27 02:13:58  85.82    15.02    -15.95
135  2024-09-27 02:15:00  85.63    14.94    -15.95
136  2024-09-27 02:16:01  85.45    15.11    -15.95
137  2024-09-27 02:16:58  85.27    14.27    -15.95
138  2024-09-27 02:17:59  85.08    15.19    -15.95
139  2024-09-27 02:19:01  84.90    14.52    -15.95
140  2024-09-27 02:19:58  84.71    15.50    -15.95
141  2024-09-27 02:21:00  84.53    17.19    -15.95
142  2024-09-27 02:22:01  84.33    13.70    -15.95
143  2024-09-27 02:22:58  84.14    14.61    -15.95
144  2024-09-27 02:23:59  83.94    12.85    -15.95
145  2024-09-27 02:25:01  83.74    13.64    -15.95
146  2024-09-27 02:25:58  83.53    14.65    -15.95
147  2024-09-27 02:27:00  83.32    13.35    -15.95
148  2024-09-27 02:28:01  83.11    13.25    -15.95
149  2024-09-27 02:28:58  82.89    13.03    -15.95
150  2024-09-27 02:30:00  82.66    13.43    -15.95
151  2024-09-27 02:31:01  82.43    12.14    -15.95
152  2024-09-27 02:31:58  82.19    12.41    -15.95
153  2024-09-27 02:32:59  81.95    11.36    -15.95
154  2024-09-27 02:34:01  81.70    11.75    -15.95
155  2024-09-27 02:34:58  81.44    10.64    -15.95
156  2024-09-27 02:36:00  81.18    11.46    -15.95
157  2024-09-27 02:37:01  80.90    10.38    -15.95
158  2024-09-27 02:37:58  80.62     9.74    -15.95
159  2024-09-27 02:38:59  80.34    10.49    -15.95
160  2024-09-27 02:40:01  80.05    10.26    -15.95
161  2024-09-27 02:40:58  79.75     9.24    -15.95
162  2024-09-27 02:42:00  79.44    10.25    -15.95
163  2024-09-27 02:43:01  79.13     9.63    -15.95
164  2024-09-27 02:43:58  78.81    10.27    -15.95
165  2024-09-27 02:45:00  78.48    10.21    -15.95
166  2024-09-27 02:46:01  78.15    10.32    -15.95
167  2024-09-27 02:46:58  77.81     9.41    -15.95
168  2024-09-27 02:47:59  77.47     9.78    -15.95
169  2024-09-27 02:49:01  77.12    10.12    -15.95
170  2024-09-27 02:49:58  76.77     9.00    -15.95
171  2024-09-27 02:51:00  76.41    10.00    -15.95
172  2024-09-27 02:52:01  76.05     8.97    -15.95
173  2024-09-27 02:52:58  75.68     9.33    -15.95
174  2024-09-27 02:53:59  75.31    10.17    -15.95
175  2024-09-27 02:55:01  74.94     9.16    -15.95
176  2024-09-27 02:55:58  74.57     9.10    -15.95
177  2024-09-27 02:57:00  74.20     8.56    -15.95
178  2024-09-27 02:58:01  73.83    10.38    -15.95
179  2024-09-27 02:58:58  73.46     9.03    -15.95
180  2024-09-27 03:00:00  73.09     9.28    -15.95
181  2024-09-27 03:01:01  72.72    10.24    -15.95
182  2024-09-27 03:01:58  72.35     8.98    -15.95
183  2024-09-27 03:02:59  71.99     9.52    -15.95
184  2024-09-27 03:04:01  71.64     9.86    -15.95
185  2024-09-27 03:04:58  71.28     9.40    -15.95
186  2024-09-27 03:06:00  70.94     8.92    -15.95
187  2024-09-27 03:07:01  70.60    10.33    -15.95
188  2024-09-27 03:07:58  70.27     7.99    -15.95
189  2024-09-27 03:08:59  69.95     7.79    -15.95
190  2024-09-27 03:10:01  69.64     7.98    -15.95
191  2024-09-27 03:10:58  69.34     8.34    -15.95
192  2024-09-27 03:12:00  69.05     8.23    -15.95
193  2024-09-27 03:13:01  68.77     8.56    -15.95
194  2024-09-27 03:13:58  68.50     8.48    -15.95
195  2024-09-27 03:15:00  68.25     8.13    -15.95
196  2024-09-27 03:16:01  68.01     8.41    -15.95
197  2024-09-27 03:16:58  67.79     8.97    -15.95
198  2024-09-27 03:17:59  67.58     8.76    -15.95
199  2024-09-27 03:19:01  67.38     8.62    -15.95
200  2024-09-27 03:19:58  67.20     8.81    -15.95
201  2024-09-27 03:21:00  67.04     9.02    -15.95
202  2024-09-27 03:22:01  66.89     9.16    -15.95
203  2024-09-27 03:22:58  66.75     8.36    -15.95
204  2024-09-27 03:23:59  66.63     8.99    -15.95
205  2024-09-27 03:25:01  66.53     9.35    -15.95
206  2024-09-27 03:25:58  66.44     8.42    -15.95
207  2024-09-27 03:27:00  66.36     9.17    -15.95
208  2024-09-27 03:28:01  66.30     9.29    -15.95
209  2024-09-27 03:28:58  66.25     9.07    -15.95
210  2024-09-27 03:30:00  66.21     8.64    -15.95
211  2024-09-27 03:31:01  66.18     8.88    -15.95
212  2024-09-27 03:31:58  66.17    10.50    -15.95
213  2024-09-27 03:32:59  66.16    11.10    -15.95
214  2024-09-27 03:34:01  66.16    10.03    -15.95
215  2024-09-27 03:34:58  66.18    10.28    -15.95
216  2024-09-27 03:36:00  66.19    10.14    -15.95
217  2024-09-27 03:37:01  66.22    10.86    -15.95
218  2024-09-27 03:37:58  66.24    10.90    -15.95
219  2024-09-27 03:38:59  66.27    11.06    -15.95
220  2024-09-27 03:40:01  66.31    10.72    -15.95
221  2024-09-27 03:40:58  66.34    11.40    -15.95
222  2024-09-27 03:42:00  66.38    11.40    -15.95
223  2024-09-27 03:43:01  66.41    11.33    -15.95
224  2024-09-27 03:43:58  66.45    11.52    -15.95
225  2024-09-27 03:45:00  66.47    12.40    -15.95
226  2024-09-27 03:46:01  66.50    12.35    -15.95
227  2024-09-27 03:46:58  66.52    11.81    -15.95
228  2024-09-27 03:47:59  66.54    11.95    -15.95
229  2024-09-27 03:49:01  66.55    11.83    -15.95
230  2024-09-27 03:49:58  66.55    11.71    -15.95
231  2024-09-27 03:51:00  66.54    11.71    -15.95
232  2024-09-27 03:52:01  66.53    11.44    -15.95
233  2024-09-27 03:52:58  66.51    11.74    -15.95
234  2024-09-27 03:53:59  66.47    10.77    -15.95
235  2024-09-27 03:55:01  66.43    11.20    -15.95
236  2024-09-27 03:55:58  66.38    10.81    -15.95
237  2024-09-27 03:57:00  66.32    11.00    -15.95
238  2024-09-27 03:58:01  66.24    11.55    -15.95
239  2024-09-27 03:58:58  66.16    10.14    -15.95
240  2024-09-27 04:00:00  66.06    10.30    -15.95
241  2024-09-27 04:01:01  65.95    10.47    -15.95
242  2024-09-27 04:01:58  65.83    10.93    -15.95
243  2024-09-27 04:02:59  65.70     9.84    -15.95
244  2024-09-27 04:04:01  65.56    11.22    -15.95
245  2024-09-27 04:04:58  65.40    10.87    -15.95
246  2024-09-27 04:05:59  65.23    11.70    -15.95
247  2024-09-27 04:07:01  65.05    10.01    -15.95
248  2024-09-27 04:07:58  64.86    11.43    -15.95
249  2024-09-27 04:09:00  64.66     9.94    -15.95
250  2024-09-27 04:10:01  64.45    10.79    -15.95
251  2024-09-27 04:10:58  64.22     9.48    -15.95
252  2024-09-27 04:12:00  63.99    10.19    -15.95
253  2024-09-27 04:13:01  63.74    10.77    -15.95
254  2024-09-27 04:13:58  63.48     9.10    -15.95
255  2024-09-27 04:15:00  63.21     9.98    -15.95
256  2024-09-27 04:16:01  62.93     9.51    -15.95
257  2024-09-27 04:16:58  62.64    10.32    -15.95
258  2024-09-27 04:17:59  62.34     8.66    -15.95
259  2024-09-27 04:19:01  62.03     9.34    -15.95
260  2024-09-27 04:19:58  61.70     9.87    -15.95
261  2024-09-27 04:20:59  61.37     9.03    -15.95
262  2024-09-27 04:22:01  61.03     8.86    -15.95
263  2024-09-27 04:22:58  60.68     7.90    -15.95
264  2024-09-27 04:24:00  60.31     9.20    -15.95
265  2024-09-27 04:25:01  59.94     7.63    -15.95
266  2024-09-27 04:25:58  59.56     8.49    -15.95
267  2024-09-27 04:27:00  59.17     8.12    -15.95
268  2024-09-27 04:28:01  58.77     7.99    -15.95
269  2024-09-27 04:28:58  58.36     8.12    -15.95
270  2024-09-27 04:30:00  57.94     7.91    -15.95
271  2024-09-27 04:31:01  57.51     7.68    -15.95
272  2024-09-27 04:31:58  57.07     8.32    -15.95
273  2024-09-27 04:32:59  56.63     6.90    -15.95
274  2024-09-27 04:34:01  56.17     7.54    -15.95
275  2024-09-27 04:34:58  55.71     8.07    -15.95
276  2024-09-27 04:35:59  55.24     6.66    -15.95
277  2024-09-27 04:37:01  54.76     7.28    -15.95
278  2024-09-27 04:37:58  54.27     7.34    -15.95
279  2024-09-27 04:39:00  53.78     7.18    -15.95
280  2024-09-27 04:40:01  53.28     7.09    -15.95
281  2024-09-27 04:40:58  52.77     6.95    -15.95
282  2024-09-27 04:42:00  52.25     7.11    -15.95
283  2024-09-27 04:43:01  51.73     7.28    -15.95
284  2024-09-27 04:43:58  51.20     6.15    -15.95
285  2024-09-27 04:45:00  50.66     6.86    -15.95
286  2024-09-27 04:46:01  50.11     6.66    -15.95
287  2024-09-27 04:46:58  49.56     6.62    -15.95
288  2024-09-27 04:47:59  49.01     6.46    -15.95
289  2024-09-27 04:49:01  48.45     6.70    -15.95
290  2024-09-27 04:49:58  47.88     6.57    -15.95
291  2024-09-27 04:50:59  47.31     6.94    -15.95
292  2024-09-27 04:52:01  46.73     6.02    -15.95
293  2024-09-27 04:52:58  46.15     6.51    -15.95
294  2024-09-27 04:54:00  45.56     6.33    -15.95
295  2024-09-27 04:55:01  44.97     6.92    -15.95
296  2024-09-27 04:55:58  44.38     5.75    -15.95
297  2024-09-27 04:57:00  43.78     6.30    -15.95
298  2024-09-27 04:58:01  43.18     6.24    -15.95
299  2024-09-27 04:58:58  42.58     6.13    -15.95
300  2024-09-27 05:00:00  41.98     6.45    -15.95
301  2024-09-27 05:01:01  41.37     5.70    -15.95
302  2024-09-27 05:01:58  40.76     6.00    -15.95
303  2024-09-27 05:02:59  40.15     5.49    -15.95
304  2024-09-27 05:04:01  39.54     5.54    -15.95
305  2024-09-27 05:04:58  38.92     5.58    -15.95
306  2024-09-27 05:05:59  38.31     5.10    -15.95
307  2024-09-27 05:07:01  37.70     5.40    -15.95
308  2024-09-27 05:07:58  37.09     5.25    -15.95
309  2024-09-27 05:09:00  36.47     5.17    -15.95
310  2024-09-27 05:10:01  35.86     5.15    -15.95
311  2024-09-27 05:10:58  35.25     5.09    -15.95
312  2024-09-27 05:12:00  34.65     4.90    -15.95
313  2024-09-27 05:13:01  34.04     4.96    -15.95
314  2024-09-27 05:13:58  33.44     4.97    -15.95
315  2024-09-27 05:15:00  32.84     4.56    -15.95
316  2024-09-27 05:16:01  32.25     4.89    -15.95
317  2024-09-27 05:16:58  31.66     4.40    -15.95
318  2024-09-27 05:17:59  31.07     4.37    -15.95
319  2024-09-27 05:19:01  30.49     4.35    -15.95
320  2024-09-27 05:19:58  29.92     4.33    -15.95
321  2024-09-27 05:20:59  29.35     4.34    -15.95
322  2024-09-27 05:22:01  28.78     4.31    -15.95
323  2024-09-27 05:22:58  28.23     4.18    -15.95
324  2024-09-27 05:24:00  27.67     4.32    -15.95
325  2024-09-27 05:25:01  27.13     4.52    -15.95
326  2024-09-27 05:25:58  26.59     4.23    -15.95
327  2024-09-27 05:27:00  26.06     4.33    -15.95
328  2024-09-27 05:28:01  25.54     4.13    -15.95
329  2024-09-27 05:28:58  25.02     4.53    -15.95
330  2024-09-27 05:30:00  24.51     4.15    -15.95
331  2024-09-27 05:31:01  24.01     4.39    -15.95
332  2024-09-27 05:31:58  23.52     4.38    -15.95
333  2024-09-27 05:32:59  23.04     4.65    -15.95
334  2024-09-27 05:34:01  22.56     4.11    -15.95
335  2024-09-27 05:34:58  22.09     4.66    -15.95
336  2024-09-27 05:35:59  21.63     4.23    -15.95
337  2024-09-27 05:37:01  21.17     4.69    -15.95
338  2024-09-27 05:37:58  20.73     4.53    -15.95
339  2024-09-27 05:39:00  20.29     4.33    -15.95
340  2024-09-27 05:40:01  19.86     4.57    -15.95
341  2024-09-27 05:40:58  19.44     4.61    -15.95
342  2024-09-27 05:42:00  19.03     4.98    -15.95
343  2024-09-27 05:43:01  18.62     4.68    -15.95
344  2024-09-27 05:43:58  18.22     4.47    -15.95
345  2024-09-27 05:45:00  17.83     4.65    -15.95
346  2024-09-27 05:46:01  17.45     4.92    -15.95
347  2024-09-27 05:46:58  17.07     5.33    -15.95
348  2024-09-27 05:47:59  16.70     4.54    -15.95
349  2024-09-27 05:49:01  16.34     5.47    -15.95
350  2024-09-27 05:49:58  15.99     5.12    -15.95
351  2024-09-27 05:50:59  15.64     4.68    -15.95
352  2024-09-27 05:52:01  15.30     5.37    -15.95
353  2024-09-27 05:52:58  14.97     5.13    -15.95
354  2024-09-27 05:54:00  14.64     5.70    -15.95
355  2024-09-27 05:55:01  14.33     5.32    -15.95
356  2024-09-27 05:55:58  14.02     5.34    -15.95
357  2024-09-27 05:57:00  13.71     5.36    -15.95
358  2024-09-27 05:58:01  13.41     4.86    -15.95
359  2024-09-27 05:58:58  13.13     5.86    -15.95
360  2024-09-27 06:00:00  12.84     5.45    -15.95
361  2024-09-27 06:01:01  12.57     4.94    -15.95
362  2024-09-27 06:01:58  12.30     5.54    -15.95
363  2024-09-27 06:02:59  12.04     5.99    -15.95
364  2024-09-27 06:04:01  11.78     5.58    -15.95
365  2024-09-27 06:04:58  11.53     5.03    -15.95
366  2024-09-27 06:05:59  11.29     6.14    -15.95
367  2024-09-27 06:07:01  11.05     5.12    -15.95
368  2024-09-27 06:07:58  10.83     5.72    -15.95
369  2024-09-27 06:09:00  10.60     6.20    -15.95
370  2024-09-27 06:10:01  10.39     5.22    -15.95
371  2024-09-27 06:10:58  10.18     6.15    -15.95
372  2024-09-27 06:12:00   9.98     5.07    -15.95
373  2024-09-27 06:13:01   9.78     5.54    -15.95
374  2024-09-27 06:13:58   9.59     5.91    -15.95
375  2024-09-27 06:15:00   9.41     5.19    -15.95
376  2024-09-27 06:16:01   9.23     5.66    -15.95
377  2024-09-27 06:16:58   9.06     5.64    -15.95
378  2024-09-27 06:17:59   8.90     2.81    -15.95
379  2024-09-27 06:19:01   8.74     3.05    -15.95
380  2024-09-27 06:19:58   8.58     3.14    -15.95
381  2024-09-27 06:20:59   8.43     3.14    -15.95
382  2024-09-27 06:22:01   8.29     3.15    -15.95
383  2024-09-27 06:22:58   8.15     3.34    -15.95
384  2024-09-27 06:24:00   8.02     2.85    -15.95
385  2024-09-27 06:25:01   7.89     3.14    -15.95
386  2024-09-27 06:25:58   7.76     3.42    -15.95
387  2024-09-27 06:27:00   7.64     2.91    -15.95
388  2024-09-27 06:28:01   7.53     3.16    -15.95
389  2024-09-27 06:28:58   7.42     3.08    -15.95
390  2024-09-27 06:30:00   7.31     3.17    -15.95

In [ ]:
df

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  97.46     6.43    -15.95
1    2024-09-27 00:01:01  97.42     6.23    -15.95
2    2024-09-27 00:01:58  97.38     5.64    -15.95
3    2024-09-27 00:03:00  97.33     5.48    -15.95
4    2024-09-27 00:04:01  97.28     5.24    -15.95
5    2024-09-27 00:04:58  97.22     4.80    -15.95
6    2024-09-27 00:06:00  97.15     4.21    -15.95
7    2024-09-27 00:07:01  97.08     4.12    -15.95
8    2024-09-27 00:07:58  97.00     3.41    -15.95
9    2024-09-27 00:09:00  96.92     3.86    -15.95
10   2024-09-27 00:10:01  96.83     3.76    -15.95
11   2024-09-27 00:10:58  96.73     3.49    -15.95
12   2024-09-27 00:12:00  96.63     3.49    -15.95
13   2024-09-27 00:13:01  96.51     2.92    -15.95
14   2024-09-27 00:13:58  96.40     3.76    -15.95
15   2024-09-27 00:15:00  96.27     2.81    -15.95
16   2024-09-27 00:16:01  96.14     4.68    -15.95
17   2024-09-27 00:16:58  96.00     5.15    -15.95
18   2024-09-27 00:18:00  95.86     5.21    -15.95
19   2024-09-27 00:19:01  95.71     5.13    -15.95
20   2024-09-27 00:19:58  95.56     4.67    -15.95
21   2024-09-27 00:21:00  95.41     5.17    -15.95
22   2024-09-27 00:22:01    NaN      NaN    -15.95
23   2024-09-27 00:22:58    NaN      NaN    -15.95
24   2024-09-27 00:24:00  95.24     5.20    -15.95
25   2024-09-27 00:25:01  95.08     5.59    -15.95
26   2024-09-27 00:25:58  94.91     5.45    -15.95
27   2024-09-27 00:27:00  94.74     5.50    -15.95
28   2024-09-27 00:28:01  94.57     5.18    -15.95
29   2024-09-27 00:28:58  94.40     5.44    -15.95
30   2024-09-27 00:30:00  94.23     5.00    -15.95
31   2024-09-27 00:31:01  94.06     5.52    -15.95
32   2024-09-27 00:31:58  93.89     6.18    -15.95
33   2024-09-27 00:33:00  93.72     6.03    -15.95
34   2024-09-27 00:34:01  93.56     5.90    -15.95
35   2024-09-27 00:34:58  93.40     5.08    -15.95
36   2024-09-27 00:36:00  93.24     6.96    -15.95
37   2024-09-27 00:37:01  93.09     5.91    -15.95
38   2024-09-27 00:37:58  92.95     5.74    -15.95
39   2024-09-27 00:39:00  92.81     6.54    -15.95
40   2024-09-27 00:40:01  92.68     7.05    -15.95
41   2024-09-27 00:40:58  92.56     7.21    -15.95
42   2024-09-27 00:42:00  92.45     7.87    -15.95
43   2024-09-27 00:43:01  92.35     7.76    -15.95
44   2024-09-27 00:43:58  92.26     8.23    -15.95
45   2024-09-27 00:45:00  92.18     8.38    -15.95
46   2024-09-27 00:46:01  92.10     7.89    -15.95
47   2024-09-27 00:46:58  92.04     8.15    -15.95
48   2024-09-27 00:48:00  92.00     8.51    -15.95
49   2024-09-27 00:49:01  91.96     7.83    -15.95
50   2024-09-27 00:49:58  91.93     8.91    -15.95
51   2024-09-27 00:51:00  91.92     8.60    -15.95
52   2024-09-27 00:52:01  91.92     8.39    -15.95
53   2024-09-27 00:52:58  91.92     8.64    -15.95
54   2024-09-27 00:54:00  91.94     8.57    -15.95
55   2024-09-27 00:55:01  91.98     8.57    -15.95
56   2024-09-27 00:55:58  92.02     8.17    -15.95
57   2024-09-27 00:57:00  92.07     7.74    -15.95
58   2024-09-27 00:58:01  92.13     8.16    -15.95
59   2024-09-27 00:58:58  92.20     8.15    -15.95
60   2024-09-27 01:00:00  92.28     7.67    -15.95
61   2024-09-27 01:01:01  92.37     7.94    -15.95
62   2024-09-27 01:01:58  92.46     6.82    -15.95
63   2024-09-27 01:03:00  92.56     8.15    -15.95
64   2024-09-27 01:04:01  92.67     9.11    -15.95
65   2024-09-27 01:04:58  92.78     8.19    -15.95
66   2024-09-27 01:06:00  92.90     8.57    -15.95
67   2024-09-27 01:07:01  93.01     8.81    -15.95
68   2024-09-27 01:07:58  93.13     9.73    -15.95
69   2024-09-27 01:08:59  93.26    10.57    -15.95
70   2024-09-27 01:10:01  93.38     9.55    -15.95
71   2024-09-27 01:10:58  93.49    10.81    -15.95
72   2024-09-27 01:11:59  93.61    10.93    -15.95
73   2024-09-27 01:13:01  93.73     8.49    -15.95
74   2024-09-27 01:13:58  93.84     9.83    -15.95
75   2024-09-27 01:15:00  93.94    11.78    -15.95
76   2024-09-27 01:16:01  94.04     7.01    -15.95
77   2024-09-27 01:16:58  94.13     5.70    -15.95
78   2024-09-27 01:18:00  94.22     7.07    -15.95
79   2024-09-27 01:19:01  94.29     6.71    -15.95
80   2024-09-27 01:19:58  94.36     6.29    -15.95
81   2024-09-27 01:21:00  94.42     7.98    -15.95
82   2024-09-27 01:22:01  94.46     7.00    -15.95
83   2024-09-27 01:22:58  94.50     8.29    -15.95
84   2024-09-27 01:23:59  94.52     8.31    -15.95
85   2024-09-27 01:25:01  94.53     7.46    -15.95
86   2024-09-27 01:25:58  94.53     8.50    -15.95
87   2024-09-27 01:26:59  94.51     8.89    -15.95
88   2024-09-27 01:28:01  94.49     7.66    -15.95
89   2024-09-27 01:28:58  94.45     8.20    -15.95
90   2024-09-27 01:30:00  94.39     8.67    -15.95
91   2024-09-27 01:31:01  94.32     9.79    -15.95
92   2024-09-27 01:31:58  94.24     9.33    -15.95
93   2024-09-27 01:33:00  94.15    10.39    -15.95
94   2024-09-27 01:34:01  94.04     7.23    -15.95
95   2024-09-27 01:34:58  93.93     5.96    -15.95
96   2024-09-27 01:36:00  93.79     5.34    -15.95
97   2024-09-27 01:37:01  93.65     5.86    -15.95
98   2024-09-27 01:37:58  93.50     5.36    -15.95
99   2024-09-27 01:38:59  93.33     5.68    -15.95
100  2024-09-27 01:40:01  93.16     5.15    -15.95
101  2024-09-27 01:40:58  92.97     5.46    -15.95
102  2024-09-27 01:42:00  92.78     5.11    -15.95
103  2024-09-27 01:43:01  92.58     5.00    -15.95
104  2024-09-27 01:43:58  92.37     4.59    -15.95
105  2024-09-27 01:45:00  92.15     5.19    -15.95
106  2024-09-27 01:46:01  91.93     5.22    -15.95
107  2024-09-27 01:46:58  91.70     5.59    -15.95
108  2024-09-27 01:48:00  91.47     6.42    -15.95
109  2024-09-27 01:49:01  91.24     5.77    -15.95
110  2024-09-27 01:49:58  91.00     6.91    -15.95
111  2024-09-27 01:51:00  90.76     7.03    -15.95
112  2024-09-27 01:52:01  90.52     7.32    -15.95
113  2024-09-27 01:52:58  90.28     7.45    -15.95
114  2024-09-27 01:53:59  90.04     8.13    -15.95
115  2024-09-27 01:55:01  89.80     8.11    -15.95
116  2024-09-27 01:55:58  89.57     8.54    -15.95
117  2024-09-27 01:57:00  89.33     7.48    -15.95
118  2024-09-27 01:58:01  89.10    12.41    -15.95
119  2024-09-27 01:58:58  88.87    12.78    -15.95
120  2024-09-27 02:00:00  88.64    13.41    -15.95
121  2024-09-27 02:01:01  88.42    13.56    -15.95
122  2024-09-27 02:01:58  88.19    14.23    -15.95
123  2024-09-27 02:02:59  87.98    12.58    -15.95
124  2024-09-27 02:04:01  87.77    13.72    -15.95
125  2024-09-27 02:04:58  87.56    14.92    -15.95
126  2024-09-27 02:06:00  87.35    14.77    -15.95
127  2024-09-27 02:07:01  87.15    14.67    -15.95
128  2024-09-27 02:07:58  86.95    15.62    -15.95
129  2024-09-27 02:08:59  86.76    14.84    -15.95
130  2024-09-27 02:10:01  86.56    14.56    -15.95
131  2024-09-27 02:10:58  86.38    15.46    -15.95
132  2024-09-27 02:12:00  86.19    15.80    -15.95
133  2024-09-27 02:13:01  86.00    15.00    -15.95
134  2024-09-27 02:13:58  85.82    15.02    -15.95
135  2024-09-27 02:15:00  85.63    14.94    -15.95
136  2024-09-27 02:16:01  85.45    15.11    -15.95
137  2024-09-27 02:16:58  85.27    14.27    -15.95
138  2024-09-27 02:17:59  85.08    15.19    -15.95
139  2024-09-27 02:19:01  84.90    14.52    -15.95
140  2024-09-27 02:19:58  84.71    15.50    -15.95
141  2024-09-27 02:21:00  84.53    17.19    -15.95
142  2024-09-27 02:22:01  84.33    13.70    -15.95
143  2024-09-27 02:22:58  84.14    14.61    -15.95
144  2024-09-27 02:23:59  83.94    12.85    -15.95
145  2024-09-27 02:25:01  83.74    13.64    -15.95
146  2024-09-27 02:25:58  83.53    14.65    -15.95
147  2024-09-27 02:27:00  83.32    13.35    -15.95
148  2024-09-27 02:28:01  83.11    13.25    -15.95
149  2024-09-27 02:28:58  82.89    13.03    -15.95
150  2024-09-27 02:30:00  82.66    13.43    -15.95
151  2024-09-27 02:31:01  82.43    12.14    -15.95
152  2024-09-27 02:31:58  82.19    12.41    -15.95
153  2024-09-27 02:32:59  81.95    11.36    -15.95
154  2024-09-27 02:34:01  81.70    11.75    -15.95
155  2024-09-27 02:34:58  81.44    10.64    -15.95
156  2024-09-27 02:36:00  81.18    11.46    -15.95
157  2024-09-27 02:37:01  80.90    10.38    -15.95
158  2024-09-27 02:37:58  80.62     9.74    -15.95
159  2024-09-27 02:38:59  80.34    10.49    -15.95
160  2024-09-27 02:40:01  80.05    10.26    -15.95
161  2024-09-27 02:40:58  79.75     9.24    -15.95
162  2024-09-27 02:42:00  79.44    10.25    -15.95
163  2024-09-27 02:43:01  79.13     9.63    -15.95
164  2024-09-27 02:43:58  78.81    10.27    -15.95
165  2024-09-27 02:45:00  78.48    10.21    -15.95
166  2024-09-27 02:46:01  78.15    10.32    -15.95
167  2024-09-27 02:46:58  77.81     9.41    -15.95
168  2024-09-27 02:47:59  77.47     9.78    -15.95
169  2024-09-27 02:49:01  77.12    10.12    -15.95
170  2024-09-27 02:49:58  76.77     9.00    -15.95
171  2024-09-27 02:51:00  76.41    10.00    -15.95
172  2024-09-27 02:52:01  76.05     8.97    -15.95
173  2024-09-27 02:52:58  75.68     9.33    -15.95
174  2024-09-27 02:53:59  75.31    10.17    -15.95
175  2024-09-27 02:55:01  74.94     9.16    -15.95
176  2024-09-27 02:55:58  74.57     9.10    -15.95
177  2024-09-27 02:57:00  74.20     8.56    -15.95
178  2024-09-27 02:58:01  73.83    10.38    -15.95
179  2024-09-27 02:58:58  73.46     9.03    -15.95
180  2024-09-27 03:00:00  73.09     9.28    -15.95
181  2024-09-27 03:01:01  72.72    10.24    -15.95
182  2024-09-27 03:01:58  72.35     8.98    -15.95
183  2024-09-27 03:02:59  71.99     9.52    -15.95
184  2024-09-27 03:04:01  71.64     9.86    -15.95
185  2024-09-27 03:04:58  71.28     9.40    -15.95
186  2024-09-27 03:06:00  70.94     8.92    -15.95
187  2024-09-27 03:07:01  70.60    10.33    -15.95
188  2024-09-27 03:07:58  70.27     7.99    -15.95
189  2024-09-27 03:08:59  69.95     7.79    -15.95
190  2024-09-27 03:10:01  69.64     7.98    -15.95
191  2024-09-27 03:10:58  69.34     8.34    -15.95
192  2024-09-27 03:12:00  69.05     8.23    -15.95
193  2024-09-27 03:13:01  68.77     8.56    -15.95
194  2024-09-27 03:13:58  68.50     8.48    -15.95
195  2024-09-27 03:15:00  68.25     8.13    -15.95
196  2024-09-27 03:16:01  68.01     8.41    -15.95
197  2024-09-27 03:16:58  67.79     8.97    -15.95
198  2024-09-27 03:17:59  67.58     8.76    -15.95
199  2024-09-27 03:19:01  67.38     8.62    -15.95
200  2024-09-27 03:19:58  67.20     8.81    -15.95
201  2024-09-27 03:21:00  67.04     9.02    -15.95
202  2024-09-27 03:22:01  66.89     9.16    -15.95
203  2024-09-27 03:22:58  66.75     8.36    -15.95
204  2024-09-27 03:23:59  66.63     8.99    -15.95
205  2024-09-27 03:25:01  66.53     9.35    -15.95
206  2024-09-27 03:25:58  66.44     8.42    -15.95
207  2024-09-27 03:27:00  66.36     9.17    -15.95
208  2024-09-27 03:28:01  66.30     9.29    -15.95
209  2024-09-27 03:28:58  66.25     9.07    -15.95
210  2024-09-27 03:30:00  66.21     8.64    -15.95
211  2024-09-27 03:31:01  66.18     8.88    -15.95
212  2024-09-27 03:31:58  66.17    10.50    -15.95
213  2024-09-27 03:32:59  66.16    11.10    -15.95
214  2024-09-27 03:34:01  66.16    10.03    -15.95
215  2024-09-27 03:34:58  66.18    10.28    -15.95
216  2024-09-27 03:36:00  66.19    10.14    -15.95
217  2024-09-27 03:37:01  66.22    10.86    -15.95
218  2024-09-27 03:37:58  66.24    10.90    -15.95
219  2024-09-27 03:38:59  66.27    11.06    -15.95
220  2024-09-27 03:40:01  66.31    10.72    -15.95
221  2024-09-27 03:40:58  66.34    11.40    -15.95
222  2024-09-27 03:42:00  66.38    11.40    -15.95
223  2024-09-27 03:43:01  66.41    11.33    -15.95
224  2024-09-27 03:43:58  66.45    11.52    -15.95
225  2024-09-27 03:45:00  66.47    12.40    -15.95
226  2024-09-27 03:46:01  66.50    12.35    -15.95
227  2024-09-27 03:46:58  66.52    11.81    -15.95
228  2024-09-27 03:47:59  66.54    11.95    -15.95
229  2024-09-27 03:49:01  66.55    11.83    -15.95
230  2024-09-27 03:49:58  66.55    11.71    -15.95
231  2024-09-27 03:51:00  66.54    11.71    -15.95
232  2024-09-27 03:52:01  66.53    11.44    -15.95
233  2024-09-27 03:52:58  66.51    11.74    -15.95
234  2024-09-27 03:53:59  66.47    10.77    -15.95
235  2024-09-27 03:55:01  66.43    11.20    -15.95
236  2024-09-27 03:55:58  66.38    10.81    -15.95
237  2024-09-27 03:57:00  66.32    11.00    -15.95
238  2024-09-27 03:58:01  66.24    11.55    -15.95
239  2024-09-27 03:58:58  66.16    10.14    -15.95
240  2024-09-27 04:00:00  66.06    10.30    -15.95
241  2024-09-27 04:01:01  65.95    10.47    -15.95
242  2024-09-27 04:01:58  65.83    10.93    -15.95
243  2024-09-27 04:02:59  65.70     9.84    -15.95
244  2024-09-27 04:04:01  65.56    11.22    -15.95
245  2024-09-27 04:04:58  65.40    10.87    -15.95
246  2024-09-27 04:05:59  65.23    11.70    -15.95
247  2024-09-27 04:07:01  65.05    10.01    -15.95
248  2024-09-27 04:07:58  64.86    11.43    -15.95
249  2024-09-27 04:09:00  64.66     9.94    -15.95
250  2024-09-27 04:10:01  64.45    10.79    -15.95
251  2024-09-27 04:10:58  64.22     9.48    -15.95
252  2024-09-27 04:12:00  63.99    10.19    -15.95
253  2024-09-27 04:13:01  63.74    10.77    -15.95
254  2024-09-27 04:13:58  63.48     9.10    -15.95
255  2024-09-27 04:15:00  63.21     9.98    -15.95
256  2024-09-27 04:16:01  62.93     9.51    -15.95
257  2024-09-27 04:16:58  62.64    10.32    -15.95
258  2024-09-27 04:17:59  62.34     8.66    -15.95
259  2024-09-27 04:19:01  62.03     9.34    -15.95
260  2024-09-27 04:19:58  61.70     9.87    -15.95
261  2024-09-27 04:20:59  61.37     9.03    -15.95
262  2024-09-27 04:22:01  61.03     8.86    -15.95
263  2024-09-27 04:22:58  60.68     7.90    -15.95
264  2024-09-27 04:24:00  60.31     9.20    -15.95
265  2024-09-27 04:25:01  59.94     7.63    -15.95
266  2024-09-27 04:25:58  59.56     8.49    -15.95
267  2024-09-27 04:27:00  59.17     8.12    -15.95
268  2024-09-27 04:28:01  58.77     7.99    -15.95
269  2024-09-27 04:28:58  58.36     8.12    -15.95
270  2024-09-27 04:30:00  57.94     7.91    -15.95
271  2024-09-27 04:31:01  57.51     7.68    -15.95
272  2024-09-27 04:31:58  57.07     8.32    -15.95
273  2024-09-27 04:32:59  56.63     6.90    -15.95
274  2024-09-27 04:34:01  56.17     7.54    -15.95
275  2024-09-27 04:34:58  55.71     8.07    -15.95
276  2024-09-27 04:35:59  55.24     6.66    -15.95
277  2024-09-27 04:37:01  54.76     7.28    -15.95
278  2024-09-27 04:37:58  54.27     7.34    -15.95
279  2024-09-27 04:39:00  53.78     7.18    -15.95
280  2024-09-27 04:40:01  53.28     7.09    -15.95
281  2024-09-27 04:40:58  52.77     6.95    -15.95
282  2024-09-27 04:42:00  52.25     7.11    -15.95
283  2024-09-27 04:43:01  51.73     7.28    -15.95
284  2024-09-27 04:43:58  51.20     6.15    -15.95
285  2024-09-27 04:45:00  50.66     6.86    -15.95
286  2024-09-27 04:46:01  50.11     6.66    -15.95
287  2024-09-27 04:46:58  49.56     6.62    -15.95
288  2024-09-27 04:47:59  49.01     6.46    -15.95
289  2024-09-27 04:49:01  48.45     6.70    -15.95
290  2024-09-27 04:49:58  47.88     6.57    -15.95
291  2024-09-27 04:50:59  47.31     6.94    -15.95
292  2024-09-27 04:52:01  46.73     6.02    -15.95
293  2024-09-27 04:52:58  46.15     6.51    -15.95
294  2024-09-27 04:54:00  45.56     6.33    -15.95
295  2024-09-27 04:55:01  44.97     6.92    -15.95
296  2024-09-27 04:55:58  44.38     5.75    -15.95
297  2024-09-27 04:57:00  43.78     6.30    -15.95
298  2024-09-27 04:58:01  43.18     6.24    -15.95
299  2024-09-27 04:58:58  42.58     6.13    -15.95
300  2024-09-27 05:00:00  41.98     6.45    -15.95
301  2024-09-27 05:01:01  41.37     5.70    -15.95
302  2024-09-27 05:01:58  40.76     6.00    -15.95
303  2024-09-27 05:02:59  40.15     5.49    -15.95
304  2024-09-27 05:04:01  39.54     5.54    -15.95
305  2024-09-27 05:04:58  38.92     5.58    -15.95
306  2024-09-27 05:05:59  38.31     5.10    -15.95
307  2024-09-27 05:07:01  37.70     5.40    -15.95
308  2024-09-27 05:07:58  37.09     5.25    -15.95
309  2024-09-27 05:09:00  36.47     5.17    -15.95
310  2024-09-27 05:10:01  35.86     5.15    -15.95
311  2024-09-27 05:10:58  35.25     5.09    -15.95
312  2024-09-27 05:12:00  34.65     4.90    -15.95
313  2024-09-27 05:13:01  34.04     4.96    -15.95
314  2024-09-27 05:13:58  33.44     4.97    -15.95
315  2024-09-27 05:15:00  32.84     4.56    -15.95
316  2024-09-27 05:16:01  32.25     4.89    -15.95
317  2024-09-27 05:16:58  31.66     4.40    -15.95
318  2024-09-27 05:17:59  31.07     4.37    -15.95
319  2024-09-27 05:19:01  30.49     4.35    -15.95
320  2024-09-27 05:19:58  29.92     4.33    -15.95
321  2024-09-27 05:20:59  29.35     4.34    -15.95
322  2024-09-27 05:22:01  28.78     4.31    -15.95
323  2024-09-27 05:22:58  28.23     4.18    -15.95
324  2024-09-27 05:24:00  27.67     4.32    -15.95
325  2024-09-27 05:25:01  27.13     4.52    -15.95
326  2024-09-27 05:25:58  26.59     4.23    -15.95
327  2024-09-27 05:27:00  26.06     4.33    -15.95
328  2024-09-27 05:28:01  25.54     4.13    -15.95
329  2024-09-27 05:28:58  25.02     4.53    -15.95
330  2024-09-27 05:30:00  24.51     4.15    -15.95
331  2024-09-27 05:31:01  24.01     4.39    -15.95
332  2024-09-27 05:31:58  23.52     4.38    -15.95
333  2024-09-27 05:32:59  23.04     4.65    -15.95
334  2024-09-27 05:34:01  22.56     4.11    -15.95
335  2024-09-27 05:34:58  22.09     4.66    -15.95
336  2024-09-27 05:35:59  21.63     4.23    -15.95
337  2024-09-27 05:37:01  21.17     4.69    -15.95
338  2024-09-27 05:37:58  20.73     4.53    -15.95
339  2024-09-27 05:39:00  20.29     4.33    -15.95
340  2024-09-27 05:40:01  19.86     4.57    -15.95
341  2024-09-27 05:40:58  19.44     4.61    -15.95
342  2024-09-27 05:42:00  19.03     4.98    -15.95
343  2024-09-27 05:43:01  18.62     4.68    -15.95
344  2024-09-27 05:43:58  18.22     4.47    -15.95
345  2024-09-27 05:45:00  17.83     4.65    -15.95
346  2024-09-27 05:46:01  17.45     4.92    -15.95
347  2024-09-27 05:46:58  17.07     5.33    -15.95
348  2024-09-27 05:47:59  16.70     4.54    -15.95
349  2024-09-27 05:49:01  16.34     5.47    -15.95
350  2024-09-27 05:49:58  15.99     5.12    -15.95
351  2024-09-27 05:50:59  15.64     4.68    -15.95
352  2024-09-27 05:52:01  15.30     5.37    -15.95
353  2024-09-27 05:52:58  14.97     5.13    -15.95
354  2024-09-27 05:54:00  14.64     5.70    -15.95
355  2024-09-27 05:55:01  14.33     5.32    -15.95
356  2024-09-27 05:55:58  14.02     5.34    -15.95
357  2024-09-27 05:57:00  13.71     5.36    -15.95
358  2024-09-27 05:58:01  13.41     4.86    -15.95
359  2024-09-27 05:58:58  13.13     5.86    -15.95
360  2024-09-27 06:00:00  12.84     5.45    -15.95
361  2024-09-27 06:01:01  12.57     4.94    -15.95
362  2024-09-27 06:01:58  12.30     5.54    -15.95
363  2024-09-27 06:02:59  12.04     5.99    -15.95
364  2024-09-27 06:04:01  11.78     5.58    -15.95
365  2024-09-27 06:04:58  11.53     5.03    -15.95
366  2024-09-27 06:05:59  11.29     6.14    -15.95
367  2024-09-27 06:07:01  11.05     5.12    -15.95
368  2024-09-27 06:07:58  10.83     5.72    -15.95
369  2024-09-27 06:09:00  10.60     6.20    -15.95
370  2024-09-27 06:10:01  10.39     5.22    -15.95
371  2024-09-27 06:10:58  10.18     6.15    -15.95
372  2024-09-27 06:12:00   9.98     5.07    -15.95
373  2024-09-27 06:13:01   9.78     5.54    -15.95
374  2024-09-27 06:13:58   9.59     5.91    -15.95
375  2024-09-27 06:15:00   9.41     5.19    -15.95
376  2024-09-27 06:16:01   9.23     5.66    -15.95
377  2024-09-27 06:16:58   9.06     5.64    -15.95
378  2024-09-27 06:17:59   8.90     2.81    -15.95
379  2024-09-27 06:19:01   8.74     3.05    -15.95
380  2024-09-27 06:19:58   8.58     3.14    -15.95
381  2024-09-27 06:20:59   8.43     3.14    -15.95
382  2024-09-27 06:22:01   8.29     3.15    -15.95
383  2024-09-27 06:22:58   8.15     3.34    -15.95
384  2024-09-27 06:24:00   8.02     2.85    -15.95
385  2024-09-27 06:25:01   7.89     3.14    -15.95
386  2024-09-27 06:25:58   7.76     3.42    -15.95
387  2024-09-27 06:27:00   7.64     2.91    -15.95
388  2024-09-27 06:28:01   7.53     3.16    -15.95
389  2024-09-27 06:28:58   7.42     3.08    -15.95
390  2024-09-27 06:30:00   7.31     3.17    -15.95

In [ ]:
import pandas as pd
from datetime import time
import numpy as np

df['DATETIME'] = pd.to_datetime(df['DATETIME'])

target_times = [
    time(0, 50),
    time(1, 0),
    time(1, 10)
]

def find_closest_time(df, target_time):

    df_times = df['DATETIME'].dt.time


    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second


    df_seconds = (df['DATETIME'].dt.hour * 3600 +
                  df['DATETIME'].dt.minute * 60 +
                  df['DATETIME'].dt.second)


    time_diff = np.abs(df_seconds - target_seconds)


    closest_idx = time_diff.idxmin()

    return df.loc[[closest_idx]]

df_filtered_list = []
for target_time in target_times:
    closest_row = find_closest_time(df, target_time)
    df_filtered_list.append(closest_row)

df_filtered = pd.concat(df_filtered_list, ignore_index=True)

df_filtered = df_filtered.sort_values('DATETIME').reset_index(drop=True)

print("DataFrame filtered for closest times to 00:50, 01:00 and 01:10:")
print(df_filtered)

print("\nDifference from target times:")
for i, target_time in enumerate(target_times):
    actual_time = df_filtered.iloc[i]['DATETIME'].time()
    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second
    actual_seconds = actual_time.hour * 3600 + actual_time.minute * 60 + actual_time.second
    diff_seconds = abs(actual_seconds - target_seconds)
    print(f"Target: {target_time} | Actual: {actual_time} | Difference: {diff_seconds} seconds")

DataFrame filtered for closest times to 00:50, 01:00 and 01:10:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-09-27 00:49:58  91.93     8.91    -15.95
1 2024-09-27 01:00:00  92.28     7.67    -15.95
2 2024-09-27 01:10:01  93.38     9.55    -15.95

Difference from target times:
Target: 00:50:00 | Actual: 00:49:58 | Difference: 2 seconds
Target: 01:00:00 | Actual: 01:00:00 | Difference: 0 seconds
Target: 01:10:00 | Actual: 01:10:01 | Difference: 1 seconds

In [ ]:
reference_time = pd.Timestamp('2024-09-27 00:50:00')
wide_window = timedelta(minutes=5)
df_proximos = df[(df['DATETIME'] >= reference_time - wide_window) &
                 (df['DATETIME'] <= reference_time + wide_window)]
print("Records close to 00:50:")
print(df_proximos[['DATETIME', 'TEC']])

Records close to 00:50:
              DATETIME    TEC
45 2024-09-27 00:45:00  92.18
46 2024-09-27 00:46:01  92.10
47 2024-09-27 00:46:58  92.04
48 2024-09-27 00:48:00  92.00
49 2024-09-27 00:49:01  91.96
50 2024-09-27 00:49:58  91.93
51 2024-09-27 00:51:00  91.92
52 2024-09-27 00:52:01  91.92
53 2024-09-27 00:52:58  91.92
54 2024-09-27 00:54:00  91.94

In [ ]:
print(df.iloc[[50, 60, 70]][['DATETIME', 'TEC']])

              DATETIME    TEC
50 2024-09-27 00:49:58  91.93
60 2024-09-27 01:00:00  92.28
70 2024-09-27 01:10:01  93.38

In [ ]:
df.to_pickle('braz271-2024-09-27_selected_0050_to_0110.pkl')

# TEC maps analysis

In [ ]:
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

## EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
embrace_tec = Embrace()
embrace_points = embrace_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)

In [ ]:
embrace_points

[(-16, -50.0, 22, 16),
 (-16, -47.5, 22, 17),
 (-14, -50.0, 23, 16),
 (-14, -47.5, 23, 17)]

In [ ]:
date = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{date} {time}' for time in times]

result = df_embrace_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(3, 41, 25)

### 00:50

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  79.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  72.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  68.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  50.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  79.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  72.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  68.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  50.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 79.0 + 0.826561* 72.0 + 0.003969* 68.0 + 0.022291* 50.0
   Value =  11.6271 +  59.5124 +   0.2699 +   1.1145
   Value = 72.523977

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 72.5240
============================================================

### 01:00

In [ ]:
embrace_tec.tec_map = np_embrace_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  78.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  71.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  63.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  65.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  78.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  71.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  63.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  65.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 78.0 + 0.826561* 71.0 + 0.003969* 63.0 + 0.022291* 65.0
   Value =  11.4800 +  58.6858 +   0.2501 +   1.4489
   Value = 71.864754

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 71.8648
============================================================

### 01:10

In [ ]:
embrace_tec.tec_map = np_embrace_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -50.0°) - Indexes: [22, 16] - TEC:  84.0
   P2: ( -16.0°,  -47.5°) - Indexes: [22, 17] - TEC:  65.0
   P3: ( -14.0°,  -50.0°) - Indexes: [23, 16] - TEC:  77.0
   P4: ( -14.0°,  -47.5°) - Indexes: [23, 17] - TEC:  61.0

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -50.0° to  -47.5° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -50.0°) =  84.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) =  65.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -50.0°) =  77.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -47.5°) =  61.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -50.0)) / ( -47.5 - ( -50.0))
   t_x = 2.12213 /  2.5 = 0.848852

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.05252 /  2.0 = 0.026260

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.848852) * (1 - 0.026260) = 0.147179
   w_01 = t_x * (1 - t_y)       = 0.848852 * (1 - 0.026260)       = 0.826561
   w_10 = (1 - t_x) * t_y       = (1 - 0.848852) * 0.026260       = 0.003969
   w_11 = t_x * t_y             = 0.848852 * 0.026260             = 0.022291
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.147179* 84.0 + 0.826561* 65.0 + 0.003969* 77.0 + 0.022291* 61.0
   Value =  12.3630 +  53.7265 +   0.3056 +   1.3597
   Value = 67.754865

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 84.89% of the way from -50.0° to -47.5°
   In Y direction (latitude):  2.63% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 67.7549
============================================================

## MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024['DATETIME'] = pd.to_datetime(df_maggia_maps_2024['DATETIME'])
df_maggia_maps_2024 = df_maggia_maps_2024.set_index('DATETIME')

In [ ]:
df_maggia_maps_2024.columns

Index(['TECMAP'], dtype='object')

In [ ]:
class Maggia(TecMap):

    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
maggia_tec = Maggia()
maggia_points = maggia_tec.find_nearest_points(lat=-15.94748, lon=-47.87787)

In [ ]:
maggia_points

[(-16.0, -48.0, 128, 124),
 (-16.0, -47.5, 128, 125),
 (-15.5, -48.0, 129, 124),
 (-15.5, -47.5, 129, 125)]

In [ ]:
date = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{date} {time}' for time in times]

result = df_maggia_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.62400055, 48.20500183, 47.78499985, ..., 19.22900009,
         18.24799919, 16.43799973],
        [48.70800018, 48.36100006, 48.0019989 , ..., 18.61000061,
         17.57699966, 16.23500061],
        [48.7120018 , 48.42399979, 48.11700058, ..., 17.99799919,
         16.95499992, 16.04000092]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [43.38299942, 43.10300064, 43.09799957, ..., 19.18000031,
         18.25300026, 17.1609993 ],
        [43.85400009, 43.58499908, 43.34700012, ..., 18.40399933,
         17.62000084, 16.44000053],
        [44.19599915, 43.94599915, 43.70500183, ..., 17.70899963,
         16.94099998, 15.69099998]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.6230011 , 41.29999924, 41.13800049, ..., 18.74399948,
         18.67399979, 18.62999916],
        [42.11100006, 41.79499817, 41.5340004 , ..., 18.92099953,
         18.80699921, 17.86199951],
        [42.46699905, 42.18199921, 41.9280014 , ..., 18.2670002 ,
         17.5340004 , 16.79299927]]])

In [ ]:
np_maggia_maps.shape

(3, 241, 221)

### 00:50

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC: 138.9
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC: 138.1
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC: 138.9
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC: 138.7

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) = 138.9
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) = 138.1
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) = 138.9
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) = 138.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357*138.9 + 0.218603*138.1 + 0.079383*138.9 + 0.025657*138.7
   Value =  93.9710 +  30.1878 +  11.0292 +   3.5574
   Value = 138.745376

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 138.7454
============================================================

### 01:00

In [ ]:
maggia_tec.tec_map = np_maggia_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC: 133.0
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC: 133.0
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC: 133.9
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC: 133.1

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) = 133.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) = 133.0
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) = 133.9
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) = 133.1

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357*133.0 + 0.218603*133.0 + 0.079383*133.9 + 0.025657*133.1
   Value =  89.9338 +  29.0672 +  10.6276 +   3.4145
   Value = 133.043217

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 133.0432
============================================================

### 01:10

In [ ]:
maggia_tec.tec_map = np_maggia_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.94748
target_lon = -47.87787

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -48.0°) - Indexes: [128, 124] - TEC: 129.0
   P2: ( -16.0°,  -47.5°) - Indexes: [128, 125] - TEC: 129.0
   P3: ( -15.5°,  -48.0°) - Indexes: [129, 124] - TEC: 130.2
   P4: ( -15.5°,  -47.5°) - Indexes: [129, 125] - TEC: 129.7

2. TARGET POINT: (-15.94748°, -47.87787°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -48.0° to  -47.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -48.0°) = 129.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -47.5°) = 129.0
   f_10 (lat_max, lon_min) = ( -15.5°,  -48.0°) = 130.2
   f_11 (lat_max, lon_max) = ( -15.5°,  -47.5°) = 129.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-47.87787 - ( -48.0)) / ( -47.5 - ( -48.0))
   t_x = 0.12213 /  0.5 = 0.244260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.94748 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.05252 /  0.5 = 0.105040

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.244260) * (1 - 0.105040) = 0.676357
   w_01 = t_x * (1 - t_y)       = 0.244260 * (1 - 0.105040)       = 0.218603
   w_10 = (1 - t_x) * t_y       = (1 - 0.244260) * 0.105040       = 0.079383
   w_11 = t_x * t_y             = 0.244260 * 0.105040             = 0.025657
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.676357*129.0 + 0.218603*129.0 + 0.079383*130.2 + 0.025657*129.7
   Value =  87.2514 +  28.2002 +  10.3332 +   3.3286
   Value = 129.113420

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 24.43% of the way from -48.0° to -47.5°
   In Y direction (latitude):  10.50% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 129.1134
============================================================