# Gopi TEC SJC analysis - 09/27/2024

In [ ]:
#Download Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [ ]:
%pwd

'/content'

In [ ]:
!ls

Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip  sample_data

In [ ]:
!unzip 'Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_SJSP_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: missing_sjsp_2024.txt
  inflating: sjsp271-2024-09-27.Bias
  inflating: sjsp271-2024-09-27.Cmn
  inflating: sjsp271-2024-09-27.Std
  inflating: sjsp271-2024-09-27-wbias.png
  inflating: sjsp336-2024-12-01.Bias
  inflating: sjsp336-2024-12-01.Cmn
  inflating: sjsp336-2024-12-01.Std
  inflating: sjsp336-2024-12-01-wbias.png
  inflating: sjsp337-2024-12-02.Bias
  inflating: sjsp337-2024-12-02.Cmn
  inflating: sjsp337-2024-12-02.Std
  inflating: sjsp337-2024-12-02-wbias.png
  inflating: sjsp338-2024-12-03.Bias
  inflating: sjsp338-2024-12-03.Cmn
  inflating: sjsp338-2024-12-03.Std
  inflating: sjsp338-2024-12-03-wbias.png
  inflating: sjsp339-2024-12-04.Bias
  inflating: sjsp339-2024-12-04.Cmn
  inflating: sjsp339-2024-12-04.Std
  inflating: sjsp339-2024-12-04-wbias.png
  inflating: sjsp340-2024-12-05.Bias
  inflating: sjsp340-2024-12-05.Cmn
  inflating: sjsp340-2024-12-05.Std
  inflating: sjsp340-2024-12-05-wbias.png
  inflating: sjsp341-2024-12-06.Bias
  inflating: sjsp341-2024-12-06.Cmn
  inflating: sjsp341-2024-12-06.Std
  inflating: sjsp341-2024-12-06-wbias.png
  inflating: sjsp342-2024-12-07.Bias
  inflating: sjsp342-2024-12-07.Cmn
  inflating: sjsp342-2024-12-07.Std
  inflating: sjsp342-2024-12-07-wbias.png
  inflating: sjsp348-2024-12-13.Bias
  inflating: sjsp348-2024-12-13.Cmn
  inflating: sjsp348-2024-12-13.Std
  inflating: sjsp348-2024-12-13-wbias.png
  inflating: sjsp349-2024-12-14.Bias
  inflating: sjsp349-2024-12-14.Cmn
  inflating: sjsp349-2024-12-14.Std
  inflating: sjsp349-2024-12-14-wbias.png
  inflating: sjsp350-2024-12-15.Bias
  inflating: sjsp350-2024-12-15.Cmn
  inflating: sjsp350-2024-12-15.Std
  inflating: sjsp350-2024-12-15-wbias.png
  inflating: sjsp351-2024-12-16.Bias
  inflating: sjsp351-2024-12-16.Cmn
  inflating: sjsp351-2024-12-16.Std
  inflating: sjsp351-2024-12-16-wbias.png
  inflating: sjsp352-2024-12-17.Bias
  inflating: sjsp352-2024-12-17.Cmn
  inflating: sjsp352-2024-12-17.Std
  inflating: sjsp352-2024-12-17-wbias.png
  inflating: sjsp353-2024-12-18.Bias
  inflating: sjsp353-2024-12-18.Cmn
  inflating: sjsp353-2024-12-18.Std
  inflating: sjsp353-2024-12-18-wbias.png
  inflating: sjsp354-2024-12-19.Bias
  inflating: sjsp354-2024-12-19.Cmn
  inflating: sjsp354-2024-12-19.Std
  inflating: sjsp354-2024-12-19-wbias.png
  inflating: sjsp355-2024-12-20.Bias
  inflating: sjsp355-2024-12-20.Cmn
  inflating: sjsp355-2024-12-20.Std
  inflating: sjsp355-2024-12-20-wbias.png
  inflating: sjsp356-2024-12-21.Bias
  inflating: sjsp356-2024-12-21.Cmn
  inflating: sjsp356-2024-12-21.Std
  inflating: sjsp356-2024-12-21-wbias.png
  inflating: sjsp357-2024-12-22.Bias
  inflating: sjsp357-2024-12-22.Cmn
  inflating: sjsp357-2024-12-22.Std
  inflating: sjsp357-2024-12-22-wbias.png
  inflating: sjsp358-2024-12-23.Bias
  inflating: sjsp358-2024-12-23.Cmn
  inflating: sjsp358-2024-12-23.Std
  inflating: sjsp358-2024-12-23-wbias.png
  inflating: sjsp359-2024-12-24.Bias
  inflating: sjsp359-2024-12-24.Cmn
  inflating: sjsp359-2024-12-24.Std
  inflating: sjsp359-2024-12-24-wbias.png
  inflating: sjsp360-2024-12-25.Bias
  inflating: sjsp360-2024-12-25.Cmn
  inflating: sjsp360-2024-12-25.Std
  inflating: sjsp360-2024-12-25-wbias.png
  inflating: sjsp361-2024-12-26.Bias
  inflating: sjsp361-2024-12-26.Cmn
  inflating: sjsp361-2024-12-26.Std
  inflating: sjsp361-2024-12-26-wbias.png
  inflating: sjsp362-2024-12-27.Bias
  inflating: sjsp362-2024-12-27.Cmn
  inflating: sjsp362-2024-12-27.Std
  inflating: sjsp362-2024-12-27-wbias.png
  inflating: sjsp363-2024-12-28.Bias
  inflating: sjsp363-2024-12-28.Cmn
  inflating: sjsp363-2024-12-28.Std
  inflating: sjsp363-2024-12-28-wbias.png
  inflating: sjsp364-2024-12-29.Bias
  inflating: sjsp364-2024-12-29.Cmn
  inflating: sjsp364-2024-12-29.Std
  inflating: sjsp364-2024-12-29-wbias.png
  inflating: sjsp365-2024-12-30.Bias
  inflating: sjsp365-2024-12-30.Cmn
  inflating: sjsp365-2024-12-30.Std
  inflating: sjsp365-2024-12-30-wbias.png
  inflating: sjsp366-2024-12-31.Bias
  inflating: sjsp366-2024-12-31.Cmn
  inflating: sjsp366-2024-12-31.Std
  inflating: sjsp366-2024-12-31-wbias.png
  inflating: TEC_dec_2024.zip

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

pd.set_option('display.max_rows', None)

df = pd.read_csv('sjsp271-2024-09-27.Std', sep='\s+', header=None)

df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

base_date = datetime(2024, 9, 27)

def decimal_to_time(decimal_hours):
    hours = int(decimal_hours)
    minutes = int((decimal_hours - hours) * 60)
    seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
    return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

print(df)

df.to_pickle('sjsp271-2024-09-27.pkl')

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-1995604197.py:7: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('sjsp271-2024-09-27.Std', sep='\s+', header=None)

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  40.12    16.32    -23.21
1    2024-09-27 00:01:01  40.01    20.26    -23.21
2    2024-09-27 00:01:58  39.89    18.91    -23.21
3    2024-09-27 00:03:00  39.76    19.12    -23.21
4    2024-09-27 00:04:01  39.62    20.02    -23.21
5    2024-09-27 00:04:58  39.47    19.24    -23.21
6    2024-09-27 00:06:00  39.31    18.05    -23.21
7    2024-09-27 00:07:01  39.14    13.91    -23.21
8    2024-09-27 00:07:58  38.97    16.61    -23.21
9    2024-09-27 00:09:00  38.79    16.05    -23.21
10   2024-09-27 00:10:01  38.60    16.75    -23.21
11   2024-09-27 00:10:58  38.40    16.78    -23.21
12   2024-09-27 00:12:00  38.19    16.77    -23.21
13   2024-09-27 00:13:01  37.98    15.47    -23.21
14   2024-09-27 00:13:58  37.77    16.49    -23.21
15   2024-09-27 00:15:00  37.55    16.41    -23.21
16   2024-09-27 00:16:01  37.32    15.94    -23.21
17   2024-09-27 00:16:58  37.10    13.65    -23.21
18   2024-09-27 00:18:00  36.87    13.68    -23.21
19   2024-09-27 00:19:01  36.63    13.86    -23.21
20   2024-09-27 00:19:58  36.40    13.63    -23.21
21   2024-09-27 00:21:00  36.17    15.05    -23.21
22   2024-09-27 00:22:01  35.93    14.18    -23.21
23   2024-09-27 00:22:58  35.70    14.95    -23.21
24   2024-09-27 00:24:00  35.46    15.31    -23.21
25   2024-09-27 00:25:01  35.23    15.63    -23.21
26   2024-09-27 00:25:58  35.01    16.14    -23.21
27   2024-09-27 00:27:00  34.78    16.33    -23.21
28   2024-09-27 00:28:01  34.56    16.90    -23.21
29   2024-09-27 00:28:58  34.34    16.85    -23.21
30   2024-09-27 00:30:00  34.12    16.48    -23.21
31   2024-09-27 00:31:01  33.91    17.93    -23.21
32   2024-09-27 00:31:58  33.71    17.42    -23.21
33   2024-09-27 00:33:00  33.51    18.11    -23.21
34   2024-09-27 00:34:01  33.31    18.92    -23.21
35   2024-09-27 00:34:58  33.12    18.78    -23.21
36   2024-09-27 00:36:00  32.94    18.20    -23.21
37   2024-09-27 00:37:01  32.76    19.87    -23.21
38   2024-09-27 00:37:58  32.58    20.46    -23.21
39   2024-09-27 00:39:00  32.41    20.58    -23.21
40   2024-09-27 00:40:01  32.25    19.28    -23.21
41   2024-09-27 00:40:58  32.09    19.90    -23.21
42   2024-09-27 00:42:00  31.93    20.11    -23.21
43   2024-09-27 00:43:01  31.79    20.31    -23.21
44   2024-09-27 00:43:58  31.64    20.13    -23.21
45   2024-09-27 00:45:00  31.51    20.32    -23.21
46   2024-09-27 00:46:01  31.37    20.51    -23.21
47   2024-09-27 00:46:58  31.24    19.18    -23.21
48   2024-09-27 00:48:00  31.12    19.73    -23.21
49   2024-09-27 00:49:01  31.00    19.47    -23.21
50   2024-09-27 00:49:58  30.89    19.69    -23.21
51   2024-09-27 00:51:00  30.78    17.98    -23.21
52   2024-09-27 00:52:01  30.68    14.48    -23.21
53   2024-09-27 00:52:58  30.58    14.35    -23.21
54   2024-09-27 00:54:00  30.49    13.83    -23.21
55   2024-09-27 00:55:01  30.41    13.37    -23.21
56   2024-09-27 00:55:58  30.33    12.68    -23.21
57   2024-09-27 00:57:00  30.25    12.37    -23.21
58   2024-09-27 00:58:01  30.18    11.85    -23.21
59   2024-09-27 00:58:58  30.12    11.56    -23.21
60   2024-09-27 01:00:00  30.06    11.62    -23.21
61   2024-09-27 01:01:01  30.01    10.59    -23.21
62   2024-09-27 01:01:58  29.96     9.37    -23.21
63   2024-09-27 01:03:00  29.92    10.53    -23.21
64   2024-09-27 01:04:01  29.89     8.67    -23.21
65   2024-09-27 01:04:58  29.86     9.48    -23.21
66   2024-09-27 01:06:00  29.84     8.94    -23.21
67   2024-09-27 01:07:01  29.82     8.87    -23.21
68   2024-09-27 01:07:58  29.81     8.44    -23.21
69   2024-09-27 01:08:59  29.80     8.23    -23.21
70   2024-09-27 01:10:01  29.80     7.92    -23.21
71   2024-09-27 01:10:58  29.81     7.59    -23.21
72   2024-09-27 01:11:59  29.81     7.98    -23.21
73   2024-09-27 01:13:01  29.83     7.14    -23.21
74   2024-09-27 01:13:58  29.85     6.27    -23.21
75   2024-09-27 01:15:00  29.87    10.50    -23.21
76   2024-09-27 01:16:01  29.90    10.81    -23.21
77   2024-09-27 01:16:58  29.94    11.55    -23.21
78   2024-09-27 01:18:00  29.98    10.26    -23.21
79   2024-09-27 01:19:01  30.02    11.10    -23.21
80   2024-09-27 01:19:58  30.07    11.25    -23.21
81   2024-09-27 01:21:00  30.12    11.34    -23.21
82   2024-09-27 01:22:01  30.18    11.70    -23.21
83   2024-09-27 01:22:58  30.24    11.22    -23.21
84   2024-09-27 01:23:59  30.30    11.88    -23.21
85   2024-09-27 01:25:01  30.37    11.75    -23.21
86   2024-09-27 01:25:58  30.44    12.14    -23.21
87   2024-09-27 01:26:59  30.52    11.21    -23.21
88   2024-09-27 01:28:01  30.60    11.60    -23.21
89   2024-09-27 01:28:58  30.69    11.51    -23.21
90   2024-09-27 01:30:00  30.77    11.81    -23.21
91   2024-09-27 01:31:01  30.87    12.86    -23.21
92   2024-09-27 01:31:58  30.96    10.96    -23.21
93   2024-09-27 01:33:00  31.07    11.72    -23.21
94   2024-09-27 01:34:01  31.17    11.41    -23.21
95   2024-09-27 01:34:58  31.28    10.80    -23.21
96   2024-09-27 01:36:00  31.40    11.23    -23.21
97   2024-09-27 01:37:01  31.52    11.32    -23.21
98   2024-09-27 01:37:58  31.65    12.40    -23.21
99   2024-09-27 01:38:59  31.78    10.97    -23.21
100  2024-09-27 01:40:01  31.92    11.20    -23.21
101  2024-09-27 01:40:58  32.07    11.76    -23.21
102  2024-09-27 01:42:00  32.22    12.70    -23.21
103  2024-09-27 01:43:01  32.38    11.74    -23.21
104  2024-09-27 01:43:58  32.55    10.72    -23.21
105  2024-09-27 01:45:00  32.72    11.83    -23.21
106  2024-09-27 01:46:01  32.90    12.04    -23.21
107  2024-09-27 01:46:58  33.08    12.14    -23.21
108  2024-09-27 01:48:00  33.27    12.57    -23.21
109  2024-09-27 01:49:01  33.47    11.54    -23.21
110  2024-09-27 01:49:58  33.67    11.96    -23.21
111  2024-09-27 01:51:00  33.88    12.01    -23.21
112  2024-09-27 01:52:01  34.09    12.37    -23.21
113  2024-09-27 01:52:58  34.30    12.34    -23.21
114  2024-09-27 01:53:59  34.52    12.89    -23.21
115  2024-09-27 01:55:01  34.74    11.89    -23.21
116  2024-09-27 01:55:58  34.96    11.72    -23.21
117  2024-09-27 01:57:00  35.18    10.90    -23.21
118  2024-09-27 01:58:01  35.40    10.30    -23.21
119  2024-09-27 01:58:58  35.62     9.89    -23.21
120  2024-09-27 02:00:00  35.84    10.41    -23.21
121  2024-09-27 02:01:01  36.05    10.59    -23.21
122  2024-09-27 02:01:58  36.26    10.55    -23.21
123  2024-09-27 02:02:59  36.46    10.36    -23.21
124  2024-09-27 02:04:01  36.65    10.28    -23.21
125  2024-09-27 02:04:58  36.84    10.85    -23.21
126  2024-09-27 02:06:00  37.02    11.35    -23.21
127  2024-09-27 02:07:01  37.18    10.64    -23.21
128  2024-09-27 02:07:58  37.34    11.14    -23.21
129  2024-09-27 02:08:59  37.48    10.87    -23.21
130  2024-09-27 02:10:01  37.61    10.43    -23.21
131  2024-09-27 02:10:58  37.73    11.24    -23.21
132  2024-09-27 02:12:00  37.83    11.16    -23.21
133  2024-09-27 02:13:01  37.91    10.68    -23.21
134  2024-09-27 02:13:58  37.98    10.84    -23.21
135  2024-09-27 02:15:00  38.03    11.62    -23.21
136  2024-09-27 02:16:01  38.06    11.13    -23.21
137  2024-09-27 02:16:58  38.07    10.39    -23.21
138  2024-09-27 02:17:59  38.07    11.04    -23.21
139  2024-09-27 02:19:01  38.04    11.17    -23.21
140  2024-09-27 02:19:58  38.00    11.23    -23.21
141  2024-09-27 02:21:00  37.94    11.12    -23.21
142  2024-09-27 02:22:01  37.86    11.01    -23.21
143  2024-09-27 02:22:58  37.76    11.19    -23.21
144  2024-09-27 02:23:59  37.64    11.14    -23.21
145  2024-09-27 02:25:01  37.51    11.20    -23.21
146  2024-09-27 02:25:58  37.35    11.11    -23.21
147  2024-09-27 02:27:00  37.18    10.93    -23.21
148  2024-09-27 02:28:01  37.00    10.88    -23.21
149  2024-09-27 02:28:58  36.79    10.66    -23.21
150  2024-09-27 02:30:00  36.57    11.03    -23.21
151  2024-09-27 02:31:01  36.34    10.88    -23.21
152  2024-09-27 02:31:58  36.10    10.96    -23.21
153  2024-09-27 02:32:59  35.84    10.66    -23.21
154  2024-09-27 02:34:01  35.57    10.40    -23.21
155  2024-09-27 02:34:58  35.29    10.60    -23.21
156  2024-09-27 02:36:00  35.00    10.50    -23.21
157  2024-09-27 02:37:01  34.70    10.80    -23.21
158  2024-09-27 02:37:58  34.39    10.97    -23.21
159  2024-09-27 02:38:59  34.08    10.91    -23.21
160  2024-09-27 02:40:01  33.76    10.70    -23.21
161  2024-09-27 02:40:58  33.43    10.91    -23.21
162  2024-09-27 02:42:00  33.10    11.27    -23.21
163  2024-09-27 02:43:01  32.77    10.45    -23.21
164  2024-09-27 02:43:58  32.43    11.51    -23.21
165  2024-09-27 02:45:00  32.10    10.57    -23.21
166  2024-09-27 02:46:01  31.76    10.80    -23.21
167  2024-09-27 02:46:58  31.42    10.93    -23.21
168  2024-09-27 02:47:59  31.09    10.26    -23.21
169  2024-09-27 02:49:01  30.75    10.58    -23.21
170  2024-09-27 02:49:58  30.42    10.72    -23.21
171  2024-09-27 02:51:00  30.09    10.68    -23.21
172  2024-09-27 02:52:01  29.77    10.56    -23.21
173  2024-09-27 02:52:58  29.45    10.69    -23.21
174  2024-09-27 02:53:59  29.13    10.05    -23.21
175  2024-09-27 02:55:01  28.82    11.34    -23.21
176  2024-09-27 02:55:58  28.52    10.20    -23.21
177  2024-09-27 02:57:00  28.22    11.52    -23.21
178  2024-09-27 02:58:01  27.93    10.37    -23.21
179  2024-09-27 02:58:58  27.65    11.03    -23.21
180  2024-09-27 03:00:00  27.37    11.19    -23.21
181  2024-09-27 03:01:01  27.11    11.22    -23.21
182  2024-09-27 03:01:58  26.85    11.11    -23.21
183  2024-09-27 03:02:59  26.59    11.79    -23.21
184  2024-09-27 03:04:01  26.35    10.68    -23.21
185  2024-09-27 03:04:58  26.11    11.23    -23.21
186  2024-09-27 03:06:00  25.89    11.04    -23.21
187  2024-09-27 03:07:01  25.67    11.42    -23.21
188  2024-09-27 03:07:58  25.46    11.66    -23.21
189  2024-09-27 03:08:59  25.26    10.71    -23.21
190  2024-09-27 03:10:01  25.06    11.20    -23.21
191  2024-09-27 03:10:58  24.88    11.93    -23.21
192  2024-09-27 03:12:00  24.70    10.84    -23.21
193  2024-09-27 03:13:01  24.54    10.93    -23.21
194  2024-09-27 03:13:58  24.38     8.89    -23.21
195  2024-09-27 03:15:00  24.22    10.07    -23.21
196  2024-09-27 03:16:01  24.08     8.92    -23.21
197  2024-09-27 03:16:58  23.94    10.13    -23.21
198  2024-09-27 03:17:59  23.81     9.52    -23.21
199  2024-09-27 03:19:01  23.69     9.68    -23.21
200  2024-09-27 03:19:58  23.57     9.53    -23.21
201  2024-09-27 03:21:00  23.46     9.78    -23.21
202  2024-09-27 03:22:01  23.36     9.81    -23.21
203  2024-09-27 03:22:58  23.26     9.20    -23.21
204  2024-09-27 03:23:59  23.16    10.47    -23.21
205  2024-09-27 03:25:01  23.07     9.96    -23.21
206  2024-09-27 03:25:58  22.99     9.29    -23.21
207  2024-09-27 03:27:00  22.91    10.05    -23.21
208  2024-09-27 03:28:01  22.83     7.02    -23.21
209  2024-09-27 03:28:58  22.75     6.79    -23.21
210  2024-09-27 03:30:00  22.68     6.69    -23.21
211  2024-09-27 03:31:01  22.62     6.77    -23.21
212  2024-09-27 03:31:58  22.55     7.11    -23.21
213  2024-09-27 03:32:59  22.49     6.49    -23.21
214  2024-09-27 03:34:01  22.43     7.08    -23.21
215  2024-09-27 03:34:58  22.37     6.44    -23.21
216  2024-09-27 03:36:00  22.31     6.91    -23.21
217  2024-09-27 03:37:01  22.25     6.94    -23.21
218  2024-09-27 03:37:58  22.20     7.15    -23.21
219  2024-09-27 03:38:59  22.15     6.84    -23.21
220  2024-09-27 03:40:01  22.09     7.62    -23.21
221  2024-09-27 03:40:58  22.04     7.25    -23.21
222  2024-09-27 03:42:00  21.99     7.34    -23.21
223  2024-09-27 03:43:01  21.95     5.28    -23.21
224  2024-09-27 03:43:58  21.90     3.50    -23.21
225  2024-09-27 03:45:00  21.86     3.41    -23.21
226  2024-09-27 03:46:01  21.81     3.31    -23.21
227  2024-09-27 03:46:58  21.77     3.20    -23.21
228  2024-09-27 03:47:59  21.73     3.28    -23.21
229  2024-09-27 03:49:01  21.70     3.03    -23.21
230  2024-09-27 03:49:58  21.66     2.96    -23.21
231  2024-09-27 03:51:00  21.63     2.69    -23.21
232  2024-09-27 03:52:01  21.60     2.97    -23.21
233  2024-09-27 03:52:58  21.57     8.34    -23.21
234  2024-09-27 03:53:59  21.54    10.29    -23.21
235  2024-09-27 03:55:01  21.52    10.06    -23.21
236  2024-09-27 03:55:58  21.50     9.97    -23.21
237  2024-09-27 03:57:00  21.48     9.60    -23.21
238  2024-09-27 03:58:01  21.46     9.34    -23.21
239  2024-09-27 03:58:58  21.45     9.06    -23.21
240  2024-09-27 04:00:00  21.44     9.02    -23.21
241  2024-09-27 04:01:01  21.44     8.87    -23.21
242  2024-09-27 04:01:58  21.43     9.12    -23.21
243  2024-09-27 04:02:59  21.43     8.32    -23.21
244  2024-09-27 04:04:01  21.44     8.14    -23.21
245  2024-09-27 04:04:58  21.44     7.19    -23.21
246  2024-09-27 04:05:59  21.45     7.83    -23.21
247  2024-09-27 04:07:01  21.46     7.83    -23.21
248  2024-09-27 04:07:58  21.47     7.57    -23.21
249  2024-09-27 04:09:00  21.49     7.86    -23.21
250  2024-09-27 04:10:01  21.51     6.56    -23.21
251  2024-09-27 04:10:58  21.53     7.03    -23.21
252  2024-09-27 04:12:00  21.55     7.00    -23.21
253  2024-09-27 04:13:01  21.58     7.00    -23.21
254  2024-09-27 04:13:58  21.61     6.76    -23.21
255  2024-09-27 04:15:00  21.63     7.02    -23.21
256  2024-09-27 04:16:01  21.67     5.96    -23.21
257  2024-09-27 04:16:58  21.70     6.40    -23.21
258  2024-09-27 04:17:59  21.73     6.32    -23.21
259  2024-09-27 04:19:01  21.76     6.26    -23.21
260  2024-09-27 04:19:58  21.80     6.17    -23.21
261  2024-09-27 04:20:59  21.83     5.91    -23.21
262  2024-09-27 04:22:01  21.87     6.03    -23.21
263  2024-09-27 04:22:58  21.91     6.28    -23.21
264  2024-09-27 04:24:00  21.94     5.37    -23.21
265  2024-09-27 04:25:01  21.98     5.69    -23.21
266  2024-09-27 04:25:58  22.02     6.02    -23.21
267  2024-09-27 04:27:00  22.05     5.11    -23.21
268  2024-09-27 04:28:01  22.09     5.57    -23.21
269  2024-09-27 04:28:58  22.12     5.70    -23.21
270  2024-09-27 04:30:00  22.16     4.86    -23.21
271  2024-09-27 04:31:01  22.19     5.70    -23.21
272  2024-09-27 04:31:58  22.22     4.83    -23.21
273  2024-09-27 04:32:59  22.26     5.11    -23.21
274  2024-09-27 04:34:01  22.29     4.94    -23.21
275  2024-09-27 04:34:58  22.31     4.88    -23.21
276  2024-09-27 04:35:59  22.34     4.99    -23.21
277  2024-09-27 04:37:01  22.37     4.66    -23.21
278  2024-09-27 04:37:58  22.39     4.88    -23.21
279  2024-09-27 04:39:00  22.42     4.56    -23.21
280  2024-09-27 04:40:01  22.44     4.80    -23.21
281  2024-09-27 04:40:58  22.45     4.60    -23.21
282  2024-09-27 04:42:00  22.47     4.54    -23.21
283  2024-09-27 04:43:01  22.48     4.32    -23.21
284  2024-09-27 04:43:58  22.50     4.59    -23.21
285  2024-09-27 04:45:00  22.50     4.52    -23.21
286  2024-09-27 04:46:01  22.51     4.11    -23.21
287  2024-09-27 04:46:58  22.51     4.31    -23.21
288  2024-09-27 04:47:59  22.51     4.29    -23.21
289  2024-09-27 04:49:01  22.51     4.25    -23.21
290  2024-09-27 04:49:58  22.50     4.24    -23.21
291  2024-09-27 04:50:59  22.48     4.19    -23.21
292  2024-09-27 04:52:01  22.47     4.19    -23.21
293  2024-09-27 04:52:58  22.45     3.76    -23.21
294  2024-09-27 04:54:00  22.42     3.61    -23.21
295  2024-09-27 04:55:01  22.39     3.34    -23.21
296  2024-09-27 04:55:58  22.36     3.42    -23.21
297  2024-09-27 04:57:00  22.32     3.20    -23.21
298  2024-09-27 04:58:01  22.27     3.09    -23.21
299  2024-09-27 04:58:58  22.22     3.01    -23.21
300  2024-09-27 05:00:00  22.17     2.89    -23.21
301  2024-09-27 05:01:01  22.11     2.91    -23.21
302  2024-09-27 05:01:58  22.04     2.84    -23.21
303  2024-09-27 05:02:59  21.97     2.70    -23.21
304  2024-09-27 05:04:01  21.89     2.64    -23.21
305  2024-09-27 05:04:58  21.81     2.65    -23.21
306  2024-09-27 05:05:59  21.72     2.59    -23.21
307  2024-09-27 05:07:01  21.62     2.35    -23.21
308  2024-09-27 05:07:58  21.52     2.54    -23.21
309  2024-09-27 05:09:00  21.41     2.30    -23.21
310  2024-09-27 05:10:01  21.30     2.05    -23.21
311  2024-09-27 05:10:58  21.18     2.24    -23.21
312  2024-09-27 05:12:00  21.06     2.08    -23.21
313  2024-09-27 05:13:01  20.93     2.03    -23.21
314  2024-09-27 05:13:58  20.79     1.92    -23.21
315  2024-09-27 05:15:00  20.65     1.84    -23.21
316  2024-09-27 05:16:01  20.51     1.86    -23.21
317  2024-09-27 05:16:58  20.35     1.83    -23.21
318  2024-09-27 05:17:59  20.20     1.78    -23.21
319  2024-09-27 05:19:01  20.04     1.71    -23.21
320  2024-09-27 05:19:58  19.87     8.23    -23.21
321  2024-09-27 05:20:59  19.70     8.87    -23.21
322  2024-09-27 05:22:01  19.52     8.66    -23.21
323  2024-09-27 05:22:58  19.34     8.53    -23.21
324  2024-09-27 05:24:00  19.16     8.80    -23.21
325  2024-09-27 05:25:01  18.97     7.23    -23.21
326  2024-09-27 05:25:58  18.78     8.03    -23.21
327  2024-09-27 05:27:00  18.58     7.78    -23.21
328  2024-09-27 05:28:01  18.39     7.52    -23.21
329  2024-09-27 05:28:58  18.18     7.45    -23.21
330  2024-09-27 05:30:00  17.98     7.28    -23.21
331  2024-09-27 05:31:01  17.77     7.22    -23.21
332  2024-09-27 05:31:58  17.56     7.39    -23.21
333  2024-09-27 05:32:59  17.35     5.97    -23.21
334  2024-09-27 05:34:01  17.13     6.51    -23.21
335  2024-09-27 05:34:58  16.92     6.41    -23.21
336  2024-09-27 05:35:59  16.70     6.06    -23.21
337  2024-09-27 05:37:01  16.48     6.03    -23.21
338  2024-09-27 05:37:58  16.26     5.80    -23.21
339  2024-09-27 05:39:00  16.03     5.98    -23.21
340  2024-09-27 05:40:01  15.81     4.88    -23.21
341  2024-09-27 05:40:58  15.59     5.74    -23.21
342  2024-09-27 05:42:00  15.36     4.64    -23.21
343  2024-09-27 05:43:01  15.14     5.13    -23.21
344  2024-09-27 05:43:58  14.91     5.24    -23.21
345  2024-09-27 05:45:00  14.68     4.77    -23.21
346  2024-09-27 05:46:01  14.46     4.20    -23.21
347  2024-09-27 05:46:58  14.23     4.60    -23.21
348  2024-09-27 05:47:59  14.01     4.85    -23.21
349  2024-09-27 05:49:01  13.78     4.38    -23.21
350  2024-09-27 05:49:58  13.56     3.87    -23.21
351  2024-09-27 05:50:59  13.34     4.50    -23.21
352  2024-09-27 05:52:01  13.12     3.68    -23.21
353  2024-09-27 05:52:58  12.90     4.15    -23.21
354  2024-09-27 05:54:00  12.68     3.98    -23.21
355  2024-09-27 05:55:01  12.47     4.22    -23.21
356  2024-09-27 05:55:58  12.25     3.39    -23.21
357  2024-09-27 05:57:00  12.04     3.74    -23.21
358  2024-09-27 05:58:01  11.83     3.56    -23.21
359  2024-09-27 05:58:58  11.63     3.51    -23.21
360  2024-09-27 06:00:00  11.43     3.39    -23.21
361  2024-09-27 06:01:01  11.23     3.29    -23.21
362  2024-09-27 06:01:58  11.03     3.20    -23.21
363  2024-09-27 06:02:59  10.84     3.54    -23.21
364  2024-09-27 06:04:01  10.65     3.35    -23.21
365  2024-09-27 06:04:58  10.46     2.97    -23.21
366  2024-09-27 06:05:59  10.28     3.16    -23.21
367  2024-09-27 06:07:01  10.10     3.33    -23.21
368  2024-09-27 06:07:58   9.93     3.05    -23.21
369  2024-09-27 06:09:00   9.76     2.69    -23.21
370  2024-09-27 06:10:01   9.59     2.96    -23.21
371  2024-09-27 06:10:58   9.43     2.80    -23.21
372  2024-09-27 06:12:00   9.28     2.79    -23.21
373  2024-09-27 06:13:01   9.12     2.88    -23.21
374  2024-09-27 06:13:58   8.97     2.37    -23.21
375  2024-09-27 06:15:00   8.83     2.65    -23.21
376  2024-09-27 06:16:01   8.69     2.42    -23.21
377  2024-09-27 06:16:58   8.55     2.39    -23.21
378  2024-09-27 06:17:59   8.42     2.32    -23.21
379  2024-09-27 06:19:01   8.29     2.29    -23.21
380  2024-09-27 06:19:58   8.17     2.24    -23.21
381  2024-09-27 06:20:59   8.05     2.20    -23.21
382  2024-09-27 06:22:01   7.93     2.19    -23.21
383  2024-09-27 06:22:58   7.82     2.14    -23.21
384  2024-09-27 06:24:00   7.71     2.11    -23.21
385  2024-09-27 06:25:01   7.60     2.08    -23.21
386  2024-09-27 06:25:58   7.50     2.05    -23.21
387  2024-09-27 06:27:00   7.40     1.99    -23.21
388  2024-09-27 06:28:01   7.30     1.92    -23.21
389  2024-09-27 06:28:58   7.20     1.85    -23.21
390  2024-09-27 06:30:00   7.11     3.28    -23.21

In [ ]:
df

                DATETIME    TEC  TEC_STD  LATITUDE
0    2024-09-27 00:00:00  40.12    16.32    -23.21
1    2024-09-27 00:01:01  40.01    20.26    -23.21
2    2024-09-27 00:01:58  39.89    18.91    -23.21
3    2024-09-27 00:03:00  39.76    19.12    -23.21
4    2024-09-27 00:04:01  39.62    20.02    -23.21
5    2024-09-27 00:04:58  39.47    19.24    -23.21
6    2024-09-27 00:06:00  39.31    18.05    -23.21
7    2024-09-27 00:07:01  39.14    13.91    -23.21
8    2024-09-27 00:07:58  38.97    16.61    -23.21
9    2024-09-27 00:09:00  38.79    16.05    -23.21
10   2024-09-27 00:10:01  38.60    16.75    -23.21
11   2024-09-27 00:10:58  38.40    16.78    -23.21
12   2024-09-27 00:12:00  38.19    16.77    -23.21
13   2024-09-27 00:13:01  37.98    15.47    -23.21
14   2024-09-27 00:13:58  37.77    16.49    -23.21
15   2024-09-27 00:15:00  37.55    16.41    -23.21
16   2024-09-27 00:16:01  37.32    15.94    -23.21
17   2024-09-27 00:16:58  37.10    13.65    -23.21
18   2024-09-27 00:18:00  36.87    13.68    -23.21
19   2024-09-27 00:19:01  36.63    13.86    -23.21
20   2024-09-27 00:19:58  36.40    13.63    -23.21
21   2024-09-27 00:21:00  36.17    15.05    -23.21
22   2024-09-27 00:22:01  35.93    14.18    -23.21
23   2024-09-27 00:22:58  35.70    14.95    -23.21
24   2024-09-27 00:24:00  35.46    15.31    -23.21
25   2024-09-27 00:25:01  35.23    15.63    -23.21
26   2024-09-27 00:25:58  35.01    16.14    -23.21
27   2024-09-27 00:27:00  34.78    16.33    -23.21
28   2024-09-27 00:28:01  34.56    16.90    -23.21
29   2024-09-27 00:28:58  34.34    16.85    -23.21
30   2024-09-27 00:30:00  34.12    16.48    -23.21
31   2024-09-27 00:31:01  33.91    17.93    -23.21
32   2024-09-27 00:31:58  33.71    17.42    -23.21
33   2024-09-27 00:33:00  33.51    18.11    -23.21
34   2024-09-27 00:34:01  33.31    18.92    -23.21
35   2024-09-27 00:34:58  33.12    18.78    -23.21
36   2024-09-27 00:36:00  32.94    18.20    -23.21
37   2024-09-27 00:37:01  32.76    19.87    -23.21
38   2024-09-27 00:37:58  32.58    20.46    -23.21
39   2024-09-27 00:39:00  32.41    20.58    -23.21
40   2024-09-27 00:40:01  32.25    19.28    -23.21
41   2024-09-27 00:40:58  32.09    19.90    -23.21
42   2024-09-27 00:42:00  31.93    20.11    -23.21
43   2024-09-27 00:43:01  31.79    20.31    -23.21
44   2024-09-27 00:43:58  31.64    20.13    -23.21
45   2024-09-27 00:45:00  31.51    20.32    -23.21
46   2024-09-27 00:46:01  31.37    20.51    -23.21
47   2024-09-27 00:46:58  31.24    19.18    -23.21
48   2024-09-27 00:48:00  31.12    19.73    -23.21
49   2024-09-27 00:49:01  31.00    19.47    -23.21
50   2024-09-27 00:49:58  30.89    19.69    -23.21
51   2024-09-27 00:51:00  30.78    17.98    -23.21
52   2024-09-27 00:52:01  30.68    14.48    -23.21
53   2024-09-27 00:52:58  30.58    14.35    -23.21
54   2024-09-27 00:54:00  30.49    13.83    -23.21
55   2024-09-27 00:55:01  30.41    13.37    -23.21
56   2024-09-27 00:55:58  30.33    12.68    -23.21
57   2024-09-27 00:57:00  30.25    12.37    -23.21
58   2024-09-27 00:58:01  30.18    11.85    -23.21
59   2024-09-27 00:58:58  30.12    11.56    -23.21
60   2024-09-27 01:00:00  30.06    11.62    -23.21
61   2024-09-27 01:01:01  30.01    10.59    -23.21
62   2024-09-27 01:01:58  29.96     9.37    -23.21
63   2024-09-27 01:03:00  29.92    10.53    -23.21
64   2024-09-27 01:04:01  29.89     8.67    -23.21
65   2024-09-27 01:04:58  29.86     9.48    -23.21
66   2024-09-27 01:06:00  29.84     8.94    -23.21
67   2024-09-27 01:07:01  29.82     8.87    -23.21
68   2024-09-27 01:07:58  29.81     8.44    -23.21
69   2024-09-27 01:08:59  29.80     8.23    -23.21
70   2024-09-27 01:10:01  29.80     7.92    -23.21
71   2024-09-27 01:10:58  29.81     7.59    -23.21
72   2024-09-27 01:11:59  29.81     7.98    -23.21
73   2024-09-27 01:13:01  29.83     7.14    -23.21
74   2024-09-27 01:13:58  29.85     6.27    -23.21
75   2024-09-27 01:15:00  29.87    10.50    -23.21
76   2024-09-27 01:16:01  29.90    10.81    -23.21
77   2024-09-27 01:16:58  29.94    11.55    -23.21
78   2024-09-27 01:18:00  29.98    10.26    -23.21
79   2024-09-27 01:19:01  30.02    11.10    -23.21
80   2024-09-27 01:19:58  30.07    11.25    -23.21
81   2024-09-27 01:21:00  30.12    11.34    -23.21
82   2024-09-27 01:22:01  30.18    11.70    -23.21
83   2024-09-27 01:22:58  30.24    11.22    -23.21
84   2024-09-27 01:23:59  30.30    11.88    -23.21
85   2024-09-27 01:25:01  30.37    11.75    -23.21
86   2024-09-27 01:25:58  30.44    12.14    -23.21
87   2024-09-27 01:26:59  30.52    11.21    -23.21
88   2024-09-27 01:28:01  30.60    11.60    -23.21
89   2024-09-27 01:28:58  30.69    11.51    -23.21
90   2024-09-27 01:30:00  30.77    11.81    -23.21
91   2024-09-27 01:31:01  30.87    12.86    -23.21
92   2024-09-27 01:31:58  30.96    10.96    -23.21
93   2024-09-27 01:33:00  31.07    11.72    -23.21
94   2024-09-27 01:34:01  31.17    11.41    -23.21
95   2024-09-27 01:34:58  31.28    10.80    -23.21
96   2024-09-27 01:36:00  31.40    11.23    -23.21
97   2024-09-27 01:37:01  31.52    11.32    -23.21
98   2024-09-27 01:37:58  31.65    12.40    -23.21
99   2024-09-27 01:38:59  31.78    10.97    -23.21
100  2024-09-27 01:40:01  31.92    11.20    -23.21
101  2024-09-27 01:40:58  32.07    11.76    -23.21
102  2024-09-27 01:42:00  32.22    12.70    -23.21
103  2024-09-27 01:43:01  32.38    11.74    -23.21
104  2024-09-27 01:43:58  32.55    10.72    -23.21
105  2024-09-27 01:45:00  32.72    11.83    -23.21
106  2024-09-27 01:46:01  32.90    12.04    -23.21
107  2024-09-27 01:46:58  33.08    12.14    -23.21
108  2024-09-27 01:48:00  33.27    12.57    -23.21
109  2024-09-27 01:49:01  33.47    11.54    -23.21
110  2024-09-27 01:49:58  33.67    11.96    -23.21
111  2024-09-27 01:51:00  33.88    12.01    -23.21
112  2024-09-27 01:52:01  34.09    12.37    -23.21
113  2024-09-27 01:52:58  34.30    12.34    -23.21
114  2024-09-27 01:53:59  34.52    12.89    -23.21
115  2024-09-27 01:55:01  34.74    11.89    -23.21
116  2024-09-27 01:55:58  34.96    11.72    -23.21
117  2024-09-27 01:57:00  35.18    10.90    -23.21
118  2024-09-27 01:58:01  35.40    10.30    -23.21
119  2024-09-27 01:58:58  35.62     9.89    -23.21
120  2024-09-27 02:00:00  35.84    10.41    -23.21
121  2024-09-27 02:01:01  36.05    10.59    -23.21
122  2024-09-27 02:01:58  36.26    10.55    -23.21
123  2024-09-27 02:02:59  36.46    10.36    -23.21
124  2024-09-27 02:04:01  36.65    10.28    -23.21
125  2024-09-27 02:04:58  36.84    10.85    -23.21
126  2024-09-27 02:06:00  37.02    11.35    -23.21
127  2024-09-27 02:07:01  37.18    10.64    -23.21
128  2024-09-27 02:07:58  37.34    11.14    -23.21
129  2024-09-27 02:08:59  37.48    10.87    -23.21
130  2024-09-27 02:10:01  37.61    10.43    -23.21
131  2024-09-27 02:10:58  37.73    11.24    -23.21
132  2024-09-27 02:12:00  37.83    11.16    -23.21
133  2024-09-27 02:13:01  37.91    10.68    -23.21
134  2024-09-27 02:13:58  37.98    10.84    -23.21
135  2024-09-27 02:15:00  38.03    11.62    -23.21
136  2024-09-27 02:16:01  38.06    11.13    -23.21
137  2024-09-27 02:16:58  38.07    10.39    -23.21
138  2024-09-27 02:17:59  38.07    11.04    -23.21
139  2024-09-27 02:19:01  38.04    11.17    -23.21
140  2024-09-27 02:19:58  38.00    11.23    -23.21
141  2024-09-27 02:21:00  37.94    11.12    -23.21
142  2024-09-27 02:22:01  37.86    11.01    -23.21
143  2024-09-27 02:22:58  37.76    11.19    -23.21
144  2024-09-27 02:23:59  37.64    11.14    -23.21
145  2024-09-27 02:25:01  37.51    11.20    -23.21
146  2024-09-27 02:25:58  37.35    11.11    -23.21
147  2024-09-27 02:27:00  37.18    10.93    -23.21
148  2024-09-27 02:28:01  37.00    10.88    -23.21
149  2024-09-27 02:28:58  36.79    10.66    -23.21
150  2024-09-27 02:30:00  36.57    11.03    -23.21
151  2024-09-27 02:31:01  36.34    10.88    -23.21
152  2024-09-27 02:31:58  36.10    10.96    -23.21
153  2024-09-27 02:32:59  35.84    10.66    -23.21
154  2024-09-27 02:34:01  35.57    10.40    -23.21
155  2024-09-27 02:34:58  35.29    10.60    -23.21
156  2024-09-27 02:36:00  35.00    10.50    -23.21
157  2024-09-27 02:37:01  34.70    10.80    -23.21
158  2024-09-27 02:37:58  34.39    10.97    -23.21
159  2024-09-27 02:38:59  34.08    10.91    -23.21
160  2024-09-27 02:40:01  33.76    10.70    -23.21
161  2024-09-27 02:40:58  33.43    10.91    -23.21
162  2024-09-27 02:42:00  33.10    11.27    -23.21
163  2024-09-27 02:43:01  32.77    10.45    -23.21
164  2024-09-27 02:43:58  32.43    11.51    -23.21
165  2024-09-27 02:45:00  32.10    10.57    -23.21
166  2024-09-27 02:46:01  31.76    10.80    -23.21
167  2024-09-27 02:46:58  31.42    10.93    -23.21
168  2024-09-27 02:47:59  31.09    10.26    -23.21
169  2024-09-27 02:49:01  30.75    10.58    -23.21
170  2024-09-27 02:49:58  30.42    10.72    -23.21
171  2024-09-27 02:51:00  30.09    10.68    -23.21
172  2024-09-27 02:52:01  29.77    10.56    -23.21
173  2024-09-27 02:52:58  29.45    10.69    -23.21
174  2024-09-27 02:53:59  29.13    10.05    -23.21
175  2024-09-27 02:55:01  28.82    11.34    -23.21
176  2024-09-27 02:55:58  28.52    10.20    -23.21
177  2024-09-27 02:57:00  28.22    11.52    -23.21
178  2024-09-27 02:58:01  27.93    10.37    -23.21
179  2024-09-27 02:58:58  27.65    11.03    -23.21
180  2024-09-27 03:00:00  27.37    11.19    -23.21
181  2024-09-27 03:01:01  27.11    11.22    -23.21
182  2024-09-27 03:01:58  26.85    11.11    -23.21
183  2024-09-27 03:02:59  26.59    11.79    -23.21
184  2024-09-27 03:04:01  26.35    10.68    -23.21
185  2024-09-27 03:04:58  26.11    11.23    -23.21
186  2024-09-27 03:06:00  25.89    11.04    -23.21
187  2024-09-27 03:07:01  25.67    11.42    -23.21
188  2024-09-27 03:07:58  25.46    11.66    -23.21
189  2024-09-27 03:08:59  25.26    10.71    -23.21
190  2024-09-27 03:10:01  25.06    11.20    -23.21
191  2024-09-27 03:10:58  24.88    11.93    -23.21
192  2024-09-27 03:12:00  24.70    10.84    -23.21
193  2024-09-27 03:13:01  24.54    10.93    -23.21
194  2024-09-27 03:13:58  24.38     8.89    -23.21
195  2024-09-27 03:15:00  24.22    10.07    -23.21
196  2024-09-27 03:16:01  24.08     8.92    -23.21
197  2024-09-27 03:16:58  23.94    10.13    -23.21
198  2024-09-27 03:17:59  23.81     9.52    -23.21
199  2024-09-27 03:19:01  23.69     9.68    -23.21
200  2024-09-27 03:19:58  23.57     9.53    -23.21
201  2024-09-27 03:21:00  23.46     9.78    -23.21
202  2024-09-27 03:22:01  23.36     9.81    -23.21
203  2024-09-27 03:22:58  23.26     9.20    -23.21
204  2024-09-27 03:23:59  23.16    10.47    -23.21
205  2024-09-27 03:25:01  23.07     9.96    -23.21
206  2024-09-27 03:25:58  22.99     9.29    -23.21
207  2024-09-27 03:27:00  22.91    10.05    -23.21
208  2024-09-27 03:28:01  22.83     7.02    -23.21
209  2024-09-27 03:28:58  22.75     6.79    -23.21
210  2024-09-27 03:30:00  22.68     6.69    -23.21
211  2024-09-27 03:31:01  22.62     6.77    -23.21
212  2024-09-27 03:31:58  22.55     7.11    -23.21
213  2024-09-27 03:32:59  22.49     6.49    -23.21
214  2024-09-27 03:34:01  22.43     7.08    -23.21
215  2024-09-27 03:34:58  22.37     6.44    -23.21
216  2024-09-27 03:36:00  22.31     6.91    -23.21
217  2024-09-27 03:37:01  22.25     6.94    -23.21
218  2024-09-27 03:37:58  22.20     7.15    -23.21
219  2024-09-27 03:38:59  22.15     6.84    -23.21
220  2024-09-27 03:40:01  22.09     7.62    -23.21
221  2024-09-27 03:40:58  22.04     7.25    -23.21
222  2024-09-27 03:42:00  21.99     7.34    -23.21
223  2024-09-27 03:43:01  21.95     5.28    -23.21
224  2024-09-27 03:43:58  21.90     3.50    -23.21
225  2024-09-27 03:45:00  21.86     3.41    -23.21
226  2024-09-27 03:46:01  21.81     3.31    -23.21
227  2024-09-27 03:46:58  21.77     3.20    -23.21
228  2024-09-27 03:47:59  21.73     3.28    -23.21
229  2024-09-27 03:49:01  21.70     3.03    -23.21
230  2024-09-27 03:49:58  21.66     2.96    -23.21
231  2024-09-27 03:51:00  21.63     2.69    -23.21
232  2024-09-27 03:52:01  21.60     2.97    -23.21
233  2024-09-27 03:52:58  21.57     8.34    -23.21
234  2024-09-27 03:53:59  21.54    10.29    -23.21
235  2024-09-27 03:55:01  21.52    10.06    -23.21
236  2024-09-27 03:55:58  21.50     9.97    -23.21
237  2024-09-27 03:57:00  21.48     9.60    -23.21
238  2024-09-27 03:58:01  21.46     9.34    -23.21
239  2024-09-27 03:58:58  21.45     9.06    -23.21
240  2024-09-27 04:00:00  21.44     9.02    -23.21
241  2024-09-27 04:01:01  21.44     8.87    -23.21
242  2024-09-27 04:01:58  21.43     9.12    -23.21
243  2024-09-27 04:02:59  21.43     8.32    -23.21
244  2024-09-27 04:04:01  21.44     8.14    -23.21
245  2024-09-27 04:04:58  21.44     7.19    -23.21
246  2024-09-27 04:05:59  21.45     7.83    -23.21
247  2024-09-27 04:07:01  21.46     7.83    -23.21
248  2024-09-27 04:07:58  21.47     7.57    -23.21
249  2024-09-27 04:09:00  21.49     7.86    -23.21
250  2024-09-27 04:10:01  21.51     6.56    -23.21
251  2024-09-27 04:10:58  21.53     7.03    -23.21
252  2024-09-27 04:12:00  21.55     7.00    -23.21
253  2024-09-27 04:13:01  21.58     7.00    -23.21
254  2024-09-27 04:13:58  21.61     6.76    -23.21
255  2024-09-27 04:15:00  21.63     7.02    -23.21
256  2024-09-27 04:16:01  21.67     5.96    -23.21
257  2024-09-27 04:16:58  21.70     6.40    -23.21
258  2024-09-27 04:17:59  21.73     6.32    -23.21
259  2024-09-27 04:19:01  21.76     6.26    -23.21
260  2024-09-27 04:19:58  21.80     6.17    -23.21
261  2024-09-27 04:20:59  21.83     5.91    -23.21
262  2024-09-27 04:22:01  21.87     6.03    -23.21
263  2024-09-27 04:22:58  21.91     6.28    -23.21
264  2024-09-27 04:24:00  21.94     5.37    -23.21
265  2024-09-27 04:25:01  21.98     5.69    -23.21
266  2024-09-27 04:25:58  22.02     6.02    -23.21
267  2024-09-27 04:27:00  22.05     5.11    -23.21
268  2024-09-27 04:28:01  22.09     5.57    -23.21
269  2024-09-27 04:28:58  22.12     5.70    -23.21
270  2024-09-27 04:30:00  22.16     4.86    -23.21
271  2024-09-27 04:31:01  22.19     5.70    -23.21
272  2024-09-27 04:31:58  22.22     4.83    -23.21
273  2024-09-27 04:32:59  22.26     5.11    -23.21
274  2024-09-27 04:34:01  22.29     4.94    -23.21
275  2024-09-27 04:34:58  22.31     4.88    -23.21
276  2024-09-27 04:35:59  22.34     4.99    -23.21
277  2024-09-27 04:37:01  22.37     4.66    -23.21
278  2024-09-27 04:37:58  22.39     4.88    -23.21
279  2024-09-27 04:39:00  22.42     4.56    -23.21
280  2024-09-27 04:40:01  22.44     4.80    -23.21
281  2024-09-27 04:40:58  22.45     4.60    -23.21
282  2024-09-27 04:42:00  22.47     4.54    -23.21
283  2024-09-27 04:43:01  22.48     4.32    -23.21
284  2024-09-27 04:43:58  22.50     4.59    -23.21
285  2024-09-27 04:45:00  22.50     4.52    -23.21
286  2024-09-27 04:46:01  22.51     4.11    -23.21
287  2024-09-27 04:46:58  22.51     4.31    -23.21
288  2024-09-27 04:47:59  22.51     4.29    -23.21
289  2024-09-27 04:49:01  22.51     4.25    -23.21
290  2024-09-27 04:49:58  22.50     4.24    -23.21
291  2024-09-27 04:50:59  22.48     4.19    -23.21
292  2024-09-27 04:52:01  22.47     4.19    -23.21
293  2024-09-27 04:52:58  22.45     3.76    -23.21
294  2024-09-27 04:54:00  22.42     3.61    -23.21
295  2024-09-27 04:55:01  22.39     3.34    -23.21
296  2024-09-27 04:55:58  22.36     3.42    -23.21
297  2024-09-27 04:57:00  22.32     3.20    -23.21
298  2024-09-27 04:58:01  22.27     3.09    -23.21
299  2024-09-27 04:58:58  22.22     3.01    -23.21
300  2024-09-27 05:00:00  22.17     2.89    -23.21
301  2024-09-27 05:01:01  22.11     2.91    -23.21
302  2024-09-27 05:01:58  22.04     2.84    -23.21
303  2024-09-27 05:02:59  21.97     2.70    -23.21
304  2024-09-27 05:04:01  21.89     2.64    -23.21
305  2024-09-27 05:04:58  21.81     2.65    -23.21
306  2024-09-27 05:05:59  21.72     2.59    -23.21
307  2024-09-27 05:07:01  21.62     2.35    -23.21
308  2024-09-27 05:07:58  21.52     2.54    -23.21
309  2024-09-27 05:09:00  21.41     2.30    -23.21
310  2024-09-27 05:10:01  21.30     2.05    -23.21
311  2024-09-27 05:10:58  21.18     2.24    -23.21
312  2024-09-27 05:12:00  21.06     2.08    -23.21
313  2024-09-27 05:13:01  20.93     2.03    -23.21
314  2024-09-27 05:13:58  20.79     1.92    -23.21
315  2024-09-27 05:15:00  20.65     1.84    -23.21
316  2024-09-27 05:16:01  20.51     1.86    -23.21
317  2024-09-27 05:16:58  20.35     1.83    -23.21
318  2024-09-27 05:17:59  20.20     1.78    -23.21
319  2024-09-27 05:19:01  20.04     1.71    -23.21
320  2024-09-27 05:19:58  19.87     8.23    -23.21
321  2024-09-27 05:20:59  19.70     8.87    -23.21
322  2024-09-27 05:22:01  19.52     8.66    -23.21
323  2024-09-27 05:22:58  19.34     8.53    -23.21
324  2024-09-27 05:24:00  19.16     8.80    -23.21
325  2024-09-27 05:25:01  18.97     7.23    -23.21
326  2024-09-27 05:25:58  18.78     8.03    -23.21
327  2024-09-27 05:27:00  18.58     7.78    -23.21
328  2024-09-27 05:28:01  18.39     7.52    -23.21
329  2024-09-27 05:28:58  18.18     7.45    -23.21
330  2024-09-27 05:30:00  17.98     7.28    -23.21
331  2024-09-27 05:31:01  17.77     7.22    -23.21
332  2024-09-27 05:31:58  17.56     7.39    -23.21
333  2024-09-27 05:32:59  17.35     5.97    -23.21
334  2024-09-27 05:34:01  17.13     6.51    -23.21
335  2024-09-27 05:34:58  16.92     6.41    -23.21
336  2024-09-27 05:35:59  16.70     6.06    -23.21
337  2024-09-27 05:37:01  16.48     6.03    -23.21
338  2024-09-27 05:37:58  16.26     5.80    -23.21
339  2024-09-27 05:39:00  16.03     5.98    -23.21
340  2024-09-27 05:40:01  15.81     4.88    -23.21
341  2024-09-27 05:40:58  15.59     5.74    -23.21
342  2024-09-27 05:42:00  15.36     4.64    -23.21
343  2024-09-27 05:43:01  15.14     5.13    -23.21
344  2024-09-27 05:43:58  14.91     5.24    -23.21
345  2024-09-27 05:45:00  14.68     4.77    -23.21
346  2024-09-27 05:46:01  14.46     4.20    -23.21
347  2024-09-27 05:46:58  14.23     4.60    -23.21
348  2024-09-27 05:47:59  14.01     4.85    -23.21
349  2024-09-27 05:49:01  13.78     4.38    -23.21
350  2024-09-27 05:49:58  13.56     3.87    -23.21
351  2024-09-27 05:50:59  13.34     4.50    -23.21
352  2024-09-27 05:52:01  13.12     3.68    -23.21
353  2024-09-27 05:52:58  12.90     4.15    -23.21
354  2024-09-27 05:54:00  12.68     3.98    -23.21
355  2024-09-27 05:55:01  12.47     4.22    -23.21
356  2024-09-27 05:55:58  12.25     3.39    -23.21
357  2024-09-27 05:57:00  12.04     3.74    -23.21
358  2024-09-27 05:58:01  11.83     3.56    -23.21
359  2024-09-27 05:58:58  11.63     3.51    -23.21
360  2024-09-27 06:00:00  11.43     3.39    -23.21
361  2024-09-27 06:01:01  11.23     3.29    -23.21
362  2024-09-27 06:01:58  11.03     3.20    -23.21
363  2024-09-27 06:02:59  10.84     3.54    -23.21
364  2024-09-27 06:04:01  10.65     3.35    -23.21
365  2024-09-27 06:04:58  10.46     2.97    -23.21
366  2024-09-27 06:05:59  10.28     3.16    -23.21
367  2024-09-27 06:07:01  10.10     3.33    -23.21
368  2024-09-27 06:07:58   9.93     3.05    -23.21
369  2024-09-27 06:09:00   9.76     2.69    -23.21
370  2024-09-27 06:10:01   9.59     2.96    -23.21
371  2024-09-27 06:10:58   9.43     2.80    -23.21
372  2024-09-27 06:12:00   9.28     2.79    -23.21
373  2024-09-27 06:13:01   9.12     2.88    -23.21
374  2024-09-27 06:13:58   8.97     2.37    -23.21
375  2024-09-27 06:15:00   8.83     2.65    -23.21
376  2024-09-27 06:16:01   8.69     2.42    -23.21
377  2024-09-27 06:16:58   8.55     2.39    -23.21
378  2024-09-27 06:17:59   8.42     2.32    -23.21
379  2024-09-27 06:19:01   8.29     2.29    -23.21
380  2024-09-27 06:19:58   8.17     2.24    -23.21
381  2024-09-27 06:20:59   8.05     2.20    -23.21
382  2024-09-27 06:22:01   7.93     2.19    -23.21
383  2024-09-27 06:22:58   7.82     2.14    -23.21
384  2024-09-27 06:24:00   7.71     2.11    -23.21
385  2024-09-27 06:25:01   7.60     2.08    -23.21
386  2024-09-27 06:25:58   7.50     2.05    -23.21
387  2024-09-27 06:27:00   7.40     1.99    -23.21
388  2024-09-27 06:28:01   7.30     1.92    -23.21
389  2024-09-27 06:28:58   7.20     1.85    -23.21
390  2024-09-27 06:30:00   7.11     3.28    -23.21

In [ ]:
import pandas as pd
from datetime import time
import numpy as np

df['DATETIME'] = pd.to_datetime(df['DATETIME'])

target_times = [
    time(0, 50),
    time(1, 0),
    time(1, 10)
]

def find_closest_time(df, target_time):

    df_times = df['DATETIME'].dt.time


    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second


    df_seconds = (df['DATETIME'].dt.hour * 3600 +
                  df['DATETIME'].dt.minute * 60 +
                  df['DATETIME'].dt.second)


    time_diff = np.abs(df_seconds - target_seconds)


    closest_idx = time_diff.idxmin()

    return df.loc[[closest_idx]]

df_filtered_list = []
for target_time in target_times:
    closest_row = find_closest_time(df, target_time)
    df_filtered_list.append(closest_row)

df_filtered = pd.concat(df_filtered_list, ignore_index=True)

df_filtered = df_filtered.sort_values('DATETIME').reset_index(drop=True)

print("DataFrame filtered for closest times to 00:50, 01:00 and 01:10:")
print(df_filtered)

print("\nDifference from target times:")
for i, target_time in enumerate(target_times):
    actual_time = df_filtered.iloc[i]['DATETIME'].time()
    target_seconds = target_time.hour * 3600 + target_time.minute * 60 + target_time.second
    actual_seconds = actual_time.hour * 3600 + actual_time.minute * 60 + actual_time.second
    diff_seconds = abs(actual_seconds - target_seconds)
    print(f"Target: {target_time} | Actual: {actual_time} | Difference: {diff_seconds} seconds")

DataFrame filtered for closest times to 00:50, 01:00 and 01:10:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-09-27 00:49:58  30.89    19.69    -23.21
1 2024-09-27 01:00:00  30.06    11.62    -23.21
2 2024-09-27 01:10:01  29.80     7.92    -23.21

Difference from target times:
Target: 00:50:00 | Actual: 00:49:58 | Difference: 2 seconds
Target: 01:00:00 | Actual: 01:00:00 | Difference: 0 seconds
Target: 01:10:00 | Actual: 01:10:01 | Difference: 1 seconds

In [ ]:
reference_time = pd.Timestamp('2024-09-27 00:50:00')
wide_window = timedelta(minutes=5)
df_proximos = df[(df['DATETIME'] >= reference_time - wide_window) &
                 (df['DATETIME'] <= reference_time + wide_window)]
print("Records close to 00:50:")
print(df_proximos[['DATETIME', 'TEC']])

Records close to 00:50:
              DATETIME    TEC
45 2024-09-27 00:45:00  31.51
46 2024-09-27 00:46:01  31.37
47 2024-09-27 00:46:58  31.24
48 2024-09-27 00:48:00  31.12
49 2024-09-27 00:49:01  31.00
50 2024-09-27 00:49:58  30.89
51 2024-09-27 00:51:00  30.78
52 2024-09-27 00:52:01  30.68
53 2024-09-27 00:52:58  30.58
54 2024-09-27 00:54:00  30.49

In [ ]:
print(df.iloc[[50, 60, 70]][['DATETIME', 'TEC']])

              DATETIME    TEC
50 2024-09-27 00:49:58  30.89
60 2024-09-27 01:00:00  30.06
70 2024-09-27 01:10:01  29.80

In [ ]:
df.to_pickle('sjsp271-2024-09-27_selected_0050_to_0110.pkl')

# TEC maps analysis

In [ ]:
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points

## EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
class Embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
embrace_tec = Embrace()
embrace_points = embrace_tec.find_nearest_points(lat=-23.20713, lon=-45.86174)

In [ ]:
embrace_points

[(-24, -47.5, 18, 17),
 (-24, -45.0, 18, 18),
 (-22, -47.5, 19, 17),
 (-22, -45.0, 19, 18)]

In [ ]:
date = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{date} {time}' for time in times]

result = df_embrace_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(3, 41, 25)

### 00:50

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  30.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  24.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  48.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  36.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  30.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  24.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  48.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  36.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 30.0 + 0.395519* 24.0 + 0.136650* 48.0 + 0.259785* 36.0
   Value =   6.2414 +   9.4924 +   6.5592 +   9.3523
   Value = 31.645293

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 31.6453
============================================================

### 01:00

In [ ]:
embrace_tec.tec_map = np_embrace_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  28.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  25.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  42.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  36.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  28.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  25.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  42.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  36.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 28.0 + 0.395519* 25.0 + 0.136650* 42.0 + 0.259785* 36.0
   Value =   5.8253 +   9.8880 +   5.7393 +   9.3523
   Value = 30.804822

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 30.8048
============================================================

### 01:10

In [ ]:
embrace_tec.tec_map = np_embrace_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -24.0°,  -47.5°) - Indexes: [18, 17] - TEC:  30.0
   P2: ( -24.0°,  -45.0°) - Indexes: [18, 18] - TEC:  22.0
   P3: ( -22.0°,  -47.5°) - Indexes: [19, 17] - TEC:  33.0
   P4: ( -22.0°,  -45.0°) - Indexes: [19, 18] - TEC:  33.0

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -24.0° to  -22.0° (range:  2.0°)
   Longitude:  -47.5° to  -45.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -24.0°,  -47.5°) =  30.0
   f_01 (lat_min, lon_max) = ( -24.0°,  -45.0°) =  22.0
   f_10 (lat_max, lon_min) = ( -22.0°,  -47.5°) =  33.0
   f_11 (lat_max, lon_max) = ( -22.0°,  -45.0°) =  33.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -47.5)) / ( -45.0 - ( -47.5))
   t_x =   1.64 /  2.5 = 0.655304

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -24.0)) / ( -22.0 - ( -24.0))
   t_y =   0.79 /  2.0 = 0.396435

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.655304) * (1 - 0.396435) = 0.208046
   w_01 = t_x * (1 - t_y)       = 0.655304 * (1 - 0.396435)       = 0.395519
   w_10 = (1 - t_x) * t_y       = (1 - 0.655304) * 0.396435       = 0.136650
   w_11 = t_x * t_y             = 0.655304 * 0.396435             = 0.259785
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.208046* 30.0 + 0.395519* 22.0 + 0.136650* 33.0 + 0.259785* 33.0
   Value =   6.2414 +   8.7014 +   4.5094 +   8.5729
   Value = 28.025157

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 65.53% of the way from -47.5° to -45.0°
   In Y direction (latitude):  39.64% of the way from -24° to -22°

============================================================
FINAL RESULT: TEC = 28.0252
============================================================

## MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024['DATETIME'] = pd.to_datetime(df_maggia_maps_2024['DATETIME'])
df_maggia_maps_2024 = df_maggia_maps_2024.set_index('DATETIME')

In [ ]:
df_maggia_maps_2024.columns

Index(['TECMAP'], dtype='object')

In [ ]:
class Maggia(TecMap):

    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)

In [ ]:
maggia_tec = Maggia()
maggia_points = maggia_tec.find_nearest_points(lat=-23.20713, lon=-45.86174)

In [ ]:
maggia_points

[(-23.5, -46.0, 113, 128),
 (-23.5, -45.5, 113, 129),
 (-23.0, -46.0, 114, 128),
 (-23.0, -45.5, 114, 129)]

In [ ]:
date = '2024-09-27'
times = ['00:50:00', '01:00:00', '01:10:00']

timestamps = [f'{date} {time}' for time in times]

result = df_maggia_maps_2024.loc[timestamps]

In [ ]:
result

                                                                TECMAP
DATETIME
2024-09-27 00:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-27 01:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [48.62400055, 48.20500183, 47.78499985, ..., 19.22900009,
         18.24799919, 16.43799973],
        [48.70800018, 48.36100006, 48.0019989 , ..., 18.61000061,
         17.57699966, 16.23500061],
        [48.7120018 , 48.42399979, 48.11700058, ..., 17.99799919,
         16.95499992, 16.04000092]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [43.38299942, 43.10300064, 43.09799957, ..., 19.18000031,
         18.25300026, 17.1609993 ],
        [43.85400009, 43.58499908, 43.34700012, ..., 18.40399933,
         17.62000084, 16.44000053],
        [44.19599915, 43.94599915, 43.70500183, ..., 17.70899963,
         16.94099998, 15.69099998]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.6230011 , 41.29999924, 41.13800049, ..., 18.74399948,
         18.67399979, 18.62999916],
        [42.11100006, 41.79499817, 41.5340004 , ..., 18.92099953,
         18.80699921, 17.86199951],
        [42.46699905, 42.18199921, 41.9280014 , ..., 18.2670002 ,
         17.5340004 , 16.79299927]]])

In [ ]:
np_maggia_maps.shape

(3, 241, 221)

### 00:50

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  49.5
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  52.2
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  52.2
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  50.5

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  49.5
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  52.2
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  52.2
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  50.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 49.5 + 0.114551* 52.2 + 0.423771* 52.2 + 0.161969* 50.5
   Value =  14.8491 +   5.9744 +  22.1145 +   8.1866
   Value = 51.124541

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 51.1245
============================================================

### 01:00

In [ ]:
maggia_tec.tec_map = np_maggia_maps[1]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  48.0
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  48.2
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  50.4
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  52.6

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  48.0
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  48.2
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  50.4
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  52.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 48.0 + 0.114551* 48.2 + 0.423771* 50.4 + 0.161969* 52.6
   Value =  14.3779 +   5.5167 +  21.3708 +   8.5186
   Value = 49.783971

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 49.7840
============================================================

### 01:10

In [ ]:
maggia_tec.tec_map = np_maggia_maps[2]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -23.20713
target_lon = -45.86174

print(f"\n2. TARGET POINT: ({target_lat:+6.2f}°, {target_lon:+6.2f}°)")

values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]
f_01 = point_values[(lat_min, lon_max)]
f_10 = point_values[(lat_max, lon_min)]
f_11 = point_values[(lat_max, lon_max)]

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.2f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.2f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.2f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.2f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS - MAGGIA
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -23.5°,  -46.0°) - Indexes: [113, 128] - TEC:  46.6
   P2: ( -23.5°,  -45.5°) - Indexes: [113, 129] - TEC:  46.0
   P3: ( -23.0°,  -46.0°) - Indexes: [114, 128] - TEC:  49.2
   P4: ( -23.0°,  -45.5°) - Indexes: [114, 129] - TEC:  48.7

2. TARGET POINT: (-23.21°, -45.86°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -23.5° to  -23.0° (range:  0.5°)
   Longitude:  -46.0° to  -45.5° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -23.5°,  -46.0°) =  46.6
   f_01 (lat_min, lon_max) = ( -23.5°,  -45.5°) =  46.0
   f_10 (lat_max, lon_min) = ( -23.0°,  -46.0°) =  49.2
   f_11 (lat_max, lon_max) = ( -23.0°,  -45.5°) =  48.7

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-45.86 - ( -46.0)) / ( -45.5 - ( -46.0))
   t_x =   0.14 /  0.5 = 0.276520

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-23.21 - ( -23.5)) / ( -23.0 - ( -23.5))
   t_y =   0.29 /  0.5 = 0.585740

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.276520) * (1 - 0.585740) = 0.299709
   w_01 = t_x * (1 - t_y)       = 0.276520 * (1 - 0.585740)       = 0.114551
   w_10 = (1 - t_x) * t_y       = (1 - 0.276520) * 0.585740       = 0.423771
   w_11 = t_x * t_y             = 0.276520 * 0.585740             = 0.161969
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.299709* 46.6 + 0.114551* 46.0 + 0.423771* 49.2 + 0.161969* 48.7
   Value =  13.9775 +   5.2650 +  20.8377 +   7.8866
   Value = 47.966785

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 27.65% of the way from -46.0° to -45.5°
   In Y direction (latitude):  58.57% of the way from -23.5° to -23.0°

============================================================
FINAL RESULT: TEC = 47.9668
============================================================