# Gopi TEC Cuiabá analysis - December/2024

In [1]:
#Download Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [2]:
!gdown '1Z2edbft-w58JT3sqGHLxx2EGzxTPkZf3'

Downloading...
From (original): https://drive.google.com/uc?id=1Z2edbft-w58JT3sqGHLxx2EGzxTPkZf3
From (redirected): https://drive.google.com/uc?id=1Z2edbft-w58JT3sqGHLxx2EGzxTPkZf3&confirm=t&uuid=48c30851-fe4b-446d-9ae1-9537d3fdf2e7
To: /content/Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip
100% 52.5M/52.5M [00:00<00:00, 98.0MB/s]

In [3]:
%pwd

'/content'

In [4]:
!ls

Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip  sample_data

In [5]:
!unzip 'Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip'

Archive:  Gopi_TEC_CUIB_09_27_2024_and_Dec_2024.zip
  inflating: GPS_TEC Readme.pdf
  inflating: cuib271-2024-09-27.Std
  inflating: cuib336-2024-12-01.Std
  inflating: cuib337-2024-12-02.Std
  inflating: cuib338-2024-12-03.Std
  inflating: cuib339-2024-12-04.Std
  inflating: cuib340-2024-12-05.Std
  inflating: cuib341-2024-12-06.Std
  inflating: cuib342-2024-12-07.Std
  inflating: cuib343-2024-12-08.Std
  inflating: cuib344-2024-12-09.Std
  inflating: cuib345-2024-12-10.Std
  inflating: cuib346-2024-12-11.Std
  inflating: cuib347-2024-12-12.Std
  inflating: cuib348-2024-12-13.Std
  inflating: cuib349-2024-12-14.Std
  inflating: cuib350-2024-12-15.Std
  inflating: cuib351-2024-12-16.Std
  inflating: cuib352-2024-12-17.Std
  inflating: cuib353-2024-12-18.Std
  inflating: cuib354-2024-12-19.Std
  inflating: cuib355-2024-12-20.Std
  inflating: cuib356-2024-12-21.Std
  inflating: cuib357-2024-12-22.Std
  inflating: cuib358-2024-12-23.Std
  inflating: cuib359-2024-12-24.Std
  inflating: cuib360-2024-12-25.Std
  inflating: cuib361-2024-12-26.Std
  inflating: cuib362-2024-12-27.Std
  inflating: cuib363-2024-12-28.Std
  inflating: cuib364-2024-12-29.Std
  inflating: cuib365-2024-12-30.Std
  inflating: cuib366-2024-12-31.Std
  inflating: cuib271-2024-09-27_page0.png
  inflating: cuib271-2024-09-27-wbias.png
  inflating: cuib336-2024-12-01_page0.png
  inflating: cuib336-2024-12-01-wbias.png
  inflating: cuib337-2024-12-02_page0.png
  inflating: cuib337-2024-12-02-wbias.png
  inflating: cuib338-2024-12-03_page0.png
  inflating: cuib338-2024-12-03-wbias.png
  inflating: cuib339-2024-12-04_page0.png
  inflating: cuib339-2024-12-04-wbias.png
  inflating: cuib340-2024-12-05_page0.png
  inflating: cuib340-2024-12-05-wbias.png
  inflating: cuib341-2024-12-06_page0.png
  inflating: cuib341-2024-12-06-wbias.png
  inflating: cuib342-2024-12-07_page0.png
  inflating: cuib342-2024-12-07-wbias.png
  inflating: cuib343-2024-12-08_page0.png
  inflating: cuib343-2024-12-08-wbias.png
  inflating: cuib344-2024-12-09_page0.png
  inflating: cuib344-2024-12-09-wbias.png
  inflating: cuib345-2024-12-10_page0.png
  inflating: cuib345-2024-12-10-wbias.png
  inflating: cuib346-2024-12-11_page0.png
  inflating: cuib346-2024-12-11-wbias.png
  inflating: cuib347-2024-12-12_page0.png
  inflating: cuib347-2024-12-12-wbias.png
  inflating: cuib348-2024-12-13_page0.png
  inflating: cuib348-2024-12-13-wbias.png
  inflating: cuib349-2024-12-14_page0.png
  inflating: cuib349-2024-12-14-wbias.png
  inflating: cuib350-2024-12-15_page0.png
  inflating: cuib350-2024-12-15-wbias.png
  inflating: cuib351-2024-12-16_page0.png
  inflating: cuib351-2024-12-16-wbias.png
  inflating: cuib352-2024-12-17_page0.png
  inflating: cuib352-2024-12-17-wbias.png
  inflating: cuib353-2024-12-18_page0.png
  inflating: cuib353-2024-12-18-wbias.png
  inflating: cuib354-2024-12-19_page0.png
  inflating: cuib354-2024-12-19-wbias.png
  inflating: cuib355-2024-12-20_page0.png
  inflating: cuib355-2024-12-20-wbias.png
  inflating: cuib356-2024-12-21_page0.png
  inflating: cuib356-2024-12-21-wbias.png
  inflating: cuib357-2024-12-22_page0.png
  inflating: cuib357-2024-12-22-wbias.png
  inflating: cuib358-2024-12-23_page0.png
  inflating: cuib358-2024-12-23-wbias.png
  inflating: cuib359-2024-12-24_page0.png
  inflating: cuib359-2024-12-24-wbias.png
  inflating: cuib360-2024-12-25_page0.png
  inflating: cuib360-2024-12-25-wbias.png
  inflating: cuib361-2024-12-26_page0.png
  inflating: cuib361-2024-12-26-wbias.png
  inflating: cuib362-2024-12-27_page0.png
  inflating: cuib362-2024-12-27-wbias.png
  inflating: cuib363-2024-12-28_page0.png
  inflating: cuib363-2024-12-28-wbias.png
  inflating: cuib364-2024-12-29_page0.png
  inflating: cuib364-2024-12-29-wbias.png
  inflating: cuib365-2024-12-30_page0.png
  inflating: cuib365-2024-12-30-wbias.png
  inflating: cuib366-2024-12-31_page0.png
  inflating: cuib366-2024-12-31-wbias.png
  inflating: cuib271-2024-09-27.Bias
  inflating: cuib271-2024-09-27.Cmn
  inflating: cuib336-2024-12-01.Bias
  inflating: cuib336-2024-12-01.Cmn
  inflating: cuib337-2024-12-02.Bias
  inflating: cuib337-2024-12-02.Cmn
  inflating: cuib338-2024-12-03.Bias
  inflating: cuib338-2024-12-03.Cmn
  inflating: cuib339-2024-12-04.Bias
  inflating: cuib339-2024-12-04.Cmn
  inflating: cuib340-2024-12-05.Bias
  inflating: cuib340-2024-12-05.Cmn
  inflating: cuib341-2024-12-06.Bias
  inflating: cuib341-2024-12-06.Cmn
  inflating: cuib342-2024-12-07.Bias
  inflating: cuib342-2024-12-07.Cmn
  inflating: cuib343-2024-12-08.Bias
  inflating: cuib343-2024-12-08.Cmn
  inflating: cuib344-2024-12-09.Bias
  inflating: cuib344-2024-12-09.Cmn
  inflating: cuib345-2024-12-10.Bias
  inflating: cuib345-2024-12-10.Cmn
  inflating: cuib346-2024-12-11.Bias
  inflating: cuib346-2024-12-11.Cmn
  inflating: cuib347-2024-12-12.Bias
  inflating: cuib347-2024-12-12.Cmn
  inflating: cuib348-2024-12-13.Bias
  inflating: cuib348-2024-12-13.Cmn
  inflating: cuib349-2024-12-14.Bias
  inflating: cuib349-2024-12-14.Cmn
  inflating: cuib350-2024-12-15.Bias
  inflating: cuib350-2024-12-15.Cmn
  inflating: cuib351-2024-12-16.Bias
  inflating: cuib351-2024-12-16.Cmn
  inflating: cuib352-2024-12-17.Bias
  inflating: cuib352-2024-12-17.Cmn
  inflating: cuib353-2024-12-18.Bias
  inflating: cuib353-2024-12-18.Cmn
  inflating: cuib354-2024-12-19.Bias
  inflating: cuib354-2024-12-19.Cmn
  inflating: cuib355-2024-12-20.Bias
  inflating: cuib355-2024-12-20.Cmn
  inflating: cuib356-2024-12-21.Bias
  inflating: cuib356-2024-12-21.Cmn
  inflating: cuib357-2024-12-22.Bias
  inflating: cuib357-2024-12-22.Cmn
  inflating: cuib358-2024-12-23.Bias
  inflating: cuib358-2024-12-23.Cmn
  inflating: cuib359-2024-12-24.Bias
  inflating: cuib359-2024-12-24.Cmn
  inflating: cuib360-2024-12-25.Bias
  inflating: cuib360-2024-12-25.Cmn
  inflating: cuib361-2024-12-26.Bias
  inflating: cuib361-2024-12-26.Cmn
  inflating: cuib362-2024-12-27.Bias
  inflating: cuib362-2024-12-27.Cmn
  inflating: cuib363-2024-12-28.Bias
  inflating: cuib363-2024-12-28.Cmn
  inflating: cuib364-2024-12-29.Bias
  inflating: cuib364-2024-12-29.Cmn
  inflating: cuib365-2024-12-30.Bias
  inflating: cuib365-2024-12-30.Cmn
  inflating: cuib366-2024-12-31.Bias
  inflating: cuib366-2024-12-31.Cmn

In [6]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta
import glob

data_dir = '.'

std_files = glob.glob(os.path.join(data_dir, 'cuib3*-2024-12-*.Std'))

std_files.sort()

dfs = []

for file_path in std_files:
    try:

        filename = os.path.basename(file_path)
        print(f"Processing {filename}")

        date_parts = filename.replace('.Std', '').split('-')
        year = int(date_parts[1])
        month = int(date_parts[2])
        day = int(date_parts[3])
        base_date = datetime(year, month, day)

        df = pd.read_csv(file_path, sep='\s+', header=None)

        df.columns = ['time_ut', 'tec', 'tec_std', 'latitude']

        def decimal_to_time(decimal_hours):
            hours = int(decimal_hours)
            minutes = int((decimal_hours - hours) * 60)
            seconds = int(((decimal_hours - hours) * 60 - minutes) * 60)
            return base_date + timedelta(hours=hours, minutes=minutes, seconds=seconds)

        df['DATETIME'] = df['time_ut'].apply(decimal_to_time)

        df['tec'] = pd.to_numeric(df['tec'].replace('-', np.nan))
        df['tec_std'] = pd.to_numeric(df['tec_std'].replace('-', np.nan))

        df = df[['DATETIME', 'tec', 'tec_std', 'latitude']]
        df.columns = ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']

        dfs.append(df)

    except Exception as e:
        print(f"Erro ao processar o arquivo {file_path}: {e}")

if dfs:
    combined_df = pd.concat(dfs, ignore_index=True)

    combined_df = combined_df.sort_values('DATETIME')

    combined_df.to_pickle('cuib_dec_2024_complete.pkl')

    print(f"DataFrame combinado criado com {len(combined_df)} linhas")
    print("Primeiras 5 linhas:")
    print(combined_df.head())

    print("\nPeríodo coberto pelos dados:")
    print(f"Início: {combined_df['DATETIME'].min()}")
    print(f"Fim: {combined_df['DATETIME'].max()}")
    print(f"Total de dias: {(combined_df['DATETIME'].max() - combined_df['DATETIME'].min()).days + 1}")

    dias_presentes = combined_df['DATETIME'].dt.date.unique()
    print(f"\nTotal de dias com dados: {len(dias_presentes)}")
    print("Dias presentes:", sorted(dias_presentes))
else:
    print("Nenhum arquivo foi processado com sucesso.")

Processing cuib336-2024-12-01.Std
Processing cuib337-2024-12-02.Std
Processing cuib338-2024-12-03.Std
Processing cuib339-2024-12-04.Std
Processing cuib340-2024-12-05.Std
Processing cuib341-2024-12-06.Std
Processing cuib342-2024-12-07.Std
Processing cuib343-2024-12-08.Std
Processing cuib344-2024-12-09.Std
Processing cuib345-2024-12-10.Std
Processing cuib346-2024-12-11.Std
Processing cuib347-2024-12-12.Std
Processing cuib348-2024-12-13.Std
Processing cuib349-2024-12-14.Std
Processing cuib350-2024-12-15.Std
Processing cuib351-2024-12-16.Std
Processing cuib352-2024-12-17.Std
Processing cuib353-2024-12-18.Std
Processing cuib354-2024-12-19.Std
Processing cuib355-2024-12-20.Std
Processing cuib356-2024-12-21.Std
Processing cuib357-2024-12-22.Std
Processing cuib358-2024-12-23.Std
Processing cuib359-2024-12-24.Std
Processing cuib360-2024-12-25.Std
Processing cuib361-2024-12-26.Std
Processing cuib362-2024-12-27.Std
Processing cuib363-2024-12-28.Std
Processing cuib364-2024-12-29.Std
Processing cuib365-2024-12-30.Std
Processing cuib366-2024-12-31.Std
DataFrame combinado criado com 44640 linhas
Primeiras 5 linhas:
             DATETIME    TEC  TEC_STD  LATITUDE
0 2024-12-01 00:00:00  54.62    10.50    -15.56
1 2024-12-01 00:01:01  54.54    11.83    -15.56
2 2024-12-01 00:01:58  54.46    11.97    -15.56
3 2024-12-01 00:03:00  54.38    13.10    -15.56
4 2024-12-01 00:04:01  54.28    13.88    -15.56

Período coberto pelos dados:
Início: 2024-12-01 00:00:00
Fim: 2024-12-31 23:58:58
Total de dias: 31

Total de dias com dados: 31
Dias presentes: [datetime.date(2024, 12, 1), datetime.date(2024, 12, 2), datetime.date(2024, 12, 3), datetime.date(2024, 12, 4), datetime.date(2024, 12, 5), datetime.date(2024, 12, 6), datetime.date(2024, 12, 7), datetime.date(2024, 12, 8), datetime.date(2024, 12, 9), datetime.date(2024, 12, 10), datetime.date(2024, 12, 11), datetime.date(2024, 12, 12), datetime.date(2024, 12, 13), datetime.date(2024, 12, 14), datetime.date(2024, 12, 15), datetime.date(2024, 12, 16), datetime.date(2024, 12, 17), datetime.date(2024, 12, 18), datetime.date(2024, 12, 19), datetime.date(2024, 12, 20), datetime.date(2024, 12, 21), datetime.date(2024, 12, 22), datetime.date(2024, 12, 23), datetime.date(2024, 12, 24), datetime.date(2024, 12, 25), datetime.date(2024, 12, 26), datetime.date(2024, 12, 27), datetime.date(2024, 12, 28), datetime.date(2024, 12, 29), datetime.date(2024, 12, 30), datetime.date(2024, 12, 31)]

In [7]:
combined_df

                 DATETIME    TEC  TEC_STD  LATITUDE
0     2024-12-01 00:00:00  54.62    10.50    -15.56
1     2024-12-01 00:01:01  54.54    11.83    -15.56
2     2024-12-01 00:01:58  54.46    11.97    -15.56
3     2024-12-01 00:03:00  54.38    13.10    -15.56
4     2024-12-01 00:04:01  54.28    13.88    -15.56
...                   ...    ...      ...       ...
44635 2024-12-31 23:55:01  49.15     5.52    -15.56
44636 2024-12-31 23:55:58  49.15     5.47    -15.56
44637 2024-12-31 23:56:59  49.15     5.68    -15.56
44638 2024-12-31 23:58:01  49.16     5.90    -15.56
44639 2024-12-31 23:58:58  49.16     5.73    -15.56

[44640 rows x 4 columns]

## 18:00

In [8]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('cuib_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_PEAKS_at_precise_interval(hour_start, minute_start, second_start, hour_end, minute_end, second_end):

    interval_label = f"{hour_start:02d}:{minute_start:02d}:{second_start:02d}-{hour_end:02d}:{minute_end:02d}:{second_end:02d}"

    print(f"\n{'='*80}")
    print(f"ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE {interval_label} UTC")
    print(f"{'='*80}")

    start_timestamps = []
    end_timestamps = []

    for day in df_clean['DATETIME'].dt.date.unique():
        start_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_start, minute_start, second_start))
        end_timestamps.append(pd.Timestamp(day.year, day.month, day.day, hour_end, minute_end, second_end))

    df_interval = pd.DataFrame()
    for start, end in zip(start_timestamps, end_timestamps):
        day_interval = df_clean[(df_clean['DATETIME'] >= start) & (df_clean['DATETIME'] <= end)]
        df_interval = pd.concat([df_interval, day_interval])

    print(f"Filtering for times between {interval_label} UTC: {len(df_interval)} remaining points")

    if len(df_interval) == 0:
        print(f"ATTENTION: No data found in the range {interval_label} UTC!")
        return pd.DataFrame(), []

    df_interval['DATE'] = df_interval['DATETIME'].dt.date

    daily_max = df_interval.loc[df_interval.groupby('DATE')['TEC'].idxmax()]
    print(f"Unique days with data in range {interval_label}: {len(daily_max)}")

    if len(daily_max) >= 5:
        top_5_days = daily_max.nlargest(5, 'TEC').reset_index(drop=True)
    else:
        top_5_days = daily_max.sort_values('TEC', ascending=False).reset_index(drop=True)
        print(f"ATTENTION: Only {len(top_5_days)} days have data in this time range!")

    print(f"\n{len(top_5_days)} HIGHEST TEC VALUES IN THE INTERVAL {interval_label} (ONE PER DAY):")
    for idx, row in top_5_days.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_5_days.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_5_days) > 0:
        print(f"\nSUMMARY TABLE OF TEC PEAKS IN THE INTERVAL {interval_label} UTC:")
        print("-" * 100)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<12}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration'}")
        print("-" * 100)

        for idx, row in top_5_days.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M:%S'):<12}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration}")
        print("-" * 100)

    return top_5_days, sequences

def analyze_PEAKS_at_interval(hour_start, minute_start, hour_end, minute_end):

    return analyze_PEAKS_at_precise_interval(hour_start, minute_start, 0, hour_end, minute_end, 0)

print("\n\n" + "*"*40 + " ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC " + "*"*40)
top_5_exact_18h, sequences_exact_18h = analyze_PEAKS_at_precise_interval(17, 59, 55, 18, 0, 5)

print("\nAnálise concluída!")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Analysing 44609 points after removing missing values


**************************************** ANALYSIS OF THE EXACT RANGE 17:59:00-18:01:00 UTC ****************************************

================================================================================
ANALYSIS OF TEC PEAKS IN THE PRECISE RANGE 17:59:55-18:00:05 UTC
================================================================================
Filtering for times between 17:59:55-18:00:05 UTC: 31 remaining points
Unique days with data in range 17:59:55-18:00:05: 31

5 HIGHEST TEC VALUES IN THE INTERVAL 17:59:55-18:00:05 (ONE PER DAY):
1. TEC: 80.30 ± 1.72 TECU, Date/Time: 2024-12-16 18:00:00, Latitude: -15.56
2. TEC: 79.97 ± 4.64 TECU, Date/Time: 2024-12-02 18:00:00, Latitude: -15.56
3. TEC: 75.21 ± 2.25 TECU, Date/Time: 2024-12-29 18:00:00, Latitude: -15.56
4. TEC: 75.19 ± 4.27 TECU, Date/Time: 2024-12-22 18:00:00, Latitude: -15.56
5. TEC: 75.03 ± 4.50 TECU, Date/Time: 2024-12-31 18:00:00, Latitude: -15.56

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 80.30 ± 1.72) has a sequence of 3 high values:
  1. 2024-12-16 17:58:58: 80.25 ± 1.59 TECU (99.9% do Peak)
  2. 2024-12-16 18:00:00: 80.30 ± 1.72 TECU (100.0% do Peak)
  3. 2024-12-16 18:01:01: 80.35 ± 1.81 TECU (100.1% do Peak)

Peak #2 (TEC = 79.97 ± 4.64) has a sequence of 3 high values:
  1. 2024-12-02 17:58:58: 79.84 ± 4.57 TECU (99.8% do Peak)
  2. 2024-12-02 18:00:00: 79.97 ± 4.64 TECU (100.0% do Peak)
  3. 2024-12-02 18:01:01: 80.09 ± 4.77 TECU (100.2% do Peak)

Peak #3 (TEC = 75.21 ± 2.25) has a sequence of 3 high values:
  1. 2024-12-29 17:58:58: 75.21 ± 2.35 TECU (100.0% do Peak)
  2. 2024-12-29 18:00:00: 75.21 ± 2.25 TECU (100.0% do Peak)
  3. 2024-12-29 18:01:01: 75.22 ± 2.36 TECU (100.0% do Peak)

Peak #4 (TEC = 75.19 ± 4.27) has a sequence of 3 high values:
  1. 2024-12-22 17:58:58: 75.20 ± 4.10 TECU (100.0% do Peak)
  2. 2024-12-22 18:00:00: 75.19 ± 4.27 TECU (100.0% do Peak)
  3. 2024-12-22 18:01:01: 75.19 ± 4.13 TECU (100.0% do Peak)

Peak #5 (TEC = 75.03 ± 4.50) has a sequence of 3 high values:
  1. 2024-12-31 17:58:58: 74.94 ± 4.41 TECU (99.9% do Peak)
  2. 2024-12-31 18:00:00: 75.03 ± 4.50 TECU (100.0% do Peak)
  3. 2024-12-31 18:01:01: 75.13 ± 4.57 TECU (100.1% do Peak)

SUMMARY TABLE OF TEC PEAKS IN THE INTERVAL 17:59:55-18:00:05 UTC:
----------------------------------------------------------------------------------------------------
Rank Data        UTC time    TEC       TEC_STD   Sequence       Sequence Duration
----------------------------------------------------------------------------------------------------
1    16/12/2024  18:00:00    80.30    1.72    Sim            2.0 min
2    02/12/2024  18:00:00    79.97    4.64    Sim            2.0 min
3    29/12/2024  18:00:00    75.21    2.25    Sim            2.0 min
4    22/12/2024  18:00:00    75.19    4.27    Sim            2.0 min
5    31/12/2024  18:00:00    75.03    4.50    Sim            2.0 min
----------------------------------------------------------------------------------------------------

Análise concluída!

## DECEMBER

In [9]:
import pandas as pd
import numpy as np
from datetime import timedelta, time

df = pd.read_pickle('cuib_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):

    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]

    peak_value = df.loc[peak_idx, 'TEC']

    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def analyze_top_PEAKS(top_n=200):

    print(f"\n{'='*80}")
    print(f"TOP {top_n} PEAK ANALYSIS OF TEC (ALL TIMES)")
    print(f"{'='*80}")

    df_clean['DATE'] = df_clean['DATETIME'].dt.date

    top_n_PEAKS = df_clean.nlargest(top_n, 'TEC').reset_index(drop=True)

    print(f"\nTOP {top_n} HIGHEST VALUES OF TEC (ALL TIMES):")
    for idx, row in top_n_PEAKS.iterrows():
        print(f"{idx+1}. TEC: {row['TEC']:.2f} ± {row['TEC_STD']:.2f} TECU, "
              f"Date/Time: {row['DATETIME']}, Latitude: {row['LATITUDE']}")

    print(f"\nSEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):")
    sequences = []

    for idx, row in top_n_PEAKS.iterrows():

        sequence = check_consecutive_highs(df_clean, row['DATETIME'], threshold_percent=90)

        if sequence:
            sequences.append({
                'peak_rank': idx + 1,
                'peak_value': row['TEC'],
                'peak_std': row['TEC_STD'],
                'peak_datetime': row['DATETIME'],
                'sequence': sequence
            })

            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) has a sequence of 3 high values:")
            for i, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                print(f"  {i+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/row['TEC']*100:.1f}% do Peak)")
        else:
            print(f"\nPeak #{idx+1} (TEC = {row['TEC']:.2f} ± {row['TEC_STD']:.2f}) "
                  f"There is NO sequence of 3 high values ​​above 90% of the peak")

    if len(top_n_PEAKS) > 0:
        print(f"\nSUMMARY TABLE OF TOP {top_n} TEC PEAKS:")
        print("-" * 110)
        print(f"{'Rank':<5}{'Data':<12}{'UTC time':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequence':<15}{'Sequence Duration':<20}{'Horário do dia'}")
        print("-" * 110)

        for idx, row in top_n_PEAKS.iterrows():
            has_sequence = any(seq['peak_datetime'] == row['DATETIME'] for seq in sequences)
            sequence_info = "Sim" if has_sequence else "Não"

            duration = ""
            if has_sequence:
                for seq in sequences:
                    if seq['peak_datetime'] == row['DATETIME']:
                        first_dt = min(seq['sequence']['datetimes'])
                        last_dt = max(seq['sequence']['datetimes'])
                        duration = f"{(last_dt - first_dt).total_seconds() / 60:.1f} min"
                        break

            hour = row['DATETIME'].hour
            minute = row['DATETIME'].minute
            time_category = f"{hour:02d}:{minute:02d} UTC"

            print(f"{idx+1:<5}{row['DATETIME'].strftime('%d/%m/%Y'):<12}{row['DATETIME'].strftime('%H:%M'):<10}"
                  f"{row['TEC']:.2f}    {row['TEC_STD']:.2f}    {sequence_info:<15}{duration:<20}{time_category}")
        print("-" * 110)

    return top_n_PEAKS, sequences

print("\n\n" + "*"*40 + "TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) " + "*"*40)
top_n_PEAKS, sequences = analyze_top_PEAKS(top_n=200)

print("\nAnálise concluída!")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Analysing 44609 points after removing missing values


****************************************TOP ANALYSIS - 200 PEAKS OF TEC (ALL TIMES) ****************************************

================================================================================
TOP 200 PEAK ANALYSIS OF TEC (ALL TIMES)
================================================================================

TOP 200 HIGHEST VALUES OF TEC (ALL TIMES):
1. TEC: 83.50 ± 3.10 TECU, Date/Time: 2024-12-02 18:58:58, Latitude: -15.56
2. TEC: 83.50 ± 3.10 TECU, Date/Time: 2024-12-02 19:00:00, Latitude: -15.56
3. TEC: 83.50 ± 3.10 TECU, Date/Time: 2024-12-02 19:01:01, Latitude: -15.56
4. TEC: 83.50 ± 3.11 TECU, Date/Time: 2024-12-02 19:01:58, Latitude: -15.56
5. TEC: 83.50 ± 3.12 TECU, Date/Time: 2024-12-02 19:03:00, Latitude: -15.56
6. TEC: 83.49 ± 3.11 TECU, Date/Time: 2024-12-02 18:56:59, Latitude: -15.56
7. TEC: 83.49 ± 3.09 TECU, Date/Time: 2024-12-02 18:58:01, Latitude: -15.56
8. TEC: 83.49 ± 3.13 TECU, Date/Time: 2024-12-02 19:04:01, Latitude: -15.56
9. TEC: 83.49 ± 3.14 TECU, Date/Time: 2024-12-02 19:04:58, Latitude: -15.56
10. TEC: 83.48 ± 3.12 TECU, Date/Time: 2024-12-02 18:55:58, Latitude: -15.56
11. TEC: 83.48 ± 3.13 TECU, Date/Time: 2024-12-02 19:06:00, Latitude: -15.56
12. TEC: 83.47 ± 2.89 TECU, Date/Time: 2024-12-02 18:55:01, Latitude: -15.56
13. TEC: 83.47 ± 3.14 TECU, Date/Time: 2024-12-02 19:07:01, Latitude: -15.56
14. TEC: 83.46 ± 2.19 TECU, Date/Time: 2024-12-02 18:53:59, Latitude: -15.56
15. TEC: 83.46 ± 3.16 TECU, Date/Time: 2024-12-02 19:07:58, Latitude: -15.56
16. TEC: 83.45 ± 2.13 TECU, Date/Time: 2024-12-02 18:52:58, Latitude: -15.56
17. TEC: 83.44 ± 2.08 TECU, Date/Time: 2024-12-02 18:52:01, Latitude: -15.56
18. TEC: 83.44 ± 3.37 TECU, Date/Time: 2024-12-02 19:08:59, Latitude: -15.56
19. TEC: 83.43 ± 3.67 TECU, Date/Time: 2024-12-02 19:10:01, Latitude: -15.56
20. TEC: 83.42 ± 2.04 TECU, Date/Time: 2024-12-02 18:51:00, Latitude: -15.56
21. TEC: 83.41 ± 3.68 TECU, Date/Time: 2024-12-02 19:10:58, Latitude: -15.56
22. TEC: 83.40 ± 2.00 TECU, Date/Time: 2024-12-02 18:49:58, Latitude: -15.56
23. TEC: 83.39 ± 1.97 TECU, Date/Time: 2024-12-02 18:49:01, Latitude: -15.56
24. TEC: 83.39 ± 3.70 TECU, Date/Time: 2024-12-02 19:11:59, Latitude: -15.56
25. TEC: 83.37 ± 1.88 TECU, Date/Time: 2024-12-02 18:48:00, Latitude: -15.56
26. TEC: 83.36 ± 3.70 TECU, Date/Time: 2024-12-02 19:13:01, Latitude: -15.56
27. TEC: 83.34 ± 1.93 TECU, Date/Time: 2024-12-02 18:46:58, Latitude: -15.56
28. TEC: 83.34 ± 3.71 TECU, Date/Time: 2024-12-02 19:13:58, Latitude: -15.56
29. TEC: 83.32 ± 1.88 TECU, Date/Time: 2024-12-02 18:46:01, Latitude: -15.56
30. TEC: 83.30 ± 1.85 TECU, Date/Time: 2024-12-02 18:45:00, Latitude: -15.56
31. TEC: 83.30 ± 3.73 TECU, Date/Time: 2024-12-02 19:15:00, Latitude: -15.56
32. TEC: 83.27 ± 1.87 TECU, Date/Time: 2024-12-02 18:43:58, Latitude: -15.56
33. TEC: 83.27 ± 3.75 TECU, Date/Time: 2024-12-02 19:16:01, Latitude: -15.56
34. TEC: 83.24 ± 1.79 TECU, Date/Time: 2024-12-02 18:43:01, Latitude: -15.56
35. TEC: 83.23 ± 3.77 TECU, Date/Time: 2024-12-02 19:16:58, Latitude: -15.56
36. TEC: 83.21 ± 1.77 TECU, Date/Time: 2024-12-02 18:41:59, Latitude: -15.56
37. TEC: 83.19 ± 3.78 TECU, Date/Time: 2024-12-02 19:18:00, Latitude: -15.56
38. TEC: 83.18 ± 1.75 TECU, Date/Time: 2024-12-02 18:40:58, Latitude: -15.56
39. TEC: 83.15 ± 1.65 TECU, Date/Time: 2024-12-02 18:40:01, Latitude: -15.56
40. TEC: 83.15 ± 3.81 TECU, Date/Time: 2024-12-02 19:19:01, Latitude: -15.56
41. TEC: 83.11 ± 1.65 TECU, Date/Time: 2024-12-02 18:38:59, Latitude: -15.56
42. TEC: 83.10 ± 3.44 TECU, Date/Time: 2024-12-02 19:19:58, Latitude: -15.56
43. TEC: 83.08 ± 1.60 TECU, Date/Time: 2024-12-02 18:37:58, Latitude: -15.56
44. TEC: 83.05 ± 3.84 TECU, Date/Time: 2024-12-02 19:21:00, Latitude: -15.56
45. TEC: 83.04 ± 1.55 TECU, Date/Time: 2024-12-02 18:37:01, Latitude: -15.56
46. TEC: 83.00 ± 3.66 TECU, Date/Time: 2024-12-02 19:22:01, Latitude: -15.56
47. TEC: 82.99 ± 1.50 TECU, Date/Time: 2024-12-02 18:36:00, Latitude: -15.56
48. TEC: 82.95 ± 1.47 TECU, Date/Time: 2024-12-02 18:34:58, Latitude: -15.56
49. TEC: 82.94 ± 3.41 TECU, Date/Time: 2024-12-02 19:22:58, Latitude: -15.56
50. TEC: 82.91 ± 1.44 TECU, Date/Time: 2024-12-02 18:34:01, Latitude: -15.56
51. TEC: 82.88 ± 3.99 TECU, Date/Time: 2024-12-02 19:23:59, Latitude: -15.56
52. TEC: 82.86 ± 1.41 TECU, Date/Time: 2024-12-02 18:33:00, Latitude: -15.56
53. TEC: 82.81 ± 1.39 TECU, Date/Time: 2024-12-02 18:31:58, Latitude: -15.56
54. TEC: 82.81 ± 3.78 TECU, Date/Time: 2024-12-02 19:25:01, Latitude: -15.56
55. TEC: 82.76 ± 1.37 TECU, Date/Time: 2024-12-02 18:31:01, Latitude: -15.56
56. TEC: 82.74 ± 3.49 TECU, Date/Time: 2024-12-02 19:25:58, Latitude: -15.56
57. TEC: 82.70 ± 1.34 TECU, Date/Time: 2024-12-02 18:30:00, Latitude: -15.56
58. TEC: 82.67 ± 4.13 TECU, Date/Time: 2024-12-02 19:26:59, Latitude: -15.56
59. TEC: 82.65 ± 1.29 TECU, Date/Time: 2024-12-02 18:28:58, Latitude: -15.56
60. TEC: 82.59 ± 1.25 TECU, Date/Time: 2024-12-02 18:28:01, Latitude: -15.56
61. TEC: 82.59 ± 3.94 TECU, Date/Time: 2024-12-02 19:28:01, Latitude: -15.56
62. TEC: 82.53 ± 1.23 TECU, Date/Time: 2024-12-02 18:26:59, Latitude: -15.56
63. TEC: 82.51 ± 3.99 TECU, Date/Time: 2024-12-02 19:28:58, Latitude: -15.56
64. TEC: 82.46 ± 1.21 TECU, Date/Time: 2024-12-02 18:25:58, Latitude: -15.56
65. TEC: 82.43 ± 1.87 TECU, Date/Time: 2024-12-02 19:30:00, Latitude: -15.56
66. TEC: 82.40 ± 1.21 TECU, Date/Time: 2024-12-02 18:25:01, Latitude: -15.56
67. TEC: 82.34 ± 1.94 TECU, Date/Time: 2024-12-02 19:31:01, Latitude: -15.56
68. TEC: 82.33 ± 1.22 TECU, Date/Time: 2024-12-02 18:23:59, Latitude: -15.56
69. TEC: 82.26 ± 1.23 TECU, Date/Time: 2024-12-02 18:22:58, Latitude: -15.56
70. TEC: 82.25 ± 1.82 TECU, Date/Time: 2024-12-02 19:31:58, Latitude: -15.56
71. TEC: 82.19 ± 1.24 TECU, Date/Time: 2024-12-02 18:22:01, Latitude: -15.56
72. TEC: 82.16 ± 1.82 TECU, Date/Time: 2024-12-02 19:33:00, Latitude: -15.56
73. TEC: 82.12 ± 1.26 TECU, Date/Time: 2024-12-02 18:21:00, Latitude: -15.56
74. TEC: 82.06 ± 1.95 TECU, Date/Time: 2024-12-02 19:34:01, Latitude: -15.56
75. TEC: 82.04 ± 1.28 TECU, Date/Time: 2024-12-02 18:19:58, Latitude: -15.56
76. TEC: 81.96 ± 1.31 TECU, Date/Time: 2024-12-02 18:19:01, Latitude: -15.56
77. TEC: 81.96 ± 1.96 TECU, Date/Time: 2024-12-02 19:34:58, Latitude: -15.56
78. TEC: 81.88 ± 1.35 TECU, Date/Time: 2024-12-02 18:18:00, Latitude: -15.56
79. TEC: 81.86 ± 1.80 TECU, Date/Time: 2024-12-02 19:36:00, Latitude: -15.56
80. TEC: 81.79 ± 1.39 TECU, Date/Time: 2024-12-02 18:16:58, Latitude: -15.56
81. TEC: 81.75 ± 1.89 TECU, Date/Time: 2024-12-02 19:37:01, Latitude: -15.56
82. TEC: 81.70 ± 1.45 TECU, Date/Time: 2024-12-02 18:16:01, Latitude: -15.56
83. TEC: 81.65 ± 1.73 TECU, Date/Time: 2024-12-02 19:37:58, Latitude: -15.56
84. TEC: 81.61 ± 1.51 TECU, Date/Time: 2024-12-02 18:15:00, Latitude: -15.56
85. TEC: 81.54 ± 1.65 TECU, Date/Time: 2024-12-02 19:38:59, Latitude: -15.56
86. TEC: 81.52 ± 1.55 TECU, Date/Time: 2024-12-02 18:13:58, Latitude: -15.56
87. TEC: 81.43 ± 1.66 TECU, Date/Time: 2024-12-02 19:40:01, Latitude: -15.56
88. TEC: 81.43 ± 0.92 TECU, Date/Time: 2024-12-16 18:37:58, Latitude: -15.56
89. TEC: 81.43 ± 0.98 TECU, Date/Time: 2024-12-16 18:38:59, Latitude: -15.56
90. TEC: 81.43 ± 1.08 TECU, Date/Time: 2024-12-16 18:40:01, Latitude: -15.56
91. TEC: 81.43 ± 1.11 TECU, Date/Time: 2024-12-16 18:40:58, Latitude: -15.56
92. TEC: 81.42 ± 1.57 TECU, Date/Time: 2024-12-02 18:13:01, Latitude: -15.56
93. TEC: 81.42 ± 0.92 TECU, Date/Time: 2024-12-16 18:36:00, Latitude: -15.56
94. TEC: 81.42 ± 0.99 TECU, Date/Time: 2024-12-16 18:37:01, Latitude: -15.56
95. TEC: 81.42 ± 1.24 TECU, Date/Time: 2024-12-16 18:41:59, Latitude: -15.56
96. TEC: 81.41 ± 0.91 TECU, Date/Time: 2024-12-16 18:34:58, Latitude: -15.56
97. TEC: 81.41 ± 1.27 TECU, Date/Time: 2024-12-16 18:43:01, Latitude: -15.56
98. TEC: 81.40 ± 1.34 TECU, Date/Time: 2024-12-16 18:43:58, Latitude: -15.56
99. TEC: 81.39 ± 1.94 TECU, Date/Time: 2024-12-16 18:34:01, Latitude: -15.56
100. TEC: 81.38 ± 2.26 TECU, Date/Time: 2024-12-16 18:33:00, Latitude: -15.56
101. TEC: 81.38 ± 1.36 TECU, Date/Time: 2024-12-16 18:45:00, Latitude: -15.56
102. TEC: 81.36 ± 2.62 TECU, Date/Time: 2024-12-16 18:31:58, Latitude: -15.56
103. TEC: 81.36 ± 1.45 TECU, Date/Time: 2024-12-16 18:46:01, Latitude: -15.56
104. TEC: 81.34 ± 2.15 TECU, Date/Time: 2024-12-16 18:31:01, Latitude: -15.56
105. TEC: 81.33 ± 1.50 TECU, Date/Time: 2024-12-16 18:46:58, Latitude: -15.56
106. TEC: 81.32 ± 1.60 TECU, Date/Time: 2024-12-02 18:11:59, Latitude: -15.56
107. TEC: 81.32 ± 1.59 TECU, Date/Time: 2024-12-02 19:40:58, Latitude: -15.56
108. TEC: 81.32 ± 2.55 TECU, Date/Time: 2024-12-16 18:30:00, Latitude: -15.56
109. TEC: 81.30 ± 2.09 TECU, Date/Time: 2024-12-16 18:28:58, Latitude: -15.56
110. TEC: 81.30 ± 1.55 TECU, Date/Time: 2024-12-16 18:48:00, Latitude: -15.56
111. TEC: 81.28 ± 2.29 TECU, Date/Time: 2024-12-16 18:28:01, Latitude: -15.56
112. TEC: 81.26 ± 2.25 TECU, Date/Time: 2024-12-16 18:26:59, Latitude: -15.56
113. TEC: 81.26 ± 1.59 TECU, Date/Time: 2024-12-16 18:49:01, Latitude: -15.56
114. TEC: 81.23 ± 2.39 TECU, Date/Time: 2024-12-16 18:25:58, Latitude: -15.56
115. TEC: 81.22 ± 1.62 TECU, Date/Time: 2024-12-02 18:10:58, Latitude: -15.56
116. TEC: 81.22 ± 1.68 TECU, Date/Time: 2024-12-16 18:49:58, Latitude: -15.56
117. TEC: 81.21 ± 1.49 TECU, Date/Time: 2024-12-02 19:41:59, Latitude: -15.56
118. TEC: 81.21 ± 1.96 TECU, Date/Time: 2024-12-16 18:25:01, Latitude: -15.56
119. TEC: 81.18 ± 2.31 TECU, Date/Time: 2024-12-16 18:23:59, Latitude: -15.56
120. TEC: 81.18 ± 1.67 TECU, Date/Time: 2024-12-16 18:51:00, Latitude: -15.56
121. TEC: 81.15 ± 1.89 TECU, Date/Time: 2024-12-16 18:22:58, Latitude: -15.56
122. TEC: 81.13 ± 1.73 TECU, Date/Time: 2024-12-16 18:52:01, Latitude: -15.56
123. TEC: 81.12 ± 1.62 TECU, Date/Time: 2024-12-02 18:10:01, Latitude: -15.56
124. TEC: 81.12 ± 2.21 TECU, Date/Time: 2024-12-16 18:22:01, Latitude: -15.56
125. TEC: 81.09 ± 1.45 TECU, Date/Time: 2024-12-02 19:43:01, Latitude: -15.56
126. TEC: 81.09 ± 2.24 TECU, Date/Time: 2024-12-16 18:21:00, Latitude: -15.56
127. TEC: 81.08 ± 1.74 TECU, Date/Time: 2024-12-16 18:52:58, Latitude: -15.56
128. TEC: 81.06 ± 2.21 TECU, Date/Time: 2024-12-16 18:19:58, Latitude: -15.56
129. TEC: 81.03 ± 2.19 TECU, Date/Time: 2024-12-16 18:19:01, Latitude: -15.56
130. TEC: 81.02 ± 1.62 TECU, Date/Time: 2024-12-02 18:08:59, Latitude: -15.56
131. TEC: 81.02 ± 1.85 TECU, Date/Time: 2024-12-16 18:53:59, Latitude: -15.56
132. TEC: 81.00 ± 2.34 TECU, Date/Time: 2024-12-16 18:18:00, Latitude: -15.56
133. TEC: 80.98 ± 1.41 TECU, Date/Time: 2024-12-02 19:43:58, Latitude: -15.56
134. TEC: 80.97 ± 1.94 TECU, Date/Time: 2024-12-16 18:16:58, Latitude: -15.56
135. TEC: 80.95 ± 1.91 TECU, Date/Time: 2024-12-16 18:55:01, Latitude: -15.56
136. TEC: 80.94 ± 2.12 TECU, Date/Time: 2024-12-16 18:16:01, Latitude: -15.56
137. TEC: 80.91 ± 1.63 TECU, Date/Time: 2024-12-02 18:07:58, Latitude: -15.56
138. TEC: 80.91 ± 2.10 TECU, Date/Time: 2024-12-16 18:15:00, Latitude: -15.56
139. TEC: 80.89 ± 1.98 TECU, Date/Time: 2024-12-16 18:55:58, Latitude: -15.56
140. TEC: 80.87 ± 2.07 TECU, Date/Time: 2024-12-16 18:13:58, Latitude: -15.56
141. TEC: 80.86 ± 1.32 TECU, Date/Time: 2024-12-02 19:45:00, Latitude: -15.56
142. TEC: 80.84 ± 2.04 TECU, Date/Time: 2024-12-16 18:13:01, Latitude: -15.56
143. TEC: 80.81 ± 2.04 TECU, Date/Time: 2024-12-16 18:56:59, Latitude: -15.56
144. TEC: 80.80 ± 1.67 TECU, Date/Time: 2024-12-02 18:07:01, Latitude: -15.56
145. TEC: 80.80 ± 2.17 TECU, Date/Time: 2024-12-16 18:11:59, Latitude: -15.56
146. TEC: 80.77 ± 2.03 TECU, Date/Time: 2024-12-16 18:10:58, Latitude: -15.56
147. TEC: 80.74 ± 1.22 TECU, Date/Time: 2024-12-02 19:46:01, Latitude: -15.56
148. TEC: 80.73 ± 2.20 TECU, Date/Time: 2024-12-16 18:10:01, Latitude: -15.56
149. TEC: 80.73 ± 2.11 TECU, Date/Time: 2024-12-16 18:58:01, Latitude: -15.56
150. TEC: 80.69 ± 2.16 TECU, Date/Time: 2024-12-16 18:08:59, Latitude: -15.56
151. TEC: 80.68 ± 4.31 TECU, Date/Time: 2024-12-02 18:06:00, Latitude: -15.56
152. TEC: 80.66 ± 2.11 TECU, Date/Time: 2024-12-16 18:07:58, Latitude: -15.56
153. TEC: 80.65 ± 2.19 TECU, Date/Time: 2024-12-16 18:58:58, Latitude: -15.56
154. TEC: 80.63 ± 1.25 TECU, Date/Time: 2024-12-02 19:46:58, Latitude: -15.56
155. TEC: 80.62 ± 2.06 TECU, Date/Time: 2024-12-16 18:07:01, Latitude: -15.56
156. TEC: 80.58 ± 2.12 TECU, Date/Time: 2024-12-16 18:06:00, Latitude: -15.56
157. TEC: 80.57 ± 5.09 TECU, Date/Time: 2024-12-02 18:04:58, Latitude: -15.56
158. TEC: 80.56 ± 2.26 TECU, Date/Time: 2024-12-16 19:00:00, Latitude: -15.56
159. TEC: 80.53 ± 1.81 TECU, Date/Time: 2024-12-16 18:04:58, Latitude: -15.56
160. TEC: 80.51 ± 1.27 TECU, Date/Time: 2024-12-02 19:48:00, Latitude: -15.56
161. TEC: 80.49 ± 1.91 TECU, Date/Time: 2024-12-16 18:04:01, Latitude: -15.56
162. TEC: 80.46 ± 2.34 TECU, Date/Time: 2024-12-16 19:01:01, Latitude: -15.56
163. TEC: 80.45 ± 5.01 TECU, Date/Time: 2024-12-02 18:04:01, Latitude: -15.56
164. TEC: 80.45 ± 1.86 TECU, Date/Time: 2024-12-16 18:03:00, Latitude: -15.56
165. TEC: 80.40 ± 1.81 TECU, Date/Time: 2024-12-16 18:01:58, Latitude: -15.56
166. TEC: 80.39 ± 1.28 TECU, Date/Time: 2024-12-02 19:49:01, Latitude: -15.56
167. TEC: 80.36 ± 2.49 TECU, Date/Time: 2024-12-16 19:01:58, Latitude: -15.56
168. TEC: 80.35 ± 1.81 TECU, Date/Time: 2024-12-16 18:01:01, Latitude: -15.56
169. TEC: 80.33 ± 4.92 TECU, Date/Time: 2024-12-02 18:03:00, Latitude: -15.56
170. TEC: 80.30 ± 1.72 TECU, Date/Time: 2024-12-16 18:00:00, Latitude: -15.56
171. TEC: 80.27 ± 1.37 TECU, Date/Time: 2024-12-02 19:49:58, Latitude: -15.56
172. TEC: 80.25 ± 1.59 TECU, Date/Time: 2024-12-16 17:58:58, Latitude: -15.56
173. TEC: 80.25 ± 2.64 TECU, Date/Time: 2024-12-16 19:03:00, Latitude: -15.56
174. TEC: 80.21 ± 4.83 TECU, Date/Time: 2024-12-02 18:01:58, Latitude: -15.56
175. TEC: 80.20 ± 1.62 TECU, Date/Time: 2024-12-16 17:58:01, Latitude: -15.56
176. TEC: 80.16 ± 1.30 TECU, Date/Time: 2024-12-02 19:51:00, Latitude: -15.56
177. TEC: 80.15 ± 1.74 TECU, Date/Time: 2024-12-16 17:56:59, Latitude: -15.56
178. TEC: 80.14 ± 2.72 TECU, Date/Time: 2024-12-16 19:04:01, Latitude: -15.56
179. TEC: 80.09 ± 4.77 TECU, Date/Time: 2024-12-02 18:01:01, Latitude: -15.56
180. TEC: 80.09 ± 1.80 TECU, Date/Time: 2024-12-16 17:55:58, Latitude: -15.56
181. TEC: 80.04 ± 1.27 TECU, Date/Time: 2024-12-02 19:52:01, Latitude: -15.56
182. TEC: 80.04 ± 1.56 TECU, Date/Time: 2024-12-16 17:55:01, Latitude: -15.56
183. TEC: 80.02 ± 2.64 TECU, Date/Time: 2024-12-16 19:04:58, Latitude: -15.56
184. TEC: 79.98 ± 1.70 TECU, Date/Time: 2024-12-16 17:53:59, Latitude: -15.56
185. TEC: 79.97 ± 4.64 TECU, Date/Time: 2024-12-02 18:00:00, Latitude: -15.56
186. TEC: 79.93 ± 1.41 TECU, Date/Time: 2024-12-02 19:52:58, Latitude: -15.56
187. TEC: 79.92 ± 1.41 TECU, Date/Time: 2024-12-16 17:52:58, Latitude: -15.56
188. TEC: 79.90 ± 2.65 TECU, Date/Time: 2024-12-16 19:06:00, Latitude: -15.56
189. TEC: 79.86 ± 1.49 TECU, Date/Time: 2024-12-16 17:52:01, Latitude: -15.56
190. TEC: 79.84 ± 4.57 TECU, Date/Time: 2024-12-02 17:58:58, Latitude: -15.56
191. TEC: 79.81 ± 1.27 TECU, Date/Time: 2024-12-02 19:53:59, Latitude: -15.56
192. TEC: 79.80 ± 1.48 TECU, Date/Time: 2024-12-16 17:51:00, Latitude: -15.56
193. TEC: 79.77 ± 2.66 TECU, Date/Time: 2024-12-16 19:07:01, Latitude: -15.56
194. TEC: 79.73 ± 1.26 TECU, Date/Time: 2024-12-16 17:49:58, Latitude: -15.56
195. TEC: 79.72 ± 4.54 TECU, Date/Time: 2024-12-02 17:58:01, Latitude: -15.56
196. TEC: 79.70 ± 1.36 TECU, Date/Time: 2024-12-02 19:55:01, Latitude: -15.56
197. TEC: 79.67 ± 1.30 TECU, Date/Time: 2024-12-16 17:49:01, Latitude: -15.56
198. TEC: 79.64 ± 2.68 TECU, Date/Time: 2024-12-16 19:07:58, Latitude: -15.56
199. TEC: 79.60 ± 1.31 TECU, Date/Time: 2024-12-16 17:48:00, Latitude: -15.56
200. TEC: 79.59 ± 4.37 TECU, Date/Time: 2024-12-02 17:56:59, Latitude: -15.56

SEQUENCE ANALYSIS (Values ​​remain above 90% of peak at 3 consecutive points):

Peak #1 (TEC = 83.50 ± 3.10) has a sequence of 3 high values:
  1. 2024-12-02 18:58:01: 83.49 ± 3.09 TECU (100.0% do Peak)
  2. 2024-12-02 18:58:58: 83.50 ± 3.10 TECU (100.0% do Peak)
  3. 2024-12-02 19:00:00: 83.50 ± 3.10 TECU (100.0% do Peak)

Peak #2 (TEC = 83.50 ± 3.10) has a sequence of 3 high values:
  1. 2024-12-02 18:58:58: 83.50 ± 3.10 TECU (100.0% do Peak)
  2. 2024-12-02 19:00:00: 83.50 ± 3.10 TECU (100.0% do Peak)
  3. 2024-12-02 19:01:01: 83.50 ± 3.10 TECU (100.0% do Peak)

Peak #3 (TEC = 83.50 ± 3.10) has a sequence of 3 high values:
  1. 2024-12-02 19:00:00: 83.50 ± 3.10 TECU (100.0% do Peak)
  2. 2024-12-02 19:01:01: 83.50 ± 3.10 TECU (100.0% do Peak)
  3. 2024-12-02 19:01:58: 83.50 ± 3.11 TECU (100.0% do Peak)

Peak #4 (TEC = 83.50 ± 3.11) has a sequence of 3 high values:
  1. 2024-12-02 19:01:01: 83.50 ± 3.10 TECU (100.0% do Peak)
  2. 2024-12-02 19:01:58: 83.50 ± 3.11 TECU (100.0% do Peak)
  3. 2024-12-02 19:03:00: 83.50 ± 3.12 TECU (100.0% do Peak)

Peak #5 (TEC = 83.50 ± 3.12) has a sequence of 3 high values:
  1. 2024-12-02 19:01:58: 83.50 ± 3.11 TECU (100.0% do Peak)
  2. 2024-12-02 19:03:00: 83.50 ± 3.12 TECU (100.0% do Peak)
  3. 2024-12-02 19:04:01: 83.49 ± 3.13 TECU (100.0% do Peak)

Peak #6 (TEC = 83.49 ± 3.11) has a sequence of 3 high values:
  1. 2024-12-02 18:55:58: 83.48 ± 3.12 TECU (100.0% do Peak)
  2. 2024-12-02 18:56:59: 83.49 ± 3.11 TECU (100.0% do Peak)
  3. 2024-12-02 18:58:01: 83.49 ± 3.09 TECU (100.0% do Peak)

Peak #7 (TEC = 83.49 ± 3.09) has a sequence of 3 high values:
  1. 2024-12-02 18:56:59: 83.49 ± 3.11 TECU (100.0% do Peak)
  2. 2024-12-02 18:58:01: 83.49 ± 3.09 TECU (100.0% do Peak)
  3. 2024-12-02 18:58:58: 83.50 ± 3.10 TECU (100.0% do Peak)

Peak #8 (TEC = 83.49 ± 3.13) has a sequence of 3 high values:
  1. 2024-12-02 19:03:00: 83.50 ± 3.12 TECU (100.0% do Peak)
  2. 2024-12-02 19:04:01: 83.49 ± 3.13 TECU (100.0% do Peak)
  3. 2024-12-02 19:04:58: 83.49 ± 3.14 TECU (100.0% do Peak)

Peak #9 (TEC = 83.49 ± 3.14) has a sequence of 3 high values:
  1. 2024-12-02 19:04:01: 83.49 ± 3.13 TECU (100.0% do Peak)
  2. 2024-12-02 19:04:58: 83.49 ± 3.14 TECU (100.0% do Peak)
  3. 2024-12-02 19:06:00: 83.48 ± 3.13 TECU (100.0% do Peak)

Peak #10 (TEC = 83.48 ± 3.12) has a sequence of 3 high values:
  1. 2024-12-02 18:55:01: 83.47 ± 2.89 TECU (100.0% do Peak)
  2. 2024-12-02 18:55:58: 83.48 ± 3.12 TECU (100.0% do Peak)
  3. 2024-12-02 18:56:59: 83.49 ± 3.11 TECU (100.0% do Peak)

Peak #11 (TEC = 83.48 ± 3.13) has a sequence of 3 high values:
  1. 2024-12-02 19:04:58: 83.49 ± 3.14 TECU (100.0% do Peak)
  2. 2024-12-02 19:06:00: 83.48 ± 3.13 TECU (100.0% do Peak)
  3. 2024-12-02 19:07:01: 83.47 ± 3.14 TECU (100.0% do Peak)

Peak #12 (TEC = 83.47 ± 2.89) has a sequence of 3 high values:
  1. 2024-12-02 18:53:59: 83.46 ± 2.19 TECU (100.0% do Peak)
  2. 2024-12-02 18:55:01: 83.47 ± 2.89 TECU (100.0% do Peak)
  3. 2024-12-02 18:55:58: 83.48 ± 3.12 TECU (100.0% do Peak)

Peak #13 (TEC = 83.47 ± 3.14) has a sequence of 3 high values:
  1. 2024-12-02 19:06:00: 83.48 ± 3.13 TECU (100.0% do Peak)
  2. 2024-12-02 19:07:01: 83.47 ± 3.14 TECU (100.0% do Peak)
  3. 2024-12-02 19:07:58: 83.46 ± 3.16 TECU (100.0% do Peak)

Peak #14 (TEC = 83.46 ± 2.19) has a sequence of 3 high values:
  1. 2024-12-02 18:52:58: 83.45 ± 2.13 TECU (100.0% do Peak)
  2. 2024-12-02 18:53:59: 83.46 ± 2.19 TECU (100.0% do Peak)
  3. 2024-12-02 18:55:01: 83.47 ± 2.89 TECU (100.0% do Peak)

Peak #15 (TEC = 83.46 ± 3.16) has a sequence of 3 high values:
  1. 2024-12-02 19:07:01: 83.47 ± 3.14 TECU (100.0% do Peak)
  2. 2024-12-02 19:07:58: 83.46 ± 3.16 TECU (100.0% do Peak)
  3. 2024-12-02 19:08:59: 83.44 ± 3.37 TECU (100.0% do Peak)

Peak #16 (TEC = 83.45 ± 2.13) has a sequence of 3 high values:
  1. 2024-12-02 18:52:01: 83.44 ± 2.08 TECU (100.0% do Peak)
  2. 2024-12-02 18:52:58: 83.45 ± 2.13 TECU (100.0% do Peak)

## SPECIFIC TIMES FOR 12/18

In [10]:
import pandas as pd
import numpy as np
from datetime import timedelta, time, datetime

df = pd.read_pickle('cuib_dec_2024_complete.pkl')
print(f"Data loaded: {len(df)} records of {df['DATETIME'].min().date()} until {df['DATETIME'].max().date()}")

# Verificar as colunas disponíveis
print(f"Colunas disponíveis no DataFrame: {list(df.columns)}")

df = df.sort_values('DATETIME').reset_index(drop=True)

df_clean = df.dropna(subset=['TEC', 'TEC_STD']).copy()
print(f"Analysing {len(df_clean)} points after removing missing values")

def check_consecutive_highs(df, peak_datetime, threshold_percent=90):
    peak_idx = df[df['DATETIME'] == peak_datetime].index[0]
    peak_value = df.loc[peak_idx, 'TEC']
    threshold = peak_value * (threshold_percent / 100)

    idx_before = peak_idx - 1
    idx_after = peak_idx + 1

    valid_before = idx_before >= 0
    valid_after = idx_after < len(df)

    if valid_before and valid_after:
        values = [df.loc[idx_before, 'TEC'], peak_value, df.loc[idx_after, 'TEC']]
        stds = [df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD']]
        datetimes = [df.loc[idx_before, 'DATETIME'], peak_datetime, df.loc[idx_after, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before, peak_idx, idx_after],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_before and idx_before > 0:
        values = [df.loc[idx_before-1, 'TEC'], df.loc[idx_before, 'TEC'], peak_value]
        stds = [df.loc[idx_before-1, 'TEC_STD'], df.loc[idx_before, 'TEC_STD'], df.loc[peak_idx, 'TEC_STD']]
        datetimes = [df.loc[idx_before-1, 'DATETIME'], df.loc[idx_before, 'DATETIME'], peak_datetime]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [idx_before-1, idx_before, peak_idx],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    if valid_after and idx_after < len(df) - 1:
        values = [peak_value, df.loc[idx_after, 'TEC'], df.loc[idx_after+1, 'TEC']]
        stds = [df.loc[peak_idx, 'TEC_STD'], df.loc[idx_after, 'TEC_STD'], df.loc[idx_after+1, 'TEC_STD']]
        datetimes = [peak_datetime, df.loc[idx_after, 'DATETIME'], df.loc[idx_after+1, 'DATETIME']]
        all_high = all(value >= threshold for value in values)

        if all_high:
            return {'indices': [peak_idx, idx_after, idx_after+1],
                   'values': values,
                   'stds': stds,
                   'datetimes': datetimes}

    return None

def find_closest_value_to_datetime(df, target_datetime, max_minutes_diff=2):
    """
    Encontra o valor TEC mais próximo de um datetime específico,
    dentro de uma diferença máxima de minutos especificada.
    """
    # Converte target_datetime para pandas Timestamp se necessário
    if isinstance(target_datetime, str):
        target_datetime = pd.to_datetime(target_datetime)
    elif isinstance(target_datetime, datetime):
        target_datetime = pd.Timestamp(target_datetime)

    # Calcula a diferença em minutos absoluta entre cada timestamp e o target
    time_diff = abs((df['DATETIME'] - target_datetime).dt.total_seconds() / 60)

    # Filtra apenas valores dentro da diferença máxima permitida
    within_range = time_diff <= max_minutes_diff

    if not within_range.any():
        return None, None

    # Encontra o índice do valor mais próximo dentro do range
    closest_idx = time_diff[within_range].idxmin()
    closest_diff = time_diff[closest_idx]

    return df.loc[closest_idx], closest_diff

def get_available_location_info(row):
    """
    Retorna informações de localização disponíveis no DataFrame
    """
    location_info = {}

    # Verifica quais colunas de localização estão disponíveis
    location_columns = ['LATITUDE', 'LONGITUDE', 'LAT', 'LON', 'STATION', 'SITE']

    for col in location_columns:
        if col in row.index:
            location_info[col] = row[col]

    return location_info

def analyze_specific_datetimes(target_datetimes, max_minutes_diff=2):
    """
    Analisa valores TEC próximos a datetimes específicos.

    Parameters:
    target_datetimes: lista de strings ou datetime objects com os horários target
    max_minutes_diff: diferença máxima em minutos para considerar um valor como "próximo"
    """

    print(f"\n{'='*100}")
    print(f"ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS")
    print(f"(Diferença máxima permitida: {max_minutes_diff} minutos)")
    print(f"{'='*100}")

    results = []

    for i, target_dt in enumerate(target_datetimes):
        print(f"\n{'-'*60}")
        print(f"BUSCANDO VALORES PRÓXIMOS A: {target_dt}")
        print(f"{'-'*60}")

        closest_row, time_diff = find_closest_value_to_datetime(df_clean, target_dt, max_minutes_diff)

        if closest_row is not None:
            print(f"✓ VALOR ENCONTRADO:")
            print(f"  Data/Hora real: {closest_row['DATETIME']}")
            print(f"  Data/Hora alvo: {target_dt}")
            print(f"  Diferença: {time_diff:.2f} minutos")
            print(f"  TEC: {closest_row['TEC']:.2f} ± {closest_row['TEC_STD']:.2f} TECU")

            # Obter informações de localização disponíveis
            location_info = get_available_location_info(closest_row)
            for key, value in location_info.items():
                print(f"  {key}: {value}")

            # Verifica se há sequência de valores altos
            sequence = check_consecutive_highs(df_clean, closest_row['DATETIME'], threshold_percent=90)

            if sequence:
                print(f"  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):")
                for j, (dt, val, std) in enumerate(zip(sequence['datetimes'], sequence['values'], sequence['stds'])):
                    print(f"    {j+1}. {dt}: {val:.2f} ± {std:.2f} TECU ({val/closest_row['TEC']*100:.1f}% do valor)")
            else:
                print(f"  ✗ NÃO possui sequência de 3 valores altos consecutivos")

            # Preparar resultado para a tabela
            result = {
                'target_datetime': target_dt,
                'found_datetime': closest_row['DATETIME'],
                'time_diff_minutes': time_diff,
                'TEC': closest_row['TEC'],
                'TEC_STD': closest_row['TEC_STD'],
                'has_sequence': sequence is not None,
                'sequence': sequence,
                'location_info': location_info
            }

            results.append(result)

        else:
            print(f"✗ NENHUM VALOR ENCONTRADO dentro de {max_minutes_diff} minutos do horário alvo")
            results.append({
                'target_datetime': target_dt,
                'found_datetime': None,
                'time_diff_minutes': None,
                'TEC': None,
                'TEC_STD': None,
                'has_sequence': False,
                'sequence': None,
                'location_info': {}
            })

    # Tabela resumo
    print(f"\n{'='*120}")
    print(f"TABELA RESUMO DOS RESULTADOS")
    print(f"{'='*120}")

    # Cabeçalho adaptativo baseado nas colunas disponíveis
    header = f"{'#':<3}{'Horário Alvo':<20}{'Horário Encontrado':<20}{'Diff(min)':<10}{'TEC':<10}{'TEC_STD':<10}{'Sequência':<12}"

    # Adicionar colunas de localização disponíveis
    location_cols = set()
    for result in results:
        if result['location_info']:
            location_cols.update(result['location_info'].keys())

    for col in sorted(location_cols):
        header += f"{col:<12}"

    print(header)
    print(f"{'-'*len(header)}")

    for i, result in enumerate(results):
        if result['found_datetime'] is not None:
            seq_info = "Sim" if result['has_sequence'] else "Não"
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{str(result['found_datetime']):<20}"
            row += f"{result['time_diff_minutes']:.2f}    {result['TEC']:.2f}    "
            row += f"{result['TEC_STD']:.2f}    {seq_info:<12}"

            # Adicionar informações de localização
            for col in sorted(location_cols):
                value = result['location_info'].get(col, 'N/A')
                if isinstance(value, float):
                    row += f"{value:.2f}      "
                else:
                    row += f"{str(value):<12}"

            print(row)
        else:
            row = f"{i+1:<3}{str(result['target_datetime']):<20}{'NÃO ENCONTRADO':<20}"
            row += f"{'N/A':<10}{'N/A':<10}{'N/A':<10}{'N/A':<12}"

            # Preencher com N/A para colunas de localização
            for col in sorted(location_cols):
                row += f"{'N/A':<12}"

            print(row)

    print(f"{'-'*len(header)}")

    return results

# Definindo os horários específicos solicitados
target_datetimes = [
    "2024-12-18 18:20:00",
    "2024-12-18 18:10:00",
    "2024-12-18 18:30:00",
    "2024-12-18 18:00:00"
]

print("\n\n" + "*"*50 + " ANÁLISE DOS HORÁRIOS ESPECÍFICOS " + "*"*50)
results = analyze_specific_datetimes(target_datetimes, max_minutes_diff=2)

print("\nAnálise concluída!")

# Informações adicionais sobre os dados encontrados
found_results = [r for r in results if r['found_datetime'] is not None]
if found_results:
    print(f"\n{'='*80}")
    print(f"ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS")
    print(f"{'='*80}")

    tec_values = [r['TEC'] for r in found_results]
    print(f"Valores TEC encontrados:")
    print(f"  Mínimo: {min(tec_values):.2f} TECU")
    print(f"  Máximo: {max(tec_values):.2f} TECU")
    print(f"  Média: {np.mean(tec_values):.2f} TECU")
    print(f"  Desvio padrão: {np.std(tec_values):.2f} TECU")

    sequences_found = sum(1 for r in found_results if r['has_sequence'])
    print(f"\nSequências de valores altos encontradas: {sequences_found} de {len(found_results)} ({sequences_found/len(found_results)*100:.1f}%)")

Data loaded: 44640 records of 2024-12-01 until 2024-12-31
Colunas disponíveis no DataFrame: ['DATETIME', 'TEC', 'TEC_STD', 'LATITUDE']
Analysing 44609 points after removing missing values


************************************************** ANÁLISE DOS HORÁRIOS ESPECÍFICOS **************************************************

====================================================================================================
ANÁLISE DE VALORES TEC PRÓXIMOS A HORÁRIOS ESPECÍFICOS
(Diferença máxima permitida: 2 minutos)
====================================================================================================

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:20:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:19:58
  Data/Hora alvo: 2024-12-18 18:20:00
  Diferença: 0.03 minutos
  TEC: 76.57 ± 3.43 TECU
  LATITUDE: -15.56
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:19:01: 76.46 ± 3.41 TECU (99.9% do valor)
    2. 2024-12-18 18:19:58: 76.57 ± 3.43 TECU (100.0% do valor)
    3. 2024-12-18 18:21:00: 76.67 ± 3.45 TECU (100.1% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:10:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:10:01
  Data/Hora alvo: 2024-12-18 18:10:00
  Diferença: 0.02 minutos
  TEC: 75.38 ± 2.78 TECU
  LATITUDE: -15.56
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:08:59: 75.25 ± 2.98 TECU (99.8% do valor)
    2. 2024-12-18 18:10:01: 75.38 ± 2.78 TECU (100.0% do valor)
    3. 2024-12-18 18:10:58: 75.50 ± 2.89 TECU (100.2% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:30:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:30:00
  Data/Hora alvo: 2024-12-18 18:30:00
  Diferença: 0.00 minutos
  TEC: 77.54 ± 4.00 TECU
  LATITUDE: -15.56
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 18:28:58: 77.45 ± 4.10 TECU (99.9% do valor)
    2. 2024-12-18 18:30:00: 77.54 ± 4.00 TECU (100.0% do valor)
    3. 2024-12-18 18:31:01: 77.63 ± 4.08 TECU (100.1% do valor)

------------------------------------------------------------
BUSCANDO VALORES PRÓXIMOS A: 2024-12-18 18:00:00
------------------------------------------------------------
✓ VALOR ENCONTRADO:
  Data/Hora real: 2024-12-18 18:00:00
  Data/Hora alvo: 2024-12-18 18:00:00
  Diferença: 0.00 minutos
  TEC: 74.03 ± 3.15 TECU
  LATITUDE: -15.56
  ✓ POSSUI sequência de 3 valores altos (≥90% do pico):
    1. 2024-12-18 17:58:58: 73.89 ± 3.21 TECU (99.8% do valor)
    2. 2024-12-18 18:00:00: 74.03 ± 3.15 TECU (100.0% do valor)
    3. 2024-12-18 18:01:01: 74.17 ± 3.12 TECU (100.2% do valor)

========================================================================================================================
TABELA RESUMO DOS RESULTADOS
========================================================================================================================
#  Horário Alvo        Horário Encontrado  Diff(min) TEC       TEC_STD   Sequência   LATITUDE
-------------------------------------------------------------------------------------------------
1  2024-12-18 18:20:00 2024-12-18 18:19:58 0.03    76.57    3.43    Sim         -15.56
2  2024-12-18 18:10:00 2024-12-18 18:10:01 0.02    75.38    2.78    Sim         -15.56
3  2024-12-18 18:30:00 2024-12-18 18:30:00 0.00    77.54    4.00    Sim         -15.56
4  2024-12-18 18:00:00 2024-12-18 18:00:00 0.00    74.03    3.15    Sim         -15.56
-------------------------------------------------------------------------------------------------

Análise concluída!

================================================================================
ESTATÍSTICAS DOS RESULTADOS ENCONTRADOS
================================================================================
Valores TEC encontrados:
  Mínimo: 74.03 TECU
  Máximo: 77.54 TECU
  Média: 75.88 TECU
  Desvio padrão: 1.31 TECU

Sequências de valores altos encontradas: 4 de 4 (100.0%)

# IGS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
!gdown '1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp'

Downloading...
From: https://drive.google.com/uc?id=1T0gBaH6IyIX72T1VPJuZa2D43HCrRFVp
To: /content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl
100% 3.60M/3.60M [00:00<00:00, 277MB/s]

In [ ]:
df_igs_maps_2024 = pd.read_pickle('/content/TF_IGS_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [ ]:
df_igs_maps_2024

               DATETIME                                             TECMAP
0   2024-12-01 00:00:00  [[37.7, 34.6, 31.9, 30.0, 28.6, 27.2, 25.8, 24...
1   2024-12-01 02:00:00  [[20.3, 18.7, 18.1, 18.2, 18.2, 18.1, 17.7, 17...
2   2024-12-01 04:00:00  [[11.6, 11.8, 12.0, 12.4, 13.0, 13.5, 14.0, 14...
3   2024-12-01 06:00:00  [[10.4, 10.8, 11.1, 11.7, 12.1, 12.7, 13.3, 13...
4   2024-12-01 08:00:00  [[9.9, 10.1, 10.3, 10.6, 11.0, 11.6, 12.3, 13....
..                  ...                                                ...
343 2024-12-30 14:00:00  [[8.9, 11.1, 14.4, 18.8, 23.7, 28.3, 32.7, 36....
344 2024-12-30 16:00:00  [[26.3, 29.8, 33.4, 37.1, 40.5, 43.7, 47.0, 49...
345 2024-12-30 18:00:00  [[43.5, 44.5, 45.3, 46.2, 47.1, 48.6, 50.0, 51...
346 2024-12-30 20:00:00  [[48.8, 49.1, 49.0, 48.7, 48.5, 48.1, 48.0, 47...
347 2024-12-30 22:00:00  [[47.0, 46.6, 45.6, 44.4, 43.2, 42.0, 40.4, 38...

[348 rows x 2 columns]

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:

    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(igs_points)

[(-17.5, -60, 25, 10), (-17.5, -55, 25, 11), (-15.0, -60, 26, 10), (-15.0, -55, 26, 11)]

In [ ]:
igs_points

[(-17.5, -60, 25, 10),
 (-17.5, -55, 25, 11),
 (-15.0, -60, 26, 10),
 (-15.0, -55, 26, 11)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -60.0°) - Indexes: [25, 10] - TEC:  86.4
   P2: ( -17.5°,  -55.0°) - Indexes: [25, 11] - TEC:  88.0
   P3: ( -15.0°,  -60.0°) - Indexes: [26, 10] - TEC:  83.7
   P4: ( -15.0°,  -55.0°) - Indexes: [26, 11] - TEC:  84.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -60.0° to  -55.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -60.0°) =  86.4
   f_01 (lat_min, lon_max) = ( -17.5°,  -55.0°) =  88.0
   f_10 (lat_max, lon_min) = ( -15.0°,  -60.0°) =  83.7
   f_11 (lat_max, lon_max) = ( -15.0°,  -55.0°) =  84.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -60.0)) / ( -55.0 - ( -60.0))
   t_x = 3.93013 /  5.0 = 0.786026

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.94474 /  2.5 = 0.777896

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.786026) * (1 - 0.777896) = 0.047524
   w_01 = t_x * (1 - t_y)       = 0.786026 * (1 - 0.777896)       = 0.174580
   w_10 = (1 - t_x) * t_y       = (1 - 0.786026) * 0.777896       = 0.166450
   w_11 = t_x * t_y             = 0.786026 * 0.777896             = 0.611446
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.047524* 86.4 + 0.174580* 88.0 + 0.166450* 83.7 + 0.611446* 84.4
   Value =   4.1061 +  15.3630 +  13.9318 +  51.6061
   Value = 85.007021

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 78.60% of the way from -60° to -55°
   In Y direction (latitude):  77.79% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 85.0070
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(igs_points)

[(-17.5, -60, 25, 10), (-17.5, -55, 25, 11), (-15.0, -60, 26, 10), (-15.0, -55, 26, 11)]

In [ ]:
igs_points

[(-17.5, -60, 25, 10),
 (-17.5, -55, 25, 11),
 (-15.0, -60, 26, 10),
 (-15.0, -55, 26, 11)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -60.0°) - Indexes: [25, 10] - TEC:  86.4
   P2: ( -17.5°,  -55.0°) - Indexes: [25, 11] - TEC:  88.0
   P3: ( -15.0°,  -60.0°) - Indexes: [26, 10] - TEC:  83.7
   P4: ( -15.0°,  -55.0°) - Indexes: [26, 11] - TEC:  84.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -60.0° to  -55.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -60.0°) =  86.4
   f_01 (lat_min, lon_max) = ( -17.5°,  -55.0°) =  88.0
   f_10 (lat_max, lon_min) = ( -15.0°,  -60.0°) =  83.7
   f_11 (lat_max, lon_max) = ( -15.0°,  -55.0°) =  84.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -60.0)) / ( -55.0 - ( -60.0))
   t_x = 3.93013 /  5.0 = 0.786026

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.94474 /  2.5 = 0.777896

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.786026) * (1 - 0.777896) = 0.047524
   w_01 = t_x * (1 - t_y)       = 0.786026 * (1 - 0.777896)       = 0.174580
   w_10 = (1 - t_x) * t_y       = (1 - 0.786026) * 0.777896       = 0.166450
   w_11 = t_x * t_y             = 0.786026 * 0.777896             = 0.611446
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.047524* 86.4 + 0.174580* 88.0 + 0.166450* 83.7 + 0.611446* 84.4
   Value =   4.1061 +  15.3630 +  13.9318 +  51.6061
   Value = 85.007021

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 78.60% of the way from -60° to -55°
   In Y direction (latitude):  77.79% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 85.0070
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):
        """
        Função para encontrar os 4 pontos da grade mais próximos
        a uma coordenada específica
        """
        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(igs_points)

[(-17.5, -60, 25, 10), (-17.5, -55, 25, 11), (-15.0, -60, 26, 10), (-15.0, -55, 26, 11)]

In [ ]:
igs_points

[(-17.5, -60, 25, 10),
 (-17.5, -55, 25, 11),
 (-15.0, -60, 26, 10),
 (-15.0, -55, 26, 11)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -60.0°) - Indexes: [25, 10] - TEC:  86.4
   P2: ( -17.5°,  -55.0°) - Indexes: [25, 11] - TEC:  88.0
   P3: ( -15.0°,  -60.0°) - Indexes: [26, 10] - TEC:  83.7
   P4: ( -15.0°,  -55.0°) - Indexes: [26, 11] - TEC:  84.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -60.0° to  -55.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -60.0°) =  86.4
   f_01 (lat_min, lon_max) = ( -17.5°,  -55.0°) =  88.0
   f_10 (lat_max, lon_min) = ( -15.0°,  -60.0°) =  83.7
   f_11 (lat_max, lon_max) = ( -15.0°,  -55.0°) =  84.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -60.0)) / ( -55.0 - ( -60.0))
   t_x = 3.93013 /  5.0 = 0.786026

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.94474 /  2.5 = 0.777896

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.786026) * (1 - 0.777896) = 0.047524
   w_01 = t_x * (1 - t_y)       = 0.786026 * (1 - 0.777896)       = 0.174580
   w_10 = (1 - t_x) * t_y       = (1 - 0.786026) * 0.777896       = 0.166450
   w_11 = t_x * t_y             = 0.786026 * 0.777896             = 0.611446
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.047524* 86.4 + 0.174580* 88.0 + 0.166450* 83.7 + 0.611446* 84.4
   Value =   4.1061 +  15.3630 +  13.9318 +  51.6061
   Value = 85.007021

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 78.60% of the way from -60° to -55°
   In Y direction (latitude):  77.79% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 85.0070
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_igs_maps_2024[df_igs_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_igs_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_igs_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_igs_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

               DATETIME                                             TECMAP
201 2024-12-18 18:00:00  [[38.6, 42.2, 45.2, 47.7, 49.5, 50.3, 49.9, 49...

In [ ]:
igs_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_igs_maps = []
for i in range(len(igs_maps)):
    np_igs_maps.append(igs_maps[i])
np_igs_maps = np.array(np_igs_maps)

In [ ]:
np_igs_maps

array([[[38.6, 42.2, 45.2, ..., 15.9, 15.3, 15.4],
        [38.9, 42.4, 45.9, ..., 18.4, 17.5, 17.4],
        [39.1, 42.5, 46.1, ..., 23.7, 22. , 21. ],
        ...,
        [24.3, 24. , 23.8, ..., 19.1, 18.4, 17.9],
        [24.1, 23.9, 23.6, ..., 18.6, 18.1, 17.7],
        [23.5, 23.3, 23.1, ..., 18.1, 17.6, 17.3]]])

In [ ]:
np_igs_maps.shape

(1, 49, 23)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):
        """
        Função para encontrar os 4 pontos da grade mais próximos
        a uma coordenada específica
        """
        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class Igs(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 2.5,
                 lon_step: float = 5):
        super().__init__(extent, lat_step, lon_step)


igs_tec = Igs(extent=(-110, 0, -80, 40), lat_step=2.5, lon_step=5)
igs_points = igs_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(igs_points)

[(-17.5, -60, 25, 10), (-17.5, -55, 25, 11), (-15.0, -60, 26, 10), (-15.0, -55, 26, 11)]

In [ ]:
igs_points

[(-17.5, -60, 25, 10),
 (-17.5, -55, 25, 11),
 (-15.0, -60, 26, 10),
 (-15.0, -55, 26, 11)]

In [ ]:
igs_tec.tec_map = np_igs_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(igs_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = igs_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in igs_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(igs_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in igs_points]
lons = [p[1] for p in igs_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(igs_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -17.5°,  -60.0°) - Indexes: [25, 10] - TEC:  86.4
   P2: ( -17.5°,  -55.0°) - Indexes: [25, 11] - TEC:  88.0
   P3: ( -15.0°,  -60.0°) - Indexes: [26, 10] - TEC:  83.7
   P4: ( -15.0°,  -55.0°) - Indexes: [26, 11] - TEC:  84.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -17.5° to  -15.0° (range:  2.5°)
   Longitude:  -60.0° to  -55.0° (range:  5.0°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -17.5°,  -60.0°) =  86.4
   f_01 (lat_min, lon_max) = ( -17.5°,  -55.0°) =  88.0
   f_10 (lat_max, lon_min) = ( -15.0°,  -60.0°) =  83.7
   f_11 (lat_max, lon_max) = ( -15.0°,  -55.0°) =  84.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -60.0)) / ( -55.0 - ( -60.0))
   t_x = 3.93013 /  5.0 = 0.786026

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -17.5)) / ( -15.0 - ( -17.5))
   t_y = 1.94474 /  2.5 = 0.777896

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.786026) * (1 - 0.777896) = 0.047524
   w_01 = t_x * (1 - t_y)       = 0.786026 * (1 - 0.777896)       = 0.174580
   w_10 = (1 - t_x) * t_y       = (1 - 0.786026) * 0.777896       = 0.166450
   w_11 = t_x * t_y             = 0.786026 * 0.777896             = 0.611446
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.047524* 86.4 + 0.174580* 88.0 + 0.166450* 83.7 + 0.611446* 84.4
   Value =   4.1061 +  15.3630 +  13.9318 +  51.6061
   Value = 85.007021

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 78.60% of the way from -60° to -55°
   In Y direction (latitude):  77.79% of the way from -17.5° to -15.0°

============================================================
FINAL RESULT: TEC = 85.0070
============================================================

# Nagoya

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
!gdown '1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR'

Downloading...
From (original): https://drive.google.com/uc?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR
From (redirected): https://drive.google.com/uc?id=1CXL-btSyeELqYjLGL-B2oSnMt-QlPFUR&confirm=t&uuid=3fbbd530-c426-4f6a-abe5-45ebc77bd7e1
To: /content/TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl
100% 4.03G/4.03G [00:18<00:00, 213MB/s]

In [ ]:
df_nagoya_maps_2024 = pd.read_pickle('TF_Nagoya_TEC_maps_intersection_case_study_Dec_2024.pkl')

In [ ]:
df_nagoya_maps_2024

                DATETIME                                             TECMAP
0    2024-12-01 00:00:00  [[18.593109130859375, 19.42150115966797, 19.42...
1    2024-12-01 00:05:00  [[18.222612380981445, 18.222612380981445, 18.2...
2    2024-12-01 00:10:00  [[18.21422576904297, 18.21422576904297, 18.214...
3    2024-12-01 00:15:00  [[18.284513473510742, 18.284513473510742, 18.0...
4    2024-12-01 00:20:00  [[18.328298568725586, 18.328298568725586, 18.0...
...                  ...                                                ...
8347 2024-12-30 23:35:00  [[26.173906326293945, 27.259140014648438, 27.2...
8348 2024-12-30 23:40:00  [[27.0389347076416, 27.0389347076416, 27.03893...
8349 2024-12-30 23:45:00  [[26.902502059936523, 26.72080421447754, 25.94...
8350 2024-12-30 23:50:00  [[27.88735580444336, 27.88735580444336, 27.887...
8351 2024-12-30 23:55:00  [[24.682987213134766, 25.294950485229492, 25.2...

[8352 rows x 2 columns]

## 12/18/2024 - 18:20

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4828 2024-12-18 18:20:00  [[18.751976013183594, 18.751976013183594, 18.8...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.75197601, 18.75197601, 18.81381989, ...,         nan,
                 nan,         nan],
        [18.25943375, 18.13648224, 18.13648224, ...,         nan,
                 nan,         nan],
        ...,
        [38.79235458, 39.10980225, 39.51619339, ..., 13.45065308,
         13.1072731 , 12.96411705],
        [38.38473892, 38.68589783, 39.00465393, ..., 13.27555275,
         12.90675449, 12.72219276],
        [38.23902512, 38.27802277, 38.43577194, ..., 12.968153  ,
         12.60940075, 12.51128292]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(nagoya_points)

[(-15.900000000000006, -56.5, 129, 107), (-15.900000000000006, -56.0, 129, 108), (-15.400000000000006, -56.5, 130, 107), (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_points

[(-15.900000000000006, -56.5, 129, 107),
 (-15.900000000000006, -56.0, 129, 108),
 (-15.400000000000006, -56.5, 130, 107),
 (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -15.9°,  -56.5°) - Indexes: [129, 107] - TEC:  79.3
   P2: ( -15.9°,  -56.0°) - Indexes: [129, 108] - TEC:  79.3
   P3: ( -15.4°,  -56.5°) - Indexes: [130, 107] - TEC:  79.3
   P4: ( -15.4°,  -56.0°) - Indexes: [130, 108] - TEC:  79.3

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -15.9° to  -15.4° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -15.9°,  -56.5°) =  79.3
   f_01 (lat_min, lon_max) = ( -15.9°,  -56.0°) =  79.3
   f_10 (lat_max, lon_min) = ( -15.4°,  -56.5°) =  79.3
   f_11 (lat_max, lon_max) = ( -15.4°,  -56.0°) =  79.3

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -15.9)) / ( -15.4 - ( -15.9))
   t_y = 0.34474 /  0.5 = 0.689480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.689480) = 0.043392
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.689480)       = 0.267128
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.689480       = 0.096348
   w_11 = t_x * t_y             = 0.860260 * 0.689480             = 0.593132
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.043392* 79.3 + 0.267128* 79.3 + 0.096348* 79.3 + 0.593132* 79.3
   Value =   3.4423 +  21.1911 +   7.6432 +  47.0529
   Value = 79.329483

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  68.95% of the way from -15.900000000000006° to -15.400000000000006°

============================================================
FINAL RESULT: TEC = 79.3295
============================================================

## 12/18/2024 - 18:10

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4826 2024-12-18 18:10:00  [[18.412939071655273, 17.651090621948242, 17.6...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[18.41293907, 17.65109062, 17.65109062, ...,         nan,
                 nan,         nan],
        [18.53962135, 17.62540054, 17.62540054, ...,         nan,
                 nan,         nan],
        [17.62013054, 17.62013054, 17.62540054, ...,         nan,
                 nan,         nan],
        ...,
        [36.95772552, 37.32144928, 37.6816864 , ..., 14.07102394,
         13.53792286, 13.37452602],
        [37.09318542, 37.28800964, 37.65478134, ..., 13.818923  ,
         13.44021893, 13.28282356],
        [36.133461  , 36.14941025, 36.71422577, ..., 13.40729332,
         13.00967979, 13.02010918]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(nagoya_points)

[(-15.900000000000006, -56.5, 129, 107), (-15.900000000000006, -56.0, 129, 108), (-15.400000000000006, -56.5, 130, 107), (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_points

[(-15.900000000000006, -56.5, 129, 107),
 (-15.900000000000006, -56.0, 129, 108),
 (-15.400000000000006, -56.5, 130, 107),
 (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -15.9°,  -56.5°) - Indexes: [129, 107] - TEC:  77.9
   P2: ( -15.9°,  -56.0°) - Indexes: [129, 108] - TEC:  78.6
   P3: ( -15.4°,  -56.5°) - Indexes: [130, 107] - TEC:  76.6
   P4: ( -15.4°,  -56.0°) - Indexes: [130, 108] - TEC:  76.5

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -15.9° to  -15.4° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -15.9°,  -56.5°) =  77.9
   f_01 (lat_min, lon_max) = ( -15.9°,  -56.0°) =  78.6
   f_10 (lat_max, lon_min) = ( -15.4°,  -56.5°) =  76.6
   f_11 (lat_max, lon_max) = ( -15.4°,  -56.0°) =  76.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -15.9)) / ( -15.4 - ( -15.9))
   t_y = 0.34474 /  0.5 = 0.689480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.689480) = 0.043392
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.689480)       = 0.267128
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.689480       = 0.096348
   w_11 = t_x * t_y             = 0.860260 * 0.689480             = 0.593132
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.043392* 77.9 + 0.267128* 78.6 + 0.096348* 76.6 + 0.593132* 76.5
   Value =   3.3819 +  20.9895 +   7.3820 +  45.3839
   Value = 77.137211

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  68.95% of the way from -15.900000000000006° to -15.400000000000006°

============================================================
FINAL RESULT: TEC = 77.1372
============================================================

## 12/18/2024 - 18:30

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4830 2024-12-18 18:30:00  [[21.299997329711914, 21.299997329711914, 21.2...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.29999733, 21.29999733, 21.29999733, ...,         nan,
                 nan,         nan],
        [21.28308678, 21.28308678, 21.28308678, ...,         nan,
                 nan,         nan],
        ...,
        [39.65393066, 40.11976624, 40.50592804, ..., 13.14062977,
         12.80635357, 12.63247967],
        [39.26050949, 39.7519455 , 40.19271851, ..., 12.65815067,
         12.54124069, 12.46903992],
        [39.23273468, 39.40169144, 39.72786331, ..., 12.41631317,
         12.32884121, 12.25786972]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(nagoya_points)

[(-15.900000000000006, -56.5, 129, 107), (-15.900000000000006, -56.0, 129, 108), (-15.400000000000006, -56.5, 130, 107), (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_points

[(-15.900000000000006, -56.5, 129, 107),
 (-15.900000000000006, -56.0, 129, 108),
 (-15.400000000000006, -56.5, 130, 107),
 (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -15.9°,  -56.5°) - Indexes: [129, 107] - TEC:  80.5
   P2: ( -15.9°,  -56.0°) - Indexes: [129, 108] - TEC:  80.5
   P3: ( -15.4°,  -56.5°) - Indexes: [130, 107] - TEC:  80.5
   P4: ( -15.4°,  -56.0°) - Indexes: [130, 108] - TEC:  80.5

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -15.9° to  -15.4° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -15.9°,  -56.5°) =  80.5
   f_01 (lat_min, lon_max) = ( -15.9°,  -56.0°) =  80.5
   f_10 (lat_max, lon_min) = ( -15.4°,  -56.5°) =  80.5
   f_11 (lat_max, lon_max) = ( -15.4°,  -56.0°) =  80.5

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -15.9)) / ( -15.4 - ( -15.9))
   t_y = 0.34474 /  0.5 = 0.689480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.689480) = 0.043392
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.689480)       = 0.267128
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.689480       = 0.096348
   w_11 = t_x * t_y             = 0.860260 * 0.689480             = 0.593132
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.043392* 80.5 + 0.267128* 80.5 + 0.096348* 80.5 + 0.593132* 80.5
   Value =   3.4918 +  21.4963 +   7.7533 +  47.7305
   Value = 80.471878

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  68.95% of the way from -15.900000000000006° to -15.400000000000006°

============================================================
FINAL RESULT: TEC = 80.4719
============================================================

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(nagoya_points)

[(-15.900000000000006, -56.5, 129, 107), (-15.900000000000006, -56.0, 129, 108), (-15.400000000000006, -56.5, 130, 107), (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_points

[(-15.900000000000006, -56.5, 129, 107),
 (-15.900000000000006, -56.0, 129, 108),
 (-15.400000000000006, -56.5, 130, 107),
 (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -15.9°,  -56.5°) - Indexes: [129, 107] - TEC:  74.9
   P2: ( -15.9°,  -56.0°) - Indexes: [129, 108] - TEC:  75.4
   P3: ( -15.4°,  -56.5°) - Indexes: [130, 107] - TEC:  75.3
   P4: ( -15.4°,  -56.0°) - Indexes: [130, 108] - TEC:  75.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -15.9° to  -15.4° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -15.9°,  -56.5°) =  74.9
   f_01 (lat_min, lon_max) = ( -15.9°,  -56.0°) =  75.4
   f_10 (lat_max, lon_min) = ( -15.4°,  -56.5°) =  75.3
   f_11 (lat_max, lon_max) = ( -15.4°,  -56.0°) =  75.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -15.9)) / ( -15.4 - ( -15.9))
   t_y = 0.34474 /  0.5 = 0.689480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.689480) = 0.043392
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.689480)       = 0.267128
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.689480       = 0.096348
   w_11 = t_x * t_y             = 0.860260 * 0.689480             = 0.593132
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.043392* 74.9 + 0.267128* 75.4 + 0.096348* 75.3 + 0.593132* 75.4
   Value =   3.2518 +  20.1547 +   7.2598 +  44.7515
   Value = 75.417774

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  68.95% of the way from -15.900000000000006° to -15.400000000000006°

============================================================
FINAL RESULT: TEC = 75.4178
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(nagoya_points)

[(-15.900000000000006, -56.5, 129, 107), (-15.900000000000006, -56.0, 129, 108), (-15.400000000000006, -56.5, 130, 107), (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_points

[(-15.900000000000006, -56.5, 129, 107),
 (-15.900000000000006, -56.0, 129, 108),
 (-15.400000000000006, -56.5, 130, 107),
 (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -15.9°,  -56.5°) - Indexes: [129, 107] - TEC:  74.9
   P2: ( -15.9°,  -56.0°) - Indexes: [129, 108] - TEC:  75.4
   P3: ( -15.4°,  -56.5°) - Indexes: [130, 107] - TEC:  75.3
   P4: ( -15.4°,  -56.0°) - Indexes: [130, 108] - TEC:  75.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -15.9° to  -15.4° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -15.9°,  -56.5°) =  74.9
   f_01 (lat_min, lon_max) = ( -15.9°,  -56.0°) =  75.4
   f_10 (lat_max, lon_min) = ( -15.4°,  -56.5°) =  75.3
   f_11 (lat_max, lon_max) = ( -15.4°,  -56.0°) =  75.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -15.9)) / ( -15.4 - ( -15.9))
   t_y = 0.34474 /  0.5 = 0.689480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.689480) = 0.043392
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.689480)       = 0.267128
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.689480       = 0.096348
   w_11 = t_x * t_y             = 0.860260 * 0.689480             = 0.593132
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.043392* 74.9 + 0.267128* 75.4 + 0.096348* 75.3 + 0.593132* 75.4
   Value =   3.2518 +  20.1547 +   7.2598 +  44.7515
   Value = 75.417774

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  68.95% of the way from -15.900000000000006° to -15.400000000000006°

============================================================
FINAL RESULT: TEC = 75.4178
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(nagoya_points)

[(-15.900000000000006, -56.5, 129, 107), (-15.900000000000006, -56.0, 129, 108), (-15.400000000000006, -56.5, 130, 107), (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_points

[(-15.900000000000006, -56.5, 129, 107),
 (-15.900000000000006, -56.0, 129, 108),
 (-15.400000000000006, -56.5, 130, 107),
 (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -15.9°,  -56.5°) - Indexes: [129, 107] - TEC:  74.9
   P2: ( -15.9°,  -56.0°) - Indexes: [129, 108] - TEC:  75.4
   P3: ( -15.4°,  -56.5°) - Indexes: [130, 107] - TEC:  75.3
   P4: ( -15.4°,  -56.0°) - Indexes: [130, 108] - TEC:  75.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -15.9° to  -15.4° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -15.9°,  -56.5°) =  74.9
   f_01 (lat_min, lon_max) = ( -15.9°,  -56.0°) =  75.4
   f_10 (lat_max, lon_min) = ( -15.4°,  -56.5°) =  75.3
   f_11 (lat_max, lon_max) = ( -15.4°,  -56.0°) =  75.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -15.9)) / ( -15.4 - ( -15.9))
   t_y = 0.34474 /  0.5 = 0.689480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.689480) = 0.043392
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.689480)       = 0.267128
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.689480       = 0.096348
   w_11 = t_x * t_y             = 0.860260 * 0.689480             = 0.593132
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.043392* 74.9 + 0.267128* 75.4 + 0.096348* 75.3 + 0.593132* 75.4
   Value =   3.2518 +  20.1547 +   7.2598 +  44.7515
   Value = 75.417774

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  68.95% of the way from -15.900000000000006° to -15.400000000000006°

============================================================
FINAL RESULT: TEC = 75.4178
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_nagoya_maps_2024[df_nagoya_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_nagoya_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_nagoya_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_nagoya_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                DATETIME                                             TECMAP
4824 2024-12-18 18:00:00  [[17.569849014282227, 17.569849014282227, 17.6...

In [ ]:
nagoya_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_nagoya_maps = []
for i in range(len(nagoya_maps)):
    np_nagoya_maps.append(nagoya_maps[i])
np_nagoya_maps = np.array(np_nagoya_maps)

In [ ]:
np_nagoya_maps

array([[[17.56984901, 17.56984901, 17.63764763, ...,         nan,
                 nan,         nan],
        [17.83648491, 17.83648491, 17.8645153 , ...,         nan,
                 nan,         nan],
        [16.60485077, 16.60485077, 16.60485077, ...,         nan,
                 nan,         nan],
        ...,
        [35.25151062, 35.38899231, 35.7537117 , ..., 14.51318359,
         13.86343384, 13.80283642],
        [34.86306763, 34.9417305 , 34.75822449, ..., 14.43698978,
         13.88199997, 13.79667377],
        [34.32035065, 34.41825104, 34.44206238, ..., 14.2071352 ,
         13.66319656, 13.62114334]]])

In [ ]:
np_nagoya_maps.shape

(1, 242, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class nagoya(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80.4, 40.1),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


nagoya_tec = nagoya(extent=(-110, 0, -80.4, 40.1), lat_step=0.5, lon_step=0.5)
nagoya_points = nagoya_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(nagoya_points)

[(-15.900000000000006, -56.5, 129, 107), (-15.900000000000006, -56.0, 129, 108), (-15.400000000000006, -56.5, 130, 107), (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_points

[(-15.900000000000006, -56.5, 129, 107),
 (-15.900000000000006, -56.0, 129, 108),
 (-15.400000000000006, -56.5, 130, 107),
 (-15.400000000000006, -56.0, 130, 108)]

In [ ]:
nagoya_tec.tec_map = np_nagoya_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(nagoya_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = nagoya_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in nagoya_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(nagoya_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in nagoya_points]
lons = [p[1] for p in nagoya_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(nagoya_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -15.9°,  -56.5°) - Indexes: [129, 107] - TEC:  74.9
   P2: ( -15.9°,  -56.0°) - Indexes: [129, 108] - TEC:  75.4
   P3: ( -15.4°,  -56.5°) - Indexes: [130, 107] - TEC:  75.3
   P4: ( -15.4°,  -56.0°) - Indexes: [130, 108] - TEC:  75.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -15.9° to  -15.4° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -15.9°,  -56.5°) =  74.9
   f_01 (lat_min, lon_max) = ( -15.9°,  -56.0°) =  75.4
   f_10 (lat_max, lon_min) = ( -15.4°,  -56.5°) =  75.3
   f_11 (lat_max, lon_max) = ( -15.4°,  -56.0°) =  75.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -15.9)) / ( -15.4 - ( -15.9))
   t_y = 0.34474 /  0.5 = 0.689480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.689480) = 0.043392
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.689480)       = 0.267128
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.689480       = 0.096348
   w_11 = t_x * t_y             = 0.860260 * 0.689480             = 0.593132
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.043392* 74.9 + 0.267128* 75.4 + 0.096348* 75.3 + 0.593132* 75.4
   Value =   3.2518 +  20.1547 +   7.2598 +  44.7515
   Value = 75.417774

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  68.95% of the way from -15.900000000000006° to -15.400000000000006°

============================================================
FINAL RESULT: TEC = 75.4178
============================================================

# EMBRACE

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
!gdown '1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH'

Downloading...
From (original): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH
From (redirected): https://drive.google.com/uc?id=1LkY0IeFfdnahoH81OKYW-2xmXHgjFPhH&confirm=t&uuid=05255cab-b84f-460a-ab43-2751a85b90cc
To: /content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl
100% 157M/157M [00:00<00:00, 162MB/s]

In [ ]:
df_embrace_maps_2024 = pd.read_pickle('/content/TF_EMBRACE_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_embrace_maps_2024

                                                                TECMAP
DATETIME
2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-09-05 00:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[16704 rows x 1 columns]

## 12/18/2024 - 18:20

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(embrace_points)

[(-16, -57.5, 22, 13), (-16, -55.0, 22, 14), (-14, -57.5, 23, 13), (-14, -55.0, 23, 14)]

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  77.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  81.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  78.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  76.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  77.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  81.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  78.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x = 1.43013 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.44474 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 77.0 + 0.444845* 81.0 + 0.095163* 78.0 + 0.127207* 76.0
   Value =  25.6245 +  36.0324 +   7.4227 +   9.6677
   Value = 78.747335

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 78.7473
============================================================

## 12/18/2024 - 18:10

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 37., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(embrace_points)

[(-16, -57.5, 22, 13), (-16, -55.0, 22, 14), (-14, -57.5, 23, 13), (-14, -55.0, 23, 14)]

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  78.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  80.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  78.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  76.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  78.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  80.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  78.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x = 1.43013 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.44474 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 78.0 + 0.444845* 80.0 + 0.095163* 78.0 + 0.127207* 76.0
   Value =  25.9572 +  35.5876 +   7.4227 +   9.6677
   Value = 78.635275

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 78.6353
============================================================

## 12/18/2024 - 18:30

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 39., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(embrace_points)

[(-16, -57.5, 22, 13), (-16, -55.0, 22, 14), (-14, -57.5, 23, 13), (-14, -55.0, 23, 14)]

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  75.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  81.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  78.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  75.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  75.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  81.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  78.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  75.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x = 1.43013 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.44474 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 75.0 + 0.444845* 81.0 + 0.095163* 78.0 + 0.127207* 75.0
   Value =  24.9589 +  36.0324 +   7.4227 +   9.5405
   Value = 77.954557

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 77.9546
============================================================

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(embrace_points)

[(-16, -57.5, 22, 13), (-16, -55.0, 22, 14), (-14, -57.5, 23, 13), (-14, -55.0, 23, 14)]

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  76.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  78.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  77.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  76.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  76.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  78.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  77.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x = 1.43013 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.44474 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 76.0 + 0.444845* 78.0 + 0.095163* 77.0 + 0.127207* 76.0
   Value =  25.2917 +  34.6979 +   7.3275 +   9.6677
   Value = 76.984852

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 76.9849
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(embrace_points)

[(-16, -57.5, 22, 13), (-16, -55.0, 22, 14), (-14, -57.5, 23, 13), (-14, -55.0, 23, 14)]

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  76.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  78.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  77.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  76.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  76.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  78.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  77.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x = 1.43013 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.44474 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 76.0 + 0.444845* 78.0 + 0.095163* 77.0 + 0.127207* 76.0
   Value =  25.2917 +  34.6979 +   7.3275 +   9.6677
   Value = 76.984852

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 76.9849
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(embrace_points)

[(-16, -57.5, 22, 13), (-16, -55.0, 22, 14), (-14, -57.5, 23, 13), (-14, -55.0, 23, 14)]

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  76.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  78.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  77.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  76.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  76.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  78.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  77.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x = 1.43013 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.44474 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 76.0 + 0.444845* 78.0 + 0.095163* 77.0 + 0.127207* 76.0
   Value =  25.2917 +  34.6979 +   7.3275 +   9.6677
   Value = 76.984852

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 76.9849
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

if df_embrace_maps_2024.index.name == 'DATETIME':
    result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
else:
    if 'DATETIME' in df_embrace_maps_2024.columns:
        df_embrace_maps_2024 = df_embrace_maps_2024.set_index('DATETIME')
        result = df_embrace_maps_2024.loc[timestamp_wanted:timestamp_wanted]
    else:
        print("DATETIME column not found!")
        print("Available columns:", df_embrace_maps_2024.columns.tolist())

if result.empty:
    if not isinstance(df_embrace_maps_2024.index, pd.DatetimeIndex):
        df_embrace_maps_2024.index = pd.to_datetime(df_embrace_maps_2024.index)

    timestamp_dt = pd.to_datetime(timestamp_wanted)

    diference = abs((df_embrace_maps_2024.index - timestamp_dt).total_seconds())
    idx_nearest = diference.argmin()

    result = df_embrace_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_embrace_maps_2024.index[idx_nearest]}")

In [ ]:
result

                                                                TECMAP
DATETIME
2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
embrace_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_embrace_maps = []
for i in range(len(embrace_maps)):
    np_embrace_maps.append(embrace_maps[i])
np_embrace_maps = np.array(np_embrace_maps)

In [ ]:
np_embrace_maps

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, 36., nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])

In [ ]:
np_embrace_maps.shape

(1, 41, 25)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class embrace(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-90, -30, -60, 20),
                 lat_step: float = 2,
                 lon_step: float = 2.5):
        super().__init__(extent, lat_step, lon_step)


embrace_tec = embrace(extent=(-90, -30, -60, 20), lat_step=2, lon_step=2.5)
embrace_points = embrace_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(embrace_points)

[(-16, -57.5, 22, 13), (-16, -55.0, 22, 14), (-14, -57.5, 23, 13), (-14, -55.0, 23, 14)]

In [ ]:
embrace_points

[(-16, -57.5, 22, 13),
 (-16, -55.0, 22, 14),
 (-14, -57.5, 23, 13),
 (-14, -55.0, 23, 14)]

In [ ]:
embrace_tec.tec_map = np_embrace_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(embrace_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = embrace_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in embrace_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(embrace_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in embrace_points]
lons = [p[1] for p in embrace_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(embrace_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -57.5°) - Indexes: [22, 13] - TEC:  76.0
   P2: ( -16.0°,  -55.0°) - Indexes: [22, 14] - TEC:  78.0
   P3: ( -14.0°,  -57.5°) - Indexes: [23, 13] - TEC:  77.0
   P4: ( -14.0°,  -55.0°) - Indexes: [23, 14] - TEC:  76.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -14.0° (range:  2.0°)
   Longitude:  -57.5° to  -55.0° (range:  2.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -57.5°) =  76.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -55.0°) =  78.0
   f_10 (lat_max, lon_min) = ( -14.0°,  -57.5°) =  77.0
   f_11 (lat_max, lon_max) = ( -14.0°,  -55.0°) =  76.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -57.5)) / ( -55.0 - ( -57.5))
   t_x = 1.43013 /  2.5 = 0.572052

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -14.0 - ( -16.0))
   t_y = 0.44474 /  2.0 = 0.222370

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.572052) * (1 - 0.222370) = 0.332785
   w_01 = t_x * (1 - t_y)       = 0.572052 * (1 - 0.222370)       = 0.444845
   w_10 = (1 - t_x) * t_y       = (1 - 0.572052) * 0.222370       = 0.095163
   w_11 = t_x * t_y             = 0.572052 * 0.222370             = 0.127207
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.332785* 76.0 + 0.444845* 78.0 + 0.095163* 77.0 + 0.127207* 76.0
   Value =  25.2917 +  34.6979 +   7.3275 +   9.6677
   Value = 76.984852

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 57.21% of the way from -57.5° to -55.0°
   In Y direction (latitude):  22.24% of the way from -16° to -14°

============================================================
FINAL RESULT: TEC = 76.9849
============================================================

# MAGGIA

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Download TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl from https://doi.org/10.5281/zenodo.15453941

In [ ]:
!gdown '1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33'

Downloading...
From (original): https://drive.google.com/uc?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33
From (redirected): https://drive.google.com/uc?id=1Qi7Xm93lhuwGWQnr3N-gquhzzUxegI33&confirm=t&uuid=1759b768-0fbb-4cdc-8ef2-91e32d563f43
To: /content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl
100% 7.51G/7.51G [01:11<00:00, 106MB/s]

In [ ]:
df_maggia_maps_2024 = pd.read_pickle('/content/TF_MAGGIA_TEC_maps_intersection_case_study_from_Sept_05_2024_to_Dec_2024.pkl')

In [ ]:
df_maggia_maps_2024

                 DATETIME                                             TECMAP
0     2024-09-05 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2024-09-05 00:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2024-09-05 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2024-09-05 00:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2024-09-05 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
15619 2024-12-31 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15620 2024-12-31 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15621 2024-12-31 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15622 2024-12-31 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
15623 2024-12-31 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[15624 rows x 2 columns]

## 12/18/2024 - 18:20

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:20:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13718 2024-12-18 18:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [40.14899826, 40.15000153, 40.18000031, ..., 13.84500027,
         13.67500019, 13.12800026],
        [39.97399902, 40.02799988, 40.15399933, ..., 13.75800037,
         13.67599964, 12.39599991],
        [39.73500061, 39.83499908, 40.02500153, ..., 13.10700035,
         12.6239996 , 12.06000042]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(maggia_points)

[(-16.0, -56.5, 128, 107), (-16.0, -56.0, 128, 108), (-15.5, -56.5, 129, 107), (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  97.8
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  98.8
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  97.7
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  98.8

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  97.8
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  98.8
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  97.7
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  98.8

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.44474 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 97.8 + 0.095076* 98.8 + 0.124296* 97.7 + 0.765184* 98.8
   Value =   1.5098 +   9.3938 +  12.1409 +  75.6025
   Value = 98.646921

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 98.6469
============================================================

## 12/18/2024 - 18:10

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:10:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13717 2024-12-18 18:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [36.83499908, 37.06399918, 37.23899841, ..., 12.40799999,
         12.40799999, 12.40799999],
        [36.57699966, 36.82799911, 37.03300095, ..., 12.85900021,
         12.6619997 , 12.54399967],
        [36.34600067, 36.5909996 , 36.81399918, ..., 13.00500011,
         12.82999992, 12.32600021]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(maggia_points)

[(-16.0, -56.5, 128, 107), (-16.0, -56.0, 128, 108), (-15.5, -56.5, 129, 107), (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  96.8
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  97.2
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  96.6
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  96.6

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  96.8
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  97.2
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  96.6
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  96.6

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.44474 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 96.8 + 0.095076* 97.2 + 0.124296* 96.6 + 0.765184* 96.6
   Value =   1.4954 +   9.2372 +  12.0128 +  73.9527
   Value = 96.698223

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 96.6982
============================================================

## 12/18/2024 - 18:30

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:30:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13719 2024-12-18 18:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [41.94900131, 41.94900131, 41.94900131, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.94400024, 41.94400024, 41.94499969, ..., 11.0880003 ,
         11.0880003 , 11.0880003 ],
        [41.89500046, 41.89799881, 41.90100098, ..., 11.36600018,
         11.25800037, 11.1960001 ]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(maggia_points)

[(-16.0, -56.5, 128, 107), (-16.0, -56.0, 128, 108), (-15.5, -56.5, 129, 107), (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  86.0
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  86.0
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  86.0
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  86.0

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  86.0
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  86.0
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  86.0
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  86.0

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.44474 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 86.0 + 0.095076* 86.0 + 0.124296* 86.0 + 0.765184* 86.0
   Value =   1.3281 +   8.1760 +  10.6887 +  65.8012
   Value = 85.994003

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 85.9940
============================================================

## 12/18/2024 - 18:00

In [ ]:
import pandas as pd

date = '2024-12-18'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(maggia_points)

[(-16.0, -56.5, 128, 107), (-16.0, -56.0, 128, 108), (-15.5, -56.5, 129, 107), (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  94.5
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  94.5
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  94.5
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  94.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  94.5
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  94.5
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  94.5
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  94.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.44474 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 94.5 + 0.095076* 94.5 + 0.124296* 94.5 + 0.765184* 94.4
   Value =   1.4599 +   8.9873 +  11.7494 +  72.2502
   Value = 94.446888

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 94.4469
============================================================

## 12/22/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-22'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(maggia_points)

[(-16.0, -56.5, 128, 107), (-16.0, -56.0, 128, 108), (-15.5, -56.5, 129, 107), (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  94.5
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  94.5
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  94.5
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  94.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  94.5
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  94.5
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  94.5
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  94.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.44474 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 94.5 + 0.095076* 94.5 + 0.124296* 94.5 + 0.765184* 94.4
   Value =   1.4599 +   8.9873 +  11.7494 +  72.2502
   Value = 94.446888

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 94.4469
============================================================

## 12/19/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-19'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(maggia_points)

[(-16.0, -56.5, 128, 107), (-16.0, -56.0, 128, 108), (-15.5, -56.5, 129, 107), (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  94.5
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  94.5
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  94.5
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  94.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  94.5
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  94.5
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  94.5
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  94.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.44474 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 94.5 + 0.095076* 94.5 + 0.124296* 94.5 + 0.765184* 94.4
   Value =   1.4599 +   8.9873 +  11.7494 +  72.2502
   Value = 94.446888

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 94.4469
============================================================

## 12/01/2024 - 18:00

In [ ]:
import pandas as pd

data = '2024-12-01'
time = '18:00:00'
timestamp_wanted = f'{date} {time}'

result = df_maggia_maps_2024[df_maggia_maps_2024['DATETIME'] == timestamp_wanted]

if result.empty:
    df_temp = df_maggia_maps_2024.copy()
    df_temp['DATETIME'] = pd.to_datetime(df_temp['DATETIME'])
    timestamp_dt = pd.to_datetime(timestamp_wanted)

    df_temp['diff'] = abs((df_temp['DATETIME'] - timestamp_dt).dt.total_seconds())
    idx_nearest = df_temp['diff'].idxmin()

    result = df_maggia_maps_2024.iloc[[idx_nearest]]
    print(f"Exact date not found. Using closest record: {df_maggia_maps_2024.iloc[idx_nearest]['DATETIME']}")

In [ ]:
result

                 DATETIME                                             TECMAP
13716 2024-12-18 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

In [ ]:
maggia_maps = np.array(result.iloc[:]['TECMAP'])

In [ ]:
np_maggia_maps = []
for i in range(len(maggia_maps)):
    np_maggia_maps.append(maggia_maps[i])
np_maggia_maps = np.array(np_maggia_maps)

In [ ]:
np_maggia_maps

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [34.4980011 , 34.72600174, 34.9109993 , ..., 13.43500042,
         13.27900028, 12.76099968],
        [34.2859993 , 34.53300095, 34.74300003, ..., 13.2489996 ,
         12.7510004 , 12.31400013],
        [34.10699844, 34.35800171, 34.58399963, ..., 12.86299992,
         12.45899963, 12.0880003 ]]])

In [ ]:
np_maggia_maps.shape

(1, 241, 221)

In [ ]:
import numpy as np
from typing import Iterable

class TecMap:
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        self.extent = extent
        self.lat_step = lat_step
        self.lon_step = lon_step

        lon_min, lon_max, lat_min, lat_max = extent
        n_lat = int((lat_max - lat_min) / lat_step) + 1
        n_lon = int((lon_max - lon_min) / lon_step) + 1

        self.grid_shape = (n_lat, n_lon)
        self.tec_map = None

    def find_nearest_points(self, lat: float, lon: float):

        lon_min, lon_max, lat_min, lat_max = self.extent
        lat_step, lon_step = self.lat_step, self.lon_step

        lat_idx_lower = int((lat - lat_min) / lat_step)
        lat_idx_upper = lat_idx_lower + 1

        lat_idx_lower = max(0, min(lat_idx_lower, self.grid_shape[0] - 1))
        lat_idx_upper = max(0, min(lat_idx_upper, self.grid_shape[0] - 1))

        lon_idx_lower = int((lon - lon_min) / lon_step)
        lon_idx_upper = lon_idx_lower + 1

        lon_idx_lower = max(0, min(lon_idx_lower, self.grid_shape[1] - 1))
        lon_idx_upper = max(0, min(lon_idx_upper, self.grid_shape[1] - 1))

        lat_lower = lat_min + lat_idx_lower * lat_step
        lat_upper = lat_min + lat_idx_upper * lat_step
        lon_lower = lon_min + lon_idx_lower * lon_step
        lon_upper = lon_min + lon_idx_upper * lon_step

        points = []

        if lat_idx_lower != lat_idx_upper and lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower),
                (lat_upper, lon_upper, lat_idx_upper, lon_idx_upper)
            ]
        elif lat_idx_lower != lat_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_upper, lon_lower, lat_idx_upper, lon_idx_lower)
            ]
        elif lon_idx_lower != lon_idx_upper:
            points = [
                (lat_lower, lon_lower, lat_idx_lower, lon_idx_lower),
                (lat_lower, lon_upper, lat_idx_lower, lon_idx_upper)
            ]
        else:
            points = [(lat_lower, lon_lower, lat_idx_lower, lon_idx_lower)]

        return points


class maggia(TecMap):
    def __init__(self,
                 extent: Iterable[float] = (-110, 0, -80, 40),
                 lat_step: float = 0.5,
                 lon_step: float = 0.5):
        super().__init__(extent, lat_step, lon_step)


maggia_tec = maggia(extent=(-110, 0, -80, 40), lat_step=0.5, lon_step=0.5)
maggia_points = maggia_tec.find_nearest_points(lat=-15.55526, lon=-56.06987)
print(maggia_points)

[(-16.0, -56.5, 128, 107), (-16.0, -56.0, 128, 108), (-15.5, -56.5, 129, 107), (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_points

[(-16.0, -56.5, 128, 107),
 (-16.0, -56.0, 128, 108),
 (-15.5, -56.5, 129, 107),
 (-15.5, -56.0, 129, 108)]

In [ ]:
maggia_tec.tec_map = np_maggia_maps[0]

print("=" * 60)
print("DETAILED BILINEAR INTERPOLATION ANALYSIS")
print("=" * 60)

print("\n1. THE 4 CLOSEST POINTS:")
for i, point in enumerate(maggia_points):
    lat, lon, lat_idx, lon_idx = point
    tec_value = maggia_tec.tec_map[lat_idx, lon_idx]
    print(f"   P{i+1}: ({lat:+6.1f}°, {lon:+6.1f}°) - Indexes: [{lat_idx:2d}, {lon_idx:2d}] - TEC: {tec_value:5.1f}")

target_lat = -15.55526
target_lon = -56.06987

print(f"\n2. TARGET POINT: ({target_lat:+6.5f}°, {target_lon:+6.5f}°)")

# Collect values and coordinates
values = []
for point in maggia_points:
    lat, lon, lat_idx, lon_idx = point
    values.append(maggia_tec.tec_map[lat_idx, lon_idx])

lats = [p[0] for p in maggia_points]
lons = [p[1] for p in maggia_points]

lat_min, lat_max = min(lats), max(lats)
lon_min, lon_max = min(lons), max(lons)

print(f"\n3. INTERPOLATION RECTANGLE BOUNDS:")
print(f"   Latitude:  {lat_min:+6.1f}° to {lat_max:+6.1f}° (range: {lat_max - lat_min:4.1f}°)")
print(f"   Longitude: {lon_min:+6.1f}° to {lon_max:+6.1f}° (range: {lon_max - lon_min:4.1f}°)")

# Value mapping
point_values = {}
for i, point in enumerate(maggia_points):
    point_values[(point[0], point[1])] = values[i]

f_00 = point_values[(lat_min, lon_min)]  # Bottom-left corner
f_01 = point_values[(lat_min, lon_max)]  # Bottom-right corner
f_10 = point_values[(lat_max, lon_min)]  # Top-left corner
f_11 = point_values[(lat_max, lon_max)]  # Top-right corner

print(f"\n4. TEC VALUES MAPPING:")
print(f"   f_00 (lat_min, lon_min) = ({lat_min:+6.1f}°, {lon_min:+6.1f}°) = {f_00:5.1f}")
print(f"   f_01 (lat_min, lon_max) = ({lat_min:+6.1f}°, {lon_max:+6.1f}°) = {f_01:5.1f}")
print(f"   f_10 (lat_max, lon_min) = ({lat_max:+6.1f}°, {lon_min:+6.1f}°) = {f_10:5.1f}")
print(f"   f_11 (lat_max, lon_max) = ({lat_max:+6.1f}°, {lon_max:+6.1f}°) = {f_11:5.1f}")

# Interpolation parameters calculation
t_x = (target_lon - lon_min) / (lon_max - lon_min) if lon_max != lon_min else 0
t_y = (target_lat - lat_min) / (lat_max - lat_min) if lat_max != lat_min else 0

print(f"\n5. INTERPOLATION PARAMETERS:")
print(f"   t_x = (target_lon - lon_min) / (lon_max - lon_min)")
print(f"   t_x = ({target_lon:+6.5f} - ({lon_min:+6.1f})) / ({lon_max:+6.1f} - ({lon_min:+6.1f}))")
print(f"   t_x = {target_lon - lon_min:6.5f} / {lon_max - lon_min:4.1f} = {t_x:.6f}")
print(f"   ")
print(f"   t_y = (target_lat - lat_min) / (lat_max - lat_min)")
print(f"   t_y = ({target_lat:+6.5f} - ({lat_min:+6.1f})) / ({lat_max:+6.1f} - ({lat_min:+6.1f}))")
print(f"   t_y = {target_lat - lat_min:6.5f} / {lat_max - lat_min:4.1f} = {t_y:.6f}")

# Weight calculations
w_00 = (1 - t_x) * (1 - t_y)
w_01 = t_x * (1 - t_y)
w_10 = (1 - t_x) * t_y
w_11 = t_x * t_y

print(f"\n6. INTERPOLATION WEIGHTS:")
print(f"   w_00 = (1 - t_x) * (1 - t_y) = (1 - {t_x:.6f}) * (1 - {t_y:.6f}) = {w_00:.6f}")
print(f"   w_01 = t_x * (1 - t_y)       = {t_x:.6f} * (1 - {t_y:.6f})       = {w_01:.6f}")
print(f"   w_10 = (1 - t_x) * t_y       = (1 - {t_x:.6f}) * {t_y:.6f}       = {w_10:.6f}")
print(f"   w_11 = t_x * t_y             = {t_x:.6f} * {t_y:.6f}             = {w_11:.6f}")
print(f"   Sum of weights = {w_00 + w_01 + w_10 + w_11:.6f} (should be 1.0)")

# Final interpolation
interpolated_value = w_00 * f_00 + w_01 * f_01 + w_10 * f_10 + w_11 * f_11

print(f"\n7. FINAL CALCULATION:")
print(f"   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11")
print(f"   Value = {w_00:.6f}*{f_00:5.1f} + {w_01:.6f}*{f_01:5.1f} + {w_10:.6f}*{f_10:5.1f} + {w_11:.6f}*{f_11:5.1f}")
print(f"   Value = {w_00*f_00:8.4f} + {w_01*f_01:8.4f} + {w_10*f_10:8.4f} + {w_11*f_11:8.4f}")
print(f"   Value = {interpolated_value:.6f}")

print(f"\n8. TARGET POINT RELATIVE POSITION:")
print(f"   In X direction (longitude): {t_x*100:.2f}% of the way from {lon_min}° to {lon_max}°")
print(f"   In Y direction (latitude):  {t_y*100:.2f}% of the way from {lat_min}° to {lat_max}°")

print(f"\n{'='*60}")
print(f"FINAL RESULT: TEC = {interpolated_value:.4f}")
print(f"{'='*60}")

============================================================
DETAILED BILINEAR INTERPOLATION ANALYSIS
============================================================

1. THE 4 CLOSEST POINTS:
   P1: ( -16.0°,  -56.5°) - Indexes: [128, 107] - TEC:  94.5
   P2: ( -16.0°,  -56.0°) - Indexes: [128, 108] - TEC:  94.5
   P3: ( -15.5°,  -56.5°) - Indexes: [129, 107] - TEC:  94.5
   P4: ( -15.5°,  -56.0°) - Indexes: [129, 108] - TEC:  94.4

2. TARGET POINT: (-15.55526°, -56.06987°)

3. INTERPOLATION RECTANGLE BOUNDS:
   Latitude:   -16.0° to  -15.5° (range:  0.5°)
   Longitude:  -56.5° to  -56.0° (range:  0.5°)

4. TEC VALUES MAPPING:
   f_00 (lat_min, lon_min) = ( -16.0°,  -56.5°) =  94.5
   f_01 (lat_min, lon_max) = ( -16.0°,  -56.0°) =  94.5
   f_10 (lat_max, lon_min) = ( -15.5°,  -56.5°) =  94.5
   f_11 (lat_max, lon_max) = ( -15.5°,  -56.0°) =  94.4

5. INTERPOLATION PARAMETERS:
   t_x = (target_lon - lon_min) / (lon_max - lon_min)
   t_x = (-56.06987 - ( -56.5)) / ( -56.0 - ( -56.5))
   t_x = 0.43013 /  0.5 = 0.860260

   t_y = (target_lat - lat_min) / (lat_max - lat_min)
   t_y = (-15.55526 - ( -16.0)) / ( -15.5 - ( -16.0))
   t_y = 0.44474 /  0.5 = 0.889480

6. INTERPOLATION WEIGHTS:
   w_00 = (1 - t_x) * (1 - t_y) = (1 - 0.860260) * (1 - 0.889480) = 0.015444
   w_01 = t_x * (1 - t_y)       = 0.860260 * (1 - 0.889480)       = 0.095076
   w_10 = (1 - t_x) * t_y       = (1 - 0.860260) * 0.889480       = 0.124296
   w_11 = t_x * t_y             = 0.860260 * 0.889480             = 0.765184
   Sum of weights = 1.000000 (should be 1.0)

7. FINAL CALCULATION:
   Value = w_00*f_00 + w_01*f_01 + w_10*f_10 + w_11*f_11
   Value = 0.015444* 94.5 + 0.095076* 94.5 + 0.124296* 94.5 + 0.765184* 94.4
   Value =   1.4599 +   8.9873 +  11.7494 +  72.2502
   Value = 94.446888

8. TARGET POINT RELATIVE POSITION:
   In X direction (longitude): 86.03% of the way from -56.5° to -56.0°
   In Y direction (latitude):  88.95% of the way from -16.0° to -15.5°

============================================================
FINAL RESULT: TEC = 94.4469
============================================================