# Zip files adjusts

In [1]:
# Download MAGGIA_TEC_maps_intersection_raw_files_2022_2024.zip from https://doi.org/10.5281/zenodo.15453941

In [2]:
!gdown '1xJJ9V8lM7GYhbNNHvXSDgB0AiyfrZvFC'

Downloading...
From (original): https://drive.google.com/uc?id=1xJJ9V8lM7GYhbNNHvXSDgB0AiyfrZvFC
From (redirected): https://drive.google.com/uc?id=1xJJ9V8lM7GYhbNNHvXSDgB0AiyfrZvFC&confirm=t&uuid=b9744c7f-2dc5-4fc2-a771-9deef0bbe728
To: /content/MAGGIA_TEC_maps_intersection_raw_files_2022_2024.zip
100% 2.77G/2.77G [00:09<00:00, 277MB/s]

In [3]:
%pwd

'/content'

In [4]:
# !ls

In [5]:
!unzip -q 'MAGGIA_TEC_maps_intersection_raw_files_2022_2024.zip'

# Data files adjusts

## 2022

In [6]:
%pwd

'/content'

In [7]:
%rm *.npy

rm: cannot remove '*.npy': No such file or directory

In [8]:
!ls

MAGGIA_TEC_maps_intersection_raw_files_2022_2024.zip  magn20232692100.nc
magn20220600000.nc				      magn20232692115.nc
magn20220600015.nc				      magn20232692130.nc
magn20220600030.nc				      magn20232692145.nc
magn20220600045.nc				      magn20232692200.nc
magn20220600100.nc				      magn20232692215.nc
magn20220600115.nc				      magn20232692230.nc
magn20220600130.nc				      magn20232692245.nc
magn20220600145.nc				      magn20232692300.nc
magn20220600200.nc				      magn20232692315.nc
magn20220600215.nc				      magn20232692330.nc
magn20220600230.nc				      magn20232692345.nc
magn20220600245.nc				      magn20232700000.nc
magn20220600300.nc				      magn20232700015.nc
magn20220600315.nc				      magn20232700030.nc
magn20220600330.nc				      magn20232700045.nc
magn20220600345.nc				      magn20232700100.nc
magn20220600400.nc				      magn20232700115.nc
magn20220600415.nc				      magn20232700130.nc
magn20220600430.nc				      magn20232700145.nc
magn20220600445.nc				      magn20232700200.nc
magn20220600500.nc				      magn20232700215.nc
magn20220600515.nc				      magn20232700230.nc
magn20220600530.nc				      magn20232700245.nc
magn20220600545.nc				      magn20232700300.nc
magn20220600600.nc				      magn20232700315.nc
magn20220600615.nc				      magn20232700330.nc
magn20220600630.nc				      magn20232700345.nc
magn20220600645.nc				      magn20232700400.nc
magn20220600700.nc				      magn20232700415.nc
magn20220600715.nc				      magn20232700430.nc
magn20220600730.nc				      magn20232700445.nc
magn20220600745.nc				      magn20232700500.nc
magn20220600800.nc				      magn20232700515.nc
magn20220600815.nc				      magn20232700530.nc
magn20220600830.nc				      magn20232700545.nc
magn20220600845.nc				      magn20232700600.nc
magn20220600900.nc				      magn20232700615.nc
magn20220600915.nc				      magn20232700630.nc
magn20220600930.nc				      magn20232700645.nc
magn20220600945.nc				      magn20232700700.nc
magn20220601000.nc				      magn20232700715.nc
magn20220601015.nc				      magn20232700730.nc
magn20220601030.nc				      magn20232700745.nc
magn20220601045.nc				      magn20232700800.nc
magn20220601100.nc				      magn20232700815.nc
magn20220601115.nc				      magn20232700830.nc
magn20220601130.nc				      magn20232700845.nc
magn20220601145.nc				      magn20232700900.nc
magn20220601200.nc				      magn20232700915.nc
magn20220601215.nc				      magn20232700930.nc
magn20220601230.nc				      magn20232700945.nc
magn20220601245.nc				      magn20232701000.nc
magn20220601300.nc				      magn20232701015.nc
magn20220601315.nc				      magn20232701030.nc
magn20220601330.nc				      magn20232701045.nc
magn20220601345.nc				      magn20232701100.nc
magn20220601400.nc				      magn20232701115.nc
magn20220601415.nc				      magn20232701130.nc
magn20220601430.nc				      magn20232701145.nc
magn20220601445.nc				      magn20232701200.nc
magn20220601500.nc				      magn20232701215.nc
magn20220601515.nc				      magn20232701230.nc
magn20220601530.nc				      magn20232701245.nc
magn20220601545.nc				      magn20232701300.nc
magn20220601600.nc				      magn20232701315.nc
magn20220601615.nc				      magn20232701330.nc
magn20220601630.nc				      magn20232701345.nc
magn20220601645.nc				      magn20232701400.nc
magn20220601700.nc				      magn20232701415.nc
magn20220601715.nc				      magn20232701430.nc
magn20220601730.nc				      magn20232701445.nc
magn20220601745.nc				      magn20232701500.nc
magn20220601800.nc				      magn20232701515.nc
magn20220601815.nc				      magn20232701530.nc
magn20220601830.nc				      magn20232701545.nc
magn20220601845.nc				      magn20232701600.nc
magn20220601900.nc				      magn20232701615.nc
magn20220601915.nc				      magn20232701630.nc
magn20220601930.nc				      magn20232701645.nc
magn20220601945.nc				      magn20232701700.nc
magn20220602000.nc				      magn20232701715.nc
magn20220602015.nc				      magn20232701730.nc
magn20220602030.nc				      magn20232701745.nc
magn20220602045.nc				      magn20232701800.nc
magn20220602100.nc				      magn20232701815.nc
magn20220602115.nc				      magn20232701830.nc
magn20220602130.nc				      magn20232701845.nc
magn20220602145.nc				      magn20232701900.nc
magn20220602200.nc				      magn20232701915.nc
magn20220602215.nc				      magn20232701930.nc
magn20220602230.nc				      magn20232701945.nc
magn20220602245.nc				      magn20232702000.nc
magn20220602300.nc				      magn20232702015.nc
magn20220602315.nc				      magn20232702030.nc
magn20220602330.nc				      magn20232702045.nc
magn20220602345.nc				      magn20232702100.nc
magn20220610000.nc				      magn20232702115.nc
magn20220610015.nc				      magn20232702130.nc
magn20220610030.nc				      magn20232702145.nc
magn20220610045.nc				      magn20232702200.nc
magn20220610100.nc				      magn20232702215.nc
magn20220610115.nc				      magn20232702230.nc
magn20220610130.nc				      magn20232702245.nc
magn20220610145.nc				      magn20232702300.nc
magn20220610200.nc				      magn20232702315.nc
magn20220610215.nc				      magn20232702330.nc
magn20220610230.nc				      magn20232702345.nc
magn20220610245.nc				      magn20232710000.nc
magn20220610300.nc				      magn20232710015.nc
magn20220610315.nc				      magn20232710030.nc
magn20220610330.nc				      magn20232710045.nc
magn20220610345.nc				      magn20232710100.nc
magn20220610400.nc				      magn20232710115.nc
magn20220610415.nc				      magn20232710130.nc
magn20220610430.nc				      magn20232710145.nc
magn20220610445.nc				      magn20232710200.nc
magn20220610500.nc				      magn20232710215.nc
magn20220610515.nc				      magn20232710230.nc
magn20220610530.nc				      magn20232710245.nc
magn20220610545.nc				      magn20232710300.nc
magn20220610600.nc				      magn20232710315.nc
magn20220610615.nc				      magn20232710330.nc
magn20220610630.nc				      magn20232710345.nc
magn20220610645.nc				      magn20232710400.nc
magn20220610700.nc				      magn20232710415.nc
magn20220610715.nc				      magn20232710430.nc
magn20220610730.nc				      magn20232710445.nc
magn20220610745.nc				      magn20232710500.nc
magn20220610800.nc				      magn20232710515.nc
magn20220610815.nc				      magn20232710530.nc
magn20220610830.nc				      magn20232710545.nc
magn20220610845.nc				      magn20232710600.nc
magn20220610900.nc				      magn20232710615.nc
magn20220610915.nc				      magn20232710630.nc
magn20220610930.nc				      magn20232710645.nc
magn20220610945.nc				      magn20232710700.nc
magn20220611000.nc				      magn20232710715.nc
magn20220611015.nc				      magn20232710730.nc
magn20220611030.nc				      magn20232710745.nc
magn20220611045.nc				      magn20232710800.nc
magn20220611100.nc				      magn20232710815.nc
magn20220611115.nc				      magn20232710830.nc
magn20220611130.nc				      magn20232710845.nc
magn20220611145.nc				      magn20232710900.nc
magn20220611200.nc				      magn20232710915.nc
magn20220611215.nc				      magn20232710930.nc
magn20220611230.nc				      magn20232710945.nc
magn20220611245.nc				      magn20232711000.nc
magn20220611300.nc				      magn20232711015.nc
magn20220611315.nc				      magn20232711030.nc
magn20220611330.nc				      magn20232711045.nc
magn20220611345.nc				      magn20232711100.nc
magn20220611400.nc				      magn20232711115.nc
magn20220611415.nc				      magn20232711130.nc
magn20220611430.nc				      magn20232711145.nc
magn20220611445.nc				      magn20232711200.nc
magn20220611500.nc				      magn20232711215.nc
magn20220611515.nc				      magn20232711230.nc
magn20220611530.nc				      magn20232711245.nc
magn20220611545.nc				      magn20232711300.nc
magn20220611600.nc				      magn20232711315.nc
magn20220611615.nc				      magn20232711330.nc
magn20220611630.nc				      magn20232711345.nc
magn20220611645.nc				      magn20232711400.nc
magn20220611700.nc				      magn20232711415.nc
magn20220611715.nc				      magn20232711430.nc
magn20220611730.nc				      magn20232711445.nc
magn20220611745.nc				      magn20232711500.nc
magn20220611800.nc				      magn20232711515.nc
magn20220611815.nc				      magn20232711530.nc
magn20220611830.nc				      magn20232711545.nc
magn20220611845.nc				      magn20232711600.nc
magn20220611900.nc				      magn20232711615.nc
magn20220611915.nc				      magn20232711630.nc
magn20220611930.nc				      magn20232711645.nc
magn20220611945.nc				      magn20232711700.nc
magn20220612000.nc				      magn20232711715.nc
magn20220612015.nc				      magn20232711730.nc
magn20220612030.nc				      magn20232711745.nc
magn20220612045.nc				      magn20232711800.nc
magn20220612100.nc				      magn20232711815.nc
magn20220612115.nc				      magn20232711830.nc
magn20220612130.nc				      magn20232711845.nc
magn20220612145.nc				      magn20232711900.nc
magn20220612200.nc				      magn20232711915.nc
magn20220612215.nc				      magn20232711930.nc
magn20220612230.nc				      magn20232711945.nc
magn20220612245.nc				      magn20232712000.nc
magn20220612300.nc				      magn20232712015.nc
magn20220612315.nc				      magn20232712030.nc
magn20220612330.nc				      magn20232712045.nc
magn20220612345.nc				      magn20232712100.nc
magn20220620000.nc				      magn20232712115.nc
magn20220620015.nc				      magn20232712130.nc
magn20220620030.nc				      magn20232712145.nc
magn20220620045.nc				      magn20232712200.nc
magn20220620100.nc				      magn20232712215.nc
magn20220620115.nc				      magn20232712230.nc
magn20220620130.nc				      magn20232712245.nc
magn20220620145.nc				      magn20232712300.nc
magn20220620200.nc				      magn20232712315.nc
magn20220620215.nc				      magn20232712330.nc
magn20220620230.nc				      magn20232712345.nc
magn20220620245.nc				      magn20232720000.nc
magn20220620300.nc				      magn20232720015.nc
magn20220620315.nc				      magn20232720030.nc
magn20220620330.nc				      magn20232720045.nc
magn20220620345.nc				      magn20232720100.nc
magn20220620400.nc				      magn20232720115.nc
magn20220620415.nc				      magn20232720130.nc
magn20220620430.nc				      magn20232720145.nc
magn20220620445.nc				      magn20232720200.nc
magn20220620500.nc				      magn20232720215.nc
magn20220620515.nc				      magn20232720230.nc
magn20220620530.nc				      magn20232720245.nc
magn20220620545.nc				      magn20232720300.nc
magn20220620600.nc				      magn20232720315.nc
magn20220620615.nc				      magn20232720330.nc
magn20220620630.nc				      magn20232720345.nc
magn20220620645.nc				      magn20232720400.nc
magn20220620700.nc				      magn20232720415.nc
magn20220620715.nc				      magn20232720430.nc
magn20220620730.nc				      magn20232720445.nc
magn20220620745.nc				      magn20232720500.nc
magn20220620800.nc				      magn20232720515.nc
magn20220620815.nc				      magn20232720530.nc
magn20220620830.nc				      magn20232720545.nc
magn20220620845.nc				      magn20232720600.nc
magn20220620900.nc				      magn20232720615.nc
magn20220620915.nc				      magn20232720630.nc
magn20220620930.nc				      magn20232720645.nc
magn20220620945.nc				      magn20232720700.nc
magn20220621000.nc				      magn20232720715.nc
magn20220621015.nc				      magn20232720730.nc
magn20220621030.nc				      magn20232720745.nc
magn20220621045.nc				      magn20232720800.nc
magn20220621100.nc				      magn20232720815.nc
magn20220621115.nc				      magn20232720830.nc
magn20220621130.nc				      magn20232720845.nc
magn20220621145.nc				      magn20232720900.nc
magn20220621200.nc				      magn20232720915.nc
magn20220621215.nc				      magn20232720930.nc
magn20220621230.nc				      magn20232720945.nc
magn20220621245.nc				      magn20232721000.nc
magn20220621300.nc				      magn20232721015.nc
magn20220621315.nc				      magn20232721030.nc
magn20220621330.nc				      magn20232721045.nc
magn20220621345.nc				      magn20232721100.nc
magn20220621400.nc				      magn20232721115.nc
magn20220621415.nc				      magn20232721130.nc
magn20220621430.nc				      magn20232721145.nc
magn20220621445.nc				      magn20232721200.nc
magn20220621500.nc				      magn20232721215.nc
magn20220621515.nc				      magn20232721230.nc
magn20220621530.nc				      magn20232721245.nc
magn20220621545.nc				      magn20232721300.nc
magn20220621600.nc				      magn20232721315.nc
magn20220621615.nc				      magn20232721330.nc
magn20220621630.nc				      magn20232721345.nc
magn20220621645.nc				      magn20232721400.nc
magn20220621700.nc				      magn20232721415.nc
magn20220621715.nc				      magn20232721430.nc
magn20220621730.nc				      magn20232721445.nc
magn20220621745.nc				      magn20232721500.nc
magn20220621800.nc				      magn20232721515.nc
magn20220621815.nc				      magn20232721530.nc
magn20220621830.nc				      magn20232721545.nc
magn20220621845.nc				      magn20232721600.nc
magn20220621900.nc				      magn20232721615.nc
magn20220621915.nc				      magn20232721630.nc
magn20220621930.nc				      magn20232721645.nc
magn20220621945.nc				      magn20232721700.nc
magn20220622000.nc				      magn20232721715.nc
magn20220622015.nc				      magn20232721730.nc
magn20220622030.nc				      magn20232721745.nc
magn20220622045.nc				      magn20232721800.nc
magn20220622100.nc				      magn20232721815.nc
magn20220622115.nc				      magn20232721830.nc
magn20220622130.nc				      magn20232721845.nc
magn20220622145.nc				      magn20232721900.nc
magn20220622200.nc				      magn20232721915.nc
magn20220622215.nc				      magn20232721930.nc
magn20220622230.nc				      magn20232721945.nc
magn20220622245.nc				      magn20232722000.nc
magn20220622300.nc				      magn20232722015.nc
magn20220622315.nc				      magn20232722030.nc
magn20220622330.nc				      magn20232722045.nc
magn20220622345.nc				      magn20232722100.nc
magn20220630000.nc				      magn20232722115.nc
magn20220630015.nc				      magn20232722130.nc
magn20220630030.nc				      magn20232722145.nc
magn20220630045.nc				      magn20232722200.nc
magn20220630100.nc				      magn20232722215.nc
magn20220630115.nc				      magn20232722230.nc
magn20220630130.nc				      magn20232722245.nc
magn20220630145.nc				      magn20232722300.nc
magn20220630200.nc				      magn20232722315.nc
magn20220630215.nc				      magn20232722330.nc
magn20220630230.nc				      magn20232722345.nc
magn20220630245.nc				      magn20232730000.nc
magn20220630300.nc				      magn20232730015.nc
magn20220630315.nc				      magn20232730030.nc
magn20220630330.nc				      magn20232730045.nc
magn20220630345.nc				      magn20232730100.nc
magn20220630400.nc				      magn20232730115.nc
magn20220630415.nc				      magn20232730130.nc
magn20220630430.nc				      magn20232730145.nc
magn20220630445.nc				      magn20232730200.nc
magn20220630500.nc				      magn20232730215.nc
magn20220630515.nc				      magn20232730230.nc
magn20220630530.nc				      magn20232730245.nc
magn20220630545.nc				      magn20232730300.nc
magn20220630600.nc				      magn20232730315.nc
magn20220630615.nc				      magn20232730330.nc
magn20220630630.nc				      magn20232730345.nc
magn20220630645.nc				      magn20232730400.nc
magn20220630700.nc				      magn20232730415.nc
magn20220630715.nc				      magn20232730430.nc
magn20220630730.nc				      magn20232730445.nc
magn20220630745.nc				      magn20232730500.nc
magn20220630800.nc				      magn20232730515.nc
magn20220630815.nc				      magn20232730530.nc
magn20220630830.nc				      magn20232730545.nc
magn20220630845.nc				      magn20232730600.nc
magn20220630900.nc				      magn20232730615.nc
magn20220630915.nc				      magn20232730630.nc
magn20220630930.nc				      magn20232730645.nc
magn20220630945.nc				      magn20232730700.nc
magn20220631000.nc				      magn20232730715.nc
magn20220631015.nc				      magn20232730730.nc
magn20220631030.nc				      magn20232730745.nc
magn20220631045.nc				      magn20232730800.nc
magn20220631100.nc				      magn20232730815.nc
magn20220631115.nc				      magn20232730830.nc
magn20220631130.nc				      magn20232730845.nc
magn20220631145.nc				      magn20232730900.nc
magn20220631200.nc				      magn20232730915.nc
magn20220631215.nc				      magn20232730930.nc
magn20220631230.nc				      magn20232730945.nc
magn20220631245.nc				      magn20232731000.nc
magn20220631300.nc				      magn20232731015.nc
magn20220631315.nc				      magn20232731030.nc
magn20220631330.nc				      magn20232731045.nc
magn20220631345.nc				      magn20232731100.nc
magn20220631400.nc				      magn20232731115.nc
magn20220631415.nc				      magn20232731130.nc
magn20220631430.nc				      magn20232731145.nc
magn20220631445.nc				      magn20232731200.nc
magn20220631500.nc				      magn20232731215.nc
magn20220631515.nc				      magn20232731230.nc
magn20220631530.nc				      magn20232731245.nc
magn20220631545.nc				      magn20232731300.nc
magn20220631600.nc				      magn20232731315.nc
magn20220631615.nc				      magn20232731330.nc
magn20220631630.nc				      magn20232731345.nc
magn20220631645.nc				      magn20232731400.nc
magn20220631700.nc				      magn20232731415.nc
magn20220631715.nc				      magn20232731430.nc
magn20220631730.nc				      magn20232731445.nc
magn20220631745.nc				      magn20232731500.nc
magn20220631800.nc				      magn20232731515.nc
magn20220631815.nc				      magn20232731530.nc
magn20220631830.nc				      magn20232731545.nc
magn20220631845.nc				      magn20232731600.nc
magn20220631900.nc				      magn20232731615.nc
magn20220631915.nc				      magn20232731630.nc
magn20220631930.nc				      magn20232731645.nc
magn20220631945.nc				      magn20232731700.nc
magn20220632000.nc				      magn20232731715.nc
magn20220632015.nc				      magn20232731730.nc
magn20220632030.nc				      magn20232731745.nc
magn20220632045.nc				      magn20232731800.nc
magn20220632100.nc				      magn20232731815.nc
magn20220632115.nc				      magn20232731830.nc
magn20220632130.nc				      magn20232731845.nc
magn20220632145.nc				      magn20232731900.nc
magn20220632200.nc				      magn20232731915.nc
magn20220632215.nc				      magn20232731930.nc
magn20220632230.nc				      magn20232731945.nc
magn20220632245.nc				      magn20232732000.nc
magn20220632300.nc				      magn20232732015.nc
magn20220632315.nc				      magn20232732030.nc
magn20220632330.nc				      magn20232732045.nc
magn20220632345.nc				      magn20232732100.nc
magn20220640000.nc				      magn20232732115.nc
magn20220640015.nc				      magn20232732130.nc
magn20220640030.nc				      magn20232732145.nc
magn20220640045.nc				      magn20232732200.nc
magn20220640100.nc				      magn20232732215.nc
magn20220640115.nc				      magn20232732230.nc
magn20220640130.nc				      magn20232732245.nc
magn20220640145.nc				      magn20232732300.nc
magn20220640200.nc				      magn20232732315.nc
magn20220640215.nc				      magn20232732330.nc
magn20220640230.nc				      magn20232732345.nc
magn20220640245.nc				      magn20233350000.nc
magn20220640300.nc				      magn20233350015.nc
magn20220640315.nc				      magn20233350030.nc
magn20220640330.nc				      magn20233350045.nc
magn20220640345.nc				      magn20233350100.nc
magn20220640400.nc				      magn20233350115.nc
magn20220640415.nc				      magn20233350130.nc
magn20220640430.nc				      magn20233350145.nc
magn20220640445.nc				      magn20233350200.nc
magn20220640500.nc				      magn20233350215.nc
magn20220640515.nc				      magn20233350230.nc
magn20220640530.nc				      magn20233350245.nc
magn20220640545.nc				      magn20233350300.nc
magn20220640600.nc				      magn20233350315.nc
magn20220640615.nc				      magn20233350330.nc
magn20220640630.nc				      magn20233350345.nc
magn20220640645.nc				      magn20233350400.nc
magn20220640700.nc				      magn20233350415.nc
magn20220640715.nc				      magn20233350430.nc
magn20220640730.nc				      magn20233350445.nc
magn20220640745.nc				      magn20233350500.nc
magn20220640800.nc				      magn20233350515.nc
magn20220640815.nc				      magn20233350530.nc
magn20220640830.nc				      magn20233350545.nc
magn20220640845.nc				      magn20233350600.nc
magn20220640900.nc				      magn20233350615.nc
magn20220640915.nc				      magn20233350630.nc
magn20220640930.nc				      magn20233350645.nc

In [9]:
import os
import glob
from collections import defaultdict

base_path = './'

file_pattern = os.path.join(base_path, '**', 'magn2022*.nc')
file_list = sorted(glob.glob(file_pattern, recursive=True))

file_count_by_day = defaultdict(int)

for file_name in file_list:

    day_dir = os.path.basename(os.path.dirname(file_name))
    file_count_by_day[day_dir] += 1

print("\nDays with less than 96 files:")

for day, count in sorted(file_count_by_day.items()):
    if count < 96:
        print(f"Dia {day}: {count} arquivos")

Days with less than 96 files:

In [10]:
!pip install netCDF4

Collecting netCDF4
  Downloading netCDF4-1.7.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting cftime (from netCDF4)
  Downloading cftime-1.6.4.post1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from netCDF4) (2025.8.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from netCDF4) (2.0.2)
Downloading netCDF4-1.7.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 42.0 MB/s eta 0:00:00
Downloading cftime-1.6.4.post1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 35.6 MB/s eta 0:00:00
Installing collected packages: cftime, netCDF4
Successfully installed cftime-1.6.4.post1 netCDF4-1.7.2

In [11]:
!pip install xarray

Collecting xarray
  Downloading xarray-2025.9.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from xarray) (2.0.2)
Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.12/dist-packages (from xarray) (25.0)
Requirement already satisfied: pandas>=2.2 in /usr/local/lib/python3.12/dist-packages (from xarray) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->xarray) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->xarray) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->xarray) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2->xarray) (1.17.0)
Downloading xarray-2025.9.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 11.5 MB/s eta 0:00:00
Installing collected packages: xarray
Successfully installed xarray-2025.9.0

In [12]:
import numpy as np
import xarray as xr
import os
import re
import glob

file_list = glob.glob("./magn2022*.nc")

file_list.sort()

tec_by_doy = {}

pattern = re.compile(r'magn2022(\d{3})')

for file_name in file_list:
    try:

        match = pattern.search(file_name)
        if match:
            doy = match.group(1)

            print(f"Processing file: {file_name}, DOY: {doy}")

            ds_disk = xr.open_dataset(file_name)
            tec = ds_disk['z'][:, :].values

            if doy not in tec_by_doy:
                tec_by_doy[doy] = []

            tec_by_doy[doy].append(tec)

            ds_disk.close()

    except Exception as e:
        print(f"Error processing file {file_name}: {e}")

print("\nSaving NPY files per day...")
for doy, tec_list in tec_by_doy.items():

    tec_array = np.array(tec_list)

    output_file = f"magn2022{doy}.npy"
    np.save(output_file, tec_array)

    print(f"File {output_file} saved successfully! Shape: {tec_array.shape}")

print("\Processing completed!")

<>:47: SyntaxWarning: invalid escape sequence '\P'
<>:47: SyntaxWarning: invalid escape sequence '\P'
/tmp/ipython-input-3900763946.py:47: SyntaxWarning: invalid escape sequence '\P'
  print("\Processing completed!")

A saída de streaming foi truncada nas últimas 5000 linhas.
Processing file: ./magn20221712245.nc, DOY: 171
Processing file: ./magn20221712300.nc, DOY: 171
Processing file: ./magn20221712315.nc, DOY: 171
Processing file: ./magn20221712330.nc, DOY: 171
Processing file: ./magn20221712345.nc, DOY: 171
Processing file: ./magn20221720000.nc, DOY: 172
Processing file: ./magn20221720015.nc, DOY: 172
Processing file: ./magn20221720030.nc, DOY: 172
Processing file: ./magn20221720045.nc, DOY: 172
Processing file: ./magn20221720100.nc, DOY: 172
Processing file: ./magn20221720115.nc, DOY: 172
Processing file: ./magn20221720130.nc, DOY: 172
Processing file: ./magn20221720145.nc, DOY: 172
Processing file: ./magn20221720200.nc, DOY: 172
Processing file: ./magn20221720215.nc, DOY: 172
Processing file: ./magn20221720230.nc, DOY: 172
Processing file: ./magn20221720245.nc, DOY: 172
Processing file: ./magn20221720300.nc, DOY: 172
Processing file: ./magn20221720315.nc, DOY: 172
Processing file: ./magn20221720330.nc, DOY: 172
Processing file: ./magn20221720345.nc, DOY: 172
Processing file: ./magn20221720400.nc, DOY: 172
Processing file: ./magn20221720415.nc, DOY: 172
Processing file: ./magn20221720430.nc, DOY: 172
Processing file: ./magn20221720445.nc, DOY: 172
Processing file: ./magn20221720500.nc, DOY: 172
Processing file: ./magn20221720515.nc, DOY: 172
Processing file: ./magn20221720530.nc, DOY: 172
Processing file: ./magn20221720545.nc, DOY: 172
Processing file: ./magn20221720600.nc, DOY: 172
Processing file: ./magn20221720615.nc, DOY: 172
Processing file: ./magn20221720630.nc, DOY: 172
Processing file: ./magn20221720645.nc, DOY: 172
Processing file: ./magn20221720700.nc, DOY: 172
Processing file: ./magn20221720715.nc, DOY: 172
Processing file: ./magn20221720730.nc, DOY: 172
Processing file: ./magn20221720745.nc, DOY: 172
Processing file: ./magn20221720800.nc, DOY: 172
Processing file: ./magn20221720815.nc, DOY: 172
Processing file: ./magn20221720830.nc, DOY: 172
Processing file: ./magn20221720845.nc, DOY: 172
Processing file: ./magn20221720900.nc, DOY: 172
Processing file: ./magn20221720915.nc, DOY: 172
Processing file: ./magn20221720930.nc, DOY: 172
Processing file: ./magn20221720945.nc, DOY: 172
Processing file: ./magn20221721000.nc, DOY: 172
Processing file: ./magn20221721015.nc, DOY: 172
Processing file: ./magn20221721030.nc, DOY: 172
Processing file: ./magn20221721045.nc, DOY: 172
Processing file: ./magn20221721100.nc, DOY: 172
Processing file: ./magn20221721115.nc, DOY: 172
Processing file: ./magn20221721130.nc, DOY: 172
Processing file: ./magn20221721145.nc, DOY: 172
Processing file: ./magn20221721200.nc, DOY: 172
Processing file: ./magn20221721215.nc, DOY: 172
Processing file: ./magn20221721230.nc, DOY: 172
Processing file: ./magn20221721245.nc, DOY: 172
Processing file: ./magn20221721300.nc, DOY: 172
Processing file: ./magn20221721315.nc, DOY: 172
Processing file: ./magn20221721330.nc, DOY: 172
Processing file: ./magn20221721345.nc, DOY: 172
Processing file: ./magn20221721400.nc, DOY: 172
Processing file: ./magn20221721415.nc, DOY: 172
Processing file: ./magn20221721430.nc, DOY: 172
Processing file: ./magn20221721445.nc, DOY: 172
Processing file: ./magn20221721500.nc, DOY: 172
Processing file: ./magn20221721515.nc, DOY: 172
Processing file: ./magn20221721530.nc, DOY: 172
Processing file: ./magn20221721545.nc, DOY: 172
Processing file: ./magn20221721600.nc, DOY: 172
Processing file: ./magn20221721615.nc, DOY: 172
Processing file: ./magn20221721630.nc, DOY: 172
Processing file: ./magn20221721645.nc, DOY: 172
Processing file: ./magn20221721700.nc, DOY: 172
Processing file: ./magn20221721715.nc, DOY: 172
Processing file: ./magn20221721730.nc, DOY: 172
Processing file: ./magn20221721745.nc, DOY: 172
Processing file: ./magn20221721800.nc, DOY: 172
Processing file: ./magn20221721815.nc, DOY: 172
Processing file: ./magn20221721830.nc, DOY: 172
Processing file: ./magn20221721845.nc, DOY: 172
Processing file: ./magn20221721900.nc, DOY: 172
Processing file: ./magn20221721915.nc, DOY: 172
Processing file: ./magn20221721930.nc, DOY: 172
Processing file: ./magn20221721945.nc, DOY: 172
Processing file: ./magn20221722000.nc, DOY: 172
Processing file: ./magn20221722015.nc, DOY: 172
Processing file: ./magn20221722030.nc, DOY: 172
Processing file: ./magn20221722045.nc, DOY: 172
Processing file: ./magn20221722100.nc, DOY: 172
Processing file: ./magn20221722115.nc, DOY: 172
Processing file: ./magn20221722130.nc, DOY: 172
Processing file: ./magn20221722145.nc, DOY: 172
Processing file: ./magn20221722200.nc, DOY: 172
Processing file: ./magn20221722215.nc, DOY: 172
Processing file: ./magn20221722230.nc, DOY: 172
Processing file: ./magn20221722245.nc, DOY: 172
Processing file: ./magn20221722300.nc, DOY: 172
Processing file: ./magn20221722315.nc, DOY: 172
Processing file: ./magn20221722330.nc, DOY: 172
Processing file: ./magn20221722345.nc, DOY: 172
Processing file: ./magn20221730000.nc, DOY: 173
Processing file: ./magn20221730015.nc, DOY: 173
Processing file: ./magn20221730030.nc, DOY: 173
Processing file: ./magn20221730045.nc, DOY: 173
Processing file: ./magn20221730100.nc, DOY: 173
Processing file: ./magn20221730115.nc, DOY: 173
Processing file: ./magn20221730130.nc, DOY: 173
Processing file: ./magn20221730145.nc, DOY: 173
Processing file: ./magn20221730200.nc, DOY: 173
Processing file: ./magn20221730215.nc, DOY: 173
Processing file: ./magn20221730230.nc, DOY: 173
Processing file: ./magn20221730245.nc, DOY: 173
Processing file: ./magn20221730300.nc, DOY: 173
Processing file: ./magn20221730315.nc, DOY: 173
Processing file: ./magn20221730330.nc, DOY: 173
Processing file: ./magn20221730345.nc, DOY: 173
Processing file: ./magn20221730400.nc, DOY: 173
Processing file: ./magn20221730415.nc, DOY: 173
Processing file: ./magn20221730430.nc, DOY: 173
Processing file: ./magn20221730445.nc, DOY: 173
Processing file: ./magn20221730500.nc, DOY: 173
Processing file: ./magn20221730515.nc, DOY: 173
Processing file: ./magn20221730530.nc, DOY: 173
Processing file: ./magn20221730545.nc, DOY: 173
Processing file: ./magn20221730600.nc, DOY: 173
Processing file: ./magn20221730615.nc, DOY: 173
Processing file: ./magn20221730630.nc, DOY: 173
Processing file: ./magn20221730645.nc, DOY: 173
Processing file: ./magn20221730700.nc, DOY: 173
Processing file: ./magn20221730715.nc, DOY: 173
Processing file: ./magn20221730730.nc, DOY: 173
Processing file: ./magn20221730745.nc, DOY: 173
Processing file: ./magn20221730800.nc, DOY: 173
Processing file: ./magn20221730815.nc, DOY: 173
Processing file: ./magn20221730830.nc, DOY: 173
Processing file: ./magn20221730845.nc, DOY: 173
Processing file: ./magn20221730900.nc, DOY: 173
Processing file: ./magn20221730915.nc, DOY: 173
Processing file: ./magn20221730930.nc, DOY: 173
Processing file: ./magn20221730945.nc, DOY: 173
Processing file: ./magn20221731000.nc, DOY: 173
Processing file: ./magn20221731015.nc, DOY: 173
Processing file: ./magn20221731030.nc, DOY: 173
Processing file: ./magn20221731045.nc, DOY: 173
Processing file: ./magn20221731100.nc, DOY: 173
Processing file: ./magn20221731115.nc, DOY: 173
Processing file: ./magn20221731130.nc, DOY: 173
Processing file: ./magn20221731145.nc, DOY: 173
Processing file: ./magn20221731200.nc, DOY: 173
Processing file: ./magn20221731215.nc, DOY: 173
Processing file: ./magn20221731230.nc, DOY: 173
Processing file: ./magn20221731245.nc, DOY: 173
Processing file: ./magn20221731300.nc, DOY: 173
Processing file: ./magn20221731315.nc, DOY: 173
Processing file: ./magn20221731330.nc, DOY: 173
Processing file: ./magn20221731345.nc, DOY: 173
Processing file: ./magn20221731400.nc, DOY: 173
Processing file: ./magn20221731415.nc, DOY: 173
Processing file: ./magn20221731430.nc, DOY: 173
Processing file: ./magn20221731445.nc, DOY: 173
Processing file: ./magn20221731500.nc, DOY: 173
Processing file: ./magn20221731515.nc, DOY: 173
Processing file: ./magn20221731530.nc, DOY: 173
Processing file: ./magn20221731545.nc, DOY: 173
Processing file: ./magn20221731600.nc, DOY: 173
Processing file: ./magn20221731615.nc, DOY: 173
Processing file: ./magn20221731630.nc, DOY: 173
Processing file: ./magn20221731645.nc, DOY: 173
Processing file: ./magn20221731700.nc, DOY: 173
Processing file: ./magn20221731715.nc, DOY: 173
Processing file: ./magn20221731730.nc, DOY: 173
Processing file: ./magn20221731745.nc, DOY: 173
Processing file: ./magn20221731800.nc, DOY: 173
Processing file: ./magn20221731815.nc, DOY: 173
Processing file: ./magn20221731830.nc, DOY: 173
Processing file: ./magn20221731845.nc, DOY: 173
Processing file: ./magn20221731900.nc, DOY: 173
Processing file: ./magn20221731915.nc, DOY: 173
Processing file: ./magn20221731930.nc, DOY: 173
Processing file: ./magn20221731945.nc, DOY: 173
Processing file: ./magn20221732000.nc, DOY: 173
Processing file: ./magn20221732015.nc, DOY: 173
Processing file: ./magn20221732030.nc, DOY: 173
Processing file: ./magn20221732045.nc, DOY: 173
Processing file: ./magn20221732100.nc, DOY: 173
Processing file: ./magn20221732115.nc, DOY: 173
Processing file: ./magn20221732130.nc, DOY: 173
Processing file: ./magn20221732145.nc, DOY: 173
Processing file: ./magn20221732200.nc, DOY: 173
Processing file: ./magn20221732215.nc, DOY: 173
Processing file: ./magn20221732230.nc, DOY: 173
Processing file: ./magn20221732245.nc, DOY: 173
Processing file: ./magn20221732300.nc, DOY: 173
Processing file: ./magn20221732315.nc, DOY: 173
Processing file: ./magn20221732330.nc, DOY: 173
Processing file: ./magn20221732345.nc, DOY: 173
Processing file: ./magn20221740000.nc, DOY: 174
Processing file: ./magn20221740015.nc, DOY: 174
Processing file: ./magn20221740030.nc, DOY: 174
Processing file: ./magn20221740045.nc, DOY: 174
Processing file: ./magn20221740100.nc, DOY: 174
Processing file: ./magn20221740115.nc, DOY: 174
Processing file: ./magn20221740130.nc, DOY: 174
Processing file: ./magn20221740145.nc, DOY: 174
Processing file: ./magn20221740200.nc, DOY: 174
Processing file: ./magn20221740215.nc, DOY: 174
Processing file: ./magn20221740230.nc, DOY: 174
Processing file: ./magn20221740245.nc, DOY: 174
Processing file: ./magn20221740300.nc, DOY: 174
Processing file: ./magn20221740315.nc, DOY: 174
Processing file: ./magn20221740330.nc, DOY: 174
Processing file: ./magn20221740345.nc, DOY: 174
Processing file: ./magn20221740400.nc, DOY: 174
Processing file: ./magn20221740415.nc, DOY: 174
Processing file: ./magn20221740430.nc, DOY: 174
Processing file: ./magn20221740445.nc, DOY: 174
Processing file: ./magn20221740500.nc, DOY: 174
Processing file: ./magn20221740515.nc, DOY: 174
Processing file: ./magn20221740530.nc, DOY: 174
Processing file: ./magn20221740545.nc, DOY: 174
Processing file: ./magn20221740600.nc, DOY: 174
Processing file: ./magn20221740615.nc, DOY: 174
Processing file: ./magn20221740630.nc, DOY: 174
Processing file: ./magn20221740645.nc, DOY: 174
Processing file: ./magn20221740700.nc, DOY: 174
Processing file: ./magn20221740715.nc, DOY: 174
Processing file: ./magn20221740730.nc, DOY: 174
Processing file: ./magn20221740745.nc, DOY: 174
Processing file: ./magn20221740800.nc, DOY: 174
Processing file: ./magn20221740815.nc, DOY: 174
Processing file: ./magn20221740830.nc, DOY: 174
Processing file: ./magn20221740845.nc, DOY: 174
Processing file: ./magn20221740900.nc, DOY: 174
Processing file: ./magn20221740915.nc, DOY: 174
Processing file: ./magn20221740930.nc, DOY: 174
Processing file: ./magn20221740945.nc, DOY: 174
Processing file: ./magn20221741000.nc, DOY: 174
Processing file: ./magn20221741015.nc, DOY: 174
Processing file: ./magn20221741030.nc, DOY: 174
Processing file: ./magn20221741045.nc, DOY: 174
Processing file: ./magn20221741100.nc, DOY: 174
Processing file: ./magn20221741115.nc, DOY: 174
Processing file: ./magn20221741130.nc, DOY: 174
Processing file: ./magn20221741145.nc, DOY: 174
Processing file: ./magn20221741200.nc, DOY: 174
Processing file: ./magn20221741215.nc, DOY: 174
Processing file: ./magn20221741230.nc, DOY: 174
Processing file: ./magn20221741245.nc, DOY: 174
Processing file: ./magn20221741300.nc, DOY: 174
Processing file: ./magn20221741315.nc, DOY: 174
Processing file: ./magn20221741330.nc, DOY: 174
Processing file: ./magn20221741345.nc, DOY: 174
Processing file: ./magn20221741400.nc, DOY: 174
Processing file: ./magn20221741415.nc, DOY: 174
Processing file: ./magn20221741430.nc, DOY: 174
Processing file: ./magn20221741445.nc, DOY: 174
Processing file: ./magn20221741500.nc, DOY: 174
Processing file: ./magn20221741515.nc, DOY: 174
Processing file: ./magn20221741530.nc, DOY: 174
Processing file: ./magn20221741545.nc, DOY: 174
Processing file: ./magn20221741600.nc, DOY: 174
Processing file: ./magn20221741615.nc, DOY: 174
Processing file: ./magn20221741630.nc, DOY: 174
Processing file: ./magn20221741645.nc, DOY: 174
Processing file: ./magn20221741700.nc, DOY: 174
Processing file: ./magn20221741715.nc, DOY: 174
Processing file: ./magn20221741730.nc, DOY: 174
Processing file: ./magn20221741745.nc, DOY: 174
Processing file: ./magn20221741800.nc, DOY: 174
Processing file: ./magn20221741815.nc, DOY: 174
Processing file: ./magn20221741830.nc, DOY: 174
Processing file: ./magn20221741845.nc, DOY: 174
Processing file: ./magn20221741900.nc, DOY: 174
Processing file: ./magn20221741915.nc, DOY: 174
Processing file: ./magn20221741930.nc, DOY: 174
Processing file: ./magn20221741945.nc, DOY: 174
Processing file: ./magn20221742000.nc, DOY: 174
Processing file: ./magn20221742015.nc, DOY: 174
Processing file: ./magn20221742030.nc, DOY: 174
Processing file: ./magn20221742045.nc, DOY: 174
Processing file: ./magn20221742100.nc, DOY: 174
Processing file: ./magn20221742115.nc, DOY: 174
Processing file: ./magn20221742130.nc, DOY: 174
Processing file: ./magn20221742145.nc, DOY: 174
Processing file: ./magn20221742200.nc, DOY: 174
Processing file: ./magn20221742215.nc, DOY: 174
Processing file: ./magn20221742230.nc, DOY: 174
Processing file: ./magn20221742245.nc, DOY: 174
Processing file: ./magn20221742300.nc, DOY: 174
Processing file: ./magn20221742315.nc, DOY: 174
Processing file: ./magn20221742330.nc, DOY: 174
Processing file: ./magn20221742345.nc, DOY: 174
Processing file: ./magn20221760000.nc, DOY: 176
Processing file: ./magn20221760015.nc, DOY: 176
Processing file: ./magn20221760030.nc, DOY: 176
Processing file: ./magn20221760045.nc, DOY: 176
Processing file: ./magn20221760100.nc, DOY: 176
Processing file: ./magn20221760115.nc, DOY: 176
Processing file: ./magn20221760130.nc, DOY: 176
Processing file: ./magn20221760145.nc, DOY: 176
Processing file: ./magn20221760200.nc, DOY: 176
Processing file: ./magn20221760215.nc, DOY: 176
Processing file: ./magn20221760230.nc, DOY: 176
Processing file: ./magn20221760245.nc, DOY: 176
Processing file: ./magn20221760300.nc, DOY: 176
Processing file: ./magn20221760315.nc, DOY: 176
Processing file: ./magn20221760330.nc, DOY: 176
Processing file: ./magn20221760345.nc, DOY: 176
Processing file: ./magn20221760400.nc, DOY: 176
Processing file: ./magn20221760415.nc, DOY: 176
Processing file: ./magn20221760430.nc, DOY: 176
Processing file: ./magn20221760445.nc, DOY: 176
Processing file: ./magn20221760500.nc, DOY: 176
Processing file: ./magn20221760515.nc, DOY: 176
Processing file: ./magn20221760530.nc, DOY: 176
Processing file: ./magn20221760545.nc, DOY: 176
Processing file: ./magn20221760600.nc, DOY: 176
Processing file: ./magn20221760615.nc, DOY: 176
Processing file: ./magn20221760630.nc, DOY: 176
Processing file: ./magn20221760645.nc, DOY: 176
Processing file: ./magn20221760700.nc, DOY: 176
Processing file: ./magn20221760715.nc, DOY: 176
Processing file: ./magn20221760730.nc, DOY: 176
Processing file: ./magn20221760745.nc, DOY: 176
Processing file: ./magn20221760800.nc, DOY: 176
Processing file: ./magn20221760815.nc, DOY: 176
Processing file: ./magn20221760830.nc, DOY: 176
Processing file: ./magn20221760845.nc, DOY: 176
Processing file: ./magn20221760900.nc, DOY: 176
Processing file: ./magn20221760915.nc, DOY: 176
Processing file: ./magn20221760930.nc, DOY: 176
Processing file: ./magn20221760945.nc, DOY: 176
Processing file: ./magn20221761000.nc, DOY: 176
Processing file: ./magn20221761015.nc, DOY: 176
Processing file: ./magn20221761030.nc, DOY: 176
Processing file: ./magn20221761045.nc, DOY: 176
Processing file: ./magn20221761100.nc, DOY: 176
Processing file: ./magn20221761115.nc, DOY: 176
Processing file: ./magn20221761130.nc, DOY: 176
Processing file: ./magn20221761145.nc, DOY: 176
Processing file: ./magn20221761200.nc, DOY: 176
Processing file: ./magn20221761215.nc, DOY: 176
Processing file: ./magn20221761230.nc, DOY: 176
Processing file: ./magn20221761245.nc, DOY: 176
Processing file: ./magn20221761300.nc, DOY: 176
Processing file: ./magn20221761315.nc, DOY: 176
Processing file: ./magn20221761330.nc, DOY: 176
Processing file: ./magn20221761345.nc, DOY: 176
Processing file: ./magn20221761400.nc, DOY: 176
Processing file: ./magn20221761415.nc, DOY: 176
Processing file: ./magn20221761430.nc, DOY: 176
Processing file: ./magn20221761445.nc, DOY: 176
Processing file: ./magn20221761500.nc, DOY: 176
Processing file: ./magn20221761515.nc, DOY: 176
Processing file: ./magn20221761530.nc, DOY: 176
Processing file: ./magn20221761545.nc, DOY: 176
Processing file: ./magn20221761600.nc, DOY: 176
Processing file: ./magn20221761615.nc, DOY: 176
Processing file: ./magn20221761630.nc, DOY: 176
Processing file: ./magn20221761645.nc, DOY: 176
Processing file: ./magn20221761700.nc, DOY: 176
Processing file: ./magn20221761715.nc, DOY: 176
Processing file: ./magn20221761730.nc, DOY: 176
Processing file: ./magn20221761745.nc, DOY: 176
Processing file: ./magn20221761800.nc, DOY: 176
Processing file: ./magn20221761815.nc, DOY: 176
Processing file: ./magn20221761830.nc, DOY: 176
Processing file: ./magn20221761845.nc, DOY: 176
Processing file: ./magn20221761900.nc, DOY: 176
Processing file: ./magn20221761915.nc, DOY: 176
Processing file: ./magn20221761930.nc, DOY: 176
Processing file: ./magn20221761945.nc, DOY: 176
Processing file: ./magn20221762000.nc, DOY: 176
Processing file: ./magn20221762015.nc, DOY: 176
Processing file: ./magn20221762030.nc, DOY: 176
Processing file: ./magn20221762045.nc, DOY: 176
Processing file: ./magn20221762100.nc, DOY: 176
Processing file: ./magn20221762115.nc, DOY: 176
Processing file: ./magn20221762130.nc, DOY: 176
Processing file: ./magn20221762145.nc, DOY: 176
Processing file: ./magn20221762200.nc, DOY: 176
Processing file: ./magn20221762215.nc, DOY: 176
Processing file: ./magn20221762230.nc, DOY: 176
Processing file: ./magn20221762245.nc, DOY: 176
Processing file: ./magn20221762300.nc, DOY: 176
Processing file: ./magn20221762315.nc, DOY: 176
Processing file: ./magn20221762330.nc, DOY: 176
Processing file: ./magn20221762345.nc, DOY: 176
Processing file: ./magn20221780000.nc, DOY: 178
Processing file: ./magn20221780015.nc, DOY: 178
Processing file: ./magn20221780030.nc, DOY: 178
Processing file: ./magn20221780045.nc, DOY: 178
Processing file: ./magn20221780100.nc, DOY: 178
Processing file: ./magn20221780115.nc, DOY: 178
Processing file: ./magn20221780130.nc, DOY: 178
Processing file: ./magn20221780145.nc, DOY: 178
Processing file: ./magn20221780200.nc, DOY: 178
Processing file: ./magn20221780215.nc, DOY: 178
Processing file: ./magn20221780230.nc, DOY: 178
Processing file: ./magn20221780245.nc, DOY: 178
Processing file: ./magn20221780300.nc, DOY: 178
Processing file: ./magn20221780315.nc, DOY: 178
Processing file: ./magn20221780330.nc, DOY: 178
Processing file: ./magn20221780345.nc, DOY: 178
Processing file: ./magn20221780400.nc, DOY: 178
Processing file: ./magn20221780415.nc, DOY: 178
Processing file: ./magn20221780430.nc, DOY: 178
Processing file: ./magn20221780445.nc, DOY: 178
Processing file: ./magn20221780500.nc, DOY: 178
Processing file: ./magn20221780515.nc, DOY: 178
Processing file: ./magn20221780530.nc, DOY: 178
Processing file: ./magn20221780545.nc, DOY: 178
Processing file: ./magn20221780600.nc, DOY: 178
Processing file: ./magn20221780615.nc, DOY: 178

In [13]:
!ls -lR ./*.npy | wc -l

96

In [14]:
import numpy as np
import glob
import re

npy_files = glob.glob("magn2022*.npy")

def extract_doy(filename):
    match = re.search(r'magn2022(\d{3})\.npy', filename)
    if match:
        return int(match.group(1))
    return 0

npy_files.sort(key=extract_doy)

print(f"Found {len(npy_files)} NPY files to process.")

all_data = []

for i, file in enumerate(npy_files):
    doy = extract_doy(file)
    print(f"Processing {file} (DOY {doy}) - {i+1}/{len(npy_files)}")

    data = np.load(file)

    all_data.append(data)

    print(f"  Shape: {data.shape}")

combined_data = np.concatenate(all_data, axis=0)

print(f"\nCombined data. Final shape: {combined_data.shape}")

output_file = "MAGGIA_TEC_maps_intersection_2022.npy"
np.save(output_file, combined_data)

print(f"\nFile {output_file} saved successfully!")
print(f"File size: {combined_data.nbytes / (1024**2):.2f} MB")

Found 96 NPY files to process.
Processing magn2022060.npy (DOY 60) - 1/96
  Shape: (96, 241, 221)
Processing magn2022061.npy (DOY 61) - 2/96
  Shape: (96, 241, 221)
Processing magn2022062.npy (DOY 62) - 3/96
  Shape: (96, 241, 221)
Processing magn2022063.npy (DOY 63) - 4/96
  Shape: (96, 241, 221)
Processing magn2022064.npy (DOY 64) - 5/96
  Shape: (96, 241, 221)
Processing magn2022065.npy (DOY 65) - 6/96
  Shape: (96, 241, 221)
Processing magn2022066.npy (DOY 66) - 7/96
  Shape: (96, 241, 221)
Processing magn2022067.npy (DOY 67) - 8/96
  Shape: (96, 241, 221)
Processing magn2022069.npy (DOY 69) - 9/96
  Shape: (96, 241, 221)
Processing magn2022070.npy (DOY 70) - 10/96
  Shape: (96, 241, 221)
Processing magn2022071.npy (DOY 71) - 11/96
  Shape: (96, 241, 221)
Processing magn2022073.npy (DOY 73) - 12/96
  Shape: (96, 241, 221)
Processing magn2022074.npy (DOY 74) - 13/96
  Shape: (96, 241, 221)
Processing magn2022075.npy (DOY 75) - 14/96
  Shape: (96, 241, 221)
Processing magn2022076.npy (DOY 76) - 15/96
  Shape: (96, 241, 221)
Processing magn2022077.npy (DOY 77) - 16/96
  Shape: (96, 241, 221)
Processing magn2022078.npy (DOY 78) - 17/96
  Shape: (96, 241, 221)
Processing magn2022079.npy (DOY 79) - 18/96
  Shape: (96, 241, 221)
Processing magn2022080.npy (DOY 80) - 19/96
  Shape: (96, 241, 221)
Processing magn2022081.npy (DOY 81) - 20/96
  Shape: (96, 241, 221)
Processing magn2022082.npy (DOY 82) - 21/96
  Shape: (96, 241, 221)
Processing magn2022083.npy (DOY 83) - 22/96
  Shape: (96, 241, 221)
Processing magn2022084.npy (DOY 84) - 23/96
  Shape: (96, 241, 221)
Processing magn2022085.npy (DOY 85) - 24/96
  Shape: (96, 241, 221)
Processing magn2022086.npy (DOY 86) - 25/96
  Shape: (96, 241, 221)
Processing magn2022090.npy (DOY 90) - 26/96
  Shape: (96, 241, 221)
Processing magn2022152.npy (DOY 152) - 27/96
  Shape: (96, 241, 221)
Processing magn2022153.npy (DOY 153) - 28/96
  Shape: (96, 241, 221)
Processing magn2022154.npy (DOY 154) - 29/96
  Shape: (96, 241, 221)
Processing magn2022156.npy (DOY 156) - 30/96
  Shape: (96, 241, 221)
Processing magn2022157.npy (DOY 157) - 31/96
  Shape: (96, 241, 221)
Processing magn2022158.npy (DOY 158) - 32/96
  Shape: (96, 241, 221)
Processing magn2022159.npy (DOY 159) - 33/96
  Shape: (96, 241, 221)
Processing magn2022160.npy (DOY 160) - 34/96
  Shape: (96, 241, 221)
Processing magn2022161.npy (DOY 161) - 35/96
  Shape: (96, 241, 221)
Processing magn2022162.npy (DOY 162) - 36/96
  Shape: (96, 241, 221)
Processing magn2022163.npy (DOY 163) - 37/96
  Shape: (96, 241, 221)
Processing magn2022164.npy (DOY 164) - 38/96
  Shape: (96, 241, 221)
Processing magn2022165.npy (DOY 165) - 39/96
  Shape: (96, 241, 221)
Processing magn2022166.npy (DOY 166) - 40/96
  Shape: (96, 241, 221)
Processing magn2022167.npy (DOY 167) - 41/96
  Shape: (96, 241, 221)
Processing magn2022168.npy (DOY 168) - 42/96
  Shape: (96, 241, 221)
Processing magn2022169.npy (DOY 169) - 43/96
  Shape: (96, 241, 221)
Processing magn2022170.npy (DOY 170) - 44/96
  Shape: (96, 241, 221)
Processing magn2022171.npy (DOY 171) - 45/96
  Shape: (96, 241, 221)
Processing magn2022172.npy (DOY 172) - 46/96
  Shape: (96, 241, 221)
Processing magn2022173.npy (DOY 173) - 47/96
  Shape: (96, 241, 221)
Processing magn2022174.npy (DOY 174) - 48/96
  Shape: (96, 241, 221)
Processing magn2022176.npy (DOY 176) - 49/96
  Shape: (96, 241, 221)
Processing magn2022178.npy (DOY 178) - 50/96
  Shape: (96, 241, 221)
Processing magn2022181.npy (DOY 181) - 51/96
  Shape: (96, 241, 221)
Processing magn2022245.npy (DOY 245) - 52/96
  Shape: (96, 241, 221)
Processing magn2022246.npy (DOY 246) - 53/96
  Shape: (96, 241, 221)
Processing magn2022247.npy (DOY 247) - 54/96
  Shape: (96, 241, 221)
Processing magn2022248.npy (DOY 248) - 55/96
  Shape: (96, 241, 221)
Processing magn2022249.npy (DOY 249) - 56/96
  Shape: (96, 241, 221)
Processing magn2022250.npy (DOY 250) - 57/96
  Shape: (96, 241, 221)
Processing magn2022251.npy (DOY 251) - 58/96
  Shape: (96, 241, 221)
Processing magn2022252.npy (DOY 252) - 59/96
  Shape: (96, 241, 221)
Processing magn2022253.npy (DOY 253) - 60/96
  Shape: (96, 241, 221)
Processing magn2022254.npy (DOY 254) - 61/96
  Shape: (96, 241, 221)
Processing magn2022255.npy (DOY 255) - 62/96
  Shape: (96, 241, 221)
Processing magn2022256.npy (DOY 256) - 63/96
  Shape: (96, 241, 221)
Processing magn2022258.npy (DOY 258) - 64/96
  Shape: (96, 241, 221)
Processing magn2022260.npy (DOY 260) - 65/96
  Shape: (96, 241, 221)
Processing magn2022261.npy (DOY 261) - 66/96
  Shape: (96, 241, 221)
Processing magn2022262.npy (DOY 262) - 67/96
  Shape: (96, 241, 221)
Processing magn2022264.npy (DOY 264) - 68/96
  Shape: (96, 241, 221)
Processing magn2022265.npy (DOY 265) - 69/96
  Shape: (96, 241, 221)
Processing magn2022266.npy (DOY 266) - 70/96
  Shape: (96, 241, 221)
Processing magn2022267.npy (DOY 267) - 71/96
  Shape: (96, 241, 221)
Processing magn2022268.npy (DOY 268) - 72/96
  Shape: (96, 241, 221)
Processing magn2022269.npy (DOY 269) - 73/96
  Shape: (96, 241, 221)
Processing magn2022270.npy (DOY 270) - 74/96
  Shape: (96, 241, 221)
Processing magn2022271.npy (DOY 271) - 75/96
  Shape: (96, 241, 221)
Processing magn2022272.npy (DOY 272) - 76/96
  Shape: (96, 241, 221)
Processing magn2022273.npy (DOY 273) - 77/96
  Shape: (96, 241, 221)
Processing magn2022338.npy (DOY 338) - 78/96
  Shape: (96, 241, 221)
Processing magn2022339.npy (DOY 339) - 79/96
  Shape: (96, 241, 221)
Processing magn2022340.npy (DOY 340) - 80/96
  Shape: (96, 241, 221)
Processing magn2022348.npy (DOY 348) - 81/96
  Shape: (96, 241, 221)
Processing magn2022349.npy (DOY 349) - 82/96
  Shape: (96, 241, 221)
Processing magn2022350.npy (DOY 350) - 83/96
  Shape: (96, 241, 221)
Processing magn2022351.npy (DOY 351) - 84/96
  Shape: (96, 241, 221)
Processing magn2022352.npy (DOY 352) - 85/96
  Shape: (96, 241, 221)
Processing magn2022353.npy (DOY 353) - 86/96
  Shape: (96, 241, 221)
Processing magn2022354.npy (DOY 354) - 87/96
  Shape: (96, 241, 221)
Processing magn2022356.npy (DOY 356) - 88/96
  Shape: (96, 241, 221)
Processing magn2022357.npy (DOY 357) - 89/96
  Shape: (96, 241, 221)
Processing magn2022358.npy (DOY 358) - 90/96
  Shape: (96, 241, 221)
Processing magn2022359.npy (DOY 359) - 91/96
  Shape: (96, 241, 221)
Processing magn2022360.npy (DOY 360) - 92/96
  Shape: (96, 241, 221)
Processing magn2022362.npy (DOY 362) - 93/96
  Shape: (96, 241, 221)
Processing magn2022363.npy (DOY 363) - 94/96
  Shape: (96, 241, 221)
Processing magn2022364.npy (DOY 364) - 95/96
  Shape: (96, 241, 221)
Processing magn2022365.npy (DOY 365) - 96/96
  Shape: (96, 241, 221)

Combined data. Final shape: (9216, 241, 221)

File MAGGIA_TEC_maps_intersection_2022.npy saved successfully!
File size: 1872.46 MB

## 2024

In [15]:
%pwd

'/content'

In [16]:
# %rm *.npy

In [17]:
# !ls

In [18]:
import os
import glob
from collections import defaultdict

base_path = './'

file_pattern = os.path.join(base_path, '**', 'magn2024*.nc')
file_list = sorted(glob.glob(file_pattern, recursive=True))

file_count_by_day = defaultdict(int)

for file_name in file_list:

    day_dir = os.path.basename(os.path.dirname(file_name))
    file_count_by_day[day_dir] += 1

print("\nDays with less than 96 files:")

for day, count in sorted(file_count_by_day.items()):
    if count < 96:
        print(f"Dia {day}: {count} arquivos")

Days with less than 96 files:

In [19]:
import numpy as np
import xarray as xr
import os
import re
import glob

file_list = glob.glob("./magn2024*.nc")

file_list.sort()

tec_by_doy = {}

pattern = re.compile(r'magn2024(\d{3})')

for file_name in file_list:
    try:

        match = pattern.search(file_name)
        if match:
            doy = match.group(1)

            print(f"Processing file: {file_name}, DOY: {doy}")

            ds_disk = xr.open_dataset(file_name)
            tec = ds_disk['z'][:, :].values

            if doy not in tec_by_doy:
                tec_by_doy[doy] = []

            tec_by_doy[doy].append(tec)

            ds_disk.close()

    except Exception as e:
        print(f"Error processing file {file_name}: {e}")

print("\nSaving NPY files per day...")
for doy, tec_list in tec_by_doy.items():

    tec_array = np.array(tec_list)

    output_file = f"magn2024{doy}.npy"
    np.save(output_file, tec_array)

    print(f"File {output_file} saved successfully! Shape: {tec_array.shape}")

print("\Processing completed!")

Processing file: ./magn20240610000.nc, DOY: 061
Processing file: ./magn20240610015.nc, DOY: 061
Processing file: ./magn20240610030.nc, DOY: 061
Processing file: ./magn20240610045.nc, DOY: 061
Processing file: ./magn20240610100.nc, DOY: 061
Processing file: ./magn20240610115.nc, DOY: 061
Processing file: ./magn20240610130.nc, DOY: 061
Processing file: ./magn20240610145.nc, DOY: 061
Processing file: ./magn20240610200.nc, DOY: 061
Processing file: ./magn20240610215.nc, DOY: 061
Processing file: ./magn20240610230.nc, DOY: 061
Processing file: ./magn20240610245.nc, DOY: 061
Processing file: ./magn20240610300.nc, DOY: 061
Processing file: ./magn20240610315.nc, DOY: 061
Processing file: ./magn20240610330.nc, DOY: 061
Processing file: ./magn20240610345.nc, DOY: 061
Processing file: ./magn20240610400.nc, DOY: 061
Processing file: ./magn20240610415.nc, DOY: 061
Processing file: ./magn20240610430.nc, DOY: 061
Processing file: ./magn20240610445.nc, DOY: 061
Processing file: ./magn20240610500.nc, DOY: 061
Processing file: ./magn20240610515.nc, DOY: 061
Processing file: ./magn20240610530.nc, DOY: 061
Processing file: ./magn20240610545.nc, DOY: 061
Processing file: ./magn20240610600.nc, DOY: 061
Processing file: ./magn20240610615.nc, DOY: 061
Processing file: ./magn20240610630.nc, DOY: 061

<>:47: SyntaxWarning: invalid escape sequence '\P'
<>:47: SyntaxWarning: invalid escape sequence '\P'
/tmp/ipython-input-2996896026.py:47: SyntaxWarning: invalid escape sequence '\P'
  print("\Processing completed!")

A saída de streaming foi truncada nas últimas 5000 linhas.
Processing file: ./magn20242690050.nc, DOY: 269
Processing file: ./magn20242690100.nc, DOY: 269
Processing file: ./magn20242690110.nc, DOY: 269
Processing file: ./magn20242690120.nc, DOY: 269
Processing file: ./magn20242690130.nc, DOY: 269
Processing file: ./magn20242690140.nc, DOY: 269
Processing file: ./magn20242690150.nc, DOY: 269
Processing file: ./magn20242690200.nc, DOY: 269
Processing file: ./magn20242690210.nc, DOY: 269
Processing file: ./magn20242690220.nc, DOY: 269
Processing file: ./magn20242690230.nc, DOY: 269
Processing file: ./magn20242690240.nc, DOY: 269
Processing file: ./magn20242690250.nc, DOY: 269
Processing file: ./magn20242690300.nc, DOY: 269
Processing file: ./magn20242690310.nc, DOY: 269
Processing file: ./magn20242690320.nc, DOY: 269
Processing file: ./magn20242690330.nc, DOY: 269
Processing file: ./magn20242690340.nc, DOY: 269
Processing file: ./magn20242690350.nc, DOY: 269
Processing file: ./magn20242690400.nc, DOY: 269
Processing file: ./magn20242690410.nc, DOY: 269
Processing file: ./magn20242690420.nc, DOY: 269
Processing file: ./magn20242690430.nc, DOY: 269
Processing file: ./magn20242690440.nc, DOY: 269
Processing file: ./magn20242690450.nc, DOY: 269
Processing file: ./magn20242690500.nc, DOY: 269
Processing file: ./magn20242690510.nc, DOY: 269
Processing file: ./magn20242690520.nc, DOY: 269
Processing file: ./magn20242690530.nc, DOY: 269
Processing file: ./magn20242690540.nc, DOY: 269
Processing file: ./magn20242690550.nc, DOY: 269
Processing file: ./magn20242690600.nc, DOY: 269
Processing file: ./magn20242690610.nc, DOY: 269
Processing file: ./magn20242690620.nc, DOY: 269
Processing file: ./magn20242690630.nc, DOY: 269
Processing file: ./magn20242690640.nc, DOY: 269
Processing file: ./magn20242690650.nc, DOY: 269
Processing file: ./magn20242690700.nc, DOY: 269
Processing file: ./magn20242690710.nc, DOY: 269
Processing file: ./magn20242690720.nc, DOY: 269
Processing file: ./magn20242690730.nc, DOY: 269
Processing file: ./magn20242690740.nc, DOY: 269
Processing file: ./magn20242690750.nc, DOY: 269
Processing file: ./magn20242690800.nc, DOY: 269
Processing file: ./magn20242690810.nc, DOY: 269
Processing file: ./magn20242690820.nc, DOY: 269
Processing file: ./magn20242690830.nc, DOY: 269
Processing file: ./magn20242690840.nc, DOY: 269
Processing file: ./magn20242690850.nc, DOY: 269
Processing file: ./magn20242690900.nc, DOY: 269
Processing file: ./magn20242690910.nc, DOY: 269
Processing file: ./magn20242690920.nc, DOY: 269
Processing file: ./magn20242690930.nc, DOY: 269
Processing file: ./magn20242690940.nc, DOY: 269
Processing file: ./magn20242690950.nc, DOY: 269
Processing file: ./magn20242691000.nc, DOY: 269
Processing file: ./magn20242691010.nc, DOY: 269
Processing file: ./magn20242691020.nc, DOY: 269
Processing file: ./magn20242691030.nc, DOY: 269
Processing file: ./magn20242691040.nc, DOY: 269
Processing file: ./magn20242691050.nc, DOY: 269
Processing file: ./magn20242691100.nc, DOY: 269
Processing file: ./magn20242691110.nc, DOY: 269
Processing file: ./magn20242691120.nc, DOY: 269
Processing file: ./magn20242691130.nc, DOY: 269
Processing file: ./magn20242691140.nc, DOY: 269
Processing file: ./magn20242691150.nc, DOY: 269
Processing file: ./magn20242691200.nc, DOY: 269
Processing file: ./magn20242691210.nc, DOY: 269
Processing file: ./magn20242691220.nc, DOY: 269
Processing file: ./magn20242691230.nc, DOY: 269
Processing file: ./magn20242691240.nc, DOY: 269
Processing file: ./magn20242691250.nc, DOY: 269
Processing file: ./magn20242691300.nc, DOY: 269
Processing file: ./magn20242691310.nc, DOY: 269
Processing file: ./magn20242691320.nc, DOY: 269
Processing file: ./magn20242691330.nc, DOY: 269
Processing file: ./magn20242691340.nc, DOY: 269
Processing file: ./magn20242691350.nc, DOY: 269
Processing file: ./magn20242691400.nc, DOY: 269
Processing file: ./magn20242691410.nc, DOY: 269
Processing file: ./magn20242691420.nc, DOY: 269
Processing file: ./magn20242691430.nc, DOY: 269
Processing file: ./magn20242691440.nc, DOY: 269
Processing file: ./magn20242691450.nc, DOY: 269
Processing file: ./magn20242691500.nc, DOY: 269
Processing file: ./magn20242691510.nc, DOY: 269
Processing file: ./magn20242691520.nc, DOY: 269
Processing file: ./magn20242691530.nc, DOY: 269
Processing file: ./magn20242691540.nc, DOY: 269
Processing file: ./magn20242691550.nc, DOY: 269
Processing file: ./magn20242691600.nc, DOY: 269
Processing file: ./magn20242691610.nc, DOY: 269
Processing file: ./magn20242691620.nc, DOY: 269
Processing file: ./magn20242691630.nc, DOY: 269
Processing file: ./magn20242691640.nc, DOY: 269
Processing file: ./magn20242691650.nc, DOY: 269
Processing file: ./magn20242691700.nc, DOY: 269
Processing file: ./magn20242691710.nc, DOY: 269
Processing file: ./magn20242691720.nc, DOY: 269
Processing file: ./magn20242691730.nc, DOY: 269
Processing file: ./magn20242691740.nc, DOY: 269
Processing file: ./magn20242691750.nc, DOY: 269
Processing file: ./magn20242691800.nc, DOY: 269
Processing file: ./magn20242691810.nc, DOY: 269
Processing file: ./magn20242691820.nc, DOY: 269
Processing file: ./magn20242691830.nc, DOY: 269
Processing file: ./magn20242691840.nc, DOY: 269
Processing file: ./magn20242691850.nc, DOY: 269
Processing file: ./magn20242691900.nc, DOY: 269
Processing file: ./magn20242691910.nc, DOY: 269
Processing file: ./magn20242691920.nc, DOY: 269
Processing file: ./magn20242691930.nc, DOY: 269
Processing file: ./magn20242691940.nc, DOY: 269
Processing file: ./magn20242691950.nc, DOY: 269
Processing file: ./magn20242692000.nc, DOY: 269
Processing file: ./magn20242692010.nc, DOY: 269
Processing file: ./magn20242692020.nc, DOY: 269
Processing file: ./magn20242692030.nc, DOY: 269
Processing file: ./magn20242692040.nc, DOY: 269
Processing file: ./magn20242692050.nc, DOY: 269
Processing file: ./magn20242692100.nc, DOY: 269
Processing file: ./magn20242692110.nc, DOY: 269
Processing file: ./magn20242692120.nc, DOY: 269
Processing file: ./magn20242692130.nc, DOY: 269
Processing file: ./magn20242692140.nc, DOY: 269
Processing file: ./magn20242692150.nc, DOY: 269
Processing file: ./magn20242692200.nc, DOY: 269
Processing file: ./magn20242692210.nc, DOY: 269
Processing file: ./magn20242692220.nc, DOY: 269
Processing file: ./magn20242692230.nc, DOY: 269
Processing file: ./magn20242692240.nc, DOY: 269
Processing file: ./magn20242692250.nc, DOY: 269
Processing file: ./magn20242692300.nc, DOY: 269
Processing file: ./magn20242692310.nc, DOY: 269
Processing file: ./magn20242692320.nc, DOY: 269
Processing file: ./magn20242692330.nc, DOY: 269
Processing file: ./magn20242692340.nc, DOY: 269
Processing file: ./magn20242692350.nc, DOY: 269
Processing file: ./magn20242700000.nc, DOY: 270
Processing file: ./magn20242700010.nc, DOY: 270
Processing file: ./magn20242700020.nc, DOY: 270
Processing file: ./magn20242700030.nc, DOY: 270
Processing file: ./magn20242700040.nc, DOY: 270
Processing file: ./magn20242700050.nc, DOY: 270
Processing file: ./magn20242700100.nc, DOY: 270
Processing file: ./magn20242700110.nc, DOY: 270
Processing file: ./magn20242700120.nc, DOY: 270
Processing file: ./magn20242700130.nc, DOY: 270
Processing file: ./magn20242700140.nc, DOY: 270
Processing file: ./magn20242700150.nc, DOY: 270
Processing file: ./magn20242700200.nc, DOY: 270
Processing file: ./magn20242700210.nc, DOY: 270
Processing file: ./magn20242700220.nc, DOY: 270
Processing file: ./magn20242700230.nc, DOY: 270
Processing file: ./magn20242700240.nc, DOY: 270
Processing file: ./magn20242700250.nc, DOY: 270
Processing file: ./magn20242700300.nc, DOY: 270
Processing file: ./magn20242700310.nc, DOY: 270
Processing file: ./magn20242700320.nc, DOY: 270
Processing file: ./magn20242700330.nc, DOY: 270
Processing file: ./magn20242700340.nc, DOY: 270
Processing file: ./magn20242700350.nc, DOY: 270
Processing file: ./magn20242700400.nc, DOY: 270
Processing file: ./magn20242700410.nc, DOY: 270
Processing file: ./magn20242700420.nc, DOY: 270
Processing file: ./magn20242700430.nc, DOY: 270
Processing file: ./magn20242700440.nc, DOY: 270
Processing file: ./magn20242700450.nc, DOY: 270
Processing file: ./magn20242700500.nc, DOY: 270
Processing file: ./magn20242700510.nc, DOY: 270
Processing file: ./magn20242700520.nc, DOY: 270
Processing file: ./magn20242700530.nc, DOY: 270
Processing file: ./magn20242700540.nc, DOY: 270
Processing file: ./magn20242700550.nc, DOY: 270
Processing file: ./magn20242700600.nc, DOY: 270
Processing file: ./magn20242700610.nc, DOY: 270
Processing file: ./magn20242700620.nc, DOY: 270
Processing file: ./magn20242700630.nc, DOY: 270
Processing file: ./magn20242700640.nc, DOY: 270
Processing file: ./magn20242700650.nc, DOY: 270
Processing file: ./magn20242700700.nc, DOY: 270
Processing file: ./magn20242700710.nc, DOY: 270
Processing file: ./magn20242700720.nc, DOY: 270
Processing file: ./magn20242700730.nc, DOY: 270
Processing file: ./magn20242700740.nc, DOY: 270
Processing file: ./magn20242700750.nc, DOY: 270
Processing file: ./magn20242700800.nc, DOY: 270
Processing file: ./magn20242700810.nc, DOY: 270
Processing file: ./magn20242700820.nc, DOY: 270
Processing file: ./magn20242700830.nc, DOY: 270
Processing file: ./magn20242700840.nc, DOY: 270
Processing file: ./magn20242700850.nc, DOY: 270
Processing file: ./magn20242700900.nc, DOY: 270
Processing file: ./magn20242700910.nc, DOY: 270
Processing file: ./magn20242700920.nc, DOY: 270
Processing file: ./magn20242700930.nc, DOY: 270
Processing file: ./magn20242700940.nc, DOY: 270
Processing file: ./magn20242700950.nc, DOY: 270
Processing file: ./magn20242701000.nc, DOY: 270
Processing file: ./magn20242701010.nc, DOY: 270
Processing file: ./magn20242701020.nc, DOY: 270
Processing file: ./magn20242701030.nc, DOY: 270
Processing file: ./magn20242701040.nc, DOY: 270
Processing file: ./magn20242701050.nc, DOY: 270
Processing file: ./magn20242701100.nc, DOY: 270
Processing file: ./magn20242701110.nc, DOY: 270
Processing file: ./magn20242701120.nc, DOY: 270
Processing file: ./magn20242701130.nc, DOY: 270
Processing file: ./magn20242701140.nc, DOY: 270
Processing file: ./magn20242701150.nc, DOY: 270
Processing file: ./magn20242701200.nc, DOY: 270
Processing file: ./magn20242701210.nc, DOY: 270
Processing file: ./magn20242701220.nc, DOY: 270
Processing file: ./magn20242701230.nc, DOY: 270
Processing file: ./magn20242701240.nc, DOY: 270
Processing file: ./magn20242701250.nc, DOY: 270
Processing file: ./magn20242701300.nc, DOY: 270
Processing file: ./magn20242701310.nc, DOY: 270
Processing file: ./magn20242701320.nc, DOY: 270
Processing file: ./magn20242701330.nc, DOY: 270
Processing file: ./magn20242701340.nc, DOY: 270
Processing file: ./magn20242701350.nc, DOY: 270
Processing file: ./magn20242701400.nc, DOY: 270
Processing file: ./magn20242701410.nc, DOY: 270
Processing file: ./magn20242701420.nc, DOY: 270
Processing file: ./magn20242701430.nc, DOY: 270
Processing file: ./magn20242701440.nc, DOY: 270
Processing file: ./magn20242701450.nc, DOY: 270
Processing file: ./magn20242701500.nc, DOY: 270
Processing file: ./magn20242701510.nc, DOY: 270
Processing file: ./magn20242701520.nc, DOY: 270
Processing file: ./magn20242701530.nc, DOY: 270
Processing file: ./magn20242701540.nc, DOY: 270
Processing file: ./magn20242701550.nc, DOY: 270
Processing file: ./magn20242701600.nc, DOY: 270
Processing file: ./magn20242701610.nc, DOY: 270
Processing file: ./magn20242701620.nc, DOY: 270
Processing file: ./magn20242701630.nc, DOY: 270
Processing file: ./magn20242701640.nc, DOY: 270
Processing file: ./magn20242701650.nc, DOY: 270
Processing file: ./magn20242701700.nc, DOY: 270
Processing file: ./magn20242701710.nc, DOY: 270
Processing file: ./magn20242701720.nc, DOY: 270
Processing file: ./magn20242701730.nc, DOY: 270
Processing file: ./magn20242701740.nc, DOY: 270
Processing file: ./magn20242701750.nc, DOY: 270
Processing file: ./magn20242701800.nc, DOY: 270
Processing file: ./magn20242701810.nc, DOY: 270
Processing file: ./magn20242701820.nc, DOY: 270
Processing file: ./magn20242701830.nc, DOY: 270
Processing file: ./magn20242701840.nc, DOY: 270
Processing file: ./magn20242701850.nc, DOY: 270
Processing file: ./magn20242701900.nc, DOY: 270
Processing file: ./magn20242701910.nc, DOY: 270
Processing file: ./magn20242701920.nc, DOY: 270
Processing file: ./magn20242701930.nc, DOY: 270
Processing file: ./magn20242701940.nc, DOY: 270
Processing file: ./magn20242701950.nc, DOY: 270
Processing file: ./magn20242702000.nc, DOY: 270
Processing file: ./magn20242702010.nc, DOY: 270
Processing file: ./magn20242702020.nc, DOY: 270
Processing file: ./magn20242702030.nc, DOY: 270
Processing file: ./magn20242702040.nc, DOY: 270
Processing file: ./magn20242702050.nc, DOY: 270
Processing file: ./magn20242702100.nc, DOY: 270
Processing file: ./magn20242702110.nc, DOY: 270
Processing file: ./magn20242702120.nc, DOY: 270
Processing file: ./magn20242702130.nc, DOY: 270
Processing file: ./magn20242702140.nc, DOY: 270
Processing file: ./magn20242702150.nc, DOY: 270
Processing file: ./magn20242702200.nc, DOY: 270
Processing file: ./magn20242702210.nc, DOY: 270
Processing file: ./magn20242702220.nc, DOY: 270
Processing file: ./magn20242702230.nc, DOY: 270
Processing file: ./magn20242702240.nc, DOY: 270
Processing file: ./magn20242702250.nc, DOY: 270
Processing file: ./magn20242702300.nc, DOY: 270
Processing file: ./magn20242702310.nc, DOY: 270
Processing file: ./magn20242702320.nc, DOY: 270
Processing file: ./magn20242702330.nc, DOY: 270
Processing file: ./magn20242702340.nc, DOY: 270
Processing file: ./magn20242702350.nc, DOY: 270
Processing file: ./magn20242710000.nc, DOY: 271
Processing file: ./magn20242710010.nc, DOY: 271
Processing file: ./magn20242710020.nc, DOY: 271
Processing file: ./magn20242710030.nc, DOY: 271
Processing file: ./magn20242710040.nc, DOY: 271
Processing file: ./magn20242710050.nc, DOY: 271
Processing file: ./magn20242710100.nc, DOY: 271
Processing file: ./magn20242710110.nc, DOY: 271
Processing file: ./magn20242710120.nc, DOY: 271
Processing file: ./magn20242710130.nc, DOY: 271
Processing file: ./magn20242710140.nc, DOY: 271
Processing file: ./magn20242710150.nc, DOY: 271
Processing file: ./magn20242710200.nc, DOY: 271
Processing file: ./magn20242710210.nc, DOY: 271
Processing file: ./magn20242710220.nc, DOY: 271
Processing file: ./magn20242710230.nc, DOY: 271
Processing file: ./magn20242710240.nc, DOY: 271
Processing file: ./magn20242710250.nc, DOY: 271
Processing file: ./magn20242710300.nc, DOY: 271
Processing file: ./magn20242710310.nc, DOY: 271
Processing file: ./magn20242710320.nc, DOY: 271
Processing file: ./magn20242710330.nc, DOY: 271
Processing file: ./magn20242710340.nc, DOY: 271
Processing file: ./magn20242710350.nc, DOY: 271
Processing file: ./magn20242710400.nc, DOY: 271
Processing file: ./magn20242710410.nc, DOY: 271
Processing file: ./magn20242710420.nc, DOY: 271
Processing file: ./magn20242710430.nc, DOY: 271
Processing file: ./magn20242710440.nc, DOY: 271
Processing file: ./magn20242710450.nc, DOY: 271
Processing file: ./magn20242710500.nc, DOY: 271
Processing file: ./magn20242710510.nc, DOY: 271
Processing file: ./magn20242710520.nc, DOY: 271
Processing file: ./magn20242710530.nc, DOY: 271
Processing file: ./magn20242710540.nc, DOY: 271
Processing file: ./magn20242710550.nc, DOY: 271
Processing file: ./magn20242710600.nc, DOY: 271
Processing file: ./magn20242710610.nc, DOY: 271
Processing file: ./magn20242710620.nc, DOY: 271
Processing file: ./magn20242710630.nc, DOY: 271
Processing file: ./magn20242710640.nc, DOY: 271
Processing file: ./magn20242710650.nc, DOY: 271
Processing file: ./magn20242710700.nc, DOY: 271
Processing file: ./magn20242710710.nc, DOY: 271
Processing file: ./magn20242710720.nc, DOY: 271
Processing file: ./magn20242710730.nc, DOY: 271
Processing file: ./magn20242710740.nc, DOY: 271
Processing file: ./magn20242710750.nc, DOY: 271
Processing file: ./magn20242710800.nc, DOY: 271
Processing file: ./magn20242710810.nc, DOY: 271
Processing file: ./magn20242710820.nc, DOY: 271
Processing file: ./magn20242710830.nc, DOY: 271
Processing file: ./magn20242710840.nc, DOY: 271
Processing file: ./magn20242710850.nc, DOY: 271
Processing file: ./magn20242710900.nc, DOY: 271
Processing file: ./magn20242710910.nc, DOY: 271
Processing file: ./magn20242710920.nc, DOY: 271
Processing file: ./magn20242710930.nc, DOY: 271
Processing file: ./magn20242710940.nc, DOY: 271
Processing file: ./magn20242710950.nc, DOY: 271
Processing file: ./magn20242711000.nc, DOY: 271
Processing file: ./magn20242711010.nc, DOY: 271
Processing file: ./magn20242711020.nc, DOY: 271
Processing file: ./magn20242711030.nc, DOY: 271
Processing file: ./magn20242711040.nc, DOY: 271
Processing file: ./magn20242711050.nc, DOY: 271
Processing file: ./magn20242711100.nc, DOY: 271
Processing file: ./magn20242711110.nc, DOY: 271
Processing file: ./magn20242711120.nc, DOY: 271
Processing file: ./magn20242711130.nc, DOY: 271
Processing file: ./magn20242711140.nc, DOY: 271
Processing file: ./magn20242711150.nc, DOY: 271
Processing file: ./magn20242711200.nc, DOY: 271
Processing file: ./magn20242711210.nc, DOY: 271
Processing file: ./magn20242711220.nc, DOY: 271
Processing file: ./magn20242711230.nc, DOY: 271
Processing file: ./magn20242711240.nc, DOY: 271
Processing file: ./magn20242711250.nc, DOY: 271
Processing file: ./magn20242711300.nc, DOY: 271
Processing file: ./magn20242711310.nc, DOY: 271
Processing file: ./magn20242711320.nc, DOY: 271
Processing file: ./magn20242711330.nc, DOY: 271
Processing file: ./magn20242711340.nc, DOY: 271
Processing file: ./magn20242711350.nc, DOY: 271
Processing file: ./magn20242711400.nc, DOY: 271
Processing file: ./magn20242711410.nc, DOY: 271
Processing file: ./magn20242711420.nc, DOY: 271
Processing file: ./magn20242711430.nc, DOY: 271
Processing file: ./magn20242711440.nc, DOY: 271
Processing file: ./magn20242711450.nc, DOY: 271
Processing file: ./magn20242711500.nc, DOY: 271
Processing file: ./magn20242711510.nc, DOY: 271
Processing file: ./magn20242711520.nc, DOY: 271
Processing file: ./magn20242711530.nc, DOY: 271
Processing file: ./magn20242711540.nc, DOY: 271
Processing file: ./magn20242711550.nc, DOY: 271
Processing file: ./magn20242711600.nc, DOY: 271
Processing file: ./magn20242711610.nc, DOY: 271
Processing file: ./magn20242711620.nc, DOY: 271
Processing file: ./magn20242711630.nc, DOY: 271
Processing file: ./magn20242711640.nc, DOY: 271
Processing file: ./magn20242711650.nc, DOY: 271
Processing file: ./magn20242711700.nc, DOY: 271
Processing file: ./magn20242711710.nc, DOY: 271
Processing file: ./magn20242711720.nc, DOY: 271
Processing file: ./magn20242711730.nc, DOY: 271
Processing file: ./magn20242711740.nc, DOY: 271
Processing file: ./magn20242711750.nc, DOY: 271
Processing file: ./magn20242711800.nc, DOY: 271
Processing file: ./magn20242711810.nc, DOY: 271
Processing file: ./magn20242711820.nc, DOY: 271
Processing file: ./magn20242711830.nc, DOY: 271
Processing file: ./magn20242711840.nc, DOY: 271
Processing file: ./magn20242711850.nc, DOY: 271
Processing file: ./magn20242711900.nc, DOY: 271
Processing file: ./magn20242711910.nc, DOY: 271
Processing file: ./magn20242711920.nc, DOY: 271
Processing file: ./magn20242711930.nc, DOY: 271
Processing file: ./magn20242711940.nc, DOY: 271
Processing file: ./magn20242711950.nc, DOY: 271
Processing file: ./magn20242712000.nc, DOY: 271
Processing file: ./magn20242712010.nc, DOY: 271
Processing file: ./magn20242712020.nc, DOY: 271
Processing file: ./magn20242712030.nc, DOY: 271
Processing file: ./magn20242712040.nc, DOY: 271
Processing file: ./magn20242712050.nc, DOY: 271
Processing file: ./magn20242712100.nc, DOY: 271
Processing file: ./magn20242712110.nc, DOY: 271
Processing file: ./magn20242712120.nc, DOY: 271
Processing file: ./magn20242712130.nc, DOY: 271
Processing file: ./magn20242712140.nc, DOY: 271
Processing file: ./magn20242712150.nc, DOY: 271

In [20]:
# ls *.npy

In [21]:
# !ls -lR ./*.npy | wc -l

In [22]:
import numpy as np
import glob
import re

npy_files = glob.glob("magn2024*.npy")

def extract_doy(filename):
    match = re.search(r'magn2024(\d{3})\.npy', filename)
    if match:
        return int(match.group(1))
    return 0

npy_files.sort(key=extract_doy)

print(f"Found {len(npy_files)} NPY files to process.")

all_data = []

for i, file in enumerate(npy_files):
    doy = extract_doy(file)
    print(f"Processing {file} (DOY {doy}) - {i+1}/{len(npy_files)}")

    data = np.load(file)

    all_data.append(data)

    print(f"  Shape: {data.shape}")

combined_data = np.concatenate(all_data, axis=0)

print(f"\nCombined data. Final shape: {combined_data.shape}")

output_file = "MAGGIA_TEC_maps_intersection_2024.npy"
np.save(output_file, combined_data)

print(f"\nFile {output_file} saved successfully!")
print(f"File size: {combined_data.nbytes / (1024**2):.2f} MB")

Found 106 NPY files to process.
Processing magn2024061.npy (DOY 61) - 1/106
  Shape: (96, 241, 221)
Processing magn2024062.npy (DOY 62) - 2/106
  Shape: (96, 241, 221)
Processing magn2024063.npy (DOY 63) - 3/106
  Shape: (96, 241, 221)
Processing magn2024064.npy (DOY 64) - 4/106
  Shape: (96, 241, 221)
Processing magn2024065.npy (DOY 65) - 5/106
  Shape: (96, 241, 221)
Processing magn2024066.npy (DOY 66) - 6/106
  Shape: (96, 241, 221)
Processing magn2024067.npy (DOY 67) - 7/106
  Shape: (96, 241, 221)
Processing magn2024068.npy (DOY 68) - 8/106
  Shape: (96, 241, 221)
Processing magn2024069.npy (DOY 69) - 9/106
  Shape: (96, 241, 221)
Processing magn2024070.npy (DOY 70) - 10/106
  Shape: (96, 241, 221)
Processing magn2024071.npy (DOY 71) - 11/106
  Shape: (96, 241, 221)
Processing magn2024072.npy (DOY 72) - 12/106
  Shape: (96, 241, 221)
Processing magn2024073.npy (DOY 73) - 13/106
  Shape: (96, 241, 221)
Processing magn2024074.npy (DOY 74) - 14/106
  Shape: (96, 241, 221)
Processing magn2024075.npy (DOY 75) - 15/106
  Shape: (96, 241, 221)
Processing magn2024076.npy (DOY 76) - 16/106
  Shape: (96, 241, 221)
Processing magn2024077.npy (DOY 77) - 17/106
  Shape: (96, 241, 221)
Processing magn2024078.npy (DOY 78) - 18/106
  Shape: (96, 241, 221)
Processing magn2024079.npy (DOY 79) - 19/106
  Shape: (96, 241, 221)
Processing magn2024080.npy (DOY 80) - 20/106
  Shape: (96, 241, 221)
Processing magn2024081.npy (DOY 81) - 21/106
  Shape: (96, 241, 221)
Processing magn2024086.npy (DOY 86) - 22/106
  Shape: (96, 241, 221)
Processing magn2024087.npy (DOY 87) - 23/106
  Shape: (96, 241, 221)
Processing magn2024088.npy (DOY 88) - 24/106
  Shape: (96, 241, 221)
Processing magn2024089.npy (DOY 89) - 25/106
  Shape: (96, 241, 221)
Processing magn2024091.npy (DOY 91) - 26/106
  Shape: (96, 241, 221)
Processing magn2024153.npy (DOY 153) - 27/106
  Shape: (96, 241, 221)
Processing magn2024154.npy (DOY 154) - 28/106
  Shape: (96, 241, 221)
Processing magn2024155.npy (DOY 155) - 29/106
  Shape: (96, 241, 221)
Processing magn2024156.npy (DOY 156) - 30/106
  Shape: (96, 241, 221)
Processing magn2024157.npy (DOY 157) - 31/106
  Shape: (96, 241, 221)
Processing magn2024158.npy (DOY 158) - 32/106
  Shape: (96, 241, 221)
Processing magn2024159.npy (DOY 159) - 33/106
  Shape: (96, 241, 221)
Processing magn2024160.npy (DOY 160) - 34/106
  Shape: (96, 241, 221)
Processing magn2024161.npy (DOY 161) - 35/106
  Shape: (96, 241, 221)
Processing magn2024162.npy (DOY 162) - 36/106
  Shape: (96, 241, 221)
Processing magn2024163.npy (DOY 163) - 37/106
  Shape: (96, 241, 221)
Processing magn2024164.npy (DOY 164) - 38/106
  Shape: (96, 241, 221)
Processing magn2024165.npy (DOY 165) - 39/106
  Shape: (96, 241, 221)
Processing magn2024166.npy (DOY 166) - 40/106
  Shape: (96, 241, 221)
Processing magn2024167.npy (DOY 167) - 41/106
  Shape: (96, 241, 221)
Processing magn2024168.npy (DOY 168) - 42/106
  Shape: (96, 241, 221)
Processing magn2024169.npy (DOY 169) - 43/106
  Shape: (96, 241, 221)
Processing magn2024170.npy (DOY 170) - 44/106
  Shape: (96, 241, 221)
Processing magn2024171.npy (DOY 171) - 45/106
  Shape: (96, 241, 221)
Processing magn2024173.npy (DOY 173) - 46/106
  Shape: (96, 241, 221)
Processing magn2024174.npy (DOY 174) - 47/106
  Shape: (96, 241, 221)
Processing magn2024175.npy (DOY 175) - 48/106
  Shape: (96, 241, 221)
Processing magn2024176.npy (DOY 176) - 49/106
  Shape: (96, 241, 221)
Processing magn2024177.npy (DOY 177) - 50/106
  Shape: (96, 241, 221)
Processing magn2024180.npy (DOY 180) - 51/106
  Shape: (96, 241, 221)
Processing magn2024181.npy (DOY 181) - 52/106
  Shape: (96, 241, 221)
Processing magn2024247.npy (DOY 247) - 53/106
  Shape: (96, 241, 221)
Processing magn2024248.npy (DOY 248) - 54/106
  Shape: (96, 241, 221)
Processing magn2024249.npy (DOY 249) - 55/106
  Shape: (192, 241, 221)
Processing magn2024250.npy (DOY 250) - 56/106
  Shape: (168, 241, 221)
Processing magn2024251.npy (DOY 251) - 57/106
  Shape: (144, 241, 221)
Processing magn2024252.npy (DOY 252) - 58/106
  Shape: (144, 241, 221)
Processing magn2024253.npy (DOY 253) - 59/106
  Shape: (144, 241, 221)
Processing magn2024254.npy (DOY 254) - 60/106
  Shape: (144, 241, 221)
Processing magn2024255.npy (DOY 255) - 61/106
  Shape: (144, 241, 221)
Processing magn2024256.npy (DOY 256) - 62/106
  Shape: (144, 241, 221)
Processing magn2024257.npy (DOY 257) - 63/106
  Shape: (144, 241, 221)
Processing magn2024258.npy (DOY 258) - 64/106
  Shape: (144, 241, 221)
Processing magn2024261.npy (DOY 261) - 65/106
  Shape: (144, 241, 221)
Processing magn2024262.npy (DOY 262) - 66/106
  Shape: (144, 241, 221)
Processing magn2024263.npy (DOY 263) - 67/106
  Shape: (144, 241, 221)
Processing magn2024264.npy (DOY 264) - 68/106
  Shape: (144, 241, 221)
Processing magn2024265.npy (DOY 265) - 69/106
  Shape: (144, 241, 221)
Processing magn2024266.npy (DOY 266) - 70/106
  Shape: (144, 241, 221)
Processing magn2024267.npy (DOY 267) - 71/106
  Shape: (144, 241, 221)
Processing magn2024268.npy (DOY 268) - 72/106
  Shape: (144, 241, 221)
Processing magn2024269.npy (DOY 269) - 73/106
  Shape: (144, 241, 221)
Processing magn2024270.npy (DOY 270) - 74/106
  Shape: (144, 241, 221)
Processing magn2024271.npy (DOY 271) - 75/106
  Shape: (144, 241, 221)
Processing magn2024272.npy (DOY 272) - 76/106
  Shape: (144, 241, 221)
Processing magn2024274.npy (DOY 274) - 77/106
  Shape: (144, 241, 221)
Processing magn2024336.npy (DOY 336) - 78/106
  Shape: (144, 241, 221)
Processing magn2024337.npy (DOY 337) - 79/106
  Shape: (144, 241, 221)
Processing magn2024338.npy (DOY 338) - 80/106
  Shape: (144, 241, 221)
Processing magn2024339.npy (DOY 339) - 81/106
  Shape: (144, 241, 221)
Processing magn2024340.npy (DOY 340) - 82/106
  Shape: (144, 241, 221)
Processing magn2024341.npy (DOY 341) - 83/106
  Shape: (144, 241, 221)
Processing magn2024342.npy (DOY 342) - 84/106
  Shape: (144, 241, 221)
Processing magn2024343.npy (DOY 343) - 85/106
  Shape: (144, 241, 221)
Processing magn2024344.npy (DOY 344) - 86/106
  Shape: (144, 241, 221)
Processing magn2024345.npy (DOY 345) - 87/106
  Shape: (144, 241, 221)
Processing magn2024346.npy (DOY 346) - 88/106
  Shape: (144, 241, 221)
Processing magn2024347.npy (DOY 347) - 89/106
  Shape: (144, 241, 221)
Processing magn2024349.npy (DOY 349) - 90/106
  Shape: (144, 241, 221)
Processing magn2024350.npy (DOY 350) - 91/106
  Shape: (144, 241, 221)
Processing magn2024351.npy (DOY 351) - 92/106
  Shape: (144, 241, 221)
Processing magn2024352.npy (DOY 352) - 93/106
  Shape: (144, 241, 221)
Processing magn2024353.npy (DOY 353) - 94/106
  Shape: (144, 241, 221)
Processing magn2024354.npy (DOY 354) - 95/106
  Shape: (144, 241, 221)
Processing magn2024355.npy (DOY 355) - 96/106
  Shape: (144, 241, 221)
Processing magn2024356.npy (DOY 356) - 97/106
  Shape: (144, 241, 221)
Processing magn2024357.npy (DOY 357) - 98/106
  Shape: (144, 241, 221)
Processing magn2024358.npy (DOY 358) - 99/106
  Shape: (144, 241, 221)
Processing magn2024359.npy (DOY 359) - 100/106
  Shape: (144, 241, 221)
Processing magn2024360.npy (DOY 360) - 101/106
  Shape: (144, 241, 221)
Processing magn2024361.npy (DOY 361) - 102/106
  Shape: (144, 241, 221)
Processing magn2024362.npy (DOY 362) - 103/106
  Shape: (144, 241, 221)
Processing magn2024363.npy (DOY 363) - 104/106
  Shape: (144, 241, 221)
Processing magn2024364.npy (DOY 364) - 105/106
  Shape: (144, 241, 221)
Processing magn2024365.npy (DOY 365) - 106/106
  Shape: (144, 241, 221)

Combined data. Final shape: (12744, 241, 221)

File MAGGIA_TEC_maps_intersection_2024.npy saved successfully!
File size: 2589.26 MB

# 5D array - merge 2022-2024 data

In [23]:
%cd './'

/content

In [24]:
import numpy as np

In [25]:
!ls *.npy

MAGGIA_TEC_maps_intersection_2022.npy  magn2022262.npy	magn2024165.npy
MAGGIA_TEC_maps_intersection_2024.npy  magn2022264.npy	magn2024166.npy
magn2022060.npy			       magn2022265.npy	magn2024167.npy
magn2022061.npy			       magn2022266.npy	magn2024168.npy
magn2022062.npy			       magn2022267.npy	magn2024169.npy
magn2022063.npy			       magn2022268.npy	magn2024170.npy
magn2022064.npy			       magn2022269.npy	magn2024171.npy
magn2022065.npy			       magn2022270.npy	magn2024173.npy
magn2022066.npy			       magn2022271.npy	magn2024174.npy
magn2022067.npy			       magn2022272.npy	magn2024175.npy
magn2022069.npy			       magn2022273.npy	magn2024176.npy
magn2022070.npy			       magn2022338.npy	magn2024177.npy
magn2022071.npy			       magn2022339.npy	magn2024180.npy
magn2022073.npy			       magn2022340.npy	magn2024181.npy
magn2022074.npy			       magn2022348.npy	magn2024247.npy
magn2022075.npy			       magn2022349.npy	magn2024248.npy
magn2022076.npy			       magn2022350.npy	magn2024249.npy
magn2022077.npy			       magn2022351.npy	magn2024250.npy
magn2022078.npy			       magn2022352.npy	magn2024251.npy
magn2022079.npy			       magn2022353.npy	magn2024252.npy
magn2022080.npy			       magn2022354.npy	magn2024253.npy
magn2022081.npy			       magn2022356.npy	magn2024254.npy
magn2022082.npy			       magn2022357.npy	magn2024255.npy
magn2022083.npy			       magn2022358.npy	magn2024256.npy
magn2022084.npy			       magn2022359.npy	magn2024257.npy
magn2022085.npy			       magn2022360.npy	magn2024258.npy
magn2022086.npy			       magn2022362.npy	magn2024261.npy
magn2022090.npy			       magn2022363.npy	magn2024262.npy
magn2022152.npy			       magn2022364.npy	magn2024263.npy
magn2022153.npy			       magn2022365.npy	magn2024264.npy
magn2022154.npy			       magn2024061.npy	magn2024265.npy
magn2022156.npy			       magn2024062.npy	magn2024266.npy
magn2022157.npy			       magn2024063.npy	magn2024267.npy
magn2022158.npy			       magn2024064.npy	magn2024268.npy
magn2022159.npy			       magn2024065.npy	magn2024269.npy
magn2022160.npy			       magn2024066.npy	magn2024270.npy
magn2022161.npy			       magn2024067.npy	magn2024271.npy
magn2022162.npy			       magn2024068.npy	magn2024272.npy
magn2022163.npy			       magn2024069.npy	magn2024274.npy
magn2022164.npy			       magn2024070.npy	magn2024336.npy
magn2022165.npy			       magn2024071.npy	magn2024337.npy
magn2022166.npy			       magn2024072.npy	magn2024338.npy
magn2022167.npy			       magn2024073.npy	magn2024339.npy
magn2022168.npy			       magn2024074.npy	magn2024340.npy
magn2022169.npy			       magn2024075.npy	magn2024341.npy
magn2022170.npy			       magn2024076.npy	magn2024342.npy
magn2022171.npy			       magn2024077.npy	magn2024343.npy
magn2022172.npy			       magn2024078.npy	magn2024344.npy
magn2022173.npy			       magn2024079.npy	magn2024345.npy
magn2022174.npy			       magn2024080.npy	magn2024346.npy
magn2022176.npy			       magn2024081.npy	magn2024347.npy
magn2022178.npy			       magn2024086.npy	magn2024349.npy
magn2022181.npy			       magn2024087.npy	magn2024350.npy
magn2022245.npy			       magn2024088.npy	magn2024351.npy
magn2022246.npy			       magn2024089.npy	magn2024352.npy
magn2022247.npy			       magn2024091.npy	magn2024353.npy
magn2022248.npy			       magn2024153.npy	magn2024354.npy
magn2022249.npy			       magn2024154.npy	magn2024355.npy
magn2022250.npy			       magn2024155.npy	magn2024356.npy
magn2022251.npy			       magn2024156.npy	magn2024357.npy
magn2022252.npy			       magn2024157.npy	magn2024358.npy
magn2022253.npy			       magn2024158.npy	magn2024359.npy
magn2022254.npy			       magn2024159.npy	magn2024360.npy
magn2022255.npy			       magn2024160.npy	magn2024361.npy
magn2022256.npy			       magn2024161.npy	magn2024362.npy
magn2022258.npy			       magn2024162.npy	magn2024363.npy
magn2022260.npy			       magn2024163.npy	magn2024364.npy
magn2022261.npy			       magn2024164.npy	magn2024365.npy

In [26]:
%pwd

'/content'

In [27]:
!ls

MAGGIA_TEC_maps_intersection_2022.npy		      magn20232692200.nc
MAGGIA_TEC_maps_intersection_2024.npy		      magn20232692215.nc
MAGGIA_TEC_maps_intersection_raw_files_2022_2024.zip  magn20232692230.nc
magn20220600000.nc				      magn20232692245.nc
magn20220600015.nc				      magn20232692300.nc
magn20220600030.nc				      magn20232692315.nc
magn20220600045.nc				      magn20232692330.nc
magn20220600100.nc				      magn20232692345.nc
magn20220600115.nc				      magn20232700000.nc
magn20220600130.nc				      magn20232700015.nc
magn20220600145.nc				      magn20232700030.nc
magn20220600200.nc				      magn20232700045.nc
magn20220600215.nc				      magn20232700100.nc
magn20220600230.nc				      magn20232700115.nc
magn20220600245.nc				      magn20232700130.nc
magn20220600300.nc				      magn20232700145.nc
magn20220600315.nc				      magn20232700200.nc
magn20220600330.nc				      magn20232700215.nc
magn20220600345.nc				      magn20232700230.nc
magn20220600400.nc				      magn20232700245.nc
magn20220600415.nc				      magn20232700300.nc
magn20220600430.nc				      magn20232700315.nc
magn20220600445.nc				      magn20232700330.nc
magn20220600500.nc				      magn20232700345.nc
magn20220600515.nc				      magn20232700400.nc
magn20220600530.nc				      magn20232700415.nc
magn20220600545.nc				      magn20232700430.nc
magn20220600600.nc				      magn20232700445.nc
magn20220600615.nc				      magn20232700500.nc
magn20220600630.nc				      magn20232700515.nc
magn20220600645.nc				      magn20232700530.nc
magn20220600700.nc				      magn20232700545.nc
magn20220600715.nc				      magn20232700600.nc
magn20220600730.nc				      magn20232700615.nc
magn20220600745.nc				      magn20232700630.nc
magn20220600800.nc				      magn20232700645.nc
magn20220600815.nc				      magn20232700700.nc
magn20220600830.nc				      magn20232700715.nc
magn20220600845.nc				      magn20232700730.nc
magn20220600900.nc				      magn20232700745.nc
magn20220600915.nc				      magn20232700800.nc
magn20220600930.nc				      magn20232700815.nc
magn20220600945.nc				      magn20232700830.nc
magn20220601000.nc				      magn20232700845.nc
magn20220601015.nc				      magn20232700900.nc
magn20220601030.nc				      magn20232700915.nc
magn20220601045.nc				      magn20232700930.nc
magn20220601100.nc				      magn20232700945.nc
magn20220601115.nc				      magn20232701000.nc
magn20220601130.nc				      magn20232701015.nc
magn20220601145.nc				      magn20232701030.nc
magn20220601200.nc				      magn20232701045.nc
magn20220601215.nc				      magn20232701100.nc
magn20220601230.nc				      magn20232701115.nc
magn20220601245.nc				      magn20232701130.nc
magn20220601300.nc				      magn20232701145.nc
magn20220601315.nc				      magn20232701200.nc
magn20220601330.nc				      magn20232701215.nc
magn20220601345.nc				      magn20232701230.nc
magn20220601400.nc				      magn20232701245.nc
magn20220601415.nc				      magn20232701300.nc
magn20220601430.nc				      magn20232701315.nc
magn20220601445.nc				      magn20232701330.nc
magn20220601500.nc				      magn20232701345.nc
magn20220601515.nc				      magn20232701400.nc
magn20220601530.nc				      magn20232701415.nc
magn20220601545.nc				      magn20232701430.nc
magn20220601600.nc				      magn20232701445.nc
magn20220601615.nc				      magn20232701500.nc
magn20220601630.nc				      magn20232701515.nc
magn20220601645.nc				      magn20232701530.nc
magn20220601700.nc				      magn20232701545.nc
magn20220601715.nc				      magn20232701600.nc
magn20220601730.nc				      magn20232701615.nc
magn20220601745.nc				      magn20232701630.nc
magn20220601800.nc				      magn20232701645.nc
magn20220601815.nc				      magn20232701700.nc
magn20220601830.nc				      magn20232701715.nc
magn20220601845.nc				      magn20232701730.nc
magn20220601900.nc				      magn20232701745.nc
magn20220601915.nc				      magn20232701800.nc
magn20220601930.nc				      magn20232701815.nc
magn20220601945.nc				      magn20232701830.nc
magn20220602000.nc				      magn20232701845.nc
magn20220602015.nc				      magn20232701900.nc
magn20220602030.nc				      magn20232701915.nc
magn20220602045.nc				      magn20232701930.nc
magn20220602100.nc				      magn20232701945.nc
magn20220602115.nc				      magn20232702000.nc
magn20220602130.nc				      magn20232702015.nc
magn20220602145.nc				      magn20232702030.nc
magn20220602200.nc				      magn20232702045.nc
magn20220602215.nc				      magn20232702100.nc
magn20220602230.nc				      magn20232702115.nc
magn20220602245.nc				      magn20232702130.nc
magn20220602300.nc				      magn20232702145.nc
magn20220602315.nc				      magn20232702200.nc
magn20220602330.nc				      magn20232702215.nc
magn20220602345.nc				      magn20232702230.nc
magn2022060.npy					      magn20232702245.nc
magn20220610000.nc				      magn20232702300.nc
magn20220610015.nc				      magn20232702315.nc
magn20220610030.nc				      magn20232702330.nc
magn20220610045.nc				      magn20232702345.nc
magn20220610100.nc				      magn20232710000.nc
magn20220610115.nc				      magn20232710015.nc
magn20220610130.nc				      magn20232710030.nc
magn20220610145.nc				      magn20232710045.nc
magn20220610200.nc				      magn20232710100.nc
magn20220610215.nc				      magn20232710115.nc
magn20220610230.nc				      magn20232710130.nc
magn20220610245.nc				      magn20232710145.nc
magn20220610300.nc				      magn20232710200.nc
magn20220610315.nc				      magn20232710215.nc
magn20220610330.nc				      magn20232710230.nc
magn20220610345.nc				      magn20232710245.nc
magn20220610400.nc				      magn20232710300.nc
magn20220610415.nc				      magn20232710315.nc
magn20220610430.nc				      magn20232710330.nc
magn20220610445.nc				      magn20232710345.nc
magn20220610500.nc				      magn20232710400.nc
magn20220610515.nc				      magn20232710415.nc
magn20220610530.nc				      magn20232710430.nc
magn20220610545.nc				      magn20232710445.nc
magn20220610600.nc				      magn20232710500.nc
magn20220610615.nc				      magn20232710515.nc
magn20220610630.nc				      magn20232710530.nc
magn20220610645.nc				      magn20232710545.nc
magn20220610700.nc				      magn20232710600.nc
magn20220610715.nc				      magn20232710615.nc
magn20220610730.nc				      magn20232710630.nc
magn20220610745.nc				      magn20232710645.nc
magn20220610800.nc				      magn20232710700.nc
magn20220610815.nc				      magn20232710715.nc
magn20220610830.nc				      magn20232710730.nc
magn20220610845.nc				      magn20232710745.nc
magn20220610900.nc				      magn20232710800.nc
magn20220610915.nc				      magn20232710815.nc
magn20220610930.nc				      magn20232710830.nc
magn20220610945.nc				      magn20232710845.nc
magn20220611000.nc				      magn20232710900.nc
magn20220611015.nc				      magn20232710915.nc
magn20220611030.nc				      magn20232710930.nc
magn20220611045.nc				      magn20232710945.nc
magn20220611100.nc				      magn20232711000.nc
magn20220611115.nc				      magn20232711015.nc
magn20220611130.nc				      magn20232711030.nc
magn20220611145.nc				      magn20232711045.nc
magn20220611200.nc				      magn20232711100.nc
magn20220611215.nc				      magn20232711115.nc
magn20220611230.nc				      magn20232711130.nc
magn20220611245.nc				      magn20232711145.nc
magn20220611300.nc				      magn20232711200.nc
magn20220611315.nc				      magn20232711215.nc
magn20220611330.nc				      magn20232711230.nc
magn20220611345.nc				      magn20232711245.nc
magn20220611400.nc				      magn20232711300.nc
magn20220611415.nc				      magn20232711315.nc
magn20220611430.nc				      magn20232711330.nc
magn20220611445.nc				      magn20232711345.nc
magn20220611500.nc				      magn20232711400.nc
magn20220611515.nc				      magn20232711415.nc
magn20220611530.nc				      magn20232711430.nc
magn20220611545.nc				      magn20232711445.nc
magn20220611600.nc				      magn20232711500.nc
magn20220611615.nc				      magn20232711515.nc
magn20220611630.nc				      magn20232711530.nc
magn20220611645.nc				      magn20232711545.nc
magn20220611700.nc				      magn20232711600.nc
magn20220611715.nc				      magn20232711615.nc
magn20220611730.nc				      magn20232711630.nc
magn20220611745.nc				      magn20232711645.nc
magn20220611800.nc				      magn20232711700.nc
magn20220611815.nc				      magn20232711715.nc
magn20220611830.nc				      magn20232711730.nc
magn20220611845.nc				      magn20232711745.nc
magn20220611900.nc				      magn20232711800.nc
magn20220611915.nc				      magn20232711815.nc
magn20220611930.nc				      magn20232711830.nc
magn20220611945.nc				      magn20232711845.nc
magn20220612000.nc				      magn20232711900.nc
magn20220612015.nc				      magn20232711915.nc
magn20220612030.nc				      magn20232711930.nc
magn20220612045.nc				      magn20232711945.nc
magn20220612100.nc				      magn20232712000.nc
magn20220612115.nc				      magn20232712015.nc
magn20220612130.nc				      magn20232712030.nc
magn20220612145.nc				      magn20232712045.nc
magn20220612200.nc				      magn20232712100.nc
magn20220612215.nc				      magn20232712115.nc
magn20220612230.nc				      magn20232712130.nc
magn20220612245.nc				      magn20232712145.nc
magn20220612300.nc				      magn20232712200.nc
magn20220612315.nc				      magn20232712215.nc
magn20220612330.nc				      magn20232712230.nc
magn20220612345.nc				      magn20232712245.nc
magn2022061.npy					      magn20232712300.nc
magn20220620000.nc				      magn20232712315.nc
magn20220620015.nc				      magn20232712330.nc
magn20220620030.nc				      magn20232712345.nc
magn20220620045.nc				      magn20232720000.nc
magn20220620100.nc				      magn20232720015.nc
magn20220620115.nc				      magn20232720030.nc
magn20220620130.nc				      magn20232720045.nc
magn20220620145.nc				      magn20232720100.nc
magn20220620200.nc				      magn20232720115.nc
magn20220620215.nc				      magn20232720130.nc
magn20220620230.nc				      magn20232720145.nc
magn20220620245.nc				      magn20232720200.nc
magn20220620300.nc				      magn20232720215.nc
magn20220620315.nc				      magn20232720230.nc
magn20220620330.nc				      magn20232720245.nc
magn20220620345.nc				      magn20232720300.nc
magn20220620400.nc				      magn20232720315.nc
magn20220620415.nc				      magn20232720330.nc
magn20220620430.nc				      magn20232720345.nc
magn20220620445.nc				      magn20232720400.nc
magn20220620500.nc				      magn20232720415.nc
magn20220620515.nc				      magn20232720430.nc
magn20220620530.nc				      magn20232720445.nc
magn20220620545.nc				      magn20232720500.nc
magn20220620600.nc				      magn20232720515.nc
magn20220620615.nc				      magn20232720530.nc
magn20220620630.nc				      magn20232720545.nc
magn20220620645.nc				      magn20232720600.nc
magn20220620700.nc				      magn20232720615.nc
magn20220620715.nc				      magn20232720630.nc
magn20220620730.nc				      magn20232720645.nc
magn20220620745.nc				      magn20232720700.nc
magn20220620800.nc				      magn20232720715.nc
magn20220620815.nc				      magn20232720730.nc
magn20220620830.nc				      magn20232720745.nc
magn20220620845.nc				      magn20232720800.nc
magn20220620900.nc				      magn20232720815.nc
magn20220620915.nc				      magn20232720830.nc
magn20220620930.nc				      magn20232720845.nc
magn20220620945.nc				      magn20232720900.nc
magn20220621000.nc				      magn20232720915.nc
magn20220621015.nc				      magn20232720930.nc
magn20220621030.nc				      magn20232720945.nc
magn20220621045.nc				      magn20232721000.nc
magn20220621100.nc				      magn20232721015.nc
magn20220621115.nc				      magn20232721030.nc
magn20220621130.nc				      magn20232721045.nc
magn20220621145.nc				      magn20232721100.nc
magn20220621200.nc				      magn20232721115.nc
magn20220621215.nc				      magn20232721130.nc
magn20220621230.nc				      magn20232721145.nc
magn20220621245.nc				      magn20232721200.nc
magn20220621300.nc				      magn20232721215.nc
magn20220621315.nc				      magn20232721230.nc
magn20220621330.nc				      magn20232721245.nc
magn20220621345.nc				      magn20232721300.nc
magn20220621400.nc				      magn20232721315.nc
magn20220621415.nc				      magn20232721330.nc
magn20220621430.nc				      magn20232721345.nc
magn20220621445.nc				      magn20232721400.nc
magn20220621500.nc				      magn20232721415.nc
magn20220621515.nc				      magn20232721430.nc
magn20220621530.nc				      magn20232721445.nc
magn20220621545.nc				      magn20232721500.nc
magn20220621600.nc				      magn20232721515.nc
magn20220621615.nc				      magn20232721530.nc
magn20220621630.nc				      magn20232721545.nc
magn20220621645.nc				      magn20232721600.nc
magn20220621700.nc				      magn20232721615.nc
magn20220621715.nc				      magn20232721630.nc
magn20220621730.nc				      magn20232721645.nc
magn20220621745.nc				      magn20232721700.nc
magn20220621800.nc				      magn20232721715.nc
magn20220621815.nc				      magn20232721730.nc
magn20220621830.nc				      magn20232721745.nc
magn20220621845.nc				      magn20232721800.nc
magn20220621900.nc				      magn20232721815.nc
magn20220621915.nc				      magn20232721830.nc
magn20220621930.nc				      magn20232721845.nc
magn20220621945.nc				      magn20232721900.nc
magn20220622000.nc				      magn20232721915.nc
magn20220622015.nc				      magn20232721930.nc
magn20220622030.nc				      magn20232721945.nc
magn20220622045.nc				      magn20232722000.nc
magn20220622100.nc				      magn20232722015.nc
magn20220622115.nc				      magn20232722030.nc
magn20220622130.nc				      magn20232722045.nc
magn20220622145.nc				      magn20232722100.nc
magn20220622200.nc				      magn20232722115.nc
magn20220622215.nc				      magn20232722130.nc
magn20220622230.nc				      magn20232722145.nc
magn20220622245.nc				      magn20232722200.nc
magn20220622300.nc				      magn20232722215.nc
magn20220622315.nc				      magn20232722230.nc
magn20220622330.nc				      magn20232722245.nc
magn20220622345.nc				      magn20232722300.nc
magn2022062.npy					      magn20232722315.nc
magn20220630000.nc				      magn20232722330.nc
magn20220630015.nc				      magn20232722345.nc
magn20220630030.nc				      magn20232730000.nc
magn20220630045.nc				      magn20232730015.nc
magn20220630100.nc				      magn20232730030.nc
magn20220630115.nc				      magn20232730045.nc
magn20220630130.nc				      magn20232730100.nc
magn20220630145.nc				      magn20232730115.nc
magn20220630200.nc				      magn20232730130.nc
magn20220630215.nc				      magn20232730145.nc
magn20220630230.nc				      magn20232730200.nc
magn20220630245.nc				      magn20232730215.nc
magn20220630300.nc				      magn20232730230.nc
magn20220630315.nc				      magn20232730245.nc
magn20220630330.nc				      magn20232730300.nc
magn20220630345.nc				      magn20232730315.nc
magn20220630400.nc				      magn20232730330.nc
magn20220630415.nc				      magn20232730345.nc
magn20220630430.nc				      magn20232730400.nc
magn20220630445.nc				      magn20232730415.nc
magn20220630500.nc				      magn20232730430.nc
magn20220630515.nc				      magn20232730445.nc
magn20220630530.nc				      magn20232730500.nc
magn20220630545.nc				      magn20232730515.nc
magn20220630600.nc				      magn20232730530.nc
magn20220630615.nc				      magn20232730545.nc
magn20220630630.nc				      magn20232730600.nc
magn20220630645.nc				      magn20232730615.nc
magn20220630700.nc				      magn20232730630.nc
magn20220630715.nc				      magn20232730645.nc
magn20220630730.nc				      magn20232730700.nc
magn20220630745.nc				      magn20232730715.nc
magn20220630800.nc				      magn20232730730.nc
magn20220630815.nc				      magn20232730745.nc
magn20220630830.nc				      magn20232730800.nc
magn20220630845.nc				      magn20232730815.nc
magn20220630900.nc				      magn20232730830.nc
magn20220630915.nc				      magn20232730845.nc
magn20220630930.nc				      magn20232730900.nc
magn20220630945.nc				      magn20232730915.nc
magn20220631000.nc				      magn20232730930.nc
magn20220631015.nc				      magn20232730945.nc
magn20220631030.nc				      magn20232731000.nc
magn20220631045.nc				      magn20232731015.nc
magn20220631100.nc				      magn20232731030.nc
magn20220631115.nc				      magn20232731045.nc
magn20220631130.nc				      magn20232731100.nc
magn20220631145.nc				      magn20232731115.nc
magn20220631200.nc				      magn20232731130.nc
magn20220631215.nc				      magn20232731145.nc
magn20220631230.nc				      magn20232731200.nc
magn20220631245.nc				      magn20232731215.nc
magn20220631300.nc				      magn20232731230.nc
magn20220631315.nc				      magn20232731245.nc
magn20220631330.nc				      magn20232731300.nc
magn20220631345.nc				      magn20232731315.nc
magn20220631400.nc				      magn20232731330.nc
magn20220631415.nc				      magn20232731345.nc
magn20220631430.nc				      magn20232731400.nc
magn20220631445.nc				      magn20232731415.nc
magn20220631500.nc				      magn20232731430.nc
magn20220631515.nc				      magn20232731445.nc
magn20220631530.nc				      magn20232731500.nc
magn20220631545.nc				      magn20232731515.nc
magn20220631600.nc				      magn20232731530.nc
magn20220631615.nc				      magn20232731545.nc
magn20220631630.nc				      magn20232731600.nc
magn20220631645.nc				      magn20232731615.nc
magn20220631700.nc				      magn20232731630.nc
magn20220631715.nc				      magn20232731645.nc
magn20220631730.nc				      magn20232731700.nc
magn20220631745.nc				      magn20232731715.nc
magn20220631800.nc				      magn20232731730.nc
magn20220631815.nc				      magn20232731745.nc
magn20220631830.nc				      magn20232731800.nc
magn20220631845.nc				      magn20232731815.nc
magn20220631900.nc				      magn20232731830.nc
magn20220631915.nc				      magn20232731845.nc
magn20220631930.nc				      magn20232731900.nc
magn20220631945.nc				      magn20232731915.nc
magn20220632000.nc				      magn20232731930.nc
magn20220632015.nc				      magn20232731945.nc
magn20220632030.nc				      magn20232732000.nc
magn20220632045.nc				      magn20232732015.nc
magn20220632100.nc				      magn20232732030.nc
magn20220632115.nc				      magn20232732045.nc
magn20220632130.nc				      magn20232732100.nc
magn20220632145.nc				      magn20232732115.nc
magn20220632200.nc				      magn20232732130.nc
magn20220632215.nc				      magn20232732145.nc
magn20220632230.nc				      magn20232732200.nc
magn20220632245.nc				      magn20232732215.nc
magn20220632300.nc				      magn20232732230.nc
magn20220632315.nc				      magn20232732245.nc
magn20220632330.nc				      magn20232732300.nc
magn20220632345.nc				      magn20232732315.nc
magn2022063.npy					      magn20232732330.nc
magn20220640000.nc				      magn20232732345.nc
magn20220640015.nc				      magn20233350000.nc
magn20220640030.nc				      magn20233350015.nc
magn20220640045.nc				      magn20233350030.nc
magn20220640100.nc				      magn20233350045.nc
magn20220640115.nc				      magn20233350100.nc
magn20220640130.nc				      magn20233350115.nc
magn20220640145.nc				      magn20233350130.nc
magn20220640200.nc				      magn20233350145.nc
magn20220640215.nc				      magn20233350200.nc
magn20220640230.nc				      magn20233350215.nc
magn20220640245.nc				      magn20233350230.nc
magn20220640300.nc				      magn20233350245.nc
magn20220640315.nc				      magn20233350300.nc
magn20220640330.nc				      magn20233350315.nc
magn20220640345.nc				      magn20233350330.nc
magn20220640400.nc				      magn20233350345.nc
magn20220640415.nc				      magn20233350400.nc
magn20220640430.nc				      magn20233350415.nc
magn20220640445.nc				      magn20233350430.nc
magn20220640500.nc				      magn20233350445.nc
magn20220640515.nc				      magn20233350500.nc
magn20220640530.nc				      magn20233350515.nc
magn20220640545.nc				      magn20233350530.nc
magn20220640600.nc				      magn20233350545.nc
magn20220640615.nc				      magn20233350600.nc
magn20220640630.nc				      magn20233350615.nc
magn20220640645.nc				      magn20233350630.nc
magn20220640700.nc				      magn20233350645.nc
magn20220640715.nc				      magn20233350700.nc
magn20220640730.nc				      magn20233350715.nc
magn20220640745.nc				      magn20233350730.nc
magn20220640800.nc				      magn20233350745.nc

In [28]:
%pwd

'/content'

In [29]:
!ls *.npy

MAGGIA_TEC_maps_intersection_2022.npy  magn2022262.npy	magn2024165.npy
MAGGIA_TEC_maps_intersection_2024.npy  magn2022264.npy	magn2024166.npy
magn2022060.npy			       magn2022265.npy	magn2024167.npy
magn2022061.npy			       magn2022266.npy	magn2024168.npy
magn2022062.npy			       magn2022267.npy	magn2024169.npy
magn2022063.npy			       magn2022268.npy	magn2024170.npy
magn2022064.npy			       magn2022269.npy	magn2024171.npy
magn2022065.npy			       magn2022270.npy	magn2024173.npy
magn2022066.npy			       magn2022271.npy	magn2024174.npy
magn2022067.npy			       magn2022272.npy	magn2024175.npy
magn2022069.npy			       magn2022273.npy	magn2024176.npy
magn2022070.npy			       magn2022338.npy	magn2024177.npy
magn2022071.npy			       magn2022339.npy	magn2024180.npy
magn2022073.npy			       magn2022340.npy	magn2024181.npy
magn2022074.npy			       magn2022348.npy	magn2024247.npy
magn2022075.npy			       magn2022349.npy	magn2024248.npy
magn2022076.npy			       magn2022350.npy	magn2024249.npy
magn2022077.npy			       magn2022351.npy	magn2024250.npy
magn2022078.npy			       magn2022352.npy	magn2024251.npy
magn2022079.npy			       magn2022353.npy	magn2024252.npy
magn2022080.npy			       magn2022354.npy	magn2024253.npy
magn2022081.npy			       magn2022356.npy	magn2024254.npy
magn2022082.npy			       magn2022357.npy	magn2024255.npy
magn2022083.npy			       magn2022358.npy	magn2024256.npy
magn2022084.npy			       magn2022359.npy	magn2024257.npy
magn2022085.npy			       magn2022360.npy	magn2024258.npy
magn2022086.npy			       magn2022362.npy	magn2024261.npy
magn2022090.npy			       magn2022363.npy	magn2024262.npy
magn2022152.npy			       magn2022364.npy	magn2024263.npy
magn2022153.npy			       magn2022365.npy	magn2024264.npy
magn2022154.npy			       magn2024061.npy	magn2024265.npy
magn2022156.npy			       magn2024062.npy	magn2024266.npy
magn2022157.npy			       magn2024063.npy	magn2024267.npy
magn2022158.npy			       magn2024064.npy	magn2024268.npy
magn2022159.npy			       magn2024065.npy	magn2024269.npy
magn2022160.npy			       magn2024066.npy	magn2024270.npy
magn2022161.npy			       magn2024067.npy	magn2024271.npy
magn2022162.npy			       magn2024068.npy	magn2024272.npy
magn2022163.npy			       magn2024069.npy	magn2024274.npy
magn2022164.npy			       magn2024070.npy	magn2024336.npy
magn2022165.npy			       magn2024071.npy	magn2024337.npy
magn2022166.npy			       magn2024072.npy	magn2024338.npy
magn2022167.npy			       magn2024073.npy	magn2024339.npy
magn2022168.npy			       magn2024074.npy	magn2024340.npy
magn2022169.npy			       magn2024075.npy	magn2024341.npy
magn2022170.npy			       magn2024076.npy	magn2024342.npy
magn2022171.npy			       magn2024077.npy	magn2024343.npy
magn2022172.npy			       magn2024078.npy	magn2024344.npy
magn2022173.npy			       magn2024079.npy	magn2024345.npy
magn2022174.npy			       magn2024080.npy	magn2024346.npy
magn2022176.npy			       magn2024081.npy	magn2024347.npy
magn2022178.npy			       magn2024086.npy	magn2024349.npy
magn2022181.npy			       magn2024087.npy	magn2024350.npy
magn2022245.npy			       magn2024088.npy	magn2024351.npy
magn2022246.npy			       magn2024089.npy	magn2024352.npy
magn2022247.npy			       magn2024091.npy	magn2024353.npy
magn2022248.npy			       magn2024153.npy	magn2024354.npy
magn2022249.npy			       magn2024154.npy	magn2024355.npy
magn2022250.npy			       magn2024155.npy	magn2024356.npy
magn2022251.npy			       magn2024156.npy	magn2024357.npy
magn2022252.npy			       magn2024157.npy	magn2024358.npy
magn2022253.npy			       magn2024158.npy	magn2024359.npy
magn2022254.npy			       magn2024159.npy	magn2024360.npy
magn2022255.npy			       magn2024160.npy	magn2024361.npy
magn2022256.npy			       magn2024161.npy	magn2024362.npy
magn2022258.npy			       magn2024162.npy	magn2024363.npy
magn2022260.npy			       magn2024163.npy	magn2024364.npy
magn2022261.npy			       magn2024164.npy	magn2024365.npy

In [30]:
maggia_2022 = np.load('MAGGIA_TEC_maps_intersection_2022.npy')
print(np.shape(maggia_2022))
print(type(maggia_2022))
print(type(maggia_2022[0]))
print(type(maggia_2022[0][0]))
print(type(maggia_2022[0][0][0]))

(9216, 241, 221)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float32'>

In [31]:
for i in range(len(maggia_2022)):
    print(np.shape(maggia_2022[i]))

(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)

In [32]:
np.shape(maggia_2022)

(9216, 241, 221)

In [33]:
has_nan = np.any(np.isnan(maggia_2022))
print(has_nan)

count_nan = np.sum(np.isnan(maggia_2022))
print(count_nan)

True
174265624

In [34]:
maggia_2022.shape

(9216, 241, 221)

In [35]:
np.set_printoptions(threshold=np.inf)

In [36]:
print(maggia_2022[0][0])

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan]

In [37]:
print(maggia_2022[0][-1])

[17.788412  17.755325  17.722652  17.688313  17.65265   17.620007
 17.595892  17.567413  17.543629  17.529224  17.512714  17.505653
 17.497473  17.497871  17.502499  17.512209  17.538767  17.567375
 17.608377  17.65319   17.699726  17.754261  17.823154  17.905228
 17.993402  18.087454  18.190685  18.302395  18.418121  18.534784
 18.649996  18.760876  18.875555  18.991348  19.097591  19.191473
 19.285069  19.371471  19.441626  19.498102  19.5466    19.575624
 19.591415  19.594072  19.58052   19.552345  19.514132  19.460115
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan  6.272935   6.167357   6.07331    5.9888716
  5.9169974  5.8587465  5.805675   5.7617235  5.725774   5.69344
  5.6691923  5.650965   5.6421976  5.641234   5.6456914  5.6588206
  5.6733527  5.688813   5.7115803  5.7386694  5.7713456  5.802364
  5.8391356  5.868101   5.902417   5.9336863  5.9615483  5.9856653
  6.0042753  6.017166   6.018556   6.0046835  5.9804816  5.9534926
  5.923062   5.887342   5.855355   5.8265696  5.8014817  5.777944
  5.752498   5.7316694  5.7048287  5.663376   5.612887   5.555109
  5.490942   5.4350805  5.3731203  5.3110223  5.248967   5.1935964
  5.1402826  5.087833   5.03549    4.980712   4.933908   4.892386
  4.857563   4.839126   4.8308597  4.8355165  4.860312   4.9062667
  4.976785   5.064345   5.162408   5.2694855  5.3853726  5.508376
  5.6250057  5.7406054  5.8532104  5.959636   6.060919   6.158811
  6.2444234  6.3194375  6.391023   6.4519305  6.502574   6.5471797
  6.584042   6.6210318  6.654288   6.6860747  6.7206225  6.7545805
  6.7814517  6.808754   6.8351336  6.8497343  6.864002   6.859804
  6.8422184  6.819226   6.782894   6.743345   6.695823   6.654055
  6.6050386  6.5572615  6.5085545  6.4565167  6.4030313  6.3510137
  6.3050447  6.252793   6.198543   6.14579    6.08814  ]

In [38]:
# del maggia_2022

In [39]:
maggia_2024 = np.load('MAGGIA_TEC_maps_intersection_2024.npy')
print(np.shape(maggia_2024))
print(type(maggia_2024))
print(type(maggia_2024[0]))
print(type(maggia_2024[0][0]))
print(type(maggia_2024[0][0][0]))

(12744, 241, 221)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float32'>

In [40]:
for i in range(len(maggia_2024)):
    print(np.shape(maggia_2024[i]))

(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)

In [41]:
np.shape(maggia_2024)

(12744, 241, 221)

In [42]:
has_nan = np.any(np.isnan(maggia_2024))
print(has_nan)

count_nan = np.sum(np.isnan(maggia_2024))
print(count_nan)

True
297383688

In [43]:
maggia_2024.shape

(12744, 241, 221)

In [44]:
np.set_printoptions(threshold=np.inf)

In [45]:
print(maggia_2024[0][0])

[      nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan 29.192455 29.162899 29.132933 29.102135 29.070847
 29.039406 29.008446 28.977596 28.947266 28.916576 28.8842   28.851604
 28.819979 28.78832  28.754368 28.720201 28.685879 28.651617 28.616816
 28.584135 28.54804  28.512815 28.476841 28.440676 28.403246 28.364563
 28.32641  28.288506 28.249765 28.213276 28.174604       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan       nan       nan       nan
       nan       nan       nan       nan]

In [46]:
print(maggia_2024[0][-1])

[39.41671   39.26682   39.108894  38.944115  38.763126  38.577763
 38.379105  38.17472   37.952423  37.721645  37.48399   37.24049
 37.002926  36.763454  36.525036  36.292767  36.06174   35.837265
 35.622192  35.40941   35.213593  35.01287   34.8202    34.637413
 34.44743   34.272167  34.10503   33.936024  33.77426   33.621197
 33.46703   33.323605  33.186466  33.04637   32.903618  32.768536
 32.631     32.492046  32.344532  32.19713   32.04554   31.892933
 31.740366  31.577015  31.410427  31.239164  31.062418  30.883389
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 22.815914  22.65648   22.495527  22.339163
 22.177057  22.019379  21.863499  21.703812  21.545238  21.3882
 21.231382  21.07831   20.922361  20.775478  20.632233  20.490072
 20.352089  20.209478  20.067507  19.932552  19.799673  19.669903
 19.550774  19.434483  19.317709  19.214039  19.116333  19.030916
 18.949978  18.88594   18.842342  18.816303  18.80616   18.804588
 18.813896  18.825289  18.840696  18.84559   18.853323  18.849377
 18.829464  18.793144  18.747004  18.666054  18.560389  18.423819
 18.258684  18.071386  17.859898  17.616058  17.348034  17.064474
 16.777817  16.488132  16.204863  15.944     15.6986065 15.488248
 15.3090925 15.159129  15.033734  14.927806  14.839627  14.7602415
 14.698163  14.637272  14.566312  14.491881  14.410303  14.324071
 14.237111  14.149386  14.063714  13.975605  13.887213  13.798266
 13.710201  13.616528  13.519538  13.41449   13.294507  13.170159
 13.035303  12.883701  12.716102  12.544497  12.353538  12.162686
 11.954899  11.738129  11.518681  11.291116  11.057593  10.839096
 10.629432  10.427698  10.243308  10.062324   9.908908   9.777698
  9.668222   9.582537   9.523565   9.487051   9.465083   9.465396
  9.481291   9.502026   9.524135   9.548085   9.574838 ]

In [47]:
# del maggia_2024

In [48]:
maggia_2022_2024 = np.concatenate([maggia_2022, maggia_2024], axis=0)
print(maggia_2022_2024.shape)

(21960, 241, 221)

In [49]:
print(type(maggia_2022_2024))
print(type(maggia_2022_2024[0]))
print(type(maggia_2022_2024[0][0]))
print(type(maggia_2022_2024[0][0][0]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float32'>

In [50]:
for i in range(len(maggia_2022_2024)):
    print(np.shape(maggia_2022_2024[i]))

(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)
(241, 221)

In [51]:
np.shape(maggia_2022_2024)

(21960, 241, 221)

In [52]:
has_nan = np.any(np.isnan(maggia_2022_2024))
print(has_nan)

count_nan = np.sum(np.isnan(maggia_2022_2024))
print(count_nan)

True
471649312

In [53]:
np.set_printoptions(threshold=np.inf)

In [54]:
print(maggia_2022_2024[0][0])

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan]

In [55]:
print(maggia_2022_2024[0][-1])

[17.788412  17.755325  17.722652  17.688313  17.65265   17.620007
 17.595892  17.567413  17.543629  17.529224  17.512714  17.505653
 17.497473  17.497871  17.502499  17.512209  17.538767  17.567375
 17.608377  17.65319   17.699726  17.754261  17.823154  17.905228
 17.993402  18.087454  18.190685  18.302395  18.418121  18.534784
 18.649996  18.760876  18.875555  18.991348  19.097591  19.191473
 19.285069  19.371471  19.441626  19.498102  19.5466    19.575624
 19.591415  19.594072  19.58052   19.552345  19.514132  19.460115
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan  6.272935   6.167357   6.07331    5.9888716
  5.9169974  5.8587465  5.805675   5.7617235  5.725774   5.69344
  5.6691923  5.650965   5.6421976  5.641234   5.6456914  5.6588206
  5.6733527  5.688813   5.7115803  5.7386694  5.7713456  5.802364
  5.8391356  5.868101   5.902417   5.9336863  5.9615483  5.9856653
  6.0042753  6.017166   6.018556   6.0046835  5.9804816  5.9534926
  5.923062   5.887342   5.855355   5.8265696  5.8014817  5.777944
  5.752498   5.7316694  5.7048287  5.663376   5.612887   5.555109
  5.490942   5.4350805  5.3731203  5.3110223  5.248967   5.1935964
  5.1402826  5.087833   5.03549    4.980712   4.933908   4.892386
  4.857563   4.839126   4.8308597  4.8355165  4.860312   4.9062667
  4.976785   5.064345   5.162408   5.2694855  5.3853726  5.508376
  5.6250057  5.7406054  5.8532104  5.959636   6.060919   6.158811
  6.2444234  6.3194375  6.391023   6.4519305  6.502574   6.5471797
  6.584042   6.6210318  6.654288   6.6860747  6.7206225  6.7545805
  6.7814517  6.808754   6.8351336  6.8497343  6.864002   6.859804
  6.8422184  6.819226   6.782894   6.743345   6.695823   6.654055
  6.6050386  6.5572615  6.5085545  6.4565167  6.4030313  6.3510137
  6.3050447  6.252793   6.198543   6.14579    6.08814  ]

# Dates adjusts

In [56]:
import numpy as np
from datetime import datetime, timedelta

def doy_to_date(year, doy):
    return datetime(year, 1, 1) + timedelta(days=doy - 1)

doys = {
    2022: {
        3: [60, 61, 62, 63, 64, 65, 66, 67, 69, 70,
            71, 73, 74, 75, 76, 77, 78, 79, 80, 81,
            82, 83, 84, 85, 86, 90],
        6: [152, 153, 154, 156, 157, 158, 159, 160,
            161, 162, 163, 164, 165, 166, 167, 168,
            169, 170, 171, 172, 173, 174, 176, 178,
            181],
        9: [245, 246, 247, 248, 249, 250, 251, 252,
            253, 254, 255, 256, 258, 260, 261, 262,
            264, 265, 266, 267, 268, 269, 270, 271,
            272, 273],
        12: [338, 339, 340, 348, 349, 350, 351, 352,
             353, 354, 356, 357, 358, 359, 360, 362,
             363, 364, 365]
    },
    2024: {
        3: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
            71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
            81, 86, 87, 88, 89, 91],
        6: [153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
            163, 164, 165, 166, 167, 168, 169, 170, 171, 173,
            174, 175, 176, 177, 180, 181],
        9: [247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
            257, 258, 261, 262, 263, 264, 265, 266, 267, 268,
            269, 270, 271, 272, 274],
        12: [336, 337, 338, 339, 340, 341, 342, 343, 344, 345,
             346, 347, 349, 350, 351, 352, 353, 354, 355,
             356, 357, 358, 359, 360, 361, 362, 363, 364, 365]
    }
}

doy249_times = [
    "0000", "0010", "0015", "0020", "0030", "0040", "0045", "0050",
    "0100", "0110", "0115", "0120", "0130", "0140", "0145", "0150",
    "0200", "0210", "0215", "0220", "0230", "0240", "0245", "0250",
    "0300", "0310", "0315", "0320", "0330", "0340", "0345", "0350",
    "0400", "0410", "0415", "0420", "0430", "0440", "0445", "0450",
    "0500", "0510", "0515", "0520", "0530", "0540", "0545", "0550",
    "0600", "0610", "0615", "0620", "0630", "0640", "0645", "0650",
    "0700", "0710", "0715", "0720", "0730", "0740", "0745", "0750",
    "0800", "0810", "0815", "0820", "0830", "0840", "0845", "0850",
    "0900", "0910", "0915", "0920", "0930", "0940", "0945", "0950",
    "1000", "1010", "1015", "1020", "1030", "1040", "1045", "1050",
    "1100", "1110", "1115", "1120", "1130", "1140", "1145", "1150",
    "1200", "1210", "1215", "1220", "1230", "1240", "1245", "1250",
    "1300", "1310", "1315", "1320", "1330", "1340", "1345", "1350",
    "1400", "1410", "1415", "1420", "1430", "1440", "1445", "1450",
    "1500", "1510", "1515", "1520", "1530", "1540", "1545", "1550",
    "1600", "1610", "1615", "1620", "1630", "1640", "1645", "1650",
    "1700", "1710", "1715", "1720", "1730", "1740", "1745", "1750",
    "1800", "1810", "1815", "1820", "1830", "1840", "1845", "1850",
    "1900", "1910", "1915", "1920", "1930", "1940", "1945", "1950",
    "2000", "2010", "2015", "2020", "2030", "2040", "2045", "2050",
    "2100", "2110", "2115", "2120", "2130", "2140", "2145", "2150",
    "2200", "2210", "2215", "2220", "2230", "2240", "2245", "2250",
    "2300", "2310", "2315", "2320", "2330", "2340", "2345", "2350"
]

doy250_times = [
    "0000", "0010", "0015", "0020", "0030", "0040", "0045", "0050",
    "0100", "0110", "0115", "0120", "0130", "0140", "0145", "0150",
    "0200", "0210", "0215", "0220", "0230", "0240", "0245", "0250",
    "0300", "0310", "0315", "0320", "0330", "0340", "0345", "0350",
    "0400", "0410", "0415", "0420", "0430", "0440", "0445", "0450",
    "0500", "0510", "0515", "0520", "0530", "0540", "0545", "0550",
    "0600", "0610", "0615", "0620", "0630", "0640", "0645", "0650",
    "0700", "0710", "0715", "0720", "0730", "0740", "0745", "0750",
    "0800", "0810", "0815", "0820", "0830", "0840", "0845", "0850",
    "0900", "0910", "0915", "0920", "0930", "0940", "0945", "0950",
    "1000", "1010", "1015", "1020", "1030", "1040", "1045", "1050",
    "1100", "1110", "1115", "1120", "1130", "1140", "1145", "1150",
    "1200", "1210", "1220", "1230", "1240", "1250", "1300", "1310",
    "1320", "1330", "1340", "1350", "1400", "1410", "1420", "1430",
    "1440", "1450", "1500", "1510", "1520", "1530", "1540", "1550",
    "1600", "1610", "1620", "1630", "1640", "1650", "1700", "1710",
    "1720", "1730", "1740", "1750", "1800", "1810", "1820", "1830",
    "1840", "1850", "1900", "1910", "1920", "1930", "1940", "1950",
    "2000", "2010", "2020", "2030", "2040", "2050", "2100", "2110",
    "2120", "2130", "2140", "2150", "2200", "2210", "2220", "2230",
    "2240", "2250", "2300", "2310", "2320", "2330", "2340", "2350"
]

datetime_list = []

for year in doys.keys():
    for month in doys[year].keys():
        for doy in doys[year][month]:
            base_date = doy_to_date(year, doy)

            if year == 2024 and doy == 249:
                for time_str in doy249_times:
                    hours = int(time_str[:2])
                    minutes = int(time_str[2:])
                    dt = base_date + timedelta(hours=hours, minutes=minutes)
                    datetime_list.append(dt)

            elif year == 2024 and doy == 250:
                for time_str in doy250_times:
                    hours = int(time_str[:2])
                    minutes = int(time_str[2:])
                    dt = base_date + timedelta(hours=hours, minutes=minutes)
                    datetime_list.append(dt)

            elif year == 2024 and doy >= 251:
                for minute in range(0, 24 * 60, 10):
                    dt = base_date + timedelta(minutes=minute)
                    datetime_list.append(dt)

            else:
                for minute in range(0, 24 * 60, 15):
                    dt = base_date + timedelta(minutes=minute)
                    datetime_list.append(dt)

maggia_datetimes_2022_2024 = np.array(datetime_list, dtype='datetime64[s]')

print(f"Total number of datetime points: {len(maggia_datetimes_2022_2024)}")
print(f"First datetime: {maggia_datetimes_2022_2024[0]}")
print(f"Last datetime: {maggia_datetimes_2022_2024[-1]}")

print("\nSample of first 10 datetime entries:")
for dt in maggia_datetimes_2022_2024[:10]:
    print(dt)

print("\nSample of last 10 datetime entries:")
for dt in maggia_datetimes_2022_2024[-10:]:
    print(dt)

Total number of datetime points: 21960
First datetime: 2022-03-01T00:00:00
Last datetime: 2024-12-30T23:50:00

Sample of first 10 datetime entries:
2022-03-01T00:00:00
2022-03-01T00:15:00
2022-03-01T00:30:00
2022-03-01T00:45:00
2022-03-01T01:00:00
2022-03-01T01:15:00
2022-03-01T01:30:00
2022-03-01T01:45:00
2022-03-01T02:00:00
2022-03-01T02:15:00

Sample of last 10 datetime entries:
2024-12-30T22:20:00
2024-12-30T22:30:00
2024-12-30T22:40:00
2024-12-30T22:50:00
2024-12-30T23:00:00
2024-12-30T23:10:00
2024-12-30T23:20:00
2024-12-30T23:30:00
2024-12-30T23:40:00
2024-12-30T23:50:00

In [57]:
maggia_datetimes_2022_2024.shape

(21960,)

In [58]:
maggia_datetimes_2022_2024

array(['2022-03-01T00:00:00', '2022-03-01T00:15:00',
       '2022-03-01T00:30:00', '2022-03-01T00:45:00',
       '2022-03-01T01:00:00', '2022-03-01T01:15:00',
       '2022-03-01T01:30:00', '2022-03-01T01:45:00',
       '2022-03-01T02:00:00', '2022-03-01T02:15:00',
       '2022-03-01T02:30:00', '2022-03-01T02:45:00',
       '2022-03-01T03:00:00', '2022-03-01T03:15:00',
       '2022-03-01T03:30:00', '2022-03-01T03:45:00',
       '2022-03-01T04:00:00', '2022-03-01T04:15:00',
       '2022-03-01T04:30:00', '2022-03-01T04:45:00',
       '2022-03-01T05:00:00', '2022-03-01T05:15:00',
       '2022-03-01T05:30:00', '2022-03-01T05:45:00',
       '2022-03-01T06:00:00', '2022-03-01T06:15:00',
       '2022-03-01T06:30:00', '2022-03-01T06:45:00',
       '2022-03-01T07:00:00', '2022-03-01T07:15:00',
       '2022-03-01T07:30:00', '2022-03-01T07:45:00',
       '2022-03-01T08:00:00', '2022-03-01T08:15:00',
       '2022-03-01T08:30:00', '2022-03-01T08:45:00',
       '2022-03-01T09:00:00', '2022-03-01T09:15:00',
       '2022-03-01T09:30:00', '2022-03-01T09:45:00',
       '2022-03-01T10:00:00', '2022-03-01T10:15:00',
       '2022-03-01T10:30:00', '2022-03-01T10:45:00',
       '2022-03-01T11:00:00', '2022-03-01T11:15:00',
       '2022-03-01T11:30:00', '2022-03-01T11:45:00',
       '2022-03-01T12:00:00', '2022-03-01T12:15:00',
       '2022-03-01T12:30:00', '2022-03-01T12:45:00',
       '2022-03-01T13:00:00', '2022-03-01T13:15:00',
       '2022-03-01T13:30:00', '2022-03-01T13:45:00',
       '2022-03-01T14:00:00', '2022-03-01T14:15:00',
       '2022-03-01T14:30:00', '2022-03-01T14:45:00',
       '2022-03-01T15:00:00', '2022-03-01T15:15:00',
       '2022-03-01T15:30:00', '2022-03-01T15:45:00',
       '2022-03-01T16:00:00', '2022-03-01T16:15:00',
       '2022-03-01T16:30:00', '2022-03-01T16:45:00',
       '2022-03-01T17:00:00', '2022-03-01T17:15:00',
       '2022-03-01T17:30:00', '2022-03-01T17:45:00',
       '2022-03-01T18:00:00', '2022-03-01T18:15:00',
       '2022-03-01T18:30:00', '2022-03-01T18:45:00',
       '2022-03-01T19:00:00', '2022-03-01T19:15:00',
       '2022-03-01T19:30:00', '2022-03-01T19:45:00',
       '2022-03-01T20:00:00', '2022-03-01T20:15:00',
       '2022-03-01T20:30:00', '2022-03-01T20:45:00',
       '2022-03-01T21:00:00', '2022-03-01T21:15:00',
       '2022-03-01T21:30:00', '2022-03-01T21:45:00',
       '2022-03-01T22:00:00', '2022-03-01T22:15:00',
       '2022-03-01T22:30:00', '2022-03-01T22:45:00',
       '2022-03-01T23:00:00', '2022-03-01T23:15:00',
       '2022-03-01T23:30:00', '2022-03-01T23:45:00',
       '2022-03-02T00:00:00', '2022-03-02T00:15:00',
       '2022-03-02T00:30:00', '2022-03-02T00:45:00',
       '2022-03-02T01:00:00', '2022-03-02T01:15:00',
       '2022-03-02T01:30:00', '2022-03-02T01:45:00',
       '2022-03-02T02:00:00', '2022-03-02T02:15:00',
       '2022-03-02T02:30:00', '2022-03-02T02:45:00',
       '2022-03-02T03:00:00', '2022-03-02T03:15:00',
       '2022-03-02T03:30:00', '2022-03-02T03:45:00',
       '2022-03-02T04:00:00', '2022-03-02T04:15:00',
       '2022-03-02T04:30:00', '2022-03-02T04:45:00',
       '2022-03-02T05:00:00', '2022-03-02T05:15:00',
       '2022-03-02T05:30:00', '2022-03-02T05:45:00',
       '2022-03-02T06:00:00', '2022-03-02T06:15:00',
       '2022-03-02T06:30:00', '2022-03-02T06:45:00',
       '2022-03-02T07:00:00', '2022-03-02T07:15:00',
       '2022-03-02T07:30:00', '2022-03-02T07:45:00',
       '2022-03-02T08:00:00', '2022-03-02T08:15:00',
       '2022-03-02T08:30:00', '2022-03-02T08:45:00',
       '2022-03-02T09:00:00', '2022-03-02T09:15:00',
       '2022-03-02T09:30:00', '2022-03-02T09:45:00',
       '2022-03-02T10:00:00', '2022-03-02T10:15:00',
       '2022-03-02T10:30:00', '2022-03-02T10:45:00',
       '2022-03-02T11:00:00', '2022-03-02T11:15:00',
       '2022-03-02T11:30:00', '2022-03-02T11:45:00',
       '2022-03-02T12:00:00', '2022-03-02T12:15:00',
       '2022-03-02T12:30:00', '2022-03-02T12:45:00',
       '2022-03-02T13:00:00', '2022-03-02T13:15:00',
       '2022-03-02T13:30:00', '2022-03-02T13:45:00',
       '2022-03-02T14:00:00', '2022-03-02T14:15:00',
       '2022-03-02T14:30:00', '2022-03-02T14:45:00',
       '2022-03-02T15:00:00', '2022-03-02T15:15:00',
       '2022-03-02T15:30:00', '2022-03-02T15:45:00',
       '2022-03-02T16:00:00', '2022-03-02T16:15:00',
       '2022-03-02T16:30:00', '2022-03-02T16:45:00',
       '2022-03-02T17:00:00', '2022-03-02T17:15:00',
       '2022-03-02T17:30:00', '2022-03-02T17:45:00',
       '2022-03-02T18:00:00', '2022-03-02T18:15:00',
       '2022-03-02T18:30:00', '2022-03-02T18:45:00',
       '2022-03-02T19:00:00', '2022-03-02T19:15:00',
       '2022-03-02T19:30:00', '2022-03-02T19:45:00',
       '2022-03-02T20:00:00', '2022-03-02T20:15:00',
       '2022-03-02T20:30:00', '2022-03-02T20:45:00',
       '2022-03-02T21:00:00', '2022-03-02T21:15:00',
       '2022-03-02T21:30:00', '2022-03-02T21:45:00',
       '2022-03-02T22:00:00', '2022-03-02T22:15:00',
       '2022-03-02T22:30:00', '2022-03-02T22:45:00',
       '2022-03-02T23:00:00', '2022-03-02T23:15:00',
       '2022-03-02T23:30:00', '2022-03-02T23:45:00',
       '2022-03-03T00:00:00', '2022-03-03T00:15:00',
       '2022-03-03T00:30:00', '2022-03-03T00:45:00',
       '2022-03-03T01:00:00', '2022-03-03T01:15:00',
       '2022-03-03T01:30:00', '2022-03-03T01:45:00',
       '2022-03-03T02:00:00', '2022-03-03T02:15:00',
       '2022-03-03T02:30:00', '2022-03-03T02:45:00',
       '2022-03-03T03:00:00', '2022-03-03T03:15:00',
       '2022-03-03T03:30:00', '2022-03-03T03:45:00',
       '2022-03-03T04:00:00', '2022-03-03T04:15:00',
       '2022-03-03T04:30:00', '2022-03-03T04:45:00',
       '2022-03-03T05:00:00', '2022-03-03T05:15:00',
       '2022-03-03T05:30:00', '2022-03-03T05:45:00',
       '2022-03-03T06:00:00', '2022-03-03T06:15:00',
       '2022-03-03T06:30:00', '2022-03-03T06:45:00',
       '2022-03-03T07:00:00', '2022-03-03T07:15:00',
       '2022-03-03T07:30:00', '2022-03-03T07:45:00',
       '2022-03-03T08:00:00', '2022-03-03T08:15:00',
       '2022-03-03T08:30:00', '2022-03-03T08:45:00',
       '2022-03-03T09:00:00', '2022-03-03T09:15:00',
       '2022-03-03T09:30:00', '2022-03-03T09:45:00',
       '2022-03-03T10:00:00', '2022-03-03T10:15:00',
       '2022-03-03T10:30:00', '2022-03-03T10:45:00',
       '2022-03-03T11:00:00', '2022-03-03T11:15:00',
       '2022-03-03T11:30:00', '2022-03-03T11:45:00',
       '2022-03-03T12:00:00', '2022-03-03T12:15:00',
       '2022-03-03T12:30:00', '2022-03-03T12:45:00',
       '2022-03-03T13:00:00', '2022-03-03T13:15:00',
       '2022-03-03T13:30:00', '2022-03-03T13:45:00',
       '2022-03-03T14:00:00', '2022-03-03T14:15:00',
       '2022-03-03T14:30:00', '2022-03-03T14:45:00',
       '2022-03-03T15:00:00', '2022-03-03T15:15:00',
       '2022-03-03T15:30:00', '2022-03-03T15:45:00',
       '2022-03-03T16:00:00', '2022-03-03T16:15:00',
       '2022-03-03T16:30:00', '2022-03-03T16:45:00',
       '2022-03-03T17:00:00', '2022-03-03T17:15:00',
       '2022-03-03T17:30:00', '2022-03-03T17:45:00',
       '2022-03-03T18:00:00', '2022-03-03T18:15:00',
       '2022-03-03T18:30:00', '2022-03-03T18:45:00',
       '2022-03-03T19:00:00', '2022-03-03T19:15:00',
       '2022-03-03T19:30:00', '2022-03-03T19:45:00',
       '2022-03-03T20:00:00', '2022-03-03T20:15:00',
       '2022-03-03T20:30:00', '2022-03-03T20:45:00',
       '2022-03-03T21:00:00', '2022-03-03T21:15:00',
       '2022-03-03T21:30:00', '2022-03-03T21:45:00',
       '2022-03-03T22:00:00', '2022-03-03T22:15:00',
       '2022-03-03T22:30:00', '2022-03-03T22:45:00',
       '2022-03-03T23:00:00', '2022-03-03T23:15:00',
       '2022-03-03T23:30:00', '2022-03-03T23:45:00',
       '2022-03-04T00:00:00', '2022-03-04T00:15:00',
       '2022-03-04T00:30:00', '2022-03-04T00:45:00',
       '2022-03-04T01:00:00', '2022-03-04T01:15:00',
       '2022-03-04T01:30:00', '2022-03-04T01:45:00',
       '2022-03-04T02:00:00', '2022-03-04T02:15:00',
       '2022-03-04T02:30:00', '2022-03-04T02:45:00',
       '2022-03-04T03:00:00', '2022-03-04T03:15:00',
       '2022-03-04T03:30:00', '2022-03-04T03:45:00',
       '2022-03-04T04:00:00', '2022-03-04T04:15:00',
       '2022-03-04T04:30:00', '2022-03-04T04:45:00',
       '2022-03-04T05:00:00', '2022-03-04T05:15:00',
       '2022-03-04T05:30:00', '2022-03-04T05:45:00',
       '2022-03-04T06:00:00', '2022-03-04T06:15:00',
       '2022-03-04T06:30:00', '2022-03-04T06:45:00',
       '2022-03-04T07:00:00', '2022-03-04T07:15:00',
       '2022-03-04T07:30:00', '2022-03-04T07:45:00',
       '2022-03-04T08:00:00', '2022-03-04T08:15:00',
       '2022-03-04T08:30:00', '2022-03-04T08:45:00',
       '2022-03-04T09:00:00', '2022-03-04T09:15:00',
       '2022-03-04T09:30:00', '2022-03-04T09:45:00',
       '2022-03-04T10:00:00', '2022-03-04T10:15:00',
       '2022-03-04T10:30:00', '2022-03-04T10:45:00',
       '2022-03-04T11:00:00', '2022-03-04T11:15:00',
       '2022-03-04T11:30:00', '2022-03-04T11:45:00',
       '2022-03-04T12:00:00', '2022-03-04T12:15:00',
       '2022-03-04T12:30:00', '2022-03-04T12:45:00',
       '2022-03-04T13:00:00', '2022-03-04T13:15:00',
       '2022-03-04T13:30:00', '2022-03-04T13:45:00',
       '2022-03-04T14:00:00', '2022-03-04T14:15:00',
       '2022-03-04T14:30:00', '2022-03-04T14:45:00',
       '2022-03-04T15:00:00', '2022-03-04T15:15:00',
       '2022-03-04T15:30:00', '2022-03-04T15:45:00',
       '2022-03-04T16:00:00', '2022-03-04T16:15:00',
       '2022-03-04T16:30:00', '2022-03-04T16:45:00',
       '2022-03-04T17:00:00', '2022-03-04T17:15:00',
       '2022-03-04T17:30:00', '2022-03-04T17:45:00',
       '2022-03-04T18:00:00', '2022-03-04T18:15:00',
       '2022-03-04T18:30:00', '2022-03-04T18:45:00',
       '2022-03-04T19:00:00', '2022-03-04T19:15:00',
       '2022-03-04T19:30:00', '2022-03-04T19:45:00',
       '2022-03-04T20:00:00', '2022-03-04T20:15:00',
       '2022-03-04T20:30:00', '2022-03-04T20:45:00',
       '2022-03-04T21:00:00', '2022-03-04T21:15:00',
       '2022-03-04T21:30:00', '2022-03-04T21:45:00',
       '2022-03-04T22:00:00', '2022-03-04T22:15:00',
       '2022-03-04T22:30:00', '2022-03-04T22:45:00',
       '2022-03-04T23:00:00', '2022-03-04T23:15:00',
       '2022-03-04T23:30:00', '2022-03-04T23:45:00',
       '2022-03-05T00:00:00', '2022-03-05T00:15:00',
       '2022-03-05T00:30:00', '2022-03-05T00:45:00',
       '2022-03-05T01:00:00', '2022-03-05T01:15:00',
       '2022-03-05T01:30:00', '2022-03-05T01:45:00',
       '2022-03-05T02:00:00', '2022-03-05T02:15:00',
       '2022-03-05T02:30:00', '2022-03-05T02:45:00',
       '2022-03-05T03:00:00', '2022-03-05T03:15:00',
       '2022-03-05T03:30:00', '2022-03-05T03:45:00',
       '2022-03-05T04:00:00', '2022-03-05T04:15:00',
       '2022-03-05T04:30:00', '2022-03-05T04:45:00',
       '2022-03-05T05:00:00', '2022-03-05T05:15:00',
       '2022-03-05T05:30:00', '2022-03-05T05:45:00',
       '2022-03-05T06:00:00', '2022-03-05T06:15:00',
       '2022-03-05T06:30:00', '2022-03-05T06:45:00',
       '2022-03-05T07:00:00', '2022-03-05T07:15:00',
       '2022-03-05T07:30:00', '2022-03-05T07:45:00',
       '2022-03-05T08:00:00', '2022-03-05T08:15:00',
       '2022-03-05T08:30:00', '2022-03-05T08:45:00',
       '2022-03-05T09:00:00', '2022-03-05T09:15:00',
       '2022-03-05T09:30:00', '2022-03-05T09:45:00',
       '2022-03-05T10:00:00', '2022-03-05T10:15:00',
       '2022-03-05T10:30:00', '2022-03-05T10:45:00',
       '2022-03-05T11:00:00', '2022-03-05T11:15:00',
       '2022-03-05T11:30:00', '2022-03-05T11:45:00',
       '2022-03-05T12:00:00', '2022-03-05T12:15:00',
       '2022-03-05T12:30:00', '2022-03-05T12:45:00',
       '2022-03-05T13:00:00', '2022-03-05T13:15:00',
       '2022-03-05T13:30:00', '2022-03-05T13:45:00',
       '2022-03-05T14:00:00', '2022-03-05T14:15:00',
       '2022-03-05T14:30:00', '2022-03-05T14:45:00',
       '2022-03-05T15:00:00', '2022-03-05T15:15:00',
       '2022-03-05T15:30:00', '2022-03-05T15:45:00',
       '2022-03-05T16:00:00', '2022-03-05T16:15:00',
       '2022-03-05T16:30:00', '2022-03-05T16:45:00',
       '2022-03-05T17:00:00', '2022-03-05T17:15:00',
       '2022-03-05T17:30:00', '2022-03-05T17:45:00',
       '2022-03-05T18:00:00', '2022-03-05T18:15:00',
       '2022-03-05T18:30:00', '2022-03-05T18:45:00',
       '2022-03-05T19:00:00', '2022-03-05T19:15:00',
       '2022-03-05T19:30:00', '2022-03-05T19:45:00',
       '2022-03-05T20:00:00', '2022-03-05T20:15:00',
       '2022-03-05T20:30:00', '2022-03-05T20:45:00',
       '2022-03-05T21:00:00', '2022-03-05T21:15:00',
       '2022-03-05T21:30:00', '2022-03-05T21:45:00',
       '2022-03-05T22:00:00', '2022-03-05T22:15:00',
       '2022-03-05T22:30:00', '2022-03-05T22:45:00',
       '2022-03-05T23:00:00', '2022-03-05T23:15:00',
       '2022-03-05T23:30:00', '2022-03-05T23:45:00',
       '2022-03-06T00:00:00', '2022-03-06T00:15:00',
       '2022-03-06T00:30:00', '2022-03-06T00:45:00',
       '2022-03-06T01:00:00', '2022-03-06T01:15:00',
       '2022-03-06T01:30:00', '2022-03-06T01:45:00',
       '2022-03-06T02:00:00', '2022-03-06T02:15:00',
       '2022-03-06T02:30:00', '2022-03-06T02:45:00',
       '2022-03-06T03:00:00', '2022-03-06T03:15:00',
       '2022-03-06T03:30:00', '2022-03-06T03:45:00',
       '2022-03-06T04:00:00', '2022-03-06T04:15:00',
       '2022-03-06T04:30:00', '2022-03-06T04:45:00',
       '2022-03-06T05:00:00', '2022-03-06T05:15:00',
       '2022-03-06T05:30:00', '2022-03-06T05:45:00',
       '2022-03-06T06:00:00', '2022-03-06T06:15:00',
       '2022-03-06T06:30:00', '2022-03-06T06:45:00',
       '2022-03-06T07:00:00', '2022-03-06T07:15:00',
       '2022-03-06T07:30:00', '2022-03-06T07:45:00',
       '2022-03-06T08:00:00', '2022-03-06T08:15:00',
       '2022-03-06T08:30:00', '2022-03-06T08:45:00',
       '2022-03-06T09:00:00', '2022-03-06T09:15:00',
       '2022-03-06T09:30:00', '2022-03-06T09:45:00',
       '2022-03-06T10:00:00', '2022-03-06T10:15:00',
       '2022-03-06T10:30:00', '2022-03-06T10:45:00',
       '2022-03-06T11:00:00', '2022-03-06T11:15:00',
       '2022-03-06T11:30:00', '2022-03-06T11:45:00',
       '2022-03-06T12:00:00', '2022-03-06T12:15:00',
       '2022-03-06T12:30:00', '2022-03-06T12:45:00',
       '2022-03-06T13:00:00', '2022-03-06T13:15:00',
       '2022-03-06T13:30:00', '2022-03-06T13:45:00',
       '2022-03-06T14:00:00', '2022-03-06T14:15:00',
       '2022-03-06T14:30:00', '2022-03-06T14:45:00',
       '2022-03-06T15:00:00', '2022-03-06T15:15:00',
       '2022-03-06T15:30:00', '2022-03-06T15:45:00',
       '2022-03-06T16:00:00', '2022-03-06T16:15:00',
       '2022-03-06T16:30:00', '2022-03-06T16:45:00',
       '2022-03-06T17:00:00', '2022-03-06T17:15:00',
       '2022-03-06T17:30:00', '2022-03-06T17:45:00',
       '2022-03-06T18:00:00', '2022-03-06T18:15:00',
       '2022-03-06T18:30:00', '2022-03-06T18:45:00',
       '2022-03-06T19:00:00', '2022-03-06T19:15:00',
       '2022-03-06T19:30:00', '2022-03-06T19:45:00',
       '2022-03-06T20:00:00', '2022-03-06T20:15:00',
       '2022-03-06T20:30:00', '2022-03-06T20:45:00',
       '2022-03-06T21:00:00', '2022-03-06T21:15:00',
       '2022-03-06T21:30:00', '2022-03-06T21:45:00',
       '2022-03-06T22:00:00', '2022-03-06T22:15:00',
       '2022-03-06T22:30:00', '2022-03-06T22:45:00',
       '2022-03-06T23:00:00', '2022-03-06T23:15:00',
       '2022-03-06T23:30:00', '2022-03-06T23:45:00',
       '2022-03-07T00:00:00', '2022-03-07T00:15:00',
       '2022-03-07T00:30:00', '2022-03-07T00:45:00',
       '2022-03-07T01:00:00', '2022-03-07T01:15:00',
       '2022-03-07T01:30:00', '2022-03-07T01:45:00',
       '2022-03-07T02:00:00', '2022-03-07T02:15:00',
       '2022-03-07T02:30:00', '2022-03-07T02:45:00',
       '2022-03-07T03:00:00', '2022-03-07T03:15:00',
       '2022-03-07T03:30:00', '2022-03-07T03:45:00',
       '2022-03-07T04:00:00', '2022-03-07T04:15:00',
       '2022-03-07T04:30:00', '2022-03-07T04:45:00',
       '2022-03-07T05:00:00', '2022-03-07T05:15:00',
       '2022-03-07T05:30:00', '2022-03-07T05:45:00',
       '2022-03-07T06:00:00', '2022-03-07T06:15:00',
       '2022-03-07T06:30:00', '2022-03-07T06:45:00',
       '2022-03-07T07:00:00', '2022-03-07T07:15:00',
       '2022-03-07T07:30:00', '2022-03-07T07:45:00',
       '2022-03-07T08:00:00', '2022-03-07T08:15:00',
       '2022-03-07T08:30:00', '2022-03-07T08:45:00',
       '2022-03-07T09:00:00', '2022-03-07T09:15:00',
       '2022-03-07T09:30:00', '2022-03-07T09:45:00',
       '2022-03-07T10:00:00', '2022-03-07T10:15:00',
       '2022-03-07T10:30:00', '2022-03-07T10:45:00',
       '2022-03-07T11:00:00', '2022-03-07T11:15:00',
       '2022-03-07T11:30:00', '2022-03-07T11:45:00',
       '2022-03-07T12:00:00', '2022-03-07T12:15:00',
       '2022-03-07T12:30:00', '2022-03-07T12:45:00',
       '2022-03-07T13:00:00', '2022-03-07T13:15:00',
       '2022-03-07T13:30:00', '2022-03-07T13:45:00',
       '2022-03-07T14:00:00', '2022-03-07T14:15:00',
       '2022-03-07T14:30:00', '2022-03-07T14:45:00',
       '2022-03-07T15:00:00', '2022-03-07T15:15:00',
       '2022-03-07T15:30:00', '2022-03-07T15:45:00',
       '2022-03-07T16:00:00', '2022-03-07T16:15:00',
       '2022-03-07T16:30:00', '2022-03-07T16:45:00',
       '2022-03-07T17:00:00', '2022-03-07T17:15:00',
       '2022-03-07T17:30:00', '2022-03-07T17:45:00',
       '2022-03-07T18:00:00', '2022-03-07T18:15:00',
       '2022-03-07T18:30:00', '2022-03-07T18:45:00',
       '2022-03-07T19:00:00', '2022-03-07T19:15:00',
       '2022-03-07T19:30:00', '2022-03-07T19:45:00',
       '2022-03-07T20:00:00', '2022-03-07T20:15:00',
       '2022-03-07T20:30:00', '2022-03-07T20:45:00',
       '2022-03-07T21:00:00', '2022-03-07T21:15:00',
       '2022-03-07T21:30:00', '2022-03-07T21:45:00',
       '2022-03-07T22:00:00', '2022-03-07T22:15:00',
       '2022-03-07T22:30:00', '2022-03-07T22:45:00',
       '2022-03-07T23:00:00', '2022-03-07T23:15:00',
       '2022-03-07T23:30:00', '2022-03-07T23:45:00',
       '2022-03-08T00:00:00', '2022-03-08T00:15:00',
       '2022-03-08T00:30:00', '2022-03-08T00:45:00',
       '2022-03-08T01:00:00', '2022-03-08T01:15:00',
       '2022-03-08T01:30:00', '2022-03-08T01:45:00',
       '2022-03-08T02:00:00', '2022-03-08T02:15:00',
       '2022-03-08T02:30:00', '2022-03-08T02:45:00',
       '2022-03-08T03:00:00', '2022-03-08T03:15:00',
       '2022-03-08T03:30:00', '2022-03-08T03:45:00',
       '2022-03-08T04:00:00', '2022-03-08T04:15:00',
       '2022-03-08T04:30:00', '2022-03-08T04:45:00',
       '2022-03-08T05:00:00', '2022-03-08T05:15:00',
       '2022-03-08T05:30:00', '2022-03-08T05:45:00',
       '2022-03-08T06:00:00', '2022-03-08T06:15:00',
       '2022-03-08T06:30:00', '2022-03-08T06:45:00',
       '2022-03-08T07:00:00', '2022-03-08T07:15:00',
       '2022-03-08T07:30:00', '2022-03-08T07:45:00',
       '2022-03-08T08:00:00', '2022-03-08T08:15:00',
       '2022-03-08T08:30:00', '2022-03-08T08:45:00',
       '2022-03-08T09:00:00', '2022-03-08T09:15:00',
       '2022-03-08T09:30:00', '2022-03-08T09:45:00',
       '2022-03-08T10:00:00', '2022-03-08T10:15:00',
       '2022-03-08T10:30:00', '2022-03-08T10:45:00',
       '2022-03-08T11:00:00', '2022-03-08T11:15:00',
       '2022-03-08T11:30:00', '2022-03-08T11:45:00',
       '2022-03-08T12:00:00', '2022-03-08T12:15:00',
       '2022-03-08T12:30:00', '2022-03-08T12:45:00',
       '2022-03-08T13:00:00', '2022-03-08T13:15:00',
       '2022-03-08T13:30:00', '2022-03-08T13:45:00',
       '2022-03-08T14:00:00', '2022-03-08T14:15:00',
       '2022-03-08T14:30:00', '2022-03-08T14:45:00',
       '2022-03-08T15:00:00', '2022-03-08T15:15:00',
       '2022-03-08T15:30:00', '2022-03-08T15:45:00',
       '2022-03-08T16:00:00', '2022-03-08T16:15:00',
       '2022-03-08T16:30:00', '2022-03-08T16:45:00',
       '2022-03-08T17:00:00', '2022-03-08T17:15:00',
       '2022-03-08T17:30:00', '2022-03-08T17:45:00',
       '2022-03-08T18:00:00', '2022-03-08T18:15:00',
       '2022-03-08T18:30:00', '2022-03-08T18:45:00',
       '2022-03-08T19:00:00', '2022-03-08T19:15:00',
       '2022-03-08T19:30:00', '2022-03-08T19:45:00',
       '2022-03-08T20:00:00', '2022-03-08T20:15:00',

In [59]:
maggia_2022_2024.shape

(21960, 241, 221)

In [60]:
print(len(maggia_2022_2024.tolist()))
print(len(maggia_2022_2024[0].tolist()))
print(len(maggia_2022_2024[0][0].tolist()))

21960
241
221

In [61]:
maggia_2022.shape

(9216, 241, 221)

In [62]:
maggia_2024.shape

(12744, 241, 221)

In [63]:
maggia_datetimes_2022 = np.array([d for d in maggia_datetimes_2022_2024 if d.astype(object).year == 2022])

In [64]:
len(maggia_datetimes_2022)

9216

In [65]:
maggia_datetimes_2024 = np.array([d for d in maggia_datetimes_2022_2024 if d.astype(object).year == 2024])

In [66]:
len(maggia_datetimes_2024)

12744

In [67]:
maggia_datetimes_2022_2024[0:12]

array(['2022-03-01T00:00:00', '2022-03-01T00:15:00',
       '2022-03-01T00:30:00', '2022-03-01T00:45:00',
       '2022-03-01T01:00:00', '2022-03-01T01:15:00',
       '2022-03-01T01:30:00', '2022-03-01T01:45:00',
       '2022-03-01T02:00:00', '2022-03-01T02:15:00',
       '2022-03-01T02:30:00', '2022-03-01T02:45:00'],
      dtype='datetime64[s]')

In [68]:
len(maggia_datetimes_2022_2024[0:12])

12

In [69]:
len(maggia_2022_2024[0:12])

12

In [70]:
maggia_2022_2024_shaped = np.reshape(maggia_2022_2024, (-1, 241, 221))

In [71]:
np.shape(maggia_2022_2024_shaped)

(21960, 241, 221)

In [72]:
np.shape(maggia_2022_2024_shaped.tolist())

(21960, 241, 221)

In [73]:
maggia_datetimes_2022_2024.shape

(21960,)

## Create dataframe

In [74]:
import pandas as pd

data = {
    'DATETIME': maggia_datetimes_2022_2024,
    'TECMAP': maggia_2022_2024_shaped.tolist()
}

df_maggia_maps_2022_2024 = pd.DataFrame(data)

df_maggia_maps_2022_2024

                 DATETIME                                             TECMAP
0     2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
1     2022-03-01 00:15:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2     2022-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
3     2022-03-01 00:45:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
4     2022-03-01 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                   ...                                                ...
21955 2024-12-30 23:10:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
21956 2024-12-30 23:20:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
21957 2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
21958 2024-12-30 23:40:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
21959 2024-12-30 23:50:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[21960 rows x 2 columns]

In [75]:
df_maggia_maps_2022_2024['DATETIME'] = pd.to_datetime(df_maggia_maps_2022_2024['DATETIME'])

df_maggia_maps_2022_2024.set_index('DATETIME', inplace=True)

In [76]:
# df_maggia_maps_2022_2024.to_pickle("./df_maggia_maps_2022_2024.pkl")

In [77]:
# from google.colab import drive
# drive.mount('/content/drive')

In [78]:
# %cp df_maggia_maps_2022_2024.pkl /content/drive/MyDrive/df_maggia_maps_2022_2024.pkl

In [79]:
df_maggia_maps_2022_2024 = df_maggia_maps_2022_2024[(df_maggia_maps_2022_2024.index.minute == 0) & (df_maggia_maps_2022_2024.index.hour % 2 == 0)]

df120 = df_maggia_maps_2022_2024[
    ((df_maggia_maps_2022_2024.index.year == 2022) & (df_maggia_maps_2022_2024.index.month.isin([3, 6, 9]))) |
    ((df_maggia_maps_2022_2024.index.year == 2024) & (df_maggia_maps_2022_2024.index.month.isin([3, 6, 9, 12])))
]

df30 = pd.DataFrame(data)

df30['DATETIME'] = pd.to_datetime(df30['DATETIME'])

df30.set_index('DATETIME', inplace=True)

df30 = df30[
    ((df30.index.year == 2024) & (df30.index.month.isin([3, 6, 9, 12])))
]

df30 = df30[df30.index.minute % 30 == 0]

print("DF 120:")
print(df120)

print("DF 30:")
print(df30)

DF 120:
                                                                TECMAP
DATETIME
2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 06:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 14:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 18:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[2196 rows x 1 columns]
DF 30:
                                                                TECMAP
DATETIME
2024-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 01:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 21:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[5088 rows x 1 columns]

In [80]:
df_maggia_maps_2022_2024 = df_maggia_maps_2022_2024[(df_maggia_maps_2022_2024.index.minute == 0) & (df_maggia_maps_2022_2024.index.hour % 2 == 0)]

In [81]:
np.array(df_maggia_maps_2022_2024.iloc[0]['TECMAP'])

array([[        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,

In [82]:
np.array(df_maggia_maps_2022_2024.iloc[0]['TECMAP']).shape

(241, 221)

In [83]:
maps = np.array(df_maggia_maps_2022_2024.iloc[:]['TECMAP'])

In [84]:
np.shape(df_maggia_maps_2022_2024)

(2424, 1)

In [85]:
np_maps = []
for i in range(len(maps)):
    np_maps.append(maps[i])
np_maps = np.array(np_maps)

In [86]:
np.shape(np_maps)

(2424, 241, 221)

In [87]:
type(np_maps)

numpy.ndarray

In [88]:
df_maggia_maps_2022_2024_0800 = df_maggia_maps_2022_2024.between_time('08:00', '08:00')

df_maggia_maps_2022_2024_1600 = df_maggia_maps_2022_2024.between_time('16:00', '16:00')

df_maggia_maps_2022_2024_2000_2200_0000_0200_0400 = pd.concat([
    df_maggia_maps_2022_2024.between_time('20:00', '20:00'),
    df_maggia_maps_2022_2024.between_time('22:00', '22:00'),
    df_maggia_maps_2022_2024.between_time('00:00', '00:00'),
    df_maggia_maps_2022_2024.between_time('02:00', '02:00'),
    df_maggia_maps_2022_2024.between_time('04:00', '04:00')
])

print("Data from 08:00:")
print(df_maggia_maps_2022_2024_0800)

print("\nData from 16:00:")
print(df_maggia_maps_2022_2024_1600)

print("\nData from 20:00 to 04:00:")
print(df_maggia_maps_2022_2024_2000_2200_0000_0200_0400)

Data from 08:00:
                                                                TECMAP
DATETIME
2022-03-01 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-02 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-03 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-04 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-05 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[202 rows x 1 columns]

Data from 16:00:
                                                                TECMAP
DATETIME
2022-03-01 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-02 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-03 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-04 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-05 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[202 rows x 1 columns]

Data from 20:00 to 04:00:
                                                                TECMAP
DATETIME
2022-03-01 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-02 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-03 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-04 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-05 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[1010 rows x 1 columns]

In [89]:
np.shape(np.array(df_maggia_maps_2022_2024_0800.iloc[:]['TECMAP']))

(202,)

In [90]:
maggia_maps_2022_2024_0800 = np.array(df_maggia_maps_2022_2024_0800.iloc[:]['TECMAP'])

In [91]:
np.shape(maggia_maps_2022_2024_0800)

(202,)

In [92]:
np_maggia_maps_2022_2024_0800 = []
for i in range(len(maggia_maps_2022_2024_0800)):
    np_maggia_maps_2022_2024_0800.append(maggia_maps_2022_2024_0800[i])
np_maggia_maps_2022_2024_0800 = np.array(np_maggia_maps_2022_2024_0800)

In [93]:
np.shape(np_maggia_maps_2022_2024_0800)

(202, 241, 221)

In [94]:
type(np_maggia_maps_2022_2024_0800)

numpy.ndarray

In [95]:
maggia_maps_2022_2024_1600 = np.array(df_maggia_maps_2022_2024_1600.iloc[:]['TECMAP'])

In [96]:
np.shape(maggia_maps_2022_2024_1600)

(202,)

In [97]:
np_maggia_maps_2022_2024_1600 = []
for i in range(len(maggia_maps_2022_2024_1600)):
    np_maggia_maps_2022_2024_1600.append(maggia_maps_2022_2024_1600[i])
np_maggia_maps_2022_2024_1600 = np.array(np_maggia_maps_2022_2024_1600)

In [98]:
np.shape(np_maggia_maps_2022_2024_1600)

(202, 241, 221)

In [99]:
type(np_maggia_maps_2022_2024_1600)

numpy.ndarray

In [100]:
maggia_maps_2022_2024_2000_2200_0000_0200_0400 = np.array(df_maggia_maps_2022_2024_2000_2200_0000_0200_0400.iloc[:]['TECMAP'])

In [101]:
np.shape(maggia_maps_2022_2024_2000_2200_0000_0200_0400)

(1010,)

In [102]:
np.shape(maggia_maps_2022_2024_2000_2200_0000_0200_0400[0])

(241, 221)

In [103]:
np_maggia_maps_2022_2024_2000_2200_0000_0200_0400 = []
for i in range(len(maggia_maps_2022_2024_2000_2200_0000_0200_0400)):
    np_maggia_maps_2022_2024_2000_2200_0000_0200_0400.append(maggia_maps_2022_2024_2000_2200_0000_0200_0400[i])
np_maggia_maps_2022_2024_2000_2200_0000_0200_0400 = np.array(np_maggia_maps_2022_2024_2000_2200_0000_0200_0400)

In [104]:
np.shape(np_maggia_maps_2022_2024_2000_2200_0000_0200_0400)

(1010, 241, 221)

In [105]:
type(np_maggia_maps_2022_2024_2000_2200_0000_0200_0400)

numpy.ndarray

# TF-120 adjusts

## Continuous

In [106]:
np.array(df120.iloc[0]['TECMAP'])

array([[        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,

In [107]:
np.array(df120.iloc[0]['TECMAP']).shape

(241, 221)

In [108]:
df120_0800 = df120.between_time('08:00', '08:00')

df120_1600 = df120.between_time('16:00', '16:00')

df120_2000_2200_0000_0200_0400 = pd.concat([
    df120.between_time('20:00', '20:00'),
    df120.between_time('22:00', '22:00'),
    df120.between_time('00:00', '00:00'),
    df120.between_time('02:00', '02:00'),
    df120.between_time('04:00', '04:00')
])

df120_2000_2200_0000_0200_0400.sort_index(inplace=True)

print("Data from 08:00:")
print(df120_0800)

print("\nData from 16:00:")
print(df120_1600)

print("\nData from 20:00 to 04:00:")
print(df120_2000_2200_0000_0200_0400)

Data from 08:00:
                                                                TECMAP
DATETIME
2022-03-01 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-02 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-03 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-04 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-05 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[183 rows x 1 columns]

Data from 16:00:
                                                                TECMAP
DATETIME
2022-03-01 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-02 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-03 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-04 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-05 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[183 rows x 1 columns]

Data from 20:00 to 04:00:
                                                                TECMAP
DATETIME
2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[915 rows x 1 columns]

In [109]:
np.shape(np.array(df120.iloc[:]['TECMAP']))

(2196,)

In [110]:
maps120 = np.array(df120.iloc[:]['TECMAP'])

In [111]:
np.shape(df120)

(2196, 1)

In [112]:
np_maps120 = []
for i in range(len(maps120)):
    np_maps120.append(maps120[i])
np_maps120 = np.array(np_maps120)

In [113]:
np.shape(np_maps120)

(2196, 241, 221)

In [114]:
type(np_maps120)

numpy.ndarray

## 08:00 UT

In [115]:
# df120_0800.to_pickle("./TF_120_MAGGIA_TEC_maps_0800.pkl")

In [116]:
df120_0800

                                                                TECMAP
DATETIME
2022-03-01 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-02 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-03 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-04 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-05 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[183 rows x 1 columns]

In [117]:
np.shape(np.array(df120_0800.iloc[:]['TECMAP']))

(183,)

In [118]:
maps120_0800 = np.array(df120_0800.iloc[:]['TECMAP'])

In [119]:
np.shape(df120_0800)

(183, 1)

In [120]:
np_maps120_0800 = []
for i in range(len(maps120_0800)):
    np_maps120_0800.append(maps120_0800[i])
np_maps120_0800 = np.array(np_maps120_0800)

In [121]:
np.shape(np_maps120_0800)

(183, 241, 221)

In [122]:
type(np_maps120_0800)

numpy.ndarray

In [123]:
np.save('TF_120_MAGGIA_TEC_maps_0800.npy', np_maps120_0800)

## 16:00 UT

In [124]:
# df120_1600.to_pickle("./TF_120_MAGGIA_TEC_maps_1600.pkl")

In [125]:
df120_1600

                                                                TECMAP
DATETIME
2022-03-01 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-02 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-03 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-04 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-05 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[183 rows x 1 columns]

In [126]:
maps120_1600 = np.array(df120_1600.iloc[:]['TECMAP'])

In [127]:
np.shape(maps120_1600)

(183,)

In [128]:
np_maps120_1600 = []
for i in range(len(maps120_1600)):
    np_maps120_1600.append(maps120_1600[i])
np_maps120_1600 = np.array(np_maps120_1600)

In [129]:
np.shape(np_maps120_1600)

(183, 241, 221)

In [130]:
type(np_maps120_1600)

numpy.ndarray

In [131]:
np.save('TF_120_MAGGIA_TEC_maps_1600.npy', np_maps120_1600)

## 20:00 to 04:00 UT

In [132]:
# df120_2000_2200_0000_0200_0400.to_pickle("./TF_120_MAGGIA_TEC_maps_2000_0400.pkl")

In [133]:
df120_2000_2200_0000_0200_0400

                                                                TECMAP
DATETIME
2022-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2022-03-01 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 04:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 20:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[915 rows x 1 columns]

In [134]:
maps120_2000_2200_0000_0200_0400 = np.array(df120_2000_2200_0000_0200_0400.iloc[:]['TECMAP'])

In [135]:
np.shape(maps120_2000_2200_0000_0200_0400)

(915,)

In [136]:
np_maps120_2000_2200_0000_0200_0400 = []
for i in range(len(maps120_2000_2200_0000_0200_0400)):
    np_maps120_2000_2200_0000_0200_0400.append(maps120_2000_2200_0000_0200_0400[i])
np_maps120_2000_2200_0000_0200_0400 = np.array(np_maps120_2000_2200_0000_0200_0400)

In [137]:
np.shape(np_maps120_2000_2200_0000_0200_0400)

(915, 241, 221)

In [138]:
type(np_maps120_2000_2200_0000_0200_0400)

numpy.ndarray

In [139]:
np.save('TF_120_MAGGIA_TEC_maps_2000_0400.npy', np_maps120_2000_2200_0000_0200_0400)

# TF-30 adjusts

## Continuous

In [140]:
np.array(df30.iloc[0]['TECMAP'])

array([[        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan, 29.19245529,
        29.16289902, 29.13293266, 29.1021347 , 29.07084656, 29.03940582,
        29.00844574, 28.97759628, 28.94726562, 28.91657639, 28.88419914,
        28.85160446, 28.81997871, 28.78832054, 28.75436783, 28.72020149,
        28.68587875, 28.65161705, 28.61681557, 28.58413506, 28.54804039,
        28.51281548, 28.47684097, 28.44067574, 28.40324593, 28.36456299,
        28.32641029, 28.28850555, 28.2497654 , 28.21327591, 28.17460442,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan, 29.16903305,
        29.13772774, 29.10786438, 29.07734871, 29.04509354, 29.01291847,
        28.98102188, 28.9487133 , 28.91672134, 28.8832283 , 28.84972191,
        28.8158741 , 28.78203964, 28.74763107, 28.71363068, 28.68289566,
        28.64789581, 28.61147881, 28.57551193, 28.53783798, 28.49993896,
        28.46294022, 28.4259243 , 28.38984489, 28.352314  , 28.3136158 ,
        28.27323532, 28.23356438, 28.19355774, 28.15424538, 28.11417389,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan, 29.1431427 ,
        29.11089134, 29.07867813, 29.04538345, 29.01530838, 28.98484039,
        28.95203209, 28.91919518, 28.8869648 , 28.85316658, 28.81925201,
        28.78516006, 28.75289917, 28.71718407, 28.67956161, 28.64211845,
        28.60524368, 28.56861687, 28.53100777, 28.4933815 , 28.45523834,
        28.41675949, 28.37661552, 28.33709717, 28.29640388, 28.25575638,
        28.21762848, 28.17561913, 28.13315201, 28.0902195 , 28.04650116,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan, 29.11481476,
        29.08316422, 29.05077362, 29.01870346, 28.98737717, 28.95564461,
        28.92344284, 28.89101219, 28.85762215, 28.82561684, 28.79034424,
        28.75393677, 28.71852493, 28.68210793, 28.64557266, 28.60818291,
        28.57085609, 28.53261185, 28.49218369, 28.45260048, 28.41215324,
        28.37131882, 28.32900047, 28.28776741, 28.2463398 , 28.20390892,
        28.1602459 , 28.11653137, 28.07252502, 28.02725029, 27.98180771,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan, 29.0875473 ,
        29.05623627, 29.02459908, 28.99409866, 28.96178818, 28.92850876,
        28.89548302, 28.86317825, 28.826828  , 28.79150581, 28.75518036,
        28.71927071, 28.68214035, 28.64475632, 28.60570335, 28.56669426,
        28.5262928 , 28.48762894, 28.44730949, 28.40790939, 28.36875343,
        28.32735634, 28.28684616, 28.24318886, 28.19975281, 28.15586472,
        28.11013603, 28.06365395, 28.01659393, 27.97097015, 27.92314529,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan, 29.05294418,
        29.02124977, 28.9891243 , 28.95644951, 28.92291069, 28.89056206,
        28.85910606, 28.82458878, 28.78972626, 28.75379753, 28.71745872,
        28.68096924, 28.64298058, 28.60542488, 28.56581688, 28.52701187,
        28.48634338, 28.44521904, 28.40596962, 28.36481667, 28.32147789,
        28.27991104, 28.23495865, 28.1920681 , 28.1464138 , 28.0999279 ,
        28.05285835, 28.00559998, 27.95768166, 27.90777206, 27.85728264,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,

In [141]:
np.array(df30.iloc[0]['TECMAP']).shape

(241, 221)

In [142]:
df30_0800 = df30.between_time('08:00', '08:00')

df30_1600 = df30.between_time('16:00', '16:00')

df30_2000_0400 = pd.concat([
    df30.between_time('20:00', '20:00'),
    df30.between_time('20:30', '20:30'),
    df30.between_time('21:00', '21:00'),
    df30.between_time('21:30', '21:30'),
    df30.between_time('22:00', '22:00'),
    df30.between_time('22:30', '22:30'),
    df30.between_time('23:00', '23:00'),
    df30.between_time('23:30', '23:30'),
    df30.between_time('00:00', '00:00'),
    df30.between_time('00:30', '00:30'),
    df30.between_time('01:00', '01:00'),
    df30.between_time('01:30', '01:30'),
    df30.between_time('02:00', '02:00'),
    df30.between_time('02:30', '02:30'),
    df30.between_time('03:00', '03:00'),
    df30.between_time('03:30', '03:30'),
    df30.between_time('04:00', '04:00')
])

df30_2000_0400.sort_index(inplace=True)

print("Data from 08:00:")
print(df30_0800)

print("\nData from 16:00:")
print(df30_1600)

print("\nData from 20:00 to 04:00:")
print(df30_2000_0400)

Data from 08:00:
                                                                TECMAP
DATETIME
2024-03-01 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-02 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-03 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-04 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-05 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[106 rows x 1 columns]

Data from 16:00:
                                                                TECMAP
DATETIME
2024-03-01 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-02 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-03 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-04 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-05 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[106 rows x 1 columns]

Data from 20:00 to 04:00:
                                                                TECMAP
DATETIME
2024-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 01:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 21:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[1802 rows x 1 columns]

In [143]:
np.shape(np.array(df30.iloc[:]['TECMAP']))

(5088,)

In [144]:
maps30 = np.array(df30.iloc[:]['TECMAP'])

In [145]:
np.shape(df30)

(5088, 1)

In [146]:
np_maps30 = []
for i in range(len(maps30)):
    np_maps30.append(maps30[i])
np_maps30 = np.array(np_maps30)

In [147]:
np.shape(np_maps30)

(5088, 241, 221)

In [148]:
type(np_maps30)

numpy.ndarray

## 08:00 UT

In [149]:
# df30_0800.to_pickle("./TF_30_MAGGIA_TEC_maps_2024_0800.pkl")

In [150]:
df30_0800

                                                                TECMAP
DATETIME
2024-03-01 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-02 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-03 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-04 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-05 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 08:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[106 rows x 1 columns]

In [151]:
np.shape(np.array(df30_0800.iloc[:]['TECMAP']))

(106,)

In [152]:
maps30_0800 = np.array(df30_0800.iloc[:]['TECMAP'])

In [153]:
np.shape(df30_0800)

(106, 1)

In [154]:
np_maps30_0800 = []
for i in range(len(maps30_0800)):
    np_maps30_0800.append(maps30_0800[i])
np_maps30_0800 = np.array(np_maps30_0800)

In [155]:
np.shape(np_maps30_0800)

(106, 241, 221)

In [156]:
type(np_maps30_0800)

numpy.ndarray

In [157]:
# np.save('TF_30_MAGGIA_TEC_maps_2024_0800.npy', np_maps30_0800)

## 16:00 UT

In [158]:
# df30_1600.to_pickle("./TF_30_MAGGIA_TEC_maps_2024_1600.pkl")

In [159]:
df30_1600

                                                                TECMAP
DATETIME
2024-03-01 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-02 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-03 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-04 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-05 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-26 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-27 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-28 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-29 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 16:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[106 rows x 1 columns]

In [160]:
maps30_1600 = np.array(df30_1600.iloc[:]['TECMAP'])

In [161]:
np.shape(maps30_1600)

(106,)

In [162]:
np_maps30_1600 = []
for i in range(len(maps30_1600)):
    np_maps30_1600.append(maps30_1600[i])
np_maps30_1600 = np.array(np_maps30_1600)

In [163]:
np.shape(np_maps30_1600)

(106, 241, 221)

In [164]:
type(np_maps30_1600)

numpy.ndarray

In [165]:
# np.save('TF_30_MAGGIA_TEC_maps_2024_1600.npy', np_maps30_1600)

## 20:00 to 04:00 UT

In [166]:
# df30_2000_0400.to_pickle("./TF_30_MAGGIA_TEC_maps_2024_2000_0400.pkl")

In [167]:
df30_2000_0400

                                                                TECMAP
DATETIME
2024-03-01 00:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 00:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 01:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 01:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-03-01 02:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
...                                                                ...
2024-12-30 21:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 22:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:00:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...
2024-12-30 23:30:00  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...

[1802 rows x 1 columns]

In [168]:
maps30_2000_0400 = np.array(df30_2000_0400.iloc[:]['TECMAP'])

In [169]:
np.shape(maps30_2000_0400)

(1802,)

In [170]:
np_maps30_2000_0400 = []
for i in range(len(maps30_2000_0400)):
    np_maps30_2000_0400.append(maps30_2000_0400[i])
np_maps30_2000_0400 = np.array(np_maps30_2000_0400)

In [171]:
np.shape(np_maps30_2000_0400)

(1802, 241, 221)

In [172]:
type(np_maps30_2000_0400)

numpy.ndarray

In [173]:
np.save('TF_30_MAGGIA_TEC_maps_2024_2000_0400.npy', np_maps30_2000_0400)

# Download outputs

In [174]:
from google.colab import files

In [175]:
%pwd

'/content'

In [176]:
!ls df*

ls: cannot access 'df*': No such file or directory

In [177]:
!ls maggia*

ls: cannot access 'maggia*': No such file or directory

In [178]:
!ls -lh maggia*

ls: cannot access 'maggia*': No such file or directory

In [179]:
!ls -lh maps*.npy

ls: cannot access 'maps*.npy': No such file or directory

In [180]:
# files.download('./TF_120_MAGGIA_TEC_maps_0800.pkl')

In [181]:
# files.download('./TF_120_MAGGIA_TEC_maps_1600.pkl')

In [182]:
# files.download('./TF_120_MAGGIA_TEC_maps_2000_0400.pkl')

In [183]:
# files.download('./TF_30_MAGGIA_TEC_maps_0800.pkl')

In [184]:
# files.download('./TF_30_MAGGIA_TEC_maps_1600.pkl')

In [185]:
# files.download('./TF_30_MAGGIA_TEC_maps_2000_0400.pkl')

In [186]:
# from google.colab import drive
# drive.mount('/content/drive')

In [187]:
!ls -lh df30*

ls: cannot access 'df30*': No such file or directory

In [188]:
# %cp TF_30_MAGGIA_TEC_maps_0800.pkl /content/drive/MyDrive/TF_30_MAGGIA_TEC_maps_0800.pkl

In [189]:
# %cp TF_30_MAGGIA_TEC_maps_1600.pkl /content/drive/MyDrive/TF_30_MAGGIA_TEC_maps_1600.pkl

In [190]:
# %cp TF_30_MAGGIA_TEC_maps_2000_0400.pkl /content/drive/MyDrive/TF_30_MAGGIA_TEC_maps_2000_0400.pkl

In [191]:
!ls -lh maps30*

ls: cannot access 'maps30*': No such file or directory

In [192]:
# %cp TF_30_MAGGIA_TEC_maps_0800.npy /content/drive/MyDrive/TF_30_MAGGIA_TEC_maps_0800.npy

In [193]:
# %cp TF_30_MAGGIA_TEC_maps_1600.npy /content/drive/MyDrive/TF_30_MAGGIA_TEC_maps_1600.npy

In [194]:
# %cp TF_30_MAGGIA_TEC_maps_2000_0400.npy /content/drive/MyDrive/TF_30_MAGGIA_TEC_maps_2000_0400.npy